These are reviews of Cal.NET prior to their 2008 merger/restructuring. There is also an extensive (and angry) review of their 2004Cal.NET/Business and MDL Review 2004  business practices and service.  Please visit the Cal.NET entry to learn more about the new company.



20050831 19:15:58 nbsp They used to be pretty cool. They have gone downhill in recent years. Two years ago, when they were still giving their users shell accounts, sombody cracked their shell server (they were running a kernel vunerable to a local root exploit at the time) and installed a rootkit along with a password collector, which led to two of my computers getting cracked after I sshd to them from cal.nets shell server. It took cal.net a month after I complained before they rebuilt the box from backups. Users/RyanCastellucci

20060114 19:25:24 nbsp (Ill move this to body later, Ryan is editing page).  But something I forgot to mention: One reason tech support sucked was they kept notes.  Once they found out we had a router, it was the only thing theyd blame.  So anytime I called and gave our account name, they instantly said oh, you guys, well cant help because you guys use a router. etc.  Users/EdWins ES

20060114 22:04:41 nbsp Cal.Net comment.  I have used them for many years and while I have had ongoing problems I dont think it was always their fault.  The way I understand it, to have DSL service you must have a telephone land line.  If there is trouble with the telephone lines, there is trouble with the internet service.  I live near 14th and Oak St and have for 20+ years. There is a large phone box on 14th and I see the phone company van there so much I think they must live there.  There is splice between 14th and Covell that has corrosion and should be replaced and there is a splice in my back yard that causes bad, awful, lousy phone service whenever it gets wet.  Yes, friends, whenever it gets wet.  So Ill start blaming CalNet when someone explains how another provider could do better with the same lines to work with.  Then, if youve got someone else to recommend, Ill think about changing.  Also the tech people are pretty nice to me and I can usually talk to them without a wait. Users/BarbaraClowers

20060115 09:23:45 nbsp I used to live in Glacier Apts (which were horrible, by the way), where Cal.Net apparently had a monopoly on high speed internet.  I dont think Comcast (or any other highspeed ISP) was available there at the time (20032004).  I recall the Cal.Net service was shitty, much like just about everyone here said.  The service was supposed to be something like the dorms in terms of how it was set up, but seemed to me by all accounts that it was just some kind of shitty DSL service.  Needless to say, it was slow.  Im a big baseball fan, and I was interested in getting MLB.tv to work, but couldnt because the service wasnt fast enough.  Like others mentioned, I too recall router problems, to the extent that the service technician who installed the service told us specifically NOT to get one.  I laughed in his face, and got one anyway.

But sure enough, it was a strange installation.  Something about screwing around with numerous router/computer settings, I dont know, Im not a computer expert (although I think that it was more complicated than installing a router on a cable modem, which Ive done).  I do know that the router person that I talked to had trouble walking me through the steps to solve the problem, although Im not sure if that is a testament to idiocy of the router person, or the absurdity of the Cal.Net service.

Another thing I thought was strange: when me and my roommate at the time were going into their office to order the service, we could easily overhear the management in the back laughing at the customer that had just left the office, and making fun of the websites (apparently porno) that the person visited and how much bandwidth they took up.  I thought that was a bit uncouth, especially with customers plainly visible in their office, no matter how funny it may have been.  Users/JohnNapier

20060405 13:03:05 nbsp I am horribly upset with Cal.net right now. They charged me $263 three times on my bill (a triple charge!). The $263 charge was to lower my monthly bills to $25, but they are still charging me 440/month and gave me a triple charge to boot! I talked to Trish and she said that she would fix it, but she never did. I just contacted my VISA card company to get this one disputed. I have called the owner and the billing dept and they have not bothered to call me back. I have been a Cal.Net user from when they were Mother.Com about 10 years ago. I have never had such horrible service from them before. I think Im switching to Omsoft. Users/SherryOneal

20070130 18:17:52 nbsp The one time I have dealt with them, they didnt have a problem with us having a router, they just wouldnt support it. So if you know what you are doing and can fix your own problems, routers should not be an issue. Maybe this is different at apartment complexes where they are trying to screw over students though. Users/NickSchmalenberger

20070516 12:48:02 nbsp Their service is really not reliable. It worked good for the first 2 weeks and then had trouble connecting after that.
They will charge you $75 dollars an hour to come out and look at your computer and their tech Chris said he was not
going to charge me for installation because he was running late for my appointment and the next thing I know they
charged me a hundred dollars..would not recommend their services to anyone...Mv  Users/Michaelv

20070911 00:12:02 nbsp Great service.  Theyve never given us a hard time about our router.  Usually they have us turn off the router and DSL box for awhile just to make sure its not a problem on our end.  They have more outages than other ISPs but its usually been the telephone company or Comcast at fault.  If its a serious outage they will refund us.  Slow speeds and slightly high prices but great email and server space.  Im not sure about limited bandwidth.  It only applies to server space, not regular internet usage. Users/KevinRollins
