
Alexander P. Lee, also known as Officer O. in the redacted Reynoso report, wasan officer with the UC Davis Police Department. He gained notoriety for http://blogs.scientificamerican.com/guestblog/2011/11/21/aboutpepperspray/ pepper spraying peaceful, sitting protesters during the November 18, 2011 UC Davis Police Response to Occupy UC Davis UC Davis protest on Friday November 18, 2011 at the direction of John Pike. He had been known for some time as the second officer.

Lee, along with John Pike, is no longer a UC Davis police officer. Lees employment with the University ended on July 11, 2012.  The SacBee has revealed that Pike was fired; it is unknown how Lees employment ended. The Yolo County DAs office has yet to determine whether or not to file criminal charges against the officers.

Lee is an Aggie who graduated with an undergraduate degree in 2008. While Lee was a student, he worked for the police department for over two years as an Aggie Hosts Aggie Host. He was http://dateline.ucdavis.edu/dl_detail.lasso?id11116 recognized with an award his senior year. He returned to campus in 2010 as a security guard and was later hired on as a full police officer. Its likely that Lee was the least experienced officer present at the events of November 18.

The Vanguard http://davisvanguard.org/index.php?optioncom_content&viewarticle&id5197:releaseofthepeppersprayreportfurtherdelayed&catid63:lawenforcement&Itemid114 has http://davisvanguard.org/index.php?optioncom_content&viewarticle&id5216:battlelineslargelyremainthesameheadedtoatodayscourthearingonreleaseofpeppersprayreport&catid63:lawenforcement&Itemid114 implied that delay in releasing the Kroll/Reynoso report was partly due to shielding the name of this officer, even though it had been widely known and is now (with the publication of the Vanguards article) even more widely known.  It has also stated that the University of California is now arguing for the release of Alexander Lees name, since it is now part of the public record, citing the Vanguard release of the name as evidence.

His photo (the photo at right) first appeared on the Davis Wiki on 29 November 2011.  The photo clearly shows the name A. Lee.  Early research by a wiki gnome deduced that his name was probably Alexander P. Lee.  Additional evidence for this hypothesis http://davisvanguard.org/index.php?optioncom_content&viewarticle&id5213:vanguardidentifiessecondofficerinvolvedinpeppersprayingonnovember18&Itemid114 has now been provided by the Vanguard, which used the Davis Wikis information as a starting point; http://davisvanguard.org/index.php?optioncom_content&viewarticle&id5306:thetrailtodiscoveringthenameofofficeralexanderleeasthesecondpeppersprayer&Itemid114 this article explains the process that uncovered the evidence.  Once the Vanguard released Alexander Lees name, http://www.davisenterprise.com/localnews/crimefirecourts/ucdwontnamesecondpeppersprayofficer/ The Davis Enterprise revealed that it had had its own picture showing the name of A. Lee all along, that videos showed Lee pepperspraying protesters at close range, that the protesters had been chanting A. Lee, A. Lee, and that it had tried to obtain Lees full name but failed.  However, the Enterprise article refused to provide Lees first name, or even to name the blog or blogger that had forced its hand.
