

Amazing Tans is a chain retailer that provides Beauty Salons and Barber Shops tanning services. They have a variety of tanning booth styles including facial tanning beds and stand up options. Amazing Tans caters to any skin type and provides Sun Protection sunless tanning as well as UV. An array of tanning lotions are available for purchase. Services can be purchased as part of package deals, or on a membership basis.

  To learn about other businesses in Davis that provide professional aesthetic services, visit our Beauty Salons and Barber Shops page.


20060310 18:29:34 nbsp a little on the pricy side, but its definitely worth it. i have been tanning for years in my home town and usually start out at 10 minutes my first time (im really fair skinned). well, today i went for the first time to amazing tans and they suggested i start out at 6 minutes. at first i was a little skeptical since i have always started at 10 and never really saw any difference. wow was i wrong! their beds are amazing. i have never gotten so much color in a first session. the girl at the front counter was also really friendly and helpful. i would recommend them! Users/CorinneEpley

20060409 17:16:16 nbsp This place is really nice.  They have monthly plans and tan packages.  In the summer, they sometimes have a deal where you just pay a flat amount and can tan (at level 1) unlimitedly until the end of they year.  The people working there are usually very friendly and informative.  I would definitely recommend this place. Users/CatLa

20070316 13:47:57 nbsp Amazing tans now has a sign in the window asking patrons to notify the manager if the store is closed during posted business hours.  Anyone know if this is in response to recent problems or complaints? Users/DavidGrundler
  Not in response to anything in particular.  Just a standard business sign.

20070405 13:22:01 nbsp WOW!!! The girls there know their stuff.  I never knew there was so much to learn about tanning beds, lotions etc.  Great customer service! A bit pricey, but I guess you get what you pay for!  Users/Jessica

20080308 09:55:06 nbsp Great customer service. On the days I just wanted to get in the tanning beds they did just that. On the days I had questions, they answered them better than I expected. They were very helpful, but it was the most I ever paid to tanning. If you are pale, it sucks because its cheaper if you pay for a certain amount of tans. So someone who tans for 15 minutes pays the same price as someone tanning for 5. I got my base before, so it wasnt too bad Users/lv

20080428 10:26:29 nbsp The place is pretty cool, and they treat dudes fine (I am not the only one I see there). You have to really work their deals though, they are extremly tricky and will NOT give you any kind of price list (cell phone camera anyone? Its the only way. Ive talked to their corporate office and its the same runaround). As with all tanning salons, its really only worth it to go with the most expensive beds, otherwise you will just get burned. Also, DONT get pressured into buying their lotions! What costs 100 bucks there is less than 40 on amazon, 25 on eBay, and so on. All in all though I cant complain, it is very convenient and my GF is not complaining either.  Users/YesItsMe
  20090721 18:35:10 nbsp I just went in to start tanning.  The girl showed me all the beds and how long it would take to get a base tan, etc.  They had a price list on the counter. I didnt get tricked into anything.  She was very straightforward and VERY nice.  No sales pressure at all. Glad I chose to go here.  Users/EricaMacGregor

20080516 13:57:18 nbsp Girls here are far nicer than at the other tanning place in Davis and more helpful. Wait is never too long for a bed. Yes, it is expensive, but worth it.  Users/tgdavis

20080928 13:10:42 nbsp not really sure why people saw this place is expensive!! it is far more reasonable than any other place in town! 5 bucks for 1 tan!!!! cant get better then that and memberships at 20$ a month unlimited...what is expensive?!?! love the employees, love the services! Users/sara87

20081031 14:50:11 nbsp I love the girls at amazing tans... great service, great beds, they arent too pushy, and overall a great tanning salon... Users/meaghan

20090309 00:02:09 nbsp Love this place! In response to the note on lotions, take a look at the ingredients on the back, you get what you pay for! When youre drying out your skin and aging yourself in the tanning process, dont skimp out on lotion. It will help save your tan and keep your skin soft in the process! Many of the lotions also have a ton of bronzers (DHA)! Save your skin people! Get a great lotion! Im loving mine!:) Users/allsmiles

20091011 10:54:23 nbsp Amazing Tans is great! I love this place. I believe they have the best prices in town, and it may be one of their guarantees to beat any other tanning salon prices (dont quote me on that). The girls that work there are all super knowledgeable, friendly and nice (with the exception with one girl I had to deal with.) If you plan on tanning at least once a week, I recommend getting a VIP membership. I pay $24.88 a month for unlimited tans in a level 1 bed and upgrades to higher level beds are cheap! The lotions are super expensive but they do have sales on them occasionally and the bottles are huge and will last for months. Friendly staff, relaxing atmosphere, best place to tan!  Users/MillaMi

20091028 15:12:57 nbsp Was about to go to prom last year...went here to get a spray on tan. Have had great first time experiences at other places, so I wasnt worried. The tan turned out awful, terribly streaky, and there were drips down my legs. Same experience for my two friends. We went back to try and get our money back, they wouldnt return it and told us that it happens every first time, and we had to come back multiple times to have it look good. Thanks for telling us! Wouldnt recommend the spray tans here.  Users/KB@CSUMB

20110129 12:35:10 nbsp AVOID AT ALL COSTS!!! Everything is nice at first, besides being wayyy overpriced, but attempting to end a membership is IMPOSSIBLE. First, there is a rule that you have to come in and quit in writing by signing a form. Then the policy is to charge you for a full month after you originally want to quit. However, I was suckered into the Stay and Save Plan, the manager told me if I signed a paper and paid $5 a month, then if I ever wanted to come back I wouldnt have to pay a new sign up fee (another one of their millions of fees). She told me there was no downside and I could end the Stay and Save program at any time. So I signed it, paid my last month fee (a month more than I wanted to stay, because of the policy) and paid the $5 a month for about 5 months. After this time, money was tight and I wanted out all together. To my despair, I found out that in the fine print it says that to get off the Stay and Save Plan, you have to pay another full price month (about $70). If I knew that I would not have consented to the Stay and Save plan. There was a change in management and the new manager said that even though the old manager had LIED to me and said that there would be no additional fees and that my last month was paid for back when I first signed the Stay and Save plan, she told me there is nothing she can do. I swallowed the bullet  resigned to pay. (and I promised myself I would never sign anything again without reading every word and never trust anyone who gives me their word on what it says) So I went in to try to pay and quit but the employee there told me the manager was not in and that she had taken my forms home with her. Long story short, I am going in today for the 3rd time to try to pay and quit, praying I will be successful. By the way the manager left me a voicemail that I have to make it in by 3 pm today because that is what time she leaves. So I have to adjust my schedule and make it in or I will be locked into paying Amazing Tans huge amounts of money forever. (So considerate, accommodating, and great customer service policy)
DO NOT GO HERE UNLESS YOU LIKE TO BE LIED TO AND SCAMMED. Users/EllieR

20110401 13:44:07 nbsp I LOVE Amazing Tans Fluffy Donuts!!

Definitely the best donuts Ive ever had! Users/OrofinJackson

20131009 18:51:44 nbsp The location on 5th Street is closed as of 9/27/13.   Users/CalamityJanie
