
Aphids are tiny, softbodied insects with long, slender mouth parts that they use to pierce and suck out plant fluids from tender plant parts and new growth; spring is an ideal time for aphid colonies to establish feeding grounds. Almost every plant has one or more aphid species that occasionally feed on it, but low to moderate numbers of aphids typically cause little significant damage.

Aphids may be green, yellow, brown, red, or black depending on the species and the plants they feed on. A few species may appear waxy or woolly, but all are small, pearshaped insects with long legs and antennae. Wooly Aphids are perhaps the most conspicuous of Davis aphids and infest Chinese hackberry trees  the white wool of these aphids is waxy sugar which causes a sticky mess when it drops off town flora trees. Generally adult aphids are wingless, but most species also occur in winged forms, especially during spring and fall when populations are high. Aphids often feed in dense groups and do not move rapidly when disturbed. On roses in particular, you may see large numbers of aphids clustered on buds and near rose heads.

Though aphids can curl leaves and produce sticky honeydew, they rarely kill plants and can often be washed off with water. Large populations cause curling, yellowing, and distortion of leaves and stunting of shoots; they can also produce large quantities of a sticky honeydew, which often turns black with the growth of a sooty mold fungus. Some aphid species inject a toxin into plants, further distorting growth, and may transmit viruses on Culinary Plants vegetables such as squashes, cucumbers, pumpkins, melons, beans, potatoes, lettuces, beets, chards, and bok choy; these  cause mottling, yellowing, or curling of leaves and stunting of plant growth.

Soon after aphid numbers get high in the spring, natural enemies such as ladybugs, parasitic wasps, lacewings, leatherwing beetles, and mantids praying mantis come out to feed on them; eliminating the need for pesticides. Insecticidal soaps and oils, such as neem oil, are less toxic pesticides that can be used when treatment is necessary; be aware however, that pesticides and oils can adversely affect beneficial insects as well.

Aphid infestations can occur in backyard gardens as a result of some of the following situations:
   In Davis, aphids are a natural occurrence every spring, with overwintering pregnant females producing huge numbers of offspring as it gets warmer. Aphideating predators arrive a week or so after the aphids, so the time of greatest damage is usually fairly short and hosing off the plants twice is often enough to control the aphid envasion for that year.
   Overfertilization can cause large volumes of lush new growth, which creates prolific feeding grounds for aphids. Use organic fertilizers or slowrelease products to control plant growth.
   Aphids especially love flowering plums, roses, tulip trees, crape myrtles, apples, and many Culinary Plants vegetables. Expect aphids when you grow these plants.  Different plant species host different aphids; so the black aphids on plum tree leaves are not the same as the green aphids on a rose.
   Ants protect aphids as well as scale insects from their natural enemies. Reducing ant infestations on plants can help control both these populations.

Reduce aphid populations by pruning infested leaves and stems, knocking populations off plants by shaking or spraying with a strong stream of water, protecting seedlings with covers or aluminum soil mulches. Another way to get rid of aphids is to make a nicotine tea by soaking cigarette butts in water then spraying the resultant tea on plants  aphids dont like nicotine. If you can simply ignore them, most aphids are heatintolerant and will be gone from the Davis area by midJune. For continuing problems, beneficial insects can be purchased at most nurseries; see our page on ladybugs for tips on encouraging your beneficials to stay within your yard. Alternatively, insecticidal oils and soaps are the next safest products and work by smothering aphids, so application must be thorough. Dont apply oils/soaps to droughtstressed plants or weather when it is very hot and be sure to read the literature to find out which plants are sensitive to these products; there are some precautions for use on impatiens, fuchsia, hibiscus, some roses, ornamental olive trees olive and some carnation varieties. Oils and soaps, however, wont kill aphids hidden within curled leaves  these must be pruned out. Of the oil and soap controls, insecticidal soaps, soappyrethrum mixtures, or neem oils are often applied on vegetables or small bushes like roses, while narrow range oils, like parafinic, supreme or superior oils, are appropriate for larger trees.


http://www.ipm.ucdavis.edu/PMG/PESTNOTES/pn7404.html UC Integrated Pest Management program provides a wealth of information on pest control, especially in the Davis area. Don Shor of Redwood Barn Nursery has also written an informative http://redwoodbarn.com/DE_aphidstrategies.html article on tools for battling aphids. To learn more about the various plants growing in our town, visit our Town Flora, and check out our Town Wildlife to see what other bugs and such terrorize our neighborhoods.

Aphid Eaters
