The ASUCD Legislative Clerk is a paid assistant in the Office of the ASUCD Vice President who corrects all pieces of legislation for grammatical and spelling errors. Additionally, the ASUCD Legislative Clerk assists the Office of the ASUCD President with miscellaneous tasks such as the ASUCD Newsletter. The Current Legislative Clerk is available to assist any members of the ASUCD Senate or public with any legislationrelated issues.

The former ASUCD Legislative Clerk was Users/StevenLee Steven D. Lee.

This piece of legislative pork was cut in the FY200809 budget.  Well, actually it was just renamed to Assistant to the Vice President, but still, its better to have the broader job.



This job is piece of legislative pork, started by Thomas Lloyds bill, that will hopefully be cut in the next budget.  This isnt meant to reflect on the people who have held the office  its just that their talents and the government would be much better served by having them do something else.  Users/BrentLaabs
 In politics, a pork barrel (or pork barrel politics) is a derogatory term describing government spending that is intended to benefit constituents of a politician in return for their political support, either in the form of campaign contributions or votes. (wiki:wikipedia:Pork barrel Wikipedia)  Porks hardly the appropriate term, my friend.  The position was created to fill a well acknowledged need in the legislative process.  If its not working, I encourage you to work with the current clerk and try to fix it.  If the clerk simply isnt doing his job, then take it up with the positions supervisor.  Like any position in student government, the quality of work is only as good as the dedication/ supervision accorded to it.  I hoped that the position under the Vice President would not suffer from such problems. Users/thomaslloyd TL
   I wasnt trying to imply that it was a bad idea.  It just hasnt worked out too well in practice.  And the people who get hired are usually people who want to get involved in ASUCD  and its a nice stipend position for them  not because of their elite English skills.  This could be something the Advisor does, or SGAO even, and not rock the boat too much.  Or just refer everything to AAC or IAC:  nothing comes out of there with many errors!   So Im merely suggesting that the VP get his/her one staff member, and not have to worry about this legislative clerk business.  Users/BrentLaabs
  Well technically a position could be considered pork if the position is worthless but is used in such a way that it expands someones resume and financial situation by way of employment and payment.  Not sure if that is what Brent meant, but it is possible.  Users/SteveOstrowski
  Itd be a tough argument for him to make. I desired the position to be filled with people that would do a good job and reduce the amount of questions in text. The creation of the position was in line with the many other changes I ushered through to streamline meetings. I think youll find that if the position/personintheposition can be fixed, it can be a tremendous asset. Its why every legislative body of our government has one (grammar by committee isnt usually the best approach). Users/thomaslloyd TL
  Well if I had a choice as to use money to pay someone or make a volunteer commission suffer more I would go with the commission.  Truly the IAC would be able to fix all the problems before it went to Senate.  Although I see it as being necessary for some of the other commissions that rarely involve themselves with the codes.  Users/SteveOstrowski

Wow, if the bills that come to IAC us are AFTER being checked for grammatical and spelling errors, it begs us to ask a.) How bad are they before, and b.) how effective is this position (effective or affective? I always confuse the two). Users/MaxMikalonis

20070206 10:02:14 nbsp I agree, the president admitted that it was a do nothing position in the executive office but Steve is known for being involved in other activities.  And I will add that some of my bills have the weirdest edits when I eventually see them in IAC when it comes to the background.  I am not alarmed but a little annoyed/amused by it.  Users/SteveOstrowski

20070206 14:17:44 nbsp I, actually would agree with what people have been saying in terms of the pork. Ive actually suggested either removing or at least reducing the position/pay itself. There are, I think some plans to expand the duties/responsibilities of the position. I must admit, that sometimes I do miss some corrections in the leg. However in my defense, sometimes legislation is introduced as urgent or is brought into the office after my office hours and so there are the occasional pieces of legislation that I do not see. As for Ostrowskis comments about my corrections. For the most part my corrections are mearly to make the legislation flow better and easier to understand. The essence and content is still there, but sometimes i have to rearrange the sentence structure to make it sound correct and professional.  Users/StevenLee
