The ASUCD Fee is what helps pay for things that ASUCD does. This is automatically added to your undergraduate student fees and is the same amount regardless of whether youre a fulltime or parttime undergrad. If you dont like what ASUCD does, you can have this fee refunded by filling out some forms.  As of 201011 this is $35.00 a quarter ($105.00 a year). (source: http://budget.ucdavis.edu/studentfees  UCD Budget & Institutional Analysis: Student Fees).

The ASUCD Fee is split in four ways.  Only $8 of it per quarter goes to the ASUCD General Fund, the part that the ASUCD Senate can allocate  the rest is given to different programs by various ballot initiatives.  Cal Aggie Camp gets $.50, $2.00 goes to the Educational Opportunity Program, and the remainder ($30.50) goes directly to Unitrans.  Related ballot measures include the Campus Expansion Initiative and the FACE Initiative.

These are mandatory student fees, and have been since Spring of 1935.  If you want a refund, you can only get the portions of the fee back that are both political in nature, and that you have an ideological objection with.  You file a form in the ASUCD Student Services Office, which is then reviewed by Mark Champagne.  You then get back your portion of the ASUCD fee which is used for advocacy, which is 24 cents per year, maximum (200809). This was required under wiki:studentgov:ASUCR v Regents to implement the terms of __Smith v. Regents__ (though a later Supreme Court case may no longer require this, ASUCD still does it).

See Undergraduate student fees for more.

  Once upon a time I was told that you can get some of your fees back, like the Unitrans fee. You fill out the paperwork to not pay the fee and they take the little blue sticker off of your ID card. So you can get some of them back, but Im not sure how much.  Users/EricFox

  At the risk of being called a coldhearted Republican, I would like to find out if anyone else shares my views on the money given out to different programs like the Cal Aggie Camp and the Educational Opportunity Program. I know that twofifty is not very much, but when there are plenty of middleclass students struggling with student loans, I do not find it right when students cannot opt out of paying for such programs (its not the money, but the principle of the thing). I am not arguing about whether these programs are effective or not (I only know what is provided in the links to the DavisWiki pages), just the fact that one should not only be able to opt out of paying for these programs, but one should instead have to opt in for these programs (like CalPIRG, a group whose stances I usually am against). I know that students are able to vote on these issues, but what about those who became students after these initiatives were voted in? And many do not even pay attention to national politics, let alone school politics. Students have enough worries already and should not have to worry about more things in order to not have to pay more money to programs that they do not even know about. But then again, maybe this is a good thing and the school is getting us ready for the real world, where the government can just screw you over little by little.  Users/hankim
