

B&L Bike Shop has expanded into the space toward E Street that was last a Sprint mobile phone store and before that a Verizon and Fix for Less.
Next door at 608 3rd Street is now B&L Too, which carries cycling apparel for men and women, accessories, and bicycle themed gifts and jewelry.

Its a Bicycle Shops bicycle store that sells quality new Bicycles bikes and everything bicycling related.  They also rent bikes (only cruisers) and are a sponsor of the Davis Bike Club. They have a friendly, knowledgeable staff that is ready and willing to help anyone coming into the shop and experienced mechanics who can quickly and precisely solve nearly any bicycle problem under the sun.  While your bicycle is in for repair, they offer loaner bikes so you can still get around town.

Between the buildings is a bike station with Bicycle tire pumps bike pumps with compressed air and a hand pump. They have a shop pump for public use for high pressure tires and bikes with presta valves  they just ask that you be courteous to other customers and pump outside.

B&L carries Jamis, KHS, Free Agent, Electra, Fuji, and SE Racing (Single Speeds).  They are also listed as one of the Davis dealers for http://www.pakebikes.com/shops/ Pake.  They have the largest selection of accessories in town, and the staff will assist you to make sure the accessories you want will work on your bike.  They also carry Daviss own BRÜBAR Energy Bars.

B&L Too has everything from jerseys, cycling shorts, outerwear, and socks to water bottles, jewelry, and sunglasses. They carry Canari, Bellwether, Chrome Bags, Klean Kanteen, Camelbak, Tifosi, Serfas, Sock Guy and more.

This is the home of Milo, the shop cat.  He is furry, friendly, and good with kids.  Many Davisites visit the store solely to see Milo, but he is sometimes upstairs napping or eating when they come by.  Milo has his own email, http://www.facebook.com/profile.php?id100001418069086 Facebook pageFootnote(As of 5/30/2010, the management and staff of B&L dont know who controls Milos FB account, so while it can be considered awesome, it can not be considered official), and section of the stores monthly enewsletter.  He has also started writing B & Ls http://blbikeshop.blogspot.com blog. Milo is awesome.

 See Also 
  Bicycle Shops  other bike shops in Davis
  Bicycling  a good starting point for your bikerelated inquiries


Again, friendly knowledgeable staff. Great place for most bike needs. I enjoy giving them my business when practical. Small selection of road bikes, but good overall bike selection.  Users/EricKlein

Ive been riding in Davis a lot longer than Ive been working at Kens, and B&L gets my business when I cant find what I need at my shop. I got my first real mountain bike from them many years ago and have gotten great service from these guys.  Users/KenNeville

20051023 19:20:07 nbsp Didnt like the service. I think he was unclear and ripped me off. Go elsewhere. Users/XeDty

20060614 16:38:16 nbsp Ive had good service here consistently, whether Ive brought my bike in for repair, tune ups, fill ups ect.  Ive come in with some small repairs for my bike that the techs have gladly fixed for free.  Also, theres a hose on the fence on the right where you can fill up your tires.  Also, watch out for the cat, its not so friendly.  Users/CharlesGeorge

20060831 18:56:23 nbsp Prices are definitely high. Service can be shoddy  not all their employees are knowledgable.  I recently bought a bike rack for my sons bike and they sold me a rack that came without installation instructions and did not fit, even though they knew the size of the bike and model I was putting it on. Users/WilliamMead

20060916 21:27:19 nbsp Very helpful staff. They let me look at bike locks even while they were closing shop. It was past 6pm on a Saturday and a staff person answered my questions about various locks and told me to take my time. Users/MattLow

20060919 23:38:35 nbsp Great customer service there, and very glad I bought the premium package for my bike with the bad luck I had with flat tires. Users/JenniferKucich

20061009 20:46:20 nbsp They definitely try to rip people off here all the time. They dont really give you many options or tell you what theyre thinking. Also, when trying to rent a bike here, they took my boyfriends card and put the $400 authorization without really explaining what it was or what it would do to his bank account. Unfortunately, this happened over the weekend so the bank couldnt do anything about the authorization which made $400 vanish from his bank account. The manager was also very hesitant to clear the charge on her end. Needless to say, he didnt rent the bike. Users/MegDana
  An authorization asks your credit card company to verify that you have a given amount of money available below your limit.  It also asks your credit card company to put that money on hold, in case further charges need to be made on the account.  This is a common practice in many rental places, as well as any hotel youll ever stay at.  The company youre dealing with does not take your money, and therefore cannot give you anything back.  Most credit card companies will release the authorization within 34 days; some take as long as 10.  Regardless, while the authorization is on the card, no, you cant use the money, but thats the entire point:  The company making the authorization wants to make sure they dont get screwed by reckless individuals.  Again, this is especially significant at hotels, which will commonly authorize two or more times the cost of the room on the card to make sure you cant skip out on the bill. Users/BrettHall

20061016 23:52:47 nbsp I went there to fix my bike on 3:00 pm, they got it, and walked back to my dorm. 2 min after I sit down to my chair, they called me it is ready, and I walked back with amazement of how they manage their business (they said it will be ready late evening or tomorrow). When I got there, I noticed that I did not bring $10 fee for the bike. I asked them that if I may take my bike and give money later (I bought $400 worth new bike there 2 weeks ago, they got my information, which make me credible) but rejected. I asked again to salesperson to ask to his boss, and the woman (whos probably the manager) rejected. Then I begged to that salesperson to personally borrow me $10 bucks and I will bring it right away, but he again did not accepted. He rather recommended if I rent a bike if I really need a bike, I said no (see what happened to MagDana) I walked back to my dorm and brought money and again walked back to Bikeshop. I got several water blisters and muscular ache on both legs. B&L, remember that, when you give a good service to a customer, that person will bring 3 more customers. But if you piss off a customer, you will lose 33 customers instantly. Users/ChickenNuggets
  To me, this doesnt seem unreasonable on the part of the business owner. I would actually be surprised to find many businesses at least in the United States who operate on the faith you expected. And in a college town, its not unusual for people to make empty promises, e.g. Ill come back with the money. Unless they led you to believe there would be no charge for the service, its reasonable to expect that you would have brought some form of payment with you. In my book, this interaction doesnt relate to poor customer service... perhaps just different expectations. Users/AlphaDog
  Right, but think about it.  In exchange for risking a loss of $10, they could have made a friend who would have brought in more business.  Worse came to worst, theyd have lost $10.  Its not like we live in NYC over here, and people really ARE looking for an excuse to not just buy the cheapest thing off the internet.  In Davis, people want personal service from local businesses. Users/edubin

20061115 14:56:09 nbsp So far, I have not yet had a problem with B&L.  The staff knows what to ask when buying bike parts so you dont get the wrong item and realize it later when you get to repairing your bike. Users/MartySmith

20070105 16:56:11 nbsp I was looking for a bike trailer. The salesperson was showing me a used trailer and toled me it was used for display only. He also told me that its a 2005 model when later on I found out its a 2002 model and that it was used for four years they didnt even apologized. I have got the feeling that I got their “special welcome” for foreigner with accent. Users/LoTam
  I have got the feeling that I got their “special welcome” for foreigner with accent.  Or a combination of a misinformed salesperson and miscommunication led to hurt feelings.  The trailer in question is in fantastic condition, and looks like it may well have sat in storage for five years instead of being used as much as it was  theres nothing wrong with it aside from someone else having owned it for a while and taking excellent care of it.  Charges of racism are serious, especially when a much more benign explanation more easily addresses the issue.  And especially when the charge is leveled against someone who is himself a minority, and would thus be less likely to express such views.  If B&L gave such welcomes to people with foreign accents, they would lose a very sizeable portion of their customer base. Users/BrettHall

20070122 18:36:06 nbsp B&L, I like your shop. Lots of cool stuff to look at, plenty of assistance, parts, repairs, some cool bikes too, you should have more parts though so everybody in Davis can really start to customize their bikes... I recommend the Pedros SynLube (green bottle) for Davis students this Winter  It stays on a long time, and you cant get it at Freewheeler! Users/GarrettGallegos

20070402 16:34:51 nbsp I bought a 700 dollar bike + bunch of accessories. They usually have really awesome service but I was SHOCKED that they actually charged me for 2 zip ties after buying an overpriced CPU holder for the aero bar today. I mean come on, its only 2 zip ties! Are those 18 cents worth repelling a regular customer? Users/KaiWan


20070429 18:28:35 nbsp As a gift in December, my boyfriend, Karl, took me to get a bike at B&L. At first, I was very hesitant about their bike selection, but after (very little!) wheedling and cajoling, I was convinved in getting a bike there. I got a hybrid bike, meaning its half mountain bike and half recreational/street bike. Its a really good bike and it fits me perfectly. Ive even strated calling it my MintNChip Mobile. :)
If you get certain packages with them upon buying a bike, they will send you notices in the mail about future checkups and tuneups. In February, I received a letter reminding me that my 60day checkup was due, and that I needed to bring it in within a certain window of time. So I called B&L, told them I received their letter, and asked if it was acceptable to postpone my 60day checkup until April. They said it was okay, and I took down the name of the person who gave me this information. I just recently went it to redeem this, and I was told that I could not get my bike tuned for free (as it was part of the initial buying package). I told the person that I called, was told contrary information, and even gave him the name of the person. He simply nodded and took my bike in the back and they fixed it. Very good customer service.
So word to the wise. Do not make assumptions about any business. Be sure to get peoples names, dates, and times, in case anyone tries to hassle you if they believe you are dishonest. I got this advice from my mother, and it has helped me immensely in my life, as there are always going to be individuals and businesses who Kens Bike & Ski try to take advantage of you or do not believe you because of prior customers Users/ArielaHaro

20070513 21:01:32 nbsp I sold my old truck and thought I would turn some of that cash into a bike, and given the service that Ive gotten at B&L, I walked in and got myself scanned. I was looking for a bike that I could balance on and ride without my hands, like my old bike. Nothing quite fit me. Either the bike was so tall that I might as well have gotten a horse, or it was too small and I looked silly on it. When it seemed like I wasnt going to be able to find one that fit me, they remembered that they had one unassembled that was similar to one of the smallerframed bikes that almost worked. They offered to assemble it for me by the next day, and when I tried out this coppercolored bike I was quickly sold. A perfect fit. A couple hours later they had my toys installed on it and it was mine. Ive been to many bike shops in Davis, some good, some annoying, but I would recommend that people try out B&L first. Users/KarlMogel

20070519 06:47:13 nbsp Pretty good on tools, I was able to buy the 16 tooth widget to remove a shimano bottom bracket. Users/BillBroadley

20070521 16:19:21 nbsp I went in today to get a lock...the staff was helpful and informative. I was impressed. Users/AdamFerguson

20070707 12:56:19 nbsp Move some shit around so its easier to walk around in here... Users/GarrettGallegos

20070714 01:35:39 nbsp Normally I go to Kens, but I went to B&L during the sale. Guy named Adam (apparently 53 adams work there) helped me extensively. Extremely helpful, I will definitely go back to B&L for more gear and/or technical help. Not dissing Kens at all, but the service at B&L was excellent! :) Also  heres a secret for those considering doing their own repairs  bikes are actually pretty easy to work on if you have the right tools!! Two greasy thumbs up, B&L!!! Users/JeffieBaby

20070806 17:01:54 nbsp theyre helpless when it comes to bmx. altho their is supposed to be one guy who knows whats up, he just never seems to be working. Users/piratechef

20070824 11:45:27 nbsp Id take B&L over the bike barn any day. They even helped me sell my old bike when I didnt want to pay to fix it. Users/HakonHope

20071002 00:54:38 nbsp They have a pretty long application full of interesting questions.. better than most other places I have tried to work. Users/DavidPoole

20071009 18:55:55 nbsp This is where I take my older Trek bike.  The staff is always really helpful.  The guy who helped me most recently (Adam?) was extremely patient, explaining different options to me.  There was no sales pressure and no condescension about my older bike.  I cant say the same for other shops in town! They also have a good selection of acessories. Users/SusanCameron

20071015 18:48:59 nbsp I think B&L is great. A lot of the staff is friendly and very helpful. I bought a lot of my parts for a bike tour here, and just got a cool little bike light for $10.    Users/PxlAted

20071019 05:16:26 nbsp they have a new sign. cool. Users/EliseKane

20071027 15:56:14 nbsp I bought a bike light from them about a month ago.  The batteries that came with it corroded the contacts, making it useless.  I went in today and showed them what it was and the readily gave me a whole new light and bracket set and I didnt even have my receipt anymore!  Ive never had any problems and theyre more than helpful when you need it. Users/MartySmith

20071114 14:32:05 nbsp Beware of the eggbaig. It was first sighted here. It tried to rob a mechanic at baig point. Scary I know, just be wary. Carry on.  Users/snacks

20071217 15:37:26 nbsp I went there yesterday and asked them for a 26 rim. When I got home and tried to fix my bike, I realized that there was no way that my tire would fit this rim. After measuring, I realized that they had actually sold me a 27 rim. This isnt that big of a deal, but it is definitely an inconvenience.
 Users/LeahGanis
 Just FYI, a 26 rim can have a beadseat diameter anywhere from 559 mm to 599 mm. http://sheldonbrown.com/rimsizing.html As always, Sheldon has the answer. Users/WilliamLewis

20071231 16:50:27 nbsp I had a great experience here. The staff was extremely friendly and helpful and they had an excellent selection. I will definitely return next time I need anything for my or my husbands bike. Users/dhsandler

20080214 23:37:31 nbsp They have a good selection of parts which the other shops seem to have to order, like stems and so on. I havent had them do any work for me, but they have always been helpful when I needed advice on selecting parts. The prices might be high, but when you factor in the cost of shipping when you buy cheaper parts online, it comes about even most of the time. Users/twblalock

20080521 18:35:02 nbsp B&L seems to cater to the low end of the Davis bike market.

Went here looking for a good long distance commuting hybrid bike.  Couldnt find one.  They mostly seem to carry heavy comfort bikes.  They put me in a measuring device, which took about 10 minutes to figure out what size bike I needed.  Freewheelers employees figured out the correct size in seconds.  I wanted to test ride one of their bikes, just to see if it might meet my needs.  They wanted to hold on to my drivers license or credit card (I forget which), and wouldnt let me try a bike without them.  I realize that they want to make sure that the bike comes back, but it didnt make me feel very good about the place.  At Freewheeler, they just let me take out the bikes that I wanted to test ride, and I bought a nice bike there as a result. Users/IDoNotExist
 What, exactly, are you complaining about here? That they took the time to fit you right (a whole ten minutes!)? That they required as most places do you to take your license out of your pocket before taking their merchandise out of the shop? If you want to sing Freewheelers praises thats fine, but if you want to do it on B&Ls page make it should make a little more sense. Users/BrianLum

20080521 23:41:09 nbsp The measuring device seemed rather gimicky, and didnt do any better than the employees at the other store.  It also kept asking for contact information (name, address, phone number), which was being collected for marketing purposes.  I dont like being marketed to, or receiving sales calls or junk mail, so as a rule, I dont give that info out to businesses unless it is actually legitimately needed for a transaction (for example, if I were signing a lease, it would make sense.)

As for the license requirement, there was a big difference in how I felt shopping at B&L and how I felt at Freewheeler.  Its certainly understandable that they would not want someone to run off with their bikes, and Freewheeler would probably have won anyway because their products were simply much better for my needs than B&L (and unlike Wheelworks, they actually wanted to sell me something!)  But given how they made me feel between asking for marketing info and asking me to trust them with my ID, it definitely decreased my desire to buy a bike there.  So if they had had a comparable bike, Id probably have gone to Freewheeler.  They didnt though.  Their bikes were not what I needed given my needs. Users/IDoNotExist
 BodyscanningCRM (the fitting software/device that B&L and Kens use) requires some form of contact information before it will continue.  From working at B&L for almost 3 years (I no longer work there), I can tell you they use your information for very little aside from contacting you when you need to be contacted.  The only physical direct mailer that has gotten sent to the mailing list at large is the beginning of the year tuneup special  and even this had to be cut back this year due to massive response last year.  Any physical mailings are prepped by the staff at the store, and are not junk mail.  The most mail youll receive is if you purchase a bike, theyll mail a free tuneup reminder and details about whichever package you received with the bike  all done by hand at the store.  B&L doesnt do sales calls (they do, however, continue to call if you leave your bike there for several months or dont pick up a special order).  They dont sell contact information.  No, really.  They DO, however, help recover stolen bikes, which they can only do if they have your contact information.  Indeed, there are boxes of records of bike sales dating back into the 80s in case any of those people ever need information about the bike they bought.
 As for trusting a store with your ID:  Do you ever use a credit card?  Every transaction you make at a physical store gets recorded.  Every retail store will have a closing procedure where the transactions for the day are printed out.  Because they are required to track that sort of thing (and oh my god closing out is tedious  but it catches errors made during the day).  Most small stores (and many big stores) have, on the store copy of the receipt, all the information needed to do a manual credit card transaction (this helps with correcting the aforementioned errors).  There are a whole mess of laws and morals that prevent employees from taking advantage of this fact.  But if you want to be paranoid (note: paranoia does not mean theyre not after you), stick with cash only.  If you want to fuel your paranoia, check the receipts youre signing  most of the time your full CC# will be at the top.  For a retail worker with few morals, physically stealing your card would be ridiculously stupid with access to this sort of information (you call within a few minutes of knowing your card is stolen  thief gets little opportunity to use the information). Users/BrettHall

20080524 07:41:23 nbsp http://www.leginfo.ca.gov/

1747.09. (a) Except as provided in this section, no person, firm,
partnership, association, corporation, or limited liability company
that accepts credit or debit cards for the transaction of business
shall print more than the last five digits of the credit or debit
card account number or the expiration date upon any of the following:

(1) Any receipt provided to the cardholder.
(2) Any receipt retained by the person, firm, partnership,
association, corporation, or limited liability company, which is
printed at the time of the purchase, exchange, refund, or return, and
is signed by the cardholder.
(3) Any receipt retained by the person, firm, partnership,
association, corporation, or limited liability company, which is
printed at the time of the purchase, exchange, refund, or return, but
is not signed by the cardholder, because the cardholder used a
personal identification number to complete the transaction.
(b) This section shall apply only to receipts that include a
credit or debit card account number that are electronically printed
and shall not apply to transactions in which the sole means of
recording the persons credit or debit card account number is by
handwriting or by an imprint or copy of the credit or debit card.
(c) This section shall not apply to documents, other than the
receipts described in paragraphs (1) to (3), inclusive, of
subdivision (a), used for internal administrative purposes.
(d) Paragraphs (2) and (3) of subdivision (a) shall become
operative on January 1, 2009. Users/DonShor

20080612 12:19:37 nbsp I love B&L. Theyve worked on my bike a couple of times and Ive bought many oddsandends parts from them. Every time Ive been in, the staff have been friendly and helpful. They really listen when I explain what Im looking for and their suggestions are clearly just that, not attempts to upsell! Users/LizPhillips

20080621 17:40:16 nbsp My partner and I moved to Davis and did not own bicycles. We were looking for comfortable simple reasonably priced bikes. I priced out our bikes at all the stores in davis and the surrounding area and it would have been about $20 cheaper to buy them in Sac but I figure it was worth it to go local and get their maintenance package. The staff was friendly, informative, and effecient. If you want a simple but nice bike to get around town with I would suggest this shop. Users/Zeeba

20080806 16:59:53 nbsp Just went here for some inner tubes. Helpful staff, very knowledgable, but I had the feeling that the staff member who was helping me kept trying to upsell me stuff. Kinda annoying and not a good way to earn loyal customers.   Users/GabeDavis

20080809 10:49:21 nbsp Good Shop with very helpful staff.  However,  some one there thinks a moose can derail a train.   Users/FrankJones

20080814 16:18:06 nbsp I liked this place initially after moving here (Ive taken three bikes there over the past couple of years) and the service (mechanical) has been good, but the labor is overpriced in general, and the last couple of times I was there 1) I had an obviously brandnew employee try to help me, which took much too longand there were three other employees loafing about, and 2) The employees in there have made my wife feel like crap.  (Ralph is an exception.)

What is it with people in retail businesses that makes them think they can treat their female customers differently from the male ones?  Ill never go back.  Ditto for my wife.  Well go to Kens instead, I suppose, or Ill fix the damn bikes myself. Users/Octavian

As a current employee of B&L Bike shop, I would like to offer my opinions on the previous comment.  I would first like to address the topic of the new employee taking much too long to help you out while three other employees were loafing about.  It is a fact that at B&L we do have several new employees on the sales floor which are not as knowledgeable as some of the  veteran employees.  If our new employee was checking in your bicycle for repair, it may also take a bit longer for this new employee to make sure that every part of the bicycle was inspected for safety.  We do through inspections for two very important reasons 1) To make sure that the customers bicycle is safe to ride and 2) so that the mechanics (which are separate from the sales staff) do not have to contact the customer while repairing the bicycle with additional safety concerns.  Although a bicycle is a relatively simple vehicle (mechanically speaking), there are many parts which a sales person (a new one especially) must remember and address before the bicycle is fully checked in for repair.  I would like to personally apologize if you felt that your time was wasted.

As for the three other members of the sales staff loafing about, I would like to state for the record that every new employee is instructed (many times) to ask questions often, or to ask for assistance, if they so feel assistance is needed.  If not directly addressed for help, it is reasonable that the other employees would trust in their coworkers ability to properly assess the condition of the bicycle.  Furthermore, it can often get crowded in our shop due to our limited floor space.  Therefore, our employees often appreciate a generous amount of space while working one on one with a customer, unless explicitly asked for assistance.   Once again, I can only offer my apology if you felt like our new employee took much too much of your time without asking for assistance from any of the other sales people.

As for other employees (besides Ralph who, I am happy to say, personally trained me) making your wife feel like crap, I would like to once again offer my apologies.  Specifically, I would like to know how our employees made your wife feel as though she was belittled so that our employees can address the problem.  We make a distinctive effort at B&L to greet every customer at the door in order to make them feel welcome in our business.  We know that, in Davis especially, you have many choices for bicycle shops, and even more choices once you enter those shops. Because of this, I feel that I can speak for all of B&Ls employees in saying that we all present the customer with their choices in a manner in which they should feel comfortable and able to make an educated decision.  If you or your wife feel at all like you have not received the proper attention at our shop, please let us know.< Users/DanielFritz

20080821 17:03:56 nbsp Daniel, I understand the comments regarding your new employees.  And Beth is the one who treated my wife with the most disdain. Users/Octavian

20080822 13:00:04 nbsp B&L misinformed me about a bicycle part and seemed extremely condescending about it. It was about whether a sizing for a part would be alright (and it was: apex, wheelworks, freewheeler all said it was fine), and the guy was just a straight up ass about it. I thought it was just me but my friend was with me as well and he could tell as well. Its funny though that FSA makes the carbon sizing of the part I wanted and the guy insisted that size would snap. You guys have to realize that not all customers are dirt racing or mtn biking. I was looking for the size because I was trying to race track, to make my ride as light as possible and durability is not an issue when Im on a velodrome. Users/btt

20080824 15:53:52 nbsp I always regret shopping at B&L. Maybe I have finally learned my lesson. I bought a bike seat for my toddlers new bike (new to her. bought at a garage sale and it didnt have a seat). The salesguy assured me that the seat he was selling me would fit any toddler bike. I asked if I could return it if it did not fit. He said it would fit and that I could return it but would be charged a restocking fee (I find this annoying since he had just assured me that it would fit. but at least he was up front about it).

The seat didnt fit. We brought the bike and seat into the store and asked if someone could help us either find a different seat that would fit or if we needed another part to make the purchased seat fit.  We found the sales people to be reluctant to help us, skeptical of our credibility (we couldnt use the charge card because we werent in the system yet we had the receipt in hand from the bike seat THAT WE CHARGED a week earlier) and in general, not helpful.   We ended up buying an adaptor to get our seat to fit. But when we asked if we could check it before buying it, we encountered lots of mumbling and reluctance.  The experience made me and my family feel like whiny losers (why should we have to try so hard to get help after we have already given them our business? and if they made a mistake in telling us something, couldnt they try a little harder to help fix the situation?). After we left, we walked down to freewheeler to purchase a bike rack. Id recommend going there or Kens if you want more consistently friendly and helpful service. Users/Lasan

20080915 22:21:59 nbsp I went to B&L after hearing that they were friendly to regular bike riders, not just hard cores.  Well, not so true.  I brought in my cruiser for repair.  They lost the ticket, and the work wasnt done when I went to pick it up.  Ok, stuff happens.  But when I arrived the second time to pick up my bike, the guy I dealt with needed me to explain everything again that I explained when I first asked them to repair my bike.  Little things, like asking for help with seat and handlebar adjustment seemed like too much to ask.  I wanted to purchase a lock and a helmet from B&L, but after the snobby attitude, I decided Id take my money elsewhere.   Users/mphpnj

20081003 17:29:57 nbsp Good selection of quality parts and tools at high prices.  Always got good service, however its madness in there on weekends the place is so busy.  Seem to stock lower end bikes.   Users/jcoffman98

20090104 10:56:24 nbsp I came here for a quick, easy repair (simply screwing back on the derrailleur and the rear brake, which had to be taken off for transport) and they looked up the closest equivalent in thei price book and said theyd have to charge me for a full derrailleur /installment/ and that itd be no less than 36 bucks and might take all day. I dragged my crippled baby over to Kens and they did it on the spot for five bucks while I waited. The merchandise here looks good but I wouldnt go here for repairs.  Users/LaFrance

    We wouldnt just reinstall a derailleur without making sure it is properly adjusted once it was reinstalled, same goes for the brakes. Charging for the work being done is how a business stays in business. Users/BethAnnon

20090122 12:03:49 nbsp Avoid this shop for any servicingrelated needs. I brought in a brand new, beautiful lugged fork to be threaded one inch...waited for 2 days to come back to a fork threaded only a halfinch, complained and was told to come back the next day so they could thread another half inch. I came back to find that not only did the second threading mismatch the first threading done, but my new fork was cosmetically damaged by a mechanic who put the fork unprotected into a vice and clamped down. That was great.

I had to wait another week for them to replace the fork, and on top of that I had to take a loss on my stem, headset purchases due to the fact that I had to go threadless because this is the only bike shop in town with the appropriate threading tools...needless to say, I wasnt going to have them do a another threading job.

In general though, the turn around here for servicing is quite slow and pricey, and the sales floor not very knowledgeable (having to call on the upstairs mechanics for many of my questions). There are only two mechanics there worth talking to; Ralph and one of the younger guys there he personally trained. If you want a good price, a knowledgeable mechanic/sales person to talk to whenever, a fast turn around, special items ordered and delivered fast, and a friendly atmosphere try APEX Cycles. Users/mistermestizo

    mietermestizo insisted on changing to a threadless fork. We offered him the exact same replacement fork. He was given an new fork and refunded for the labor that was originally performed. Mistakes happen and we took care of the customer in the exact way that he asked.

    As for calling upstairs for a mechanic that is where the mechanics work. So if you need to talk with a mechanic they have to come downstairs. Users/BethAnnon

20090307 02:18:52 nbsp B&L has to be the best bike shop in Davis.  They have a very knowledgeable and friendly staff, good selection, and good prices.  I try to go to B&L for any biking problems I might have. Users/dj123

20090317 23:39:11 nbsp I have been to all the Bicycle shops in Davis. Their service is the best so far. Staff is friendly and very knowledgeable. Everytime I have been to this store they made me feel cared even if I buy a small stuff. They always offer good solutions to my bike repair projects. They have large selection of parts and tools. They offer good bicycles for all ranges and the prices are very reasonable. Great store, great selections, great service,great prices, great people. My first address whenever I need something for my bicycles.I will definitely buy my next bicycle from B&L.    Users/Aytug

20090320 17:05:58 nbsp My experiences with B&L have been great. My first experience with B&L began after I had taken my wifes bike to several other shops in Davis looking for a new comfy seat. However, the seat tube diameter was nonstandard. The other bike shops in Davis said I was SOL, that the bike was a piece of crap, and there was nothing they could do but sell me a new bike. B&L on the other hand, gave me some options including helping me get a different tube so that I didnt have to replace the bike. B&L didnt make a dime but they helped me out anyway. A year later I went back and to buy a new bike for myself and they really went all out in their service. After fitting me for a bike they let me try many different bikes with no hard sell. I went back on several different Saturdays to try the bikes until I found one I really liked. Again, they were very nice and didnt pressure me. The after sale follow up has been great. Wonderful experience overall.  Users/RScott

20090429 22:38:29 nbsp B&L is great. They not only took care of my repairs quickly but the guys in the repair shop were super friendly and went the extra mile to make sure that my bike was operating at its best. I commute to Sacramento on my bike so its important to me that its reliable. B&L will get my business as long as I live here. Theyre awesome. Users/Hiveman

20090506 18:35:47 nbsp Well, I just stopped by the B&L yesterday, picked up a shiny new chain and a tube. Their newest employee, Daniel, is the nicest guy around, and quite knowledgeable about his bicycles! Users/JohnDudek

20090709 13:20:32 nbsp Just came across a woman who was sold the tip to a 1/4 gig line as a presta to schrader adapter for 50 cents at B&L, another quality transaction Users/steveguyman
    Google says a gig line is the straight line formed by a military uniforms shirt, belt buckle, and trouser fly.  Searches for various spellings (jig?) come up with nothing useful (closest was for fishingtype gear, which Ive tried and failed to find in the store).  Also there are buckets of proper adapters at each counter and the staff does indeed know what theyre for, so I have no idea what Mr. Anonymous Story is trying to say.  More details would be appreciated. Users/BrettHall

20090709 21:05:58 nbsp I like this shop. We have bought 2 bikes, a helmet, bike trailer & some locks from them and they are very knowledgable. Had a few repairs done too and they were fair on pricing. Great customer service. Users/jwendt

20090721 20:21:46 nbsp horrible service. Brought my bike here to have the front wheel straightened. The person who checked in my bike said it would be no problem. Three days later I get a call and they tell me they cant fix my bike because the front wheel has dents in it ... so I rode the bike they loned me over to the shop to get my bike and when I get there they tried to give me my bike without the front wheel attached to the bike and without the tire on the wheel. I said you going to put that back together right? They said, oh, was it together when you brought it in? I said of course. Next a second employee came out to try to explain to me why they couldnt reassemble my bike .. for liability issues. I told them to put my bike back together, in the same condition it was in when I brought it, and they refused. They made me put it back and made me go outside to inflate my tire. I have never ever been treated so poorly by any business.  Users/RealComputers
    Thats not the conversation I remember.  Rather than play your word against mine, though, Ill try to explain the liability issue:  If we perform work on a bicycle, where we know that such work makes the bike unsafe (or less safe) to ride, and you are injured while riding this bike, we are liable for your injuries or death.  Further, you instructed us to stop work when you did not want us to complete the work necessary to make the bike safe to ride.  If we have to disassemble part of the bike (or, in this case, remove the tire from the rim) in order to perform the work ordered, we arent going to then complete the work when you tell us to stop.  Ill also note that the mechanic was asked to put the tire and tube back on the wheel so that you could pump it up, and for the whole time we had your bike you had one of our rental bikes at no charge, because we know how inconvenient it can be to be without your bike.  Im sorry if our actions seemed like bad customer service to you, but unfortunately its the way this industry has turned (especially in California, home of the frivolous lawsuit) (there is a large portion of this decision that is based on simply caring about the safety of our customers, and wanting them to enjoy their cycling experience as much as possible  Im emphasizing the legal aspect because thats how it was brought up).  So customer beware:  If you want a bike thats unsafe to ride, B&L will not work on your bike (conversely, were willing to resurrect just about anything you can dig out of your garage if its able to be fixed and you love the bike enough to fix it).  Users/BrettHall

20090901 16:24:25 nbsp This place is a ripoff for small parts.  They tried to charge me $4 for a set of bearings that cost $1 at the Bike Barn on Campus.  That and the guy that helped me was pretty clueless.  I had bought another part a few days earlier thinking that it was way too expensive, but was assured by Brett (the same Brett who feels the need to defend his store against all negative comments here) that I was paying a low price compared to similar parts in his inventory.  Sorry, but this store is kind of a joke.  If you want a nice road bike, go to Wheelworks or Kens.  If you need a commuter, go to Free Wheeler.  If you need parts, go to the Bike Barn.  If you need to get ripped off on parts that are marked up about 1000%, go to B&L.  Users/Jibbajaba
    The axle I sold you should have gone for $11, not the $7 I charged.  Our fault for not labeling it clearly, but thank you for pointing it out so I can add more things to my todo list.  Oddly, the only reason I remember this transaction is that I thought Mr. Jabbas reaction was that the price was so low.  Wheels Manufacturing does make some inexpensive axles (including the one in question), but none that should be sold for that much under $10 (assuming the goal is to make some semblance of profit).  Users/BrettHall
    Well then Im sorry, but thats even more ridiculous.  I can buy an entire new coaster brake kit for $19, and that includes the axle, three sets of bearings, the clutch, two brake pads, etc.  Everything except the rear cog.  And thats for a Shimano brake kit.  You are charging $11 for an axle, plus $4 each for bearing sets?  Thats $23 just for those 4 parts.  I should have just returned the axle to your store, but it was my mistake for not doing my research first so I just ate it.  I went back to the Bike Barn and got the bearings I needed.  Brett, you seem like a nice guy, but your store seems like its set up to take advantage of the clueless based on some of the comments here.      Users/Jibbajaba
    I cant believe you are complaining about prices and then advising people to go to WheelJerks.  Last I checked they dont even sell a road bike for under $1000 and if you even ask them about prices they look at you like you dont belong in this store.  Ridiculous.      Users/AmandaAbughosh

20090902 15:07:44 nbsp B&L has provided pretty good service to me, and on the rare occasion that they didnt meet my expectations, I contacted the manager and she was very helpful in resolving the issue.  It is funny that some people complain about reasonable business practices such as asking for payment when the customer picks up the bike, or charging for each item used, or asking for an ID when you take their bike out and could ride away with it. Holy cow. But...peace and love, peace and love. Serenity now... Users/RonB

20090913 19:52:17 nbsp I advise AGAINST going here to get any work done on your bike at all. I went there last year just to get a tune up (my bike was working fine but I try to bring it in anyway every year). When I tried to ride it home the gears began to stick and I could not move the pedals at all. When I brought it back they said that the chain was bad and that I would need to either replace it or only use it on one gear. For basically breaking my bike I got charged over 80 dollars. Then today I had Aaron from the bike shop on G street (APEX Cycles) come by just to fix my flat tire and in just a few moments he had fixed my gears as well not charging me extra. You should go there instead of this place, which as others have mentioned, only rips people off, treats them rudely, and does not seem to really understand how bikes work.  Users/jsh314

20090918 17:13:08 nbsp i bought a used hampton and wanted to know more about the bike he took my bike put it on the stand and started taking it apart with no explanation then told me i had to pay for a service fee i felt uncomfortable oh and the lady manager kicked my bike chain that was on the ground really do not like them would NEVER ever reccamend them Users/tylor

20090918 22:24:36 nbsp i have no idea why everyone keeps saying their staff is so friendly. i went in to get a rack on my bike. the guy refused to put it on for me because they were too busy. most of the employees were just standing around. he told me i could put it on myself in 20 minutes, yet didnt give me any tools. i returned the stuff and took my bike to freewheelers. ive never had worse service anywhere. Users/tlynn

20090930 00:18:57 nbsp Always great (& friendly) service and competitive prices. Highly recommended! Users/Oleg.Lokhvitsky

20091112 08:24:03 nbsp I love B&L Bike Shop and the folks that work there.  I needed to replace some part on a older bike (tires, brake levers, brake pads, etc) and went there looking for options.  I received excellent and knowledgeable advice on every part I looked at.  Sure I could of used the staff for information, written down part numbers and went searching on internet hoping to save a few dollars.  Except without the advice of the staff I would have purchased the wrong parts online and would have had to exchange or repurchase the parts.  Thanks B&L staff for saving me both time and money!  They also have the best selection of tools of any bike shop in Davis. Users/mjwood

20100224 20:07:55 nbsp Good accessory selection, mediocre servicing; overpriced, sluggish, disinterested, and rarely thorough. There are some good mechanics here, but youll only get them on the third or fourth try. I perceive a selfrighteous vibe from some of the floor employees, which is more or less confirmed by the commentary they leave here. Since when is it appropriate to berate a dissatisfied customer? If not for the tone, I would let it go, but the hostility is tangible.
Ill be coming back to shop for addons, but no service. Too bad, its a really nice space and in a prime location.  Users/JaneKostina

20100418 15:02:26 nbsp Ive been trying really hard to like this bike shop, but they are making it oh so difficult for me.  Ordered an integrated headset w/ installation.  Didnt have the part in stock, which isnt really their fault.  After 1 week, they had the part, but said the wrong part was ordered.  This was not my fault since I asked two workers which headset I should get.  They returned that headset and ordered another one.  A week later (today) I give them a call and they say that the part is out of stock in their main warehouse, and will proceed to order the part from somewhere else.  So they are going to place an order on monday, and have it arrive NEXT Friday.

Basically, if you want a headset change to take nearly a MONTH, go to B&L.  otherwise, go some place that knows bikes.  goddamn i am pissed. Users/kidkoryo

20100503 16:57:06 nbsp Note on B & L policy:  Customers may not borrow tools to install newly purchased parts. Users/NicoLinesch

     That seems very reasonable and should probably go without saying.  Users/AmandaAbughosh

20100523 14:40:11 nbsp Through the summer, B&L offers lead rides around the Davis Bike Loop, Saturdays 4:306:00pm  lots of fun! The leader was knowledgeable and aware of his riders capacities. As a secondyear Davis resident and bike commuter, I very much enjoyed the opportunity to see the other twothirds of our town. I would unhesitatingly recommend this as a familyfriendly weekend activity.

(And for those who might find their way around the bike loop, or larger loops, on their own, consider the advantage of having a mechanics attention for an hourlong, open air, FREE consultation :)
 Users/rlreeves

20100613 10:34:14 nbsp Im really surprised at some of the negative reviews here!  I bought my bike here about a year ago and it was very reasonably priced and exactly what I needed.  Since then, anytime I needed something for my bike the staff was SUPER friendly and never took over a day for any service request. Users/AmandaAbughosh

Im not to surprized by the wide range of reviews.  Most shops in Davis that have been around for more than a couple years have both very satisfied and very unsatisfied customers.  My B&L Experience has been decidedly mixed, good value, not so good service.  Users/Rocksanddirt

20100815 14:11:50 nbsp  I needed some minor adjustments to my bike, and they helped me out, free of charge. Great service. They are willing to help people in need, even when it is not convenient for them. Users/tylertucker

20110311 23:16:16 nbsp Go elsewhere. Super disappointing service and repair! There are too many bike stores in town to put up with mediocrity. :( Users/RobynW

20110326 12:37:33 nbsp I was bummed that they didnt stand by their accessories. I bought a light there that broke the very first time I tried to change the battery (I had not done anything weird or out of the ordinary in trying to change it) .  I figured theyd stand by the product and replace it, but no dice. Users/edubin

20110417 15:48:39 nbsp Extremely friendly and helpful! I got a flat on picnic day, and brought my bike in the next morning. I didnt have a lot of time, and needed to work in north Davis in the afternoon, so they fixed it while I waited. Thank you!!  Users/GwenBarrow

20110421 08:07:00 nbsp I went in to get my tube replaced for my road bike and payed $20 for the new part and labor. Unfortunately the guy who put the new tubing in neglected to take out the glass in the tire that had caused the flat in the first place. So after leaving the shop on my bike...the tubing popped again. I went in to ask for them to fix it with free labor but they denied me. So I payed another $20 to have them fix their own mistake. They were fairly rude about the whole situation and I feel as though it was just a big rip off. Next time Ill fix my own tire and get it right the first time.. Users/Johnramp

20110905 22:51:30 nbsp Our experience of B&L was very different in a time of need scenario. We had just finished running the 10K Labor Day Race and found my tire was flat. We walked over to B&L and asked if we could buy a tube and change the tire. Nowhere posted does it say, you cant borrow tools. We werent asking for a headset wrench or cone adjustors; we only needed one tire iron. They shook their heads saying Nope. Well change it for $10 though. This neighborhood store wanted to take advantage of us when we were most in need and low on cash. We promptly walked out and over to Kens Bike and Ski and bought one there. I will never walk in B&L again and will send all my friends to Kens where they didnt hesitate to loan us a tire iron. Users/DebWestergaard

20111009 19:18:18 nbsp Went there today. I felt as if Ive been discriminated. I went in first and this other girl walks in and she got service before i did just because she had a more expensive bike. Well sorry some jerk had to go and steal my cheap bike seat and seatpost.  After that I proceeded to stand in awkwardness for the next ten minutes with a seatless bike when obviously at least three different workers saw me and yet none offered any help to me. I walked out. I am very disappointed in their service especially when Ive seen some very great customer service comments on here.   Users/HyeRin

20120125 20:19:35 nbsp Stopped in today to buy parts for my used, dingy bike.  Friendly, helpful staff that greeted me when I came in and were great at getting me what I needed and answering my questions.  Didnt make me feel like my bike was beneath them!  Thx! Users/sherrillstone

20120221 00:13:34 nbsp As a decadal Davis cyclist, I have sampled nearly every road and shop.  Today, Jesse at B&L affirmed my positive belief in downtown Davis bike shops.  With regard to my last bicycle repair, I am all smiles.  Thanks B&L for hiring Jesse and the other guys I interacted with today.  They were all cheerful and honest. Please make an effort to carry more combination locks. Users/bartbart

20120312 20:32:12 nbsp I went in today to get a quote on fixing my bikes brakes. I think someone who was parked next to me caught my brake cable on their bike and when they pulled away...they just kept pulling. Anyway, the staff was very friendly and Dante rethreaded my brake cable for free. They were very nice and I will definitely return for all my bike needs. Users/MichelleHV









20120614 10:19:05 nbsp Went here for a bike repair and could not have been more disappointed. First it took 45 min to drop off my flat tire because an estimate was necessary for me to sign. However during said estimate numerous customers were helped and rang up for purchases. I asked if they could just call me with the estimate but was refused. So finally left with an estimate for a flat tire and came back the next day for pick up only to find the front basket not attached properly to the wheel because they couldnt figure it out.I was told that the last person had done it wrong, we had the basket attached at this shop by these same people. They attached correctly after I explained how. All in all my flat tire took 2 hrs for drop off / pick up. Considering that the reason I paid someone to do it was to save time, it was all rather ridiculous. I am going somewhere else next time with better knowledge and customer service. Users/Zeeba

20120717 20:48:19 nbsp Comment on the employees! I biked over to use their free air pump, and caught my leg on my fender as I was getting off my bike. This gouged my leg, and I started dripping blood. I walked  to the doorway, Eric saw me (but not my leg) and asked if I needed anything. After I asked for a paper towel or bandaid, he saw my leg, rushed over and opened up the bathroom for me to clean up. James (another very kind employee) brought in my bike so it wouldnt get stolen. Eric pulled out a massive first aid kit, gave me alcohol swabs, found gloves, and bandaged my leg. No joke, he bandaged my leg! The entire time, James and Eric exchanged the cutest and most hilarious banter.(sidenote: I do not know them personally, they told me their names as I was leaving.) (sidenote#2: if bike shops arent their calling, I suggest they start a sitcom.) All in all, the greatest customer service I have ever gotten, especially considering I bought nothing. And it was the best surgery I have ever gotten in a bike shop. Users/Kaylaaa

20120805 02:13:34 nbsp I have had nothing but positive interactions with the staff at B&L. When I dropped off my bicycle for a tune up, the staff member (I cant remember his name) asked me questions about my biking habits since I wasnt sure what I needed to get done. He explained each of his suggestions in detail, and being familiar with basic mechanics all of the suggestions made sense. He didnt try to sell me on maintenance that wasnt necessary and he alerted me to mechanical issues to pay attention to as I commute and cover 100+ miles a week.

As for some of the negative reviews here  I think a misunderstanding of liability and basic payment practices are the chief complaints. A business that touches and repairs a mechanical transportation device (be it car, motorcycle of bicycle) has a legal obligation to make repairs that are necessary for the proper and safe functioning of your bicycle. If, upon making the requested repairs to your bike, a mechanical flaw is found that makes the bicycle unsafe for you to ride, the business MUST fix this problem before giving the bicycle back to your possession. This is why you are provided with an estimate. If you read the estimate and the legal language, this is spelled out for you most of the time. I cannot say that my estimate said this because I didnt check for the language. I didnt check for the language because I understand that mechanical flaws that are discovered and deemed required will be fixed and those charges will be added to my bill.

In addition, most estimates include a clause that states if you refuse to pay your bill, the business will legally retain your property until payment is rendered within 30 days. After that period, the business has the right to keep your property and do with it what they please. This provides the sometimes very necessary incentive for people to pay their bills. This is commonly referred to as a lien and is completely legal. Given that the cost of repairs on most bikes wont exceed the cost of the bike, there is no reason for a business to not keep your property and pursue small claims court to recoup the cost of repairs. Small claims court has no purpose in this industry, and a lean is far more effective at safeguarding the business that has provided a service to you.

I hope this helps customers understand the intent behind policies and understand that its not a slight to customer. The policies used by B&L are standard of a repair based business and reasonable when viewed by how a business can be affected if they do not think ahead. At the heart of these policies is the intent to provide safe service to you as a customer and safeguard their business to continue operating in the future, which is good for the business, good for Davis and good for their customer base as a whole.

B&L  You have a loyal customer with me. Keep up the outstanding work and Ill be seeing you in the near future for my next tune up! Users/MichelleKoehler

20121011 06:19:18 nbsp If you want a cruiser, a 50 lb/ bike that usually female college students like, come here.  If you want a sports bike, hybrid or road, dont bother.  They have very few bikes.  This shop is clearly tailored to nonserious bike riders. Users/DavisLurker

20130423 18:52:07 nbsp Great shop!  I once had a flat tire and didnt have the right pump, and after a call to B&L they actually arranged for a family member to come help me out.  When the inner tube popped pumping it up, the person helping me left, got a new one, came back and replaced it at no charge to me.  I cant say Ive ever had customer service like that before, and Ill always go back. Users/ChrisFarmlett

20140530 11:03:30 nbsp My thanks and appreciation to mechanics Blair, Dane and Paul, for getting my bottom bracket replaced after Freewheeler gave up on it.  Blair for assuring me they could get the old stuck cup out for sure, no matter that the other shop had failed; Dane for cautioning me that there might be an extra labor charge if it was especially difficult, and that I should consider whether the bike was worth it; Paul for figuring out how to do the job quickly and efficiently, without complaint and without extra charge, and even describing his technique to me afterwards.  Very impressive staff! Users/stephthrasher
