

Bay Area Rapid Transit. A wiki:WikiPedia:Heavy_rail heavy rail system that runs both above and below ground (and water). It serves San Francisco and most of the East Bay. Parts of the Bay Area not served by BART are Marin, Sonoma, Solano, and Napa Counties, and the Peninsula south of Millbrae.

BART is accessible across from the Amtrak station platform in Richmond. If youre heading west and get off the Amtrak train in Richmond, you have to go downstairs, through the BART ticket counter, then back upstairs via escalator to access the BART platform. Amtrak also connects with BART at the Coliseum station in Oakland.

Amtrak has its own connector bus to San Francisco, for which you buy a single ticket from Davis. To reach San Francisco from BART in Richmond, board any inservice BART train. If its destination is  Fremont, you have to change trains at MacArthur station. Most of the time, about half of the trains from Richmond go directly to San Francisco. A ticket agent who can explain the relevant options is usually on duty, or visit the Amtrak page for more details. Amtrak sells $10 BART tickets for only $8 the Cafe Car. You can buy up to a maximum of two tickets per trip.

If you are riding Amtrak to get to a BART station south of Oakland, especially Dublin/Pleasanton, you may wish to purchase your Amtrak ticket to the Oakland Coliseum station and transfer to BART there. However, make sure the Amtrak train goes there at the time you are travelling, as not all Amtrak trains go that far. For Castro Valley and Dublin/Pleasanton, you avoid two BART train changes by changing at the Coliseum station. For Berkeley, San Francisco, San Francisco Airport, and intermediate destinations, Richmond is the best station to transfer to BART.

The closest BART station to Davis is the North Concord/Martinez station.  However, if you are driving to BART from Davis, it is worthwhile driving an extra 3.5 miles and starting your BART journey at the Walnut Creek station.  The Walnut Creek station, as opposed to the North Concord/Martinez station, is right off of the freeway.  Also, fares to locations of interest (i.e. SF, Berkeley, Oakland, anywhere except Pittsburg..) will be substantially cheaper to/from the Walnut Creek station as compared to the North Concord/Martinez station.  Without traffic (repeat, WITHOUT traffic), it takes just under 1 hour to drive from Davis to Walnut Creek BART Station. That time will go up substantially during the holidays and during commute hours. It can take nearly five hours Christmas Eve morning to get from Davis to Walnut Creek. Thanksgiving can run six hours. Other holidays can be equally insane on I80.  Keep in mind the travel time to the station on holidays.

Note that in 2009, BART stations will no longer have free parking, and will charge $1 per day.

Note that BART stops running fairly early at night.  The final train every night goes through San Francisco between about midnight and 12:30 AM, through Oakland between about 12:30 AM and 12:45 AM, and arrives at the Walnut Creek station at 1:04 AM.  If you plan on attending an event that ends late (especially something like a concert that could run late past the official end time), it is a good idea to know the last BART available.

Amtrak lists BART connections and schedules on their site, making it a one stop shop for planning Bay area trips sans car.  Bicycles are allowed on BART, except during certain peak hours or on crowded cars.

wiki:WikiPedia:BART Wikipedia Entry



20050629 15:30:11 nbsp I use BART to go to the city, but it really pains me.  Its ridiculously overexpensive.  If youre going in a large group of people, its often cheaper to just drive and even pay up to $25 for parking. Unless theres some certain event, it could possibly be quicker too, depending from what station/line youre on. And obviously, the time of day for the traffic conditions.  If only it would be a MUCH more efficient and cheaper public transport, such as Sydneys http://www.cityrail.info/ CityRail.  God I miss that.  Its used much more than Bart, and it can comparatively be less than a quarter of the price. Users/EdWins ES
    Or like Washington D.C.s Metro system.  Now thats public transitI could easily get from one end of the city to the other in minutes for like a buck and a half.  The Metro makes BART look like some Carthaginian pachyderm,
      popping you for five bucks each trip.  Users/LeightonHinkley TheEl
    Do you realize that the Washington D.C. area is MUCH SMALLER (and more densely populated) than the Bay area geographically? Users/AlexanderWoo
    http://www.nlc.org/about_cities/cities_101/187.cfm No kidding?  Im talking about getting around within the city of San Francisco itself, not running from Fremont to Richmond.  For the former, BART is worthless.  Users/LeightonHinkley The El
    BART is really a semisuburban commuter system; the public transportation system for getting around SF is Muni.  Now I agree Muni sucks.  But the same argument still applies: Georgetown to the Capitol is probably the distance from the Financial District to the Castro?  And most of SF is 3 stories high or less, and moreover, SF residents work all over the place, not mostly in one downtown.  Users/AlexanderWoo
    I grew up in DC, and having visited London, NY, Paris, etc, Id hardly hold up the DC Metro as an excellent rail system. But these arguments are just wrongThe Washington D.C. metro area (which the DC Metro transit system serves) is actually larger than the Bay Area geographically if you exclude the far ends at Pittsburg and Fremont. It is also less dense overall (building height is restricted in DC to 130 ftcan you say that about SF?). Furthermore, Tysons Corner, Bethesda and Arlington are all served by Metro and all outside the city, but number among the largest hiring centers (and commuter destinations) in the country. But the real reason BART isnt as convenient as many other light rail systems is because of the terrain. DC is relatively flat, and it was by and large simple business to bore tunnels for the metro (excepting a few challenging sections under the Potomac River). Because the core of SF is anything but flat, building a truly adequate subterraneanrail system would be prohibitively expensive. Just be grateful were not as bad off as LA!  Users/ThomasHandley TH

20051121 22:47:09 nbsp I disagree. BART is worth the money for its reliability and speed. It does get a little expensive when you cross the Bay Bridge, but it is hardly more expensive than driving. If youre going downtown or to the Civic Center, definitely take BART over driving. If youre carpooling with enough people, then okay, that might be worth it. Only because youd be distributing the cost, though. Users/NumiaCairaguas
   Have you used comparable transport elsewhere?  I forgot to mention DCs metro, I grew up there, nice call Leighton.  BART is ridiculous, those two blow it out of the water.  Its definitly overpriced. Users/EdWins ES
   Yup: http://sfgate.com/cgibin/article.cgi?f/c/a/2005/05/01/BAG32CIDA21.DTL  (From the SF Chronicle:  BART fares poorly in cost comparison.  Rail riders elsewhere pay less, even before proposed increases May2005).

20051122 03:55:16 nbsp I used to take bart between balboa and embarcadero every day for school. One day, i fell asleep on the way home and ended up in pitsburg. Be carefull of falling asleep on bart. Users/AlexEley

20051123 14:11:00 nbsp how many miles is the DC line?  I recall that it was a nice system, but not many miles of line.  (especially compared to BART) Users/RocksandDirt
   Even before the underconstruction silver line is complete, the DC metro covers 126.71 linear miles, versus 104 for BART.  Users/ThomasHandley TH

20051123 17:30:00I dont really remember about DC, been too long. But as I said, http://cityrail.com/networkmaps/mainmap.jsp City Rail blows BART out of the water.  Baseline much cheaper, and more of a range.  Sydney also has bus services which a lot of people use in conjunction with the train. Everyone in fact; nobody really drives to work.  Its way more flexible. Student prices, yay. Family fares  If the adult has more then one kid, he only has to pay for one of them. And kid defines up to age 16.   A city ticket counts all 8 city stops, and you can go from one to the other and back and forth as much as you want.  Whereas its a $9.40 round trip to Embarcadero from Dublin, and more if I want to go to the Civic center. From Fairfield to the City costs 3.35 (US dollars) and thats a 45/50mile round trip.  Also, a ticket really is a boon to tourists.  Discounted entrance to the zoo, the Olympic Stadium, aquarium, and other things, like ferries (even commuting ferries).

While SF does has muni, muni is for city only.  True you can take Caltrain and other things, but it doesnt add up the same way.  Look at anyone in the East Bay trying to get somewhere.  Sydney has it down damn well, its far cheaper, far more efficient, used by everyone, not plagued with the problems BART and Amtrak have with moola, and its not just city/local transport. You can really use it to get places.  Check the http://cityrail.com/networkmaps/mainmap.jsp map again. If you ever extensively use CityRail (and you will if you ever visit Sydney), youll never be able to take BART or anything else again.

You can take a train right from the Domestic Terminal of the airport out towards the http://www.bluemts.com.au/tourist/ Blue mountains. The farthest stop on that particular line that I can remember costs $34.80 adult, $19.70 student. Aussie Bucks. Thats  $25 bucks for a one way adult, $14.3 for a student.  Airport to the mountains. Thats 240 kilometers. From the SF airport to Dublin costs $7.10. This is why I also dont like Amtrak.  It costs me 12 or 13 bucks to go from Davis to Martinez  one way, some 40 to 50 miles?  Give me a break. Id much rather go to those beautiful mountains and take a http://images.google.com/images?hlen&qjenolan%20caves&saN&tabwi cavetour.  Users/EdWins ES


20080701 14:30:47 nbsp so, comparing BART to city rail:
Lidcombe to Circular Quay 12.7 miles single (peak) ticket $3.63USD, round trip (peak) $7.26, roundtrip (offpeak) $4.96
Downtown Berkeley to Civic Center 12.7 miles $3.40
Some notes: Berkeley to downtown is going to be expensive and take a while to drive b/c of the Bay Bridge. Also, BARTs infrastructure is expensive in that area on account of the transbay tube. BARTs fares are expensive compared to other vendors (even though their peak oneway is less than City Rail) but BART has a lot of challenges to contend with, such as crossing the bay and making sure all structures are earthquake proof.
That being said, this comparison suggests that BART is very competitive in one way peak fares, but City rail (an other vendors) offer cheaper services when one is traveling off peak, or when one procures a multitrip ticket. Perhaps then, BART could boost ridership and revenues by being more creative with their fare structure. Either they can offer multiride tickets, or perhaps they can reduce the fare of offpeak travel, especially considering the fact that autocongestion is lower during nonpeak times, making car travel more attractive then anyway Users/briangoldner
