
Bicycle Helmets are strongly recommended, by doctors and by city and campus officials, for anyone who bicycles in Davis or anywhere else.  They are also legally required in California for bicyclists under the age of 18.  Head injuries are the biggest cause of death in fatal bike accidents and a major type of serious injury in nonfatal bike accidents (http://www.nhtsa.dot.gov/people/injury/Newfactsheet03/BicycleHelmetUse.pdf NHTSA Fact Sheet). Bicycle helmets prevent most head injuries and lessen many others.  Doctors can repair many kinds of damage after a bicycle accident, but they cannot repair brain damage.  Even a simple concussion is a type of brain injury; whether or not it leads to hospitalization, it may still involve insidious (meaning medically undetected) longterm brain damage.

Make sure that your bicycle helmet is in good condition.  Throw the helmet away if it is damaged in an accident, or if it is weathered; replace it at least every five years.  Sizing the helmet and adjusting the straps are tricky but important steps; the helmet and strap should be snug without feeling tight.

 The helmet debate 

Just as with motorcycle helmets and seat belts, there is some public debate as to whether it is important to wear a bicycle helmet.  The scientific consensus, based on both casecontrol studies and ergonomic theory, is that bicycle helmets are important.  Exactly how important they are and how to best design a helmet are a matter of continuing research (http://depts.washington.edu/hiprc/practices/topic/bicycles/helmeteffect.html University of Washington Med school review).

Much of the debate is about bicycle helmet laws rather than about the merit of helmets.  There is a libertarian argument that laws should not unduly protect people from themselves.  This is one reason that bicycle helmets are not generally required for adults in the United States, and it is part of a continuing debate over motorcycle helmet laws.  Few people would argue that children should not be protected from themselves, and that is why bicycle helmets are required for children in California.

It is true that bicycling is about three times as safe per mile of travel than walking in the US, as measured by fatalities (http://www.vtpi.org/puchertq.pdf Pucher and Dijkstra, 2003). That makes bicycling less safe per hour, or per trip, because bicycling is about 5 times as fast as walking. Protecting pedestrians and bicyclists are both major public safety challenges that require many partial solutions. Even though helmets are not a good solution for pedestrians, they are an important solution for bicyclists.

It is also true that the rate of reported head injuries increased from 1991 to 2001 in the United States even though bicycle use fell in the same period (http://bicycleuniverse.info/eqp/helmetsnyt.html New York Times, July 29, 2001). A common time trend does not imply cause and effect and it is open to many possible explanations. For instance, doctors may diagnose a type of injury or illness more thoroughly or more liberally over time, so that a problem appears to get worse when it is actually only getting reported more.

The http://en.wikipedia.org/wiki/Bicycle_helmet#The_helmet_debate Wikipedia page on bicycle helmets is a better place to pursue the general debate over bicycle helmets and helmet laws than DavisWiki.  The comments section of a DavisWiki page is a better place for debating than the main section, then gather them up and put them in the top as cogent points.  Of course, since there are no rules  except that you must wear a Wiki helmet when debating on the wiki  feel free to ignore that.


(undated) These testimonials have been moved to the comments section.

  I was riding with a group of people traveling about 1518mph on a county road. One guy hit a bump that caused him to lose his grip and fall forward onto his handlebars (he had been talking and pointing at something, leaving one hand on the grip). When the rear wheel hit the same bump, it bounced up and he landed headfirst on the pavement. Two seconds. He ended up with a cracked cheekbone, broken nose, a concussion, and abrasions on his face. While we waited for the ambulance to arrive, I examined his helmet. The foam padding, where it rested on his forehead, was mashed flat. I shudder to think what mightve happened had he not been wearing it. I dont know what the statistics say, but seeing that was enough to convince me that wearing a helmet is wise. (So is medical insurance...he didnt have any, unfortunately.) Users/DukeMcAdow
  I have had but two encounters with cars in over 25 years of riding in Davis. In the latter, on 10/30/07, my helmet broke when it smashed into someones windshield  probably saving me from a bad concussion and possibly saving my life! In the former, I was caught by someones car door and left much of my forehead skin on G Street. (That might have been the last time I rode without a helmet!) Okay, neither accident happened on campus, but they have curbs, bollards & other nogginmushing objects there too. Bicycle helmets are only for people who want to live with intelligence  if you dont mind a significantly higher chance of traumatic brain injury, dont worry your pretty little head about one. (Thats an attempt at grim cynicism!)  Users/DougWalter
  Given that Ive received a concussion from a solo bike crash while I was wearing a helmet, I fully support the wearing of helmets to mitigate head injuries.  The idea of not wearing a helmet just seems absurdly stupid to me, especially if the reasoning is because it looks stupid or because I feel stupid.  You could end up a lot more stupid if you crash while not wearing a helmet. Users/BrettHall


20071026 15:01:16 nbsp Bicycle helmets are only for professors.  They have so much invested in that noggin, its actually worth protecting.  Otherwise, bike helmets arent cool. Users/BrentLaabs
  Notwithstanding many professors are still wearing the same helmets they had 10 or 20 years ago, which have long since deteriorated to the point of uselessness.  Which brings me to my next point:  helmet standards were improved in 1999, and every helmet manufacturer recommends replacing a helmet every 34 years or after an impact, whichever comes first.  The foam becomes brittle, so instead of crushing like its designed to, it simply transmits the force directly into your skull.  The paramedics will NOT thank you for using an old helmet if you crash. Users/BrettHall


20071102 22:29:48 nbsp The amount of misinformation on this site regarding helmets is ridiculous. Several people here have suggested that helmets save lives when there is no evidence whatsoever that would support such an assertion. In fact, to the contrary, research has shown that as the rate of helmet use goes up, the rate of head injuries rises as well (http://bicycleuniverse.info/eqp/helmetsnyt.html). This is not at all surprising when you consider that helmets which meet current standard are only designed to prevent direct hits to the head at speeds of 12 miles per hour or less. Consequently, the most a helmet can do is to save you a few stitches or bruises if you fall off a bike; helmets offer practically no protection in serious accidents where ones life is at stake.

Furthermore, and perhaps most importantly, cycling is no more dangerous than walking(http://www.magma.ca/~ocbc/hfaq.html#A8). I am sure none of you wear helmets when you walk, why then would you wear one when riding a bike?  Users/Maitl
  12mph is likely average or above average for most people riding on campus and in town (see also: everyone who is on department store or cruiser bikes).  Which, by what Mait claims (which is indeed correct), is exactly the speeds for which helmets are designed.  No, a helmet will not save you if you get hit by a car (very little will).  But it can help immensely if you hit another cyclist, or if you cause yourself to fall and your head hits an object more solid than your skull. Im as opposed to misinformation as you are, so youll need a much better antihelmet argument than it wont save you if your life is on the line wont fly with me  because helmets CAN and DO prevent serious injuries (see also: the concussion I suffered while wearing a helmet, in a crash where only I was involved  no, my life would not have been in danger without the helmet, but the helmet did save me a bloody head and trip to the hospital). Users/BrettHall
   it can help immensely if you hit another cyclist, or if you cause yourself to fall and your head hits an object more solid than your skull: True, but the risk of becoming involved in such an accident and incurring a serious head injury is fantastically low. According to the US center for disease control and prevention, less than 1% of traumatic head injuries result from riding bikes. Given such an incredibly low risk, why should one wear a helmet, even if helmets are effective? Walking is just as dangerous as biking (if not more so), and helmets could undoubtedly also mitigate injuries resulting from walking, but would you wear a helmet each time you stroll through your neighborhood?
    The biggest difference between walking and biking is that when walking your feet are on the ground and your hands are probably free; while on a bike your hands are gripping the handlebars and the momentum of riding means that if the front wheel stops abruptly YOU will continue in an arc forward and down (being thrown over the handlebars and likely landing on your head). Users/LoisRichter
   youll need a much better antihelmet argument than it wont save you if your life is on the line: That was only part of my argument. Did you overlook the part where I said that the rate of head injuries has gone up as the rate of helmet use has increased? Did you click on the links I provided? The one leading to the bike helmet FAQ should have been particularly informative.
   helmets CAN and DO prevent serious injuries: Helmets can also give their wearers a false sense of security which can increase the risk of injury. This is known as risk compensation and it may be one of the reasons why widespread helmet use has done nothing to lessen bikerelated injuries. Another form of risk compensation may also occur as a result of wearing a helmet: according to a recent study, car drivers tend to drive less cautiously around helmetwearing cyclists. (http://www.sciam.com/article.cfm?chanIDsa029&articleID778EF0ABE7F299DF3594A60E4D9A76B2)
    From that same article: New York City released a report on bicycle deaths and injuries: 225 cyclists died between 1996 and 2005 on New York streets; 97 percent of them were not wearing helmets. Of these deaths, 58 percent are known to involve head injury, but the actual number could be as high as 80 percent.  Davis isnt New York, of course, and our biking is seldom in direct competition with autos.  But it still seems to me that wearing a helmet is safer than not.  A helmet may not stop my crashing, but it may save me from head injury.   Users/LoisRichter

  Bicycling is safer than walking on a perhour basis: http://www.bicyclinglife.com/SafetySkills/answer1.htm
  Six times as many pedestrians as cyclists are killed by motor traffic, yet travel surveys show annual mileage walked is only five times that cycled; a mile of walking must be more “dangerous” than a mile of cycling.(http://www.bmj.com/cgi/reprint/321/7276/1582.pdf)
  On a perkilometer basis, walking is more dangerous than cycling: http://www.cyclinginstructor.com/cyclinginstructor.nsf/($Category1)/E0A4E09F5D74812F80257177004D9A87/$FILE/c2014.pdf?OpenElement Users/Maitl

  If you watched the Tour de France, youd realize how dangerous cycling can be. You said (without qualification) that cycling is no more dangerous than walking. Maybe thats true if you can walk 50 mph. Basically, youre saying that a head injury, when traveling at 5 mph, is no more dangerous than a head injury when traveling at 50 mph (or 20 mph, since thats a speed most of us can obtain when cycling). Users/KaiTing
   If I was to watch the Tour de France, I would realize how dangerous bicycle RACING would be. The Tour is a race which is completely different from the short and relatively slow bike rides that the average cyclist undertakes. There is simply no comparison between my daily ride to class and Lance Armstrongs arduous, 3000 km trek through France; hence, the Tour de France says nothing about what the typical cyclist experiences. Furthermore, even if watching the event were a substitute for hard statistics and research, it still wouldnt help your case. According to the online encyclopedia Encarta, accidents resulting in serious injuries or death are rare and only three people have died in the tours 100+ year history.Users/Maitl
   Have you watched Nascar lately?  Makes me scared to step inside a car!Users/JeffShaw

  If wearing a helmet makes me at all safer in terms of the outcome of an accident then I will do it. By the way, your links refer to observational studies which can not be used to support the cause and effect relationships your arguments imply.Users/ScottMorgan

20090802 12:17:21 nbsp Ive noticed that the students around Davis (18 and younger, not the students at UCD) wear helmets that are solid, almost spherical, appear to be made of metal or a hard plastic, and have no ventilation.  Everyone over 18 wears styrofoam helmets.  Anyone know why the kids are wearing different helmets than the adults?  Is there a law about this?  Do they offer more protection?  It doesnt seem like it would be much fun to wear a helmet with no ventilation in the Davis summer heat... Users/IDoNotExist
 The solidish helmets are skateboarding helmets. Theyre fashionable for one reason or another, despite the fact that they suck. wl
  More often they are BMX helmets.  Skateboarding helmets are designed for extremely lowimpact, repeated collisions, and do not meet CPSC requirements for bicycle helmets (they spread the impact, rather than absorbing it).  BMX helmets look similar to skateboarding helmets from the outside, but include the same crushable closedcell foam found in regular bike helmets.  The law requires riders under the age of 18 to wear a CPSCapproved helmet.  And yes, BMX helmets have little ventilation compared to other styles. Users/BrettHall

20090802 14:11:30 nbsp So do they make regular, ventilated helmets in kids sizes too, or do the kids just have the BMX style helmets available? Users/IDoNotExist
  Regular helmets are available in youth sizes.  Baby helmets (meeting requirements for ages 1+) are giant bulbous things that arent ventilated, but the kids wearing them are also not exerting themselves (and need more protection).  So basically, when the kids old enough to be riding a bike instead of being a passenger, there are ventilated helmets to keep the head cool and protected.  Well, cooler, anyway.  The BMX style is more popular among certain groups of youths, though.  Answering why would require a graduate thesis. Users/BrettHall

20100226 23:42:18 nbsp I once flipped over forward on my bike.  My head bounced around three times on the pavement  I shudder to think what wouldve happened if I didnt have my helmet on me.

Best part besides being alive?  My bike survived and still works to this day!  Compared to my Target bike in freshman year, which crumpled as I was biking uphill one day. Users/AlexanderHo
