



The Boardwalk is an 8unit townhome complex located in 2 buildings at 805 and 819 H Street. These apartments were built on the former site of a plant nursery: Davis Nursery, a retail nursery owned by the Basinger family for more than 40 years. There is a unique goldtipped variety of Deodar cedar in front (visible in the photo above) which was planted by nursery owner Tom Basinger. The apartments are located directly across the street from the freight train tracks. The freight train comes by a few times each day (much less frequently than Amtrak), typically only during daylight hours. The complex is close to bus lines, bike routes, markets, restaurants, and shopping centers. Its about 10 blocks from UCD campus.

The townhomes have either 3 or 4 bedrooms and 3 bathrooms (depending on the unit). All units have: energy efficient features (i.e. soundproof dualpane windows, highgrade insulation walls, new appliances), individual indoor washer & dryer, walkin closets, heating & air conditioning, hispeed internet (Cat5) wire to every room, private covered porch area, mature trees, and unassigned parking in a lot. Overflow parking can generally be found in the street.

The following rates were listed here by a Boardwalk Apartments representative:
 In 2010, base rent was between $2,000 to $2,600 per month.  Rent includes 12 parking spots per apartment and city utilities (water, sewer & trash).
However, comments below indicate that management in fact demands additional monthly payments for utilities and for dedicated parking spots, a few of which are covered garage spots.  Consider yourself warned.


To learn more about rental housing in Davis, check out our Housing Guide as well as our Apartments pages.



20071212 01:37:39 nbsp How exactly does he check in?  It may not be legal.

And is it just me, or is two grand a month pretty ballsy for an apartment with such a good view of the tracks? Users/MelissaH

20081030 21:30:54 nbsp LOL  I forgot about the extra fees. Want one of the 3 garage spots? $50 a month. Want to rent a washer/dryer? $50. Dog? You guessed it  $50. Users/sbyun

    20090319 08:57:23 nbsp I read some of these comments and have to say my experience with this mgmt. team has been spectacular!  They are quick to respond to any requests that are needed and just charge the market rate (ppl. are not forced to rent here, lol)..anyhow, this just looks like a unhappy person looking to take out their issues on somebody, so they write something negative. Users/davisaggie

    20090417 15:34:53 nbsp These comments seem outdated since im finishing my year here at these apts. and theyre just great (theres a reason why they have a waiting list)..overall, Ali is real responsive to anything that comes up and is a real good handyman.I highly recommend this place over Tanglewood and Willows which are places I was at before. Users/darthvader2010

    20100517 15:35:32 nbsp Ive had a great experience here where its nearby the campus and downtown with ample parking compared to my friends other areas of living...staying here another year. Users/Baron

20090923 11:18:37 nbsp I lived there and the place was pretty nice, but the train was really loud and came early in the morning. The worst part was the management, they were inconsiderate and rude. They would go back on their word and would not allow you to put anything outside your apartment if you lived in the apartments on the street. Overall I would not recommend these apartments because the places were over priced but more importantly Ali was a awful land lord! Users/davisalum19

20100524 16:38:26 nbsp This apartment complex is INFESTED with cockroaches.  They are on the walkway in between apartments, swarming by the trash containers, and in the upstairs and downstairs of the units.  We have had cockroaches all year, and are currently finding about 1 per day in our kitchen.  At night, there are dozens on the walkways, especially near the recycling unit in the parking lot.  We have had cockroaches crawl up drains in the kitchen sink, downstairs bathtub and upstairs bathtub.  If you want to live here, be prepared to step on a lot of bugs.   Users/DavisGrad10

20100609 11:52:10 nbsp Thank you for your comment DavisGrad10.  An exterminator has been ordered and cleaning the interior of units is the tenant responsibility.  I can recommend a cleaner if that helps. Users/sritern

20100609 12:00:03 nbsp Same person (user: sbyun) commenting for over 2.5 yrs.  The comment of he frequently checks in applies to the person writing the post.  It is unfortunate s/he had a bad experience, but the comments are outdated and is harassment/personal drama which is not necessary on wiki. Users/sritern

The following comment was initially deleted because it does not appear to be a genuine comment from a tenant. 
20100608 23:10:06 nbsp I am a happy renter and highly recommend this place! The new management, building amenities, money saved on energy efficient utilities, quite neighborhood with extra insulation and proximity to campus are all great. I agree parking is easy with additional shaded parking on the street. Have not had any issues with cockroaches. Any normal cleaning of sinks, mopping, vacuuming, etc. would prevent attracting insects. Users/ResonsibleStudent

20110225 11:48:56 nbsp Does anyone know the sq footage of these apartments??  Both 3 and 4 bedroom total sq. footage?  Thank you!  Users/FranThompson

20110503 13:37:13 nbsp I dont understand the awful reviews about Ali.  He really is a very approachable manager.  As a proper tenant, we did a thorough inspection of the apartment when we moved in and he fixed all problems with any appliances at the time.  Even when we were the ones to break the garbage disposal, and he told use we would have to pay for the plumber, he ended up fixing it himself with no charge. I by mistake even underpaid my rent once, just a typo on the bank transfer. He contacted me and did not charge a late fee.

I am up before 6am every day and the first train does not come until just after 6:30am. I pretty much always find parking right in front of the apartments.  I actually prefer to park on the street as apposed to the parking lot since the street is shaded.  As far as cockroaches are concerned, I have never lived in an apartment/house in davis that did not have cockroaches at the very least outside the house.  The one time I did find two roaches in this apartment, I contacted Ali and he put me in touch with the person to come spray the house and I havent seen one since.  Other than that, I might see one occasionally outside, but they are everywhere in davis.

He does come around the apartments to work on the garden and outside maintenance, but has never come inside our apartment without advance notice and permission.

For me its location is the best part, just a block from the Coop and three blocks from downtown.  If I was staying in Davis, I would renew my lease.  Even the girls who lived the apartment before us had been there for three years, I believe.    Users/DTahiliani

20120112 14:10:50 nbsp I have lived at this townhome complex for slightly more than six months, and in light of the many negative reviews of the dwelling and owner/operators, it seems appropriate to provide an account of my experience living at the Boardwalk Apartments, and particularly, to address some of the more sensational claims made in previous posts. First, I have enjoyed, tremendously, living at the Boardwalk Apartments. Ali has never related to me in the manner described above  I have found him and his wife Michelle to be fine, pleasant, reasonable people nor has he ever entered my apartment without my consent. Second, I have NEVER seen a cockroach in my apartment. In fact, it should be noted that the cleanliness of my unit (I cant, obviously, speak as to the condition of the other residences) was the principal reason that I decided to live here. Second, while the train does often pass by this property a couple of times a day, most often it passes by during normal waking hours (between 8 and 5 oclock)) and usually without much fanfare. I urge anyone reading this to be mindful of the fact that ones perception of what constitutes a nuisance is a fairly subjective sort of thing. Personally, I do not find the train operations to be burdensome in any way. Last, I have paid a mere $100 each month that I have lived here, for water, sewage, garbage and electrical service. In Davis, that is a very reasonable sum of money to have to pay for such services. As for the parking, Ali and Michelle have in place a policy that provides the tenants of each unit one parking space, at no additional charge. Also, those who renew their lease are afforded the opportunity to acquire an additional, assigned parking space if space becomes available. Upon reflection, I think one would do well to realize that this is a very fair policy. For those that are deliberating about whether to live at the Boardwalk Apartments, they absolutely warrant your consideration.Users/HoldenCaulfield

20120131 13:55:02 nbsp Zombiek: I am not Ali or Michelle Ghorbanzadeh, or anyone that they happen to be closely familiar with. I provided an account of my experience living at the Boardwalk Apartments, principally, because I found your account of living at the Boardwalk, and your experiences with Ali and Michelle, to be so remarkably inconsistent with mine. They have treated me well, so I thought it right to tell the users of this wiki, and anyone else that happens to peruse this site, my story. Its that simple. I use the pen name HoldenCaulfield as a way of protecting my identity, which, as evidenced by your handle of zombiek, I should think you would understand. It seems that I live in the unit that you once occupied, presumably with an individual by the name of S B (his mail often fills my mailbox.) If, however, you are still unconvinced, then I suppose you could inquire as to the location of the IP address of this post. I am, as I was when I first posted on this page, on the UC Davis campus, using a UC Davis wireless internet network. Youre not really going to suggest that Ali or Michelle have access to campus wireless networks, are you? Users/HoldenCaulfield

20120302 15:20:20 nbsp im thinking of maybe moving back to Davis for this summer. Are there and subleasers for $500/mo or less room? I was a prior student and feeling like being around the energy again.  Would not mind being back living in the apartment i was before. Users/ResonsibleStudent

20120610 15:45:34 nbsp After I first signed my lease, I was a little worried because I came across this site.  However, Ive lived in these apartments now for my second and third year of law school at Davis and find these comments to be exaggerated.  The apartments are very nice  two story townhomes, newly built with hardwood floors, and new appliances. Other apartments/homes in Davis are older and have a lot of problems  but these apartments are really nice for davis, clean, safe, and really close to all the restaurants.  Ali and Michelle will email/call you and try to give you an advance notice when they are showing your place as best that they can.  They do not just show up randomly and are not intrusive or overburdensome.  They look out for the residential community and try to keep the environment of the complex fun and student friendly.  I would recommend living here as long as you are not bothered by the noise of the train (which me and most of my roommates werent). Users/RabiaP

20120613 21:02:02 nbsp I had a very pleasant experience living in Boardwalk Apartments.  Its located in a very convenient location, all the amenities worked well and it felt very much like a home. Ali the owner was easy to contact and we had no trouble at all during our time there.  I was worried about roaches when I moved in as well but the unit was very clean and my rooommates and I all had a great time living there.  I would recommend it.  Users/kpearl
