
Updated Nov. 11, 2009

Graduate of UCD in International Relations back about the time the Berlin wall was coming down.

For the last about 7 years I have lived in Davis with my family.

You can find me here:
  facebook   http://www.facebook.com/brian.m.hiatt http://www.blogs.sun.com/brianhiatt
  blog  http://www.blogs.sun.com/brianhiatt http://www.blogs.sun.com/brianhiatt
  twitter http://twitter.com/BHiatt http://twitter.com/BHiatt







20091111 15:53:09 nbsp Welcome to the Wiki. Maps are automatically generated by the {{{Address()}}} macro. Look for the map icon on pages that have an address macro to the right of the page title. Users/JasonAller
