

The California National Primate Research Center is a secure research facility located at Pedrick Road and Hutchison Drive. It houses about 5,400 monkeys. The center is controversial to some (see Urban Art for example), leading some detractors to refer to it as the Monkey Farm. The $24 million facility has made recent discoveries about autism and conducts AIDS research (via SIV studies) among other scientific and medical projects.

The centers conference room, Room 1001 hosts weekly seminars on cuttingedge topics in biomedicine. The room capacity is 98.

The facility has had many monkeys die accidentally: one of the first fatalities to be reported occurred in February 2002, when a monkey crawled into a drain pipe and was killed by an impeller.

A monkey completely escaped from the facility in 2003, leading many to question whether UC Davis was competent enough to handle a Biosafety Level 4 Laboratory proposed biodefense lab. The biodefense lab, if created, would have infected monkeys with dangerous diseases such as anthrax and smallpox; an escaped monkey from the facility would have therefore posed a potential threat to the community (http://articles.sfgate.com/20030224/news/17476091_1_macaquemonkeyucdavis source). A higher level laboratory would have better security.

Outside the facility  but still part of the centers monkey population  seven (of eight in the room) longtailed Macaque research monkeys died on August 21, 2004 of heat exhaustion after a heater malfunctioned. The temperature rose from its normal 75 degrees F. to 115 degrees F. The event occurred in the Animal Resources Science building south of campus, which served as an overflow facility for the Primate Center. After this happened the overflow facility was shut down.

Stop Animal Exploitation Now!, an animal rights group, alleges that a whistleblower letter was sent to the USDA and UCD in July 2008. They say it listed identification numbers for 86 monkeys found dead in their cages and another 19 that were hospitalized in an emaciated or dehydrated state. They also claim that as a result of the USDA ignoring the whistleblowers letter, at least 36 more animals died. The university spokesperson stated he was unaware of any such letter or allegations.  In response, the animal rights group produced a necropsy report of a monkey that died in 2010 and was covered in mud and gravel.  The university spokesperson, Andy Fell, noted that  such a condition also occurs in the wild, and is due to normal monkey behavior, noting Unfortunately, they’re pretty rough sometimes.  The USDA, who has inspected the facility 19 times from January 1st to April 19th, 2011, said that they would investigate the claims in the letter. (http://www.davisenterprise.com/localnews/groupsaysprimatecenterusdacoveredupnegligence/ source).

There are pages from the CNPRC relating to http://www.primate.ucdavis.edu/animals/care.aspx animal care, http://www.primate.ucdavis.edu/animals/why.aspx why primates are used, and the http://www.primate.ucdavis.edu/science/units.aspx types of research done.

The California Aggie http://www.theaggie.org/2009/04/23/primatecenteraccusedofanimalabuse/ ran an article on 4/23/09 about a commercial being run by Stop Animal Exploitation Now!, an Animal Liberation Front animal rights group. The commercial uses footage from other animal research centers to paint a poor image of the Primate Research Center.

Some research at the Center involves deliberately inducing states of acute and chronic stress in primates, leading some to question the quality of care and consequently the value or worth of conducting some of these experiments. Some of the methods of stress induction include strapping the primates to immobilization devices for two hours at a time, daily, for seven days, to study the effects of stress upon the mind and body (http://www.ncbi.nlm.nih.gov/pubmed/20153584/ source).

According to the http://www.sacbee.com/2010/10/28/3138650/virussickenedmonkeysanduc.html Oct. 28, 2010, edition of the Sacramento Bee, a deadly new form of a virus infected about 24 titi monkeys at the center in May 2009, killing a total of 19 primates. A human researcher was also infected by the virus and yet never sought treatment for it, even after weeks of being sick, raising concern that she may have put the Davis human population at risk during that time frame. The incident was not reported until over a year later at a meeting of infectiousdisease specialists in Canada. UC Davis officials said they had no knowledge of the matter until the general news media reported on it.  It is currently unknown if the monkeys infected the researcher or if the researcher infected the monkeys. http://news.sciencemag.org/sciencenow/2011/07/newvirusjumpsfrommonkeysto.html?refhp Recent research suggests the virus may have possibility originated from a macaque monkey, and somehow passed along due to lax or ignored safety protocols, to the titi monkeys and humans.  However, the crossspecies transmission is incredibly interesting to the scientific community, and sheds new light on adenovirus research and the need to monitor viral outbreaks.

On July 19 of 2012, SAEN (see above) gathered to protest the facility. In particular, they made allegations of a primate recently having been found strangled to death on a bungee cord, as well as another fatality of an emaciated primate, apparently severely dehydrated and ridden with maggots at the time of death.

Stories of the facility being burned down in the 60s are an urban legend, possibly fueled by the 1987 Animal Liberation Front attack on Thurman Laboratory.  In fact, it was constructed during the early 1960s on the site of the old Pierce Ranch.

Leuren Moret, a controversial environmental commissioner in Berkeley and a UC Davis graduate, has stated that primates at the facility were subjected to mindcontrol experiments in the 60s. http://www.youtube.com/watch?vnzXYyhmvUg

 Criticism 

Selfabuse is a common problem among primates at the Davis Center.  Although the level of visible injury from selfabuse is most often nonexistent or mild, the behaviors can sometimes lead to severe selfbiting, hairplucking, or headbanging.  These traits are commonly found in the more sociallyisolated, indoor primates at the Center (http://www.informaworld.com/smpp/content~contenta907200745~dball~jumptyperss source). Not all indoor primates at the Davis Center are singlehoused, but at least some are.  Federal laws do not require singlehousing cages to be very large, and this can therefore be a source of distress for the primates.  Some of the cages holding adult rhesus monkeys are only 28 x 22 x 46 inches in size.  Not surprisingly, the Centers official website only shows http://www.cnprc.ucdavis.edu/animals/care.aspx pictures of the monkeys that are held outdoors.

The Davis Center sometimes conducts experiments designed specifically to inflict physical and/or psychological distress in primates that are not under anesthesia, in order to study the physiological effects of acute, severe, and/or chronic stress in human beings, among other purposes. The desired effects are sometimes achieved by forcing the primates into immobilization devices for extended periods of time, with individual sessions lasting a maximum of two hours each, for up to seven consecutive days. According to the Davis Centers official FAQ on its website, the Animal Welfare Act requires that any procedures causing more than slight or momentary discomfort be performed using appropriate painrelieving drugs. Thus, the procedures that deliberately cause physiological and/or psychological stress seem to be in violation of the spirit, if not the letter, of the Animal Welfare Act.

There is controversy as to what the letter even is.  As the American Humane Society puts it, Unfortunately, the regulations of the Animal Welfare Act include a definition of painful procedure but not of distress or distressful procedure. In 2000, the U.S. Department of Agriculture called on the public and the research community to comment on possible adoption of a definition of distress and to change the current pain and distress categorization system used by researchers to report to the USDA (http://www.hsus.org/animals_in_research/pain_distress/faq_pain_and_distress.html source).  In the absence of a definition of distress, this aspect of the Animal Welfare Act is, unfortunately, unenforceable. Nonetheless, the Davis researchers continually state that no primates experience pain or distress without anesthesia within their facility, even though causing the primates stress is the means through which the studies are conducted.

http://www.jneurosci.org/cgi/content/full/27/28/7386 Another study began by surgically creating lesions in the brains of rhesus monkeys, in an area of the brain known as the amygdala.  The experimenters then tried to induce fear in the monkeys, who were restrained in a custombuilt primate chair within an isolation booth capable of creating total darkness, with bursts of air, white noise, and sudden flashes of light.  The experimenters then performed the same fear induction methods on nonsurgically altered monkeys (so that the monkeys would learn the fear startle response) to see if the fear startle response continued after the monkeys had been surgically altered.  The stated goal of the study was to determine the role of the amygdala in acquiring, retaining, and expressing a fearpotentiated startle.  There seems to be a real question as to whether this end justifies the suffering of the monkeys.

Some people believe that the actions of the Davis Center are ethically problematic even if they are not illegal.  It is clear that the primates are suffering; after all, the stated aim of some studies is to measure the effects of fear or stress, and they must be suffering to some extent if they are feeling fear or under stress.  Reasons for believing these actions are unethical include: the belief that testing on any animal that can experience pain is unethical; believing that testing on animals of higher intelligence in particular (e.g., primates, dolphins) is unethical; or the belief that there may be some cases where the benefits of animal (or primate) testing outweigh the harms, but that the potential benefits of these particular experiments do not outweigh the harms caused.

 Federal Citations 

The http://theaggie.org/article/2011/04/07/federalgovernmentcitesucdavisforanimalcruelty California Aggie and the http://www.sacbee.com/2011/03/31/3516377/ucdaviscitedfortreatmentof.html SacBee ran an article stating the USDA has officially cited UC Davis for animal cruelty in at least one case involving a primate that was involved in four separate studies even though it had several health issues up to and including selfinflicted injuries. The USDA Animal and Plant Health Inspection Service denied a first appeal made by UC Davis. A second appeal is currently under review. If the appeal is denied, it could result in the loss of federal grants from the National Institute of Health which would severely hinder research potential in this field at UC Davis which relies heavily on this grant money for its funding.

The violation was originally suspected by an animal rights organization that had come across the monkeys death report. The group notified the USDA and requested an official investigation.

The Center has been http://www.sacbee.com/2013/03/08/5247944/ucdaviscitedindeathsof19.html cited yet again, this time for the death of 19 monkeys.

 Response 
The statement that severe self injury occurs at the center does not give any numbers, but implies that severe self injury is common. It also cites a study as evidence for that statement that is specifically centered around remedying such abuse, as the study is entitled Risk Factors and Remediation of SelfInjurious and SelfAbuse Behavior in Rhesus Macaques. This study is also not easily accessible to people who dont want to pay $30, or who arent attending the college, so it is difficult to validate the accuracy of the claims made about its contents.

It isnt surprising that the center doesnt show the primates that are held inside in smaller cages, because A) those monkeys are almost certainly part of active experiments, and scientists guard their proprietary information just as jealously as corporations do theirs, and B) the center needs to watch out for their PR just like any other public entity and as such they know such pictures will lead to Animal Liberation Front wacky animalrights groups creating http://theaggie.org/article/2009/04/23/primatecenteraccusedofanimalabuse misleading media to push their own agenda.

It is true that the monkeys in the center are subject to some studies where they experience stress. These studies are hardly intolerable, as they consist of either briefly being startled or being in a chair for 2hrs a day. Since it would skew results to conduct more than one set of experiments on a single monkey, one of those two forms of stress is all that the monkey would experience.

Beyond that, understanding the physiological basis and consequences of stress is extremely important, as stress in humans can cause a broad variety of problems, such as increased susceptibility to disease, impaired developmental growth, increased weight and the diseases that leads to, increased drug use, insomnia, and depression, among others. By understanding it. we can find ways of curing it.

The center is regulated by applicable state and federal laws, and numerous inspections, some of which occurred without prior notice, have shown the center to be well within the confines set by those laws. Those laws themselves are created by the people, and by their elected representatives, so if there is an aspect to the law that the public dislikes, then it can be changed. If you dont like the situation there, write your lawmakers, but also write to the scientists that work there, so that you can get an accurate picture of what they do for a living. They arent evil people, and they dont set out with the intention to hurt animals. Beyond that, listen to both sides, but keep in mind that both sides have an agenda to push.

Security

Much of the defense/security is designed to keep humans away from the monkeys so the monkeys dont catch human diseases. Even when they arent serious health hazards (like the common cold), catching a human disease could seriously skew research results.   Visitors have to show that they dont have tuberculosis.



20051107 10:36:50 nbsp Yeah, I know. I went there once, and I had to get a paper from my doctor saying I didnt have tuberculosis. Users/NickSchmalenberger

20051107 11:56:04 nbsp This page is generally skewed against the CNPRC. It lists several cases of primates dying because of human/machine error and only a passing reference to the extraordinarily beneficial research they do. Ill clean this up later, try to unbias it. Users/JesseSingh
   The only reason it lacks is because those who know havent added.  There have been several people over the years who have commented Im going to add some positive info, and none ever did.  Please, please add some info.  Users/JabberWokky jw

20070426 15:16:22 nbsp I know someone who works here, good times Users/StevenDaubert

20071226 22:32:34 nbsp http://www.ted.com/index.php/talks/view/id/76 Users/Easan

20080331 17:48:56 nbsp The page faults Primate Freedom for being misleading, but doesnt say how.  Then, it sends links to the CNPRCs official website without any disclaimer.  To say this page is biased against the center is bullshit. Users/TobinJones

20080810 21:58:53 nbsp i think the link is wrong for the primate freedom site Users/MattHh

20080811 13:50:31 nbsp Does anybody know what diseases or conditions have been cured or helped via primate research? I dont want to start any kind of big debate here, but I would like to know how such research has benefited us, costs aside.users/JoePomidor
  An acquaintance of mine is a postdoc in comparative pathology, and hes doing research on SIV (simian immunodeficiency virus) and, thereby indirectly, on AIDS.  Its tough to do direct research on AIDS for obvious reasons.  When it comes to this type of research, Im all for rounding up monkeys and poking them with needles, as long as it doesnt affect the sustainability of their species, and as long as reasonable measures are taken to minimize their discomfort. Users/TheAmazingLarry

20081201 16:41:23 nbsp The Primate Freedom site is no longer available due to a lawsuit by the University of California to suppress information pertaining to its research staff and activities.  (i.e. A SLAPP) Users/TobinJones
  I have a feeling that  the lawsuit is designed to protect the privacy of the employees, so http://www.nytimes.com/2008/08/04/us/04firebombs.html this sort of thing doesnt happen to them. Privacy matters aside, its also completely possible that there is proprietary information of one kind or another out there that isnt meant for free circulation. Its hard to be more specific, because you dont really give any sources or details.
 EDIT: I did some extra research, and the reason for the lawsuit is to stop protesters from harassing animal researchers. (For more info go to http://www.lasuperiorcourt.org/civilCaseSummary/index.asp?CaseTypeCivil this link and type in case number SC097145.) I dont understand how a lawsuit designed to keep a website from telling people where those researchers live (presumably so they can go there and attack them or their property) is a wiki:WikiPedia:SLAPP.Users/JoePomidor
  Woohoo for the lawsuit. users/Edwins ES

20090423 11:27:01 nbsp The spokesperson and executive director of Stops Animal Exploitation Now!, the organization that is running the commercial meant to smear the center, also claimed that You cant study a human disease in a different species, implying that he has no idea how this type of research works. Users/JoePomidor
   Guessing this is in reference to the http://www.uwire.com/Article.aspx?id4035760 article (linked from Uwire) in the Aggie.  I believe UCLA isnt the only UC to now refuse to respond to certain requests filed under the Freedom of Information act, due to aforementioned issues (home vandalism (from graffiti, flooding, or fire), car bombings, etc).  In full context though, the quote was Primates arent subject to HIV, Budkie said. You cant study a human disease in a different species. Thats likely a purposefully misleading statement.  It is true that they arent subject to HIV, but SIV is virtually the same thing.     There are some differences between HIV and SIV in general, and you cant really crossinfect humans, chimps, and macaques for example with the same strains (the data on why only came out a few years ago, its really really interesting). Furthermore, theres lab strains like SHIV that are almost like a combined version, and etc.  Theres so much to learn.   The concept that you cant learn about HIV from SIV is ludicrously incorrect, much less human diseases. users/Edwins ES

20090423 12:24:53 nbsp I wish all the crazies who protested these facilities would stop accepting pharmaceuticals. Evolution would then have its intended affect. Users/condemned2bfree

I dont think you need to resort to calling people crazy just for protesting (as long as it is carried out legally), nor do I think it is reasonable to wish they would be wiped out. Everyone is entitled to voice their opinion in opposition, so long as they arent causing any damage, which I realize happened here in the past. Some people do refuse to use pharmaceuticals, and in many cases seek out alternative treatments with great success. Cheers!
Users/aprilaries

Of course, this also means you are entitled to to call them crazies, if that is your opinion! Users/aprilaries

20090424 16:58:45 nbsp In response to an earlier comment, two kinds of research that have benefited humans greatly that have been done on primates, are the testing of drugs used during pregnancy and birth. Which for obvious reasons are rather hard to ethically test on humans. In addition, most drugs on the market for epilepsy also come from primate research. I am not sure how to link to the scientific papers since if you cant see them without a membership. But if you google these two things you should find a fair amount of abstracts on these research subjects. This type of research cant be done on cell culture since it requires multiple organ systems and other animal models (such as mice) are too physically different from us in terms of birth process and brain function to be good research models. I would be happy to give more info if people are interested. Users/Zeeba

20101006 09:33:46 nbsp I worked there and I tested the stress rooms myself.  Helped build the cages and tried them out on myself. Primates, including human primates, sit there bored until they get a puff of air in the face. Not a violent puff of air, just enough to catch you off guard. Not a big deal at all. Users/JimJones

20110406 18:06:10 nbsp In order to do mind control on humans, they had to do animal studies first. The monkey colony at UC Davis in the 60s where I was an undergraduate is where they actually did the animal studies to develop mind control. it was adapted to human application at the applied science facility at UC Davis.  Leuren Moret http://www.youtube.com/watch?vnzXYyhmvUg Users/alcatraz

20120124 02:15:12 nbsp Monkey!!! Users/MikeyCrews
 Mikey!!! Users/MonkeyCrews

20130309 12:11:07 nbsp My roommate is an ethical vegetarian and works here (I wont go into how critical and empathetic she is, since thatd just be opinions). My understanding is that its not as bad as it sounds on this page and the experiments are all very humanely done. I know that she does a lot of cleaning and video watching to essentially watch how many times they do a specific action.  Users/HannahToru
