The California Aggie, via The Davis Enterprise, prints 8,000 to 10,000 copies every school day.

 History 

In 2005, circulation was 13,000, causing some to believe that California Aggie overpublishes a significant amount of copies each day. They claim R4 Recycling can show this.  Some also claim an internal audit of The California Aggie showed they overprint, but it is unclear whether any such audit ever took place.  When asked, thenEditor in Chief Ryan P. Fuller claimed he had never heard of any internal audit and that he had never seen a report from R4 Recycling.  It unknown whether either of these ever took place.  The topic was  addressed in former ASUCD President Kalen Gallaghers farewell speech. Below is a letter sent to the individuals addressed, it has been copied here for public information:

According to some unnamed source, in 2005, a days paper cost the Aggie about $1200, and about $700 just to print.

  Dear ASUCD Senate Senators, Caliph Assagai President Assagai, Darnell Holloway Vice President Holloway, Devin Whitney Controller Whitney:

  Ive gotten wind of some legislation that EPPC Environmental Planning and Policy Commission may be writing regarding The California Aggie The California Aggies circulation.

  Im writing to remind you that while The California Aggie is part of ASUCD, neither the Senate nor the Executive Office has control over how The Aggie is managed. This includes editorial and advertising content, as well as our distribution.

  Furthermore, I will not recognize any ASUCD legislation that attempts to cut The Aggies circulation.

  Ive also heard about a group (Students for an Orwellian Society Im not mentioning its name) that is planning to take copies of The Aggie in recycle bins to our advertisers. I understand that some of the senators know who these individuals are. I will report any theft (that is, the removal of a significant amount of the papers) to the campus police department.

  Thank you.

  Sincerely,

  Ryan P. FullerBR
  Editor in ChiefBR
  The California Aggie

As of 20050511, no one has seen any proof that there was any such R4 Recycling study done, or any internal audit of The California Aggie.  Some have, however, collected leftover The California Aggie Aggies (questionably legal) in an attempt to bring attention to the possible overprinting (seen below).

A lot of the recycled The California Aggie Aggies can be found near Kerr Hall in several extremely large recycling bins.

 How it boiled out 

During the week of May 2^nd^, 2005, several members of Students for an Orwellian Society went around campus and collected old The California Aggie Aggies that had been left in stands.  This allegedly took place at about 10PM.  During a day of collection they obtained approximately 2000 aggies (pictured right).  Users/BrentLaabs Brent Laabs (of Students for an Orwellian Society) brought the collected The California Aggie aggies to the Campus Media Board and expressed his dismay about aggie distribution processes.  ThenEditorinchief Ryan P. Fuller quickly responded that The California Aggie was open to changing and examining their distribution system, and does work with R4 Recycling as much as they can.  Ryan P. Fuller also expressed concern about the collection of leftover The California Aggie Aggies from stands, citing it as a violation of Fair Use.  Users/BrentLaabs Brent Laabs responded to this by accusing the The California Aggie Aggie of committing fraud by misreporting their circulation numbers to their advertisers.  The Campus Media Board questioned Ryan P. Fuller on the matter, and he reassured them this was a priority for the The California Aggie Aggie.

On May 5^th^, 2005, the ASUCD Senate passed a resolution encouraging oncampus publications to work closely with R4 Recycling to reduce their waste.  (Resolutions differ from bills.  Bills are legislation and can order/allocate, etc.  Resolutions are sort of tokens, ways to express something, or ways to formally ask someone to do something but not force them to).
 Discussion 
Its not stealing if the copies are removed from the recycle bins is it? Users/JackHaskel
  I have friends who have been chased by the police for taking from recycle bins.  Users/BrentLaabs
  Technically taking from recycling bins may be theft, as is dumpster diving... at least that is what Davis PD told me at a dumpster one day...  Users/RevChad

Ryan P. Fuller is correct.  Only the Campus Media Board has authority to tell The California Aggie what to do. (I think.)

In the public Editorial Board meeting the question of aggie overprinting was discussed, and Ryan P. Fuller said that the Aggie had done an internal audit and it showed they didnt need to reduce printing?  I demand more information! Users/PhilipNeustrom

Actually Id like to remind everyone not to take anything for granted unless there is evidence of it  in this case, Id say theres no reason to say Only the Campus Media Board has authority to tell The California Aggie what to do. unless someone can cite a place in the ASUCD bylaws where it says as much.  Personally Im not going to rule out it doesnt, and am of course open to arguments either way, but Id just like to remind everyone to avoid running on assumptions. Users/KrisFricke

Very interesting Mr. Chief Justice... I just ran through all the codes and never saw anything that would make the Aggie any more autonomous than the CoHo.  At best, theres the units admin plan, something that could be changed (or overruled) by a mere majority vote.  Anyone down for turning the Aggie into the ASUCD California Aggie?  Let the propaganda begin! (just kidding but maybe someone who doesnt like it this way would look into writing a constitutional ammendment to ensure autonomy in the future? ie. a fourth branch of sorts...) Users/ThomasLloyd
   The ASUCD consitution says that the Aggies Editor in Chief cant be fired  but youre right, neither can the head of the Coffee House (as far as I know she is a union employee and only Mark Champagne can fire her).  The Aggie does get benefits from being an informal ASUCD unit:  Free space in Lower Freeborn and their accounting done for free.  Aside from that, it could readily break free from the association.
    __Actually__ what it says is All unit Directors may only be removed by a 2/3 majority vote of the entire Senate (with the exceptions of The California Aggie and KDVS Radio). (Art II, Sect 4, Paragraph 4)  A literal reading of this actually gives the unit director (EditorinChief) LESS protection than other editors, stating that 2/3rds of senate is NOT the only way to remove them.  Now those of us on the Court might not necessarily take it in so literal a fashion, but hey that IS what it says.... Users/KrisFricke


So, does anyone think forwarding this letter to the Aggies advertisers is a bad idea?  Users/BrentLaabs
  Seems a little hasty to me. Anything that could result in undesired damage should always be done carefully IMO. JH
  Also, doesnt seem like the letter proves anything?  Its just letting the ASUCD Senate that they have no power over The California Aggie. Users/PhilipNeustrom

Wow. Let me clear some things up about what the EPPC is doing.  We are authoring a Resolution that would give ASUCD Senate support against overprinting of ALL oncampus publications. For some reason, everyone gets excited about singling out the The California Aggie when it comes to overprinting. If you really care about the issue, you would be targeting even greater offenders. Also, please do not remove any Aggies from the paper bins. It is illegal, and it does not help anything. Take pictures if you feel inspired, but do not remove any recycling. R4 Recycling and the Aggie work with eachother every year to work on the issue of overprinting. Thats more than I can say for other oncampus publications. In addition, the Aggie recycles all of the remaining Aggies from the prior day in bins that are designated by R4 to do so. Again, this action takes greater environmental responsibility than other oncampus publications do. Since all of the Aggies are taken to a single recycling location, it is easy to see what is overprinted by the Aggie. Unfortunately, it is not as easy for the common student to see how much other overprinting is happening oncampus since R4 does not have designated recycling sites in place for all overprinters. This legislation will be used by R4 to assist them in their continuous efforts to reduce ALL overprinting oncampus. If you are genuinely interested in resolving this problem, I suggest you contact R4 and ask about ways that you can help.Users/NancyMathison

I dunno.  This is a typical UCD move: try to compel something (or a whole class of people) by terrorizing someone into it.  Wouldnt it be better to work with the groups in question first, rather than twisting their arms?  As the former EditorinChief of the King Hall Advocate, we routinely found large amounts of copies thrown in the recycle bins (or just plain trash bins), while they were still current.  While, as a daily, I suppose the Aggie is less likely to be a victim of this, I think the Aggies problem is not overproduction, but rather poor distribution.  Several distribution points are dry by early morning, whereas other points never seem to be have many copies taken.  So perhaps a study of the distrubition trends can make it more effective.  Users/JaimeRaba jr
  I think youre kind of missing the issue.  It doesnt matter if the issues are thrown away while they are current  that means someone read it and has thrown it away after reading it.  I also think it is clear that one of the groups involved does not want to work with the others, i.e. I will not recognize any ASUCD legislation that attempts to cut The Aggies circulation. Users/BrentLaabs
      The current issues reference was only referring to accusations of King Hall Advocates overproduction at one point, but it was determined that custoldial staff was actually recycling piles that had not even had the opportunity to enter circulation before they had become stale since it is monthly.  As the Aggie issue is presented above, it concerns overprintingi.e., too many issues are being produced, and stacks of unread copies are being thrown away.  I do not get from the dicussion above that the dispute is that people are reading them and throwing them away.  So unless the issue is rearticulated in the terms you suggest, I do not come to the same conclusion as to the issue.  It looks like unread copies are being throw away alledgedly because printprodution is beyond the probable circulation numbers. Users/JaimeRaba jr
      Brent, are you suggesting that The Aggie should bend to the will of the senate?  Users/ArlenAbraham
        The main problem is that if The Aggie bends to the Senate, they give up legitimacy.  However, I think the Senate is right on this issue.  The Aggie prints way too many copies, and the R4 study proves it.  ASUCD people are not asking to fire the editorial board, they just want them to help the environment an print a few less, after all.  Users/BrentLaabs

Can someone provide a copy of the R4 Recycling study? Seems that this would be a case where access to the raw data would be helpful. Also if the internal audit is publicly available that would be helpful as well. Users/JasonAller

20050713 17:30:36 nbsp I am proud to say that this past year I have spent working with Building Roles and as the Advertising Manager of the California Aggie Newspaper. For a group that talks about community growth and development, most of the time you choose to spit on your competition for doing a good job before seeking out the facts. Do any of you honestly think that Kaplan was against the wiki and for Building Roles because we are better looking then you? Do you really think the aggie actually lies to customers on how many papers we print? Read what is written on these pages, it might tell you something about how serious Kaplan could take a site like this. While I like the idea of a site like this, you need to learn to accept other peoples successes gracefully. I would love for any of you to become a part of building roles and see way Kaplan and U.C. Davis believes in us. Users/DustinDevan
  I, for one, read whats written on these pages.  Are you refering to California Aggie Printing?  It does not say the aggie over prints or that they lie to their advertisers.  When I see something incorrect or slanted I try my best to fix it, and I encourage you to do so as well!
  Hey, are you the person who threatened to call the UC Davis Police Department UC Police Department on me?  It may or may not be overprinting, but Student Judicial Affairs thought it was serious enough to warrant further study.  Well, at least Daniel Stone isnt an 4ssHa7 like some previous Aggie staffers.  Like you.

20050714 17:05:17 nbsp You have never met me whoever called me an a$$hole.  You were to busy collecting old papers to do the simple thing and talk to the person with all the numbers.  The one thing I never undrstood is why did you guys ever care about how many papers we publish or how we distribute.  Is your life really that boring that you need to occupy your time with such pointless endeavors.  The california aggie is a service that students can enjoy and benifit from.  Unlike this site, it publishes all points of views without craping on them.  You know what I think is funny.  Most of the people on this site spend so much time complaining about so called violations and rule offenses trying to hold people responsible (ie camping in the dorms).  But when RobRoy makes an election violation you people did a 360.  Its pretty sad when people cant hold themselves to the same level of integrity that they are trying to hold others to.  DustinDevan

20050714 17:34:40 nbsp I have to agree with Arlen.  Instead of attacking you, I am going to follow up on your invitation to attend Building Roles.  Since I am the marketing/publicity person for my club, I should have a lot in common with you. Users/BrentLaabs

20050714 19:05:53 nbsp maybe you should have followed up on my invitation to talk about the aggie that I made to you before you took the paper before you went your stupid quest to steal papers DustinDevan
  The only invitation I got from anyone at the Aggie was an invitation to spend a night behind bars from you. Users/BrentLaabs

I never said anything was shit.  What are you talking about?  The reason he took the papers was not to recycle but because he wanted to prove a point.  I even asked Brent on the phone before he took the papers if I could answer any questions involving the aggie publishing.  But he didnt want to do it the easy way.  For the record, the aggie does NOT over publish the paper.  There are business and logistical needs for the 13,000 papers we put out a day.
   Youre absolutely right  there are business needs.  Former ASUCD President Kalen Gallagher claimed that The California Aggie prints 13,000 so they can inflate circulation values to tell advertisers, in his farewell address.  Advertising is definitely a business need.  I make no such claim, but if it were true, it would constitute fraud.  This is why we undertook an investigation.  Certainly we need an independent investigation as well.BRAlso note: you called and asked to talk to a member of the Students for an Orwellian Society, and youre a member of the media.  Guess what kind of interview you got. Users/BrentLaabs bl

Kalen is an idiot that made something up and I am not a member of the media.  At all papers, there are divisions between editorial and business.  Sorry, but that is common knowledge.  Nothing you could have said to me could have been printed.  If you feel everytime some moron steps to the mic and says something it warrants an investigation you are going to spend a lot of your time chasing down crap.  The aggie has been publishing 13,000 papers since the mid 80s.  If we were committing fraud, we would have been exposed already.  You were just looking for something to make your self feel important and that is sad.  I think its kinda of arrogant of you to try to attack an institution that has been around since 1915.  Go join the ACLU if you want to make drastic pointless change.  Most people have better things to do with there lives Users/DustinDeVan

  Not sure why the insult to the ACLU....as a Northern California Board Member and President of the Campus Club, I was actually considering working with Building Roles after talking with DarenBlonski Daren, as we share a common friend. But, if my club would not be respected I see no point.  Users/JimSchwab

I apologize for that statment.  Got carried away.  The I have agreed and disagreed with some of the things the ACLU has done.  Nevertheless, they are a valuable organization  DustinDeVan

  Why is there so much Building Roles discussion on this page? I mean, I know DustinDevan is the advertisement guy at the Aggie and a member of Building Roles, but this is getting kind of crazy here. I know the Aggie wrote a story about Building Roles, which Dustin probably helped score for his club. But seriously, what is the connection? BR  Users/RobRoy Rob I got disqualified and reinstated from the election but my Aggie Endorsement was never rescinded Roy
