

Camp Adventure is a program run by the University of Northern Iowa which sends American college students to work in recreational programs for youth abroad. Many programs are hosted on American and allied military bases, embassies, schools, and community organizations throughout the world. Students mainly run day camps, but overnight, languageimmersion, and sports camps programs are available from timetotime. Students with an affinity for water can alternatively work as lifeguards and swim instructors. Many aquatics programs are held on US Military bases in Japan, Southern Europe, and stateside (primarily in Florida and Hawaii). The UC Davis/California State University, Sacramento program was started by the late great Nancy Tibbitts (former Adviser at the Internship and Career Center) in 2006. For many years Heidi Van Beek was the Professional Development Coordinator for the program. That title has now passed to Megan Elliot.

Camp Adventure was founded at the University of Oregon in 1985. At its inception, the program sent 12 students to three sites in Korea. In 1997, it sent approximately 600 students to 118 program sites in 16 countries. In 2008 over 900 students went around the world to such locations as the United Kingdom, Russia, Germany, Italy, Spain, Belgium, the Netherlands, Korea, Japan, Hong Kong, Peoples Republic of China, and the United States. In 2013 Camp Adventure programs were held all around the world, but for the first time since 1985 no programs were held in South Korea.

In addition to the opportunity to travel and gain experience working with children and youth, Camp Adventure offers students with a number of  additional benefits: free airfare and housing, a living stipend, transcript notation/units (not normally transferable to UC Davis, but might depending on major), memories that will last a lifetime and more!

Students who are interested in participating in Camp Adventure are recommended to attend one of the informational meetings that are usually held at the beginning of fall quarter. At informational meetings students can learn about eligibility criteria for the program and hear from program veterans about their experiences. Students then attend one of two LACs (Leadership Assessment Centers) at either UC Davis or California State University, Sacramento where they participate in group interviews (interviews consist of a formal oral interview and an informal practical component. Participants should be prepared to teach a song and a game appropriate for grade schoolaged children). After the LAC, students should be prepared to fill out a lot of paperwork (a rigorous background check is processed on all participants).  Students who are accepted into the program must participate in a Professional Development series in Winter and Spring quarter. Professional Development is always held on Tuesday nights and training locations alternate between UC Davis and California State University, Sacramento. Ride shares are organized by Camp Adventure veterans. During Professional Development counselors are taught everything they need to know to run a recreational program for children.

There are some expenses associated with participation, which include: uniform, tuition (for credits that dont transfer to UC Davis. Sorry, its mandatory), Red Cross Lifeguarding Certification (required of all participants, unless you cannot swim. If you cannot swim...well work something out), supplies, passport (visa costs covered by program) etc. Participant costs before going abroad normally do not exceed $2000. Expenses can be paid in full or in installments. While living/working abroad many students are able to live modestly using just their stipend, though most veterans will recommend saving up some money for weekend travel excursions.

Although the program is based at the University of Northern Iowa, Camp Adventure Youth Services student participants come from over 80 colleges and universities (as of 2008) to participate. It is a great way to make new friends from all over the country!

Camp Adventure Counselors create Magic Moments for children and youth that last a lifetime. They also sing a lot, make lots of friends, and eat lots of dessert.

Camp Adventure is often called a cults cult by its participants, because once you join you never want to quit!

(Info taken from: http://en.wikipedia.org/wiki/Camp_Adventure)
