Basics:  Student Focus is alleged to have campaigned for the Fall 04 ASUCD Senate election in the Dorms. This is seen as a serious problem to some as it means they were campaigning closely to polling places on election day, which is against elections regulations. Some of the accusations include claims that the candidates helped people vote. Senators Nafeh Malik and Sean Ruel resigned only one week after they were sworn in.

Nov 18th  http://media.www.californiaaggie.com/media/storage/paper981/news/2004/11/18/Opinion/Guest.Opinion1318807.shtml?sourcedomainwww.californiaaggie.com&MIIHostmedia.collegepublisher.com Election Injustice Should Not Be Tolerated Guest Opinion by ASUCD Court Chief Justice Users/KrisFricke Kris Fricke  The first hint that there are major controversies brewing is published the day the elections conclude

Nov 19th  http://media.www.californiaaggie.com/media/storage/paper981/news/2004/11/19/FrontPage/Student.Focus.Takes.Three.Of.Six.Possible.Senate.Seats1318822.shtml?sourcedomainwww.californiaaggie.com&MIIHostmedia.collegepublisher.com Student Focus Takes Three of Six Possible Senate Seats  Election results announced, light allusions to controversy are made.    ASUCD Vice President Paloma Pérez justifies the situation with Many are guilty of campaigning in the dorms, even Ive campaigned in the dorms.

Nov 22nd  http://media.www.californiaaggie.com/media/storage/paper981/news/2004/11/22/FrontPage/Election.Complaints.Brought.To.Senate1318838.shtml?sourcedomainwww.californiaaggie.com&MIIHostmedia.collegepublisher.com Election Complaints Brought to Senate  Students return from the weekend to find the allegations have been brought up in Senate.

Nov 23rd  On November twentythird the coverage mushroomed with:
            Article: http://media.www.californiaaggie.com/media/storage/paper981/news/2004/11/23/FrontPage/Student.Focus.Potentially.In.Violation.Of.Student.Housing.Rules1318857.shtml?sourcedomainwww.californiaaggie.com&MIIHostmedia.collegepublisher.com Student Focus Potentially in Violation of Student Housing Rules  (which would simultaneously be a violation of elections rules)
            Editorial: http://www.californiaaggie.com/media/storage/paper981/news/2004/11/23/Opinion/Alleged.Campaign.Violations.Necessitates.Election.Reform1318859.shtml?norewrite200606071636&sourcedomainwww.californiaaggie.com Alleged Campaign Violations Necessitates Election Reform
            LetterstotheEditor: http://www.californiaaggie.com/media/storage/paper981/news/2004/11/23/Opinion/Letters.To.The.Editor1318858.shtml?norewrite200606071639&sourcedomainwww.californiaaggie.com link  including ASUCD Court should Have Power Returned & a scathing response by the Elections Committee Chair to Users/KrisFricke Justice Frickes earlier guest opinion.  Fricke in return responded with http://www.livejournal.com/users/emosnail/149554.html this rebuttal.

Nov 30th  The California Aggie http://www.californiaaggie.com/media/storage/paper981/news/2004/11/30/Opinion/TheAggie.Rescinds.Its.PreElection.Endorsements.Of.Student.Focus.Candidates1318915.shtml?norewrite200606071647&sourcedomainwww.californiaaggie.com formally rescinds all preelection Student Focus endorsements due to the controversy regarding Dorms dorm campaigning.  A http://www.californiaaggie.com/media/storage/paper981/news/2004/11/30/Opinion/Letters.To.Editor1318917.shtml?norewrite200606071647&sourcedomainwww.californiaaggie.com letter to the editor was also published alleging that Nafeh Malik participated in dorm campaigning, despite the fact he was on crutches.

Dec 2nd  The ASUCD Senate meeting in which the new candidates were supposed to be sworn in turned into a threehourlong public discussion about whether the candidates alleged to have campaigned in the dorms should be sworn in or not.  Because of the complaints filed against the Elections Committee in the Election Statement Controversy, it would violate ASUCD bylaws to swear in new candidates while the complaint was being considered by Student Judicial Affairs SJA.  The The California Aggie Aggie has a http://www.californiaaggie.com/media/storage/paper981/news/2004/12/06/FrontPage/Newly.Elected.Senators.Unable.To.Take.Office1318979.shtml?norewrite200606071651&sourcedomainwww.californiaaggie.com good article covering the events of the senate meeting.  The Senate agreed to continue with business without swearing in new officers, as many senators felt that ASUCD was under attack. Most felt it would be a bad idea to suspend the bylaws to let accused cheaters take office, including the recently elected Janine Fiel of the LEAD slate who did not want to take office under the circumstances.  Dyanna Quizon in particular felt that campaigning in dorms was a sign of poor character, and denied ever taking place in any such activities.


Dec 7th  Aggie Articles:
   The California Aggie published many http://www.californiaaggie.com/media/storage/paper981/news/2004/12/07/Opinion/Letters.To.The.Editor1318997.shtml?norewrite200606071652&sourcedomainwww.californiaaggie.com letters to the editor, critical of Student Focus Focus actions, at the dorms and in the Senate.  One letter says that candidates should have legal ways to campaign in the dorms and reach out to freshmen, but Internal Affairs Commission Chair Kahliah Laney had said at the previous Senate meeting that her efforts to get candidates in the dorms would be hampered by the current scandal.
   Aggie Columnist Russ Fagaly wrote a http://www.californiaaggie.com/media/storage/paper981/news/2004/12/07/Features/LikeA.Ship.Of.Fools1318989.shtml?norewrite200606071653&sourcedomainwww.californiaaggie.com column calling for the recall of the Student Focus candidates and arguing that ASUCD is in the worst shape it ever has been.

Jan 13th:
   Nafeh Malik and Sean Ruel http://www.californiaaggie.com/media/storage/paper981/news/2005/01/14/FrontPage/TwoSenators.Resign.Ham.Sworn.In1319188.shtml?norewrite200606071654&sourcedomainwww.californiaaggie.com resign from the senate exactly one week after being sworn in.
