Cary Arnold was born in the old Sutter Davis Hospital the first year it opened in 1968. She graduated from Davis Senior High School in 1986 and is an agent with the Arnold & Sanchez team along with her husband, Jon Sanchez, at Doug Arnold Real Estate, Inc. Coldwell Banker, Doug Arnold Real Estate, Inc.

She is also the publisher/editor of Davis Life Magazine http://www.davislifemagazine.com Davis Life Magazine, an online magazine about Davis featuring the work of work of approximately 30 writers and photographers, as well as the Yolo County Buyers Guide which DLM produces for Coldwell Banker, Doug Arnold Real Estate, Inc. Cary is also the vice chair of the board of directors for the Davis Chamber of Commerce.

She has three sons: Mark Ling, editorinchief for The California Aggie for the 2010/2011 school year; Spencer Ling, a soontobe Davis Senior High graduate; and Logan Sanchez, an elementary school student in Davis.


20081022 14:28:02 nbsp Cary,

I noticed you have been posting a lot of links to articles in Davis Life Magazine, which I think is fantastic.  However, I have some feedback which I hope you will consider because I think it will make the pages better.  Rather than including a link to an article in the following format:
Story on El Macero Country Club golfing in http://sept2008.davislifemagazine.com/golf/pg7 Davis Life Magazine
Why not do it this way, so you have a link to both the article, and the Davis Life Magazine page on the Davis Wiki?
http://sept2008.davislifemagazine.com/golf/pg7 Story on El Macero Country Club golfing in Davis Life Magazine Users/DavidGrundler

20081024 16:47:42 nbsp Damn, I just learned how to link to the magazine and was so proud of myself! Ill see how I can include both while still highlighting the story as opposed to my page... Thanks for the tip. Users/CaryArnold

20081025 18:17:33 nbsp Do you think you could find some space in Davis Life Magazine to link back to the wiki? Users/JasonAller

20081027 11:18:32 nbsp Jason, Yes, when our phase II is complete, well be able to do that when we mention or refer to it in a story. Ive also tried contacting the main folks who spend the most time managing the Wiki to do a story on it, but I never heard back from anyone. If you can point me in the right direction, Id love to give the Wiki some coverage! Users/CaryArnold
  20090520 23:15:05 nbsp Is phase II complete? Looking back through your http://daviswiki.org/Users/CaryArnold?actionuserinfo edit history I see a lot of edits that add links to your magazines website, but I dont see many edits that add to the wiki. In order to avoid the appearance of taking advantage of the wiki or spamming, it might be good to balance the linking by adding content. There is so much more you know about Davis that you could share. Users/JasonAller
  Perhaps youre right Jason. I think Carys intention is that by linking back to the stories, the service to the wiki is selfevident  links to stories specifically about the thing people are looking up on the wiki. Perhaps there are tidbits one could add, for instance: http://sept2008.davislifemagazine.com/golf/pg7 Story on El Macero Country Club golfing in Davis Life Magazine in which it is discovered blah, blah, blah. Is this what you are looking for? Because otherwise, as you can probably imagine, the magazine devours a great deal of time and energy, as does the other work that Cary does for her business, her family and throughout the community. Spending even more time adding more and more data to the wiki might be asking a bit too much, but of course thats up to her. As she has said, she has tried to get some of the wiki admins to participate in a story about it, however they so far havent been receptive.  Users/condemned2bfree
     Why dont you participate?  You are a wiki editor, as is everybody else.  Surely you can find somebody on here who can participate.  Or just start an entry with some questions, and everybody will answer.  jw
       I would be more than happy to participate, however, there is somewhat of a conflict since I also write regularly for the magazine. I would actually very much enjoy writing the piece. Your idea of starting an entry is a good one, however eventually I would want to meet people in person at some point, especially for photography. Keep in mind, whoever writes the piece will be sure to mention that there are no official admins of the site, however pretending there arent a handful of individuals that contribute/edit more than others doesnt necessarily make it so.  Users/condemned2bfree

20090521 10:19:29 nbsp Hey, Cary.  To alert somebody in chat, just use their chat name.  It usually beeps or otherwise alerts them that somebody wants to talk.  To check your messages on the Davis Wiki, just click your user name in the upper right corner.  Having a message just means that somebody edited this entry (your user entry).  That allows you to know when somebody has replied back to you... and you can click on their signature to go to their user entry and reply back to them.  Its a pretty easy system once you get the hang of it.  Im not quite sure what youre asking... I think people have just been encouraging you to add to the wiki more than just links.  And yes, you can easily add a media section to the bottom of any entry.  Just type {{{ Media }}} on a line by itself, and then put your link (preferably with enough of a description so people know what the article is about) underneath it.  Media links tend to be just above the comment bar and any internal category links (i.e., it tends to be Media, then under that any category links like For other local restaurants that serve Thai food, visit the Thai Restaurants entry, and then the comment box, with reviews under it.  Thats just how I and some other people tend to do it... theres no strict rule, and Im just letting you know how I format it.   The wiki is a community written work, so there are loads of differing opinions out there, so dont let any one statement sway you too much.  Personally, I really like the media links  I wish the Enterprise, Aggie, Sacbee, SNR, Daily Democrat or any other local news source would help link their stories (so long as they dont change their site without redirects, causing hundreds or more links to turn into broken links).  In my eyes youre focusing on your part of the community  your magazine  and helping out the wiki with what you know.  Thanks.  Users/JabberWokky Evan JabberWokky Edwards

20090521 10:27:44 nbsp JW... Thanks so much. Well proceed accordingly and give more info regarding the stories and put them under a media heading, and add one if there isnt one already. Ill pass this info on to Mark also. If you think we could get 34 of the editors together in person ever, Id love to do a story on the Davis Wiki and those who put so much time into making it what it is. We just need someone to coordinate getting the people together. Let me know. Well be assigning our August stories around July 8th, so I would need to know by then. Ive been trying to put this together for awhile... Thanks again. Users/CaryArnold

20090521 10:30:27 nbsp oops... June 8th, not July. Users/CaryArnold

20090521 10:35:51 nbsp Check out the entry for Sophias Thai Kitchen for an example if you want a layout format thats fairly common here on the Davis Wiki.  Keep in mind that this is just an example, and there are plenty of creative ways to create entries.  For instance, the entry for sunflowers just makes you feel happy and refreshed when you go to it.   Users/JabberWokky

20090609 08:17:41 nbsp Hi Cary, Im a graduating senior at UCD and a Private Pilot. I read your article about the Davis University Airport from the Davis Life Magazine recently. Having trained from CAFF myself and as someone that regularly rent from them, I must say the article was an enjoyable read and I wanted to thank you for that. However, there was one place in the article that I thought I should clarify.

In your paragraph:

Initially, those who do decide to take flight classes work towards obtaining the Private Pilot Certificate. Apart from a commercial pilot, who needs a fouryear degree, a private pilot needs no more education than flight instruction from Cal Aggie Flying Farmers.

You dont need a fouryear degree to become a commercial pilot. The eligibility requirements to become a commercial pilot are listed here by the Federal Aviation Administration:
http://rgl.faa.gov/Regulatory_and_Guidance_Library/rgFar.nsf/FARSBySectLookup/61.123

A commercial pilot, technically, is any pilot who is certified to fly for hire or compensation, even in a small plane such as the Cessna 172 that you flew in with Jonathan. However, I understand that when you wrote commercial pilot, you might have been referring to airline pilots, but even then, I dont know of an airline that requires a fouryear degree in their hiring criteria, although it is often preferred. In fact, a fouryear degree isnt required to become a CFI (Certified Flight Instructor), or an ATP (Airline Transport Pilot) which basically allows you to be in command of an air carrier service such as an airline (to be captain). However, youll find that most of the major bigname airlines out there desire a fouryear degree, and of course, now days without one almost any career is offlimits. I just wanted you to be informed of whats actually required vs. whats desired.

Also, in the public and media, its a common misconception that commercial pilots are automatically airline pilots. For example, not all commercial drivers are automatically bus drivers  some are truck drivers and others are taxi drivers, all of whom still have to possess a commercial drivers license. For commercial pilots, the same applies  some could be flying small planes for bannertowing, while others could be flying cropdusters for cropdusting.

Cheers Users/AnthonyLam

20100603 09:57:59 nbsp Would the Chamber be open to a presentation for business owners about how to have a positive experience with the wiki? In the past they have ignored the offer of a presentation and Q&A session. Users/JasonAller

20100603 10:01:50 nbsp See wiki:wikispot:Presentations/Chamber of Commerce for an example. Users/JasonAller

20100728 16:05:46 nbsp Cary, I apologize.  Im going to spend a little while organizing my thoughts now, and Ill respond to your comment on the DLM/Talk page to keep the discussion in one place.  But I wanted to apologize if I offended you.  My comment about the DLM page being clunky was an aesthetic one, and I have a couple of thoughts for improving its readability (and maintaining the content).  It certainly wasnt constructive, and that contradicts what I expect of myself and hope for from my fellow editors.  So for that, too, I apologize.  I still have some issues with the prevalence of links to DLM, but Ill address that on the /talk page.  The more I think about it, the more I think my problem may be one of perception.  But, like I said, Im going to take a little more time to organize my thoughts.  For now, Im going to restore the DLM page, and Ill try to make a couple of more constructive suggestions there about ways to organize it.  I havent read a lot of DLM articles, but those Ive read Ive liked.  As far as I can tell, youre doing a good job with the magazine and in the community; my concerns lie elsewhere.

Anyway, all of that said... sorry.  I dont like it when other people approach issues on here that way, and I shouldnt have done so myself.  More later on the Talk page. Users/TomGarberson

20100728 17:10:52 nbsp I took a stab at breaking up the text describing each issue using headers, and a table of contents making it easy to navigate to each individual issues description.  Its just one option that I think may help.  A couple of other thoughts for ways to improve the page:
  Include links to each months issue/archive.  I tried poking around the archives, but wound up with blank articles.  For example, http://www.davislifemagazine.com/2009/03/ March 2009 shows article headlines (Im assuming), but no text.  But something as simple as that link tacked onto March 2009 Issue would make it easy for users to find what theyre looking for at the DLM site, and just generally make the DLM wiki page more functional.
   On a side note, while I didnt spend a long time looking, a quick glance around didnt turn up older archives of DLM than the year or so linked at the bottom left.
  Thirdperson perspective.  Early on, theyre typically described as The June 2009 issue; later it transitions to Our January 2010 issue.  The former is preferable.
  Linking to the subjects of articles.  The wikis all about interconnectivity, and having links to the subjects of the articles makes it easy for wiki users to find out more about a subject, or find their way to related subjects.  Particularly if there are going to be DLM links on the individual wiki pages, I think its good to link to the pages from DLM.
These are all just suggestions, and theres quite a bit involved.  I, and Im sure other editors, would be happy to help out, if you like these ideas.  I think theyll go a long way toward making the page more user friendly, and more wiki friendly.  But there are certainly other ways to do it.  Let me know what you think. Users/TomGarberson

20100728 18:19:16 nbsp Hey Cary, sorry you got discouraged.  The wiki is really an adhoc group of everchanging volunteers, and there actually arent really rules around here (aside from being civil).  Often times someone (like Tom Garberson on that discussion page) will start talking about something as a way to figure something out or get other peoples opinions  that doesnt mean something is set in stone.  It usually takes a few days for discussions to head toward a consensus. Users/PhilipNeustrom

20100729 23:49:16 nbsp I really like reading Davis Life Magazine, and Im happy for it to be linked from the Davis wiki. Thats why Im sad about all the broken links Users/CovertProfessor has found lately to davislifemagazine.com. Web designers have been breaking old links during site redesigns for the whole history of the web, so youre definitely not the only one with (lots of newspapers do also, I think its more common with lots of part time staff and high turnover) but there have always been ways to redirect users to the new address with some effort also. I tried the search feature on the site to find the article that used to be linked from Graduates of the Davis Joint Unified School District so I could put it back with the new address, but it didnt come up with my searches. Could you tell me the new address or fix the link again? Thanks very much! Users/NickSchmalenberger
