

The Cat Clinic of Davis offers medical, dental, and surgical care exclusively for Cats cats.

Jim Kaneko, DVM/MPVM is the primary Veterinary Hospitals veterinarian on staff.  He is the son of local town figure Jerry Kaneko.


20050908 16:06:48 nbsp Dr. Kaneko is the best vet in town when it comes to felines Users/LauraChavez

20051014 11:17:53 nbsp I wish Dr. Kaneko would have let me know in advance that him shaving a spot on my cats belly (which took about 10 seconds) would cost $26. However, the same thing likely would have occured at any other vet... soooo... I guess thats not really a valid complaint. Other than that, I think hes great.  Users/AnnaJones

20060106 15:26:32 nbsp Dr. Kaneko has always been really good about communicating options for us re: our elderly kitty.  His staff is extremely helpful and friendly, and really care about how the pet is doing. Every time I go in to get supplies they jot my verbal updates down in her chart thats like, employeetreatment at places like AngellBoston. Users/AnsateJones

20060718 09:40:55 nbsp Dr. Kaneko and his assistants are among the kindest people Ive ever met. I recently had to put down my 17 year old cat who was dying from chronic renal failure. It was a long, painful, heart wrenching process, but the team here couldnt have been more supportive. They answer any question no matter how mundane it may seem and truly feel for the cats they care for. There are many great vets in Davis, but I cant thank them enough for making the hardest decision of my life a little easier. They go the extra mile to help out in any way possible. Davis is lucky to have them.  Users/DaveCar

20060915 22:04:09 nbsp Although Dr. Kaneko is a rather good vet, his prices are sky high and he tends to recommend more than is necessary.  For example, he recommended 10 mg. chlorpheniramine  to treat our cats allergies.  Thing is, he wanted to charge about .60 per tab when it is available in the OTC section of Longs across the street for about 4.00/100 tabs. He made no mention of thisnice!  So, do your research before you buy anything from him.      Users/OhmyGosh

20061211 16:04:30 nbsp My girlfriend took her cat here to have her nails clipped. After the cat wiggled and moaned for awhile, the vet popped his head in and said her cat is a constant nuissance there. He was extremely rude and suggested that she stop going there. This cat is probably the friendliest cat Ive ever met, and the Woodland vet hospital trims her nails in less than 2 minutes. Basically, Woodland is way better for prices, service, and friendliess. Users/ChrisMay

20070104 23:57:52 nbsp I like Dr. Kaneko and the staff but they do seem to charge a lot without telling you in advance. Maybe this is normal for medicine but I am going to another vet. Users/GreenThing

20070108 19:35:56 nbsp I took my Josephine here for her first vet exam and it went very well. He did try and do pricey things without mentioning it but I made him show me all the costs before he did anything. I dont like having to ask but its worth it for the great service. Users/NicoleBush

20070225 11:35:34 nbsp Dr. Kaneko has cared for all three of my cats. They are always willing to take us right in and we never feel rushed. He does recommend expensive proceedures and/ or tests, but I believe its because he wants the cat owner to know all of the options available. Once I understood that, I never feel pressured or guilty about making a decision about whats best for me or my pets. My experience is that they are a compassionate and freindly cat clinic. I would highly recommend them. Users/SheriSwink

20070513 17:06:05 nbsp Dr. Kaneko and his staff provide excellent service.  In the past, my cat has not been kind (to say the least) to vets.  He started off hissing (as expected) with the staff at the Cat Clinic, but their kind and gentle demeanors calmed him down quickly (I was shocked).  Since then, he never hisses or struggles while in their care (again, shocking).  Dr. Kaneko has always been very kind, professional, and provided me with a range of options for treatment and care.  I always get a phone call the day after his is treated at their office to make sure he is doing fine after shots, etc.  I highly recommend this clinic and Dr. Kaneko.   Users/SaraMeyer

20070514 20:28:25 nbsp I had my cat spayed at the Cat Clinic. Overall, I would recommend this place. The nurses were friendly, answered all of my questions, and they treated my kitty well. They called me after the surgery to let me know my cat is doing good and they even called me the day after to check up on her. My little cat is healed and back to being a playful, purrrfect little buddy. Thanks to everyone at the Cat Clinic of Davis for doing a great job!  Users/mikew

20070529 21:51:06 nbsp Dr. Kaneko is all about money. My cat was dying and he refused to save him unless he got nearly a thousand dollars up front. I promised him I would pay it or give him half and he was ready to let my precious cat die. I borrowed the money and he treated him. When I got my cat back he was soaked in urine, terrified and it took a long time to recover. The same thing happened to him some time later and I checked him into VetMed. He came out purring, clean, and happy...and it cost LESS than Dr. Kaneko. He is a money grubber and he really is targeting the cat lovers. Dont believe the smiling face, this is a man who would let a magnificent cat die if not given every cent of the outrageous prices he charges. Boycott the Cat Clinic.  Users/DavisGirl

20070602 12:21:51 nbsp Wow DavisGirl, those are some pretty big assertions youve made. Its strange how no one else seems to have had the same problem. Without more information, it makes it very hard to take your claims seriously. Users/DaveCar

20070821 10:51:41 nbsp I was a client of his when he worked for a vet clinic in Sac. When he open the Cat Clinic, he was a natural choice for vet care for my cats.  He gives the best care and I would recommend Dr. Kaneko to any cat lover.  All his employees are great. Users/bodhicatva

20080209 18:03:40 nbsp Ive been taking my kitty here since we moved to Davis in 2005. The staff is really warm and friendly, and Dr. Kaneko is very thorough in trying to solve kittys problems. They always call to see how she is doing after Ive brought her in with a problem, and I appreciate that. We will be sorry to take her somewhere else when we move away from Davis.  Users/StellaChiara

20080816 09:31:23 nbsp My cat was having unknown pain in her hind quarter. The Dr. basically jumped to a diagnosis without fully examining her. He said that because she was old, it was likely arthritis. Luckily when I picked my cat up to put her back in the carrier, I felt a lump on her haunch and pointed it out. It was an abscess. When you pay a person a bunch of money to figure out what is wrong with your pet, youd expect him to do a thorough job! Users/jtmcn1

20090219 09:32:06 nbsp Im fairly new to the area (been here almost 2 years). Ive been to Dr. Kaneko a few times with my cats and Ive always had a very good experience. Both cats had dentals (one with a number of extractions). I initially went to UCD where I would have been charged 2x what cat clinic charged for the dental (and they wanted to keep my cats in the clinic overnight). Overall, very pleasurable experience! Users/jglovicz

20100214 13:34:42 nbsp This place is great. Vaccines at a fraction of the regular cost at other vets! I would tell people not even to bother with waiting in line at vaccine clinics! This place is even open on Saturdays and you can have vaccines without an exam. Also, with my terrible beast of a cat, the staff was great. Dr Jim really tries to minimize the stress that my cat endures while seeing that he gets what he needs. I really do not like places that mistreat grumpy cats just to get the job done. He always shows me how much services will cost when I ask him and he never pressures me into spending beyond my budget.    Users/Tack

20100224 14:53:58 nbsp Dr. Kaneko and his staff are wonderful. I brought in a very sick feral cat I had trapped the night before and Dr. Kaneko came into the office early to meet me and was a great help. Ive brought in several ferals that needed treatment and he has worked with me to make it cost efficient while giving the animals great care. I highly recommend him  and it is good to work with a vet who really cares about cats. Users/Wujimine

20100410 14:31:31 nbsp Though I believe Dr. Kaneko is very good and his staff are lovely, I also feel that the Cat Clnic is rather overpriced. I had to pay for a full first time visit when I took my kitten in the first time and all they did was weigh her and tell me she was too small to get shots.  Their prices for spaying seem quite high  I was told it would be something like $180 to have my cat spayed.  Though I suppose they are taking some advantage of the fact that Yolo county has no low cost spay/neuter clinics.  As a student, Im unfortunately going to have to drive to Auburn to get my kitten spayed for $30... I recommend this place, however if money is a concern I think its worthwhile to look into other options. Users/soledad101
  While I cant speak to the Cat Clinic specifically, spaying is a substantial and highly invasive procedure.  The School of Veterinary Medicine vet school has clubs which assist with a couple of different lowcost or free spay/neuter clinics, but those tend to have most of the labor performed by volunteersincluding the actual surgery.  Any veterinary office that is observing reasonable safety procedures and that isnt being subsidized through some assistance program for lowincome folks is going to be expensive (several times the cost of a neuter, typically).  If its really $30 and not through some special program, Id be extremely hesitant to take my cat there (I dont think he would appreciate being spayed, anyway...).  Just the cost of anesthesia and the time of a doctor and a monitoring tech is substantially higher than that. Users/TomGarberson

20100411 18:04:37 nbsp At the recommendation of my friends, Dr. Kaneko has been my cats vet for many years now.  In addition to the typical vaccination and exam visits, he has been very helpful with behavior problems and is a genuinely nice caring person.  His prices seems to be on par, if not low compared to other office vets, plus he often has coupons in the green machine.  Easy to get an appointment too.  I highly recommend him. Users/lemurific

20101018 11:35:50 nbsp Ive used Dr. Kaneko, Woodland Vet Hospital, and another vet in South Davis. I have a new kitten & just priced firsttime treatment. A quick comparison:

Dr. Kaneko has been very gentle with my pets and very competent with routine treatment. Hes been sensitive, realistic, & informative about options & costs for very ill pets. For basic kitten care he is $8.00 lower for an exam than the highest option, not including the alwaysavailable coupon for 10% off. FELV testing is similarly lower.

Every time Ive asked, UC Davis has been outrageously expensive.

Woodland Vet Hospital has good vets and IMHO is better equipped than Kaneko to handle higherend problems. They tend to be a bit more expensive. They are less sensitive than Kankeko to costs when discussing options for seriously ill pets, & more willing to go with more sophisticated options. Great vets, though.

Other info pertaining to comments above, JFYI:
 WVH mentioned that all vets are required by law to give a routine exam the first time that they see a pet.
 There are lowcost spay & neuter clinics: my kitten will be spayed for $30. and vaccinated for $8./shot (Yolo County SPCA; there are additional options). If shes small enough, the spay will be $15.
 Emergencies: Alternate to UCD (beyond expensive) is the SolanoNapa Emergency Clinic, open 24/7. Still costly, but not as bad. WVH does emergencies too, but doesnt specialize in emergencies.
 There are a couple of mobile vets, a wonderful option for an animal who you dont want to transport: TriCounty Mobile Vet Service & House Pet Calls. I used a different mobile vet for a frail cat & that was an excellent decision. Unfortunately that vet is no longer practicing here.


 Users/PJ

20110807 13:43:45 nbsp I am extremely happy with the Cat Clinic of Davis, and with Dr. Kaneko.  The environment is quiet, with only 1 doctor, and no dogs in the waiting room (I was also the only client in the clinic at the time).  Dr. Kaneko was very gentle with my cat, making her as comfortable as she can be at the vet.  The most important aspect for me was that Dr. Kaneko took the time to clearly explain all the options available for treatment, carefully laying out all the pros and cons of each option.  In the end, he allowed me to make the decision, without making me feel bad for choosing one option over another.  The treatment option that we decided upon is working well for my cat, and is also easy for me to give.  Dr. Kaneko also did not force me to do any additional tests that I did not feel were helpful. His prices were reasonable for the area, and I found them to be lower than both UC Davis and South Davis.  I definitely recommend the Cat Clinic to anyone looking for a quiet place to take your feline, and a doctor that will be willing to work with you to find the best possible treatment for your cat. Users/BrookeRoberts

20120628 13:37:44 nbsp Ive been taking our cats here for years and Dr. Kaneko has always been compassionate and gentle.  He is direct and patient in explaining things to me and never pressured me to invest more than I was comfortable with in the care of our cats  very nonjudgmental and kind.  Based on my experiences there, I find really hard to believe that he would tell someone that they were not wanted there or be rude. Maybe it was a misunderstanding or a bad day?  He may be a bit pricier than others, I havent researched that. Our dogs go to Midtown, but for cat care you may not find a more decent, honest or compassionate vet. I think hes a good guy who really cares.
 Users/MaggeSanger

20120721 16:18:46 nbsp I have been living in Davis for 4 years now and have taken 4 different cats to the cat clinic. My husbands cat got sick and Dr. Kaneko never tried to push us into unnecessary tests. I found a kitten on a play ground of the school I worked at and took him here immediately (he is always willing to take people in the same day they call, usually within the hour). He gave him nutrients (free of charge) and barely charged me for an exam. Unfortunately, the poor little guy had flea bite anemia and began having seizures and had to be put to sleep. He and his office staff were so helpful for that.
My cat Dinah began having facial ticks and we took her to VetMed. they charged us $200 just to see her, then tried to charge us $1500 for tests. They also couldnt get blood from her. We took her to Dr. Kaneko the next morning and he charged us under a quarter of their cost, was able to get blood, and, no questions asked, gave us antiseizure medicine. She unfortunately progressed too much and he talked us through options, and let us know it was probably the right choice to put her to sleep. Her blood was so thick that he was worried it wouldnt work, so he gave her anesthesia (he paid for it himself) and let us sit in the room for almost a good hour while we said our goodbyes and never rushed us. His staff came in a couple times to check on us and see if we needed anything. Long story short (apologize for the length, I just have a lot of experience with him), I would never trust anyone with my kitties more than the Cat Clinic.  Users/Kelleigh

20120802 17:22:55 nbsp Took my year old cat was was pleasantly surprised by the experience. My cat received a shot for worms and a dose of flea Advantage which was applied with no application charge! Reasonably priced for a specialized clinic, and definitely will go back if I need anything else. :D Users/AnneElvin

20130420 12:45:23 nbsp Dr. Kaneko is an amazing vet. My kitty is FIV positive, and it would be easy to convince me to have a slew of tests done every time I bring him in. I have never felt taken advantage of by the Cat Clinic crew, nor has Dr. Kaneko ever suggested expensive tests or treatments without first suggesting more affordable options. Im baffled by the comments accusing the clinic of being overpriced or untrustworthy. In my experience this is simply not true, and in fact the complete opposite of my personal experiences.  Users/AllisonJoy

20130424 17:40:21 nbsp Weve been taking our cats to Dr. Kaneko since we moved to Davis in 2008. He is so friendly and good natured. Im jealous that my cats have a doctor with better bedside manner that most people doctors. He gives you a range of options when treating your pets, not just the most expensive ones, so you can choose a path that is best for your cat and your budget. Our cat Miranda recently passed away and I had to take her to an overnight hospital to put her down because her symptoms were so extreme and painful. That week I received a condolences card from Dr. Kaneko and his staff. It meant a lot to me and my family. Users/BrianPakpour

20130512 10:16:15 nbsp The best experience ever.  Very nice to have a place where there are no dogs to scare our cat.  The vet and his staff  are very competent, gentle, wonderful to deal with. The vet explained everything in detail that we needed to know.  I could not believe how low the prices are  for a checkup, rabies vaccination, distemper vaccination, nail trimming, and two Advantage medication vials, the total was only $123, with a 10% coupon we had.  AND they called the next day to see how our cat was doing! Fantastic place, fantastic people. Users/DeborahLattimore

20130625 10:05:06 nbsp Dr. Kaneko is such a gentle, kind vet. I have taken my two cats there and he never pushes me to spend more than I can afford, and never guilttrips me for not being able to afford much. One of our cats got very sick and he referred us to UC Davis for some tests he couldnt provide. He followed up with us multiple times afterwards, calling to ask how our cat was doing, offering advice, and making sure both cat and I were okay. No charge for any of that handholding. What a great guy. I also really like that I can always get in the same day. Very calm, friendly office. All around, a great experience. Users/EvaG

20140102 13:50:17 nbsp I like Dr. Kaneko is kind, warm, and very gentle with my cat. However, I have decided to switch vets it seems like over the last several years, this office is becoming more and more disorganized and cant seem to track which vaccines my cat has had and/or needs. The amount of interference I have had to run between them and my cat has escalated quite a bit and to a level I can no longer manage. I do like the Cat Clinics prices and staff, but have reached the end of my abilities for tracking and double checking my cats care. Users/EmilyMoore
