
This page is part of a four (Southern California, Central California, & Northern California) page series on California Californias regions.

The Central Coast spans the region north of Santa Barbara to Santa Cruz and comprises most of the 805 Area Codes area code. Residents of these cities and towns tend to prefer the term Central Coast , although on a direct north/south division of the State, they would fall on the south side. Two major highways run through the region, California State Route 1 (also called the Pacific Coast Highway by SoCal people) and US Route 101. The Central Coast while mostly seaside towns and cities, also includes the Salinas Valley and some other inland regions. Mostly liberal, San Luis Obispo was the only seaside County apart from Orange County to go to Bush. The Central Coast is home to a wide variety of flora, fauna and climates. From conifer and oak forests, rolling grasslands, sandy and rocky beaches and farmland, the Central Coast is a pleasant place that seems far removed from the metropolises of San Francisco and Los Angeles.

 Subregions 

 The Southern End: Santa Barbara County 
Lompoc
Lompoc lies to the North of Santa Barbara and is located inland, away from the coast. This area was originally inhabited by the Chumash Indian tribe. Lompoc lies along Highway 1 by Vandenberg Air force base. Lompoc had its beginnings as a mission town, built around the Spanish Mission La Purísima Concepción in 1787. After Mexico took over the mission, it was secularized and for the most part abandoned. During the Great Depression, the Civilian Conservation Corps restored the missions standing buildings and it has since been used as a museum for visitors. During the 1980s, Lompoc was gearing up for a tourist boom as Vandenberg Air force base was supposed to play host to shuttle launches. After the Challenger disaster, NASA changed their plans and Lompoc fell into a recession after having built up its economy in anticipation of the tourism that the shuttle launches would have brought. Concentrating on a flower industry and the natural beauty of the surrounding region, Lompoc managed to stabilize its economy and has since been dubbed “The City of Arts and Flowers.”

Buelton & Solvang
Both Solvang and Buelton are located off Highway 101 just north of Santa Barbara. Both towns have populations under 6,000 and are connected by Highway 246 that runs eastwest. Solvang began as a small Dutch town that sprang up around the Spanish Mission of Santa Inés in 1911. Many of the buildings were constructed to resemble traditional Dutch buildings from Europe. The town has an excellent variety of cafes and bakeries to offer. Buelton, though smaller than Solvang, has experienced an increase in population over the last few years. Many new wineries have cropped up around Buelton and Highway 246.

Santa Maria
It is estimated that Santa Marias population as of 2005 was around 90,000 individuals. This makes Santa Maria the largest city in Santa Barbara County, surpassing the city of Santa Barbara. In the last decade, Santa Maria has experienced tremendous growth, especially in the Hispanics Hispanic population. The city currently has a slightly larger Hispanic population than Anglo. Santa Maria is situated off of Highway 101 and straddles the county line.  Santa Maria is famous for its strawberries, its Santa Maria Style BBQ, and for being the home of the Michael Jackson trial.


 Midway Between the Giants: San Luis Obispo County

Pismo Beach
Though is has only a population of around 8,500, Pismo Beach remains famous both locally and abroad for several reasons. One may recall that Bugs Bunny had been heading here but took a wrong left turn in Albuquerque, New Mexico. On a slightly more serious note, the Pismo Clam (Tivela stultorum), is a native of the Central Coast and is the official State Mollusk, as well as the unofficial mascot of the town. Yearly there is a huge clam festival, where copious amounts of clam chowder can be obtained. On Fathers Day weekend there is also a huge classic car festival (similar to Hot August Nights in Reno) that any car enthusiast would enjoy. The http://www.monarchbutterfly.org/ Pismo Beach Monarch Butterfly Grove is the largest in the state (and one of the largest in the nation), hosting an average of 100,000 migrating Monarchs annually from October to February (with a 9091 peak of 230,000 butterflies). These particular Monarch Butterflies live an average of 6 months, versus 6 weeks for the common Monarchs.

San Luis Obispo
The county seat, San Luis Obispo boasts a population of 44,000 residents. The city is home to the Spanish Mission San Luis Obispo de Tolosa which the town grew up around, and California State Polytechnic University, San Luis Obispo. About one third of the citys population is of college age or attending college. The town has a slow growth policy similar to Davis, preserving the small, college town feeling it has nurtured over the last few decades. San Luis Obispo is located almost halfway between San Francisco and Los Angeles, making it an ideal rest point for anyone going up or down the state along Highway 101. Just north of San Luis Obispo on Highway 1 is Camp San Luis Obispo, the original home of the California National Guard. Of other interest, Jamba Juice was founded in San Luis Obispo and is still in its original location at 17 Chorro Street #C. Also, architecture student Weird Al Yankovic was a DJ at the Cal Poly radio station and recorded My Bologna in the mens restroom in the library.

Atascadero & Paso Robles
Located north of San Luis Obispo along Highway 101, this region is mostly farmland but wineries have recently been emerging, especially around Paso Robles and Highway 46 to Cambria. Atascadero is a small town that sits at the end of Highway 41 that connects to Morro Bay. Paso Robles, which has a population of about 24,000, is a nice resort town that has enjoyed a recent growth due to its many vineyards. Paso Robles is also host to the California MidState Fair.

Morro Bay
A small, sleepy town located along Highway 1. Morro Bays history goes back to 1542, when Portuguese explorer Juan Cabrillo named the large domed rock in the bay “El Moro”, as it reminded him of the turbans the Moors wore. Morro Rock was at one time twice as tall as it is now, but from 1889 to 1969 the rocks were removed for use as construction materials. A notable example of this is the Presbyterian Church in downtown San Luis Obispo, which is built almost exclusively with Morro Rock stones. Under the Mexican government, large tracts of land were given to cattle ranchers. The close location to an all weather port naturally raised Morro Bays prominence. The outpost didnt form into a town proper until 1870, when a wharf was built to accommodate larger ships. In the 1940s, Morro Bay became a prominent abalone fishing spot until their numbers began to decline. Nevertheless the port still has a large fishing industry, which sees anything brought back from shark to halibut and rockfish. Seals, sea otters, and an assortment of sea birds can be seen in around Morro Bay and her estuaries. Seafood restaurants abound and gift shops selling trinkets and shells can be found by the port. Morro Bay also offers beautiful sandy beaches that are often littered with sand dollars in the early morning hours.

Cambria & San Simeon
Up the coast from Morro Bay along Highway 1 is the town of Cambria. Located in the foothills above the coast, there is a nice mixture of a beach and mountain atmosphere in this town. Deer, raccoon and foxes can sometimes be seen in the glades and groves of Monterey pines. The town boasts a population of 6,000 and has a quaint feel about it. Cambria has a slow growth policy based on a water number which is currently not moving. No construction on new property has been done for about a year now and housing prices have skyrocketed. Cambria is also home to Nitt Witt Ridge, a house built by Art Beal who rescued garbage from the local landfill and used it to build his antithesis to Hearst Castle. San Simeon is further north along Highway 1 and is known mostly for Hearst Castle. This estate was built slowly between 1865 and 1919 by William Randolph Hearst. Like some medieval palace, the estate is large enough to be self sustaining. The estate contains many different architectural styles from Roman to Spanish and Gothic. Hearst Castle is a National Historic Landmark.


 Mountains and More: Monterey, Santa Clara & San Benito County

Big Sur
A beautiful stretch of natural beauty, Big Sur has no proper designations but is generally considered the region above San Simeon to Carmel. The climate is wet, allowing thick forests including coastal redwoods to grow. Sparsely populated, Carmel is the largest town in this region. Highway 1 offers a scenic snippet of this regions splendor if youre only passing through.

The Salinas Valley
Salinas Valley is a rich agricultural belt that is bordered by hills on both sides and runs along Highway 101. Its cooler climate and higher precipitation then the Central California Central Valley allow for greener vegetables like lettuce, tomatoes and other salad greens to be grown here. This region is featured prominently in many of John Steinbecks novels, with his birthplace being Salinas. Salinas is the largest city in the region with a population of about 151,000. Salinas also has the largest shopping mall in Monterey County. South of Salinas is the cities of Soledad and King City, both located along Highway 101. Soledad is home to Mission Nuestra Señora de la Soledad built in 1791. The area around Soledad has many vineyards which attract some tourism. King City is an agricultural town and is located south of Soledad. At the opposite end of the Salinas Valley in the north is Gilroy. Located in Santa Clara County, the town has a population of around 41,000 residents. Known for its garlic crop, the town hosts an annual garlic festival which serves the ever popular, garlic ice cream. Hollister, located in neighboring San Benito County normally hosts the yearly Independence Motorcycle Rally, but it was canceled this year due to lack of security funding. The event is similar to the Motorcycle extravaganza in Sturgis, South Dakota and attracts thousands of enthusiasts from all over the nation.

Monterey
Monterey has a city population of around 30,000. The city is located on the south side of the Monterey Bay. Known for its marine aquarium and fishing wharf, it is a popular tourist destination. Monterey served as the capital of California under the Spanish and Mexican governments from 1770 to 1849. During the MexicanAmerican War, a small battle was fought around the town and the defenders surrendered to U.S. forces where John Sloat a navy commodore raised the American Flag over the customs house claiming California for the United States. The city has an extensive fishing industry that was even larger in the past. Cannery Row is a waterfront street that once had a huge sardine canning factory but now serves as a place for vendors to sell their stuff. Similar to San Franciscos but with its own flavor, Fishermans wharf has many seafood restaurants and gift shops, offering spectacular views of the bay.


The Northern Border: Santa Cruz County

Santa Cruz
A popular destination point for NorCal people, Santa Cruz is the probably the closest you can get to SoCal beach life. Located on the northern end of the Monterey Bay, the city enjoys a cool Mediterranean climate. With a population of about 54,000, the city has a small resort feel. Amongst its attractions are the large swaths of sandy beach for swimmers and bathers, good surfing conditions, the states oldest boardwalk and a redwood forest adjacent to the city that offers many camping and hiking adventures. Several serial killers inhabited Santa Cruz during the 1970s earning the city its nickname “Murder capital of the world.”  The city was once pretty conservative but is now very liberal. Partly due to its relatively close proximity to the Bay Area, but largely due to the opening of UC Santa Cruz in the 1960s. A beach/bohemian culture that was partly born from this liberalizing can be seen throughout the city, especially in its younger residents.
