



>“We give you peace of mind about the safety & reliability of your car”<


Center City Automotive owned by Users/d&mHatton Doug & Margee Hatton, is a quality, leading automotive repair center providing competent and honest service since 1981. Friendly atmosphere and topnotch advice at the front counter and on the phones is provided by Doug Hatton & Jim Wolgemuth. Automotive technicians Dave Haverstock, Steve Moore, Shawn Heaton, Rick Mortensen and Sean Sears dont just fix or maintain your car, they get to know you and your car. Let Center City Automotive keep your vehicle running right, and when needed, help you get back on the road with the right repair solution.

See Center City Automotive on Facebook:  http://www.facebook.com/centercityautomotive


  See also: Automobile Repair.



20060901 09:47:33 nbsp Ive been using them for a couple years and I really like them. They are honest, do good work, and every once in a while, throw in an extra fix that you didnt ask for. After going to Advanced Auto for a while, Ive been very happy with the service at Center City. GreenThing

20070601 18:19:56 nbsp Great service! The guys there were extremely helpful, thorough, and very quick.  Users/LinneaUggla

20070802 17:38:41 nbsp Today was my first experience with Center City and I will definitely be trusting them with my car for future repairs.  They were professional, made the necessary repairs quickly (same day) and for much less money than I expected to pay!!  They also took the initiative to do a quick scan of other systems, including belts to ensure all was fine.  They have certainly earned my repeat business! Users/scd

20070827 20:04:31 nbsp This is a great place to take your car to when having troubles.  They are reliable, knowledgeable and honest...which is everything you need when looking for someone to fix your car.  They do let you know what youre paying for and why its something you need to fix.  Definitely the go to place in town! Users/Danya

20070904 14:23:07 nbsp This place is great. My Toyota truck had a blown headgasket, and when my dad and I decided to repair it ourselves instead of having them do it (the cost of repairs would have been just short of the value of the car) they gave us plenty of advice and tips. Ive had them do lots of other service, and wont ever go anywhere else. Users/BryceEsch

20071110 23:53:49 nbsp Very nice people. Friendly, prompt and honest. They explained to me what needed to be change and why. I went in originally to fix a slipping clutch, they installed the new clutch; however; the new clutch was defective. The guys at Center City reordered a new and more expensive replacement clutch for me at no extra cost. After my first experience, I went back and had my timing belt and water pump fixed. Would definitely recommend them. Users/GMC

20080211 10:51:38 nbsp This is bar none the best independent shop in Davis.  I have been going there for years, and before that my family.  They are honest and reliable, I have NEVER been up sold or told something that turns out not to be the case.  their price is always competitive to big chains, and they know your name and your car.  they will give you the truth even if it means they lose a job.  When a repair doesnt solve the issue as well as you would like they are eager to find out what needs to be done and always fair with price.  ALL shops will make mistakes, faulty parts happen etc... it is HOW they deal with it that counts!

example:  My front end was squeaking, they said it was a dry joint someplace in the suspension...  said it is an ungreasable joint, and is replace or nothing.  BUT, they then said that they tested it for wear, and it is still well within tolerances, so as long as I can deal with the squeek, it is no biggie!  I was shocked, probably $500 in labor, any other shop would have just said, yeah, your flux capacitor is out, you need a new one.

Doug and Jim at the desk are a bit bearded up as one commenter mentioned... but they are honest and listen to you...  much better than some 21 year old clown at the desk of speedylube or whatever.  It is a great feeling to have a trusted mechanic... to know that although a repair might not be cheap, they will do what needs to be done right, and at the best possible price.  Users/Carsonsig

20080514 01:03:42 nbsp Excellent service! I took my Nissan car to them to check the Service Engine Soon light. They found out that it was my cars front catalytic converters problem. They called the Nissan dealer and found out that my car was still under warranty (I bought it as a used car, so myself did not realize Nissans 8 year/80000 miles warranty). And the warranty was going to expire in 3 weeks! It was so nice for them to find out that I was still under coverage. Then I called Nissan and got my part replaced for free (or I have to pay almost $500 for a cat converter!).

So I strongly recommend this mechanics store! People are honest, knowledge and professional. Whats more important, I feel that they were really standing on my side, gave good suggestions to save $$ and get the best deal. Users/ezhang

20080710 15:31:20 nbsp they are the best. i refuse to take my car anywhere else in davis. my car is there right now and ive been going to them for like 2 years or 3. they dont make me feel like an idiot when i tell them whats wrong w/ my car even though i should because sometimes its me running the battery out on accident. today i was pushed into the schedule even though they were overbooked w/ cars. they said theyd try to fix it in the best time they could. they are really honest there and grateful for the trust that people have for them. also they remember you well.  Users/KimberlyMiller

20081110 23:29:35 nbsp Overall experience: Very Good, Very Satisfy, Very Professional.
I needed a replacement of a Starter in my car, and I called around Davis to get the best estimation of the cost. Center City Autos called back with the best price, and agree to use factory manufactured parts for my car, which is exactly what I wanted. I brought my car in around 12pm on Monday, and Jim/Doug called me that my car is ready to go at 4pm of that same day.
Very fast services, and Very friendly. Jim/Doug would chat with you and answer questions relating to car that you may have. They do look like two hippies (especially when they said Peace to me, Hahaha). My overall experience here is very good because of their friendly manner, and their pricing were the cheapest that I could find in Davis. I recommend this place to whoever need their car diagnose and/or fixing.  Users/crepelover

20081112 15:44:18 nbsp This place is FANTASTIC. My windshield wipers stopped working on the first truly rainy day this year. I dropped one child at preschool, called Center City on my way home, was able to drop the car off immediately, and my infant daughter and I were given a ride home by courteous staff member. Two hours later they called to let me know the wipers were fixed (wiring was loose) and that I could use a new battery...which they installed free of charge (only paid cost of the battery). They picked me up within 1/2 hour and I made it back to daycare pickup on time. Amazing service. Far exceeded expectations. Users/JMakus

20090304 11:14:36 nbsp honest, great, fast. not too expensive. I have never been to a better auto shop! Users/yadayada

20090626 21:26:34 nbsp I took my truck to center city auto because one of the spark plugs blew out. I took it in knowing that this was the only place in davis that could work on it so I was skeptical. They told me that the spark plug hole was as big as it got and I needed a new engine that would cost me anywhere between 3,000 to 6,0000 dollars to fix. So I got it towed to San Francisco to a family frieds shop and the friend told me that Center City was lying to me and he fixed it for 200 dollars including service fees. Users/kseabright

20090713 09:01:39 nbsp Took my car in for a couple of very simple repairs and was very pleased. The repairs were done quickly, well, and for a reasonable price.  The guy at the counter was really nice.  Ill definitely go back if I have more serious problems. Users/DataPoint

20091016 20:48:31 nbsp Speedy service, but extremely irritated that they charged me for something they didnt repair. Now I have to wait until Monday to take the car in  again. Im sure Ill either get a refund or proper repair on Monday, but its extremely frustrating that they dont have an answering machine of some sort. Users/ElizabethAbinante

20100604 08:08:53 nbsp Jim and Doug have done very good jobs on my cars, always with unusual friendliness. I feel so much reassured now with a trustworthy auto repair place to have. More Davis business folks could try to imitate them!Subodh Users/SubodhJain

20101011 13:09:29 nbsp These guys are EXCELLENT. After my A/C was misdiagnosed 4 different times by another auto body shop, I took it to Center City and they got it right the first time. Ever since then my A/C has been working perfectly. Everyone here seems to be super friendly and knowledgeable as well. I plan on taking my car here and only here in the future.    Users/trevorchreid

20110218 12:03:11 nbsp These guys are the best! Fantastic service, very honest and reasonable. We been going here for many years. They always go above and beyond. Thanks Doug and Jim and your great team!! Users/agerould

20110513 15:49:02 nbsp I have gone to Center City for a few years and had nothing but positive experiences. My car broke down a month after I moved to Davis and I knew no one in town, but a kind couple passing by used their AAA membership to tow my car to their shop (Center City) which they highly recommended. I was not disappointed!! My car was repaired the next day and for a very reasonable price. Every time my car has had a problem I have taken it to them and they have been just awesome and always treated me kindly. I was driving an old car (25+ years) and these old cars have problems, you know, but I dont think I ever saw them twice for the same problem. Once they fixed something it was FIXED. I could not ask for better repair service, really. They also back up their work, so if you have questions, concerns, or are just confused about how your newly repaired car is running they are super patient. Yeah, Doug and Jim kind of look like hippies and have some of that hippie zen to them, but they are undoubtably solid and professional mechanics. I ended up selling my old car and they were the first people I called when something was wrong with my new one. Unfortunately they dont work on the type of new car I got, which made me sad since I trust them and they have done good work for me in the past, but they gave me a recommendation to another shop that is on the same level as them in terms of quality, honesty, and value.  Users/DanaMace

20110815 20:03:14 nbsp I took my car here for an oil change. It wasnt the cheapest oil change (It would have been $50 if I hadnt brought my own oil and filter, so it would be nice if they had coupons or a student discount.), but they were really helpful. After they saw that my oil level was a lot lower than it should have been, they checked around, found some potential problems, and patiently explained them to me without making me feel pressured to spend hundreds on a bunch of repairs. They also washed my windshield and topped off my power steering fluid for free. This is the first time the oil change wasnt done by my dad so I have no idea if thats customary, but either way I thought it was a nice touch. Update: As a quick note about my oil change, I noticed later that the oil was a whole half inch above the full line on the dipstick. Not sure how/why they put in too much, but they took the extra out for me.Users/MeggoWaffle

   The big reason Im editing this comment is I recommended this place to my partner and he had a very mixed experience. I have pasted his account below:

My experience with Center City was mixed.  I brought my car in when a belt broke, thinking it would be a simple fix.  However it turned out several things compounded to cause the belt to break and it would be more money to fix than the car was really worth to me.  So I asked them if they knew if any mechanic would be interested in buying it off my hands and having a fixer upper.  The person I spoke with kindly said he would check around.  Unfortunately nobody was interested, so I came in to ask what my options were.  He came up with a third option: they fix as little as possible to get the car running so I could retire my car with the state of California.  They bought cheap parts and fixed as little as necessary for the car to make the drive to Sacramento to the salvage yard.  This saved me a lot of money.  I really appreciated how they worked with me for a solution.  The negative was their communication.  They constantly left me waiting to hear from them, even when they said they were going to call.  Looking at my phone records, they only called me twice during this whole ordeal.  I was forced to call them when I hadnt heard from them in days.  The worst was that they kept pushing back the day when they said the car would be ready, and it ended up taking a week to fix my car up just so it would be drivable and I could sell it to the state.  They were clearly putting other cars ahead of mine, which was frustrating considering I was a paying customer like any other and it had already been there for nearly a month.  For the $90 an hour they charge for their service, it didnt feel even remotely worth it.  Also they misquoted the original cost to fix my car by $200 due to bad math.  So the positive is that they worked with me to find an alternate solution to my car troubles which was nice.  They were also extremely friendly when I spoke with them.  The negatives were that they seemed to put my car on the back burner while they worked with other cars and they were very bad at communicating with me.  They also charge $90 an hour for labor which is in the upper end of what mechanics normally charge.

20110825 17:26:37 nbsp Ive gotta agree with most everyone here  theyve got the best prices around, they do great work, and they dont just do the bare minimum  they genuinely want your car to run as well as possible. Theyre honest and are great at explaining everything having to do with your car. Ive tried a number of other places before, and now wont go anywhere else. You really do feel like theyre on your side  not trying to cheat you out of money or say that your car needs stuff it doesnt. Im glad theyre in town. Plus, how often do you get your car serviced by the lookalike members of ZZ Top? ;)  Users/mday24

20120531 15:47:40 nbsp Today we noticed that our headlight was out on our Prius.  The last time the headlight went out, I brought the car to the Toyota dealer in Davis and they charged me $150 to change the bulb claiiming they had to remove the bumper.  I called them today and they gave me the same price.  I called my local mechanic, Center City, and they told me to bring the car over and they would take a look.  They changed the bulb after working on it for half an hour, charged me $15 for the bulb (the bulb at Toyota was $40) and sent me on my way.  I love Center City, have been taking my cars there for repairs for years and have always been more than satisfied.  I recommend them highly for any auto repairs.
Shelly Bailes/Ellen Pontac Users/ShellyBailes

20130404 13:31:43 nbsp Ive been going to Center City for a few years now and like them a lot.  Ive always felt theyve given me good work at a decent price.  Ive never felt pressured to get extra work done, (in fact, I think they go out of thier way to not do this).  The last time I brought my car in for major work, they replaced my radiator and water pump.  The next week I noticed some minor coolant leakage, and when I called back they repaired it quickly and free of charge.  It was the type of service I would expect from a good mechanic.  Also, while a lot of garages can look somewhat sloppy, the Center City facily is always clean and organized.  Doesnt necessarily mean they are altogether better than anyone else, but think it suggestive of the type of work they do, i.e. professional and honest.  Highly recommended. Users/jefftolentino

20140327 21:07:04 nbsp Knowledgeable, fair, honest service.  I have been very pleased with both major and minor repairs by Center City. Users/Nokomis
