
Claire Black Slotton is one of Davis resident real estate agents.

For over 20 years, Claire Black Slotton has been providing the kind of oldfashioned service that people talk about over and over. Thats why her clients keep sending their family and friends her way. In fact, over 80% of Claires business is repeat and referral. She knows the town; she knows real estate and shell negotiate like a tiger for you.

She is also a Davis resident and a democracy advocate.  She stands in front of the Varsity Theater after some showings of Al Gores movie An Inconvenient Truth about global warming, with an ironing board, stamps, envelopes, pens, paper, and addresses of elected officials for Davis so people can communicate their will to the people who are supposed to be representing them in government. You just write your letter, address and stamp it, seal it up, and put it in the box with the rest, and Claire mails them all together. Claire is serious about democracy and regards the writing of letters to ones representatives as something akin to voting, and for that reason she is very careful about the secrecy of your letter.

Unfortunately she is not able to do this all the time as she has a business and a family to look after.  Claire has her ironing board and writing materials stored in a closet at the Varsity Theatre, so if you want to fill in, you need only mailto:claire@iclaire.com contact her and show up at the Varsity when a movie showing gets out. Or alternately, you could get your own materials and table at the Varsity, or anywhere else.


20061019 20:59:37 nbsp The description above provides some interesting context about Claire. However, if you happen to  navigate to this page from Realtors, you might find yourself a bit mystified about Claires skills in real estate. What you would want to know is that Claire is highly experienced, very knowledgeable about Davis, savvy about real estate buying & selling process, has an unassuming lowkey style, and  perhaps the most important quality in someone that will broker one of the lifes most important economic transactions  she is thoroughly honest. She helped us buy our dream house in Davis, and continues to provide occasional advice and counsel, years later. Highly recommended. RayValdes

20090729 15:21:49 nbsp Ive run out of adjectives to describe Claire.  Let me put it this way ... I wish everybody I knew was buying a house so that I could recommend her.  She is phenomenal.  Claire knows Davis.  She knows real estate, she knows people, she knows painters and contractors and who to ask for toilet recommendations ... Claire Knows.  Everything.  Shell probably even give you restaurant suggestions if you ask.

Claire is the kind of service provider you want at your side, particularly in this market.  I had a very complex circumstance, and it was very frustrating at times (and frankly, Im kind of a handful) but Claire always made me feel that I was more important than the sale, and was always looking out for my best interests.

I cannot say enough good things about her, and if you are looking for a realtor and you happened upon this page... Lucky you.  Your search is over.  Go buy a lottery ticket.  Users/NDS1111

20091012 12:04:45 nbsp As a new first time home buyer moving to Davis, I was so relieved and happy to meet Claire.  She was extremely patient and knowledgable about Davis and homebuying.  She was extremely responsive to my questions, my schedule (she even met me late on a Saturday night to get an offer in writing after I got off work)and my desire to get the right house  without any pressure for a quick sale on her end.  I found our days looking at homes to be enjoyable and it was obvious by the homes that she had listed as a sellers agent that she was a true professional.  I later found out that she had helped some other friends who had a similar experience. Buying a house can be an extremely stressful time but Claire took the time to explain the process and the pitfalls and was a true ally in the process.   Users/hladner

20100208 09:00:58 nbsp The comments about Claires political interests are wonderful, and certainly in line with her professional drive and focus.  However, were writing this comment about Claires expertise in helping us buy a home in Davis, after two years of renting.  She is able to explain very clearly her business philosophy and style (organized and disciplined, and she hopes for the same with her clients), and yet she listens closely, and respects, what we wanted and how we wanted to work.  For us, the two key items with Claire were her record as a realtor (number of sales, long (20 years!) familiarity with the Davis market, and professional certifications), and her knowledge and understanding of disability access issues.

We went on two tours with her, where she had collected four or five homes with differing features.  Each time, after listening to our comments about the first house, she discarded a couple from the set.  By the second tour, she understood exactly what we were _really_ looking for (even though we hadnt articulated it clearly for ourselves!), and in less than two weeks had found a nearly perfect house.  My wife describes it as the most perfect house weve ever seen  and that in ten years of homebuying in both the Bay Area and Davis.  Claire was able to put together a purchase for us which closed less than a month later, including some backandforth with the sellers.  She recommended a contractor and decorator to get the house ready for us.  Throughout the process, Claire was great about both taking and returning our calls, addressing and calming our nervousness, and making sure that we were getting exactly what we wanted, both in a home, and in the process of working with her.

For anyone looking to buy (or sell, I think) a home in Davis, we would recommend Claire without reservation. Users/kelseymh
