

Clarity Massage is owned and operated by Stuart Steinman, a certified Massage Services massage therapist.  He offers deep tissue, Swedish, sports and relaxing massage. Rates are one hour for $60, or two hours for $100.

  From therapy to pure relaxation, Davis offers a variety of Massage Services


20071129 21:19:02 nbsp Ive only had one massage with Stuart so far, but I think he is a fantastic masseuse.  I visited him with very tight hamstrings, IT bands and quads, and he worked them out beautifully  just the right amount of time and pressure.  Highly recommended!

If you need any more convincing, he has a wonderful introductory special  2 hours for $75. Users/LibbyS

20080723 09:59:48 nbsp Does anyone know why some comments made about Clarity Massage were removed from this page?  Isnt the point of posting on these websites to inform other potential customers of the experience they may receive?  Users/UnsatisfiedWithClarityMassage
  I think you should ask Jeff Speckles about why some comments were removed...  Users/StevenDaubert

20080816 00:54:22 nbsp I have been seeing Stuart Steinman of Clarity Massage regularly since April of this year, and he is definitely the best massage therapist who has ever worked with me.  He is very skilled, has always made me feel more than comfortable, and has the caring nature of a true healer.  I would definitely recommend him. I suffer from myofascial pain, intrinsic pain from a bulging disc, and other consequences of having been injured in car accidents. Of all the many massage therapists I have seen in Davis, Sacramento, Los Angeles, Hawaii, and Massachusetts, Stuart has provided me with the most relief, providing deep tissue massage with the perfect amount of pressure.  After having suffered a particularly grueling period of several months of nearly constant pain from the base of my skull down my neck, with referred pain across my shoulders and into my upper back, it was only Stuart who spent the time and made the effort to pay such attention to my muscular tension and pain, listen to me, and pretty quickly tailor a course of treatment for me that had me walking out of his office painand tensionfree after my second visit to him.  My condition is chronic, so the pain and tension return, but never to the levels prior to the time I began to receive massage therapy from Stuart. Although I am a patient receiving care from the U.C. Davis Department of Anesthesiology and Pain Medicine, and although I have been prescribed powerful pain medications and treated with physical therapy, cervical steroid trigger point injections in my neck, shoulders, and upper back, and acupuncture with vibration, no treatment provides the high level of pain relief that I am fortunate to receive from Stuart Steinmans massage therapy.  From what I can see, Stuart is genuinely, truly happy about the fact that he has helped me, and continues to help me, to such a great degree.
Prior to receiving my first massage from Stuart, I was regularly seeing another massage therapist who repeatedly chose not to listen to me when I told him I needed deep tissue attention to my shoulders and neck.  When I told this other therapist that I had found a massage therapist (Stuart) who actually listened to me and as a result, relieved my pain, the other therapist demanded information about my new therapist and was upset that I was leaving for someone else. I thought this other therapists reaction was highly inappropriate, and did not divulge Stuarts name, although the other therapist may have seen Clarity Massage written in my calendar. Needless to say, I was perturbed when I recently read a posting from an anonymous person that contained serious unsubstantiated, highly defamatory allegations against Stuart Steinman and Clarity Massage.  I would not be surprised if this posting was made by a disgruntled competitor too cowardly to be anything other than anonymous.
My name is Kelly Williams Ching, and I have been a Davis resident for almost 20 years.  I owned a business in Davis for a short period of time a few years ago, and I have practiced law in Sacramento since 1994.  I stand behind and support Stuart and his business one hundred percent. Stuart Steinmans massage therapy has greatly improved the quality of my life, and Stuart represents only kind, compassionate care, so it is disturbing and disgusting to see him and his character attacked in a way that can negatively affect his very livelihood, not to mention the pain and stress this nameless, faceless, cowardly attacker is causing for Stuart and his family.                  Users/KellyC

20090623 14:13:38 nbsp Ive payed for a few massages in my life, and Stuart is the best!  Ive never had a more comprehensive massage.  I highly recommend clarity massage if you want a real massage.  I was losing hope it finding someone who could really work out a lot of kinks in my back, and Im thrilled I found here.   Users/AyseG

20090928 18:27:14 nbsp I guess the massage was pretty good, but I was pretty bothered by the environment.  The sheet and towel repeatedly slipped, exposing me.  I have had many massages and this is way out of the normal. Users/Meemsie

20100106 00:40:07 nbsp If you are female, do not go to this business.  Stuart Steinman harasses female clientsaccidentally or outright, whichever he thinks he can get away with.  This isnt a rival businesswhich is the lame excuse given in these volunteer comments trying to defend himbut simply someone who wants to warn ladies that may go/are going to Clarity Massage.   Users/LongtimeResident

20100716 16:22:24 nbsp I also felt uncomfortable during the massage things that youre not sure he meant to do but that bother you and the more you think about it the more it bothers you. It sucks because other than that he gave me the best massage ever! Users/JasperD
