

Comcast has been providing Media cable television service to Davis area residents for a while, and now offers broadband internet and telephone service in Davis as well. In addition, Xfinity also provides home security systems and monitoring including video monitoring. They also provide thermostat/lighting control. This is all controlled from a 24/7 Comcast monitoring center. Sleep well because Comcast is watching you... The City of Davis Telecommunications Commission is in charge of the http://cityofdavis.org/cs/cablefranchise/index.cfm franchise agreement with Comcast governing their business in the town, and complaints about Comcast should be sent to the Commission. The base price for broadband internet and basic cable TV service is about $57 per month, though they have been offering various discounts to entice customers away from existing options such as SBC Global and Omsoft.

Comcast has rebranded their digital cable, internet, and telephone services to Xfinity. The rebranding was done to try to distance themselves from past negative interactions with their customer base nationwide. Xfinity stands for infinite content choices and crossplatform features, thus guaranteeing an inability to deliver what they promise.

Xfinity commercials and online advertisements now omit the use of Comcast name almost entirely.

Comcast owns all of NBC Universal. They used to own only 51%, but Comcast decided to buy the rest in order further their quest for world domination. Comcast also owns Fandango.com and holds ownership in many cable TV networks.

Comcast changed its logo in 2012 to permanently include the NBC Peacock logo.

Comcasts scheduled maintenance windows start at 12:30 AM. Your phone and internet might go down then. And you wont be given any notice. If you regularly stay up all night working on some assignment, this will probably bite you eventually.

Comcast Internet does some stupid things. One example is ESPN360. ESPN360 is trying to be like a cable channel on the internet. If you want it, your ISP has to subscribe to it. If you want to subscribe to it and your ISP doesnt pay for it, you cant. If you dont want to be throwing ESPN360 money, you cant opt out. Another example is them http://networkmanagement.comcast.net/DomainHelperLogic.htm hijacking DNS records for domains that dont exist and using this to try to serve you ads. Essentially, theyre lying to your computer saying a server exists when it doesnt, breaking a lot of stuff, and using the opportunity to put ads in your face. If youre looking at getting internet for your place, you might want to check out your Broadband other options.

XFinity Customers who had boost service previously just got a faster connection rate of 25mbs vs the 16 they had prior. XFinity speeds are close to 54mbs but tend to cap lower and ranges between 37 and 45 Mb/s to date. New Customers Triple Play Internet, TV and Digital Phone service 99.00/mo for the first 24 months ... Internet max 250gb downloads per month (114.99 for year 3 and 129.00/mo after). Triple Play Preferred Includes three free months of HBO and Showtime along with one year of free DVR service 119.00/mo 24 months ... Internet downloads max 400 gb/mo. (135.00/mo. year 3 and 149.00/mo after), HD Preferred PLUS Triple Play 139.99/mo first 24 months Internet Downloads max 550 gb/mo. plus free Internet TV/film downloads(155.00/mo. year 3 and 169.00/mo after).

Payments can be made at the office on Research Park Drive. After hours, payments can be dropped off through a slot in the door.

If you subscribe to both Cable and Broadband through Comcast, its about $95 a month (new customers only).  They charge 45.99 for Internet (existing customers cost $79.99/mo. offer is for new customers only), 49.99 (or so) for TV (though you can get Basic Cable for approx. $11 it doesnt come with any cable channels such as MTV though). But they do a promotional $19.99 per service for the first 3 months.  And free home installation for the broadband.  Threaten to cancel your service! Last June I called to say I wanted to cancel as some roommates would be gone and the remainders couldnt afford it, as well as moving, etc. They responded with offering me the $19.99 promotion again! So I had 6 months of cable Internet and television at about $40 a month, totally awesome. You can also pay with a credit card over the phone, either with the automated system or with a service rep.

Xfinity is no longer just a cable, internet, and telephone provider. They are now selling home security services and thermostat/lighting control. Yes, Comcast can now control your home security, lights, and temperature. Remote control and video monitoring is available. You can access your homes systems from a mobile phone or computer.

Significant Outages in Service
>Image(tech support.png,thumbnail, 600, Accurate depiction of Tech Support)<

September 2010 Outages and Problems

Starting from the 9th of September (according to one Comcast tech), a series of problems started affecting internet service in Davis through Comcast.  Continuing into October, a wide array of people reported problems.

Read more about your neighbors experiences and add your own on the /September 2010 Outage entry about the outages.
Winter 2005 Outages
Comcast had so many problems in winter of 2005 that The Davis Enterprise wrote an http://www.davisenterprise.com/articles/2004/12/02/news/029new2.txt article about it.

  Wasnt this because Comcast broadband was new to most of Davis? I was told that so many people were getting it that they werent able to handle the load. It had something to do with previous arguments with the city of Davis (I think there was an aggie article about it once). Having to tear up some roads to lay cable, and the maintenance over the years, etc. They did have a bit of a rough start but for tons of people who were stuck with shitholes like Cal.NET it REALLY was like a lifesaving desert oasis. Users/EdWins ES

    Yes, that was a large part of it. They have since upgraded their network to better handle the load. I wasnt all that pissed about it, I got several months of service free by bitching at them a lot.  Users/RyanCastellucci

Comcast Cable Internet is notorious for having extended periods of no service. This leads many people to lament that Comcast is good...when its working.  Typically there is nothing you can do during these blackouts and if you call support they will tell you power cycle your modem. In fall of 04 Comcast entered the cable Internet market in Davis, which goes some length in explaining their unstable service, but after speaking with a technician, it was revealed that outages during the spring of 05 were in fact caused by an apartment on Valdora who subscribed to Comcast and shared their Internet with their neighbors. Naturally everyone on the connection was downloading movies and thus by the technicians estimate they were using about 10gigs of bandwidth a day which caused instabilities in the entire network. The FCC was contacted and as a result these people were banned from Comcast for life. Comcast is for the most part much more stable nowadays but if you do not get the promotional rate, it is pretty costly per month.  The upside to this is that you are getting much faster speeds than DSL and there is no annual contract to maintain.  DavidFu

  The outage caused by one apartment, and subscribers banned for life sounds urbanlegendish.

     It is a perfect example of an wiki:wikipedia:Urban_legend urban legend. Would the load be any greater with their neighbors connected even with everyone downloading movies than with they themselves maxing out their bandwidth? No, it couldnt be. It would just mean that their neighbors service would suck. (Why all this persons neighbors (naturally) are such video download hounds to a greater extent than the general public is another mystery.) Even if we pretend that it was all true: one persons neighbors couldnt have much of an effect compared with the entire population of Davis which Comcast services. Even if everyone in the city decided to peg their bandwidth at the same moment, it still wouldnt be expected to cause instability (something only in Hollywood movies, you know like the router/computer exploding and the wires catching on fire...). In reality, packets would get dropped, peoples accesses would timeout, but no equipment would be harmed (!) and when the heavy load ceased, everything would return to normal. Its caused DenialofService. That urban legend is just the sort of thing the ISPs would love people to believe. ISPs and telcos pricing structure is based on averages the more people use, the more it costs them. Thus, they dont make a profit on heavy users and try to discourage/harass them as much as they can get away with without alienating the rest of their customers. Users/SteveDavison

  10GB per day only averages out to 925kbps, which Comcasts network should be able to handle even if it were designed by trained monkeys. I once downloaded 20 gigs overnight (All 14 Debian Linux CD images, plus the DVD images) and nobody broke down my door. I also have no idea why they would contact the FCC, sharing your connection like that is legal (IANAL), though it does violate Comcasts TOS (terms of service). That said, I think that their network was initially underengineered, but it seems to have gotten better. Check out http://www.broadbandreports.com/forum/remark,11455559 this thread on broadbandreports.com  Users/RyanCastellucci
  Agreed.  10GB a day isnt hefty at all. On the upper end of common use, but not break the network usage.  Also, unless they had faulty electronics and were broadcasting RF, the FCC wouldnt give a darn about anything they were doing  the FCC doesnt have anything to do with bandwidth (wireless, yes, but again, its at the electronics level, not the usage... a wireless router can share/broadcast/download anything and the FCC doesnt care as long as it stays in the allocated frequencies).  This sounds awfully like an urban legend spawned by people who were sharing cable and/or bandwidth with their neighbors, got caught and banned, and decided to talk it up into a bigger story than it was (or the chain of gossip inflated events).  Users/JabberWokky
   Maybe the people hacked their modem to remove the bandwidth limit. This can indeed wreak havoc on a cable network, and would warrant FCC involvement. However, rather than being banned for life, the persons responsible would probably end up in jail.  Users/AmitVainsencher AV
    The FCC would only get involved if said hacking caused signal leakage, which is unlikely. Removing the bandwidth cap is just a matter of changing the firmware. It doesnt somehow change the shielding which keeps the signals contained in the cable system. As for the prison thing, that would only occur if Comcast convinced the DA to prosecute on computer trespassing charges or something like that. Lets assume for a moment, however, that the hacking causes significant signal leakage. The most the FCC will do is send you nasty letters and issue an administrative forfeiture if you ignore them for a year or so. wl

Daily Degradation in Service

 Ive had Comcast in my last two apartment complexes working beautifully, except for the initial few rocky months it was new to most of Davis. I now live in Brush Creek Apartments, and am starting to have some trouble with my broadband.  I used to live with 4 other guys at one complex, 2 at the other, and here its just me and my girlfriend  Im positive its not some bandwidth hogging issue. Its fine in the morning, but as the day progresses, it seems to get worse. It just gets slower starting in the afternoon. Verified using a few online tests (stuff like http://bandwidthplace.com/speedtest/, etc) and the highly efficient counterstrike method: open up my servers list and just watch the latency go from 20 or 30 in the mornings to 100+ in the evenings. Makes for crap playtime. Is there anything they could do if I call them up, or am I just S.O.L.? Users/EdWins ES
   Ive been having the same problem. They probably wont fix it, but they will give you a discount on you bill if you whine and ask for it. If you take a look at my smokeping page, you can clearly see the lag for me, and one of my friends who lives across town. Id be happy to add you to my monitoring there if youd like something to back up your complaints when you bitch at Comcast. Users/RyanCastellucci

Comcast on good day with the premium service level: {{{
23:13:03  http://kernel.org/pub/linux/kernel/v2.6/linux2.6.14.4.tar.bz2 > `/dev/null
Resolving kernel.org... done.
Connecting to kernel.org204.152.191.5:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39,194,430 application/xbzip2

100%> 39,194,430  1006.65K/s    ETA 00:00

23:13:41 (1006.65 KB/s)  `/dev/null saved 39194430/39194430
}}}

Note that Comcast is now considering bandwidth caps with overage charges, as well as reducing the speed of your entire connection if you download data faster than they think you should (regardless of whether or not you are actually paying for the ability to do so).  More information on this can be found at http://gizmodo.com/387901/comcastconsideringmonthlydatacapsandoveragefees Gizmodos article on the subject
  Looks like its no longer a consideration. On Thursday, Comcast officially announced that http://arstechnica.com/news.ars/post/20080828itsofficialcomcaststarts250gbbandwidthcapsoctober1.html theyre implementing a 250GB bandwidth cap for their subscribers. It looks like a horrible practice, but many of us have to deal with them since theyre often the only ISP available in the area.  Users/WilliamBinnsSmith

  Apple just announced the availability of high definition programming via iTunes.  A single 1 hour TV show with no commercials (ie. a 43 minute long video) in high definition (1280x720) is 1.3 GB.  To really understand the impact of Comcasts bandwidth cap, the average TV viewer watches about 8 hours of TV per day.  If you were to attempt to get your TV from the Internet (through iTunes, for example) rather than live through Comcasts video stream, and you were an average user, you would get kicked off the network by Comcast.   Users/IDoNotExist

Another interesting fact is that the quality of the cable reception and internet speed is based partly on how far your house is from a hub, which are those little green domed things about a foot tall in some peoples front yards. Many of them are also encased in a black sleeve approximately 1.5 feet in length on what appears to be the lowest power lines (such as at the corner of 4th and J Streets). If your home is more than 300 feet or so, then there can be some problems with signal quality and channel reception.

Solutions

Questions you may wish to ask

After upgrading my Internet service to receive cable (and many problems along with it) I was informed of some things by the technician who finally appeared to fix it that told me I was never able to receive the bandwidth or signal quality I had been paying for the entire time because of a filter that should have been removed 3.5 years ago.

 1. Are there any filters on my line that should not be there? As far as Internet goes, if this filter is on your line you will only have access to the most highly populated data channel #79. Without the Filter you will have access to #7679 allowing for a less populated signal and access to cable as well.  For cable, if you see the code 12:00m in the info guide where the time should be or if you see the code S0a00 on a channel you should, but are not able to, receive, it may be because of this filter.

 1. What is my signal strength?  When paying for cable this could be the difference between functioning HD channels and fuzzy or no picture quality at all on many of them. As for the Internet, it is the difference between truly highspeeds and barely above DSL quality speeds and might prevent you from obtaining the bandwidth and baud rates you are paying for.

 1. During and after repairs ask about exactly what repairs the techs are making and to see the parts, if any, that were repaired, exchanged or removed. You have the right know, and the techs are required to share the information to inform you, about any and all repairs they are making to your service. Take pictures if you would like to, but always ask detailed questions so you know whats going on with the service you are paying for. Knowing this information could be the difference between a tech telling you to powercycle your box or modem for the hundredth time or actually getting you the help you need with your service.

 1. Whenever getting new service through Comcast, make sure they test all the lines form the cable box to your residence. It is part of their job (which they often do not do if they are not asked to) and they are required to changed any lines that may cause a conflict (at NO COST) to ensure you have the service you are subscribing to.

In case anybody has trouble with the national number heres the direct line for the Sacramento office (800)8242000 well at least thats the number they gave me. Users/ArmyDecoy

All of this is useful, but there is one last thing to consider before making the switch to Davis primary Broadband Provider from DSL or other subscriber services... Past and current litigation against them from their Satisfied Customers.

Pending Litigation Against Comcast 

  http://www.crainsdetroit.com/article/20100629/FREE/100629867/cityofdetroitsuescomcastoverallegedcontractviolations#  City of Detroit, Michigan
  http://en.wikipedia.org/wiki/Hart_v._Comcast Hart v. Comcast Class action Lawsuit in P2P violations and the followup http://20somethingfinance.com/comcastclassactionlawsuit/ settlement
  Comcast Attempts to Override current FCC regulations regarding the retransmission of broadcast signals http://www.freepress.net/files/Comcast_Program_Access_Litigation_Letter.pdf and http://www.commondreams.org/newswire/2010/02/196 Comcast has , as of October 9th, 2010, been lined up for http://news.yahoo.com/s/nm/20101009/media_nm/us_comcast_doj arbitration in the matter.
  Another big FCC lawsuit, which actually went to http://www.washingtonpost.com/wpdyn/content/article/2010/04/06/AR2010040600742.html Comcasts favor after initially losing in the lower courts.
  They purchased AT&Ts Broadband lines and then tried to screw them. In the end, it cost http://www.comcast.com/About/PressRelease/PressReleaseDetail.ashx?PRID152 Comcast $170 million.
  An entire listing of several lawsuits, past and present, regarding the lack of security on Comcasts very own web domains http://www.360reports.com/p/co/Comcast_Corporation_litigation.html

There are several other lawsuits which can very easily be found if you look. The bottom line is that Comcast does not care about the consumer, the FCC or any regulation regarding monopolies and is even trying to get the average consumer to bow down and accept an arbitration agreement that would cost the consumers the right to sue under any circumstances. On the bright side, there is way to opt out of this arbitration and retain your right to bring suit if necessary by filling out https://www.comcast.com/arbitrationoptout/default.ashx this form.


Comcast/Archive Archive Page for Comments from 20052009


20100204 00:09:20 nbsp Comcast is apparently changing its name to Xfinity.  Dont be fooled. Users/IDoNotExist

20100322 00:14:00 nbsp comcast is a really crappy service for a really ridiculous rate.  Users/randomstudent

20100427 17:30:52 nbsp COmcast HighSpeed Internet has been down all afternoon. A call to Comcast resulted in them saying that most of Downtown is out, because theyre doing scheduled maintenance. In the middle of a weekday. During Midterms. Great job! Users/JerseyCity

20100617 21:27:44 nbsp On June 17, 2010, I was watching the NBA Finals Game 7, Lakers vs Celtics. With about 5 minutes left in the 3rd quarter the screen went blank. Channels 112 were not working, meaning that it wasnt the network ABCs fault, but Comcasts. I listened to ESPN radio coverage of the game, but with about 8 minutes left in the game I couldnt stand to just LISTEN anymore and I ran off to the nearest bar to watch the game. At the bar, I wasted money on food and drink that I did not want in order to watch the game, and watched excitedly as the game went down to the wire. If I had waited for Comcast to fix its little problem then I would have missed probably one of the greatest NBA Finals series in years. I rest my case Users/boing3887

20100727 13:19:02 nbsp Words cannot describe how much I hate Comcast. When I first moved into an apartment in Davis, my roommate and I wanted to make sure we had internet as soon as possible. Because of this, we went to Davis weeks in advance to set up an appointment, get a modem, and have everything ready within a few days of moving in. We signed up with an online deal that got us a free modem and the first six months for $29.99 a month, but apparently they could not send a technician to flip the switch (or whatever they do to turn our service on) to connect us for a few weeks. When they finally did get our connection running, they gave us the full price deal which we spent months fighting. What is even worse is that the contractor who was supposed to disconnect the previous tenants decided to do so several weeks later after they moved out and we finally got our connection working so we needed to have a technician come activate our service again! I am posting this comment now because the roommate holding the Comcast account is moving out and I am going through quite a bit to figure out how to get the most convenient transition out of this (especially since they want to charge me a $45 installation fee for basically flipping a switch!). Users/hankim

20100727 13:32:09 nbsp Love their internet service, hate their serviceservice.  Also, they moved a number of HD channels from their old location in the 900s (the normal HD channels) into the late 700s/early 800s.  The 800s are porn channels.  So, if you want to flip through the Guide menu to find the regular HD channels youre looking for, you have to scan past a whole bunch of porno names.  As amusing as some of the names may be, the new organization is ridiculous and likely offensive to some. Users/TomGarberson
  I do not have their cable television service, but I think it helps people like me make up convenient excuses. Oh no honey, I was not looking for porn, I accidentally got to this channel while looking for the sports channel. Users/hankim

20100807 21:36:32 nbsp It takes forever to get anything fixed and you have to jump through a zillion hoops during the process.  I think it took 3 weeks to get the cable fixed when it died (they didnt understand what the problem was for several hours, and then they sent the wrong stuff to fix it).  The internet also has a habit of going very slowly from time to time, or cutting out (which is confirmed by calling them).  If there was a comparably priced option with another company I would take it; unfortunately we cant get DSL out here (we tried). Users/themichelle

20100824 10:02:18 nbsp Am on the 26 mbs plan currently (was formerly the 16 w/speed boost). Decided to upgrade recently but for craps and giggles decided to run a speed test this morning to see where my service was really at. The results:

http://www.speedtest.net/ Speedtest.net says 4.7 mbs, 13.1 mbs, 6.9 mbs
http://reviews.cnet.com/internetspeedtest/ Cnet speed test says 2.3 mbs, 4.7 mbs, 2.2 mbs
http://www.bandwidthplace.com/ Bandwidth Place says 16.6 mbs, 18.6 mbs, 17.8 mbs

I tested at 10 different sites, clearing my cache, updating and cleaning my reg, even ceasing all background programs which run on the internet in the background (ie: anything with an autoupdate feature, Skype, and anything else runnign on INet.) before running all of them, clearing the cache in between each one. The result varied on each site between 2.2 mbs (lowest) and 18.6 mbs (highest). My overall average download speed is 10.1 mbs which is a far cry from the 26 I am paying for. Yes, I live in an Apartment complex, yes it is cable and yes they tell you up front the speeds may vary, but getting less than half of what you are paying for?  Seems odd to me. Now I am wondering whether to upgrade or not. I am sure that even if it were half of the service I was paying for it will still be a 100% improvement. Just not sure if its worth the added fees anymore. I hate you Comcast. Users/WesP
 My understanding is that it varies dramatically based on time of day and usage of other people on the same node as you.  A handful of people torrenting in a small area can really bog things down for everyone else.  I was on the 18mbit downstream (it recently got upped), but fairly often got download rates of 22mbit+; other times, it would be as low as about 6mbit.  A friend who lives in South Davis and had the same plan would regularly get 15+ in the mornings, but on weekends and after about 5pm on weekdays, hed drop to virtually nothing.  Couldnt play games, stream video or anything else.  That was close to a year ago, and my impression is that theyve sorted the problem out so its at least functional at all times.  But it can get pretty nasty if people in your area are hard on their connections. Users/TomGarberson

20100831 16:08:17 nbsp I started a new account with them because the roommate who was in charge of the Comcast account was moving out and I like how they charged me ten bucks to literally press a button on a computer. Really?  Users/hankim
  could be worse, I was charged 20.00, and all I did was add cable to my internet. He literally dropped off the box and just said plug it in. We did plug it in, had to wait 3 hours before any channels appeared, had the internet die on us 6 times in less than 12 hours after he showed, and today there is still no guide information on the set. It is annoying.  Wes

20100904 10:27:20 nbsp Were thinking of switching our phone service to Comcast  can anyone comment on the reliability and quality (i.e., good clear sound) of the phone service? Users/CovertProfessor
  Its voice over IP.  They give you a device that combines your phone jack with your router (or maybe with your TV too if you have that from them).  The service does not go through your regular wall plugs, if I remember correctly.  I think I had my base station plugged into my combo router device.  So be careful to ask how many phones can be hooked up to it, and if they must be plugged in.  If you lose internet service, you lose phone service as well.  Comcast went down for me for under a day total out of a year (that Im aware of), although that day was spread out at multiple times.  You may note from my experiences above that my opinion of my experiences with comcast is not very high.  A trip to the dentist is generally much more pleasant.   Users/IDoNotExist
   Thanks, thats helpful.  We have Comcast internet now and I agree that its pretty reliable, though not perfect (loss of a day total spread over different times of the year sounds about right).  How was the sound quality?  I ask because sometimes Skype sucks for us.   Users/CovertProfessor
    I dont remember having any problems with it.  I really didnt use it very much though.  I made almost all of my calls on my cell, and just used the comcast voice service for the occasional long meeting that would have burned my cell minutes.  There were no latency issues or drops like you might get with Skype.  Comcast probably dedicates a certain amount of bandwidth to, or prioritizes, voice calls in order to guarantee that youll be able to make a call without disruptions.  (Really, its a tiny amount of data.)  By the way, if you happen to have an iPhone 4, or you get one of the new iPod Touchs were just announced, you can make voice and video calls for free at very high quality (MUCH higher than a cell phone) using Facetime.  But the other party has to have it too...   Users/IDoNotExist
     A really simple way to use the existing phone jacks, is just make sure the line from at&t is disconnected at the phone box outside, and plug the comcast phone jack into a wall jack. Then the other wall jacks will work, assuming they are all still connected to each other as one extension. It could be complicated though, if its not clear what is what in the phone box. If youre in an apartment this could be difficult too, but not impossible. Users/NickSchmalenberger
      Thanks to you both!  Very helpful. Users/CovertProfessor

20101103 19:44:49 nbsp Does anyone know of any time requirements for cancelling cable service (i.e., advance notice, billing cycle, etc.)?  We have been with them since before they were Comcast (12 years) and we are thinking of switching to DirectTV and would like to avoid paying for two services at the same time if we can avoid it... Thanks! Users/BigGuy

20101118 12:15:06 nbsp Heres something fun for yallhttp://vinhboy.com/blog/2010/03/25/howtogetfreecomcastinternet/ How to get free Comcast Internet. Users/PeterBoulay

20110104 00:07:14 nbsp Comcast failing again for the past two weeks in North West Davis :( Users/Col

20110204 11:48:27 nbsp anyone know how well comcast internet runs in N. Davis?  Users/max72

20110326 04:23:59 nbsp If I could McVeigh all of Comcast, I would. Users/JoshLawson

20110403 09:03:36 nbsp Whats up with Comcast these days? There TV network is getting worse, I was watching UConn Vs. Kentucky and in the last 2 minutes of the game the screen went blank for 10 seconds.
Luckily Im not a diehard college basketball fan, but still.. Users/NikhilDahal

20110403 12:18:28 nbsp Me and all my roommates are literally (yes, i know what literally means) SICK with comcast. I just want to play my Hockey Video Game when I get home from school!!! I dont want to know some failed way to fix the fact that between 4pm and 12am on weekdays, the internet is so slow that you cant play anything, you cant even have a conversation in an XBox live Party. Im not a computer person, I dont get why stuff cant just work... I just want to know what internet provider I can switch to that wont cost more than comcast (or at least will be close) Users/NoahDoss

20110613 01:40:19 nbsp So I checked in on my internet plan since I wanted to make sure I could end it when I am moving to another place without any fees or something and was told I basically had a fixed rate of $29.99 a month last month. This month I get a notification from my bank telling me that I got a charge of $59.95 from Comcast. So now I go back to ask what happened and am being told that I didnt have a fixed rate and my promotional rate expired. Assholes.  Users/hankim

20110621 07:41:44 nbsp And after a weekend of hell, thanks to Comcast stating they did not have a payment I made two months ago, I called them to set up a cancellation date telling them I was switching to AT&T (had already made the appointment). Miraculously, my payment showed up in their system this morning...  I hate you Comcast. Users/WesP

20110621 11:22:59 nbsp Ive found that threatening to cancel my account is the ONLY way to get the service I need or speak to someone who will help me efficiently and accurately. Last time I did this (Ive done it twice now) was because I had been quoted one price over the phone when I made the install appt. but then was billed for a higher amount later. I called 1800COMCAST to resolve. All they kept telling me was how sorry they were that I was unhappy but they couldnt do anything because they were actually a call center in the Phillapines. Finally after I got fed up and said I would cancel my service, I was magically transferred to a cool lady in Sacramento who took care of everything in in less than 10 minutes. Users/jsbmeb
  I was transferred to one of those people too. She said she would call me back but never did... foreveralone.jpg. Now I get a discounted price of $45 a month (after annoying some more people), if they actually arranged this properly, unlike the previous experiences Ive had with them not giving me the proper price for months on end.  Users/hankim

20110808 13:53:21 nbsp There was a ~45 minute outage today, apparently widespread in the area (according to Comcasts automated message). Users/CovertProfessor

20110819 10:55:33 nbsp Moving and asked them to disconnect on 8/20/2011. Idiots disconnected today. Hopefully getting reconnected will be smoother, although I doubt it from previous problems with them. Users/hankim

20110822 08:18:31 nbsp They keep charging me for a modem that I never got since I purchased my own years ago and I keep having to call them about it. Wish they could keep better track of their records. Users/hankim

20110904 14:09:07 nbsp Interesting factoid.  If you call and go to the change or upgrade your account thing in the menu, they will not discount your rates.  I made my usual periodic call to knock my TV/internet rates back down to a reasonable level, and the woman I reached outright said she couldnt give me a discounted rate, except for the slight decrease Id get if I added voice to my account ($144/month down to $136/month).  So I thanked her and said Id be making inquiries into switching over to DirectTV.  Thats when she told me that their loyalty department is closed on Sundays, but before I switch I should be sure to call back during the week and select downgrade at the menu, because they could probably offer me a better rate.

Moral of the story: they wont help you unless you tell them youre leaving.  Good to know!

As usual, if they wont knock my bill back below $100/month Ill be leaving Comcast.  Ill report in with what kind of results I get.  For those whore curious, by the way, DirectTV is currently offering a 210channel package including free HD and free NFL ticket for $35/mo for the first year, bumping up to $50/mo for the second year of a 2year contract.  MUCH cheaper than the 140 or so than my current 140 or so channels on Comcast that dont include NFL and cost about $75/mo. Users/TomGarberson

20110907 14:08:24 nbsp I love how their phone line puts you on hold for twenty minutes when they are closed and then they tell you to call back later. Seriously, they cannot have a message that tells you that they are closed? Been dealing with assholes reading off scripts for the past week and I still dont have the internets. If I ever go postal, its going to be in a Comcast building.  Users/hankim

20110914 08:16:02 nbsp Those fuckers now make you download some shit software that basically resets your browsers home page and search engine in order to activate their service. FUCK COMCAST. Users/hankim

20110926 20:30:34 nbsp Well UCD is back in full swing and once again Comcast has demonstrated to me they cant handle the load in terms of internet bandwidth you blow Comcast. If it didnt take 2 minutes to get to this page (cant even log into my email account)Id let you know by email already did by phone and you are aware of cable and internet issues in my area... gee thanks.  Users/RichardL

20110930 21:24:48 nbsp Yep.  At the beginning of every single UCD school year, Comcast users in Davis experience issues with their service.  They dont seem interested in anticipating the increased usage when 15K20K students, staff, and faculty come back after the summer and start using the internet.  I guess it makes a kind of sense.  Why should they spend any money on preparing for the issue ahead of time when they can just wait for the torrent of pissed off phone calls, and then invest the minimum amount of money and effort to make most of the complaints stop?    Users/Wajinki

20111003 14:34:06 nbsp Supposedly I have a bill or something that was due on the 29th of September, at least when I chatted with a representative who could see the updated bill, which I cant see online for some reason, supposedly because they havent updated my online account yet... what is this I dont even. Users/hankim

20111014 16:17:26 nbsp Does anyone know how to get a channel listing by network of Comcast stations? I have been searching for years. Users/EricWecker

20111230 13:29:46 nbsp Our internet service was unavailable for much of 29 December and through the morning of 30 December.  Was getting 33% packet loss in the evening, which became 60% and then completely out again through the evening until the morning of 31 December, when it was sporadically in and out.  Technical support was, as usual, unhelpful.  Yay, Comcast. Users/CovertProfessor
 Phone support can only do so much when the problems on your end.  You probably just need a new computer.  Good luck with it, I know once you get it straightened out youll love Comcast!
  I guess my whole neighborhood needs new computers then, too.  cp

20120204 16:39:25 nbsp @CovertProfessor I had similar issues in December as well. In fact, ever since midDecember Ive had strange problems where the quality of my connection changes erratically for a few hours then it cures itself for the rest of the day. Its quite frustrating.  Is anyone experiencing similar issues? Users/KrisKalish

20120210 18:54:38 nbsp Comcast is by far THE WORST company I have ever dealt with in terms of customer service and billing. Despite the fact that I signed up for the service with a reallive, physical salesman, Comcast charged me almost double what my first months bill should have been. Despite the fact that I had a signed contract (how often can you say that these days?), it took three phone calls and a trip to the Comcast office to get them to honor the rate I signed up for. Comcast cobbles your bill together from an assortment of temporary discounts, promotional rates, and credits, all of which expire at different times and without any notice. So once or twice a year my bill unexpectedly doubles, and I have to go through a fresh round of threatening to cancel, getting the bill fixed, and signing up for some new motley assortment of discounts. The latest fiasco was a $77 service charge they slapped me with after sending a technician out to reconnect a cable one of their other technicians had accidentally disconnected while working on someone elses hookup. Seriously... $77 for a 5 minute visit to screw a cable back in. It only took an hour to get things sorted out on the phone this time though. Thats my personal record!  Users/Johnmlambert


20120422 20:29:19 nbsp COmcast is the worst company to do ANY business with!! In fact my service has hiccups all the time!! They want to charge me $121.90!! Better Buisiness is going to get a report on them. Its very ridiculous when you supposedly get a good company, and all your service is shit!! I am going to report them to everyone I can!! BBB, Call Curtis, and as many other watch dog types I can!! This company is the biggest rip off you can ever blow any money on!! DO yourself a BIG favor and try to find a better company!  Users/frankinDavis

20120430 19:23:22 nbsp One year later, Comcast has sent a collection agency for $30 after me. My roomate and I had pixilated service for two straight months, and were getting BS answers mixed with discounts off our monthly charges. Once we had enough of about a week of nothing but pixilation, we switched to Directv. I have all emails on file, and yes, I am willing to go to court over $30. I swore their commercials claimed they are now putting customer service first, but I suppose nowadays trusting commercials is just foolish. No I do not work for Directv, but we had one day of it not working and we already have a next day appointment for them to fix it. Users/DCWine

20120602 23:44:25 nbsp COMCAST IS HORRIBLE!!!!! I had them for a year and I kid you not, literally EVERY SINGLE bill they would try to charge me at least $50 more than what I shouldve been paying for a variety of bullshit charges that theyd try to sneak on my bill. I spent a whole day each month just being passed around on the phone from person to person just to get the damn charges taken off. Avoid them at all costs!!!!  Users/SadieHutchison

20120711 16:59:12 nbsp I despise Comcast. My services started in January 2012, but Comcast forgot to ship my equipment and it didnt arrive until January 30th. They still wanted to charge me for the first month... every month since then has been hell. Service outages are the least of my problems. Comcast tries to slam ridiculous charges on me regularly and its a pain in the neck to call in, wait on hold, then get transferred around for eternity to get the charges removed. Sometimes I go through the entire process and realize nothing was taken care of, so I have to do it all over again! I spend hours dealing with Comcast every month. I cancelled service on the first of this month (which was a miserable process that took hours), and Ive never been happier. I vote with my dollar and I refuse to vote for Comcast in the future unless they make some serious changes. Users/JaneFitzsimmons

20120919 00:50:19 nbsp It has been my first year as a Davis Comcast subscriber. Speeds are decent (as expected from Comcast), much better than other internet options out there (I have a Docsis 3.0 Modemworks nicely and no rental fee). My first month was very strange. I signed up for their Blast internet and crappy digital TV (because it was cheaper than just the Blast Internet itselfI myself dont have a TV so this isnt really useful unless you want to create an Xfinity account to watch ESPN3 or something. Oh, and a digital cable box is not the same as a HD cable box) They sent out a tech to install/configure the internet (which I could have done at home with my cell phone, reading off the MAC Address) and cable box, but the tech ran out of cable boxes and told me they will send me one. The cable box arrives a week later, by then I got my first bill, which was very strange, around $115. $50 was installation, and $65 was for the internet and cable package (even though the advertised price was $39.99). I talked to my Comcast rep in Davis, who told me that I will pay for partial amount (just installation fee) and they send me a new, separate invoice for my first months service. Days go by, and I get calls on my cell from Comcast during class, threatening to cancel service if I did not pay. I called Comcast directly and they told me they will fix my bill. Another week goes by, and I get calls from debt collectors, urging me to pay. I finally get the new invoice in the mail and that bill still isnt right (about $60). I call Comcast a final third time and they told me my account shows $41.40, and they will contact the debt collectors to stop harassing and send out another invoice in the mail. Finally after a month and a half, I cleared my account and paid for installation and my first months bill. Since then the internet has been decent, and I have been paying a constant monthly fee; no problems for a year.

Note that after one year their rates change again, depending on what contract you signed. I had $39.99 per month for an entire year which is a special deal opposed to the 6 month deal. After one year the price increased to $54.99 per month, and after two years the price will be the standard normal monthly service fee of $79.99

Comcast isnt too bad, after you dispute their charges and call them numerous times. Then they back off.
 Users/JournaL

20130209 12:57:09 nbsp Returned my equipment a month ago. Today some service person called saying they were coming to an apartment I no longer live in to pick up a modem that I dont have and now I have to sort all this crap out. They really need to get their shit together. Corporate office was closed so I had to go through their regular customer service, but the person I talked to was pleasant enough. Users/hankim

20130729 19:11:35 nbsp I previously had AT&T and after moving to comcast, I felt that it was a whole lot faster. Thats the good thing.

I first got a good deal with comcast internet, $37.99 for 12 mgbps a month for a whole year. I had to move to a different apartment and comcast sent out a technician to turn on my new apartments connection or whatever you would call it. They charged me I think it was an additional $39.99, more than what I pay for a month for my service, but I couldnt do anything since there was no service in my new apartment for 90 days+. The technician then asked me if he could drill a hole in my wall, and since I did not know what he wanted to actually do, I allowed him. He FAILED to notify me of an additional charge of $21.99 for the socket he put in the wall. If he notified me about the charge, I would have said no and drilled the hole myself because it was a simple hole that was only 5 inches across to where he needed to put the line to my router. I called comcast and the representative I managed to talk to was able to remove the charge and mentioned that it will reflect in my bill soon, and I also received a letter in the mail telling me of the change in my bill.

I then paid my bill for sixty something dollars (my regular bill+the technician) the following month. That was about 3 weeks ago, and now I check my online statement to see when the next bill is due and I see the $21.99 charge+ a late charge! I am very upset at Comcast at the moment, and they are getting an earful from me once I get on the line with a representative.  Users/JaceWinter

20131025

Anyone thinking of getting Comcast dont do it if you want to preserve your sanity. Terrible service (for a while I could only use it on certain days for certain times because any other time it would lag beyond belief) and they have terrible customer service. I called to have someone come in and check the wiring on Thursday then they rescheduled it for Friday for some unknown reason and now they want to reschedule for Monday because I didnt call to confirm the appointment that I had made that same day. This isnt the first time they do this to me. When I was trying to get my service installed they literally had me waiting for an hour before someone answered the call. Then I had to give my information and as they were transferring me the call dropped on their end. So I called again, gave my information, being transferred then the call dropped yet again. I called yet again wait for another long time before someone else picket up, gave my information and was finally patched through to someone who would help me. They advertise these really great speeds but they dont back it up with the service. To make it worse, customer service is beyond useless in helping out since they will always, always blame it on your computer rather than on themselves. Its never their fault, its always yours in their view point. Definitely, not worth the time or money. Its better to not have internet than to put up with such inadequacy.

Had this service for a month and a half now and never before had I had so much problem getting my internet to work. Maybe if I use an ethernet cable all the time it wont lag. A deeply unsatisfied customer

20131216 13:58:56 nbsp We reluctantly switched to Comcast a couple of months ago when we moved because AT&T does not offer true highspeed service in our area (L Street and east). To be fair to Comcast, we have screamingly fast speed with them and I appreciate that. But what a scammy company Comcast is. You definitely need to watch for charges every step of the way. We couldnt get the really good rates they advertise online because if you order online you cant arrange to pick up the equipment here in town, meaning you have to wait several weeks for it to be sent or for a rep to come out. Since you cant place your order until the previous tenants release their contract with Comcast, you may only have a day before movein, so youre stuck buying the service on the phone at higher rates.

Also, we had terrible internet speeds at first, and when I called they offered to send out a tech. He was very efficient, and by replacing the route we rent from Comcast and a couple of the cables from it (not in the wall), he solved the problem. And then I got a $30.50 service visit charge. Comcast never told me there would be a charge, and I dont see why there should ever be a charge for them to replace their own equipment (especially in the first 30 days). With the help of a reluctant billing supervisor, I got that reversed. Just beware! Users/EvaG

20140711 03:59:03 nbsp Remember This One, I just came here to say that there service was a big CRAP & so much expensive. Users/GeorgeAAlvarez
