
Majoring in Community and Regional Development (CRD) will earn you a Bachelors of Science degree, like all majors in the College of Agricultural and Environmental Sciences College of Ag. Students can emphasize their studies in one of five areas of concentration: community groups, policy and planning, social services, organization and management, and economic development. There is also a twoyear Community Development Graduate Group graduate program that leads to a Master of Science degree.  To Minor in CRD, you only need CRD 1 plus five upper div CRD courses. Easy and you get flexibility. Within the list of acceptable courses (on their website), there are no required courses other than CRD1 for non majors.

Now all CRD major students must take Two CRD Research methods courses. You must take CRD 151 and atleast one other course. The courses that can fufill this requirement in 2011 are http://hcd.ucdavis.edu/crd/docscrd/crdmethsoverview_oct%2028.pdf. Please see an advisor to confirm that a particular course will fufill the requirement.

In many CRD courses but not all, a final is not given. Several CRD upper division courses instead require a group project or a long final paper, a plus for those who do well on written work.

 Courses 
1. The Community  This course is quite popular because it is a tripledipper lowerdivision GE class meaning it satisfies three general education requirements: Social Science, Diversity, and Writing. It is is a very straightforward class, although half the quarter is spent solely on defining community. Many students feel that the course also has an insane amount of reading in it, but the professor (Bernadette Tarallo) is a very nice woman who is very friendly. The class is favorable to giving answers and opinions in class. You will have to write a 5 page essay on a community (usually that you are a part of or are familiar with). CRD1 is offered every qaurter.
As of now, the rules for triple dippers and other GE courses have changed for new UC Davis students begining study in Fall 2011. Please consult the course catalogue. The old rules still apply if you entered before Fall 2011.

2. Ethnicity and American Communities  A less popular class, but those who take it usually give good reviews. It is unfortunately only offered in Fall Quarter. The main paper is to write a long essay on a community in which you are not a member of. This class builds on CRD 1, but a much greater focus is given to diversity, ethnicity and gender than then previous class.

CRD 20: Food Systems 20. Food Systems  A course for students interested in where their food comes from and its environmental and social impacts.  Involves lab time where students do fieldwork to answer research questions they create about the food system. Taught by Professor Users/RyanGalt.

157. Politics of Community Development  This course is really interesting becuase you learn a lot about community organizing and that naturally, every decision the policymakers pursue has an effect on the local community. If anyone is interested in social sciences (Pol, IR, PreLaw) this is a really good class to take. It  mixes basic concepts from course 1 and then combines aspects of Sociology, CRD, Pol, etc. A fun course if you are minoring in CRD from a social science major and/or you need upper division units. This course is not currently scheduled in the 201112 year.

162  This course covers the history of work and the rise of technology, influencing professions and the relationships within the workplace. You will read a lot of material and studies (theory, becuase this is UC Davis) behind the institution of work. There is a new professor teaching it this year so course content will be different.

CRD 151 Field Research
A Spring Qaurter only course taught by Tarallo. This course is REQUIRED for CRD majors. The class teaches students how to conduct field research by splitting the class up into mini groups. You meet with the TA and with Tarallo a few times to show progress. The course is really great becuase you, the students get to choose what to study and ask if it is being used efficiantly. It dosnt have to be in Davis. Past topics have included Unitrans, Nutrition in public schools, Sustainable school lunch programs, Awareness on Womens health, the Dinning Commons, the Oakland As 2007 proposed move to Fremont, etc. You really become friends with people in your group and it teaches you interview skills. You also learn to split up group projects equally. The group gets to annonmously report selfgiven assessment grades for the people on your team at the end of the qaurter. Finally, you learn a lot of cool research findings from your classmates before giving one yourself. A fun class (though lectures themselves are somewhat boring). Tarallo is a really kind professor and she loves meeting up with you for ideas.
