These are archived comments about DaVinci High School.



The Principal of this school spends an inordinate amount of time at her desk monitoring the email traffic of the students in the school. The students are provided with a laptop computer with email and internet access. My suggestion to students, is to use the computer for school work only, send email messages that only discuss school work, dont chat with fellow students unless you keep in mind that she is also receiving each and every email.  In fact, use your own computer and leave the laptop at school. Bring your work to school on a flash drive and dont send email at school at all. See the ACLUs website on students rights at http://www.aclunc.org/students/guide/introduction.html I encourage every student to read the information provided.  Users/SharlaDaly

What proof do you have that the principal is spending inordinate amounts of time checking email? You are not a student, and your certainly not staff.
Curious Student


  Id like to highlight a passage in the ACLU guide mentioned by Sharla, above: Contrary to what you may think, youth actually have a lot of rights under state and federal laws. For instance, according to the United States Supreme Courts ruling in 1969, It can hardly be argued that either students or teachers shed their constitutional right to freedom of speech or expression at the schoolhouse gate. And youth have a lot of other rights besides the First Amendment provision of free speech and expression.  Users/ZacharyNorwood ZN
   Students may also want to check out some http://www.space.net.au/~thomas/quickbrowse.html webbased proxies.  If you use one of those, all they will be able to see is that you are connected to the proxy.  If you are using the schools provided email then they will always be able to monitor that.
  Oh yeah, thats a great idea, especially since webbased proxies are a blatant violation of the student Network Acceptable Use Agreement, and students can have their network privileges (critical for basic academic functioning at a school like Da Vinci) drastically curtailed.

20051103 19:35:31 nbsp I would really like to know what the Principals explaination of this is. Was this disclosed to the students prior to their enrollment? Perhaps the school board candidates should be asked what their take on this is?

I did a little bit of research: the district http://www.djusd.k12.ca.us/DaVinciHighSchool/resources/registration/District%20AUP%20.pdf Acceptable Use Policy:

{{{G. Privacy

a. You should expect no privacy in the contents of your personal files
on the district Internet/network system and records of your online
activity. All student use of the Internet will be supervised and
monitored. The districts monitoring of Internet usage can reveal all
activities you engage in using the district Internet system.  The district
specifically asserts ownership of all information on its system.}}}


It then looks like even flash drives arent safe and that proxies could give a false sense of security. These students agreed to leave any protections that they might have had behind when they signed up. Futher if students at other schools in the district signed the same AUP they are just as vulnerable.  Users/JasonAller

 This is a public school and the students likely cant refuse the agreement if they wish to continue attending?  Monitoring High School computer usage is pretty common.  The issue may be whether the monitoring continues taking place when the students are no longer in their classes.  Because the students keep their laptops while attending, the students may have developed a reasonable expectation of privacy and ownership.

   I think the district has protected itself quite well with the AUP against a reasonable expectation. I think that they are wrong and are setting a bad example, but it appears that they have crossed the ts and dotted the is. Check out the last page of the http://www.djusd.k12.ca.us/DaVinciHighSchool/resources/registration/District%20AUP%20.pdf Acceptable Use Policy; I wonder how they would handle a student who didnt agree to either of the two sections at the end? How do you have a student on a technology campus who wont use your computer or your network? Also take the time to compare the district AUP to the campus http://manuals.ucdavis.edu/ppm/310/31016a.htm AUP.

     The policy is in place, no doubt, to reassure parents that their children wont be accessing inappropriate material or using their computers for noneducational purposes while in school.

       Its more to protect the district. If one parent found a student doing something innapropriate on a schoolowned computer, the school could get in a lot of trouble, and the principal would be blamed. Theyre protecting themselves and their property. If I were to send one of my students home with one of my computers I would definitely want to know what they were doing. If the student doesnt agree, they can go to Davis High School  Users/MiriamKaufman


20051103 21:23:43 nbsp As US citizens, we have a fundamental right to privacy. Period. No amount of monitoring will obviate the origin of a students desire to do something deemed inappropriate. Its up to the parents and teachers, ultimately, to instill a sense of propriety and a desire to spend computer time productively. No one should agree to a legal abrogation of his or her fundamental rights. Users/ZacharyNorwood ZN
  That is a very idealistic, and unfortunately unrealistic, goal for high school students.  Users/MiriamKaufman
   As I see it, our fundamental rights are not merely ideals. Those who think they are may unwittinglyor wittingly!promote social inequality. I think rights such as privacy correspond to concrete realities, such as freedom of thought and action. To help frame the right to privacy in understandable terms, consider this question: if students are abusing their privileges, whats the root cause? If the cause is external to the school system, such as a culture or home environment that discourages discipline, then no amount of administrative snooping can fix the problem. In this case, other solutions would be much more effective than abusing someones right to privacy, e.g., educating the teachers and parents about how important schooling is, how ones education translates into their ability to achieve, and so forth. An intrinsic desire to learn must be fostered; a proactive, not a reactive, solution must be sought. Users/ZacharyNorwood ZN
     High school students dont have the same rights to privacy the rest of us do. While I agree with you in some ways that they should, the district cannot count on parents and teachers to motivate kids to want to learn, as sad as that sounds. Most parents have many more things to worry about than what their kids do in school. So, administrative snooping is so the schools can protect themselves from lawsuits, destruction of property, etc. They cant trust every single student not to abuse their priveledges at school. Im not saying I agree, thats just the way it is. And its going to be a long long time until every single parent and teacher can motivate their kids to want to learn. But hey, youre right, that is the goal. Users/MiriamKaufman
      Hypothetically speaking, if I had a child enrolled at Da Vinci High (assuming there was snooping and a rights waver), I would first threaten, by way of formal letter, then, if necessary, take legal action to assure his or her right to privacy remained unthreatened by the administration; from my vantage, therefore, the present privacy policy at Da Vinci High is just as likely to produce lawsuits as it is to prevent them. It cannot be argued that our constitutional rights are nonexistent until we matriculate at the university level. If the administration is afraid of lawsuits of a different naturesuch as legal action taken as a consequence of a child violating pornography lawsthen would it not be equally as effective to have a policy that states clearly that the school is not responsible for the possible abuse of computer privileges? This seems to be the view adopted by UC campuses, and it is apparently working for them. Whats more, the present policy at Da Vinci High seems arbitrary and Orwellian; arbitrary because other legal, protective measures could be adopted, such as using a policy similar to UC Davis, and Orwellian in the sense that the administration is actively and willfully spying on the students soley by motive of their own selfpreservation. In my mind, there is no rationalization for this behavior. Users/ZacharyNorwood ZN
        Youre letter would get nowhere because, let me say it again, students (high school, not college) do not have the same rights to privacy as adults. Step foot on a high school campus and your privacy rights are gone. I will look it up and show you if you dont believe me (but, honestly, I dont want to make the effort right now, hopefully you will believe me). Im not saying I agree with the district, Im just telling you why they do the things they do. Schools do not take the stance that they are not responsible for students actions because what would that say about them if some instance of abuse came up? Parents would be angry! The school might lose their funding  remember this is an experiential school. They are taking maximum preemptive measures to avoid problems. And I would really question how much the principal monitors, theyve got enough on their plate than to sit perusing through student emails for hours. Users/MiriamKaufman
         I appreciate your position, which is quite understandable given the circumstances and forces against progress, but I cannot respect your conscious conformity simply on account of the way things are. Certainly, there are more complex issues preceding the behavior and tendencies of children than previously imagined. Im deeply aware of this. Not only am I aware of the mindnumbing complexity of adolescent development from experience, I also study, regularly, the precursors of human behavior, both at the social and neuralcognitive/developmental level. Parents and peers, the political and economic zeitgeist, genetic predispositions, etc.all of these factors must weigh in. And indeed, given the lack of experience, perspective, and knowledge of adolescents, some of their rights may be attenuated or forestalled until they gain sufficient psychological development to be selfreliant. Nevertheless, theres a major difference, both in degree and kind, between barring, for example, the right to drink alcohol, carry a weapon, and so forth, on the one hand, and implementing surveillance systems designed to punish students for viewing a dirty picture or sending private, nonacademic emails, on the other. The real crux of the issue, therefore, is not the fact that rights may be rationally checked, for justified reasons, but rather the question as to the legitimacy of particular policies that overstep the bounds of rational justification and, in so doing, the bounds of our fundamental rights. This is why my contention remains. It seems obvious to me that the complexity surrounding the issue is precisely what casts doubt on this administrations oversimplified, Orwellian approach to solving the problemand we have not even agreed that there is a real problem. By any objective standard, this administrations solution creates a greater problem than it purports to solve. When you take away or temporarily attenuate ones freedom, the net result should be an increase in freedom for the greater number (while avoiding, of course, the tyranny of the majority). This, I believe, is not happening with this particular policy at Da Vinci High. In terms of seeking a real solution, I believe we have the collective power, if not legally then discursively, to fight bureaucracy, especially in such a small county where public opinion is so strong. As for myself, you can be certain that my hypothetical legal actionthough I doubt such a minor case as this requires such action, since sustained, public engagement should be sufficientwould, if public engagement gained no ground, spark enough controversy to shed light on the issues; and if in the end my case failed, I would see the attempt itself as setting a precedent for future cases. Such is the nature of morally motivated civil action, and such is the love of ones children and the rights of all children. Users/ZacharyNorwood ZN

Do we have a right to privacy as U.S. citizens? The 4th Ammendment grants that citizens may be secure from searches and seizures, but that could be constrained to not include privacy especially if said citizen had no knowledge of being spied upon. Did you mean some other law? Unless theres a law granting a right, we aint got it. Users/SteveDavison
  The Amendments in the Bill of Rights recognize some of the inalienable rights, they dont grant them. Users/JasonAller
  In the http://www.house.gov/Constitution/Constitution.html preamble to the constitution, it states that one of its fundamental aims is to secure the blessings of liberty to ourselves and our posterity; in http://www.archives.gov/nationalarchivesexperience/charters/bill_of_rights_transcript.html amendment IV to the Bill of Rights, it states that The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated. And so I ask, what is liberty if not freedom to privacy, in thought and action? and what is the right to be secure in papers and effects, if not a right to privacy of thought and action? On the contrary, we got it, and saying the amendments to the constitution simply recognize our rights but do not grant them is like saying you have the right to avoid murder but, ultimately, if you are murdered, there may or may not be an investigation. This stance, which is rhetorical in nature, is absurd. Its grasping at infallible beliefs of a kind invulnerable to refutation. Users/ZacharyNorwood ZN

20051103 21:28:19 nbsp It really isnt as bad as it made out to be here, just dont be an idiot and sell drugs over the school provided Email system. If you are really intersted in sending private Emails and browsing privately, then there are ways around, like proxies, which do in fact keep your usage hidden, but are usually unavailable do to overusage. remember: DHS students dont usually get to Email at all in english, History, and Math classes, so it should be considered a privalage, anyway the computers were given for academic purposes, so you shouldnt expect for them to accomidate for other activities Users/DanielGonzales


20051103 21:39:43 nbsp Should most of this discussion be moved to Acceptable Use Policies? Maybe leaving Sharlas comment and a pointer to the new location? Users/JasonAller

20051103 21:46:35 nbsp A proxy accessed from a computer that has a wiki:WikiPedia:Screen_scraping screen scraper or other monitoring program is not private. Users/JasonAller

20051103 22:08:29 nbsp as far as screen scraping goes, i dont think theres any of that going on.  (this probably doesnt belong here, but whatever)  All of the laptops have a program called Security Agent Dashboard from lightspeed systems installed.  Does anyone know what it does/can do?  It doesnt seem to do anything, but due to apathy and lasiness and the fact that i dont really do anything on this computer, (besides the wiki of course) i havent looked into it much. Users/AlexNorris
  It could be that they are running a product from http://lightspeedsystems.com/. Users/JasonAller

20051103 22:35:49 nbsp Schools are prisons.  The Sex Pistols knew that a long time ago.  Youre not supposed to have any right to privacy at a primary or secondary school  you forfeited that right the first day you attended Kindergarten.  Your personal belongings and your locker can be searched at any time without a warrant and without probable cause.  And we wonder why students go wiki:WikiPedia:Columbine_High_School_massacre Columbining their schools.  Welcome to America, everyone, where the Bill of Rights only applies if you help your local congressmen get elected. Users/BrentLaabs
  Compare the privacy bylaws of UCD to Da Vinci hightheyre quite different. I empathize with your sentiment, but I nevertheless contend that schools, if they do what theyre supposed to do, educate, are not prisons, but sources of lifelong freedom: mental freedom, first, and material freedom, second. This is what schools should be, and youre right, oftentimesmaybe even most of the timetheyre simply institutions designed to perpetuate class stratification. Theyre designed to bring ones skills up just enough to reinforce the economy. But we should never give up on education and the institutions that are designed to educate. We must fight for our right to true education. Users/ZacharyNorwood ZN
  Whoa Brent, Columbine was NOT about lack of privacy at public schools. Users/MichelleAccurso

20051103 23:37:02 nbsp About email reading, is encryption banned? What forms? I didnt see anything about encryption in the AUP. It could be fun to do pencil and paper cyphers. Users/NickSchmalenberger

20051104 07:17:37 nbsp One person who goes there explained it to me. He said each student is loaned a laptop for the school year. They are periodically audited, so the student may not add their own software, etc. For your own stuff, youll want your own computer. Below University level, schools are highly computerphobic. Users/SteveDavison

20051104 07:30:38 nbsp While software, etc. on the computer is periodically audited, email traffic is monitored on a daily basis.  The Principal will interrupt email conversations between students, discipline based on content in the emails.  The students should limit their email content to logistics for school projects only. No chatting.  Users/SharlaDaly

20051104 07:40:22 nbsp Can someone with one of the provided laptops post a list of the approved software? Users/JasonAller

20051104 16:05:00 nbsp My understanding is that by technologybased they mean they use technology (laptops, Internet), it doesnt mean that they study technology itself. Their website confirms this. This may not be the place for the budding geek. Users/SteveDavison

20051105 09:22:58 nbsp Well, just because they dont teach technology, does NOT mean that you cant learn it yourself :)  As i have been doing since last year.  One of the major benefits of having a laptop is being able to easily study whatever you want at any time. Users/AlexNorris

20051106 20:19:40 nbsp As far as approved software, we are really only allowed to install dialup software, and nothing else.  Last year they said I could Install blender 3d rendering program, and winamp, but this year they told us to not even download applications.  The computers did come with the Adobe Creative Suite and six Macromedia Programs to keep us busy. Users/DanielGonzales

20051109 20:40:07 nbsp I think the coolest thing about DaVinci is that, even though I dont attend any classes there, nor am part of the school, the teachers say hi to me when Im on campus, and acknowldege my existance, unlike some of the teachers who I see every day at DHS. Users/JohnDudek

20051114 14:28:24 nbsp Dont talk shit about ms. Mari.  Shes awesome and she has an amamzingly hard job. She has a few thousand people who don think that she can run this school, and on top of that, she is the principal of a school that has a bunch of irresponsible teenagers that run around with two thousand dollar laptops.  Of course shes gonna read emails.  She ahs to make sure that district property isnt being used for things that the district doesnt condone.  And she doesnt read emails, only emails that have been flagged by the filters are read.  These are filters that look at what is beign said in the email, and if specific words are said, then the email is flagged.   Users/JulienBiewerElstob

BRI can understand your loyalty, but if you read the schools policy, youll see that your posting here would violate the schools computer use policy. Isnt it even more disturbing that there are filters scanning each and every email that you send?

  Square one seems to be a good place for you to start, so I recommend reading Orwells great dystopian satire, NineteenEightyFour. Users/ZacharyNorwood ZN
   Under the old chestnut tree. Human rights are just another political tool, so dont be selfrighteous about them. This isnt the type of problem that should be solved through normal political mechanisms like complaining and invoking rights. The way to solve this is to just quietly work around it. As far as I have heard, there is still nothing in the AUP against students at Da Vinci from using pencil and paper ciphers (as distinct from codes, which are arbitrary word associations) because that way there wouldnt need to be any software installed on the district computer. If students at Da Vinci want more information on the use of ciphers, I remember there are several books in the DSHS library that would explain how to do this. Can you get reliable wireless access from outside to get around the district http filter? Are the laptops able to log on to other wireless networks? I think it is really important that you work only with the resources already available to you on the laptops instead of exploiting to get higher privileges because this way the district maybe cant get you. If they are really mad they can get you for whatever they want, so just dont make them really mad and you can probably get away with them not reading your email. P.S. The type of problem that __should__ be solved with political action is the districts Microsoft Windows homogeny. Maybe this could be an issue during the next school board election? Users/NickSchmalenberger
    Human rights as political tools? At times, certainly; but in this instance? I think not. Based on your response, I suspect that youve been indoctrinated by cultural relativists and pluralists into believing theres no physical basis for ethics, and so all arguments against supposed abuses of humanity or socalled rights are founded on misconstruction. If you were to read Nussbaums Upheavals of Thought, Cosmides and Toobys Adapted Mind, or E. O. Wilsons essays on ethics, to name a few relevant works, I doubt youd maintain such a social constructionist outlook. The old, blank slate model of humanity is finally in the grave, thanks to progress in the neurosciences, yet its still massively popular as a folk psychological explanation of cultural complexity. As with all outmoded paradigms, however, some time must pass before they fade away into that timebound category of metaphysics. Unfortunately, however, all obsolete paradigms have a social halflife, so to speak: they continue to reside in the minds of the previous generation of academicians, who in turn spread their selfreinforcing mental viruses to credulous students. While I admire your recommendation, or the use of software ciphers, I maintain that such solutions are merely reactionary and provisional, and should be used only until they are no longer necessarythat is, until a proactive solution is reached. And regarding Microsoft hegemony, I agree; but this problem is, at present, minor in comparison to snooping emails for comparatively insignificant reasons, which is a complete waste of time and money when you consider the comparative significance of other schoolrelated problems. Until M$ starts taking our right to privacy away at the software level, as they plan for future releases, we should not turn a blind eye to immediate abuses of mental and material freedom. Users/ZacharyNorwood ZN

Compare DaVincis policy with UCDs policy in the recent http://www.californiaaggie.com/media/paper981/news/2006/01/30/CityNews/University.Stands.On.Respecting.Privacy.Rights1536259.shtml?norewrite&sourcedomainwww.californiaaggie.com  article in the Aggie. Heres a sample quote: What the university has done is set a clear policy to respect the privacy of all of its members with respect to their electronic communications, Donald Dudley said. Its making a blanket policy that were not going to routinely monitor, inspect or access student electronic information. Users/SharlaDaly

20060328 20:16:43 nbsp As a former Da Vinci student (I am a Senior at DHS now) I want to say that after experiencing what I did at Da Vinci, I think it is completely the rightdoing of the staff to flag whatever they need to.  When I first began last year, there were absolutely no precautions on the machine really...we had the freedom to install anything we wanted.  I even hacked it so that I could still access the internet and my computer would not be detected.  I did this so I could install music players, have lots of random applications, etc, but I still was distracted by these things dramatically in class.  The distractions that the computer cause for us (the students) cause us to have a much smaller curriculum than DHS students.  All in all, I believe that Da Vinci can be the most fun and beneficial thing for the people who take it seriously; however students who joined just for the laptop and expecting to do less work definately did not find their way. Users/JoeyBennett

20071107 14:11:43 nbsp There are legal reasons the school has to restrict the use of the computers. And besides, their purpose is for classroom use, not personal use. If you need some outside software installed for legitimate classroom purposes, you can ask and often it will be allowed.
Ive read articles about other schools in other parts of the country using laptops in class and how disruptive theyve become, because the kids are allowed to do anything they want with them, so they waste class time playing games, chatting, etc. DaVinci is strict about the computer use because they are using the computers for learning, not playing. Students sign the acceptable use policy so they understand the restrictions.
I am not a student there, but the parent of a recent grad. My student had very few, and very minor, issues with the restrictions. Users/NotSure
