This editor can edit this entry and tell us a bit about themselves by clicking the Edit icon.


20100711 13:44:30 nbsp Youve made http://daviswiki.org/Peak_Performance?actiondiff&version2114&version1113 criminal accusations. The appropriate venue for these is to go to the Police and report the crime. Considering that you didnt bother to establish any identity prior to making accusations that serious against another member of the Davis community I dont see why your words should stay on the Peak Performance page. Users/JasonAller

20100712 14:28:28 nbsp Jason is not a moderator.  He is a member of the Wiki Community community, just like you.  The wiki is run by and for the people of Davis.  Which is why it is really freaking odd why youre using the name contour66 rather than Dawn, or Jim or Sue.  Everybody here is equal, and youre part of the effort, with the exact same rights to content and responsibility to maintain the wiki that Jason has.  Anybody can edit, delete or otherwise change all content on the wiki.  We work together, which is why a mysterious person who refuses to identify themselves gets some odd looks.  Imagine walking into a park, joining a community effort to plant flowers, and refusing to give your name.  Or a town hall meeting, church, or even a bunch of people who get together for sushi.  Thats the community of Davis, and thats the kind of community here on the wiki.  Users/JabberWokky Evan JabberWokky Edwards

20100712 16:44:26 nbsp Hey, Ill have a beer with you. Do you want to meet at Sudwerks at 7 pm today? Any other time this week is good for me too. Users/NickSchmalenberger

20100712 17:11:49 nbsp I saw your comment on JWs page, Look, I am not trying to rile up anything, but erasing comments that only to educate your utopia of a Davis Community is clearly ironic if not hypocritical.  I just wanted to say, first of all, that I support your comment on the Peak Performance page.  I restored it once, after it was deleted, then someone else edited it.  My point is that there are a lot of editors here, we dont always agree, but most of us try to work together as collaboratively as we can even so.  So, there will be those who support your leaving the comment you did (like me) and those who dont.  We generally try to talk these things out.  It seems to me youve given good reasons (including good reasons for anonymity) and your comments are corroborated by previous commenters on the page.  Second of all is to understand why some of the editors have reacted negatively to your comment.  Sometimes we get people who come to the wiki, leave libelous or offensive comments anonymously, and are never seen again.  Some editors have had to deal with that time and time again, and they get understandably frustrated and may at times overreact.  Sometimes, its hard to tell the legitimate complaints from people who just have an axe to grind.  So, some editors are a little sensitive when it comes to comments like yours, seeing them as the bad sort of comment rather than the legitimate complaints you (in my opinion) seem to have.  But overall were a good, wellmeaning bunch.  I dont think anyone is trying to make Davis out to be a utopia that it isnt, only to try to protect people and businesses from accusations that arent legitimate. Users/CovertProfessor

20100712 18:10:37 nbsp Hey, I dont mean to be analretentive (is that hyphenated or not?), but you asked a bunch of questions, so Im breaking them all down to answer:

Why is it odd? Because I choose not give my name for specific reasons?  Yep.  Thats odd.

Apparently neither of you understand how businesses run, as I can see by the vast amount of wasted time and effort placed on creating your wiki page.  I cant speak for Jason, but my entry built up over the last five years Ive been using the wiki.  The http://daviswiki.org/Users/JabberWokky?actionrecall&version1 first version back in 2004 was pretty simple.  A little here, a little there (and some of it was written by other people, wiki style)... it all slowly adds up.  Ive actually been a business owner for about 13 years now.

What if my name was contour66? You know there are many people in this community that dont have such generic and boring names as the one you mentioned.  I must say, as somebody who goes by the name JabberWokky, thats the first time anybody has accused me of demanding boring names.  :)  Is contour66 the name you go by?  Having spent time with people in the SCA, theater folk, goths, bikers, Rocky Horror fans and just plain weird folk, I tend to know quite a few people who go by odd names.  Generally numbers arent appended, so I took it as a computer name rather than one your drinking buddies call you.  My apologies if I am wrong... but you have to be used to questions by now if you introduce yourself as contour66.

Look, I am not trying to rile up anything, but erasing comments that only to educate your utopia of a Davis Community is clearly ironic if not hypocritical.  I didnt erase any comment.  In fact, I havent even looked up what comment youre talking about.  The only thing I noticed was that you referred to Jason as a moderator, so I headed over to point out to you that he isnt (or rather, you both are  everybodys a moderator, with equal content rights).  When I did so, I noticed his comment about identity and simply expanded upon it.  End of story.  I didnt mean to imply anything about some comment you made (where?).

If you are so afraid of me falsifying who I am then, why dont you invite me to have a beer and I can tell you in person why you and your partner in crime are in the wrong?   Alas, my wifes career has taken me out of Davis, and itll be a while before I get back (its on that really long editor entry you commented about).  Ill rain check you on the beer: Ill be more than happy to take you up on it next time I get back.  My wifes family is in the area, and a visit is overdue.  My phone number and email (and address, although Im moving) are on my editor entry... Im more than happy to chat as best I can.  But I think you missed the point: theres no issue of falsifying, its simply the social issue of using an obviously fake name.  That social issue exists regardless of if I point it out or not.  Youre using a fake name in a community that mostly uses real names, which carries a stigma.  Since you might not have been aware, I simply pointed it out.

No big shakes; you walked into a community and people are now talking to you.  Since everybody has complete rights to edit anything, theres a lot of talking to work things out when people disagree about an edit.  Its pretty much a sign youre being welcomed into the community here.  If you want, Ill even state it explicitly: Welcome to the Wiki! Users/JabberWokky Evan JabberWokky Edwards, (814) 8898845

20100713 07:31:33 nbsp Hey Contour, Welcome to the Wiki.  The issue of anonymous people making accusations against businesses is a contentious one here just because its come up a number of times.  I dont want to restart the argument over it, but if youre curious, theres a lot of discussion at {{{Strelitzia Flower Co/Talk}}} and Barefoot Yoga Studio/Talk.  Its nothing personal toward you; you just stepped into the middle of an longtime, ongoing argument.

And if you want to grab a beer and/or talk about it, give me a ring. 5593555814 Users/TomGarberson

20100714 12:28:13 nbsp Just FYI Utopia was actually a dictatorship of sorts.  Nearly no choice was given to the populace.  Food for thought, since youre saying Utopia as if its a good thing.  Users/MasonMurray
