



Cranbrook Apartments, managed by Tandem Properties, offers one and twobedroom units.  Despite its location near the train tracks, busy J Street, and Covell Boulevard (across from the old Hunt Wesson Plant), many resident DavisWiki commenters think that it is a pretty quiet place to live. The security deposits are $300 for the one bedroom and $400 for the two bedroom.  Residents seem to like the hot water, fast and free internet, WiFi in the clubhouse, new machines in the fitness room, landscaping, spacious closets, and the responsive management and maintenance team.  Apparently the management is really good about fixing problems within about an hour of hearing about them.

If you like living in the mix then Cranbrook Apartments was made for you! Cranbrook is located (conveniently!) along Covell Blvd. within walking distance of Nugget, Subway, Hair Salon, Travis Credit Union, and more! With quick bike routes, you will be to the UC Davis campus, downtown Davis, restaurants, and shopping galore in no time. Come in today and take advantage of the awesome pool, Free DSL, the 24hour fitness room, the fantastic new espresso machine, freshly baked cookies, great rates on one and two bedroom floor plans, and of course, fabulous management that is out of this world!!

 Management Notices 

Looking for Fall 2014? Call today to schedule your model apartment tour! Click http://www.tandemproperties.com/ here to view Tandems availability (updated twice daily) for fall 2014.


Floor Plans



(updated 1/21/2014)

Apartment Amenities
All Major Appliances
Spacious Closets
Full Length Mirrors
Ceiling Fans
Air Conditioning and Heating
Ample Storage
Free, Highspeed DSL in each Apartment (just ask us how!)
Beautiful Floor Plans
Bath Tubs

Cranbrook’s Special Features
24hour Pool & Spa
24hour Fitness Center
2 24hour Laundry Facilities
24hour Study Lounge with WiFi
BBQ & Picnic Areas
1.5 miles from UCD Campus
On Unitrans Bus Route ‘E’ and P/Q
Hot/Cold water, Garbage, and Sewage fees paid
Cats Allowed!
Coffee and teas in the Lounge
Freshly Baked Cookies & Other Treats
Free Ample Parking


Pictures






Mobility
Location  .4 miles from Oak Tree Plaza, home to stores and shops like Nugget Market, Carls Jr., CVS Pharmacy, Travis Credit Union, Subway, Cenarios Pizza, Tutti Frutti Frozen Yogurt and Avis. Only a few blocks to downtown and near UC Davis.

Public Transportation  Cranbrook is located on Unitrans E bus line which goes to Memorial Union.  Several Yolobus routes stop nearby at Covell Blvd at J Street and will take you to Sacramento, West Sacramento, Woodland and Sacramento International Airport

Bicycle  Cranbrook is on the Covell connector to The Davis Bike Loop.  The UC Davis campus is 1.5 miles away.  There are bike lanes on all of the surrounding streets.

Pedestrian  For recreational adventures, walk over or under the Covell Train Overpass to connect to The Greenbelt.  For grocery, shopping, some services and dining, Oak Tree Plaza is about 4 blocks away.  Head down J St. and youre practically downtown.  This is also a good jogging location.

Parking  Plenty (uncovered) parking available.

ADA Accessibility  Fine  lots of ramps


To learn more about rental housing options in Davis, check out our Housing Guide as well as our Apartments pages.

Older comments can be found in the /Comment Archive comment archive.



20100105 11:51:49 nbsp Cranbrook rules. Definitely one of the best complexes around. The manager chrissy and melissa are the shit. Not literally. The premises is always very clean and i always see maintenance and landscaping being done. Very friendly staff all around. Awesome pool, awesome workout room, soda machine, twenty four hour study lounge and laundry room. Its expensive and the rooms arent too big, but you realize why you pay so much after you move and everyone at your new apartments sucks, and its filthy. I had the worse roommate anyone could possibly have but cranbrook was still awesome. Cranbrook, yay. Users/Maqz

20100128 00:50:55 nbsp  My roommate and I have been living here for the past few months and I can honestly say that its totally worth it. It is expensive, but once you move in you understand why. The only problem we have is that living on the second story we can hear when our neighbors; both downstairs and next door, close their doors  it shakes the whole living room, same happens when the trains are passing by. Other then that, whenever we have any maintenance problems we just call down to the office and they are here within the half our, its relatively quiet, close to P, Q, and E lines the nugget and CVS. The lounge, gym, laundry room are all clean and well kept as is the lawns, during the summer and fall they were always here 2x a week. Everyone at the office is great, and are VERY helpful. The amenities are great as well!  Also our rent actually decreased by $20, and once we renew our lease we get our full deposit back ! ! ! Users/VMtz

        So we did get our full $400 deposit back (with the $3 interest) and altogether our rent was lowered by $40

20100223 02:45:46 nbsp I havent lived here for that long but it seems pretty nice so far. When we first moved in we had a pretty big rat problem and some other minor problems, but management was really quick and friendly in fixing it. Sometimes the laundry room fills up, but if you time it right it should be fine. Its very quiet, I live in a complex next to Covell and was worried about car sounds but its really not bad. The noise thing is true, when people are outside it sounds like they are talking to you, but theres not usually people outside my window. Pipes squeak and it was annoying at first but Im used to it now. Its very close to the E bus line and the Nugget, which is convenient. The bike ride isnt too bad. I like how they have free cookies during their open hours and a cookie oven in the study lounge...is that there for tenants to use also? I always wondered that.

Overall its a nice place to live, really pretty trees and spacious layout. Maintenance is pretty stellar, and there isnt too much to complain about. Users/AlisaKim

20100709 13:46:57 nbsp I have been living here for almost two years now and can say that I have had a pleasant experience, mostly due to management staff who are really enthusiastic, helpful, and make things easy for you. Krissy, the Residential Manager, has been awesome in helping accomodate all my needs here. I would recommend not residing at the west end near the train tracks, where I lived for over a year. The second year, I chose to move nearer to the entrance area by the corner of J and Covell and it has been really nice. Quiet and covered by trees so, I rarely have to turn on the airconditioning even in the 90 degree hear so far. Cool staff, endless hot water, free DSL, and spacious master bedroom with walkin closet, big pool with spa, a nice 24 hour study room with comfy leather couches, and the workout room were some of my favorites here...some reasons why I decided to lease for another year. All these were helpful in dealing with the stress of applying to and studying for pharmacy school. Yay, I got in! Users/LKim78

20100722 15:01:16 nbsp I lived at Cranbrook for two years and am happy to have stayed there for my entire term at Davis. All my friends were always moving about trying to find a better deal than their previous apartment, but I did some research before moving to Davis and found that Cranbrook matched my needs best. I was looking for something far enough away from campus that you dont have to deal with the bar crowds if you choose not to, but within walking distance of a shopping center for groceries and such. Cranbrook was perfect. I believe that the residents are from all walks of life, undergrads, graduate students, families, and the single working crowd. This keeps everything lowkey and mutually respectful. None the less, we had plenty of BBQs out by the pool without every having a problem with management. The price isnt bad, and we got all our deposit back plus a bit of interest, which is unheard of. The management couldnt be any more warm or friendly, in fact they felt more like extended family than complex overseers. All in all, Im very happy to have stayed at Cranbrook while at Davis, and would recommend it to any friend, I did actually, and three friends of mine live there now! Users/CarsonConner

20100806 14:00:06 nbsp The Cranbrook Apartments are the BEST apartment complex in Davis. I toured many apartments when I moved to Davis last year and nothing compared to Cranbrook. The management and maintenance teams are fabulous. Management knows you by first name and is available to answer any question and help you with anything you need. Maintenance responds to any question or problem you might have promptly and efficiently. The Cranbrook Apartments are affordable, well maintained, quiet, friendly neighbors, great pool, close to bus lines, easy biking distance to campus, and walking distance to a great shopping center.  I recommend this complex to anyone currently looking for a place to live in Davis.  Users/EDunn

20100814 09:11:42 nbsp I have lived at Cranbrook for 3yrs now and it is the place to be. The Management and Maintenance Staff are amazing and super Friendly, they make sure you are well taken care of. The Lounge is nicely decorated and the pool just got new pool side furniture that is so Country Club Worthy. The gym is pretty nice too, its perfect for when you are home and dont want to go all the way to the arc, just to workout. Ohh did I mention you can also reserve the lounge for when you want to have get togethers and study groups. Plus there are always fresh cookies available, and snack in the lounge plus the awesome Cappuccino Machine on a well stocked coffeetea bar. The whole property is well maintained, cleaners at least 3 times a week,gardening weekly....what better place to live in than one that is well kept. They even clean your carpet when you renew your lease. And the West End Parking Lot was recently repaved, so no guessing is this a park, it is beautiful and well defined with Disable Parking as well. The apartments are really spacious!! The 1bd apartments have 2 very nice size closets and enough space in the rooms for a full desk, queen size bed, a dresser, lamp tables and still much more space. I have that much furniture and still managed to fit in a large queen size air mattress when I had guest over.     Users/StarHarris

20100819 06:24:36 nbsp I am looking for someone that is willing to take over my year long lease and wants to move in soon. My brother and I enjoy living at Cranbrook but we cannot afford our 2b apartment anymore. We have a bottom floor two bedroom that is located next to the pool, very close to parking lot, trash and laundry. If anyone is interested please email me at jfcranbrook@gmail.com. Thanks ) Users/Jfranckiewicz

20100903 16:24:34 nbsp I just moved from cranbrook and I was very satisfied with the management as well as the maintenance staff. Any problems I had were immediately resolved and the front office was very friendly towards walking in with any of your concerns. I am really going to miss the friendly service provided by the Cranbrook staff. The apartments are very nice and moderately priced for the city of Davis. I really enjoyed living at Cranbrook and would recommend it to any person looking for a quiet place to live with a competent staff and beautiful pool.  Users/ElliotSobel

20100914 00:14:28 nbsp The painting inside the units at cranbrook is always great! I wonder why that is Users/StevenDaubert

 This is because residents are allowed to paint their own apartments as long as they paint over in white when they leave. Users/jenb

20110315 09:18:52 nbsp Anyone willing to post their average cost of Electricity and Gas per month? Users/KirstenSargent
  I pay about $35 a month for PG&E.  We try to keep all the lights not in use off and keep the heater at 70.  We also tend to cook and use the dishwasher a lot too.

20110413 12:53:42 nbsp Thanks for posting your info about PG&E!! I noticed a comment on the Facebook page about inspection week .. What is inspection week exactly? :) Users/KirstenSargent
 Hi Kirsten! Inspection week is when Steve & Ed go to each apartment and make sure that all of the appliances are functioning properly and that everything is in good repair (e.g., doors, windows, light fixtures, etc.).  We made sure that everyone had notice that theyd be popping inthis only happens once a year. I hope this has been helpful! ~Users/Cranagement

20110416 10:29:58 nbsp APT 168 resident here at Cranbrook. I was supposed to post this but never had the time. Great service! The office closed already on friday and I had to pick up a package. Management stayed just to give me my package! that made my weekend!
 Users/SamVang

20110512 21:44:53 nbsp I love this apartment. I took a tour with my parents in Spring Quarter 2010 and moved in June 2010. Thereve been very few issues, and those issues have been dealt with quickly by management. If anyone else is interested, one of the rooms in my 2 bedroom is going to be up for sublease starting June 10 2011 through August 31 2011. I put the room up on CraigsList here http://sacramento.craigslist.org/sub/2378156315.html if anyone is interested.

Bills usually total about $30 per person (PG&E and phone), and even though youd be getting the bigger room (11x13), rent is split equally. Im OK with two people sharing that room, too, so rent would be super reduced :) Users/ChristineDillard

20110517 19:24:27 nbsp I am interested in this place but hesitant  for any past or present tenants, were you comfortable during the summer without central air? Users/isands

20110711 23:02:27 nbsp I posted before about needing a Summer room mate, but it turns out I also need a room mate for September 1 2011  August 31 2012. If anyones interested, please contact the front office and tell them youre interested in a room in apartment 366. Theres also an ad on Craigslist here: http://sacramento.craigslist.org/sub/2489733745.html .  Users/ChristineDillard

20110711 23:05:34 nbsp Hey! This is a super awesome complex! The management rocks! I have a room available for sublease for the entire upcoming school year! Here is the craigslist ad with all the details! http://sacramento.craigslist.org/roo/2499349679.html
You will have your own room at $577/month and the apartment will be shared with one super friendly girl and a cat. You will not need to pay for utilities or Internet. Let me know if your interested!  Users/RoxanneCoonrod

20110728 16:46:55 nbsp Hi, All  want to recommend Cranbrook as highly as possible for the simple fact that the management is superlative and that, ultimately, is what affects a comfortable apartment life.  No problem! is the constant response, no matter how inconvenient the request to their time.  Ive seen Steve working hard on an issue on a Sunday morning, I get immediate response to any problem, large or small with the apartment, and really feel they are friends, not just the management.  If potential noise is an issue for you, ask for something away from the J/Covell corner, or near the trains, but otherwise, just normal apt. sounds.  Great neighbors and a huge kittyfriendly population.  Our neighbors helped us with a charming stray, and we kittysat for them while they were away.  Theres no nonsense here and if there is, you are aware of it instantly and it is handled instantly.  Truly nice folks here and the study lounge is tres comfy and always smells like cookies! You might pay extra here, but it is infinitely worth it.  Kudos to the staff, one and all, and would recommend to anyone, not just students.  Cheers, folks and enjoy Cranbrook.  I sure did!  Users/catchambers

20110920 18:25:24 nbsp I really enjoyed living at Cranbrook. I only moved because I needed a bigger place. Anyways, as far as the apartments go, they were in nice and clean. My biggest complaint about this place was that when the sprinklers were on, we only had hot water.

But the thing that made this complex so amazing was the management. They were always friendly and always helpful. Maintenance issues were fixed quickly, and they office staff was always great and helpful. I had some roommate issues that they were even willing to help work out! They are great people, and I recommend this place to anyone looking for a nice apartment. Oh, and we got back our full deposit with no hassle whatsoever. Users/LinLulu

20120409 17:05:43 nbsp I made a big move from AZ to Davis and am so thankful to have found Cranbrook!  Its been a GREAT first place to live!  Especially with being new to California, I appreciated having excellent management.  They have amazing attitudes and are eager to take care of their residents.  With any little maintenance things, Steve or Ed have come by to help very quickly.  Love having a workout room, pool, and being close to downtown.  Lived here for 16 months and have deeply enjoyed it!  Moving now that Ive found a house to rent but will miss the excellence of Cranbrook! Users/JenTiffan

20120418 12:42:57 nbsp This comment may sound out of the ordinary, but bear with me. Aside from the obvious things that an apartment complex should have (walls, roof, working toilets, fresh water, etc.) Cranbook offers by far the best living experience in Davis. Ive lived in Davis now for about seven years, during that time I have stayed in south davis with Allegre apartments, west davis at a privately managed apartment, and the remainder of my time in North Davis, one year at Chautauqua and the this will be my fourth year living at Cranbrook. I know what youre thinking, hes spent three years living at the same place, and hes signed up for a fourth, they must have some awesome management, great onsite staff for repairs and maintenance, and be an overall great place to live. It is, all that and more. Ive never really taken advantage of the pool or the gym facility that they have on site, but they do offer those. Its located close to Nugget market, which is a great place to go and get your groceries, as well as the occasional dinner.

But here is what I really love about Cranbrook, I live in an apartment with some empty space out front in the form of a concrete patio where bikes used to be stored. I say used to because Cranbrook has allowed me to reappropriate the space into my own little orchard and garden. At the moment I have over a dozen fruit trees growing in buckets, a 2x8 foot raised planter box, and theyre discussing letting me put in a greenhouse. Maybe they know that the more stuff they let me put in, the harder it will be for me to leave, or maybe they just really love and appreciate their tenants. Either way, how awesome is it that an apartment complex would let you do that? And weve also tilled one of the smaller dead areas where nothing was growing and planted a few flowers and veggies for the summer.

Never before have I lived somewhere that I would have even considered broaching those ideas to management. The folks who work here are friendly, chatty, and enjoy engaging in conversation with their residents. I often find myself going in to hangout or chat with the office folks at least once a week. Krissy and Olga are a blast to chat with and a guaranteed laugh. Sarah, who will sadly be leaving at the end of the summer to move onto bigger and better things, Stanford (congratulate her on that if you see her), is hilarious and always fun. I consider all of the folks who work there to be friends of mine and people that I will miss when I move out one day. Steve and Ed are the two maintenance staff that are always around, they are prompt, friendly, and great people to be around. Sometimes its awkward to have someone inside your house working while youre home, but not with Ed and Steve, theyre friendly and engaging and theres never any kind of awkwardness around them while theyre there.

Bottom line, had I known about this place when I first came to Davis, this is where I would have moved to start (I also wouldnt have lost any money on security deposits from moving so often). Sign the lease for a year, and then the next, its a decision you wont regret.    Users/PhilipCelloJr

20120513 16:59:54 nbsp I lived in both the single and 2 bedrooms in Cranbrook within the past 2 years and I say, its a pretty decent place to live in. I lived in the back portion, so the downside to that was that the train would annoy me in the morning but it would wake me up for class along with the boppers who run around the area. I timed myself and it takes awhile for me to get to my car from my apartment but only because I lived in the farthest part literally on the edge of the area. What I hated most about this place was whenever I parked close to the buildings, you know the U shape area of the parking lots, not the entrance but the part where its closest to the buildings in the back portion of the lot, people would just park where they would block a couple of cars from getting out. It has happened to me more than 10x within 2 months by the same people. Im not trying to be racist, but it was these African American people who lived in the back and they yelled at me for asking them to move their cars because they made me late for work and school a couple of times. The staff is great here though, just I remember the lady cleaning the washing machine with her mop, dont know if it was the same one she used to clean the floor with. Decent workout area and pool. I moved out because I have friends who lived closer to school and got a cheaper price from them, other than that the distance from school and everything else is in the perfect area and I would stay here if I were alone.  Users/JaceWinter

20120924 16:34:44 nbsp I needed to upgrade from a 1 bedroom apt to a 2 bedroom. Our neighbor wanted to downgrade so we both got together and signed a contract asking management to not get involved as we trade places. The unit was not as clean as we would have hoped. There were stains on the carpet, the walls were discolored, and the unit was just not very clean. Even though we asked management to stay out of our agreement they still replaced all the carpets, repainted the apartment, and sent in a full cleaning team at no cost to us. Ive lived in a few other apartment complexes in Davis and Cranbrook has the best management by far. If youre looking for a new place I highly recommend checking out Cranbrook.

PS. They always have fresh cookies in the office. Users/GlenGillman

20121013 08:42:24 nbsp So, maintenance is amazing here. Every problem was fixed within two days. We just had a clogged toilet and garbage disposal, and someone showed up at 7:00 on a Friday night, fixed everything and then said they would replace both of them. Couldnt have asked for more. The places are nice, the pool is great. Best apartment complex Ive lived in so far and this is my 5th year in Davis. Users/KyleTos


20130226 11:17:51 nbsp I love living at Cranbrook apartments. This is the first place Ive lived at on my own (with my boyfriend) and I was actually really scared to live on my own at first. However, when I came here to do the tour, everyone was just so friendly. There were fresh cookies and smiling faces to greet us. They have been so flexible with our financial aid when it comes to paying rent and the activities they organize are amazing. The thanksgiving dinner was fabulous. And the maintenance has been fantastic. I can not recommend these guys more highly. Best first apartment I could have asked for. Users/VictoriaAugusto


20130226 11:35:00 nbsp This place is awesome. The prices are reasonable. The management is wonderful and very punctual when it comes to maintenance and/or additional renovations. They had to fix three pipelines and we got a new bathroom out of it (new floors and new paint!).  My apartment is cozy, and the study hall is great for finding new neighbors: students! In other words: you should move here!  Users/LeryanBurrey

20130227 20:37:23 nbsp I absolutely love living at Cranbrook! I have nothing but good things to say about this place. When my fiancé and I looked at apartments, we knew from the moment we got here that this was the complex to choose. Not only is it the same price/a little less as most places in Davis, but its also the most modern. I love the layout of my apartment. I have a 1 bed 1 bath and the bedroom is huge and I have a gorgeous walk in closet, everything about the place is perfect! The management is insanely awesome. They are always there when you need them and are never bothered by us coming in. In fact, they love visitors. They are always doing something fun for us residents. They had a big welcome bbq this fall with an awesome raffle, a huge catered Thanksgiving dinner, they provided lunch for us all of finals week (including Nutella), they had set up a gorgeous dessert bar for Valentines Day, the list goes on! The facilities are all 24 hour, which is perfect, especially for the study lounge. They are always friendly and understanding. They never enter your apartment without your permission and always let you know when they have been there. When it came time to resign our lease, we were in an unsure situation of whether or not we could stay, but they gave us an extension (which was very convenient on our part and made our situation much less stressful). Also, my fiancé noticed a problem with our car and searched town for someone to fix it. Everyone wanted hundreds of dollars so he returned home and the maintenance guys here at Cranbrook lent him all the tools he needed to fix it himself and they even helped him do it! That saved us so much money and made us appreciate our management so much more. This kind of management is hard to find. Everything about them is fun and they care so much about their residents, it really shows. You havent experienced good management until you have met Cranagement! Users/ChelseaUhrig

20130329 01:19:02 nbsp My husband and I (and baby) lived here fro about 2 years. This is THE best apartment complex in Davis. We absolutely had a 100% positive experience with everything about this place. The staff are SO awesome. Chrissy, Emily, and Nicole always made us feel taken care of. They are so attentive and make sure that problems are resolved quickly. I LOVE cranbrook! Users/jenb

20130527 08:52:38 nbsp Cranbrook apt, is the best apartments I have ever lived at. Very quiet, friendly and lots of parking. Maintanes men are prompt, friendly and always willing to help. Office staff are polite and caring. Did I mention quiet? Very quiet, pet friendly! It was a great experience. I would live there again. Chrissy the office manager really helped me by finding someone to rent my apt and letting me out of my lease. She went way above and beyond to work with me when I fell on bad times. The area is always clean, garbage is picked up frequently, which is a bonus.  I had a very good experiance. Thank you cranbrook.  Users/Charhall

20130606 11:14:19 nbsp Honestly, one of the best places to live in Davis.  The location is pretty fantastic as youre easily within walking distance of The Nugget Market, its a comfortable bike ride to downtown, and its not that far from campus.  If you have a car, one of the biggest headaches is always parking, but in the 2 years that Ive lived here, Ive NEVER had to fight for a parking spot or ever had to park far away because there was no parking.  Theres always parking on the street and in the spacious parking lot in the complex.  Krissy the apartment manager is totally awesome  shell take care of you and treat you like one of her own.  Management as a whole is always friendly and approachable and always tries to make time to listen to you, even if you just wanna chat.  One of the best management teams Ive ever come across while living in Davis, and Ive lived here 6 years and have had to move every year EXCEPT when I lived here.  Could not be happier.  Also, the complex as a whole is very quiet.  If you want rude people who blast their ridiculous sound systems late at night and have insanely loud parties, go live somewhere like Fountain Circle in North Davis.  If you want a place thats quiet, relaxing, and with courteous people, live here.  You wont regret it. Users/TimIshii

20130829 13:08:58 nbsp I have lived here for a year now, the management is great and always very helpful, its near the train tracks but living halfway into the complex it has never bothered me even with the windows open. There are two main things to look out for though, first is when choosing an apartment try to stay away from the dumpsters, as the dump trucks sometimes come early enough in the morning where you might want to still be sleeping (about 8am) and they are insanely loud if your apartment is next to one. Other than that it is just water problems. Granted here you dont pay for the water bill, but there have been over a dozen issues with it over the course of the last year. A lot of the times it is just the water being turned off for a few minutes without notice, sometimes much longer, and after it turns back on the water is brown so you have to let it run till it gets clear again. The lack of water pressure and then it coming back on has also lead to the toilet filling itself up with the dirty water, leading to it needing random cleanings. Finally the water temperature is not constant and if you try to take a shower when the grass is being watered the lowest temperature you can get is boiling. So while you still have water you cant take a shower without burning yourself. Overall I do love Cranbrook and signed up for another year because these issues are only slightly annoying sometimes and never match how awesome the management can be, but if you plan to live here keep this in mind. Users/norikaeru

20130910 11:45:50 nbsp
Hi Norikaeru

Thank you for taking the time to share your thoughts with us. I can’t express enough my apologies for the main water line break in the property over the summer. Although we provided the showers, toilets, and drinking water as we worked hard to swiftly repair the line, we realize it was a huge hassle for everyone involved. Thank you for your patience. The good news is that it is fixed! In general, we do occasionally shut the water off briefly for small repairs in individual units and this does at times result in a moment of brown water residue to be flushed through the pipes. We do our best to warn our residents to let the water run for a bit to become clear again but I understand that it can be a little unsightly and inconvenient.

As for the sprinklers, I am excited to say we are exploring an automated sprinkler system to alleviate our watering at peak shower times of the day. This will have much less impact on water pressure and temperature in all of the apartments.

We are very glad you decided to renew your lease here at Cranbrook Welcome to another great year and please do not hesitate to let us know if there’s anything we can do to make your stay even better.  Feedback like this allows us to know how we can better serve our residents and provide a positive rental experience. Our main priority is our residents satisfaction We want you to love where you live.

Sincerely,
Krissy
Residential Manager Users/krissyp

20130920 13:03:26 nbsp I lived in Cranbrook Apartments for 2 years, and all I can say is that theyre the best apartment complex in Davis! The apartment managers are honest, friendly, and really caring about their tenants. Every time that I needed help with a maintenance issue or other things, they respond immediately! Krissy is just wonderful, and she tries her best to accommodate all of her tenants needs. The other assistant managers are also great. Unlike other complexes out there, Cranbrook doesnt try and cheat their tenants with their deposit money. I got my full deposit back for cleaning the basics and making sure that nothing was damaged. Oh and another thing, the parking is great! Youll always find parking in this complex! Overall, I cannot emphasize how great of an experience Cranbrook was for me. So, if you want to live in a student friendly environment and have the best staff available to you, choose Cranbrook!  Users/Zyra

20130922 14:40:06 nbsp Cranbrook is a wonderful place to live. The rent is reasonable, the apartments are nicely laid out (with pretty big bedrooms), the management is very helpful, and maintenance works quickly to fix anything you need. I lived at Cranbrook for 2 years and it was by far the best place I lived in Davis. The bus stop is close by and the pool is really nice as well. They also have a gym and a study room. I would HIGHLY recommend living at Cranbrook! Users/LouiseM

20131002 22:59:35 nbsp I lived in Cranbrook Apartments for one year, and the only reason I moved out was to get a four bedroom apartment with my new housemates.

I have ZERO complaints. Management was always friendly, accommodating, and fantastic. They have free snacks, cookies, and coffee every day, free WiFi in the study lounge (speed is good, and the lounge was always nice and quiet when I was there), they do a PB&J/snack bar during finals week, they had a lovely complimentary Thanksgiving dinner (they even gave me some meat to take home to my dog), and they do several raffles and contests for residents throughout the year. They immediately took care of any requests or concerns I had. Maintenance even came to my apartment while I was at work to change some light bulbs and turn the AC on for my pets during a heat wave. Even after moving out, Krissy and the rest of the staff have been friendly and accommodating. They were also generous with my security deposit; I got a lot more back than I was expecting to.

The old assistant manager Emily was AMAZING. She helped me through all of the lease paperwork and went above and beyond to address any concerns I had. She always remembered me and my apartment number when I went to check for packages. I would visit the office sometimes just to hang out with her.

I lived in a west end apartment by the train tracks, and it was no problem at all getting used to the trains. I got a great view of the fireworks that they sometimes set off at the Community Park (at F and Covell) from the staircase outside my apartment. I also knew several of my neighbors names and felt completely comfortable around them. We would talk, hang out, do favors for each other, etc. The community at Cranbrook is wonderful. While the complex is a little far away from the school, I prefer it that way. It was quiet and felt safe. There are also several bus lines nearby (the E Line is right outside, which goes through downtown), so transportation was never an issue.

THANK YOU to Krissy and the rest of the Cranbrook staff for all your hard work! It definitely makes a huge difference. Ive had some negative experiences with apartments in the past, and this definitely isnt one of them. Hands down, if youre deciding between Cranbrook and another apartment complex, Cranbrook should definitely be your first choice. Users/FeliciaMegowan

20140326 16:26:25 nbsp Honestly, the management do their best to act like they care. But I have a upstairs neighbor who acts as if he and his roommate are raving 24/7. I have gone to them 3 times, filed a police report, and this neighbors have hardly even changed their behavior...My next step is to try to see if I can try to break lease if nothing changes, because the bass is constantly shaking the walls and sometimes it goes into the night as well, during quiet hours. I enjoyed living here initially, but I feel disrespected by my neighbor as well as management, as they seemed to kind of brush off what I was saying. Everything here is built probably about 50 years ago, and there are flour beetles everywhere, even when I first moved in. I chose these apartments because of the good reviews, now Im starting to wonder if there were any complaints in the past. Due to the lack of insulation, the gas heater costs a fortune! I had central A/C at my old apartments, and the bill for heating was half the price despite the fact that it was a 4bedroom. At Cranbrook, I am sharing a 2 bedroom apartment, and turn on the heat only sometimes, and my gas bill is ridiculously expensive, $70 for 2 people! Needless to say, I chose to be cold rather than to keep such ridiculous amounts. The lack of insulation also causes every creak and stomp by your upstairs neighbor to be heard, and if youre fortunate like us, then your neighbor will also share his wallshaking, ceilingthumping rave music with you. Cheers! Users/DavisCollegeStudent

20140401 11:03:42 nbsp Hi DavisCollegeStudent,

I am so surprised by your comment here and on Yelp. I want you to feel free to come to the office to discuss any concerns you have so we can help make your experience at Cranbrook the best it can be. Prior to this week, we had hoped that your noise problem was resolved by the notices we posted to the resident. Unfortunately, after chatting last week, we understand that was not the case.  Cranbrook’s policy in regards to noise is two warning lettersto give the residents the chance to become aware of the problem and correct the behaviorand in the case of a third violation they receive a third and final notice to comply and we take further action. We explained this policy to you and was under the impression you understood that was the next step we would be taking when you left the office.  I apologize if you felt like your concerns weren’t being heard.

As far as your pest and insulation concerns, we had no idea your were having these issues.  We need to know you are having these sorts of problems in order to resolve them. Please come into the office so we can chat about how we can work together to fix things for you. We genuinely value you and all of our residents here at Cranbrook. Thank you for taking the time to post your experience.  It is feedback like yours that helps us better serve our residents and we do want very much for our residents to be happy here.

Sincerely Krissy Users/krissyp

20140430 14:35:11 nbsp Awesome place to live! Close to downtown...all kinds of stores nearby and amazing hospitality :)..lived here for 4 years and loved every minute. Users/robertmoctezuma

20140701 15:19:22 nbsp My favorite part about Cranbrook is definitely the staff! I have been living in Cranbrook for two years now and I can honestly say that there is nothing that they wouldnt do to help you. Krissy, the Residential Manager, rules. She can pretty much accommodate any need and fix any problem. Joanna, Nichole and Kathryn are the sweetest. They are really enthusiastic and eager to help. There is nothing that the maintenance team cannot fix. I see Evon the most and he is really helpful and nice. Whenever I need something fixed, he responds very quickly and the job is done well. They love their residents and often organize games where we can win things, catered meals for thanksgiving or cinco de Mayo... They even bake cookies and serve fresh coffee every morning!!
The amenities are great. They have a nice gym and a really, really nice pool! Ive heard its the largest pool of all the residences in Davis. The apartments are spacious and clean. They even let you paint the walls if you want. Its very quiet and the exteriors are very clean and well kept. Nugget and CVS are a 3 minutes away by bike, downtown is 5 minutes and campus 10 minutes. The E line stop is also very close to the entrance.
Im so glad Ive found Cranbrook and Im definitely not moving out until I graduate. I really recommend this place if you dont want to worry about anything related to your apartment!  Users/AlexandrineMailhe

20140703 15:33:46 nbsp Cranbrook is such a great place to live! We girls had a wonderful living experience here this year! Its very convenient, close to Nugget, CVS. I love the pool and spa, we had so many good memories there. The apartment is sunny, bright, spacious, and my closet is huge!! The best of all, the staff here are super nice and helpful. They deal with issues very quickly. Whenever we have a problem, its solved the same day. Parking is easy. So many parking spots, I never had a problem parking here. Overall, Id stay here another year if I didnt have to move out of Davis for work. I highly recommend this apartment. Users/SusieWang

20140815 12:14:42 nbsp Cranbooks management is definitely its highlight. Ive lived in Davis for a while now and no other apartment management will treat you like family. I absolutely love the holiday festivity. The management offers thanksgiving dinner. Im a huge turkey fan, so the annual thanksgiving dinner was awesome to say the least. Furthermore, the management is very quick at fixing problems. Our AC stopped working a few times this summer. They fixed the AC the same day I sent in the request. When the AC broken the third time, they didnt hesitate to replace the old AC with a brand new one. All in all, I feel Cranbrook management honestly care about their tenants, and I would love to recommend them to any college student! Users/NickYin
