In retrospect, over the last couple of days, several of my comments regarding the March 4, 2010 Public Education Protest and its protesters have been harsher or more sarcastic than necessary.  I apologize if I offended anyone; that truly was not my intent.  I intended shock value to express my frustration with the whole thing, but I had no desire to hurt any feelings.  Please keep in mind that when I use you in here, I am speaking generally to those who fit a category and, while I do quote a couple of people to illustrate my points, I dont mean to target anyone individually.

Rather than go on with the back and forth with all of its crossposting between different threads and trying to draw out answers to my questions, I thought that I would  compose my thoughts in a relatively coherent way.  Im going to try to respond to a number of the statements, comments, ideas, and attitudes with which I have taken issue, and to lay out my general feelings on the topic.  Because its so long, I thought Id give it a separate page.  Please feel free to respond to any or all points. Users/TomGarberson

My issue with demonstrations
Im not categorically opposed with demonstrations/protests/strikes, not by any means.  I am opposed to them when I dont think theyve got a reasonable chance of doing any good, however.  When the activities planned for a protest have no rational relationship to promoting a solution to the problem, its not going to be a good thing.  This becomes far, far worse when the protest involves violence, graffiti, or major disruption to the lives of others.

My issue with the attitudes of many protesters
Ill use the following quote for the purpose of demonstration, since it so perfectly embodies the attitude with which Im concerned:
  so for this strike, there should have been about 2 weeks notice. If people know there will be a strike, they shouldnt be in their labs. They should join the picket line. Failure to do so makes one a scab. One should expect disturbances when there is a strike. Thats the whole point of it.
The arrogance of this statement had my jaw resting on my desk.  In essence, it is saying that anyone who A) Does not agree with the protesters; B) Agrees with the protesters but feels that the issue should be addressed differently; or C) Is unaware of the protest actually DESERVES whatever happens to them at the hands of the protesters.  I have no issue with you thinking people are lazy or inactive should they choose not to join in your movement.  Thats fine!  But when you go so far as to say that they deserve to lose out on education, be unable to get to the hospital, or have days or weeks worth of research destroyed by whatever you might choose to do during a protest, you go waaaaaay too far.  Not to say that the two situations are equal on any level, but the rationalization is identical to the one used by terrorists the world over to excuse killing innocents unassociated with their targets.  Bystanders deserve what they get!  Just something to think on.


Why I disapprove of many of the actual demonstrations I come across
The fundamental problem with any situation where you have a large group of emotionally charged people out to say screw you to authority is the potential for things to go downhill rapidly.  Again, dont get me wrong: Im not saying its always bad!  But the propensity for otherwise intelligent people to do painfully stupid things has been illustrated since time immemorial.  All too often, all it takes is one rabble rouser to turn a great event that brings people together, educates, and garners positive publicity into a fiascoor worse.  To illustrate, Ill copy over my experience as a freshman here at Davis which I posted elsewhere:

  Im reminded somewhat of a rally that took place my freshman year here, probably in Spring 03.  I lived in Tercero B Building, and right outside, at Tercero A Building Casa Cuauhtémoc, there was a rally about racism and racial inequality in education and that kinda stuff.  I thought it was kinda cool, and watched for a while out of the balcony at the east side of the building.  They had several excellent speakers.  But within about an hour or so, someone got on the bullhorn or microphone and started a chant of KILL THE WHITEY that went on for a good 5 or 10 minutes before people finally settled down.  The lesson I learned from that is you can have a really wellintentioned group that gets together and turns into a group of raving idiots because one lone rabble rouser with a microphone triggers a mob mentality and turns their goals to shit, making their movement 100% counterproductive.

Whether because of simple recklessness once people get excited or some Durkheimian totemic religious group experience, the fact remains: things have a tendency to get ugly when riledup groups take to the streets.  As such, I strongly feel that great caution needs to be taken in organizing such events.  The tendency of protesters to deny responsibility for the consequences of their actions is both saddening and infuriating.  If someone gets hurt, its always law enforcements fault.  If someones research is harmed or their education interrupted, its their own damn fault for not participating.

Take a little responsibility for your own actions.


Why I disapprove of this particular protest
  It was counterproductive
I can only think that this protest was counterproductive.  It made students seeking action from politicians on the budget and fees look bad.  A lively, educational protest that didnt do anything stupid would have been a good way to raise awarenesspositive publicity.  A march on the capitol, where youd be getting the attention of people who could do something about the issue would have been a great way to take action.  Hell, even going in to Oakland would have been a good ideathat is, http://www.ucop.edu/ UCOP in Oakland, where youd find people who actually have some say in the matter.  I dont think city hall or 880 fit the bill, sorry.

Moreover, when Ive asked (repeatedly) what rational relationship exists between the actions of the protesters and their ostensible goals, the only reply Ive heard is: ummm, the protest was for education.  The other obvious possibility is publicity but, for reasons I think I explain clearly here, I find that all but impossible.

It was also diluted by all the causes for which the protesters were apparently demonstrating.  All of the budgetary stuff, sure... but Israel, homophobia, racism, the war, and police brutality?  Come on, now.  The only thing all of that is going to do is undermine the primary message.

  It was hypocritical
This is the one that gets me the most angry, even though its probably the least substantial.  These people claim that the goal of the protest is to lower student fees and return funding for programs, but they WASTE UNIVERSITY MONEY.  Its beyond infuriating.  Its beyond stupid.

Its like a child running to mom and dad, demanding a bigger allowance, and when he doesnt get it, throwing a fit and starting to break his toys.  To quote from one of the supporters, costing the University system money is precisely in keeping with the goals of the protest, especially if the students continue to be active and pursue it, because it sends the message that the tuition increase isnt going to be a fruitful way to increase revenue.  Are you kidding me?  Money doesnt grow on trees!  Mom and dad cant afford to give you everything you want.  When you break your toys, your best case scenario is that the money that mightve upped your allowance is going to be used to replace the crap you broke.

What do you expect the university to do?  Lay off professors?  Staff?  Close buildings?  Drop graduate programs?  End subscriptions to all of the library resources?  Cut internet?  Yes, there are a variety of ways they can save costs, but the previous times theyve tried to do so, other children have locked themselves in Mrak in another fit.  Ill bet a lot of them were even the same damn children.

Its also quite ironic that a group thats protesting hate spewed at the Lesbian, Gay, Bisexual and Transgender Resource Center LGBT center in the form of graffiti would use graffiti themselves.  I recognize that the objection is to the hate and intolerance, not to the use of graffiti; the ironic parallel simply illuminates one more poor choice made by the protesters.

  The worst of it was planned
Another disappointing facet of the March 4 events is the simple fact that I cant even write any of it off as that propensity for people to get too fired up.  Showing up with good intentions and getting a little overexcited doesnt make spray paint magically materialize in your hands.  And the fact that other groups at other universities were equally stupid with the freeway obstruction likewise makes it obvious that that foolish stunt was planned ahead, presumably by the organizers.

The problem with selfdescribed Activists (pardon the tangent)
I am referring here to statements like, its difficult when youre a student trying to be an activist.  This is common.  Way too common.  When youre trying to be an activist, rather than trying to accomplish X, youre focused on the means, not the ends.  A protest has no inherent value.  I know there are those who will hate me for saying it, but its true.  If a protest doesnt make progress toward a valuable end, its worthless.  By trying to be an activist, as evidenced in this discussion, its all too easy to simply dismiss other avenues of trying to reach the same end.  When you find yourself dismissing those who share your goals, those who write letters to their representatives, those who discuss the issues with their friends and try to get them out to the polls, simply because they didnt attend a protest, you are doing your goal more harm than good.  It may make you an activist, but what good is that doing you or the other people whose interests are at stake?

One additional problem: Fringe groups
My final point is about activists who do outrageous, inflamatory, or highprofile disruptive stuff.  Do you not realize that youre just like any other fringe group?  Being loud and inyourface doesnt always help, as upsetting as that may be.  Fred Phelps holds lots of protests.  Should the police block off freeways for him and his followers to stroll down?  Am I a scab when I choose not to participate in his demonstrations?  The fact of the matter is that when you draw negative publicity, you make your movement look bad.  Phelps hurts the nations perception of evangelists among those who dont know enough evangelists to realize that they are (generally) real human beings, not hatebots.

By being violent, by vandalizing, or by creating problems of the sort this group tried to create, they identify themselves as a fringe group and cast a negative light on their goals.  This doesnt just harm you!  It affects all UC students.

Conclusion
Im not sure which bothers me more: the stupid things the protesters did, the hypocrisy inherent in their doing, or the blithe and arrogant attitude of the participants and supporters whose sense of entitlement frees them of any notions of personal responsibility whatsoever.  Im disappointed, but I do hope that the protest was at least cathartic for those involved.  I honestly believe that, all too often, catharsis is the primary value of these things.

Signed (ish),
Users/TomGarberson



20100307 21:20:58 nbsp Bravo! Really, truly I would love to see this (perhaps modified slightly due to word length limits) as an oped piece in any local/national paper.  Wonderfully done.Users/OliviaY

20100307 21:23:18 nbsp Its times like these when I wish that the Wiki had the equivalent of Facebooks like button.

Very well said. Users/IDoNotExist

20100307 21:30:30 nbsp tl;dr Users/TomGarberson

20100307 21:34:40 nbsp Thank you  I think most people wholeheartedly agree with you.  Users/MichellePalmer

20100307 21:37:03 nbsp Hahaha Users/IDoNotExist

20100307 21:42:29 nbsp I agree wholeheartedly. Users/MattBlair

20100307 21:51:58 nbsp excellent.  Users/ARWENNHOLD

20100307 22:22:00 nbsp OK Stayed away from this a bit as I was not personally involved and am still conflicted on my thoughts on all of this but this critique was too obvious to avoid.

Oh, and when people who are protesting the graffiti on the LGBT center spray paint crap on other school buildings, you know theres something wrong. Seriously.

There is a MAJOR difference between homophobic hate being written on a wall and criticism of the university. Do you really think they were mad about having to paint something over? Im not even defending their graffiti here but your missing the point of what happened. Seriously.
 Users/CraigFergus
  Both involved expressing a feeling in a vandalizing manner. Sure, one of the feelings is more agreeable to some, but that does not make it any less of a crime. Users/hankim
   No, its like if I put a big sign that said DO Something! in the chiefs lawn to protest the burning cross I found in mineCF
      Ignoring the fact that a burning cross can do more damage to a property than a sign, I tend to respect peoples right to hate as long as they do not infringe on anyones rights, like the graffiti people did (although I still think its the work of teenagers acting stupidly than people with actual malice). Users/hankim
  Yeah, youre right, theres a big difference.  Sorry, I could have addressed that point better.  I just meant to highlight the irony that in protesting hatred that manifested as graffiti they resorted to graffiti. I didnt mean to make it sound like I thought they were protesting the graffiti itself.  Users/TomGarberson
Note: the this thread of comments refers to the original version of the text which I have since corrected.  CraigFergus correctly points out that the use of spray paint graffiti wasnt the grounds for protesting; rather, it was the message contained therein.  You can check out the phrasing he critiqued http://daviswiki.org/March_4,_2010_Public_Education_protest/Criticism?actiondiff&version221&version120 here.  My apologies for the implication. tg

20100307 23:33:08 nbsp As you probably would gather from what Ive written concerning the protest so far, I agree with almost everything youve said.  One exception: I agree with Craig that the issue with the LGBT center has everything to do with the message and nothing to do with graffiti.  They could have written it in chalk and it would still be offensive.  The other exception:  Im really pleased to see students take charge of their own destiny like this, even if it was a bit counterproductive.  For years I taught students who were sure that they couldnt make a difference about anything  that life in general and politics in particular was just something that happened to them.  So to see students who think they can make a difference makes me smile.  Theres hope for this generation. Ok, sorry, one more  I think the administration could be making a better case to Sacramento, and to the public at large, than they have been.  We need to explain why the UC/CSU is so important to California, since people seem to have forgotten.  So, protest to Sac, yes, but I think its relevant to protest locally, too.  (Just in a different manner).  Users/CovertProfessor

20100308 12:40:03 nbsp Im all for protesting and disruption. For the last few years, as Ive learned more about them, Ive looked up to people like Gandhi and Dr. King for their abilities to bring about major change through nonviolent means. As a rule, though, I tend to think that a protest should be either peaceful, symbolic, or both. Yesterdays was neither, and there were parts of it that were more contradictory than anything.

First, there was no clear message for the protests. A lot of people I talked to, and myself included, thought the protest was all about the budget cuts and the inefficiency of the California Legislature and the UC Regents to provide enough funds for education. People I talked to that were part of the protest included the recent acts of hate and vandalismswastikas found around campus, the hate speech vandalizing the LGBT centeras reason for protesting. If you dont send a clear message, what can you accomplish? The purpose of a protest should be to get a message across to bring about change, and if no one knows what that message is, it simply looks like unbridled rage. Not only was there not a clear message, there were clear contradictions to the message I believe they were trying to send.

Its one thing to create disruptions and disturbances, to encourage students to come out of the classroom and join you. But to protest your right to an education and then pull fire alarms, literally depriving people of the option to stay in or attend their classes, actually takes away that right from your fellow students. The fact that there was no planning or organization with the fire alarmsif students were smart, they wouldve had people in every building pulling an alarm at the same time to shut down the ENTIRE campusmakes it look like they were impassioned students doing whatever they felt might be a good idea at the time, with no leadership or organization. Similarly, attempts to block buses that primarily serve students getting to campus to claim their right to an education sends a contradictory message, and even prevents students from getting to campus to protest.

Second, there was no clear leadership. A couple of people have told me there were a few people that did a lot of planning for this protest, but Im willing to bet that no one knew who was in charge. They could point to a person with a microphone or a megaphone if they wanted, but no one knew the names of a single person (excluding Laura, who was arrested and then released) that had done any planning for the protest. Its so easy to pick up a microphone or megaphone and shout something inflammatory and enrage the students enough to do something like plan to take a freeway. But if no one knows whos ACTUALLY in charge, whats to prevent anyone from pitching an idea and having the entire crowd follow? In that case, all of the planning goes out the window, and it again looks like impassioned rage.

Once the protesters stopped pulling fire alarms and blocking busesthings at least related to their goals, however convoluted the message wasthey decided to march to the freeway. I simply cant understand this. There was no symbolism in shutting down the freeway, nor any real common sense. Who would be the first person to step on? As I read Twitter updates from a California Aggie Reporter who was on scene and posting every few minutes or so, I realized that students were actually pushing against police lines and barriers. The decision to take the freeway probably made them more enemies than friendsanyone who had to sit in traffic, anyone who saw it on the news that saw it as a bunch of pissy students trying to do something ridiculous because they were angryand a lot of students Ive talked to dont understand how it made any sense, either. People argue that it would get media attention: it did. The media will give you about two minutes of time, but after that, the story is forgotten. It also detracted from what went on in Sacramento yesterday, which is where I feel the real energy and attention should have been devoted.

I support protesting, but you need to have a plan, a goal, and a clear message. Some symbolism would be nice, too. I also believe the most successful protests have defined leaders who can control the passions of their fellow protesters and prevent it from turning into a mob. The only thing that impressed me about yesterday was that the protesters left the intersection of Anderson and Russell voluntarily, without being asked. Its important to take the anger out of a protest. Passion is one thing, but anger clouds reason, and people dont respond well to it. A protest should be a positive thing to bring about positive changeand yesterday was none of those things. Users/AaronSamson
  Thanks for your comments.  I find them thoughtful and helpful.   Users/CovertProfessor
  Yes, thank you for the great insights!  While I still have some disagreements with the specifics (fire alarms, in particular, for reasons discussed elsewhere by OliviaY and others), what you describe could have easily solved many of the problems I have with what went on on Thursday.  You described the sort of protest that by and large could be both beneficial and respectful.  Sadly, Ive come to expect something far from that benchmark from student protesters the vast majority of the time. Users/TomGarberson

  Still dont agree with the fire alarm pulling, same as you. Meant to say that even though I disagree with it, it would at least make more sense if it looked like there were SOME kind of plan instead of just a person randomly pulling them. Even if they had people stationed outside with important things to say (instead of just shouting Join us!) it would have looked less like a bunch of pissant students. But firealarm pulling in general, I feel is the wrong way to go about things.Users/AaronSamson

20100308 23:06:23 nbsp You may wish to read http://www.davisvanguard.org/index.php?optioncom_content&viewarticle&id3290:commentarythekidsarealrightandcivilizationwillsurvive&Itemid118 David Greenwalds very interesting & supportive take on the protest. Users/CovertProfessor
  His comment about protesters not needing to draw up solutions and only needing to bring attention to an issue bothers me. If there is a problem that people cannot create a logical solution to, then theres no use protesting it and the best thing to do is push on to the best of ones abilities. If there are logical solutions, then the protesters should be able to provide them and argue for them. Otherwise, that is just begging for an unruly mob without any actual logic driving them. And many people have been going through this depression with major inconveniences, but not all of us feel the need to have other people come to our aid at their expense. Californias large number of regulations and taxes during an economic slump have chased major companies away, leaving people laid off and with bigger issues than whether some stranger gets access to affordable college education. Keeping these people from going home after a long day jobsearching or working for reduced pay because one believes that he or she deserves a college education is ridiculous. Furthermore, taxing these companies (like some have suggested) more will chase them further away and that will mean even less tax payers to fund California. Users/hankim

   The lack of regulation at the national level, particularly with respect to the financial sector, was what drove us into a near depression in the first place.  As for the corporate tax base, lets look at where Californias taxes come from with respect to corporate taxes.  Californias major industries are:
    1) Defense  very highly funded since 2001.  Cutbacks from not wanting to continue an incredibly unpopular war have reduced funding for this industry, but not by a lot.  Regulation didnt cause any of the major defense contractors to leave California.  In fact, they all have major facilities in the state, especially around military bases.
    2) Entertainment  movies have gotten very expensive of late, and in a deep recession, people dont want to spend $10$15 per person to take their family out to a movie, especially when they can see another movie using cable or netflix.  On the other hand, this didnt stop Avatar...  The movie industry is not suffering from heavy regulation.
    3) Agriculture  people buy food regardless of whether there is a recession, although they may move to lower priced items.  Farmland cant move out of state, even if regulated.
    4) Technology (computers)  this one got hit very hard by the recession.  Computer and software companies sell their products to consumers, who havent been buying much of anything, and to businesses, who have been holding off on taking on new capital expenses because of the recession.  Its not regulation  its the economy.
    5) Biotech  These do long term R&D, with investments closing in on a billion dollars per drug.  They didnt go anywhere.  In fact, this is a thriving industry.
    6) Clean tech  this one is booming, because of increased environmental regulation.  The need to buy energy efficient and clean technologies has spawned a huge new industry.  This is where all the VCs are putting their money these days.
    7) Education  The universities arent leaving CA.  They cant.  But budget cutbacks have done dramatic damage to CAs education system.
    8) Automotive  Traditional automakers have had terrible problems because of the recession.  GM and Toyota closed their NUMMI plant, not because of regulation, but because GM could no longer afford to prop up Pontiac, which manufactured the Vibe at that plant (it was nearly identical to the Corolla).  But we have two new automakers  Tesla and Aptera, which have based themselves here because of CAs stricter environmental regulations.  They are developing and selling extremely energy efficient cars.  In fact, CAs regulations have been largely responsible for the commercialization of hybrid and electric vehicle technology.
    So CAs regulations were not responsible for its economic problems, but some of its regulations were responsible for helping its economy!  Users/IDoNotExist
        Education does not generate profit, so you really cannot consider it an industry. The only reason why clean technology in California is even starting is because tax dollars are being spent there and not because it is at all a profitable industry. Farmers can move out of the state, and most of the time, imported food is cheaper (sometimes even with subsidies) so that would just drive remaining farmers out of business in California. The cause of the depression would be opening up a whole new can of worms. Users/hankim
          Seriously?  Check out how many billions of dollars universities generate by licensing their research to industry.  Or how many major companies have been spun directly out of university research projects.  At Stanford, one department alone spun off Google, Sun, SGI, and one or two others that I cant think of on the moment on its own!  UCD alone employs thousands of faculty, staff, and students, and many companies depend on its research for their existence.  Clean tech, like many other industries, requires some initial government funding to get started in order to allow its costs to come down to competitive levels.  This would be less necessary if the government did not already subsidize dirty forms of energy (for example, by spending a trillion dollars protecting our oil supplies in the past decade).  (An article in todays NY Times at http://www.nytimes.com/2010/03/09/business/energyenvironment/09solar.html?reftechnology goes into that for other countries.)  Farmers cant just move out of the state.  Its very hard to move a farm.  Youd have to buy farm land elsewhere, and if everyone did that, there would be lots of cheap farm land available here for other people to buy.  The cause of the depression is deeply intertwined with why CA (and every other state) suddenly had massive budget problems when the depression started.   Users/IDoNotExist
           With all those billions, you would think universities would be more financially stable. By the money spent protecting our oil supplies, do you mean the Iraq war? Because ironically, American oil companies did not get any contracts with the new Iraqi government. Also, even with very efficient technology, solar and wind power (which tax money is being thrown at) can barely handle base loads of most cities. Most of the time, more of an environmental impact is created building and maintaining these plants than using coal for energy. If we really want clean energy, nuclear is the way to go, but of course, people have quite a few preconceptions about nuclear plants. And I guess the farmers who are unable to move out of California will just be unable to compete with cheaper goods elsewhere and will just have to go out of business then. Users/hankim
           Ill tell you what.  Take any company, no matter how profitable.  Now remove its major source of income or positive cash flow.  Watch what happens to the finances of the company.  Most of the money from licensing technology goes directly into the states economy, not to the university.  Yup.  I mean the Iraq war.  Do you really think wed have gone in there if Iraq had no oil?  I agree that nuclear would be a great solution.  I dont think that the farmers will be going out of business any time soon somehow.  In any case, I dont see how any of this means that Californias regulations have caused its economic problems.   Users/IDoNotExist
            If we really want clean energy, nuclear is the way to go < this. Users/TomGarberson (P.S. dont you think this is getting a little far afield?)
             Sorry, I just wanted to address his points and I tried to not get too far off by going into the cause of the depression but it went there anyway. Users/hankim
   Han, youre doing it again.  Youre making it sound as though its all about individual students complaining about not getting their education while this economy is hard for everyone.  Then when I point out how important affordable higher education has been for California, and how the current situation is hurting the state (making it a less attractive place to move to, giving us less of a brain pool to draw from, giving us an unfair system where deserving people cant be educated because of their economic situation), you say you agree with me.  If you really do agree with me, then please stop misrepresenting the issues at stake!   Users/CovertProfessor
    If by current situation you mean the protests, I agree with you. Where we disagree I believe is that I think the current UC system is unsustainable and costly to the state. And I was arguing against what Greenwald said about too many people going through this depression without inconveniences and that he believed we needed more disruptions. Users/hankim
  Just to clarify, these were the parts of Greenwalds essay that caught my eye especially:  Maybe what people really need is to have their daily routines disrupted.  I talked to a lot of students out there last week and hope to talk to more this week.  The impact of fee cuts is devastating.  There are many students who just cannot afford an education anymore.  There are many people who are no longer on campus to speak out. I am tired of reading about students whining that their classes were disrupted or that they could not get home, at least they still have an education.  There is a bigger picture out there and if the only thing that some had to sacrifice was a few hours of class or an inconvenience getting home, it is a small thing. First, there is the irony of Greenwald saying that the students were whining about having their classes cut, while others have said that it was the protesters who were whining.  Perhaps we should just stop saying that others are whining and actually listen to what they are saying.  Second  and more importantly  I think Greenwald points out something that has been overlooked, at least in our wiki discussion.  The protesters (whether they realize or not) arent just protesting for themselves.  They are protesting for people who want to be students right now, but who cant afford it, as well as for future prospective students who similarly wont be able to afford it.  So, perhaps (and I think this is open for discussion) asking people to miss classes for a day or two isnt such a sacrifice; indeed, it is asking a sacrifice from those who are already privileged for those who are not privileged.  Again, I am not sure that I agree with Greenwald, only that I find his take interesting.   Users/CovertProfessor

20100309 01:27:31 nbsp A lot of people complain about how the protests had nothing to do with anything that could help things out. Consider the following excerpt from a booklet put out by some people at Santa Cruz

{{{Everything is set up in advance to ensure that nothing actually changes.
We are given options for managing the crisis and options for fighting the
cuts. We attend interminable meetings and plan symbolic actions. These
things change nothing. The problem is simple: no decision making body
has the power to give us what we want—especially during a crisis. The
deans and chancellors making the cuts are subordinate to the UC presi
dent. The UC president is subordinate to the Board of Regents. The Board
of Regents gets its funding from the legislature. And the hands of the leg
islature are tied by the the California constitution, which requires a two
thirds majority to raise taxes.

We must reject all options on offer and demonstrate that without negotia
tions, it is still possible to act. That is why we do not make demands. All
demands assume the existence of a power capable of conceding them.
We know this power does not exist. Why go through the motions of ne
gotiating when we know we will not win anything but paltry concessions?
Better to reveal the nature of the situation: there is no power to which we
can appeal except that which we have found in one another.}}}

http://theimaginarycommittee.files.wordpress.com/2009/11/occupationguide.pdf Source Users/WilliamLewis
  Thats just.... dumb.  Personally, I think its fine to complain about the problems without having all of the solutions.  After all, we elect people to solve these problems for us; a peaceable protest says Hey, you!  Fix this!!  And I am optimistic enough to think that these problems are fixable.  (Heres one option: http://democrats.assembly.ca.gov/members/a20/pdf/AB656factsheet.pdf AB 656, which would generate funding for the UC, the CSU, and the community colleges by enacting a new tax on oil and natural gas severed from California land or water; we are the only oilproducing state in the nation that lacks an oil/natural gas severance tax).  To protest without thinking the problems are fixable... yeah, I dont get that.   Users/CovertProfessor

20100309 08:09:19 nbsp In other words, Graaaaaaah!  Annnngggrrrryyyy!

I stand by my criticism. Users/TomGarberson
