
Dahlak Brathwaite is a recent UC Davis graduate and budding artist who has appeared twice on Russell Simmons Def Poetry Jam. He has performed numerous times in Davis at venues including Freeborn Hall, the Wright Hall Mainstage, 194 Chem, Silo Pub and Cafe, and Central Park. He has appeared at these performance sites with iLLLiteracy as well as with his backing band, the HiLifes.

With iLLLiteracy and Marc Bamuthi Joseph, he has toured the world, including Europe and Africa.  His first album, Dual Consciousness reached number two in category?.  He has appeared with Lauryn Hill, Mos Def, Talib Kweli, Common, Last Poets, KRSOne, Afrika Bambataa, and Saul Williams.

As an artist who works with poetry, hiphop, and theater, his performance for HBOS Def Poetry Jam in 2005 had three standing ovations, earning him a spot in the 2006 season.

As an actor in Davis, Dahlak has appeared on the stage of Wyatt Pavilion in The Island (2006) and in one of 2005s ThirdEye Theatre Festival plays, Language Barrier.

At a 2007 concert on the UC Davis campus, Dahlak had trouble organizing his concert due to requirements placed by the University, and Aggie Hosts in particular. They required tickets for a free event, later turning away all the people without tickets that had stood in line for over an hour despite the fact the building was far under capacity. Additionally, some people were patted down while others were not. He was so dissatisfied with the treatment of his fans that eventually he http://media.www.californiaaggie.com/media/storage/paper981/news/2007/05/30/CampusNews/HipHop.Concert.Cancelled.Due.To.miscommunication2910125.shtml cancelled the show. This resulted in http://media.www.californiaaggie.com/media/storage/paper981/news/2007/06/04/CampusNews/Asucd.Senate.Encounters.Controversy.In.Final.Meeting2911359.shtml lots of people calling the Aggie Hosts racist at a ASUCD Senate meeting. In response the ASUCD Senate passed a resolution calling for the creation of a uniform performance policy.
