## This page gets included in the larger Dancing page.

These Dance Studios offer Dance Classes and training in Dancing


  Applegate Dance Studio
  Blueprint Dance Company
  Aalim Middle Eastern Dance is a new Middle Eastern dance academy that is originally from London, then St. Louis and now right here in Davis. It teaches the various cabaret styles of Raks Sharki/ Oriental dance #bellydance# as well as folkloric styles from many different countries. Classes are taught by Lili who has 10 years of performing experience in St. Louis, MO as well as San Juan, PR as well as 4 years of teaching experience with Aalim Dance Co. Classes are for all ages, shapes and sizes and are meant for both total beginners and those that have already had some experience with bellydance. Classes are held independently at Barbaras Dancing Tonight Studio on Sundays from 8:309:30pm. Classes cost 6 for $50 #$8.33/ class# or a dropin rate of $10/ class. Private lessons also available. You can contact LILI at lilibellydance@yahoo.com.

  DAVIS STAGES Where Ideas Move Jazz  Tap   Ballet  Children Classes to Adult  All Levels Welcomed! Visit http://www.stagesdancestudio.com/ STAGES or Like us on Facebook to unlock the possibilities! http://www.stagesdancestudio.com/ Stages Dance Studio

  Dance Baby Dance
  The Davis International Folk Dancers is an underground remnant of the 1950s and 60s folk dance movement where dances from Bulgaria, Israel, Greece, Armenia, and other countries with strange and wonderful dance traditions are given new life.  The leaders of the group teach a class most Sunday evenings at the Davis Art Center, 7pm to 10pm, with all requests during the last hour.  The dances range from simple to complex, from exotic to more popular.  The members also make appearances at other locations and times for specific types of dance, such as Davis Israeli Dancing and Balkan folk dancing.
  Fiesta DanceN Fitness also known as FDF, is a dance studio, fitness gyms gym, holistic health club and multicultural arts center. It is a space where students and instructors can come together to share common interests in promoting complete health, developing physical fitness, sharing music, studying international dance, and appreciating cultural diversity. Fiesta Dance N’ Fitness; mission is to encourage fun fitness for overall wellbeing, and to also promote respect for other cultures through World Arts Education. Check the online schedule http://fdfcenter.com/fdfschedule.php for updates on classes, workshops and seminars.
  wiki:westsac:Spotlight Dance & Fitness  A ballroom, latin, and swing dance studio in West Sacramento.  About a 10 minute drive from Davis, with a very friendly and supportive group of students and staff.  The instructors here are all professional dancers and instructors, so whether you are a complete beginner, or a seasoned veteran, you are sure to get a quality dance education at Spotlight.  Many Davisites and UCD students take classes here.
  Pamela Trokanski Dance Workshop and Performing Arts Center offers a variety of classes, including  Modern/Contemporary, Ballet, Pointe, Jazz, Hip Hop, Dance Team, Belly Dance, Fire Dance, Zumba, and Classes for children ages 46, and more. It is the school for the Pamela Trokanski Dance Theatre. The experienced, thirteen member, faculty brings both breadth and depth to a dancers training. In addition to ongoing technique classes, the Dance Workshop also offers a wide range of summer dance intensives. For more information, visit our web site at http://www.trokanski.com.
