## This page gets included into the larger Dancing page

These are Dancing Dance Classes in Davis. Some are held at Dance Studios and others at a variety of other locations.

  Dance troupe Kanz alSahara is teaching belly dance classes at the Davis Arts Center Summer 2014 on Wednesdays 6:308:00pm https://kanzalsahara.squarespace.com/events/ Link for more info

  Aalim Middle Eastern Dance is a new Middle Eastern dance academy that is originally from London, then St. Louis and now right here in Davis. It teaches the various cabaret styles of Raks Sharki/ Oriental dance (bellydance) as well as folkloric styles from many different countries. Classes are taught by Lili who has 10 years of performing experience in St. Louis, MO as well as San Juan, PR as well as 4 years of teaching experience with Aalim Dance Co. Classes are for all ages, shapes and sizes and are meant for both total beginners and those that have already had some experience with bellydance. Classes are held independently at Barbaras Dancing Tonight Studio on Sundays from 8:309:30pm. Classes cost 6 for $50 ($8.33/ class) or a dropin rate of $10/ class. Private lessons also available. You can contact LILI at lilibellydance@yahoo.com. THIS EMAIL DOESNT WORK, PLEASE POST A WORKING ADDRESS, I TRIED TO CONTACT YOU :)
  Argentine Tango with Miguel TaillantMiguel Taillant, a native of Argentina, has been teaching tango for over 35 years.  Classes Spring 2013 quarter are at South Silo on Sundays from 3 to 5 pm.  Contact tangobravo2k@yahoo.com if you have any questions.
  Barbaras Dancing Tonight teaches a variety of dance styles from hip hop to swing and ballroom. Barbara usually offers a few of her more popular introductory courses at a very low rate through http://www.city.davis.ca.us/pcs Davis Parks & Community Services. This is a good way to find out if you like her style as well as a particular dance style; Barbara also employs other instructors who specialize in different dance styles. If you choose to sign up for classes through the dance studio, you can purchase these on a dropin basis for greater flexibility.

  Davis STAGES offers jazz, tap, and ballet for children and adults  All Levels Welcomed! http://www.davisstages.com/ Stages Dance Studio

  The Davis International Folk Dancers is an underground remnant of the 1950s and 60s folk dance movement where dances from Bulgaria, Israel, Greece, Armenia, and other countries with strange and wonderful dance traditions are given new life.  The leaders of the group teach a class most Sunday evenings at the Davis Art Center, 7pm to 10pm, with all requests during the last hour.  The dances range from simple to complex, from exotic to more popular.  The members also make appearances at other locations and times for specific types of dance, such as Davis Israeli Dancing and Balkan folk dancing.
 Davis Israeli Dancing is for dancers of all ages and all levels of experience.  Open to the public, Davis Israeli Dancing is held on the first and third Thursday of the month from 7 to 9 pm at Congregation Bet Haverim social hall.
  Davis Swing Dancers
  The International House Davis offers Salsa classes every Monday evening from 7:30 pm to 8:30 pm, taught by Carlos Whyles, as well as Tango classes every Tuesday evening from 6 pm to 7:30 pm, taught by Damien Kima.  Classes are free for IHouse members or $10 per class to drop in.  IHouse also hosts occasional one evening dance workshops, see their http://www.internationalhousedavis.org/newsevents/calendar2/ calendar for upcoming events.
  The International Social Dance Club is a new student organization that will be starting up in Fall 2008.  Like the Davis International Folk Dancers they will do a wide variety of dances from around the world, but with a greater emphasis on western European partner dances (waltz, polka etc.) and more regular teaching.  The club meets Wednesday nights from 810 in the ARC Pavilion. When you enter the Pavilion from the ARC side, follow the signs to the club.
  Spotlight Dance & Fitness  A ballroom, latin, and swing dance studio in West Sacramento.  About a 10 minute drive from Davis, with a very friendly and supportive group of students and staff.  The instructors here are all professional dancers and instructors, so whether you are a complete beginner, or a seasoned veteran, you are sure to get a quality dance education at Spotlight.  Many Davisites and UCD students take classes here.
  Parks & Community Services Department Davis Parks & Community Services offers dance courses through their http://www.city.davis.ca.us/pcs/download/ Recreation Program. These classes are very reasonably priced, and instruction is typically by professional dance instructors.
  Popping Club @ UC Davis teaches popping, a funk style, at the ARC Pavilion or ARC Dance Studio four days a week (Monday  Thursday) and is open to all skill levels. Check the official website calendar for more information regarding lessons and open sessions.
  The Sacramento Country Dancing Society puts on a Contra Dance every 3rd Friday at the Davis High School Dance Room from 811pm with a beginners workshop at 7:30pm. The cost is $5 for students and $10 for adults, with a maximum of $25 per family.
 Experimental College regularly offers a variety of dance styles at reasonable prices, including salsa, capoeira, and sometimes samba. Be sure to check the EC Guide at the start of each quarter to find out when classes will be held.  In Spring 2010 Davis Ecstatic Dance is offered.
  The Graduate and many other dance clubs often offer a free 30 minute or hour long lesson with your cover charge before they begin spinning beats. This is particularly true of certain styles such as country line, swing, and salsa... youre not likely to get an intro to hip hop at any club!
  http://www.dynamicdancing.com Dynamic Dancing with Yvette  Yvette teaches a variety of dance styles including: Jazz, Ballet, Tap, Musical Theatre, Hip Hop and Bellydance. Classes are taught at three Davis locations and in Woodland.
  Irish Dancing is taught at the Davis Art Center for kids, teens, and adults of various skill and energy levels.
  Pamela Trokanski Dance Workshop and Performing Arts Center offers a variety of classes, including  Modern/Contemporary, Ballet, Pointe, Jazz, Hip Hop, Dance Team, Belly Dance (both Traditional Cabaret Style and American Fusion Style,) Fire Dance, Cheer Dance, Zumba, Dance Improvisation and Body Conditioning Classes for Dancers. The Dance Workshop also runs FREE Dance for Parkinsons classes, which are classes specifically geared for people with Parkinsons Disease. During the summer, the Dance Workshop also offers a wide range of week long dance camps and intensives ranging from dance camps that offer younger dancers an experience with multiple dance forms to intensives that focus on technique, repertory, and performance, both live and for DVD audition choreography. It is the school for the Pamela Trokanski Dance Theatre. The experienced, thirteen member, faculty brings both breadth and depth to a dancers training. Visit our web site at http://www.trokanski.com.
  The ARC is now offering all sorts of dance classes, from Ballroom and Salsa to Bellydancing and Ballet.  They are offered each quarter and are taught by a very knowledgeable group of instructors.  Check the quarterly Recreation Guide (or the ARC website) for more information.
  Hanneke Lohse teaches allages ballet at the Davis Art Center six days a week, and her dance group performs at the Veterans Memorial Theatre twice a year.
