



The Davis Police Department (DPD) provides law enforcement for the town of Davis and investigates Crime crime. On the UC Davis campus police services are provided by UC Davis Police Department the campus police. Police Chief Chief Landy Black joined the department in April 2007. The department has the unenviable job of keeping the peace between long term residents and students in a college town.

The Davis Police Department building was built in the early 2000s and replaced the old Davis Police Department Building in Downtown. The Police Department previously occupied 226 F Street which is now Bistro 33. When the Police Department was located in downtown, police cars parked up and down F street was a common sight.

The Davis Police Department has had a long history of using the Ford Crown Victoria Police car going back into the 90s. The Ford Crown Victoria is known for its rear wheel drive, V8 engine, and good reliability record. The top speed has been recorded at over 150 miles per hour, however it is limited to about 129 miles per hour due to government limits. The Ford Crown Victoria was discontinued by Ford in 2011. Fords replacements for the Crown Vic are police cars based on the current Ford Taurus with much more powerful engines, suspensions, brakes, fourwheel drive, and bulletproof doors, etc. There are currently 2 other popular replacements for the Crown Vic. One is the Dodge Charger and the other is the Chevrolet Caprice. The Caprice is actually made by General Motors Australia division called Holden. The car is called the Holden Caprice in Australia. Caprices are not available for civilian use in the United States and therefore all new Caprices in the U.S. are police cars and can easily be spotted. The Dodge Charger police cars look just like civilian cars and the Taurus also looks much like a civilian Taurus sedan. The weakness of the Dodge Charger is that it is very common for the brakes to give out after several thousand miles necessitating expensive repairs.

The ACLU has challenged the Davis PD for their tactics used in an investigation regarding graffiti at Davis High School. This is an important case, one that brings up a lot of questions, and is very important to both the police department, and Davis citizens. http://davisvanguard.org/index.php?optioncom_content&viewarticle&id4618:freespeechandjournalisticshieldorhinderingapoliceinvestigation&catid54:lawenforcement&Itemid87 article.

The department is now in possession of a MineResistant AmbushProtected vehicle.  In general, a MRAP can provide cover to perform rescues of victims and potential victims during shooting incidents, and deliver officers into activeshooter incidents or barricaded hostage incidents.  The City Council and the Police Department are in active discussions about the vehicle. http://www.sacbee.com/2014/08/20/6642425/davisacquiresmineresistant.html

 Officers 

  John Neves Officer Neves  Often seen downtown on a bike.
  Lieutenant Tom Waltz  Badge number 51.
  Jesse Dacanay  Motorcycle Cop, Badge number 85.
  Josh Helton  Badge number 72.

 Services 
  They issue Residential Parking Permits and http://www.city.davis.ca.us/police/pdfs/forms/Noise_Permit_Application_and_Instructions.pdf sound permits
  They enforce laws including Noise Violation noise violations
  They offer both a ride along (with an officer) and a sit along (with a dispatcher) program
  While federal funding for the program lasted they provided free gun locks which could be used to lock your Guns gun or your Bicycles bicycle
  On January 24, 2006, the Davis Police Department website introduced https://www2.ci.davis.ca.us/police/crimereporting/ online crime reporting. You can report certain nonviolent crimes from the comfort of your own web browser, without having to visit the station and wait for an available officer.  There are also http://cityofdavis.org/police/log police logs online.
  There is a http://cityofdavis.org/police/patrol/davispolicecadetprogram.cfm Police Cadet program.
  A Vacation House Check program. Fill out the request form http://www.city.davis.ca.us/police/pdfs/forms/Vacation_House_Check_Request.pdf here and turn it in to the Desk Sgt. at the station.
  If your bike is in the City of Davis, and you have lost your bike keys or your bike lock is malfunctioning, they can come out and cut your lock. Proof of ownership is required, and this service is only provided during normal business hours.
  Martial Arts and Self Defense Low Cost Self Defense Classes for Women, Teens and Kids

 Daily crime reports 

The Police Department maintains an online http://cityofdavis.org/police/log/index.cfm Crime Activity log and a http://maps.cityofdavis.org/gis/crimemap/ crime map.  You can read about all the policerelated events each day.  Most are runaway children and loud parties, but some are much more serious, such as people driving their cars into bicyclists, pedestrians, and parked cars.

As of 20120416 I set up a http://www.packetcollision.com/davispd/ site to archive old crime activity logs, which should automatically download each days log and save it for as long as I have a server to host it on. It might be useful if anyone wants to read old reports.

 Police Community Relations 

The ASUCD StudentPolice Relations Committee tries to create sustained dialogues between UC Davis students and both police departments.  As part of the studentpolice relations work, the Davis Police Department answered a list of frequently asked student questions of the police  FAQ StudentPolice.  Prior to that, the CityUCD Student Liaison Commission had a PoliceStudent Relations SubCommittee to create dialogues between students and both police departments (operational from January 2006 to January 2007).

The Davis Police Community Advisory Board, created in January 2006 and made up of local residents, business owners, and other community leaders, is charged by the Chief of Police to assist in community outreach efforts.

In the spring of 2006 an unknown group or individual sent out C.A.R.O.L.E. flyers calling for a Police oversight commission.

 Racial profiling 
On http://www.sacbee.com/content/news/story/13489410p14330102c.html Aug 29, 2005, the Sacramento Bee reported that the Davis Human Relations Commission may call next month for a commission to investigate an alarming number of racial profiling complaints against the Davis PD. The department has one officer assigned fulltime to investigating racial offenses.
On May 23rd 2006 a large, mixed group of undergraduates, graduates, faculty and community members http://www.californiaaggie.com/media/storage/paper981/news/2006/05/24/CityNews/Students.Residents.March.To.Protest.Racial.Profiling2013607.shtml?norewrite200607310136&sourcedomainwww.californiaaggie.com marched on the police department to protest racial profiling and police misconduct. The march began on the MU Patio and ended at the police department.

From January 1^st^ to August 19^th^ 2005:
  Latinos, which make up 10% of the population, made up 20.5% of all arrests.
  Blacks, which make up 2.4% of the population, made up 9.2% of all arrests.

The UC Davis Concerned Campus Affiliates released their racial profiling report on November 15, 2005.  The report is available at http://www.policeracerelationsreport.net/  The Affiliates include Kristee Haggins, Donald Moore, Natacha Foo Kune, Fernando Socorro, Steven Baissa, John OrtizHudson, Carla Lacey, Renee Lopez and Michele Dyke, Jesse Owen, Paul Ratanasiripong, Rahim Reed and Karen Roth.

According to the Civilian Oversight Board to Strengthen and Improve the Davis Police Department, Davis Human Relations Commission, examples of racial profiling that have taken place in Davis include:

  In 2004, an African American college student was stopped twice within two weeks while driving on Davis streets late at night. The young driver was a Davis High School graduate and awardwinning community servant. On one occasion, the DPD officer made a Uturn and flipped on his lights before he could have seen the back of the driver’s car. He issued a fixit ticket for a tow ball (which helps a car tow other vehicles) obstructing the view of registration tags. On the other occasion, the young man was stopped on Russell boulevard for unclear reasons and the first words out of the DPD officer’s mouth were, “Is this car stolen?” The young man’s father called the President of Blacks for Effective Community Action, enraged and afraid for his son, whom he had raised as an upstanding young citizen in Davis.

  In 2005, the wife of a prominent Muslim community member was driving to pick him up from a meeting at the DPD station. The wife was stopped by a police officer for not having stopped completely at a stop sign. She was adamant to the officer and to her husband that she had stopped. When the community leader spoke to a high level police administrator, he was told, “That officer is going to retire next month. Let it go. Go to traffic school.”

(http://72.14.253.104/search?qcache:vj9jNAXz_YJ:www.city.davis.ca.us/meetings/councilpackets/20060221/11_Citizen_Review_Board.pdf+%22davis,+ca%22+arrests+race&hles&ctclnk&cd13&glus&clientfirefoxa link)
(http://www.city.davis.ca.us/meetings/councilpackets/20060221/11_Citizen_Review_Board.pdf pdf document of report

 Racial and Gender Makeup of the Davis Police Department 
Data taken from the Annual Data Sharing Meeting on March 2004. http://www.city.davis.ca.us/police/press/pdfs/HateCrimeinfoRevisedHRC030304a.pdf link to PDF
94 full time permanent employees
White ––69 (73%)
African American ––2 (2%)
Hispanic ––17 (18%)
Asian/Pacific Islander ––6 (6%)
Native American ––0 (0%)
Male ––58 (61.7%)Female ––36 (38.3%)

 Image 

Various people have different opinions about police enforcement no matter where you live.  Due to their strict enforcement of Davis famed Noise Violation noise laws, they are sometimes referred to as Professional Party Poopers.  However, the police department issues almost no minor in possession or distribution to minor citations for alcohol offenses.  Others point out that theirs is a thankless job, and that you cant make everybody happy at once, especially while enforcing laws that you didnt write. The DPD even went as far as producing Davis Police Department Trading Cards to boost their image. The DPD printed and distributed trading cards with interesting information about each officer.  Read about them in a Maxim article from April 2000 titled http://www.maximonline.com/stupid_fun/articles/article_3551.html To Serve and Collect.

 
As you can see, Davis police carry a special device that disrupts the speed of light, causing all pictures of them to become dubiously blurry...Except for this one:

Links
 Related information on the Wiki 
  How to survive police encounters
  What Should I Know If Im Arrested?
  Police Misconduct Stories
  Police Appreciation Stories
  California Aggie Aggie columnist Michael Giardina wrote an article about police officers, available http://www.californiaaggie.com/media/storage/paper981/news/2005/02/04/Features/Police.Ordinary.People1319448.shtml?norewrite200606071939&sourcedomainwww.californiaaggie.com here.

 Media 

http://www.davislifemagazine.com/Content.aspx?m5/1/2009&cId2905 Read about bicycle officer Pete Faeth in the May 09 issue of Davis Life Magazine.
http://www.sacbee.com/2010/05/13/2749544/davisbikecop.html?mi_rssPhoto%20Galleries Again, bicycle officer Pete Faeth featured in a photo series in the Sacramento Bee on 5/13/2010.

Working with the Sacramento Police Dept. and CHP on http://www.hulu.com/watch/223348/copsoddarrests3#playqueuedshowbyoriginal_premiere_dateasc COPS 03.13.11.
 External Links 

  http://ratemycop.com/index.php?stCA&dept13751 Rate My Cop rankings for the Davis PD

The Davis police played a crucial part in an episode of the TV show Cops around 2011. In one episode, there was a high speed chase down Interstate 80. The suspect was being followed by the Sacramento Police and the California Highway Patrol. The Davis Police Department laid out a spike strip on the freeway causing the suspects tires to blow out. This disabled the suspects car and allowed the police to apprehend the suspect and end the suspects dangerous freeway getaway.




20051109 12:38:56 nbsp While I was biking near a cop car the other day, I noticed that the gun in the front seat wasnt a standard shotgun, but what appeared to be some sort of asult rifle. Are Davis cops rolling with wiki:WikiPedia:M4_Carbine M4s Carbines? Users/ArlenAbraham

 SWAT team members opt to carry a rifle instead of the shotgun. Any other riflecertified officer may carry one also. Not all patrol officers carry them. They are also not M4s.  Anon
   Yes.  The DPD now has Carbines.  Someone broke in to a business downtown, I was there, and the cop got out of the car, and he had an M4 in the trunk.  There were a few other cops there with M4s with scopes and laser sights.  I think.  Users/JulienBiewerElstob
    However, unlike the weapon described in the abovelinked wikipedia article, DPD patrol carbines are not automatic weapons (machine guns).  They are semiautomatic.Users/CameronMenezes
     Not all of them have M4 carbines, but every patrol car is equipped with a shotgun. Anon.

20051109 13:32:42 nbsp A few months after the Sterling Riots, a fight broke out in the parking lot. It was broken up by a Davis police officer who got out of his car carrying what looked like and M4 and, strapped to his back, was a shotgun. My room mate noted that he wanted an AWP because the scene was too counterstrike to be real. Users/MichaelGiardina

20051125 01:35:15 nbsp Ive had my fair share of gripes about the police, but when I needed them the other night in an emergency, they were there in no time. It turned out to be alright, but they didnt mind rushing out at all and were very cool about it. Its good to know theyre there when you really do need them.  Users/DaveCar

20051208 15:56:09 nbsp If the police start carring m4s and mp5s  i am gona be more careful around them cause those things pack a punch Users/SeanReedy
  Yes, because you are impervious to their .45 sidearms...  Users/ArlenAbraham arlen
    Any sensible person buys the kevlar and helmet every round!  Users/KenjiYamada

20051208 18:11:34 nbsp I live in South Davis, and there is this one cop that is always turning on his siren....couple times a night every night.  Is that really called for? Users/DudeNude
  Sirens are turned on when police are rolling code 3 to an emergency call.  Code 3 means an officer is driving faster than normal, and cops only do this when rushing to an emergency.  Sirens are used to warn other motorists.  If sirens were not turned on, and a motorist collided with a cop rushing to an emergency, the police department would undoubtedly be sued for not providing sufficient warning that the police officer was driving fast.Users/CameronMenezes

20060101 21:29:20 nbsp Ive lived in the East Bay for about 20 years and always had a high opinion of the law enforcement officers in the various cities Ive in.  That said, I really dislike Davis cops.  And so do all of my friends.  They seem to have nothing better to do than hassle people over trivial issues.  Theres too many of them, they have no connection to community values, and they need to act like people instead of a team of misguided robocops.  Users/GrumpyoldGeek
   theres too many of them?  You sound like the same kind of person who would bitch if an officer didnt respond to your 911 call quickly enough, because there were too few officers working on the day/night you called in.  Concerning police officers connection to community values, just look at the extremely low crime rate in the city of Davis.  DPD Officers ENFORCE city community values, and help make this such a safe, great city.  Whens the last time you feared for your personal safety while walking down a Davis street?  Your statements sound foolish.Users/CameronMenezes
   I agree with Grumpyoldgeek  how many police officers does it take to make the community safe? I would feel just  as safe if there were half as many police officers. I grew up in a town, about one quarter the size of Davis, and we did not have a police force at all  the town was probably safer than Davis. There also seems to be a cultural problem within the group of officers hired by Davis, where acting out of control and being dishonest is accepted practice. Davis would benefit if the entire DPD was shut down and let the UCDPD perform all police work. Shift the culture to something better.
   I must disagree with you.  First and foremost: Please do not judge an entire department based on unproven allegations against a few officers. Second, you are an idiot if you think that the UCDPD could take care of all policing in the city of Davis.  The Davis PD is already swamped with calls on Thursday, Friday, and Saturday nights, as it is.  Your idea of the UC Police doing all police work in the city of Davis is not practical, and really, not very well thought out.
     Excellent idea.  As soon as the whole police department accepts responsibility and makes amends for the exchiefs and officer Lys behavior in the Halema Buzyan affair, Ill not judge the whole department on their behavior. Users/GrumpyoldGeek
     Why should anybody assume responsibility for what happened, when Officer Lys arrest of Halema Buzyan was entirely in compliance with applicable law?  Stop being so grumpy, Grumpy.Users/CameronMenezes

If the Davis PD were shut down to shift the culture, no longer would students have to deal with traffic cops.  Cops wouldnt be busting up parties anymore, and students could drink and/or smoke pot wherever they wanted to.  Sounding good so far?   How about this: Property crime rates would skyrocket, as well as personal crimes.  More people would be injured in traffic accidents, and there would be more pedestrian injuries at elementary, junior high, and high schools.  Gangs would get a foothold in Davis.  Still sounding good?  Your ideas are ridiculous.  Just out of curiosity, though: have you ever been on a police ridealong?  Going for a ridealong might further your education on the life of a police officer.  I encourage you to give it a try.Users/CameronMenezes

Right!  and if we were to leave Iraq the terrorists would immediately march into Davis and blow up the water towers. The Davis Police might have brain washed you into thinking the gangs are at the doorstep of Davis and they desire to destroy all civilization as we know it. The reality is that very little would change if the entire Davis Police Department decided to take a six month sabbatical.
There are many 90,000 person towns (Davis & UCD combined) with single police departments  having two police departments is inefficient. Obviously, the UCD police staff would have to grow in order to cover the entire city, but much of the administrative duplication could be eliminated. Davis would end up with a better managed police force and would also save money.SteveHayes
  As I said, ridealongs are both interesting and informative.  You are assuming quite a bit in your assertions, though your mention of Iraq and water towers is pretty funny.  I suppose well have to agree to disagree.   :)Users/CameronMenezes

20060519 18:28:44 nbsp I really like the police station a lot. It reminds me a great deal of the police stations seen in the game Earthbound. Users/SteveKent

20060607 21:27:06 nbsp The two traits that I have found most disturbing about Davis Police Officers are the lack of honesty and how they cover for each others mistakes. I will never believe another police report after my experience with Davis Police reports. There is no honor there, at all! Users/SteveHayes
   Care to share your problem with the Davis police?  Im curious what happened.  In the meantime, unless every single officer in the Department issued you a false citation, I think its best you limit your criticisms to the officers who wronged you, instead of denigrating the entire police force.Users/CameronMenezes
           You seem about the age of my sons, youll have to forgive me, are you Latino?  Your name looks like it, but you never know.  My sons grew up in Davis, and they were regularly questioned by the police as to where they were from or what they were doing walking around our neighbor as teenagers.  Not once were they given citations.  Im 55 years old, I have graying hair, and a few months ago I got pulled by the Davis PD and asked if I were a gang members.  I told the officer I used to march with Cesar Chavez and I asked him if he knew who that was.  He knew the name.  We had a good conversation.  I wasnt breaking any law.  I got no ticket.  I know countless stories of the same kind.  There is a problem here.  It started at the top, the lack of leadership by the police chief.  It started before that by getting rid of Police Chief Jerry Gonzalez.  Hell I lived here since the early 70s and there has always been a problem.  Rick Gonzalez, Jerrys brother, said the other day that when they started the Human Relations Commission in 1983, there was a problem.  It still hasnt been resolved.Henry Bianco
  I have dark skin and black hair, and yes, I am often mistaken for being Hispanic (I am not).  Ive lived in Davis for five years, and have never been treated poorly by any police officer.  Cops are on edge around ANY person that they dont know, and simply being respectful (Yes, sir.  No, sir) goes a long way in benefiting community/police relations. (And I dont mean to imply that you or your sons are/were impolite, thats not my intention at all) Every good cop is a bit suspicious by nature, and it is this suspicion that stops many crimes before they happen.  I was pulled over once in Davis, because my car matched the description of a car that had just burglarized an apartment complex.  The officer was a bit onguard with me, but I was very polite, and the officer let me go within two minutes.  Users/CameronMenezes
           Glad to hear that, I know a lot of people who have had bad experiences with the cops.  Most people of color either have a personal experience or know of someone who has.  A lot of my friends have moved out of here over the years because they grew tired of it.  My sons dont like to come back here that much, they feel safer in LA than they do here.  Thats a sad statement to make.  In meantime, according to my sources, there have been four new complaints filed in the last month, and two new pending lawsuits.  One involves a 20yearold Muslim kid, allegedly beaten by five Davis Police Officers.  If you live in South Davis and go to Safeway, youve probably met the kid.Henry Bianco
           Sorry to hear that, I know a lot of people who have had good experiences with cops.  Again, Ive found that mutual respect is a very useful tool to use when talking to police officers.  I have not heard anything about this alleged beating.  Just out of curiosity, what does the 20 yearold mans religion have to do with his alleged beating?  Why are you telling us that the man is a Muslim?  I am not sure why you included that in your response... are you trying to say that the man is darkskinned?  Correct me if Im wrong, but being a Muslim means you are a believer in the honorable religion of Islam.  There are believers of Islam in all corners of the world, who have many different colors of skin...  Users/CameronMenezes
   I love broadstroke allegations without a shred of supporting evidence  Users/DaveZavatson

20060614 20:12:20 nbsp Did anyone hear about the police chief resigning? Users/CindySperry
  Yes, Jim Hyde claimed that the Human Relations Commission was disrupting police work, but really it was because another department offered him a better salary.  Paul Amnuaypayoat
  Did Chief Hyde tell you this himself?  Paul, thats quite an assertion.  I dont doubt money has something to do with his resignation, but Im sure the activities of the HRC were also factored into his decision.Users/CameronMenezes
        Really Cameron?  Then can you explain why he applied for a position in several places over a year ago, before any of the HRC stuff occurred?  He was even offered a job at one point, but ended up turning that one down.  Word is that Hyde has been looking to a bigger pond since he got here.  The Antioch Job and pay raise gave him the excuse to do so.David Greenwald
         David, you are right!  The actions of the HRC and people of the same ilk had nothing at all to do with his decision!  Get real, man.  Many cops in other cities cringe at the idea of being a police officer in Davis, because the citizens of Davis treat their cops as if the officers themselves are the primary villains in this town.  I have never seen a more ungrateful citizenry in my entire life.  It is amazing that we have such quality police officers, considering the flak that Davis officers get just for doing their jobs.  Can you honestly blame Chief Hyde for throwing out his application to a few other agencies?  All police officers have to be constantly on guard for their own physical safety, but Davis police officers have to live with the additional fear of being fired/sued by people like you.  I respect your opinion, but boy, do I disagree with you.Users/CameronMenezes
            I must have missed the part where I said it had nothing to do with his decision.  But, I was pointing out to you that he was looking elsewhere before any of this came up.  Certainly, Hyde had to know that the council was considering getting rid of the HRC and its chair long before he resigned.  It was mentioned in early February.  So Hyde had to know that had he stayed on the HRC would not have been around, although his blame probably hastened the move, but I had been told in April that it was in the works for after the election.  So I dont buy the explanation.  I do take issue with your notion of ungrateful citizenryI think there are serious problems with the Davis Police Department.  In fact, there are 14 pending cases, many of which will become lawsuits and there are very serious allegations raised.  Davis Police Officers if they abide by the law and the constitution have nothing to fear.  When they cross the line, then it becomes a problem.  Unfortunately, some of the bad seeds in the department have tainted the good name of the majority of officers.  That has to and will be corrected.David Greenwald
             Fair enough, David.  Nor am I making the bold statement that all cops, everywhere, always abide by the rules.  By way of explanation, however I am appalled by the way some Davis citizens rush to judgement when issues arise concerning the conduct of police officers.Users/CameronMenezes
                          Must be pretty hard being a police office in Davis, having to be take verbal insults and all. I bet officers would rather be stationed in big cities with more violent crime and more guns on the streets. Cops have a tough, dangerous job. However, I am going to have to say its safer to be a cop in Davis then most major urban areas. There are good cops in Davis, but there also bad cops. And when there is no disciplinary actions taken against bad officers, when citizens feel their complaints are not being heard, when misconduct is rewarded like a remake of Catch22, something has to change. The city needs to get into a 12 step program to solve this issue... the first step is to admit there is a problem. Hell, I might even be happy if someone on the city council said they wanted to investigate the possibility of a problem....but that has yet to happen.  Users/JimSchwab
                         James, whats with the constant need to ridicule police officers?  Davis is probably a safer place to be a cop than in some other cities...duh.  Whats your point?  Are Davis cops not as important as cops in other cities?  I dont see where youre taking this.  This thread was about the police chiefs resignation, and your rant has little to do with that.  Youve mutated this thread into Jim Schwabs reasonswhyIhatedavisPD.  Issues?  Catch 22?  12step program?  What are you talking about?  Please be specific when throwing out allegations.Users/CameronMenezes

20060730 16:03:10 nbsp The DPD’s conduct in general is not appropriate for a small city like Davis, where most of the arrests are alcoholrelated, not hardened criminals.  DPD use excessive force and come the end of the month, they seem to pick you up for anything they can possibly muster up.  They have created a negative aura around downtown, and I fear for my safety because of the police when I go out to drink at the bars.  I spoke to the Sheriff at the Yolo Co. Detention Facility this morning, and last night 40 Davis students were picked up.  The night before one of my friends got arrested for attempting to break up a large fight near the bars.  My friend is huge, and surely intimidating, but was not instigating anything.  The DPD are hurting morale in Davis, when people become too scared to go out fearing runins with hardass cops.  This is not the proper environment for police actions that belong on an episode of Cops in Buttholeville, AL. Users/CamelJoe
  Camel Joe Your intimation that alcoholrelated crimes are not as bad as crimes committed by hardened criminals is a bit misguided, at best.  I went for a ridealong with a Davis police officer, and we were called to the scene of an accident a few blocks north of Fraternity Row.  A drunk, 19 year old UCD student crashed his car into someones house.  He could have killed people walking on the sidewalk, or even someone sitting in front of that house.  And what do you mean, how are we expected to get home from downtown if we cant drive?  Ever heard of walking?  Or better yet, drink responsibly so that your BAC is low enough to be legal.  Finally, Joe, the only time I EVER fear the police is when I know that Im somewhere/doing something that I shouldnt be.  (For example: when Im at a very late, loud party... when Im speeding in Davis... when I do a California stop... when I remain close to a bar where people are fighting.)  I suppose I disagree with everything you said, Joe, even the part about Buttholeville, Alabama.  I heard its a rather nice place.Users/CameronMenezes

      Cameron  I certainly didnt mean to say it was ok to drink and drive.  I meant that since we are under threat of arrest for drunk in public while WALKING home, there is a dilemma.Users/CamelJoe
       Look, dealing with cops requires that you have COMMON SENSE.  Dont do stupid things, dont talk smack to the officers, and a person will probably have a very brief (and pleasant) encounter with the police!  It is certainly not illegal to remain at loud parties, but if a person has a shred of common sense, said person will leave before the cops arrive to shut the party down.  When cops shut down parties, as we all know, it can  be fairly chill, or extremely tense.  Users/CameronMenezes
           We will have to agree to disagree.  You are right about the education thing, thats why I said this is not the case for all DPD.  There are good people there, too, Im sure.  Im just sick of the cowboy cops.Users/CamelJoe
            Cowboy cops?  Ive never seen their stetsons. Get a grip, dude. Try to remember that UCD students arent the only Davis residents.  Truth be told, Davis cops spend an inordinate amount of time preventing intoxicated college students from doing stupid things that hurt other people.Users/CameronMenezes
             Of course, UC Davis students are not immune to alcoholism and other dependency issues which keep the DPD very busy, especially on weekends. This does not mean that they are the only problem citizens in the downtown area face. I am personally proud of our police department for their handling of recent issues that have confronted our community. Hopefully, they will have continued vigilance.Paul Guess

20060730 16:24:45 nbsp CamelJoe: WTF?  Are you really saying that it should be OK to drink and drive? Users/GrahamFreeman
    You should bring your concerns to the attention of the UCD Student/City Liaison Commission.  I think they are actively engaged in addressing these issue.  Users/SharlaDaly

20061007 12:31:56 nbsp Gave me a ticket for not having my headlights on! What a freak!!!!! Users/ChiragPatel
   How absurd.  Clearly there is nothing wrong with driving with your lights off during darkness.  It isnt like it is a safety issue or anything.  DaveZavatson

20061114 22:43:40 nbsp What happened to the police logs? They changed it to unsearchable scanned pdf copies! Users/JohnWong

20061228 23:59:17 nbsp They dont seem to care or do much after you file a police report. Users/JohnWong

20070211 17:11:21 nbsp They give you tickets and dont even listen to your explanation. What happened to first time warnings?  Users/KiwiSelina
   So did you receive first time warnings in the past?  And now no longer are?  Doesnt that mean it isnt the first time any longer?   DaveZavatson

20070618 23:56:08 nbsp I dont mean to come off as rude or inconsiderate towards anyone, but Ive been feeling lately like the DPD have become bylaw enforcers, rather than law enforcers. Not intentionally or maliciously, necessarily. It seems the DPD spends alot of time and attention unnecessarily. This might be because they have to meet a certain quota, and there are too many officers to meet the quota on regular terms (thus racking up #s on bylaw charges instead of real crime), or because the davis residents themselves have become pampered and use the police for unnecessary and often absurd reasons (Ive seen some silly situations). Either way, i think the officers in Davis are just as much victims of the police system as those at the receiving end of the law. I dont mean to make anyone angry, I just thought Id share my views.  Users/KatieDavalos
  hey katie, your comment is good to have here. could you be more specific in the silly situations youve witnessed? xie xie ni, and i hope things are going well for you.Users/JessicaRockwell
  hey jessica!!! well, i was generally speaking about some of the absurd calls the police get as i read them in the Aggie, but if you want a personal account i was walking down Alvarado and listened in on a conversation between two police officers and a local home owner. the home owner was upset that his neighbors sprinklers watered his lawn. I of course dont know the specifics, but i remember chuckling because the police dispatch came on the radio and announced some code, and both officers turned around to listen to this serious radio message, clearly giving it more importance than the situation they were currently involved in. To me, that seems a little absurd, and Im sure other people have witnessed something similar. One quota example i can give is when i saw a UC police car parked in front of the BioSci parking garage flagging down every biker without a headlight on their bike and giving them each tickets. no one was given a first warning, and there were 10 bikes lined up at a time while their owners waited for tickets. Although they were violating the law, i really feel like this was unnecessary, and almost sneaky (waiting for violators in one spot, like fish in a net). But those are off the top of my head. I havent seen you in a while, hope everythings well for you as well!! Users/KatieDavalos

20070704 15:22:59 nbsp A ticket for not parking within 18 inches of the sidewalk as the last car in a row at the outskirts of town. Seriously? The parking zone has enough space for construction vehicles to park diagonally in. Who the hell has time to stop their car, get out of the car, look up the vehicle information, and write a ticket for not being 18 inches from the curb. Users/LiRic

20070806 12:52:33 nbsp I got a ticket for making a U turn on a dead end street, over by the spca he did not even want to give a warning just gave ticket and said have a nice day. If that is how cops are i want nothing to ever do with them that is mean and abuse of power in  my book and tons of other people books! Users/Brians

20070912 11:32:04 nbsp I have lived in Davis for a few years now, and none of my interactions with the Davis police have been positive. While they seem to be more into warning me then issuing me a ticket, they do detain or pull me and people I know over quite often and for bogus reasons (your third taillight is out, You were walking erratically and, my personal favorite, You are out pretty late.) The officers I have interacted with have been all male, patronizing, and threatening. I have started to request identification whenever I run into an officer. While I understand that they do work very hard to protect us from ourselves and our fellow men, some officers have proven themselves to be all too human. With guns.

I would like to know if there is some sort of citizen watch group for the actions of the officers. I know that there have been investigations, liaisons, and committees, but I would also like to see if there is interest in a group that will just serve to watch and make note of the Davis police forces actions, whether they pertain to race, gender, age, etc. Perhaps if they know we watch them just as they watch us, they will act more like civil servants.   Users/JillBenciWoodward

20071017 23:53:15 nbsp I got a ticket for going 35mph in a 30mph zone while it is dead empty (on the bridge on russell after exiting 113 S), on a dry condition, clear weather and perfectly safe. I thought the officer job is to enforce public SAFETY not to hand out ticket on every single chance they got. When is the last time they took a traffic survey anyway? I think most people go pass 35mph down russell now a days. And, correct me if Im wrong, but has anyone notice that the cop become very aggressive on certain days of the month? Anyone know when is the schedule for their Nonexistence Quota. But to be fair, I have encounter an officer who are dedicated to do their job right, which is to enforce public safety. He stopped me after making a rolling stop on a flashing red light at russell at around 3 am. And after he make sure I was not under the influence, he let me go. He told me that he is just looking for DUI. Users/UCD

20080208 11:29:13 nbsp Officer Ramos is gorgeous! Users/tgdavis

20080422 02:01:14 nbsp I live quite far (over near Mace/Chiles) from campus/downtown area, and I happen to enjoy walking, so Ill commonly stroll home.  Generally, its not a problem, but Ive noticed some extremely overzealous officers; for instance, coming home from the library around one am on a Wednesday evening I was stopped on THREE separate occasions by different officers.  Each of them questioned me, and one searched me.  While I recognize that the Davis Police do a very good job, honestly, if they have so many patrolling that they have nothing better that three of them will find the time to pull over clearly sober individuals walking in the evening, it kind of indicates that perhaps we have a few too many officers around; either that, or theyre mismanaging resources.

I do want to say that Officer Pineda happens to be an extremely friendly and considerate member of the police force. Users/TimCoady
 One AM is evening to you? What a nightowl. ;)  I took a quick look at the handydandy crime map (linked above)...looks like in that area there were eight burglaries/thefts in the last month. I wonder if they were trying to pay more attention to that area because of that...? I imagine most burglars are male, so a lone male walking that late at night might look suspicious. Users/DukeMcAdow

20080708 01:30:45 nbsp I have always felt that the police seem to get a bad rap from people who dont really appreciate the situations that police encounter on a regular basis. I also have never had any opportunity to experience the quality of our own police force first hand, besides one time when an officer gave me a fixit ticket for a broken headlight. Both of those being said, tonight I witnessed a police officer use their lights to get through an intersection that would otherwise have caused them to have to wait an interminable minute at most. While I still would like to give them the benefit of a doubt, this seems like an abuse of power. I can imagine that they might have needed to get somewhere with some haste, but the officer in question turned off their lights again as they drove off, which is not something that would happen if they were really in a legitimate hurry. I still support them, but this sort of behavior erodes the confidence of the lawabiding public. Users/JoePomidor

20081007 08:05:30 nbsp Ive had a few troubling experiences, 2 having to do with what I feel was racial profiling, however the incident that really took the cake was how the DPD handled my hitandrun. I stopped at the red light in front of IHOP and a bright yellow (with racing stripes, mind you) Acura slammed into the back of me and took off with a smoking car. We had a witness stop, a partial license plate number and seriously, it was a bright yellow car with racing stripes that was now smoking (and we saw it get right on I80). When the police officer finally made it out to us, he took our statement and pretty much said he wouldnt help us at all since he was off work in a 1/2 hr. He also said he wouldnt be sending anyone else out to look for the car either. Instead I got chewed out for having my parents name (and not mine) on the cars registration (I was on the insurance, of course). Way to go Davis PD.    Users/AmLin

20081108 11:06:08 nbsp I live in a South Davis apartment complex for disabled people and we have an ongoing problem with one of the tenants who sexually, verbally and physically harasses other tenants; peeks in the windows; bangs on the doors at all hours of the night yelling vicious, nasty things; violates the famed noise ordinance (constantly); steals (if he can find an open door) and in general makes us feel so threatened that we worry if we need to go out (say, to do laundry) after dark.  Keep in mind that he isnt in a wheel chair and most of us are, also, if you are a woman its even worse.  The Davis Police (not all, but most) simply dont have enough experience and/or disability awareness education.  They either seem to think that because we are disabled we are also nuts or they are afraid of possible ramifications if they take any action, so they dont do anything.  All of this aside, the poor man is simply not getting the help he so clearly needs.
After many, many months of this, with no police action, we finally convinced the landlords (based in Minnesota)to begin eviction proceedings.  We feel that if the police were doing their job he would be getting the help he needs instead of having to go through an eviction process. Users/KatyMartin

 The police department saw this post and came out to our complex to see how they could work with us to resolve this situation.  I do feel they have a thankless job and am amazed (and thankful) that they continue to choose to do it at all. Users/KatyMartin

20090313 18:56:05 nbsp I was riding my bike downtown, saw a police officer ahead of me just watching people stop at a four way stop sign, I approached the stop sign, came to a complete stop, and kept going but was asked to stop as soon as I passed the intersection. I was then questioned on how well my bike brakes worked and rudely lectured on how lucky I was to not get a ticket for running a stop sign because I stopped at the second white line and not the first one. I now understand that I have to stop at the first white line, but was telling me that I was lucky to not get a ticket for running a stop sign in a threatening voice really necessary when I told him I honestly didnt not know the law was the first white line? (how many people know that was the law for bikes anyway?) Not a big issue, but it still reflects on the nature of Davis Cops. Users/rocknice
   Perfectly legit on the officers part. Since you didnt know the rules, obviously they made the right call with stopping and educating you. You really ARE lucky they didnt ticket you. Bikes are vehicles and share the road, if you want to keep the privilege of at least having the right to be recognized or respected then you should follow the rules (at least when there are cops obviously watching you). You must follow all the rules that a car follows, stopping where cars must stop, yielding to pedestrians, etc. There are also other rules you must follow in addition to those: you must let faster traffic pass you when it is safe to do so (generally if you are going half the speed limit), you must ride as far right as it is safe to do so (if the lane is narrow, then the safest spot might be in the middle of the lane so nobody tries to pass you in the same lane or to avoid the door prize). If you went past the first line because you wanted a better view of cars who are waiting to the right or left of you, you should take the middle of the lane. You can see them, and they can see you easier as well. http://dmv.ca.gov/pubs/vctop/vc/tocd11c1a4.htm Users/KellyM


Downtown has turned into Bike School. While I realize this is Kelly Ms idea of the perfect town (see above) I was stunned 7/24/09 at being instantly double ticketed by Officer Faeth a) for allegedly not stopping at a stop sign (I didnt put my foot down) while b) wearing an iPod. A caution / some attempt to educate me would have been appreciated. The ticket alleges I went straight through the junction at 12 mph. After giving me the ticket Officer Faeth acknowledged hed watched a car reverse directly into my path  then shrugged there was nothing he could do about it.  Users/Biggins

  > An update 7/25/09: In response to complaints about cyclists infractions and data concerning the number of incidents in Davis in which bicycles are involved Davis Police instructed Officer Faeth to strictly enforce all cycling laws and to issue cyclists with as many tickets as possible, according to Davis PDs Captain Pytel. So long as the zero tolerance policy against cyclists is in force, Im going to be uncomfortable riding in downtown. Not quite what I had in mind living in the city of bikes.
 FYI, there is no law in California that requires you to put a foot down at a stop sign. To ride on the highways, you must be able to place one foot on the ground w/o dismounting (cvc 21201(c), so no tall bikes or pennyfarthings), but thats not the same thing. All that is required that you come to a stop, no matter how brief. If a cop indeed ticketed you for this, you need to challenge the ticket and report the issuing officer to his supervisor for retraining. wl
Thanks for that info wl. Regardless of the law, Davis PD seems to have independently decided that putting a foot to the ground is confirmation that youve really, REALLY stopped. Perhaps they could ask drivers to use their emergency brakes at stop signs to prove the same thing? Captain Pytel told me on the phone that as far as he is concerned whatever speed was written on the ticket doesnt matter so long as the officer testifies I was perceived to be moving forward. So much for truthful policing.

1/9/09: I have been bailed at a staggering $358. Because the alleged offenses happened when I was riding a bike, Im not allowed to attend Traffic School and reduce the bail to 60 bucks  only drivers are allowed this privilege. Ive asked for a trial.

Police Chief Landy Black denies the existence of the policy to write cyclists as many tickets as possible, but data from Davis PD shows that the number of tickets pinned on Davis cyclists doubled 20078 to a cool 1203 tickets. In that time Davis PD has at the very least doubled the police time for issuing tickets to cyclists, adding a police officer exclusively to the task, fulltime. Based on figures up to 08/2009 the rate of ticket issuing is still increasing  2000 tickets for Davis cyclists looks like a possibility for 20089, once the new academic year starts and many more people arrive downtown on bikes. Chief Black says that the fairness of this surge is a matter of perspective, while Captain Pytel denies it is linked to $$ revenue. However, on request Davis PD was unable to produce any evidence for the complaints about cyclists infractions which Captain Pytel says initiated the surge, and the data concerning the number of incidents in Davis in which bicycles are involved appears to be completely superficial. It doesnt correlate the number of incidents to the higher levels of bike use in Davis, and doesnt even indicate who is at fault in the incidents! Users/Biggins

Just a quick FYI. Traffic school is available for vehicle infractions that cause a point to go on the drivers record, the purpose is ultimately to remove the point. If the offense happened on a bike, there is no point to remove therefor traffic school is not allowed. Also traffic school doesnt reduce your bail amount, it actually increases the bail amount by around 66 bucks in addition to having to pay for traffic school separately. Users/R.W.
> Thanks for that R.W.

11/23/09: Sigh. Four months since the alleged offenses took place, bail check longsince cashed, Xmas coming and short of money, and I still dont have a judgment. Yolo Court say theyll look into whats gone wrong. And meantime, the whole rig I was riding  my bike and my daughters trailer  has been stolen (compare Mario M below). With such vigilant policing I can surely look forward to their return ...

12/10/09: The bike was found! By the police? Of course not. By a friend, who saw it being ridden in broad daylight on J St. I reported the recovery back to Davis PD in order to update the crime report, and out of curiosity asked whether the crime report had meantime actually prompted any action. ... with the competing priorities/cases, we simply just do not have the resources to assign someone to your case. Okay, so my misdemeanor wearing an iPod on my bike was assigned the fullest possible police resources; the felony of stealing the bike was assigned none at all. The traffic ticket incurred on the bike was sent over to Superior Court straightaway; the case number for the theft of the bike was left unprocessed. Asst Police Chief Pierce effectively blames me for this lapse, because even though I filled out the report in full, As for your case, the reality is that there seem to be few if any leads from the information I have seen in the report. Bizarrely, Asst Pierce writes this without asking anything at all about the recovery  where and when the bike was found, under what circumstances, or who was riding it at the time. So if Davis PD isnt interested Ill put it out here. A youth about 15 years old (with entourage) who, lets speculate here, may even be the thief, and who may well know the whereabouts of the other missing property listed on the report. He surrendered the bike because he didnt want any trouble, little knowing that hed be more likely to attract trouble from Davis PD if hed been wearing an iPod. At a stop sign. On a sunny day. Again, see Mario Ms conclusion below.

12/19/09: Just another quick FYI. Biking with an Ipod and running a stop sign are both infractions and the amount of police resources used to write a ticket for that are minimal at best. The stolen bike is probably a misdemeanor and not a felony, unless it was a really expensive bike then it may be a felony, but not a violent one. I am glad to hear you got your bike back, but try to see the other side of things. As a resident of Davis, and a taxpayer, I would rather see police resources being used on more important issues than stolen bikes. Bikes are stolen all the time in Davis and DPD and UCDPD no doubt recover a good deal of stolen bikes, but a stolen bike looks exactly like a regular bike so its really hard to spot them on the road and with limited resources the respective departments no doubt find it a better use of their time and money to go after more serious offenses that endanger public safety, and yes that does include riding a bike with headphones on. Again, I am glad you got your bike back, but try to be a bit fair with the criticism of the police department. R.W.

2/20/10 Hello again RW. Yes, I can be fair, but I cant be an apologist for Davis PD. Trespass at my home, theft of irreplaceable equipment and my daughters heartbreak (her bike never came back) are as serious to me, as a resident and taxpayer, as my wearing headphones is to you. To be honest, and with due respect to the legalese youre quoting, my sense is that most ordinary people think of trespass and theft as even more serious crimes than wearing headphones on a bicycle. Im afraid we have to share our law enforcement resources! Im curious why you endorse Davis PDs sentiment that bikes are stolen all the time in Davis as though thats a fact of life here like hot summers and allergies, when in fact were acknowledging that bike theft here is a chronic problem that will only get worse if its accorded zero priority. Instead were pretending that Davis CA is so beset by threats to public safety (like my wearing an iPod) that basic community policing is a thing of the past. Even if Davis polices according to whats cost effective (as opposed to what is legally mandated and morally right) then the city has to ask whether it can afford to pay fulltime police officers to follow cyclists around town looking for infractions. Or maybe youre right  the tickets are so cheap to write, so easy, and so lucrative, then lets ticket, baby, ticket  but thats pretty troubling isnt it. What about fairness or quality of life?

Finally, back to the basics of this sorry saga. Im not sure how I can break this to the judgeandjury folks who patrol this page, but its worth one last try  I didnt run a stop sign. Ill let you in on the end of the story. Davis PD decided not to contest the case and declined to fill in the sheet of paper stating their side. After 5 months in legal limbo, on bail at Woodland, the court threw out the case. I expected better from Davis PD and it troubles me that others dont.

It is not against the law to bike with an iPod.  In fact, if it were it should also be against the law to bike with a hands free device.  You may not have both ears covered/plugged.  So if you have headphones cocked so one ear is clear or only one ear bud it is not against the law.  Users/masonmurrayMM


20090812 01:14:46 nbsp After receiving two biketickets for not having my bike registered and another for crossing a red light, having my bike lock sawed through on a Tuesday afternoon in Down Town Davis and had my bike stolen in broad daylight, Ive come to the conclusion that the Davis PD is WORTHLESS. They patrol the wrong parts of the city and give bikers trouble instead of actually preventing crimes. However, I like the fact that if I ever need to find a police officer I can be assured to find one at the UMall, either at Starbucks or outside of AMPM(Arco gas station). Users/MarioM

> The red light ticket doesnt surprise me, but ticketed for not having your bike registered? Are you kidding? Very sorry to hear about your bike being stolen. Users/Biggins

20090902 12:21:36 nbsp As a frequent driver downtown, I appreciate when bikers stop at a stop sign. Most do not and it makes driving very frustrating when I have to slam on my brakes in the middle of an intersection because a clueless biker is speeding thru the stop sign. Maybe the tickets will aid bikers in remembering bike laws.  Users/EricaMacGregor

As a driver and cyclist downtown, Erica, I agree bikes  and cars (yes, including police cars) doing their usual aretheyarentthey rolling stops  should stop at stop signs. Since I stopped at the stop sign, what will the ticket aid me in remembering? Users/Biggins

20090902 19:50:07 nbsp FWIW most of the cops I ever see at the U Mall Starbucks are UCDPD.  Users/ARWENNHOLD
  Yes, the city of Davis ones seem to like the Starbucks on Covell better. Users/jsogul jo

20091125 12:56:22 nbsp who/which company designed the building exterior? I love it :)  Users/val
  Dont know, but we call it The Bowling Alley Users/JimStewart

20091128 19:16:52 nbsp Why is the online reporting form always down on the weekends/holidays?   Users/KsFair

20100103 13:27:29 nbsp I was just discussing this yesterday with my best friend and I gotta say... Id much rather deal with Davis cops at their worst than most other city cops at their best. Ive never personally had a problem and am of the belief that if you dont line yourself up for trouble you wont end up with it. Strictly speaking from personal experience, of course. Users/KBathory

20100122 11:49:45 nbsp I recently moved away from Davis, and I have to say that during my time actually living in Davis, the police officers that I had personally dealt with were all helpful, polite, and extremely reasonable.

However since about last October, my viewpoint has begun to change. I must preface with the fact that I do believe that if people choose to live in a college town then they must get over the fact that Friday and Saturday nights will be loud. Especially on holidays. If they do not like it, they can buy earplugs or move elsewhere. I have had many weekend nights where I needed to sleep and couldnt because of my neighbors party, but I never complained because I was aware that noise came with the territory.

I started writing my experience indetail but it was taking much too long so all I will say is this: I do not believe that it is ok to break up a rather tame party, on not only a Saturday night, but on Halloween, at 10:30pm due to a noise complaint that no one knows who issued because all of the neighbors were previously informed of the party and had given their OK. Furthermore, I dont think it is ok that the police officers not only held my friends license (she was throwing the party) as well as her roomates licenses until the party ended, but then also threatened to give everyone in the house a noise violation ticket if she didnt clear out the house immediately.

I understand that police officers have a very important job, and that drunken idiots can be hard to deal with, but everyone at that party was just hanging out, there was no random yelling, or whooping, there were no drunkards in the street doing stupid things. It was just a Halloween party.

In the same week (the next Saturday) I had a similar experience, except the party was of about 15 people, and you couldnt even hear the music from the front door, let alone at any other side of the house. This was an instance where there was a random yelling person, so I get the noise complaint thing. However, even after the noiseculprit was identified and the hosts apologized and promised it would not happen again, the police officers once more threatened to wait outside and give tickets to everyone in the house if partygoers did not leave. When someone pointed out that they could not do so, they received the I will talk to YOU in a second statement in a very unnecessarily threatening tone, especially because the only thing they had been receiving were yes sirs and no sirs and complete and utter politeness. In all, I found the officer to be rude, and exuding quite a bit of anger for no reason. Maybe he was having a bad day, they happen, but the more and more stories I hear the more I find this to be less likely. In the end, about 5 violation tickets were issued to the smallest and quietest party probably every held in the City of Davis.

I know that all officers cannot be held accountable to the actions of a few, however those officers with bad attitudes need to realize that the way they treat a person, or group of people greatly affects that groups perception of the entire Police Department. Unfortunately I have talked to many people and until a few months ago could not understand their dislike for Davis Police officers. This is unfortunate, because I HAVE met nice officers, though sadly it seems that now they are few and far between, and they are given a bad reputation due to the attitude of other officers. Users/alexie

20100314 14:27:27 nbsp The davis police department is a joke. When was the last time they ever solved or prevented a crime? They cant even figure out who has been stealing from peoples apartments in Tanglewood apartments for years now! Davis is a very safe town where the main purpose of these douche bags is to break up parties and issue traffic citations. The city of Davis would be just as safe if they hired some mediocre security guards. Send those bastards to Oakland to do some real work and they wouldnt last a day. Users/eliba0107
  Actually, if you read the daily crime bulletins, you can see the wide variety of situations where the police were able to assist people in real ways. For instance, in yesterdays bulletin, the very first entry is a person who was arrested trying to break into the front door of someones house. I know that that person, at least, feels that the police are helpful and serve a useful purpose. That same bulletin has a few other hitandruns that the police assisted in. Maybe your animus towards them stems from a conflict in which you were not on the same side as them? Users/JoePomidor

20100518 22:45:11 nbsp To respond to the past couple of posts, please think twice before talking trash about a department that is stretched thin in their attempt to keep Davis safe. The department has to deal with budget cuts, as well as various agencies throughout the state, and a significant group of folks in town, including students dont feel the need to increase funds for public safety (that is until THEY need to call the police.)

A good number of DPD officers are ACTUALLY experienced officers from more busy areas in the East Bay as well as the Sacramento area. What people fail to realize is that it is more difficult to apply to be a police officer in smaller safer towns due to the high expectations of their department. Many high income communities in the Bay Area only accept lateral officers that have put in their time in cities like SF, Oakland, Richmond, etc. because they want officers that can deal with any kind of problem should they arise, so before you go mouthing off about a cop, keep in mind that they have probably seen more hectic scenarios than you think.

Secondly,the majority, if not all of the officers in this town are degree holders (a good number of Sac State and UCD alum as well.) Theyre folks just like us who enjoy the same things we do and want to do their best to keep this city safe. There has been a spike in burglaries, auto theft, and a big increase in the transient population (not to mention an increase in the gang population.) All of these things are what citizens and students dont want to believe.

A lot of UCD students who are from the bay think their towns are more dangerous and police do more work, etc. Well, if you have a problem with how Davis runs things, then by all means go back to where your from and face the real problems youd rather deal with, since the low violent crime rate in this town seems to bother you. I grew up in the Bay Area (South San Francisco/Daly City to be exact,) and I think cops back home are more hard assed than cops here, but both still show up when I need them. Thats what it all comes down to: You can bash and hate all you want, but when you walk out of your apartment and realize your car is gone, or someone busts into your apartment and robs you at gunpoint (its happened recently) then go and call the police. Call the men and women with whom you have such a big aversion for, because you can talk all the sht you want about them, but theyll respond to your call, because thats what they do, even though they know they may need to help a cophater. Think about that. To serve a community in which not EVERYONE likes you? I doubt any student can comprehend that unless they know someone in law enforcement.

This town is being overrun with drug addicts, burglars, and validated gang parolees, but no one cares. All students care about is that one time where they messed up and a cop corrected them. Believe me, the cops are dealing with more than just parties. Manpower is so low that they only answer party calls after REPEATED calls from a neighbor, so get pissed at your neighbors for snitching on you. Other than that, they are patrolling areas where residential burglaries are common. Not sure how UCDPD works (Dewey is a UCD cop, not City of Davis cop; theres a difference,) but the city cops dont have time to mess around with college kids. Like I said: hate all you want, and if you stick by your opinion, then man up about it and DONT call the cops if you need them, and hope you have more than liability insurance. Users/Omicron

20100522 00:33:34 nbsp They still have no right to 1) turn on sirens and speed just to avoid waiting red lights, 2) not signal when changing lanes, 3) take out their frustration on innocent kids that make innocent mistakes. I dont hate cops. Users/flamecrow

 I have seen them not signal, and also drive ridiculously.  Ive seen them cut people off, do sudden lane changes, and almost cause accidents.  C

20100804 10:27:16 nbsp The Davis Police Department is excellent.  It is just that one bad apple that ruins it for all of the good officers out there.   Users/AshleyHamidi

20100807 21:38:24 nbsp The couple times Ive dealt with the police they are always nice and professional.  Also the bicycle cop is really friendly.  Of course, I dont give the cops a reason to dislike me either! Users/themichelle

20101224 15:32:32 nbsp I have to give them credit. I work as a bocer downtown and interact with them quite often. The officers are always cordial and polite and sometimes even have a friendly joke or two to share.

Last night, while walking home, I witnessed a drunk driver jump the curb into the PG&E yard, nearly hitting the building where I live. I called it in and the response time was fairly rapid. Turns out the driver was a familiar person to me and the officers handled it from beginning to end with the utmost professionalism. In fact, I have never witnessed such professionalism in officers anywhere else when dealing with someone who was very obviously intoxicated.

The only things I can suggest either to the police or to the residents of Davis is:

A) Residents:  Drink responsibly. As a bouncer I do the best I can to ensure you do not drive away from my establishment drunk, but its really your choice. You are risking your safety as well as others.

B) To the DPD: Since it is quite apparent that too many citizens will ignore the above advice I suggest either a back up breathalyzer for all officers or some way of storing the data elsewhere so you can always do the test when needed. The breathalyzer they used last night had a full memory and they were not able to measure the BAC in the field.

Did learn a few new sobriety test techniques though while I witnessed evwrything last night so thanks for that, will be useful at the bar.

Merry Christmas to Officers Wilson, Gillette and all the rest.

Thanks for all you do for Davis. Users/WesP

20110104 22:18:26 nbsp I have called DPD three times. Once to report people shooting guns, once to report a dog attack, and once to report I had found two purses that appeared to be stolen. They wouldnt give me the time of day for ANY of these.  In fact, they didnt come out for any of them.  I dropped the purses off to the police station myself because it was the right thing to do.  However, they were actually quite annoyed that I reported these incidents.  But they sure have plenty of time to write a ticket! In fact, they will send two officers to write a cell phone ticket.

I really didnt mind them much at all before, but when I actually had to interact with them (and needed their help), theyre worthless.  I also dont find them to be personable or amiable, no matter what the situation.

I would be interested to know the turnover rate of DPD.  I have lived here many years, and never see the same officers twice...why?  Users/CeCeWhite
  You should have called 911 for the part of people shooting guns, and the Animal Control for the dog attack. I found a little puppy last month under neath a car and she was not aggressive, Animal Control was there within 30 minutes. Users/NikhilDahal

20110707 15:29:32 nbsp all of your links here are shit. I dont want to look at the 404 website!!!!!! Users/JustinYoder

20110727 15:19:00 nbsp Cops are hit or miss. One time this guy with his friends walked by my porch and started to yell racial slurs at me. I had a large group of people inside and they all heard because the windows were open. They all came out and started to surround the group and confront them about how its not cool to yell those things. The guys ran and called the cops on us. We tried to explain that the other guys were yelling racial slurs but the cops would not listen. It also really peeves me sometimes when they bust you for something really trivial, like a busted tail light. Only sometimes are they tolerable and understanding. They sure are fast to get on the scene too. Users/David.Tran

20110816 17:23:12 nbsp I actually like the bicycle cops (I think theyre with the City of Davis and not UCD). When I was a freshman and I didnt know the rules of biking (e.g. stopping at a stop sign...lol), a bike cop was friendly enough to explain to me the rules and let me off with a friendly warning.

However, I have been stopped a few times by the Davis police for no reason (e.g. walking to the Amtrak station around 5am because my train leaves at 6am). Theres probably not enough crime in Davis, I suppose. :/ Users/PaulV

20111031 07:28:13 nbsp Best police reports in the solar system; hands down! Users/AshleyHamidi

20111119 20:51:17 nbsp Really they are only going to do a Use o Force Review about the pepper spray action of officer John Pike.

http://youtu.be/6AdDLhPwpp4

Annette Spicuzza, chief of campus police, said officers in riot gear were unable to get out after they were encircled.
A use of force review will determine whether we made all the right decisions and handled it the way we should have handled it, Spicuzza told reporters. Users/anthonykao

20111214 06:46:50 nbsp I for one will admit cops are not perfect, but I love how a lot of these complaints start out I was only doing.... If you are stupid enough to break a law, no matter how small, in front of a police office, would you rather he be like Star Wars, say These are not the droids were looking for, and just look the other way. If you feel you there was an abuse of power, report it to the station, not Daviswiki. But, if you are stupid enough to break a law and get caught, you will not get sympathy from most people Users/DCWine

20120227 17:06:40 nbsp I went here to get a fix it ticket signed off and had a pleasant experience.  The front desk staff was friendly and the officer who signed my ticket was nice.  Also, I only had to wait a few minutes for the officer to come sign off.   Users/LoriOrf

20120831 My son is a second year student at UCD. He loves this school and my wife and I have been so impressed with how freindly and helpful the universtiy has been. We just moved him into a rental home this past month, but the house needed some work so I brought up a group of kids to help clean and paint. We were all unfamiliar with the parking rules for this area, but we didnt think we were doing anything that would rise to the level of inappropriate. We got to the house around 7:30 am on a Tuesday morning to start work. One of the kids parked his car on the street, but left his tires on the sidewalk side of the curb. The curb was of the sloped variety and in our neighborhoods (SF Peninsula) parking on the sidewalk side of the curb is not only allowed, its encouraged (it leaves room for cars to pass). He left ample room on the sidewalk for any pedestrian to pass and, while the streets are certainly wide enough for two cars to pass comfortably, everyone in this neighborhood uses the street for pedestrian travel, anywaysstudents on bikes, kids on skateboards, mothers with strollers, grandparents on walks. He was cited $43 for parking on the sidewalk and $43 for parking on the street without a permit between the hours of 2am and 8am. The only sign near the house alerting motorists of permit requirements is hidden in a tree down the street, and besides, the time to issue tickets for that offense should be at 3am, not 7:45am. A simple warning would have been a much more friendly way of welcoming these families to your city.

20121211 22:35:22 nbsp I had a car alarm going off next to my apartment sporadically for almost four days. I had left a note on the car but the owner clearly wasnt around. At a loss for what to do I called the Davis police department (nonemergency number) and a police officer arrived shortly and called me on my cell phone to get the details of the car. He then CALLED BACK to tell me that he had tried to disable the car alarm without success but had contacted the owners of the car via the Palo Alto Police department where the car was registered. The next day the car was moved and the car alarm harassment of my sanity stopped. Thank you Davis Police Department for treating my nonemergency so kindly and thoroughly.  Users/Zeeba

20130814 21:32:45 nbsp Anyone know how much these clowns charge for fix it tickets? Call me lazy but dont feel like riding up to Woodland to the CHP office lol Users/STTO

20140517 18:40:18 nbsp The Davis police have a bad reputation both inside and outside of Davis. This has even been mentioned on a radio show out of the bay area. Kind of sad for a progressive community like Davis. Users/ConcernedCitizen

20140612 22:04:38 nbsp I am sure that the Davis PD does many good deeds for the town, but there really should be a citizen oversight board. There are reported instances of officers going beyond the bounds of the law, and these need to be investigated in an independent fashion. Users/DavisNewbie
