

David L. Jolkovsky, DMD, MS provides endoscopic root planings (deep cleanings) and periodontal cleanings to help prevent tooth and bone loss; regenerative periodontic procedures to replace gum and bone tissue that has been lost; and dental implants to replace teeth that have been lost.

To explore other dentists in the Davis area, please visit our Dentists page.


20060501 21:54:02 nbsp Dr. J is far and away the best dentist Ive ever dealt with. I had gum graft surgery with him in 2004 and a tooth extraction in 2005, and both experiences were... well, not pleasant, but as pleasant as could be, under the circumstances. His staff was super effecient and friendly, and his bedside manner really put me at ease. Users/RobWestergaard
  He performed dentistry on you in bed? Users/NickSchmalenberger

20071217 13:22:15 nbsp I had a root planing/scaling with Dr J in 2007 and he is great.  He took the time to answer all questions I had and did a great job.  I have gum graft surgery scheduled with him in a month.  I have no reservations about returning to him or recommending him.  My only complaint is he doesnt do regular dentistry, just periodontal work.  I wish I could see him for all my dental needs. Users/CraigP

20080315 09:40:32 nbsp I had a gum graft surgery done yesterday and it went really well. Dr. Jolkovsky and his staff were so friendly, helpful and very calming. They were very patient with me and my anxiety and they explained every step of the process, helping me feel very comfortable. Users/EmmyMelton

20080402 19:49:31 nbsp      Dr. Jolkovsky’s office is a joke. I went there for a periodontal exam. Dr J apparently felt he had answered enough of my questions and palmed me off to an assistant who he said would answer my questions. She promptly palmed me off to the front desk where my questions still weren’t answered. His office refused to provide a treatment plan. Dr. J’s staff doesn’t listen to him or just refuses to follow his directions. This appointment was a waste of time and money.   Users/DouglasH

     This comment seemed out of place to me, I have been referring patients to Dr. Jolkovsky for several years and almost all have reported a very positive experience.  I contacted Dr. Jolkovsky regarding his experience with DouglasH. Dr. Jolkovsky informed me the patient was given a full treatment plan for all recommended procedures (this is standard procedure in pretty much any office).  The patient was appointed for a one hour appointment that ran over to one hour and twenty minutes.  Dr. J had to see his other patients so he offered to have his assistant answer DouglasH’s questions and offered a second half hour appointment (at no additional charge) if he still had questions.  DouglasH later sent a letter to Dr. J explaining he felt he did not get his money’s worth from the appointment, so Dr. J gave him a refund.
	It is unfortunate that DouglasH did not get the answers he was looking for, but it sounds like Dr. J was being as accommodating as possible in this situation.  DouglasH only registered on the wiki to leave this comment and one other at another Hamid Shirazi, DDS periodontist in town).  He reported a very similar experience at this office as well.  Sometimes people are looking for certain treatments or answers that are quite different than the standard of care. Users/DagonJones

       I had the appointment with Jolkovsky in December 2007. The exam was for a gum graft. After the appointment I communicated with Jolkovsky’s office several times about my unanswered questions and obtaining a treatment plan. I finally received the treatment plan and a refund in May 2008. The treatment plan was dated March 27, 2008. Once again, the exam was in December 2007.  Jolkovsky and his staff knew they had not answered my questions and I was NOT offered a second appointment.  It’s not that I didn’t get the answers I was looking for. I wasn’t getting answers. Jolkovsky and his staff decided they were finished answering my questions.  I did find a periodontist in Sacramento that did stay for the entire appointment and who answered my questions. I had the periodontist do the gum graft and the work was done very well.  DouglasH


20080422 11:05:14 nbsp Dr. J is amazing. I had some gum removed, and even though you normally would just get an anestetic shot, I was panicky and he could see that on my face without even me even having to say anything. I appreciated his understanding and compassion, especially when I told him I didnt swallow any pills (they ground it up for me). Im sure I was more trouble than some patients, but he never acted like it, and he was extremely helpful and accomodating. He gave me phone numbers where I could reach him if I needed too, and he even called me later that night just to find out how I was doing. My schedule was crazy for the followup visit, and his staff went out of their way to find an appointment that would work for me. I highly recommend Dr. J. Users/RG

20080716 20:09:31 nbsp Dr. Jolkovsky is a fantastic DMD. I recently had my first (hopefully only) dental implant done w/ him. Ive had a lot of anxiety and fear around dentistry and he helps you cope w/ that. He talks you through gently and doesnt push. Hes extremely gentle and efficient. The office staff is also fantastic. Highly recommended. Users/ahbrapeach

20081003 18:40:56 nbsp I have needed a gum graft for a couple of years and I had been putting it off because I was so nervous about the procedure.  I finally went to Dr. Jolkovsky to have the graft done a couple of weeks ago.  He was very patient and he did everything he could to make me feel as comfortable as possible, including explaining anything I wanted to know and giving me extra time to relax.  I have healed very well and I am very glad I went to see him.  I highly recomend him to anyone who is nervous about seeing a periodontist because he is so patient and understanding. Users/EJones

20091118 15:57:18 nbsp I had not been to the dentist in over 30 years and was quite nervous, embarrassed and fearful of the outcome. Although I need some radical work, Dr. Jolkovsky and his staff couldnt be nicer and more thorough. The doctor listened to all of my concerns and questions, and addressed them all! Great experience, and kind people. Users/LML

20100201 18:01:45 nbsp Over the past couple of years, Dr. J has implanted 5 teeth for me and I am very happy with the results!  Dr. J and his staff were very supportive throughout and while there was some shortlived discomfort involved in each step of the procedure, it was not painful and nto nearly as traumatic as I had expected.  I always felt very secure in knowing that Dr. J is always available for questions or problems.  All of my experiences in Dr. Js office have been super positive and I would highly recommend him as a surgeon.  I also highly recommend this procedure, if needed. Users/dpaige

20100212 15:37:47 nbsp I hate going to the dentist and I was facing lots of dental work.  The office staff of Dr. Js were so kind and compassionate.  Dr. J made me feel so comfortable.  He offered procedural sedation to help get me through.  All his work, including a beautiful new implant is impecable.  I would highly recommend this group of wonderful people.  Users/scoopslade

20100521 15:14:41 nbsp Dr. Jolkovsky has implanted two teeth, top and bottom, for me.  Both times I was nervous and anxious about the procedure.  Dr. J.s work is so seamless that I had no problems with either of the tooth implants and they feel no different than my real teeth.  I would highly recommend him for tooth implant procedure. Users/jm7sumner

20100714 12:45:19 nbsp Great experience. Latest was a tooth implant. Almost painless!!!!!!!!!!!!!!!!!!! Users/stevecraig

20100729 15:51:11 nbsp Dr. J is the best dentist I have been to.  He did a very successful sinus lift and bone grafting for me.  I am very impressed by Dr. J and all his staff.  I had a consultation with a dentist in Palo Alto and his cost was at least 3 times Dr. Js.  I am very grateful to Dr. J for being a great dentist and keeping his costs very reasonable. Users/LBoyd

20101006 12:18:48 nbsp Dr. Jolkovsky and his staff are compassionate, professional and thorough.  I recently had a root planing/scaling done with the perioscope and it was a very positive experience.  Needless to say beforehand I was quite nervous, but Lee (the most kind and caring hygienist) did such a wonderful job and made me feel very calm.  I have no hesitation continuing my treatment with Dr. J and recommend his office wholeheartedly. Users/jrsygrl

20110513 10:25:26 nbsp Dr. J and his staff are extraordinary – trustworthy and kind, thoughtful and knowledgeable, beyond professional in all ways. The treatments I have received there include tissue grafts, bone grafting in my sinuses and teeth implants. At the time, I was living on the Peninsula and friends from near Sacramento recommended Dr. J. In 2005 I relocated to SE Ohio and Dr. J has remained my periodontist. I continue to go to the dental hygienist in his office who is always excellent and Dr. J is my adviser on all things dental. I still fly from Ohio to Davis to have Dr. J. place my implants.

I trust Dr. J and his staff implicitly. The respect and thoughtful consideration shown by them to me, other patients as well as their colleagues in the dental field continue to take me by wonderful surprise.

Northern Californian refugee in SE Ohio Users/MarionSLee

20110624 10:39:10 nbsp I was reffered to Dr. J by my regular Dentist in Davis Dr. Johnson.  Being a Healthcare professional, and also a Director at a local hospital, I understand how important not only the quality of care being given, but also the service given by all the staff.  You could have the greatest skilled dentist or specialist around.  However, if you do not have the service component down, nothing else matters.
I WAS VERY IMPRESSED with my first initial contact with him and his staff!!!!!!!  The goal is to have a good experience in a situation where fear consumes you.  If you are successful in reducing that fear, then the experience is considered good.
When I found out that I needed a gum/tissue graph, I was scared out of my seat.  Dr. J. and his staff saw that, heard my concerns, and ensured me that I would be taken care of.  Even though I was still scared about having the surgery, my fears were still subsided by his staff.  Once the surgery was over, SERVICE did not stop there.  I received a phone call that evening from Dr J seeing how I was doing.  I had a scare about a week later thinking I blew my graph.  I called them up, and was seen immediately.  I was relieved to find out my graph was still there and I was recovering well.
IF YOU WANT THE WHOLE PACKAGE OF A SKILLED PERIODONTIST AND STAFF, THIS IS WHERE YOU NEED TO GO!!! I would have no second thoughts trusting him with any one of my family members!!! Users/ChristopherGiambruno

20111129 22:44:17 nbsp I found myself in need of an implant and was referred to a periodontist in town, but I wasnt all that comfortable with what I found there so I went in search of a second opinion and found Dr. J.  That was a most fortunate move as I found a winner here. The office staff, hygenists and technicians are super, Dr. J takes time to listen to whatever is on your mind and I couldnt be happier with the outcome. Everything proceeded exactly as stated, no surprises and I would almost have to say it was a non event...which is pretty amazing considering all that was involved. Id recommend the Office of Dr. Jolkovsky with both thumbs up...  Users/AllanMcCrary

20111204 12:11:14 nbsp My experience at this office is in line with virtually all the other commenters. I needed several rounds of gum grafting surgeries, and while I wouldnt wish gum grafting on anyone, this office and staff were extraordinary in making the experience as pleasant as possible. I no longer live in Davis, but if I needed these surgeries again, would go back to Dr. J. in Davis. Users/DavidBenjamin

20111221 13:06:43 nbsp Dr. Jolkovsky is unprofessional and the whole gum graft industry might be one big hustle:

I have known for some time that I have extensive bone loss in my jaw.  I asked my dentist where I previously lived about getting gum grafts about 6 years ago.  She impressed upon me that gum grafts were for aesthetic purposes only, and that if I had receding bones due to genetic reasons, the gum would continue to recede regardless of adding on extra tissue.

During my regular dental check up last spring, Dr. Jones asked if I’d ever considered getting gum grafts.  I told him what my previous dentist told me, and he said ‘well in your case it wouldn’t be for aesthetic purposes.’  So we set up an appointment for me to meet with Dr. Jolkovsky.

During the initial consultation, Dr. Jolkovsky made a big show of the mobility in my lower teeth, and made a big show of where my gums used to be and where they are now.  He said that I ‘had to have’ gum grafts.

A few curious and unprofessional things happened during the initial consultation:  1)  Dr. Jolkovsky said my gums had receded just as badly on the back side of my teeth as the front.   I asked why he wasn’t recommending gum grafts for the back of my lower teeth, and he wouldn’t answer me.  2)  I’ve been dealing with a few major and emotionally trying health issues and started crying in his chair when discussing them while going over health history, and he couldn’t have cared less, he showed absolutely no compassion and in fact seemed annoyed that I started crying.  3)  He wrote a prescription for me to pick up pain medication to take before the gum graft procedure.  I have an intolerance to certain proteins, and when I asked if the pain medication might contain these, he told me to research this on my own.  I expressed bewilderment at this and he very begrudgingly said he’d have one of his assistants look into this.  I also asked if the labcreated gum grafts (as opposed to my own tissue) might contain these proteins, and said he didn’t think so but I wasn’t convinced he was going to look into it.

After the initial consultation, I started researching gum grafts on my own.  My friend is a dentist in another state.  He said he agreed with my previous dentist that gum grafts were for aesthetic purposes only, and that the science behind any purported health benefits was really shaky.  He said he would never recommend to any of his patients that they get gum grafts.  Furthermore, most online medical sources stress the aesthetic benefits of gum grafts, rather than any health benefits.  This jives with why Dr. Jolkovsky only wanted to do the gum grafts on the front.  Essentially, this all sounds like plastic surgery for inside your mouth:
http://www.mayoclinic.com/health/periodontitis/DS00369/DSECTIONtreatmentsanddrugs
http://www.perio.org/consumer/grafts.htm
http://www.webmd.com/oralhealth/gumtissuegraftsurgery

After researching this, I wrote and asked Dr. Jolkovsky specifically what the health benefits of gum grafts were and what my alternatives might be.  He wrote back and said I could come in again and we could discuss or he could answer over email.  I said I would like answers over email, but he never wrote back.  Eventually, I wrote to Dr. Jones and told him I was turned off by Dr. Jolkovsky saying I ‘had to have gum grafts’ and not answering my questions.  Dr. Jones forwarded my email to Dr. Jolkovsky—I know—and Dr. Jolkovsky wrote to me saying:  “Periodontal/dental care requires a high level trust and confidence between patient and provider, and unfortunately I dont feel we were able to establish that.  I wish you the best of luck with your oral health and hope everything works out for you.”  So that’s that, folks, if you dare question a man of science like Dr. Jolkovsky, you’re not going to get answers and in fact will get shut out.

One person online described her visit to a periodontist like visiting a used car salesman.  I couldn’t agree more.  Sitting in Dr. Jolkovsky’s chair made it seem like getting gum grafts was the most urgent and important thing I could do for my health.  I would really like answers on gum grafts; it truly seems like a lot of people might be fooled by the industry.  In my department at UC Davis, we always teach our students that science is very much shaped by cultural and capitalistic interests and is not neutral by any means.  Unfortunately, too many put too much faith in doctors and science.

And Dr. Dagon Jones, I see you’ve supported Dr. Jolkovsky in a post above.  How lovely.  I’ll preempt you by saying that I only registered on DavisWiki to leave this comment, for now anyway.  I’ll eventually get around to writing a review for you.
  Users/ActionFigureBarbie

        Seems like maybe this was the perfect storm of two strongish personalities? I was SO anxious about my gum grafts, and even came in twice to talk more about whether donor tissue or my own would be best. This was welcomed and I asked a TON of questions. He was extremely gracious about it. Regarding the industry, I think each application of this  or any  procedure depends upon the circumstances, but I can certainly say I had to have them, and the benefits have been great (can eat/drink cold things again, my roots arent exposed, etc). Also, included in the price of the procedure with Dr J. is what I thought was a thorough number of followup visits, like 3 months, 6 months, 1 year, to check on healing, progress, the graft sites, etc.  Also, the links you gave go into some detail about the health benefits. You can lose your teeth! It can be cosmetic, but can also be to correct problems that are definitely health not cosmetic. This is a guy who knows his stuff, does it well, and is a professional. Users/DavidBenjamin

I am truly very sorry that you had a bad experience with me and my office.  As a health care practitioner, I place a great deal of value on the doctorpatient relationship and not only give the best treatment that I can, but treatment that is tailored to each patient’s individual needs.  Our office goal is “to help our patients achieve the highest level of health and wellbeing.”  It is not often, nor without significant thought, that I do not accept a patient for treatment or dismiss a patient.   In response to your questions about the problems and potential solutions your general dentist referred you to my office for, I cannot be specific to your case for patient confidentiality reasons.  However, I can speak to my general policies and guidelines I follow and the reasons that I follow them.  Please click http://daviswiki.org/Dental_Questions#head4039c96b7f4912219b073c6de4199a3c10910ece here to go to Gum Grafts on the Dental Questions page on Davis Wiki for more information about gum recession, its causes, and different ways to treat it.  In the unusual circumstance when a patient and I do not seem to be establishing a clear level of communication and a good rapport, I feel that it may be in the best interest of the patient to see a different periodontist so they feel comfortable with their treatment.  That being said, I still offer you a second (at no charge to you) consultation to review the specifics of your situation and hopefully we can establish better communication.Users/DavidJolkovsky

Jolkovsky, youre full of it. DouglasH
