


Davis Swim & Fitness is a South Davis Gyms gym. Some of its features include:
  Over 50 group exercise classes a week  (Boot Camp, Yoga, Pilates, Stretching Classes, Stability Ball, Super Ab Classes, Spin, Fusion Step)
  25 Yard Outdoor Heated Swimming Pool
  Coed Jacuzzi
  Matrix Strength Training Equipment
  Matrix Elliptical Trainers/Treadmills with Individual TV Screens
  15 Schwinn Elite Spin Bikes
  Nationally Certified Instructors in for the Swimming Program, Personal Training and Aerobics
  Complimentary Towel Service
  Kids Club and Outside Play Area For The Kids
  Triathlon Swim Training, Private Lessons, Coached Master Swimming, Youth Swim Team, DSF Tiny Bubbles Program InfantToddler, Aqua Aerobics Classes
  Social Events: Wine Tasting, Parents Night Out and The Marshmallow Triathlon
  Personalized Fitness Programs: Personalized Training and Aerobics Dept.
  Outside Basketball Court
  Massage Room: Massage Therapist offers Deep Tissue, Acupressure, and Swedish Massages and Exfoliating Foot Scrubs
  Also home to the DSF Martial Arts Academy

See our Gyms page to find out about other gyms in the Davis area.





  /Comment Archive Archived comments can be found here.

 Current Comments 


20090915 21:01:20 nbsp This is an email I sent Tammy just last week, having absolutely no idea about the hateful and ridiculous agenda that 1 person seems to have on this Wiki site. I just happened to check the gym out on Davis Wiki tonight, purely by chance, and I had absolutely no idea of the existence of this seething rampage of an unhappy person bent on revenge. I am shocked, it is really abusive, and DavisWiki should be able to screen for obvious pathology such as this, and one person making up fake names to try to create the illusion of support for their craziness. So, I found my email to Tammy and I am pasting it in here. I know everyone who attends MaryEllens, Sheryls, Alisons, Aubreys. Barbaras, and Mallorys classes consider themselves so lucky to be a member of this gym. And Tammy, we all know how wonderful you are. Keep shining your light!

Hi Tammy,
Firstly I just want to tell you again how much your gym classes have become such a special and important part of my life! All of your instructors are such high quality Sheryl and Alison, Aubrey is fantastic and of course MaryEllen is an absolute star. I love Crystal and Valerie, and so does James. Honestly, I think you have such an incredible product, you should be very very proud. I know you work sooo hard to make Davis Swim and Fitness stand out and be the best, and you are succeeding. I truly admire and appreciate your vision, enthusiasm, big heart and sweet sweet smile! You make DSF so much more than a gym, it has become like a family to me, and so many others!

Couples yoga was fantastic, thank you so much! I was very honored that you called me! I cant wait for next time when I can bring Erik! I have 2 friends who have recently joined DSF, and they are very impressed also by the quality of everything. I had another friend come this morning, I had to really convince her to come, since she hasnt worked out in 7 years, never been a gym member anywhere, and has never done yoga. But she has heard my accolades for so long, and she had the day off today, and so she came. She loved MEs yoga class, found it very hard, but loved it. She is tempted to start giving the weekend and evening yoga a go, and zumba. She has some financial concerns, and I told her Id ask you if the special $99 for 3 months was  still in effect, because at that price she just may be able to swing it. Thanks for letting me know!

Have a wonderful Labor Day today, Tammy. Thanks again, for everything.
Sacha

PS I totally forgot to mention how fantastic the zumba classes are Barbara and Mallory are such wonderful people, talented dancers and teachers, and I feel so fortunate to be able to take classes with them.  Users/SachaLaurin
   If you wish to believe one person left all these negative comments, then youre a fool and deserve it when you get ripped off!!! Buyer beware!!   Users/PublicEnemyNumberOne

20091022 19:46:18 nbsp There are no improvements at this gym. Nice equipment doesnt make your manager smarter. And its sad to see that so many people have their heads in the sand. You really think one person is being negative about this heep of a gym. I was from 24hr and went here then quit due to the managements incompetence. As soon as I quit this place I saw many friends from old 24hr that said they were charged from this gym and they never set foot in it once. When they called they were told pay up or collections.  Huh...seems to me Tammy if you want better comments take care of people. Tammy has the audacity to say free speach is great when positive Wow that is really ignorant!!! Maybe you shouldve addressed problems instead of run away from them. Users/PublicEnemyNumberOne

20091112 08:38:14 nbsp The only good thing about this gym is the pool. Everything else is useless.

I just created an account to leave a comment specifically for this business. IF YOU CANCEL YOUR MEMBERSHIP HERE GET A RELEASE FROM THE GYM IN WRITING!!!!! I joined for the summer back in 2006. The kids at the front desk dont care enough to make sure a persons membership is cancelled, that or the manager conveniently loses your letter of cancellation you left at the front desk. This gym decided to continually charge me a monthly membership fee for almost a year after I left the Davis area. After over 700$ accrued they finally called me to tell me I owed them this ridiculous sum of money. When I asked for this to be checked into nobody ever called me back, when I called four more times and left messages, nobody called me back. Finally got a letter from a collections agency. Dont be fooled, THIS BUSINESS IS OUT TO RIP YOU OFF! This must be the only way they can afford to stay in business. They even hired a firm from the east coast to handle the numerous times theyve done this to folks. Anyone else out there that this happened to? There were at least 2 other people mentioned in previous comments. Hmm.....Users/jesakit

20091120 14:42:53 nbsp After reading all the negative comment here, I was pleasantly surprised by the facility. I was a member since many months ago (through my job) and finally set foot on the facility (just not a gym going person...) Its clean, the staff are courteous, and the Lift and Pilates class is one of the best gym classes Ive attended, the instructor was extremely engaging and encouraging.   Users/val

20100124 14:35:10 nbsp Lol, considering that 24 Hr Fitness is a shitty gym in its own right, I will not bother looking here after seeing these comments. Thanks for your comments! Users/antlu

20100222 19:46:35 nbsp I agree totally with jesakits comments on this gyms management and billing.  I found the facility OK.  The pool and spa were nice and the classes were fine, although I found it disturbing that there was frequent talk in the classes about this or that person being banished from the gym.  I didnt like the constant noise of really lame music played so loud that even expensive noisedampening earphones didnt work.  Dont ask the management to turn it down.  They wont, even if you are the only one there.  I like to time my workout to my own playlist, and it finally got to be too much. So I quit.  I did what the contract said, which was to give 30 days written notice.  In fact I gave 45 days notice.  I not only mailed a letter to the club, but handed a copy to the person working the desk. This was three years ago.  I started getting dunning letters and wrote (including a copy of my original letter) but this made no difference.  The management sent me a letter asking whether my original letter (which they claimed never to have received) had been sent registered mail.  I told them it had not, since that was not required in the contract.  They kept billing me and turned my account over to a collection agency.  I actually found the agency a lot nicer and more reasonable than Ms. Hengel.  I tried going through Mediation Services, but Ms. Hengel would not return their calls.  I thought that this crazy behavior would just have to end.  How much are they willing to pay to get 2 months fees from me?  Apparently a lot, because I just got another call from yet another collection agency.  I told them to check with Davis Mediation Services.  I guess they did, because he has quit calling.  This is the worst experience I have had with a business in Davis.  The management seems vindictive and a little crazy.  Actually kind of scary.  I just cant agree that the negative entries represent a minority opinion.  This is my first post to Davis Wiki, and I agree with the critics.  There!  Now I feel better!

 Users/ellenfromsouthdavis

20100702 08:55:03 nbsp I joined this gym in April 2010 to use the pool. I really like this facility it can get very busy though and peak hours can be very crowded. If you are looking to work out in a non meat market environment this is the place. Mostly professional mature people and the equipment is great. I recently started using more of the gym and working with a trainer, Gina, she is GREAT and really very professional and has some exercises I would never have tried that are very effective.I love this place just wish it was a larger facility! Users/VBurgett

20101213 21:57:27 nbsp I was a member of 24 hour fitness when Davis Swim took over. I called 24 hour fitness and moved my membership to another gym in Sacramento so that I could continue to stay with them and also I lived in Sacramento at the time. Months later I received a bill from Davis Swim for $56. I called and explained that I never transferred my membership to them and that I went with 24 hour fitness and was currently paying my membership still. The guy on the phone got really rude with me and said that I had to pay their fee for not giving a notice or something or they would send me to collections. I figured that I didnt have the energy or time to deal with that small amount so I mailed them a check. That was back in 2007 I believe. Today 12/13/2010 I received an email from them saying that I am currently 90 days past due and owe them $56 or I will be sent to collections. I think they have some kind of scam going on there. Please think before handing over your information to them or even signing up. There are plenty of other choices. Please be careful. Users/RobertLing

20110222 22:06:41 nbsp 20110222 I have to agree with the negative comments and I would say to everyone..BUYER BEWARE! This gym and in particular its owner has some very shady practices in regards to their billing practices. I have found the owner to be a liar and a cheat. Without going into a lot of detail, it is clear by my experience that they dont have their act together as far as the business/billing and customer service. Davis is a small community and the word is getting around. Continue these practices and you wont be in business much longer.  Users/Malinda

20110227 21:58:14 nbsp I have been going to this gym for several years and have never had to interact with a manager or any staff at all to be honest, so I dont see where all these negative reviews are coming from. Most the people I have seen at this gym get in, swipe their card, work out, and leave without a single problem. It offers exactly what I want, a quiet place to come and work out at night thats not overly jammed with people. The pool is always clean and the temperature is just right for me, even nighttime swimming in the winter isnt too cold. The machines have always functioned well and been consistent for me, and I never have had to wait more than a minute or two to use them. My girlfriend also takes yoga and pilates classes here and can only say good things about them. The only downside to this gym is the number of swim classes that fill the daily schedule in the summer time, but that problem is easily solved by coming later at night. Thanks Swim and Fitness! <3 Users/IanBurau

20110301 16:37:57 nbsp I was a member two and a half years ago, at that time I moved to over 50 miles away and so did my girl friend....so I had no reason to go to this club anymore.  I found that trying to give my 30 day notice to the management was just about impossible.  I came by the club and the management was never in and the people at the front desk said they could not help me.  I tried calling but none of my messages were ever returned.  finally one of the people working the front desk suggested that I leave my own letter telling the management that I was canceling my membership....so I wrote up my letter and gave it to the person behind the desk.  That was over 2.5 years ago.  Now a Month ago they sent me a letter saying that I owe them $600.00, so I contacted them and told them I had quit and did not owe the money....they of course said they did not get my letter.  My question with that is why did they not contact me before this.  Now they have sent me to collections....I do not think they are in the right.  Has this, or something similar, happen to you?  If so send me an email and perhaps we can all get together and get a lawyer and fight this.  You can email me at donotberippedoff@gmail.com. Users/DanPiper

20110508 16:45:09 nbsp Wow, I’m all for free speech but this is crazy!  People, if you want Capital Athletic Club or Arden Hills Country Club then by all means go there and pay their pricing.  Davis Swim and Fitness “is what it is”, and doesn’t pretend to be anything more  DSF is a great local neighborhood gym without the meat market and pretentiousness of other facilities.  I can go there, work out, be left alone, and leave.  The equipment works, if it doesn’t a sign is posted and its usually fixed within a couple days.  The pool is awesome.  From what I can tell the instructors seem to all build relationships and get to know their students.  From what I have seen the personal trainers seem to know their stuff.  I am comfortable leaving my kids in the kidsclub, the environment feels safe.  The owner will host BBQ’s on holidays with entertainers, and also fun events such as the 4th of July marshmellow triathlon. It’s a shame that this otherwise useful wiki can be overloaded by negative comments of nitpickers and deadbeats. Users/JClark
Free speech is great for warning people of shady businesses with unscrupulous owners, like D S&F!!

20110713 12:24:42 nbsp This is gym management is full of thieves!!! I signed up for 3 months trial (the minimum you could do) and I paid my $120 at the front. After my membership ended, I received a bill of $50 saying that I must pay this to Davis Swim and Fitness. I t did not make any sense because I already paid $120 up front when I signed up. After few months, I got more letters and calls from this jerk ass attorney from SAC who threatened me to take this matter to the court. Some how I owe $167 more to the club. PLEASE BEFORE YOU SIGN UP FOR THIS GYM ASK THEM ABOUT THEIR HIDDEN FEES!!!! These guys are CROOKS!!! STAY AWAY!!!! The gyms facility is not up to date. Most area you find weights lying on the floor and it gets like a fishmarket on weekdays so its hard to find a peaceful place to work out at. Mostly, high school kids and senior citizens come out here to work out. I would suggest to stay away from these THIEVES and CROOKS! Save your money and time and go get a membership at different local gym. Users/Raz

20110828 18:30:10 nbsp Interesting comments. Not my experience though! Pros: Love the pool, lack of crowds, great (usually) front desk staff, never had any billing problems or issues, equipment is kept clean and in good condition. Cons: Some of the new lockers are pay only, the class schedule is 99% wrong (always double check before you assume and show up.), the staff doesnt seem to have the power to do anything other than greet people and clean (like when kids run amok while their moms are in Yoga class... true story! Overall, a good value for the money, but I only really come here to swim. Since every time I show up for a class, there was a schedule error, I cant speak for the classes or their teachers at all. Users/Antoinette

20111102 14:49:41 nbsp This is a great gym. The atmosphere is professional and friendly, not intimidating. The rates are reasonable and the facilities are excellent for what you pay. The staff is always eager to assist and if they cannot help you immediately  to resolve a billing question, for example  they will leave a note for someone who can. You can select from a wide variety of aerobic classes, yoga, weighttraining with a personal assistant, participate in excellent Masters swim program or remain as anonymous as you like and makeup your own personal training schedule. There are an ample supply of treadmills, eliptical riders, bikes, step machines, freeweights and weight machines to accommodate all members. I love the place. The casual vibe coupled with professional assistance if you need or desire it make it by far the best gym in the area. P.S. Some of the staff, trainers and aerobic instructors are pretty hot  not that it matters. Cheers. Richard Users/RichardH

20111129 17:00:58 nbsp Deceptive and low integrity!
My gym membership was transferred here without my knowledge when my gym closed.  The first communication I got from them was a bill.  Naturally, I expected the charge to be waived since I never set foot in the place and didnt want the membership, but its their policy not to do that.  The owner instructed the manager not to release anyone trapped this way.  Is this who you want to have a business agreement with?
Im guessing theyre in real trouble to behave this way.  Protect your money and go somewhere else.  Users/StephenW

20120121 17:18:26 nbsp Anybody know the current rates? The website seems to be missing that key information and Im not interested in talking with a salesperson over the phone or spending time visiting if I dont even know whether we can afford it. If its on the website and I missed it, Id appreciate the link to that page in particular. Thanks! Users/BorgilVino

20120302 19:33:42 nbsp If you love zumba, you should try out the aqua zumba DSF now offers!! Its a blast! Users/BNSCALLON

20120302 20:56:28 nbsp @BNSCALLON,
Do you work at (or own part of) DSF? Youve been editing its page repeatedly for the past couple of months. Users/Chamoudah

20120703 10:03:38 nbsp I recently joined since the ARC for an alum when you add in parking (like $1500 per year for 2 hours 5 days a week) is just ridiculous. Its fine although the way staff respond to inquiries varies. I got a flyer and decided to go in to see it, thought it was nice. (I hadnt looked at this page.) They told me I had 48 hours to use my golden ticket, which it turned out I didnt have and that I could just call them up and do it over the phone if I wanted to. So when I called in on Thursday to join I was told I had to use the web site. A very authoritative sounding womans voice told me I couldnt join in person for that special. Then the authoritative sounding woman gave me a golden ticket code over the phone. I tried to use the Website to join but it was glitchy and the next day the web developer emailed me that he didnt think it went through. So, I called and they said to come in because I couldnt join over the phone. A tall curlyhaired guy who has lost a lot of weight that works there was very nice about everything. He set me up with a 14 month membership for the cost of the best price for 12 months. He offered to precancel my membership if I wanted that.

Ive been happy with the facility so far. (Weirdest thing was one night some guy came through and turned off all the lights. I think it was a joke he was playing on his buddy over by the weight rack. Staff came and turned them back on.)

Its a little quiet for my taste compared to the ARC, but its got a nice pool right there, all the equipment Im used to using.

So, overall its logistically got some minor problems with signing up. If unjoining has the same sort of logistics, it could be problematic I suppose. But I think its a matter of getting to the right person. Putting on my management hat, I suspect a training problem for staff or perhaps inexperience leading to confusion.

Its similar to Davis Athletic Club Id say, but slightly smaller. The clientele is somewhat younger than DAC which I like.  Users/YogaBhoga

20120719 17:17:14 nbsp Well, its about a month later now. I got an email from Marta saying I needed to come in and pay. But I have. Reviewing the charge on my credit card, I have not only paid, but the charge was for more than it was supposed to be. I wrote back. I expect things will get straightened out.  Users/YogaBhoga
Yeah sure, good luck with that!!


20120929 23:35:16 nbsp Pathetic excuse for a gym. The supposed owner is cheap.. watch out make sure you read your contract. Theyll charge you for anything to make money since they are going broke. Clearly the owner doesnt know how to run a business. She barely follows any labor laws. The owner is so unprofessional always getting into fights with members. The gym itself is tiny and dirty. Most of the employees are great thats about it. STAY AWAY FROM THIS GYM!  Users/jthom

20130105 08:25:44 nbsp I have submitted membership inquiries through their website and no one answers me.  Great management who doesnt even respond to email asking to give them money. Users/DonnieDarko

20130221 09:53:57 nbsp I just switched to DSF in January after my beloved Curves closed at the end of the year. Ive had nothing but positive experiences with Tammy and the rest of the staff.  I can always find a bike to ride and the three classes I take are always on time and well taught. The classes room could be bigger but everyone fits in and the instructors are flexible about coming in a bit late or having to leave early. Gina, my trainer in the 28 Day Healthy Choices program, is conscientious and super friendly. Ive already seen a big drop in bodyfat percentage which makes me very happy!  Users/LaurieLoving

20130221 13:45:18 nbsp As a former owner of a fitness center myself, I truly appreciate the great customer service of Mgr Shannon and the rest of staff as well as the effort put into Davis Swim & Fitness by the owner, Tammy. The staff is welltrained in what they do and really connect with the members. I just finished Ginas 28 day Healthy Choices nutrition class, and I lost 10lbs & 14inches in my 1st 6 weeks at DSF. She really personalizes her class & I recommend it. Ive taken 3 different classes for strength training & cardio ~ they were all very well led by Katie, Jennifer & Corina. They were extremely effective in meeting my fitness goals. I have used cardio equip like the treadmill & stationary bikes for the 1st time here along with weighted resistance machines and have to say: this is a workout for sure & I like that I can tailor my time at DSF to meet my needs & goals with such a wide variety of options.  My husband is happy about the heated pool & Ill cheer him onto another lap from my hot tub! D  Im excited about the upcoming additions & improvements Tammy has worked so hard to accomplish. DSF will be even better! Their fees were what my fees were but they offer many more features, & their special offers are worth taking advantage of.  I was a bit apprehensive about going to a regular gym after being spoiled with my community of ladies only and a simple workout, but Im a happy transplant!  Thx Tammy & All!! Users/AnnArneson

20130302 11:04:42 nbsp Got a flyer on my door with a good deal for DSF membership, but after reading the comments on this page I dont think Im going to sign up.  Looks like DSF f#K$ you with their billing practices without even having the courtesy to kiss you first.  I hope people are being honest with their comments and not being jerks for the sake of being jerks. Users/JohnMendez

20130317 19:08:42 nbsp After 8 months of trying we still are unable to get Davis Swim Fit to stop charging a monthly membership to our card. My son had a membership, charged to our card, and he stopped using the gym when he moved from Davis to Sacramento in August 2012. We live in Vermont (we also lived for Davis nine years). We phoned the gym in August to ask them to discontinue the charge, but they said we had to fill out a form, which they never sent. My wife called them in October, and they said they would cancel the membership. They didnt. Our son went into the office in January 2013 and asked them to discontinue the charges, and they said they would, but so far we have been billed as usual for January, February, and March. Well talk to our credit card company tomorrow. BEWARE of providing your credit card number to the management. This is certainly the worst experience Ive had with any company in Davis. Users/SethBigelow

20130325 14:45:23 nbsp Ive been a member at Davis Swim and Fitness over fifteen years and Ive seen it go through a couple of ownership transitions.  Yes, as others mentioned, there were some problems.......until Tammy became the sole owner about five years ago, Since then the Club has continued to get better and better  its a hidden gem, actually.

Im baffled about the negative comments.  I have not observed the problems they cite.

Im serious about my workouts and am not interested in the socialclub/meatmarket atmoshere of some other gyms.  At Davis Swim and Fitness, however, there is an unintrusive social aspect that resonates.

What are some of the other reasons I like this Club.......let me count the ways:
Clean and comfortable Club with uptodate equipment and workout toys
Professional and friendly staff
Owner who is dedicated to continued improvement of the Club facilities and is quick to correct problems as they occur.
Heated swimming pool, jacuzzi, and pool house with showers, etc.
Wide variety of many group fitness classes with helpful, friendly instructors
Two basketball courts
Volleyball court
Kids daycare center and outside playground
Familyfriendly events

Over the years I have visited and worked out (as a guest) at several other Davis gyms
.......for me DSF is without a doubt the best.
  Users/MarieWest

20130327 06:56:45 nbsp As others mentioned, I had a similar negative billing experience a couple years ago, after being a member for several years. I had a oneyear membership contract and wrongly assumed it would be up at the end of the one year. After the year was up, I didnt want to renew my membership, so I assumed it would be canceled because I didnt pay and sign up again. A month or so later, I received a bill for a onemonth membership plus a late fee, even though I had not gone to the gym. I think the fine print in the contract said you needed to give them a 30day prior notice in writing that you wanted to cancel or you would be charged bythemonth after your membership was up. I called to question the bill and was treated horribly by two employees. It was the worst experience Ive had as a customer in the many years Ive lived in Davis. I wish I put this on Wiki back when it happened, because I dont remember the names of the employees anymore, but I think it was a frontdesk employee and an accountant. At one point, someone slammed the phone down and hung up on me. It was a very negative experience, to say the least.

A better and more customerfriendly way to handle it would be to just cancel someones membership if s/he doesnt pay. The way they handled it when I was a member (Im not sure if its still this way) makes it seem like they are just trying to be sneaky and even unethical to get extra money from their customers. This experience I had was enough to make me never want to be a member there in the future. I spent so much money there over a few years, and they still treated me so badly. Please keep that in mind if you decide to become a member.  Users/ClairLee

20130328 15:38:14 nbsp WOW!!! It really baffles me to see how hateful and RUDE some people are. I am a member of Davis Swim and Fitness and have been for almost 3 years now. I ABSOLUTELY love the facility and the staff working there makes it even better. When I joined back in 2010, I clearly remember a lengthy contract that I had to sign. I am an attorney so I ALWAYS read any contract in full, (which apparently some of you adults on here need to start doing). Upon sign up, the front desk staff member explained to me that after my year was up, my membership would go to a month to month state AUTOMATICALLY, and that if I wished to cancel I would just need to give 30 days notice. No surprises, CLEAR AS DAY, membership will not automatically cancel, you must cancel it yourself!! Well a year later when the time came for my membership to go to the month to month, I had naturally forgot all about it. After 3 months of being billed the monthly rate, I finally realized my membership had lapsed and went to the month to month state. I called the front desk, because I didnt want to pay the higher monthly rate, I preferred to do it a year at a time to receive a discount; upon calling I got in touch with the Manager Shannon. First and foremost she is one of the most professional and friendly people I have had the chance of meeting, and her customer service skills are one of a kind. I was calling just to renew my membership, and after hearing my dilemma, she offered to credit the current month that I had been charged towards my renewal. I understood it was MY responsibility to have renewed before time lapsed, and I told her this, and she STILL offered to go above and beyond to make my experience a positive one.

Since then I have renewed my membership yearly, attended classes regularly, and built a strong bond with the staff and other members of the club.  This is not a 24 Hour Fitness or a Cal Fit and if it was, I WOULDNT BE A MEMBER!!! It is a small gym, locally owned and locally ran. Tammy, the owner is currently remolding the facility and putting a lot of time and money into making Davis Swim and Fitness an even better place. It disgusts me to see people trash talk  and down grade people and businesses because of their own stupidity. Especially when its a local business? Sickening. GET A LIFE!!!  Users/MonetGomez

Wow, because you were treated decently everyone else who has had very negative experiences are STUPID. Youre another ignorant human. Just give your experience and let that speak for itself moron!!! Users/PublicEnemyNumberOne

20130402 23:09:28 nbsp Tammy deserves all the bad press.  I have tried repeatedly to contact DSAF through the website and she doesnt even respond.  What kind of a manager/owner doesnt answer people? One whos incompetent and has no business running a business. When Tammy sells it, Ill go back.   Users/DonnieDarko

20131231 00:58:19 nbsp Overall negative experience. Moved to south Davis a year ago and place was close. Front staff kids were young probably HS kids but attentive. Place is tiny, pretty crammed, very average equipment and locker rooms are outside and average at very best. Personally had a negative experience with owner Tammy Hengal but wont get into details. Other places will give more bang for buck Users/Parker8821

20140622 18:35:47 nbsp Here is my attempt to provide an honest, objective review of Davis Swim and Fitness: I really like this gym, a lot! It has a great feel to it, just lots of locals (dare I say townies?) working out. Use of the pool is included in membership dues, as are most workout classes, which is awesome and the reason I chose this gym in the first place! There seem to be quite a few high school kids that use the facility, and they always seem to be pretty respectful. One of their front desk employees, however, can be really loud and annoying when interacting with them. Good thing I always have my earbuds in! My ONLY complaint about this gym is the classes: they are the reason I joined, but they change every once in a while, and not in a way that suits my needs (but they may suit other people fine). The schedule is frequently inaccurate which can be frustrating to someone like me who has a variable work schedule. This is the sole reason I will not be renewing my membership (btw, they could not have been more clear at the time I signed up that membership would need to be canceled 30 days prior to avoid my card getting charged a full month. Come on, guys). My conclusion? This is a great gym with friendly people and quality equipment, but if you are like me and want to join solely for the group exercise classes, look elsewhere. Users/mooodavis
