
Services and Rates
 60 Minute Custom Massage: $85
 90 Minute Custom Massage: $125
 Hot Stone 90 Minute Massage: $135
 Reiki 60 Minute Massage: $60





 
  From therapy to pure relaxation, Davis offers a variety of Massage Services

http://davismassage.globat.com/test/wpcontent/uploads/2012/12/our_storymain1.jpg



20100515 nbsp Davis Massage Center is awesome!! I have chronic issues with my upper/middle back (trapezius, rhomboids and levators), largely because of being slumped in front of a computer for most of my waking hours.  Having recently relocated to Davis, I had been searching for a massage therapist that could provide therapeutic massage that would address my specific problems.  After experiencing a few automatic carwash massageswhere the therapist performs precisely the same routine on every client regardless of their actual needsI was delighted to find Amanda at DMC!!  I first went to DMC after my back had gotten pretty bad (to the point where I actually had a back spasm), and received a deep tissue massage from Amanda, and after an hour on the table I felt like a totally new man!!  I am delighted to have found my new Davis massage therapist.  If you need expert, therapeutic massage that is tailored to your individual needs, I highly recommend that you make an appointment with Amanda!!   BMoore Users/BMoore

Comment: I just wanted to give a HUGE recommendation for this place! I was in a car accident a couple months ago, and went to the Davis Massage Center for a series of massages as part of the treatment for my injuries. Not only did the massages help TREMENDOUSLY with my neck and back pain, but I had the added bonus of finding guidance in an extremely stressful situation. Megan Roberts, the owner, was so helpful in walking me through all of the insurance paperwork and making sure everything was in order. It was so obvious that she really cared about my health, and understood how stressful this situation was. She is an AMAZING massage therapist! Everytime I walked out of there I was feeling better and more relaxed. So, a big thank you to Megan! And anyone out there looking for a great, relaxing massage: youll definitely find it at the Davis Massage Center!!!   Meagan Gallagher

20081021 12:06:04 nbsp Megan was fantastic!  I havent had much experience with getting massages but her skills were amazing.  I am so glad that my wife recommended her to me.  I would highly recommend her myself to anyone who wants to unwind and relax. Users/isaackim

20100402 10:05:34 nbsp I can also highly recommend this service.  I have suffered from chronic low back pain for many years and have been seeing Megan Roberts, the previous owner, for many years.  I just recently visited and had a massage with the new owner, Amanda Lee, and I was blown away!  I have had many, many massages over the years.  My massage yesterday, with Amanda, was one of the best I have ever received.  I strongly recommend!   Richard Glass Users/rglass

20100810 22:14:57 nbsp This place was horrible, the worst massage I have ever had. They were late to begin with and I was waiting outside, the place was not even open on a weekday before 12pm. The room wasnt ready, the massage therapist was quickly trying to clean up the room as we were both  walking in. Not only did the place look shabby, but my therapist was sick! She said it was just allergies, however, she sounded like a frog and was coughing uncontrollably throughout my massage. I made the massage appointment because Ive been experiencing a lot of stress in my life lately and just wanted a relaxing massage. It is VERY difficult to relax when your massage therapist is coughing all over you. Now looking back, I wish I would just have stood up, got dressed and left, but I was really wanting a massage and wishing the massage would get better. This place is in a bad location where you can hear street traffic and it was far from relaxing when my therapist had to restart the relaxing music several times during my massage. I left the place feeling more stressed than I had when I came in and worried that I might get whatever cold she had. I also left with $70 less in my pocket, which was $5 more than their website advertised for a student discount. This place is a joke, and I dont recommend going there! By the way, I DID get whatever cold she had two days later!  Users/hamaleo11

20100902 09:19:45 nbsp Davis Massage is a wonderful healing place!  I am 61, and have received four massages from Amanda in the last two months.  The room is spacious, painted in buttercup yellow, and decorated tastefully.  Amanda is a gifted massage therapist. I was there when she had an allergy attack, and did not get sick afterwards. I have recommended Amanda to family and friends, and I have standing appointments to continue to avail myself of Amandas therapeutic services. I highly recommend Amanda at Davis massage! Users/MariPerla

20101108 15:39:14 nbsp This was the best massage I have ever had! Amanda is such a sweetheart, and gives absolutely amazing massages. I had been having back problems for weeks and by the time she was done my pain was completely gone and stayed gone for good. I will be coming here again for sure. I cant wait to go back! Users/EricWilson

20101117 12:57:20 nbsp I loved my massage with Amanda. She has an experienced touch and works deeply without causing pain. The studio is peaceful. I cant wait to return! Users/MarianHughes

20110227 20:02:41 nbsp Amanda was great.  I have had many massages and know what a great massage therapist is, and she definitely is one.  I look forward to my next massage.  A+ Users/DaveBuscaglia

20110419 10:41:47 nbsp Amanda is fantastic!  I went to see her after having neck and shoulder pain due to a work related stress.  Amanda was attentive to my needs and my neck and shoulder pain was pretty much resolved by the end of the session.  Definitely would recommend Amanda to everyone! Users/hsteele88

20110519 11:04:19 nbsp As pretty much everyone here has said, Amanda is quite amazing! Not only is she a great masseuse, but it has also been a delight to get to know her as a person. She really helped me out when my neck locked up back in January, giving up her lunch break to fit me in that very day. She was definitely a life saver! Since then, I have gone back twice to get the relaxation massage to relieve my muscles from all the stress I am under as a graduate student. She has always been very fun to go to, and does an amazing job. I feel great when ever I leave! I would definitely recommend her to anyone who has actual muscle pain or just wants a nice relaxing massage to help melt the stress away :) Users/rfm209

20110625 13:06:55 nbsp I have tried massages at many places over the years, and have always walked away feeling at least a little unfulfilled. I have paid big money for deep tissue massage, but it has never been deep enough, and therapists have never spent enough time in my problem areas. Just as BMoore pointed out, they seem to have to do their routine massage for some reason. I dont necessarily WANT my calves massaged! Amanda is the first therapist who has truly responded to my needs. She is strong, kind, intuitive and skilled. She spent almost an hour on my right shoulder both times I have seen her (went twice in 1 week!), and I feel like I have gotten something I have really needed for probably a decade. I recommend her most highly. Users/AmeliaBaurmann

20110811 21:19:57 nbsp Im very excited that Chelsea Bell is working here in Davis now.  Shes an excellent therapistshes good enough to put you to sleep, but shes also adept at treating problem areas (sciatic nerve, in my case).  During my last treatment with her, she worked my lower back, glutes, and legs for the hour, and my sciatic nerve really felt much better.  Im a grad student so Im stuck at a desk a lotIm really glad shes closer to campus now.  I highly recommend her.    Users/YossarianLives

20110901 21:08:17 nbsp I love, love, love massages (who doesnt?).  But Im picky.  I had my first massage at DMC, with Amanda.. and already Im so pleased...I think Ive found someone who really understands muscles.  Shes got great strength, sensitivity, instinct, and some awesome techniques.  Her studio is comfortable, professional, and centrally located. Already made an appt for next week.  Happy!  Ill have a few more massages before making a recommendation to others, but so far, so good.           Users/KariPeterson

20111006 12:02:47 nbsp I assumed massages were a dime a dozen until....Chelsea!  She was thorough, responsive, and listened carefully in those first few moments when we discussed what hurt and why I was there, areas that didnt hurt upon leaving.  After the second massage I asked why her technique was so different and why it was that I left feeling so much better  she mentioned terms like contact and flow which meant little to me, but if those words mean anything to you good, I am glad they proved helpful.  I highly recommend her and will continue getting my massages from her until I finish my PhD and return to rural Wisconsin where the massages arent so great.   Users/ajm15

20111107 19:53:17 nbsp Okay, Ive now had about 7 or 8 massages with Amanda and can confidently recommend her! 1) she is very professional and runs her business competently.  Shes always been on time, ready to go.  She knows what shes doing and never wastes your time. She finds out what you need and budgets the time perfectly. 2) It is really comfortable there! From the table to the linens to the music to the ambience to the aroma... its all fantastically luxurious, welcoming and nurturing.  3) Amanda gives an incredibly good massage. She knows how to work on problem areas, she checks in regularly on intensity and location.  Shes got some wonderful techniques that make a deep tissue, therapeutic massage feel like a relaxation massage.  I recommend her highly.  Users/KariPeterson

20111111 18:16:54 nbsp 20111111 Chelsea Bell is the one to see!

Ive been receiving massages for at least 7 years now, but never quite got what all the hubbub was about until I got a massage from Chelsea.  Her motto is relaxation and pain relief, which she literally executes with her hands.  Im very sensitive, so its hard to find someone who applies just the right amount of pressure so that its not painful, yet actually accomplishes something.  Chelsea listens to your problem areas and actually targets them during the massage.  During my last session, she managed to remove all my knots and soothe all my aching muscles; much better than Ibuprofen!  And even better, there are halfhour sessions available if youre in a hurry or a student on a budget.NancyPinard Users/NancyPinard

20111129 15:51:30 nbsp I am a avid runner that trains an average of 1014 hours a week. I contacted Amanda for I was in desperate need of a deep tissue massage on my legs after an intense training run up in Foresthill on Sunday. I could barely walk yesterday prior to my visit. After my 1 hour session w/Amanda I felt AMAZING!!! She is by far the best masseuse I have ever had and I cant wait for my next visit. She was very attentive to my needs and worked on my legs for the majority of the session. I am very grateful to Amanda  she is truly the best and a master @ her work!!!!!!!  Roxana Users/anaxor

20111222 12:50:37 nbsp I am 35 weeks pregnant and just had the best prenatal massage ever thanks to Chelsea Bell! She was all ready when I got there, room was nice and toasty compared to the brisk weather outside:) She was thoughtful and sensitive to my gigantic belly. She had lots of pillows to make sure I was comfortable. And gave me time to find a comfortable lying position. She was gentle but effective. Baby stayed asleep the whole time and I had no contractions or leg cramps:) And I feel great the next day! Actually slept well last night too! I highly recommend this prenatal massage! Best 1 hour of relaxation you can hope for at this point in pregnancy (especially with a 15 month old at home)! Thank you again Chelsea! Users/TheresaDries

20111227 02:40:30 nbsp Chelsea was amazing! Before I went to Chelsea, I was skeptical and extremely nervous about message therapy.  I always assumed that a visit to a message therapist would be much more uncomfortable rather than enjoyable. But after an 8 hour hike in Yosemite National Park, my sore muscles needed desperate help! Chelsea was amazing! She made sure that I was comfortable and did a great job at concentrating on my leg muscles.  I highly recommend her for anybody who is a firsttimer and hesitant about getting a message. She is also a great gal! She was very fun to be around! I am definitely going back given that as a grad student, I am always sitting at my desk, and therefore constantly experience back pain. Go to Chelsea! Users/BMH

20120213 09:35:21 nbsp Feb 2011: Outstanding massage! Chelsea gave me an amazing deep tissue massage, which really helped out with back pain and an IT band strain. Shes very professional, friendly, and attentive to client concerns. Ill definitely be coming back regularly. Im an athlete and have gotten regular deep tissue massages for the past 5 years, and this is one of the best. Also, the space is very cute and convenient!  Users/DoctorS

20120214 16:07:59 nbsp I had my first Davis Massage Center visit yesterday. Ive had massages from several different masseuses over the years and Amanda is one of the very best. My 1 hour relaxation massage was fantastic, and Amanda took the time to focus on the areas Id brought to her attention. The location is ideal and Amanda is very professional. I highly recommend Amanda and the Davis Massage Center!   Users/AndrewLightfoot

20120413 19:07:15 nbsp Amanda is Amazing!!!  I have been getting massages for over 20 years and nothing compares to the treatment I received today. Amanda is not only incredibly skilled, intuitive, and caring, but she listens. She focused on the areas that I mentioned were troublesome and gave her full attention until things started to shift and a shift is exactly what happened. My neck hasnt felt this relaxed and pain free in months. Wow such a treat. I will be booking a weekly massage from now on:)  Kia Users/phyllismeaux

20120509 14:19:25 nbsp I absolutely love the Davis Massage Center  after my first visit Im hooked! Im a UCD student under a lot of stress recently, and needed help with my very tense back and neck. Ive been to Amanda three times now for the relaxation style massage  and have never felt better. My sleep has improved dramatically, and so have my tense muscles. Amanda is great  she is professional, attentive to your needs and will take care of you. I highly recommend the Davis Massage Center! Im  really happy with the service here, and plan on visiting at least twice a month. Treat yourself  this is well worth the money, I promise! Users/YogiKaye

20120725 15:32:56 nbsp Chelsea is phenomenal! I have had massages from various therapists, and Chelsea is by far my favorite; and shes even better than those at large facility, professionaltype spas and the ones at five star resorts (not to mention you pay triple). It only took me one 60 min massage to be convinced, which I then subsequently bought a 10 onehour package deal immediately after. Anyway, I highly recommend Chelsea! I have to force myself not to go too often so as not to get spoiled.  Users/KenLoh

20121110 09:03:45 nbsp 20120811 Davis Massage Center is the place to go in Davis! I went for a deep tissue massage to get rid of knots in my back from sport climbing  and she did a great job! Also, she doesnt try and browbeat you into signing up for a monthly massage program like other places in Davis. I like to go for massages, not for sales spiels. Amanda is amazing, listens to what you need, is intuitive about health and bodywork, and is very sweet. Best massage ever. Users/AaronKutzer

20121115 13:16:14 nbsp Having a past life in outdoor sports and actively working in construction I probably need regular visits. My first time at DMC was extremely relaxing. Amanda asked about injuries or current pain and addressed them masterfully. My neck, shoulder, lower back, feet and forearms all feel so much better the day after. I would highly recommend DMC and especially the deep tissue sports style! Users/charlespersson

20130728 22:36:48 nbsp Davis Massage Center is great and I highly recommend it.  Chelsea is the best massage therapist I have ever had.  I get a relaxed massage and I always finish feeling refreshed and rejuvenated.  I also leave with all the former pains in my body completely gone.  Chelsea knows exactly the right touch and pressure to give, and is very receptive to your needs.  Again, I highly recommend Davis Massage Center. Users/BrandonHoward

20130804 03:14:51 nbsp I initially went to Davis Massage Center for a lower back and neck pain. After one session with Chelsea, I experiened a significant improvement on my symptoms.
It was my first time receiving a massage, but it turned out to be a fabulous experience thanks to Chelsea.
Highly recommended!! Users/BryanC

20130923 14:36:44 nbsp Amanda is the best massage therapist I have ever had. About a year ago, I started seeing Amanda for workrelated neck and shoulder pain. The pain is gone now, and I still go back  Amanda really knows how to reduce stress and put you in a good space. Users/jescheib

20140425 09:55:17 nbsp Chelsea and Amanda are incredible!!! For the past couple of years I have been going to Chelsea and my partner, mom and sister have been getting massages from Amanda. Throughout my last pregnancy I would go anywhere from once a month to twice a week and it was a lifesaver! I always leave happy and feeling great. Chelsea is wonderful at accommodating schedules, she will work with me and stay late so I can sneak by once the kids are asleep. I have recommended them to multiple people and everyone agrees, they are definitely the best! Enjoy!!! Users/cmfarinsky

20140523 16:55:59 nbsp My daughter gave me a gift certificate to Davis Massage Center as a Mothers Day gift.  Ive been going monthly to a different Davis masseuse for the past three years and have been getting massages for 20+ years.  Today I had a 1.5hr. massage from Chelsea and I floated home.  It was absolutely the best massage I have ever had.  The room is beautiful, the massage bed is extremely comfortable, and the music is just right, sort of Japan meets tropical rainforest.  (I loved it when the crickets could be heard). Every second was bliss, and the neckwork at the end of the massage was indescribable.  I felt like I was inside of a poem.  Chelsea is so friendly and picks up on vibes immediately  can tell if you want to talk or not, and checks in about the amount of pressure, if youre too warm or cold.  Oh  and when the hot towels appear, its like magic. I never heard her open the small microwave door to get them.  I can hardly wait for my grown children to come here and all of my friends. Thank you, Chelsea.  Ill see you every month!  Deborah Users/DeborahLattimore

20140601 16:45:08 nbsp I just had my first massage at Davis Massage Center and it was wonderful! Chelsea did such a good job of listening to my needs and working therapeutically on longterm and new problem spots. She was a pleasure to work with, and her massage was incredible—lots of varied pressure that kept my mind interested and my body happy. Her 1.5hour massage included head and foot massage and left me absolutely glowing and about as relaxed as its possible to be. Her massage room was calm and welcoming. I will be back! Users/EvaG
