http://www.daverosenberg.net/ David Rosenberg (also known as Dave Rosenberg) served on the City Council Davis City Council for a rare three consecutive terms from 1984 to 1996, serving as Mayor of Davis twice from 198688 and again from 199496.  With a stern hand and a sense of humor, Rosenberg was noted for running efficient meetings.  He was instrumental in developing televised meetings of the City Council, which soon became the best show in town.  Rosenberg was recognized by the Davis Enterprise as the Father of Downtown Davis.  During his term of office he was active in placing new lighting, signage, art and benches in the downtown.  He is credited with saving the Varsity Theater.  He brought in two downtown movie theaterparking garage projects, helped create the multimodal transportation facility, proposed and developed the teen center and Public Skate Park skateboard park, expanded the senior center, expanded Central Park and planned and built a dozen new parks in town, developed the South Davis Specific Plan, developed the East Davis Specific Plan, developed the 1988 General Plan, and championed the Pole Line Road Pole Line overcrossing and the Mace Boulevard Mace Blvd. overcrossing expansion projects.  In the late 1980s he proposed the creation of the Natural Resources Commission, which continues to operate into the 21st Century.  Rosenberg negotiated the famous PassThrough Agreement with the County which protects Davis from outside development.  During his years on the City Council  particularly from 19861990  Rosenberg formed a progressive coalition with Ann Evans and Michael Corbett Mike Corbett known as the Gang of Three which brought many environmental, social and housing innovations to Davis including a limited equity cooperative, cohousing cohousing, recycling, a declaration of Davis as a Nuclear Free Zone, and a ProChoice City.  Rosenberg has probably been mentioned more frequently in Bob Dunning Bob Dunnings columns than any living person.

Rosenberg also served on the Yolo County Board of Supervisors representing Davis, El Macero and Willowbank from 1996 to 2003, serving as Chairman of the Board of Supervisors twice.  He served as Chairman of the Yolo County Economic Development Council and as CoChairman of the Criminal Justice Cabinet, and served as the liaison to the Yolo Health Council.  Rosenberg also served as a member and Chairman of the YoloSolano Air Quality Management District.  He was the driving force behind the development and construction of the new, modern Juvenile Justice Center.  He participated in the development and construction of a new building for the District Attorneys Office, and a new Library in Esparto, and laid the groundwork for construction of a new public library in West Sacramento and in South Davis.  While on the Board he was instrumental in restoring fiscal health and a healthy reserve for Yolo County Government.  During his tenure on the Board of Supervisors, he focused on the preservation of agricultural land.  Growth and development was held in check, and urban growth was primarily directed to the existing cities.  During his term of office, the growth rate of the unincorporated areas of the county was below 1% per year, and some 97% of Yolo County land was zoned agricultural.   He negotiated on behalf of the county with the City of Davis a renewal to the passthrough Agreement, protecting the city from urban growth around its borders.  He signed an agreement with the City of Davis and the City of Woodland to prevent urban growth in the land between those two cities.  He negotiated and signed on behalf of the Board an historic agreement (unique in California) with the Rumsey Band of Wintun Indians which resulted in millions of dollars flowing to the county.

Rosenberg served as a Senior Advisor to two California Governors: Jerry Brown and Gray Davis.  For Jerry Brown he served as Deputy Appointments Secretary, helping the Governor appoint an unprecedented number of women and minorities to state government positions. He also served Jerry Brown as Deputy Executive Secretary and Chief of Staff.   For Gray Davis he served as Director of Community and Intergovernmental Relations and as Director of Operations for the Governors Office.  In these roles he negotiated with Indian Tribes, was the liaison with city and county governments throughout California, headed up the Governors community relations effort and supervised the Governors field offices, and made sure the Governors staff coordinated with each other.  He has served as Chairman of the California State Lottery Commission, Chairman of the California Law Revision Commission, and as Chairman of the California Victim Compensation and Government Claims Board (the former Board of Control.).  Additionally, Rosenberg served as the Ethics Officer for the Governors Office.

In 2003, he was appointed a Judge of the Yolo County Superior Court Yolo Superior Court, where he currently serves as a trial judge with a full felony criminal assignment, including felony jury trials.  By early 2010, Judge Rosenberg has presided over 80 felony jury trials in the Yolo Superior Court.  Judge Rosenberg has handled civil, family, and juvenile matters for the Court as well.  In addition, Judge Rosenberg serves on the Appellate Division of the Superior Court.  He also has taught other Judges at the California Judges College.  A noted expert on parliamentary procedure, Judge Rosenberg has taught Mayors, Council members, County Supervisors and Clerks parliamentary procedure and has published Rosenbergs Rules of Order which has been adopted by a number of California jurisdictions to govern the conduct of their meetings.

In 2007 Judge Rosenberg was elected Presiding Judge of the Yolo Superior Court by the other Judges of the Court for a twoyear term in 200809, and then in 2009 was reelected by the Judges to serve a second term as Presiding Judge of the Court for 201011.  He was also elected (by other Presiding Judges throughout California) as a member of the Executive Committee of the Trial Court Presiding Judges Advisory Committee, representing mediumsize Courts.  He is leading the effort to build a new Courthouse for Yolo County, and such a new Courthouse is planned to be constructed by 201213.

Rosenberg is also the Noteworthy Published Authors author of a science fiction novel entitled Endgame.  Rosenberg remains active in his community, serving several terms as Noble Grand (President) of the Davis Odd Fellows.

From 20052009, Rosenberg served as Noble Grand (President) of the Davis Odd Fellows, the oldest organization in Davis.  The Davis Odd Fellows Lodge was chartered in 1870 (known as Yolo Odd Fellows Lodge in those days).  Rosenberg transformed the Davis Odd Fellows from a quiet organization of 40 members to one of the leading and most active organizations in Davis with close to 150 members.  The Davis Odd Fellows Lodge is now one of the five largest Odd Fellows Lodges in the United States, and is the fastest growing.  As Noble Grand, Rosenberg presided over a complete remodel of the Lodge Hall, located at 415 Second Street.  He continues to actively participate in the Odd Fellows, both locally and statewide.  He is a member of the Board of Directors and Vice Chairman of the Odd Fellows Home of California which owns and operates two large retirement communities in Napa and Saratoga.  He also serves as one of the three Trustees of teh davis Odd Fellows Lodge, and as President of the Hall Board Association, a six member board that owns and manages all properties of the Davis Odd Fellows and Davis Rebekah Lodge Davis Rebekah lodges.  Rosenberg is recognized as a leader in seeking progressive changes for Odd Fellowship, and has brought a crosssection of the community into the Davis Odd Fellows Lodge.

He is an Honorary Member of the Rotary Club of Davis Davis Rotary and a member of the American Legion.  A 1974 graduate of the UCD School of Law where he earned his J.D. and was elected to Phi Kappa Phi, Rosenberg served as a trial lawyer for close to 20 years. He also holds a B.S. in Journalism from Cal Poly, where he graduated in 1968.  Rosenberg served as a First Lieutenant in the U.S. Army during the Viet Nam War era  from 196870, serving as a Special Services Officer assigned to Germany.  More information on Judge Rosenberg can be found at http://www.daverosenberg.net. His wife, Lea Rosenberg, was honored as Davis Citizen of the Year, was elected Most Dedicated Community Volunteer four separate times by the readers of the Davis Enterprise,  and remains very active, chairing numerous local organizations such as the University Farm Circle and Soroptimist International of Davis Soroptimists and serving as President of the Davis Rebekah Lodge and as a Board member of the Yolo County SPCA.  Rosenberg has two adult children (Jason and Janis) and a grandson (Jonathon).  He was born in 1946 in a village in Bavaria, the son of Jewish Holocaust survivors, who immigrated to the United States in 1949, and became U.S. Citizens in 1954.  Rosenberg and his family returned to Europe in 1958 where he attended Junior High School and High School, and he returned to the United States to attend College in 1964.

On February 4, 2014 a lawsuit was filed in Yolo County Superior Court naming Lea Rosenberg and spouse David Rosenberg. The suit alleges in part: David Rosenberg and his wife (Lea Rosenberg) are deeply involved — as either officers or directors — with a web of nonprofit entities worth millions of dollars known as Saratoga Retirement Community, Meadows of Napa Valley, Davis Odd Fellows, Odd Fellows Homes of California, Davis Rebekah Lodge, Soroptimist International of Davis, and others.

Lea Rosenberg — as the wife of a judge – was energetically raising funds from various businesses.

Judge Rosenberg’s judicial campaign treasurer, Victor Bucher, is a nationally renowned expert in the area of accounting and tax fraud, and also serves as the ‘treasurer’ of a separate nonprofit entity launched by David Odd Fellows — Davis Odd Fellows Charities, Inc. — where David Rosenberg serve as president and Bucher as Treasurer.

The suit alleges that consistent with the statutory framework put into place by 26 U.S.C. § 6104(d) — Plaintiff served a request for Davis Odd Fellows and Davis Rebekah Lodge to make available for inspection their IRS 990 forms.

Plaintiff delivered the request through Lea Rosenberg because she was the common denominator between the various ‘Odd Fellows’ entities and Soroptimist, in that she served as an officer and/or director of the various ‘Odd Fellows’ entities, and as president of Davis Rebekah Lodge.

The suit further alleges that Lea Rosenberg chose to ignore and otherwise breach the duty to comply with 26 U.S.C. § 6104(d). 

For more, please see:  http://lesliebrodie.blog.co.uk/tags/davidrosenberg/



 Links 
http://lesliebrodie.blog.co.uk/tags/davidrosenberg/

  http://daverosenberg.net/ DaveRosenberg.net



20090813 17:11:57 nbsp How can a person, whose family is a holocaust survivor, treats Mexicans and Black Americans like Jews, who lived in Nazi Germany and came before the honorable Judge with the name Roland Freisler. I personally do not believe that he tells us his true Biography. Even during his time as a Mayor he did nothing to correct and change the bad public image of Davis’s police. Users/schacht

20091025 16:46:57 nbsp I found his book Endgame in a random old box. Is it any good/worth reading? Users/MichaelGiardina

20121118 15:48:57 nbsp HAPPY BIRTHDAY, YOUR HONOR!!!!

Next November will be 10 years since Ive known you and your family.  Its also 10 years since you first became a judge in Yolo County! Users/AshleyHamidi
