

http://www.thedavisaikikai.com/ The Davis Aikikai offers instruction in aikido and weapons for adults and children. Adult Aikido classes are taught through the Experimental College and are open to all  you do not have to be affiliated with UCD to attend. Weapons classes require permission of the instructor. Childrens classes are open to kids 617. Exceptions are made to the age limit with permission of the instructor.

Aikido is a Japanese martial art founded by Ueshiba Morihei, reverently known as O Sensei. The kanji characters comprising Aikido (Ai harmony  Ki energy of the universe  Do way or spiritual path) can be translated as the way of spiritual harmony. Aikido does not teach defeating or beating an opponent. Instead, the student learns to neutralize aggressive energy by blending and merging with the energy of an attacker. Weapons work also constitutes part of Aikido training. More advanced students practice with boken (wooden sword) and jo (staff) before graduating to Iaido, the art of drawing the steel sword.

Since Aikido redirects the energy in an attack, people of all ages and sizes may become effective aikidoka.


Here is a video of Aikido weapons practice from the Davis Aikikai website:
http://www.thedavisaikikai.com/Davis_Aikikai_Jo_Work.mov(10.5MB)

Older comments can be found in the /Comment Archive comment archive.


20090109 13:16:11 nbsp Ive never heard of a sensei saying bad things about another sensei or dojo.
Its not inappropriate that an opinion is being expressed, but this is not just an opinion; its an appeal.  Its like someone standing outside of the dojo telling passersby to stay away.  It seems that this person has an agenda against the Davis Aikikai.  What is the purpose of attempting to dissuade others from discovering that which they may in fact enjoy?  Its presumptuous to petition others against trying something on the grounds that they would not enjoy it merely because the petitioner himself doesnt enjoy it.  It makes sense that one would not ask for others what they would not want for themselves.  But people want different things.  If one doesnt like dancing what is to be gained by dissuading others from trying it?Users/NilesRyan

20090224 13:34:36 nbsp Im certainly not an officially sanctioned spokesperson for The Davis Aikikai, but at times Ive felt like offering responses to some of the comments left here.  Thinking about it now though, if I was a prospective student, I wouldnt be deterred from trying the Davis Aikikai, even if the negative comments left here were much worse.  Even if I tried, I doubt Id be able to reverse any or all of the damage these comments may have caused in the minds of some prospective students, considering that each reader is unique and will have a unique reaction to a forum like this.  I think what Nick Howells wrote above is right; prospective students should try the class for themselves.  Also, I dont see an end to this kind of debate, it seems like some students who have a negative reaction to the class will always feel like writing their opinions in a forum, and maybe some students with a positive reaction will always feel compelled to respond.  Therefore, this will be my last entry in this forum.  My first Aikido instructor shared with me this sentiment, and I paraphrase, that people should strive to master the arts that allow them to be successful in life, and although its not for everyone, Aikido is a very good way.  So I hope you all find the right paths for you. Users/NilesRyan

20090509 11:49:25 nbsp My principal reason for commenting was an objection to the categorization of Birtsenseis teaching as simply nonWestern.  Given my past experience, and my impressions watching the class (reinforced by other comments here), I felt compelled to clarify the nature of Japanese instruction.  Perhaps I saw Birtsensei on a bad day, but that does not excuse his dismissive behavior.  It is specifically because I value Aikido highly that I wished to dissuade interested students from choosing this instructor.  I think it would be discouraging and unrepresentative of the joy that Aikido has to offer.  As for making such comments public, I agree that it would be inappropriate for another sensei to make such comments, since they have some interest in attracting students themselves.  However, the purpose of the DavisWiki is to inform new Davis students of aspects of the Davis community.  Consequently, it is an appropriate forum for discussing ones experiences as a student.  In fact, it took me several months to decide to actually post about my observations, and I only did so because my feelings were strong and others seemed to have had the same experience.  I also used my name because I did not wish to be sniping anonymously.  The post was not a fervent appeal for students to stay away, but simply my observations and a defense of proper Japanese teaching.  No doubt Birtsensei is quite skilled, and his class is conveniently located.  If, after reading the comments here, students still wish to train with him, more power to them.  Perhaps being forewarned about the teachers impatience will allow them to roll with the punches, so to speak, and lead to a more enjoyable training experience.  Aikido is a wonderful art and fosters a great community, and I urge all students to give it a try through whichever venue they think best. Users/EAalto
