
Davis Bike Exchange (DBE) is an amazingly versatile bike shop with a remarkably high Shadiness Factor. The owner, Rich, has been working on bikes for over 25 years. He parts out old bikes, builds newtoyou bikes out of them (selling them at very reasonable prices), and stocks many interesting new models. Rich is very dependable and the services you receive are of high quality and at a reasonable low cost.  DBE stocks parts not found anywhere else in Davis such as springer forks, banana seats, ape hangers, etc. If he doesnt have it in stock, hell pick you up any part he doesnt have.

The Davis Bike Exchange specializes in the used market.  Used bikes include any brands once sold new in other shops since their inventory is based on donations.  On any given day, you might find Specialized, Trek, Cannondale, Cervelo, Colonago, BMC, Schwinn, Fuji, Raleigh, Bianchi, Giant, Gary Fisher, KHS, K2, Jamis, Klein, Scott, Santacruz, Intense, Electra and other classic/vintage brands in their doors.

Be careful though, as with buying anything used. The DBE is not an authorized dealer for these brands and cannot help you with any future warranty issues, and they do not offer warranties on the bikes they sell.

You have to be willing to dicker and deal with Rich if you want to buy at the lowest price. Before you go, do your research and know both the value of what youre buying and how much youre willing to pay. That is, of course, if hes willing to deal with you. As the comments below indicate, he often makes it clear to customers that theyre wasting his time. He makes up prices off the top of his head. A number of customers have found the shop closed when they showed up during business hours.

Several people have bought used bikes or parts here only to have them fail within hours or days. Upon trying to return them, some have been refused, while Rich has offered to buy others back at half price. If you dont know enough about bikes to give yours a thorough inspection before buying, you might want to think twice about buying it heretheres a pretty good chance youre going to get ripped off, and then verbally harangued when you try to get the owner to make good.

If you have a bike that you dont want anymore drop it off down the street at Bike Forth

 See Also 
  Bicycle Shops  other bike shops in Davis
  Bicycling  a good starting point for your bikerelated inquiries




20050426 10:04:41 nbsp Shadiness factor definitely high  he quoted me a price on a bike that was $50 higher than hed told my husband a few days before. Admittedly, this is a small sample size, and there may have been a valid reason for the price difference. Id recommend paying attention to the condition of the bike rather than what he tells you about how little it has been used, because the two dont always seem to match up in our experience. He has a nice dog, though. Users/JessicaLuedtke
  If he just makes up prices on the spot for things (like you might at a garage sale), this might explain it. I expect hed give the cheaper price if you asked. Just a guess. (Historical note: The nonnegotiable pricing we are accustomed to came about when retail grew beyond sole proprietorship. The price stickers were for the benefit of the cashier, who lacked the knowledge and authority to adjust the price.) Users/SteveDavison

20050426 20:28:06 nbsp Probably the only bike shop in Davis where you can haggle, not that youll get very far... Users/ArlenAbraham

20050705 01:03:49 nbsp The guy who owns this place seems like he could give a shit if he sells you a bike or not. I think he probably launders money and that the bike shop is just a front. Users/BenTaylor

20050927 5:17:55 nbsp Two days before classes start and the guy is still backed up with stuff. The comment above saying the guy is there when he feels like it is definitely true. I came by today at 1:45 and there was a sign on the door that said will be back at 2:30. Sigh, I just want my bike back.... Users/AndrewLeonard

20051021 23:05:33 nbsp I was quite pleased with the service here.  I had two bicycles that were damaged.  Both of the frames and three of the wheels were bent.  The bike exchange was one of only two shops in town that showed any interest in fixing them at all.  He also gave me a much better price than the competitor.  This is because he actually fixes bicycles and doesnt just trade out damaged parts for new ones.  Every other shop told me that three of my wheels were damaged so bad that they would have to replace them.  The bike exchange only replaced one and that was only because I asked for a little better quality wheel.  He ended up getting both my bikes back in great shape and I didnt have to fork over loads of cash.  He does seem to slip off sometimes when he should be open, but just give him a call before you go so you know he is there.  So if you would like a decent used bike or to actually have your bicycle repaired give the Bike Exchange a visit. Users/JasonMoore
 Jason stated a different opinion on 20111009  Users/BruceHansen Art

20060531 20:00:38 nbsp I thought this place was awesome: a dank shop with some sweet antiques as well as some real junkers, and some kickass lowriders for good measure.  The place is virtually always empty, but they have EVERYTHING, unlike any other bike shop in Davis.  Before I found this place, I was convinced that no shop in town stocked chainrings or chainring bolts, or ANY used parts at all for that matter.  And the mechanic Trey is really cool, and appreciates customer interest in his work.  I dont know about anyone else who works there, but they all seem pretty cool to me.  In short:  if you want to pay way too much and get parts that are spiffier than you need, go somewhere else; but Im sure as heck sticking to this place.  And the bike church, which is also pretty neat. Users/CatherineCallaway

20070102 17:10:01 nbsp Ive always had good luck with Richs Shop.  Hes pretty cool and does an excellent job building wheels.  Hell also build you a bicycle if you have special needs. (He built my wife a nice small mixte) Users/RichardJacobsen

20070129 15:48:59 nbsp I love this place.  Granted, Ive only had flats and other minor problems fixed.  But he always seems to do it in good time, and charge me very reasonably.   A few days ago (1.25.07) he fixed a back tire flat and replaced a broken spoke, for a total of $14.  He has always seemed friendly and easygoing.  I think he must just work for the fun of it, since he clearly doesnt go out of his way to act professional or make tons of money.  Anyway, I like it and I highly recommend him to anyone who needs their bike fixed up. Users/NaBarry

20070310 19:37:05 nbsp Pretty bad service, I dont plan on ever going here again. My roommate and I went in looking for a part but didnt know exactly what we wanted. So we asked him a few questions. He responded in an annoyed time and said you are wasting my time. Also, when my roommate went to check and make sure that a part was the right size he angrily asked if we were calling him a liar. As someone else said, he doesnt seem to give a shit whether or not he sells you anything. I literally felt like he was only one step away from kicking us out of the store for trying to buy a part. Terrible Customer Service. Users/ZackFrederick

20070310 20:33:38 nbsp I have bought two bikes here plus various parts and have always had good experiences. An awesome place. Users/NickSchmalenberger

20070311 00:37:49 nbsp My dad swears by this place Users/StevenDaubert

20070705 20:21:16 nbsp I talked to the owner on the third and the landlord is trying to evict the shop. I am deeply saddened by the potential closing of yet another long standing downtown business. I am also angered at the landlord, those of us who wish Davis to remain the bike capital of the US should take notice. Users/Chadsharply

20070925 01:21:31 nbsp Worst bike shop experience ever. Extremely rude and didnt care if anyone bought anything or not. I hope they go out of business so they dont turn people off to biking! I went in there to get a used front wheel for my bike. The guy showed me a wheel that was old and crappy though he said it is a damn good wheel that is easily worth $90. I said that was too much for my old crappy bike. He was told by the owner to promptly put the wheel back. They then said that I was wasting their time and they had too much to do. Businesses who think they can treat people like this should not get any customers. Im surprised they have persisted this long. Users/Tmai

20070925 02:25:56 nbsp
Tmai: You have mistaken your preconceived notion of what a business is (no doubt you were educated as to dealing with corporate clones in your previous South Bay Silicon existence: i.e., WalMart, etc.) for reality.
Fyi: Rich is the guy who runs the Bike Exchange; a friend of mine. Let me tell you hes used to dealing with human beings secure in who they are, not insecure clones like you tried to be, Tmai. Go back, be a man, deal with Rich like the human being you really are, not a clone. Then see what happens. You might be surprised out of your clone self into actually getting a good deal.
Respect goes a long way among humans, my naive friend.
Users/WilyFerret

20070925 22:28:35 nbsp This place is shady and very rude i suggest not ever going there bad news!!!!!! Users/Brians

20070930 14:48:31 nbsp Owner was rude as hell, refused to even speak to me because he hired someone to do it for him as he told his friend he was talking to, so he yelled at one of his employees who was outside 100ft away (yelled rudely, like a total prick, to come help me, even though he was standing right there) and when the guy came to help me, he didnt have a damn clue what the hell i was talking about anyway (apparently a 700c wheel is a special size these days, wtf?) and the owner refused to speak to me so what the hell was i supposed to do? He also refused to discuss the sale of a couple things he had on display, its not a showroom, its a bike shop. The frames/bikes I was interested in were rare, but not insanely so, and they need to be built and ridden and loved, instead of sitting there. That crusty frame will sit in the back never being used because the owner is a rude asshole. Bikes are meant to be ridden, not looked at. Users/GarrettGallegos

20071014 03:46:03 nbsp This was the only shop that would fix a wheel for me.  It was an odd wheel from an old Austrian bike, a Steyhr, with broken spokes, etc.  Kens, B & L said theyd have to buy new hub and rim too dangerous otherwise!  This dude did it fine and polished it up for 25.00, which I was happy with considering Id been riding on it anyway.  Rumor has it the shop is moving next to Aggie Liquor, which Im kind of happy about.  I actually think it will improve his business. Users/JeffShaw

I too have a very bad experience at this place. The guy is one of the rudest persons that i have ever come across. Users/SoumenRoy

20071027 12:26:15 nbsp The worst bike store. Thought it would be a great place for used parts and repairs, but the owner was a total prick each time I visited...EACH TIME. The first time, one of his employees handed over two rusty screws to me and said, no charge, but the owner wanted $2. I just turned around and walked right out the door with screws in hand. Not that I like it, but thats just the sort of way I deal with them now. It should be called the bike dump. I think theyve recently relocated to 5th and L.  Users/Manlaw

20080108 13:16:13 nbsp I went there for a set of front cones  he seemed highly uninterested in helping me, and told he couldnt give a shit looking for individual cones in his drawer of cones+axles, and that Id need to buy a set. Fair enough, I suppose. His assistant takes a look at the old cones I brought in, and finds a supposedly compatible axle/cone set. I take it home, realize its the wrong size, and come back the next day to return it. Holy crap, what a dick. He starts bitching about me to another customer, about how Im wasting his time because I dont know anything, etc etc. He spends more time whining than the time it takes to actually open the cash drawer and give me my $5. Users/StewartShearer

20080301 17:58:57 nbsp Rich fix my daughters flat tire in minutes not hours like the other snobbish bike shops in town. Rich and I had a good conversation about the old days of bikes. His impressive collection of old tricycles and bikes is to not be missed. With the smell of WD40 in the air my daughter smiled when she got on that bike again. He make look like an intimidating Marine but Rich is a soulful character fixing bike in Davis one at a time. Users/kswanson

20080314 16:25:40 nbsp This is the only place I trust with my bike. Both of them know a great deal about all kinds of bikes and have been really helpful. And Court TV is always on in the shop, so theres an added bonus. Users/elliottpollard

20080320 16:43:42 nbsp I took my bike here for a tune up recently. They were helpful and answered all of my questions. They didnt even get annoyed when I said I wanted new tires then changed my mind at the last minute.  The tune up itself was inexpensive and my bike was ready when promised. So far the bike is running smoothly and I have no complaints. I would recommend this shop to anyone.  Users/GabeDavis

20080605 15:05:23 nbsp Overall a bizarre store. One time you go in there and he is nice as can be, other times he is ultra surly. If you can deal with the curmudgeon of an owner they have some neat vintage parts and bikes. I was going to get my girlfriend a bike here but his attitude totally turned me off and I took my business elsewhere.  Users/schester

20080620 13:20:29 nbsp HORRIBLE SERVICE!! I bought a bike from them and it broke in about 5 minutes, when I took it back they were VERY rude and not at all happy about repairing it. They gave me a really crappy, bent chain and NEVER had the bike ready on time. Rich is a lot nicer and more reliable than the little guy, so if you do go here, deal with him. Overall, Id advise people to go elsewhere.  Users/littlelove

20080626 02:31:18 nbsp Dont waste your time. Poor service...actually none. Not a bike in the store worth 5 bucks. Nice Motobecane sign out front, Im sure they are an official dealer!?! Users/Helikid

20080626 11:37:57 nbsp This is the only place in town that was willing to work on my 1966 BSA bike with a Sturmy Archer 3speed and front drum brake. Fixed everything up and charged reasonably. No, the guy didnt go to charm school, but he was interested and able to work on my old bike that no one else would touch.  Users/Annamaria

20080729 19:34:21 nbsp One time I didnt have enough money and Rich let me slide. Walk in there with confidence and youll survive. Overall not a bad experience.  Users/AvidSpots

20080730 01:18:29 nbsp My Sturmey Archer trumps Rich, its to old and to rare Users/StevenDaubert

20080912 10:43:02 nbsp haha I like this store a lot.

I was in there checking out some frames and a freshman came in with his dad.  he asked if he could get a fixie and i heard something along the lines of

I dont waste good frames on things like that.  just put it in a gear and dont change it

RESPECT Users/aechanio

   Actually, they are now building fixed gear and single speed bikes since there is a lot of demand for them. Users/KellyM

20081003 17:27:29 nbsp Basically a thrift store full of junk parts.  Mediocre service (customer service, not their work) at best, although the older guy didnt seem to bad, the mechanic was not friendly at all.  Come here if you looking for a cheap junker to ride around town.    Users/jcoffman98

20081008 18:26:13 nbsp Definitely not everybodys cup of tea. not the shiny, bling, bling modern day shop. rather, think auto mechanic for bikes. best shop for those going low budget or those interested in keeping old favorites going strong.  rich is a walking bike encyclopedia, so the older, the gnarlier the better. he loves bikes. people, he can do with or without.  I recommend knowing what you want, or want to ask, before you head in. dont get all hoitytoity on him, cause he knows his shit even if he doesnt sound like your average collegiate staffer. if you catch him in a mood, ask him how the fish have been bitin, because thats where he goes off to do when you cant find him. and, no, not a huge new bike inventory. Users/dockao

20081018 16:54:04 nbsp Dont go to there! Rich is a total asshole that couldnt be reasoned with at all. In my whole life, I have never been so intimidated by a business owner. Users/v99erik

20081019 13:39:15 nbsp I was not really happy with the shop. I bought a 2nd hand Mongoose XR200 and it cost me $125. The bike broke down frequently, and I need to bring it back to them to have it fixed. I feel that the shop owner doesnt really care about me because I am a new customer I guess, and I feel that the employee was quite rude sometimes. The paddle was actually not the same pair! I guess he thought I am annoying. Finally I sold back the bike to them at half price, and I bought a new bike (Trek 7.2FX) from Free Wheeler. Even though I lost $62.5, I am glad that I dont have to use that damn bike anymore. Users/edwin2005hk

20081020 11:38:19 nbsp Although it can be a stressful experience dealing with the staff, this place is really tho only place in Davis that will work on a vintage bike. I had a wheel built here and I have to admit its served me well the last few months. Reasonable pricing on service, but its usually cheaper to get the parts you need online. Beware crankiness and prepare to be shunned when you walk in the door. I probably wont be going in anytime soon because they seem pretty sick of me asking questions but not buying anything. Users/TheWigglyWizard

20081207 18:28:30 nbsp I found my stolen bike on a rack here. I had receipts for the parts so they gave it back to me. Still isnt clear how it got there... Users/AndrewPeake
  Wow, that doesnt sound Shadiness factor shady at all. I think I might avoid this place, unless my bike gets stolen...Users/JoePomidor
  True, but it must be hard for any used bike shop to avoid this problem unless they were to run every bikes serial number and description by the police before buying it (and if there were a cost effective way to implement such a system, Id be all for it).

20090117 17:38:50 nbsp I love bikes, all sorts of bikes, know bike culture, and know great bike stores low rent and high rent all over the world  and this one is a bottom feeder. The character (Rich? or plain Dick?) presiding over this expensive crap actually knows next to nothing about bikes (whats a quill stem?), which he tries to cover up with the abuse and general weirdness. We are chumps if we think that this is some sort of authentic soulful Olde Tyme experience that tests manhood. If you want to talk about fishing bait, try a fish store. This store can only get away with it in a college town too polite to tell anyone to f off. So no, this place isnt the alternative to chain stores, and probably Davis still needs a friendly place dealing in beater bikes and old stock. In the meanwhile, go to your local independent bike stores for new stuff, check CraigsList for old stuff, get advice and parts from http://www.sheldonbrown.com/, see if local thrift stores or the Bike Barn or auctions on campus have a used bike for you, support local builders for fixies (a fixed wheel isnt riding a bike in one gear, boom boom), and see if mending your own flats is quicker and cheaper in the long term.  Users/Biggins
 If they rebuild wheels and frames, and the customers are happy with that work Id say they are probably at least as competent as the other bike shops that mostly sell new bikes. Several comments say he did work other shops wouldnt do and he did it well (JasonMoore, JeffShaw). Also RichardJacobsen says he does build bikes, so if he doesnt like fixed gear bikes oh well. Apex Cycles does build fixed gear, but I think Ill still go here if they are open...  Users/NickSchmalenberger

20090120 14:49:14 nbsp I bought a new cruiser from Richard that was too high. He personally adjusted it for me free of charge. Also, every time I would get a flat tire, he would pump it up and add the green slime so that I wouldnt have anymore problems. When my bike lock was stuck, he put WD40 in it and fixed it for free.  Users/Aiphi

20090124 12:44:50 nbsp This guy was the biggest self important dick I have met in a while. I went in to his store to buy a tube and adapter for a bike I was selling. I asked him for some information about the bikes value and he responded with an opinion that was so low as to be ridiculous. No matter, I put the tube in and met the buyer out in the parking lot so if they needed any parts for the bike we could get them  right there. Im talking with the person and Rich comes outside with some serious attitude and says what are you doing in my parking lot. He said you need a business license to sell bikes in this town and he was going to call the police on me for selling a bike without a license. I politely refuted his assertion and said we were there so if we needed parts to complete the sale we could just buy them right then. He threatened me again with the police and said he owned this parking lot and asked me to leave. It was amazing how angry he got when I told him to just call the police, but I wanted to continue the transaction so just went across the street. I was not doing this as a business, just my own personal bike. I will make it my personal mission to tell everyone I know just what a bad experience I had. In all my years, I have had very very few business experiences like this. I hope he goes out of business soon. Users/demoman

20090203 15:24:44 nbsp I agree about the Shadiness factor. I came in looking for a bike, they told me they would put in $100 dollars worth of tune ups and repairs and sold me the bike for 175.  Since then I have had to put a lot more money having the wheels trued, the breaks redone, gears adjusted and tightened, etc.  Basically, they sold me a lemon.  When I confronted them about it, they blamed all the problems on myself and how I take care of the bike, and wouldnt fix the bike or refund me part of the money.  This place sucks! Users/arip

20090322 11:28:06 nbsp A good shop with dogs. A friend was having trouble with a bike from there and also with the staff. After a hard haggle the transaction was reversed. That was really sympathetic. I cant wait to see how Rich handles these darn cotter pins on my dads old bike. :) Users/lilmonstu

20090423 12:01:39 nbsp Went there a couple of months ago, but forgot to leave a comment.
The place was really shady, and neither of the two guys who were there seemed to know anything. I was looking for a pair of new 26 tires (standard mountain bike size). They said theyve never heard of the size and asked me what it was in cm (which is used usually, only to measure road tires such as the standard 700cm). I dont understand reading all these comments and judging through my personal experience how these guys manage to stay in business. Users/Oleg.Lokhvitsky

20090524 22:08:09 nbsp Ive never had anything but excellent service here since buying my bike from Rich several years ago. I was lured away to another shop briefly (Im a sucker for coupons) but when I came back to DBE for a flat fix, Rich noticed a problem that was obviously a result of recent service (I couldnt say what it wasIm a complete dilettante about bike stuff and am never made to feel like Im wasting their time by my questions.) He fixed it and I renewed my loyalty and was off. (He even worked on the brake on my moms fourwheeled walker and didnt charge anything for it.) Users/CathyYoung

20090630 15:58:12 nbsp Brought in my bike with a flat back tire. Told to come back in 2 hours. Returned after 2 hours and my tire was still flat. But the guy fixed it up right in front of me in like 2 minutes. Rather impressive, actually. Cost around $12. Ill return if I ever get another flat. Users/JustinAi

20091022 12:17:19 nbsp I will never go to this bike shop EVER again.  The two guys that run this place do not belong in any kind of industry dealing with customer service.  The owner made me feel like I was an Ahole for wanting to take a bike off the rack so I could take a look at it.  They made me feel like I was putting them out just for being in their store.    Users/trevorchreid

20100311 20:01:31 nbsp Not only the worst bike shop but the worst place to visit in Davis. Asked me to show him the cash before he would take out a $20 used part from the display window. I had cash but seriously who would actually show him the cash and buy from this shitty man. Users/FUDBE
  Wow, I just read the comments about this place, and... wow.  Sounds incredibly shady and unbelievably rude.  Why does anyone still shop here? Users/TomGarberson

20100423 15:25:09 nbsp Aholes. I called to ask about tuneups and the guy was incredibly rude!!!! I asked him what was included in a tuneup and he said the list too fast, so I asked if it included brakes and he yelled at me saying that he already said that. Thinking he was joking I laughed at him and asked what time they were open til and he hung up on me. I was so angry. I would never ever take my business here. Users/Ilovetacos

20100527 11:58:00 nbsp I will never spend money in this shop. Yesterday I witnessed a shouting match between the employees/hangerson of the Bike Exchange and an AfricanAmerican guy they accused of panhandling at the other end of the shopping center. The four Bike Exchange dudes stood on the sidewalk and traded raciallycharged insults with the man, then threatened to stomp him. When the man left, they laughed at him and called him a p_ssy, then patted each other on the backs and traded highfives.

It was like watching a group of teenage jocks bully some kid in the high school hallway. I grew up in the south, where this sort of thing is more common. It was sickening there, and I wont support it in Davis.

Im a Davis cyclist, and the Bike Exchange is the closest bike shop to my house. I can say with 100% determination that the Davis Bike Exchange will never get a dime from me, and I hope others take into consideration where there money goes as well. Users/MupDup

20100726 14:44:18 nbsp I got into an accident and my poor bike looked like a mess. The handlebars were bent out of shape and the brakes broke. Rich fixed her up in a about 20 minutes or so and even re wrapped my handlebar tape while talking about the old days when he worked at the Schwinn factory. Plus, this was done free! I dont understand why so many people are writing bad reviews about this place. You just have to know what you want and do your research beforehand! )

Also, Ive brought my bike here for an overhaul and now she runs like she just came out of the factory.  Users/hyangdan

20101101 22:24:09 nbsp While I will agree that this bike shop, or at least the idea of it, is a good concept, it need some kind of control or system of checks and balances. Just last week a blond haired kid (18mid 20s) was riding a bike and stole another one from my apartment complex just down the street and took it over to the shop. No doubt he was using the Bike Exchange as a pseudo chopshop which I think is not good for the community at large nor for the shop specifically.  Users/WesP

20110426 16:29:37 nbsp If you have an old bike that needs some fixing up, come here. Rich and co seem to know what theyre talking about when it comes to older bikes especially. I took in an old bike that needed its frame welded, and they took care of it very fast. theyre customer service isnt great, but as far as Im concerned that doesnt matter if they do a good job, which they did. they didnt call me when my bike was finished, and they were slightly unfriendly on the phone when I called, but when I arrived to pick up my bike they were nice and the repair was pretty cheap. also, APEX bikes did a tuneup on my bike a few weeks prior to this, and I didnt think they did a very good jobRich confirmed, and laughed when I told him I took it to APEX.. turns out, APEX didnt even grease my bike up or do several other small things that should certainly be included in a $90 tune up. will definitely return to this bike shop over APEX. While they might not be the most friendly people here, and they may not provide the best customer service, they do a good job at what they do and thats all that matters in my book. Users/rcrane

20110515 11:03:19 nbsp I dont know why some of these people write negative remarks about a bike exchange that happens to have tons of parts ive never seen, handlebars from 5$ and up, and cheap bikes. Yeah they may ignore you if you are asking too much of them, because Rich knows what he is talking about when it comes to bikes, and has been in sales, and bike manufacturing for over 20 years. You guys all give him crap, because you compare his business to Cycleworks, B&L Bike shop, and Apex.. Well if you want to get talked down upon for only having 800$ to drop on a road bike at Cycleworks, then go for it. But here, he talks to you regardless and if you buy a good bike, he will make sure you get a good deal/price for it. I bought a Trek 1000 there yesterday with Ultegra Crank, F. Derailleur, and the rest of the bikes Shimano Components (Tiagra, Sora) for $400.00, which for the quality of the bike, was a good buy for a Road bike. While the bar tape was worn down a little bit when I left before picking up the bike, Rich and his coworkers tuned up the bike completely and made it look brand new. It was beautiful!

I will definitely return to the Davis Bike Exchange! Users/RonaldMegeath

20110706 18:30:54 nbsp This is the only place I will go to for bikes/bike parts. Everywhere else is ridiculously overpriced. Staff was very friendly and helpful to me. I bought a Schwinn Womens comfort bike here back in April and they gave me a 4 month gurantee that if anything goes wrong with the bike to just bring it back and theyll fix it free. Have never had a problem with this bike and loved the smooth ride and comfortable seat. I was recently hit by a car and the bike was banged up pretty good so the first place I thought to bring it to was here. They greeted me upon my entering the store and said theyd have my bike fixed and ready to go by Friday and gave me a good estimate on what the repairs would be and even said that if for some reason I couldnt fit the bike in my car or ride it home that theyd put it in their pickup truck and bring it to my place. No its not your fancy downtown bike store but it is a good place to buy a bike or have it repaired. They have good used bikes, unlike the ucd bike auction that sells bikes that are broken down impounds. Users/KathrynAzarvand

20110824 22:30:25 nbsp I wont go back to this bike shop... I bought a used bike for a day and when I brought it back the next day for a refund (personal reasons... aka I cant ride a bike to save my life) the manager told me that he would buy it back for half price.  AFTER A DAY!  No reasoning with this guy....  Users/RobinTrevor

20110917 19:33:28 nbsp Bunch of unhelpful, grumpy, unprofessional workers behind the counter.  Would not recommend. They are slow, and they dont do the job right. They are very rude. Users/EthanHall

20111008 19:29:37 nbsp If you have come onto Daviswiki looking for reviews of Davis Bike Exchange, then I implore you to listen to me. Right off the bat, DO NOT under any circumstances, give this shop your business. Avoid them like the plague. Allow me to explain. I am not a singletime disgruntled customer. I have purchased a whole bike and several parts here over the past years. In those times, my experiences were unfavorable, but were never enough to dissuade me from a bargain. However, my perspective of this business has changed permanently. The shop is owned by Rich and he employs three to four employees who seem to work there daily. I use the word work very loosely. Today, I went into the shop to check out steel forks for a bike I was building up. I made the mistake of picking up a fork from their sorry excuse of a bike rack. I was instantly scolded by one of the employees who said, Do you just pick up things that dont belong to you. I apologized as I was aware of their attitude prior to entering the store and rubbed it off. I later asked the owner, Rich, if the crown race I had would fit on the fork. He proceeded to remove the previous race and attempt to install mine. He gave it back to me.....crooked. I told him I would buy a fork anyway and think about the installation later. I noticed several deep scratches on the side of the fork. So I asked if I could get another one I spotted that seem to be in better condition. In an instant, he went from bearable to outright hostile. He told me I was wasting his time and that it was close to closing. The shop closes at 6 pm, it was 5:11...I was initially shocked. I told him I didnt mean to waste his time, I just wanted the fork I wanted. He told me to get out of his store. I simply retorted with ok and left feeling insulted and furious. I apologize if this is lengthy. However, I could not, in good consciousness and being a decent human being, allow this injustice to go unnoticed. I do not want anyone else to experience this. No one deserves that kind of rude service. I sincerely implore you to never EVER shop here. I concede that they sell cheap bikes and parts; but many of which are suspect to being stolen. I am slightly suspicious of the positive reviews. I cannot comprehend why they would hold them a good light. At the same time, give some weight to the negative reviews, I can vouch because I have either seen or had similar experiences when I was a patron there. If you want good service, go to the other various bikes shops in town. At the very least, they will treat you with dignity. Read the reviews, do your research, and ask yourself...How much is my selfrespect worth? Users/JonathanLuong

20111009 10:06:56 nbsp Jonathan, I know the feeling when you go into this shop to purchase something and are asked to leave.  Obviously the reason I was asked to leave was because I had commented at a gas station to Rich about a dog that that he had previously taken car of in his shop.  I later learned that people associated with the dog had ripped Rich off.  Still that was not a valid reason to insult me.  I suggest to all that rather go into the shop to be insulted, let Rich have what he maybe wants:  everyone stay away from the shop. Users/BruceHansen Art

   I am sorry you were treated in such a manner. His behavior towards others is outright negative, if not an oddity. It is a good thing that discourse is growing and that we can warn people. Still, you did not deserve to be spoken to like that and I wish you only the best.Users/JonathanLuong

20111009 15:07:01 nbsp I wrote a favorable comment about this shop on 20051021 23:05:33 not too long after I first moved to Davis. This was after my first experience at the shop where I fortunately did find someone in Davis willing to fix my bicycles for a reasonable price. I went back to the shop two more times within the next year or so looking for odd parts and was subsequently treated like crap by the owner, Rich, for no apparent reason. I unfortunately never rectified my original favorable comment about the shop and after reading so many comments about the poor business practices and attitudes of the shop employees, I wanted to chime in that I completely agree. After I was treated bad, I have refused to return or to recommend anyone to go to this shop. I can only imagine that he is able to stay in business because Davis has a transient population that is always in need of bicycles. The new folks in town have always gone to the only bike shop in town that sells somewhat inexpensive used bikes unknowing that these guys are jerks. I cant imagine that he actually has any returning customers. I recommend avoiding this shop especially since there are at least four relatively new bicycle shops (The Bike People, Blisworks Bikes, Apex Cycles, and Bike Forth) in town that can help you purchase a used bicycle and actually be friendly and helpful when interacting with you. I want to note that I am certainly biased, as I cofounded the Davis Bike Church/Davis Bike Collective and that I am also posting this comment because Rich recently called the cops on both the Davis Bike Collective and The Bike People because he assumed we were practicing without business licenses. That certainly is not a very neighborly thing to do, but fits well with all of the other descriptions of him on this page. Users/JasonMoore

  I would also like to add upon Jasons comments. He appears to hold much animosity to other bicycle shops and organizations within Davis. I know for sure that he spoke very ill of the Davis Bike Collective and called them, beatnik hippies. I find it humorous that he doesnt realize how outdated his choice of words were. Secondly, I found the volunteers at DBC to be kind, helpful, and patient. I am not surprised that Rich called the police on DBC and The Bike People. Although, I wish it could have been the other way around... Users/JonathanLuong

20111009 16:59:19 nbsp If Rich wants to start with sone customer service, he could ask Chris to help him get in touch with me.  Users/BruceHansen Art

20111208 15:04:44 nbsp Price of new 27 inch tires here:  9.95.  CVS has them at 12.99, Ace only has folding tires now.   Cheapest at the bike shops with friendly people I could find was 14.99. Users/JeffShaw

20120207 18:44:13 nbsp This is a great bike shop. There are good bikes at good prices and the guys know what they are doing.  I bought a bike there that was actually big enough to fit me (which is hard to find because Im very tall) and it was in great condition.  Im very happy with it.  I brought it back a couple weeks later with a problem and they fixed it up for me free of charge.   Users/KevinKraft

20120209 15:37:22 nbsp Im sure like all of us, these folks have their good days and bad days. Treating people with dignity and respect no matter their appearance and giving them a chance is helpful here. Have had some experiences that people have described, but have borne through them and actually recd some very helpful, truthful information and great service on my bikes. If you are a townie versus a student you are probably better off here. Users/omrob

20120304 17:36:25 nbsp HORRIBLE.  Apparently, Im wasting his time (the guy working on the bikes, who I assume is Rich).  I think a lot of people have been wasting his time.  I DO NOT RECOMMEND. Users/WredMarc

20120404 18:11:41 nbsp This place was perfect. My road bike was completely messed up, front and back wheels were bent, frame was bent, and the pedals were twisted. (the reason my bike was so banged up was because it was hit by a car). Before I went to them I went to Kens Bike and Skis and they told me I may as well get a new bike. However when I went to the Bike Exchange they told me they could fix everything at a price below one hundred dollars and do it within three hours.I was doubtful at first but when when I came back three hours later my bike as good as new. I could not notice any damage that had occurred to it previous. I highly recommend this place to everyone. Cool people and excellent service. I am definitely going there from now on. Users/DeanPernas

20120616 16:35:53 nbsp If for some reason you like being insulted and inexplicably thrown out of the store by an erratic and aggressive individual, then this is the place for you. Otherwise, avoid at all costs. To be honest, I still dont completely understand what happened when I went in the other day  walked in, asked a question about a product I wanted to buy, then found myself a few minutes later thrown out on the street, stunned. Wowza.

The only thing I can think of how this guy is still in business is that there is a warp in our timespace consumer continuum there. Or that he’s a moneylaundering front. Or a fence for stolen merchandise. Or a very longrunning punk’d skit. Pick one! Users/BettyWashington

20120705 10:08:37 nbsp i always bring my bikes here. he is a fantastic wheelsmith and whenever he trues my wheels he gives me a 2 for one price, because i come there all the time, i am respectful because he knows what hes doing, and im the customer, who needs to talk to someone who knows what they are doing. so i think through this mentality i have always had good experiences here. once i even traded him a real nice, new mountain bike for one of those badass lowrider cruisers hes got. anyway, great place, if youre not a jackass. Users/mynameisGIL

20120829 10:56:08 nbsp Do not deal with this guy. Last week my daughter and I picked out one of his used bikes to buy. An employee told us a price and said he would have the agreed upon handle bar change and kick stand added by an agreed upon time a few days later. I offered to pay at that time but was told to pay when we picked it up. When we returned nothing had been done and the owner was obstinate and abusively said many others were in front of us. He also said he didnt ever do anything unless he already had been paid. My daughter had bused over from Sac. and he said our problems werent his problems and to get out of his store. We were so amazed and frustrated we couldnt believe he was in business. Please dont do business with this unreasonable, abusive and frightening character. He really shouldnt be dealing with the public. Users/chuckroe

20120830 11:07:01 nbsp I will never use this bike repair shop. This shop may be inexpensive but they have no customer service skills and could care lessI believe what AnnieDavisowitz actually means is could NOT care less if you were satisfied with the repair. The owner hungup on me for no reason other then not wanting to hear what I was explaining to him. I brought my bike in for a simple flat tire. I had my bike outside my back door, so I know it went nowhere and today, about two and a half weeks later I went to ride it and it is completely flat! I asked if the tire really was replaced (the inner tube) or what was I to do or think? He said I can tell you if that is what it needed then thats what was done and hung up on me. Real customer service. Strange that it went flat without ever taking it out for a spin? I can not trust this shop and their work, and I would never recommend them to anyone. There are several bike shops in Davis that actually care about their customers and stand behind the work that they do, then to wast time on a burntout shop owner who does not give a damn about his work or reputation or curiosity to customers. Save a big headache, and your hard earned cash, and go somewhere where they care about you and the service they offer!
 Users/AnnieDavisowitz

20130702 15:41:37 nbsp Today the owner exhibited the most rude, nasty, angry behavior Ive ever experienced in a Davis shop. My guest and I had gone into the shop to buy a bike for one month after which he would buy it back for 50%. For visitors here 13 months only, its been a winwin deal to provide them with  transportation at a reasonable cost. However, today I tried to talk to him about a brake problem with the last bike, and he simply blew up and told us to get out! Im a mature woman and felt completely blindsided by this attack. Never will we return to this bike shop  take your business to The Bike People down the street. Youll pay a bit more, but the peace of mind  and quality  are worth it! Davis Bike Exchange may have a long history in town, but the owner has progressed from grouchy to downright scarey. His temper is the stuff of nightmares. Stay away! Users/SusanTrigilio

20131201 21:29:56 nbsp Great prices for parts, buy NEW tires for 12 bucks. Ive spent a couple hundred bucks here over the years buying brakepads, tubes and tires for bike builds. Nice local business that  i will continue to support. Users/BradyCorcoran

20140426 17:46:18 nbsp How is this guy even still in business? Someone should call the BBB. Users/Ilovetacos

20140710 16:49:51 nbsp Is this place still open? Just like many other, I had bad experiences here, never go back there for service; I would rather go to an expensive place and get reliable service, not to mention there are still other cheap and fair place that still gives reliable service. Anyway, I passed by that location couple times on my way to the bank and other location, the door is firm shut, for sometime I assume theyre out of business, but if theyre still open...man, people now a day Users/Cyclonus

20140728 10:56:18 nbsp Highly satisfied customer! I went to the bike exchange 7/22/14 around one in the afternoon. I asked to look at a bike, I received prompt assistance.I was quoted an affordable price.I had to go home and then come back, when I returned and hour later, the bike was still there and the quote I was given had not changed. I  was given the opportunity to ride the bike around the parking lot, everything worked well.The owner and his employee was very attentive, I was struggling putting my bike on my car and they came out to help me! Users/sheerah
