

Davis Auto Body is an automobile repair shop.  Manager Phil Nader is rude and can be very unpleasant when going through the process of repairing your car, but the result is quickly done, firstrate work.  Their prices tend to be bit higher than other shops.  The owner has been in the industry for a longtime and demands perfection on all jobs.  They will clean your car as part of the repair.

See also: Automobile Repair.


20051103 18:40:42 nbsp Do not go here, for anything!  I went today to get a second estimate on damage to my car and the man who helped me was completely condescending and just plain rude.  He told me that he wouldnt work on my car because the paint had chipped off (even though all I wanted was an estimate) and he wouldnt do a formal estimate because he wouldnt work on it.  His whole attitude was horrible, Ive never been treated so badly as a prospective customer in my life.  Go to A1 body, they are so friendly to everyone, even students. Users/KristyHeidenberger

20051224 14:24:43 nbsp They were really nice to me. They replaced my bumper and vacuumed the car, made it smell nice, and washed it without asking. Users/MichaelGiardina

20060206 11:51:58 nbsp This shops has its ups and downs, As Ive experienced for the while I worked there. For one the manager Phil Nader is rude and can be very unpleasant when going through the process of repairing your car. But on the bright side the painter is extremely talented and does firstrate work. As for the owner he has been in the industry for a longtime and demands perfection on all jobs. All and all this is a good shop. Users/TravisLaFever

20060510 18:58:47 nbsp I just had a great experience with this shop.  I received an accurate & free quote.  When I dopped my car off for repair they had all the paperwork filled out in advance  I was in & out of the shop in 5 minutes.  I dropped my car off on Monday, they promised to get it back by the end of the week  I had it back TUESDAY afternoon!  And it was not a minor repair.  As for Phil, when I dealt with him he seemed organized, professional and competent.  Would definitely recommend Davis Auto Body.  Much better experience than Ive had with other shops in the past.  Users/JonathanKaplan

20060609 17:16:37 nbsp I would recommend these guys for anyone who needs to get repairs done.  I wrecked my Volvo and took it to get repaired here.  The estimate was $400 more than A1 ($3200 compared to $2800), however they could work on it immediately unlike A1 which would have made me wait two weeks before they could do the repairs.  Everyone I interacted with was very friendly and professional, despite the clusterfuck that was my attempts to get an insurance claim at the last minute.  The one complaint I have is they did not call me to ask about a latch that was broken but not discussed in the original estimate.  They chose not to replace it (and not charge me the $250 it would have cost), however if given the choice Id have asked them to fix it.  Not a big deal though, and overall I had a very good experience. Users/ZacMorris

20060823 04:25:03 nbsp I had a minor dent in my vehicle that needed two side panels to be replaced. The parts themselves were about $300 bucks. A1 Autobody did an estimate: $1100 and about 4 days of work. Davis Auto Bodys estimate? $2400 and 57 days. The manager told me they charge a little more because theyre the best. Well, I dont think over twice the original estimate is a little. Users/JesseSingh

20060823 10:16:28 nbsp Yeah theyre ridiculous with pricing and estimates.  Nothing but dissapointments. Users/ScottAdams

20070813 13:45:11 nbsp Dont go here; they were totally rude and overpriced. Users/Carol

20080118 19:17:57 nbsp I am surprised by some of the comments on here. I just got my van back after major body work. I dealt with Phil Nader over the past month and he was wonderful. He really went above and beyond. He helped us deal with the insurance companies, rental car and even helped get us into a rental when the insurance companies tried to refuse one. He kept us up to date in the process and was very kind the entire time. I also am amazed at their work. My van looks new. His crew did a wonderful job on everything. The paint looks great and every little detail was dealt with. They even cleaned the entire van in and out. It really made an awful situation of being in an accident much better. I also forgot to mention that Phil even covered some of the costs to keep my van from being totaled. They are really great people at Davis Auto Body and do awesome work.  Users/HeatherFlood

20080302 18:48:28 nbsp I went here to get an estimate on some damage and Phil was very professional and helpful.  He even offered to lower the labor rate when I told him I was planning on paying for the damages on my own.  Great first impression! Users/kevinV

20080325 16:01:44 nbsp I am very suprised at these comments. I have had both of my cars in this shop for a total of THREE accidents in the last two years (none of which were my fault). My repairs were all covered under insurance and they are a great shop to deal with. They kept in close contact with me through all steps of the repair process, I always received prompt phone calls, and the work they performed was excellent. Car repairs are expensive and it seems that the majority of negative comments dealt with estimates and questions, not about actual work performed. It was a breeze dealing with them (and I hope I wont have to go back soon). Users/lfeleciano

20100827 11:41:45 nbsp I have used Davis Auto Body (DAB) 6 times over the last nine years (let me say that most of the damages to my car have occurred while I was NOT in it  I am not a reckless driver!).  The first time I went there a van belonging to a local business hit me and the owner told me to just take my car to DAB and he would pay them directly.  They did an excellent job and I have been taking my vehicles there ever since and I have also referred many people to DAB; they have always been happy with the results.  As a single woman, I have been treated poorly by mechanics in the past, but Phil and Jaime at DAB have ALWAYS treated me with respect, and the shop has always done an excellent job on my vehicles.  I would not take my car anywhere else.  Davis is a really fortunate community to have such a fine, upstanding local car repair business.  If I were a mechanic, it is where I would want to work.   Users/CrystalBarber

20111128 17:29:48 nbsp After reading reviews for this place I was a little worried. But boy were these reviews wrong! I had a fantastic experience with this place. Its location next to Davis Enterprise (rental car) is very convenient. But their service was really the most stellar part about this place. The staff were cordial and prompt. They communicated well and seemed eager to please. When my car was returned, it was perfectly clean and the work was perfect. I could not have asked for a better job.  Users/GAvila

20120209 13:30:50 nbsp If your insurance does not work with Davis Auto Shop this is NOT the place to go to. A friend of mine recommended this place. The estimate was 50% higher (1000$) than the insurance companys estimate and the manager was pretty grumpy (I wanted to avoid the word rude). In the end I went to A1 body, and those people are much friendlier and nice.  Users/anamaria2

20120221 20:06:42 nbsp Ive never experienced such professionalism and efficiency in any body shop besides this one.  My car was damaged and I brought my car here to get the hood and fenders replaced. The expected completion time was over a week, waiting for the parts to come in, but they got everything fixed within 5 days. The finish was great, and they wash your car for you! Everything was done to specification. Their staff are super friendly, especially jaime and john. One day after picking up my car, one of my light bulbs blew out, thinking it might have been their fault, they let me bring my car back in and they replaced the bulb for me! Free of charge. Id recommend this place for their exceptional quality work and super friendly staff.  Users/FiddyFetzer

20120821 11:06:37 nbsp Professional, excellent service.  Ive been to Davis Auto Body three times in the past year (bumper repair for my daughters, my wifes and my car).  Jaime is fast, professional and pleasant. He knows how to work with the customer and the insurance company to get the job done at the right price. My daughters bumper repair was done on the spot with minimal charge.  John mostly sits in front of the computer and may appear grumpy but hes just all business.  If you want a warm, fuzzy experience Id recommend one of the massage therapists in town.  I you want your car repaired right and at a reasonable price, Id go to Davis Auto Body. Theyre a little hard to see from the road because of the trees. Users/RRodriguez

20130121 14:37:05 nbsp 1212013 I went there to get my car repaired and they did the job, But when I went back to get latch fixed on my car that they were to have fixed.The man that has been working with me has given me the run around about fixng it.I have had to call them they dont call you I told him all I want is my car back to the way it was. He says that it has to do with my trunk spoiler being to heavy for the latch, it worked before I got hit so fix it right.I will not go back to them for anything else. I figure that they do the job and get you out but dont go back and ask to get want was to repaired fixed they dont do it.They are rude. Users/RoxannaRay
