

The Hospital

Davis Small Animal Hospital has been at its current location since 1978. It has been owned and operated by Dr. Janet Edson for over 20 years.  Her conviction has always been to provide the best possible care for our clients.  To accomplish this, the hospital has the most modern equipment available and the most skilled staff possible.  Dr. Edson cares for animals over their whole lives and she has vast experience in geriatric medicine to provide the best lives for our older patients.  Check out our website http://www.dsah1617.com

Dr. Edson also has a flair for design. Please stop by and check out our beautiful facility

 Doctors 

Dr. Janet Edson received her Doctor of Veterinary Medicine degree in 1988  from the University of California at Davis, perhaps the premier veterinary college in the US. She worked for two years at a hospital in Sacramento and then bought the Davis Small Animal Hospital in order to provide the best possible medical care to her clients, the kind of care she provides for her own animals.  She is an outstanding veterinarian with a true passion for her patients. She loves the older animals and through her expertise is able to provide them with years of quality life.

Dr. Kirstin Murphy joined the DSAH about 1 year ago.  She graduated from UC Davis School of Veterinary Medicine in 2000.   She left Davis for a period of 7 years and returned to Davis when her husband, also a veterinarian, became a faculty member at the UC Davis School of Veterinary Medicine. Dr. Murphys primary veterinary interest is dentistry and she has developed outstanding skills in this area.  One of the the things that attracted Dr. Murphy to the DSAH is the top of the line technology to diagnose and treat any dental problems of your family pets.



 Support Staff 

We have the greatest staff in the world. They love to meet new people, but be sure to bring your four legged family memebers.


 Feline Staff 

There are several live in clients. One or more will greet you when you come visit.


  See our Veterinary Hospitals page for other vet services within Davis.



Users/StevenDaubert sez that MUGA was borded there for about a week and has had some vet checkups at the DSAH, The Dr. was good according to his parents.

20051014 12:31:52 nbsp I have taken two rats here for the same problem: both developed tumors. The first time I went in, the vet was over an hour late. But he euthanized my rat for free (normally its like $35), so I decided not to hold it against him. With the second rat, the vet tried to convince me to pay for expensive tumorremoval surgery, and declined my request to have her euthanized because she was still fiesty (despite the fact that the tumor was starting to get infected). I ended up taking her home and euthanizing her myself (humanely). I will not return to this place. Users/AlexPomeranz

20051223 10:35:01 nbsp I have a dog and a cat, and have taken them to this place over the past five years. People are always nice, from the vet to the techs to the receptionist. The treatment is excellent as far as I can tell. I have not tried other places in Davis, but have gone to different places in different cities over the past twenty years, and this is the best that I have experienced. Users/HughToppe

20061106 10:36:58 nbsp I have a cat and have taken it here a few times for urination and fecal problems. On both occasions, I was told that numerous tests were needed. When I asked if they were all necessary for the one problem, they treated me as if I did not have the animals best interest in mind. On another occasions they charged an extra fee for a flea treatment that I did not ok. When I asked about it, the money would not be refunded. I would not recommend this hospital. The doctor at the Aggie Animal Clinic in Dixon is amazing, he is the best vet that I, and other pet owners I know, have ever had. Users/JohnFranklin

20061201 15:24:19 nbsp My family has brought our pets (cats and dogs) to Davis Animal Hospital for over 20 years. We have always found the staff to be caring, compassionate and professional, from the receptionist to the techs to the vets themselves. Dr. Edson and Dr. Sobrano are excellent. I have never felt pressured to have tests performed on my animals. Moreover, Davis Animal Hospital makes housecalls for euthanasia, which means that pets can be put to sleep without a traumatic and stressful trip to the vet. I cannot give a high enough recommendation to this clinic!!!! Users/CatherineHess

20061228 12:38:16 nbsp I wouldnt recommend this veterinary hospital to anyone. I brought my rabbit here to be treated for mites and over $300 and one round of treatments later, she still has mites. The vet failed to tell me that I need to steam clean my carpet to get rid of mites living in it (this was after he first told me all I needed to do was vacuum it, which I uselessly did). I searched online and found out youre not even supposed to steam clean the carpet because the humidity helps the mites breed. Thanks alot!! Not to mention, they charged me a ridiculous amount of money for all sorts of things. Best of all, the vet acted like it was my fault that the treatments hadnt worked. Yes, thats it, becuase I totally wanted to waste $350 going to this shady place. Users/CarolShu

Ive regularly visited Dr. Soberano at the Davis Small Animal Hospital after getting Lula Belle, our Corgi puppy; Dr. Soberano was great, and Id recommend him to anyone as a kind, competent Vet. However, even with an established appointment, I waited an average of 20 minutes before each of my ~6 appointments. I have to admit, after a long day at the office, this became a bit much. So, although they are well meaning, they need a bit of help on the organizational front, becuase the last time I went in (to drop off something), there were 6 people in the waiting area, and no on at the reception desk. They all looked like theyd been there awhile, too. So, keep that in mind of you go to this place. Id recommend going to the Woodland Vet Hospital myself; they are very organized. You can visit their website at www.woodlandvethosp.com. Dr. Larson did Lus spay, and did a great job. Kudos to their whole operation; nice, organized folks! Users/CristinaWilson

20070405 14:09:37 nbsp I did not have a great experience with Dr. Gustavo Soberano. He suggested a teeth surgery that was so expensive and explained that it was absolutely necessary. My dog is 11 years old and I didnt feel that it was the right decision. So, I waited and its been three months and she completely perfect. So, unless you have the money to spend on something unnecessary I dont recommend going there. Users/CTai

20070305 10:23:08 nbsp I took our hamster in because her eye had a huge infection and shed lost half the fur on one side of her face. Dr. Edson was really good and the staff professional. They called to check up for four days thereafter, which impressed me. The hamster recovered, but I would have given them high marks even if she hadnt made it. Conscientious group, in my opinion. Users/RobertBoole

20070529 22:16:57 nbsp I also remember waiting here and being told I needed unnecessary meds, vaccines, etc. I havent gone in a few years but there was a reason. Users/DavisGirl

20080223 21:55:09 nbsp After playing phone tag with UC Davis all week with no success due to their long wait list, I brought my two rats here to Davis Animal Hospital.  They got me in the same day I called, and treated them for parasites.  The care from Dr. Soberano was exceptionally good, and very reasonably priced.  He spent a lot of time answering my questions  and I had a lot.  My rats had begun to fight the week before, and he gave me suggestions to stop their fighting WITHOUT costly neutering, which was suggested to me by an online rat forum.  My boys are now feeling substantially better, and with Dr. Soberanos advice regarding adding a variety of new toys and additional food and water sources, they are no longer fighting!

Nevertheless, he did offer to do the surgery if they continue to fight.  He even called back to follow up.  What more could I ask for in rat care? Users/incognitoTA

20080506 09:08:20 nbsp I used to take my dog here  since she was a puppy 11 years ago. After this place changed ownership I had to take my dog in to have a foxtail removed from her nose. Not the first time (at least twice before). But previously the cost was always less than $150  including ~$60 for anesthesia. This time the bill was $510! There was no cost estimate before the procedure (I naively assumed the cost would be in the same ballpark as before). They charged $130 for anesthesia, PLUS fluids $130 (never necessary before), PLUS blood tests $95 (also never needed before). Havent been back since. Users/BridgetOflaherty

20080507 11:28:55 nbsp I used them for 14 years with my two dogs.  When it was primarily Dr Edson and Dr Ibsen.  They performed surgeries and took care of both my family members very well.  For the most part the tech staff were incredibly helpful and kind.

I believe they are a bit overpriced compared to other vets in town but they do provide great care.  I cant say I had the best experience with Dr Soberano and I probably would choose another vet for any new pet I may get but if you live near them they are certainly worth looking into. Users/loneshark

20080808 10:34:49 nbsp When reading all of the comments the consensus is overpriced and excessive in charges. I would agree. I took my dog here for care and was told that they would need to do a series of tests that would cost almost $500 dollars. I was given a breakdown of the charges and decided on doing some of the tests and not others. When finally billed the charges were more than the estimate and mysteriously there were additional charges that were not even included on the original treatment plan. I was also offered medicine from them that was past its expiration date. When I inquired about that I was told not to worry about it. I decided to get the meds elsewhere and paid almost half what this office was going to charge me. I will never take my animals back here. The vets could be top notch but their apparent efforts to maximize revenue feels to me like a gross diservice to the clients. Users/pedalpower

20080808 17:55:58 nbsp Dr. Edson is an incredible woman and doctor (and yes, she sure does have over 20 cats as well as other animals in her home...Ive met them all).  They are a bit pricey, but you get great service.  If I still had my cat, Bucky, Id still go here... Users/SunjeetBaadkar

20081129 08:27:30 nbsp Dr. Gustavo Soberano is probably the best vet I have found for my rats. Every time I take any of my rats in he explains everything very well and takes time to answer my questions. If you have a rat that needs to see a vet, I would definitely go here.  Users/Bri916

20090411 14:57:45 nbsp First off, Gustavo is no longer working there.  We originally started going here a couple years ago because we knew Gustavo personally.  We loved him as a person and as a vet.  Today though I was completely let down by the office.  I called in right when they opened because my kitty who is dying of kidney failure needed to be put to sleep.  He had been going downhill all week but I was waiting for the right time and we realized last night that it was time.  So I called and they told me they were overbooked and refused to see me.  Now personally, I feel like patients with routine vaccinations or things like that can be rescheduled.  The refused to try and fit me in or anything.  They told me I could come in next weekend.  Sorry lady, my cat is not going to make it until then.  I was very diappointed that they could not take the 15 minutes to put my suffering cat to rest.  After learning that Gustavo is no longer there and they way they treated me today I think I will be looking for a new vet.  My kitty ended up dying in my arms a few hours later and I took him there to be cremated but I dont think I will go there again after I pick up his ashes. Users/MsSteffee

20090420 09:02:56 nbsp With Dr. Janet Edson’s veterinary medical skill, compassion, and flexibility in treatment we have enjoyed seven happy months (and counting!) with our beloved old dog.  I couldn’t be more grateful.

As a chemotherapy patient, our dog has visited Davis Small Animal Hospital far more frequently than he would for checkups and occasional illness and mishaps.  He’s a particularly sensitive animal and rather shy, and I worried that these repeated chemo appointments would distress him a lot.  To see him look forward to seeing Dr. Edson is really heartwarming.  He stands with his nose pressed against the door and listens for her.  When she arrives he wags his tail and he’ll go off to the treatment room without hesitation if Dr. Edson invites him in.

As pet owners, our dog’s quality of life is the key issue in all decisions we make for him.  Dr. Edson has kept us informed and involved in every aspect of his chemotherapy and, recently, in the decision to discontinue clinical chemo treatments. When he had an significant adverse reaction to one of the more effective drugs during the winter, she agreed to modify the protocol to protect him from a repeat of that experience.  With careful monitoring his lymphoma has stayed in remission and he has had many happy weeks since then.  We have never felt that Dr. Edson was battling the disease at the expense of the patient’s quality of life; she has pinpointed what treatments help him the most and trouble him the least.  This is extremely important to us, and we have enormous confidence in Dr. Edson’s judgment.

We understand that our pet is nearing the end of his life and, as hard as it would be on us, we are determined to help him die peacefully if he comes to the point where staying alive means suffering.  Knowing that Dr. Edson would euthanize him at home is a great comfort to us, and just another reason that we are so grateful for her compassionate professionalism.
 Users/SusanWilcox

20090424 14:20:41 nbsp We have taken our many cats and dogs to Davis Animal Hospital for over 20 years, for everything from annual vaccinations to many (over the years) euthanasias and the accompanying preceding treatments for extending life when facing terminal illness.  During all of this we have also visited varioius other clinics and specialists  we will never go to UC Davis again!  and have had many chances to compare treatments and diagnosis.  Janet Edson, in our opinion, is one of the best diagnosticians in the northern half of the state, a veterinarian that actually listens to her clients and carefully assesses each problem, all the while keeping the client informed of the steps she is suggesting, and why.  She always lays out the options, investigates new modes of treatment, consults with specialists when necessary, and clearly communicates the issues regarding BOTH quality of life and potential costs.  She is also the most caring and supportive veterinarian we have encountered. We also respected Gustavo Soberanos skill and were sad to hear he had left.  The clinic is wellrun, with excellent support staff, something we could not have said before Dr. Edson assumed complete ownership a couple of years ago.   Pat Erigero and Tom Matoff Users/TomMatoff

20090511 16:14:47 nbsp wow.. first off as compared to the other places in town this is not that expensive. if you guys dont look into what your doing and signing up for when you take you animals somewhere, its your fault, do not fault the vet because your to lazy to investigate what is required when giving your pet to a vet for  a surgery or a check up. i have used this vet for years and i have never once had a bad experience with them, in fact a few months ago my cat jack had a urinary track infection and could not urinate and we ended up taking him to a place that wanted $5000 to do a surgery and then $250/day to look after him while he recovered. we talked to the vets her and not only did we get he surgery done for under $700, but the vet actually took my cat home with her to take care of him because he was to sick to be left by himself, and charged only $50/day to do so. i cant think that this place could get anything less than a shinning review from anyone that bothers to do any kind of research into the kind of treatment that their pet would be receiving. i have taken multiple pets here and every time i have had a pleasant experience, and i would HIGHLY recommended this place to anyone that want the best for their pets. Users/jaksin

20090701 15:43:54 nbsp I have taken two cats to Dr. Edson over the years, and have found her very supportive and knowledgeable. She has always presented me with a range of options, and costs, and helped to me evaluate the cheapest yet most probable route to take toward achieving a diagnosis. I currently have a cat with an unexplained respiratory problem  a specialist looked for a polyp, and upon not finding one, recommended a cat scan (no pun intended), which costs over $1000. Dr. Edson has helped me create a plan of attack toward finding a diagnosis for this problem without the cat scan, which is way out of my budget. While the tests have still been expensive, with many tests coming back negative, I understood her reasoning for trying things in the order that we did, based on the cats symptoms and what i could afford. She often called me and talked at length about my cats symptoms and progress, and I feel she has a genuine concern for him. And the best news is that the recent test came back positive, and there is likely a fairly simple effective antibiotic cure! I am very thankful to Dr. Edson for her ideas and persistance, and would highly recommend her to others with cats  she knows a lot and has a genuine dedication Users/farmedgirl

20100216 22:40:06 nbsp Dr. Edson and Dr. Murphy are both excellent veterinarians who have years of practicing veterinary medicine under their belts. Whenever a procedure is recommended, you can always ask for an estimate. You dont necessarily have to do every procedure that is recommended, and both doctors are more than happy to negotiate different methods to treat your pets (especially good for students!). A lot of the recommended procedures are just precautions, but if you dont want to pay for it or dont have the means to pay for a procedure, then you dont have to! Duh.  Users/JYuki

20110430 22:00:23 nbsp I was humbled by the staffs compassion and efforts to save a stray cat I came in with. They were amazing at working out costs with me since I was limited. They really went the distance for this animal, all of them from the receptionist, technician to Dr. Edson.  Users/dizzyditz

20110918 13:27:51 nbsp Ive been taking my two dogs here over the past year and have been very satisfied. From parasite infections to surgeries, the care my dogs have received from Dr. Edson and Dr. Murphy has been outstanding. Its clear that both of these vets of them love their work and are very qualified doctors. Both have explained procedures, risks, and costs clearly and carefully and been understanding re: my limited financial resources (Im a grad student).
The vet techs and front office folks have always been friendly and professional as well. They have made us feel welcome and have been flexible in scheduling for both emergencies and nonurgent care. I have been to many vet clinics in Davis and I strongly recommend Davis Small Animal Hospital. Users/BenReeb

20120613 08:02:13 nbsp I was disappointed to learn I was misled by the clinics name  Dr. Edson doesnt treat rats. Users/Willikers
 In the veterinary field, small animal or small animal general practice refers to dogs and cats.  Rodents, birds, reptiles, and so on are generally called exotics. Users/TomGarberson
  Comments from 20052008 indicate they used to treat rodents (at least rats and hamsters), but it was by Dr. Soberano who is no longer with this practice. Users/edwins ES

20130902 16:13:08 nbsp I bring my furry exotic pet here for regular check ups.  She recently had to have something stuck in her intestine surgically removed, and that went as smoothly as can be imagined.  Dr. Keller is very considerate and attentive to both me and my pet. (And shes cute too!)  Yes, the cost is certainly higher than youd pay anywhere else, but you indeed get your moneys worth in terms of the best care for you pet. Users/DanielPfister
