A surprising number of dental patients on the wiki have left comments questioning billing procedures and diagnoses of their dentists.  These comments are especially hard to sort out for a few reasons.  For one, nobody likes going to the dentist, so its easy to come away with negative feelings.  As well, many college students may be handling their dental insurance for the first time and may be unaware of how it works.  Nonetheless, if any sort of fraud is occurring, it benefits everyone (everyone with teeth, and everyone who pays insurance premiums) to root it out.

Questionable practices mentioned by patients:
  Charges exceeding the amount the dentist submitted to the insurance company.  This is a violation of the contract between an insurance company and the dental office.  Most insurances expect the patient to pay a portion of the fee (co pay).  Just because a dentist accepts a certain insurance does not necessarily mean they are contracted with that insurance company.  If a dentist accepts an insurance, but is not contracted with them, then the dentist will submit their usual and customary fee (which can be higher than a contracted fee) to the insurance company.  The insurance then pays the dentist whatever is dictated by the patents plan and the patient is responsible to pay the difference.
  Diagnoses of cavities when none exist. (E.g. you have eleven cavities). This is particularly tricky because once a hole has been drilled, the evidence is gone.  Also some dentists have different opinions of what needs a filling.  Some dentists prefer to watch very small cavities (in hopes that they dont spread) and some dentists like to restore very small cavities.
  Charging for multiple cleanings or only cleaning half of a patients mouth. Sometimes the dentist or hygienist needs more than one hour to remove all the tartar from your teeth.  Most insurances only cover 1 cleaning every 6 months and the patient has to pay out of pocket for the second cleaning.  This is very frustrating to the patient if it is not explained, however, it does not constitute fraud.
  Not releasing records or xrays to the patient.  It is customary for dental offices to charge a nominal fee (usually about $30) for the duplication of xrays.  Dentists are required to release these records upon written request of the patient, they are not required to do so for free.

How to avoid dental fraud:
  Know what your insurance does and does not cover.  (You are responsible for knowing what your insurance covers, not your dentist.)
  Get in touch with your insurance before paying any bill that you think is questionable.  (Calling them afterwards is okay too.)
  Get a second opinion if you are suspicious of a diagnosis (most dental plans cover second opinions).

Note on ethics of accusations
While we all want to stop dental fraud, it is important to keep in mind that any unfounded accusations can be very damaging to a potentially upstanding practitioner.  For this reason, it is important to be absolutely certain a practice is fraudulent or unethical before leveling accusations.

UC Davis students are covered by Delta Dental.  See their page on Dental Insurance Fraud (http://www.deltadentalca.org/enrollee/fraud.html).  But keep in mind that this page discusses more than just insurance fraud.


20060613 09:52:26 nbsp A common thing Ive heard and been told about has to do with overcharging insurance, but not at the expense of the patient.   I know for sure that wisdom teeth are a big issue as they have to be surgically removed.  It costs a lot more to remove an impacted wisdom tooth than nonimpacted ones.  Most all insured people will pay the same amount no matter what (since its so costly either way), but one of the most common practices is insurance being billed for 4 impacted wisdom teeth (if in reality it was only 2 or 3).  As the patient pays a set amount either way, most people either dont notice, or dont care as insurance will cover it.  (People might not care as a normal dentist cant perform this procedure, and youll need to see a oral surgeon for this one time event). Users/EdWins ES

20070415 09:35:52 nbsp Definitely get a second opinion if youre not sure about the diagnosis, but heres another thing to keep in mind  dentists differ in their treatment philosophy.  Some want everything to be perfect, so if they see a tiny little problem, they will fix it.  This sort of dentist will be the one who tells you that you need lots of fillings, etc.  Other doctors are more willing to take a wait and see approach; sometimes small cavities or other problems dont amount to anything, or wont amount to anything for a long, long, time.  Personally, Id rather have the wait and see dentist than the perfectionist dentist, but the thing to do is to match the kind of dentist you want with the kind of dentist you have.  This is the sort of thing you might ask about in your first visit with a new dentist: ask, what is your treatment philosophy?  I had a perfectionist dentist once, and I will always wonder if I really needed the treatment that I received.   Users/CovertProfessor

20080206 11:09:40 nbsp When decay is shallow and in the enamel only it is reversable.  Ions from your saliva can absorb into an early lesion and remineralize the affected enamel.  This generally only works on the smooth surfaces of the teeth (like in between the teeth and on the sides).  When decay is very shallow on the chewing surfaces of the teeth it often continues to spread despite all best efforts to keep the areas clean. This is because all the pits and grooves of the teeth harbor many bacteria and are difficult if not impossible to clean.  Access to decay in the pits and grooves of the teeth is often straight forward; therefore, removal of only the decay with a very small preparation (hole)can be achieved.  This is often referred to as microdentistry.  So if your dentist tells you you have cavities ask if any of them are possible to remineralize.  Remineralization can be assisted by fluoride mouthrinses and xylitol chewing gum. Xylitol is a natural sweetener that inhibits bacteria from sticking to the teeth. The most important aspect of remineralization is preventing acid attack, so brush and floss daily (flossing is ussually the key) and avoid frequent sugar/charbohydrate snacks.  Once decay has grown past the enamel and is into the dentin (the inner part of the tooth) a filling is necessary.
If you are attepmting to remineralize some very suspicous areas of decay your dentist may want to take xrays more frequently to make sure they dont spread too deep.  If anyone has questions about dentistry, dental materials, or preventive dentistry please go to dental questions
I will answer any questions people may have.   Dagon H.C. Jones DDS
 Users/DagonJones

20080520 20:43:48 nbsp On top of what Dr. Dagon Jones has said, you can get Xylitol at Kims Mart with the brand by Lotte or you can head over to the store next door, I think its Davis Health Foods? The name escapes me now, but you can get Spry gum with Xylitol right there! Users/CalvinCheng

20100129 22:49:36 nbsp My husband took my 5 yr old in for 2 fillings in her baby teeth (Tooth#AO and JO). He didnt see a drill or a shot just a nail polish like brush the dentist used on her teeth. Sounds like sealants, but I was charged $152 for each cavity.  Her appt was at 0800 and he was done and checking out and leaving with her at 0823 am.  I have changed offices and pursued this, but seems like the new dentist is covering for her because he didnt acknowledge that there were restorations there, but when I filed a grievance with Delta Dental, he sent a letter stating he looked at her teeth and the restorations are there. I spoke with that office concerning this issue over the course of two weeks and not once did he tell me that they were there. When I questioned the original dentist and told her my husband was there the whole time and didnt see a shot or drill, she told me that maybe she did it so fast that he didnt see it.  Suspicious? She has also sent documentation that she gave her lidocaine, but my husband saw none of it.  In fact, he was waiting for her to get the shot because he knew she would freak out.  Also discoverd that my 8 yr old had sealants put on tooth 19 and 30 and at the next visit with the new dentist, he said it looked like nothing was ever there.Users/MMG

20100209 10:43:37 nbsp This last comment is a tricky one to evaluate.  I cant say what happened one way or the other but it is important to understand that a filling can be done without a shot.  Anesthetic is not always necessary when doing a small filling.  A drill or similar instrument is needed to remove the decay (otherwise it is considered a sealant, not a filling).  Instruments other than a drill can be used such as a microblaster (like a small sandblaster) or a laser, both of these are uncommon and not frequently used on kids.  Also many filling materials and sealants are tooth colored so it can be very hard to notice them on the teeth once they are done. Users/DagonJones

20100211 20:45:17 nbsp I guess my main point was that I point blank asked the dentist if she gave her a shot with a needle and she said yes.  My husband did not see this nor did he see or hear any type of drilling.  This is where I believe she is lying. I feel she isnt being honest with me given the circumstances that my husband witnessed and the use of the sealant brush.  My husband also works with someone whose friend left that office after she was told to bill for services not rendered.  She refused so she quit. When my husband returned to work that day, he expressed how surprised he was that he was in and out of there.  He also mentioned that filling cavities had changed a lot since he had them because there was no drilling or shot.  This is what raised my suspicions that it wasnt cavities that were filled, but sealants done. My complaint has more to do with the ethics since I spoke to the dentist myself and to tell me she did use a needle and did it so fast that he maybe didnt see it just doesnt seem reasonable.  They sent me the notes after I requested them (I received them a week later) and it says right on there that she received a shot and that a moderate sized preparation was done.  From what Ive read on the composite fillings, they seem to take a little longer to do so she is awful speedy if she got that all done for two cavities in 1518 minutes, especially on a child who has never had dental work done.  I did submit a grievance to the dental board in my state.  I am hoping they will investigate and help me settle this once and for all.  Its hard to let go of it if they are committing fraud because I obviously would not be the only one that has had this happen at that office.  Thank you for your comments. Users/MMG

Your concerns are valid and I understand your suspicion. The situation you are describing sounds fishy. It is terrible to feel taken advantage of, especially when it involves your children.  I hope you eventually get some answers that make sense.users/dagonjones

20120324 19:48:08 nbsp we have a local dentist that has commited fraud in the past. he is the son of e very prominent dentist in the next town over. he completely destroyed his dads practice and had to leave town. now we are having a problem with him. if you arent aware, there is a place for people who have no dental plan and need dental work, there is a place called care credit. it is just like a credit card company, but it is only used for dental work. my little niece, who was only 23 at the time went to this dentist and had xrays which were paid for in cash by my elderly mom. he said the work that needed to be done would cost $5,500.00, so they applied for the credit. on the next visit my niece had 5 teeth pulled and a filling, which soon fell out and that is ALL the work she ever had done! then she found out she had cancer and died at age 24 and never returned to the dentist. this so called dentist charge the whole $5,500 on her second visit for work he had never done!!! she is dead and they are after my mom to pay the $5,500.00. while she had been getting billed she was paying $250.00 a month to the care credit, so she has already overpaid them. this dentist has been in trouble for fraud before. i got all the bills together and took them to the county attorney and he looked them over and he even agreed with me, he said the dentist is even charging us interest on something that has already been paid for, which he said was illegal. he also said that a dentist cant do $5,500.00 worth of work in one day! be he wont touch it with a ten foot pole! he told me that the dentists kids and his kids went to school together and it was a conflict of interest!!!!!!!!!! the county prosecutor wont touch it! i cant find anyone who will take on this case!!!! in the meanwhile the credit company is threatening all kinds of legal, action against my 86 year old mom and we cqant get anyone to help us????? i guess it is the truth, that lawyers and doctors all stick together and my family is just screwed! we have already overpaid this dentist for the work he has done which wouldnt even total $500.00 much less $5,500.00 what are we supposed to do???? who can we turn to for help??? Users/bobbyshahan
  Try the Dental Board of California: http://www.dbc.ca.gov/consumers/enforcement.shtml

20130117 12:30:53 nbsp I find most health care providers will give Xray copies for free or a nominal ($5$15) fee. These always are professional copies of the XRay and/or CD of the imaging. My dentist wanted to charge me 30$ for a printer paper copy of my dental xrays. Not on a CD or professionally printed, but on regular printer paper. When I inquired then about the large fee, the assistant told me that fee was not for materials, but only to release my records which are owned by the dentist. I felt that was poor business practice.

Also, I went in for an examination and xray, and the dentist cleaned my teeth, did not examine then, and took an xray. Then I was told I could leave. When I asked about my xray the assistant told me the doctor would call me to let me know if I had cavities or not. Huh? The entire scenario was so strange and unprofessional. I opted to stay and within 3 minutes the assistant returned and informed me the dentist said I had no cavities. Just like that. No showing me the xrays or explaining anything, just, no cavities, when would you like your next appt?

I dont think I will be making any further appointments.

Also, I have several brown spots on my teeth and one specifically concerning one that seems to be some kind of deterioration. The dentist said it was left over adhesive from my braces which had turned brown. However, it is not in the right place and does not seem to be adhesive, it looks and feels like a decaying area. Every time I voice concerns about the brown spots, the dentist says they are just discolorations. I have not had any cavities according to my dentist for 3 years. That seems unusual considering I had braces for 18 months and my teeth care was not optimal during that time.

Any advice on these strange occurrences??

Thanks! Users/NatalieFrancis
  Here is information about the California law regarding patient access to medical records:  http://www.mbc.ca.gov/consumer/access_records.html (see also http://www.mbc.ca.gov/consumer/complaint_info_questions_records.html)
    The patient or patients representative is entitled to copies of all or any portion of his or her records that he or she has a right to inspect, upon written request to the physician. The physician may charge a fee to defray the cost of copying, not to exceed 25 cents per page or 50 cents per page for records that are copied from microfilm, along with reasonable clerical costs. By law, a patients records are defined as records relating to the health history, diagnosis, or condition of a patient, or relating to treatment provided or proposed to be provided to the patient. Physicians must provide patients with copies within 15 days of receipt of the request.
    Copies of xrays or tracings from electrocardiography, electroencephalography, or electromyography do not have to be provided to the patient or patients representative if the originals are transmitted to another health care provider upon written request of the patient and within 15 days of receipt of the request. A patient may request to purchase copies of his or her xrays or tracings. All reasonable costs, not exceeding actual costs, may be charged to the patient or patients representative.

 Im not a lawyer, but it sounds to me as though your dentist should not be charging you $30 for printer paper copies of your xrays.  As for your brown spots, I cant imagine why a dentist would not want to fill a cavity, but if you have concerns, I dont see any alternative but to see another dentist.   Users/CovertProfessor

20140122 23:16:27 nbsp My dentist charged me for immediate dentures, I didnt get the uppers for a month and the lower partial 2 weeks later, also he left a piece of tooth then charged another $500 to remove that, also the upper was crooked, when I told them they mickey moused it straight by making the right side 1/4 inch thicker than the left, and even my regular doctor asked why my upper lip is sticking out so far, so I showed him. Its ridiculous that they still havent got it right, (7 months have gone by), and I am paying these clowns a small fortune for shawdy work. do I have gto keep paying these guys even though I am going to have to pay a competent dental office to do things right ? Do I have any recource ? Any help wou;ld be greatly appreciated. Glenn Rose, rs_glnn@yahoo.com Users/GlennRose
