Depression is a mood disorder that generally includes periods of sadness, low energy, and decreased self esteem.  Depression can be set off by difficult situations, such as a loss of a loved one, an emotional breakup, or failure in school or work.  Other times it can seem to come out of nowhere, or from seemingly miniscule circumstances.  Regardless, depression can feel overwhelmingly painful and very real.  A small percent of people suffering from depression commit suicide each year, and anyone having a severe episode of depression should seek help.  Depression affects people of all types, but is very common among young adults, and both UC Davis and Davis High School provide numerous programs to help students cope with, and recover from depression.
Getting Help
If you or someone you know is feeling suicidal right now, please get help immediately.  Suicide Prevention of Yolo County has a 24hour crisis line, Call 5307565000.  If someone is about to kill themselves right now, call the police.

For more emergency resources, see the Emergency Psychological Services page.

If you are not feeling suicidal, but still depressed and would like to get some help, you have many resources available to you.  The Counseling and Psychological Services page is probably the best place to start.  UC Davis students can also see counselors from free through UC Davis Counseling and Psychological Services.  Similarly, high school students have options available to them through their counseling office.  Nonstudents can also get affordable therapy through the Yolo Family Service Agency.
Simple Strategies for Coping With Depression
  Exercise  Exercising is an easy way to break out of a depression cycle.  It a good distraction and makes you feel better physically.  It can also give your mind a break if youre over thinking things, (sometimes called the monkey mind).  Davis has lots of options for getting exercise:
   Bike  Davis has lots of of places to Bike Rides go on a bike ride.
   Run  There are also many places to Places to Walk or Run go on a run in town.
   Workout  If you can pay for a membership, join a Gyms & Fitness gym.
  Eat a Healthy Diet  Eating right is an important way for keeping your head right.  Like exercising, eating a healthy diet will also make you feel better physically, and will increase your energy throughout the day.  Avoid high sugar and over processed foods.
  Get Proper Sleep  There is a large body of evidence supporting the relationship between proper rest of reducing depression.  Shoot for eight hours of sleep a night.  Some people use sleep aids if they are having problems sleeping, but this should be used infrequently if possible.  Either way, getting a full nights sleep will make you feel more energized during the day, and more responsive to stress.
  Reduce Drug and Alcohol Intake Really isnt much more to say here, drugs and alcohol usually cause more harm than good.
  Turn Off The TV and Stay Offline  American Idol, Facebook, and yes, even Daviswiki are poor solutions to coping with depression.  Get off the couch and go outside.  Yeah, can be very hard to motivate sometimes, but if you force that first step of getting out of the house, its much easier to stay out in the sunshine.  Stay active, and distract the monkey mind, and you will feel better.
  Tend To Your Social Support System  Having people to turn to in times of need is important if you have recurring episodes of depression.  Look for opportunities to make friends with new people, even if you arent immediately feeling low or depressed.  Check in with your existing friends periodically to maintain relationships.  And if your friends are ever feeling down, be that good friend and be there for them.  While not directly related to depression, the Unofficial Survival Guide to UC Davis and the Freshman Guide have a lot of good advice for making friends.
  Talk It Out  Talking out your problems with someone you trust can be extremely helpful for getting over emotional problems.  Use your friends or family for small problems.  If you cant rely on friends or loved ones, or if you have more complicated problems, use a counselor or therapist.  If you are a UC Davis student, you can get free counseling through UC Davis Counseling and Psychological Services.  If you are not a student, you can still get affordable therapy through the Yolo Family Service Agency.  Also see the Counseling and Psychological Services page for additional resources.
  Keep a Journal  Writing out your problems in a journal is a good way to organize your thoughts and work out problems.  Use free association to get your feelings out, then spend a little time rereading the things you put down.  This can help you identify patterns within yourself that make lead to changes in mood, or reactions to stress.
  Develop a Whatever Attitude  It sounds a little funny to say here, admittedly, but in many situations it is useful to blow off circumstances that are having a negative effect on your mental health.  This is particularly effective when dealing with people with strong personalities.  Just blow them off as irrelevant and find other people that make you happy.  Many times, just saying whatever aloud will make you feel better.  Of course, dont blow off things like a job or a credit card payment.  Use the whatever attitude wisely and it can be useful technique.
  Keep Yourself Busy  Keeping busy is an excellent way to break a depression cycle.  Distract yourself with tasks and give your mind a break.  In many cases, fulfilling work will help lift your spirit and make you feel better.  There are literally endless ways to keep yourself busy, but the important part is motivating yourself to get off the couch and out of the house.  If youre in a complete rut, however, here are a few things to start:
   Volunteer  Volunteering is an excellent way to break out of depression.  Not only will you fill time with more meaningful tasks, you can do important things that help others in need.  It is also a great way to meet new people and strengthen your own social support network.  A volunteer job usually comes with a regular schedule, which can help with longer term depressions.  Davis has many excellent Volunteer Opportunities for people.
   Garden  Gardening is another great way to distract yourself out of a depressive cycle.  There is a fair amount of meditative and physical work involved with gardening, which can be very healthy when you are feeling down.  It can get you off the couch and out in the sunshine, and if you grow fresh vegetables, it will improve your diet!
   Art & Crafts  Working on a project is a useful technique for keeping busy if you are feeling down. Artistic projects can also be a good emotional outlet.  Many projects can be free or very low cost, (drawing can be done with a pencil and paper, carving can be done with a knife and a tree branch wood, etc).  Davis also has many resources for arts and craft projects.
    Davis Art Center  The Davis Art Center has classes year round and equipment available for use.
    Craft Center  The Craft Center also has classes and equipment for art projects.
    Davis Makerspace  Davis Makerspace is an open workshop for exchanging ideas and working on all kinds of projects.
   Vehicle Maintenance  As odd as this sounds, car or bike repair can be very effective for coping with depression.  It can help ease the monkey mind, and can reduce other problems in your life (at least those that are transportation related).  If you dont have a car or bike to fix, try repairing a leaky faucet or patching a hole in the wall.  Start small, and find problems that wont have a huge impact if it you cant find a solution (ie: reboring your cylinders might be more trouble than its worth as a starter project.  Maybe try fixing the radio instead).  Fixings stuff is fun.  Check out Bike Forth for bicycle repair resources.
   Clean Your House  Like repairing a vehicle, cleaning up your house can be very meditative and calming.  Having a clean living space will also make you feel less cluttered and more in control of your life.
  Work To Fix Your Problems  This can definitely be a hard solution sometimes, and often, like in the case of a lost loved one, may not be entirely possible to acheive at all.  Still, getting to the heart of something that is bothering you, and making changes to improve your situation, is obviously a highly effective way of getting over a depression.  If your in a destructive relationship, get out of it.  If you are struggling in school, consider another major.  If youre unhappy at your job, look around for something else.  Yes, often we get ourselves into very difficult, often painful situations, but take things a little bit at a time.  Chip away at your problems if you have to, but eventually youll make the change you need and youll feel better.
