Diplomas in Davis can come from UC Davis or Davis High School.

 UC Davis Diplomas 

You can get one after 110 long years at UC Davis. It requires leaving Sophias for hours at a time and getting to know the library. Students have to wait 34 months after they graduate to get their diploma. They can choose to pick it up (for free) or pay a fee for the Office of the University Registrar registrar to mail it ($60 in 2010). Dont delay picking up your diploma for too long—the registrar shreds diplomas not picked up after five years.

The diploma frame will set you back $40$250 at the UC Davis bookstore... or around $14 from Target. The physical diplomas themselves are disappointingly plain and small (8.5 x 11, or a normal sheet of letter sized paper) compared to some other institutions. King Hall Law Students, School of Medicine med students, and School of Veterinary Medicine vet students get something substantially larger (11x14). You can get a nice matte inset frame with a glass cover that fits them at many retail stores.

The diplomas are issued by the UC Board of Regents on the nomination of appropriate UC Davis Colleges college (for undergraduates), Professional Schools school (for professional students), or the Division of Graduate Studies (grad students). They are signed by the governor, president of the university, chancellor, and the head of the college/school/graduate division. The signatures look to be rasterized printed images—theyre not even autopenned! If you get a reissued diploma (lost the original, changed your name), the reissued diploma has the current signatures and not the ones that were on your original.

Despite the fact that the University of California never used Latin on any of their diplomas until 2009 (see the paragraph on the Japanese Internment degrees), UC Bachelor of Arts degrees are referred to by their Latin abbreviation, AB (Artium Baccalaureus), as opposed to the more common BA. The diplomas themselves still use the common language of Bachelor of Arts. Bachelor of Science degrees arent referred to by the Latin SB, but the standard BS.

Alphabet soup! UC Davis issues the following degrees: AB, BS, BAS (Bachelor of Arts and Science), MA, MS, PhD, MBA, JD, LLM, MD, DVM (Doctor of Veterinary Medicine),MAM (Master of Agricultural Management), MAS (Master of Advanced Studies), MAT (Master of Arts in Teaching), M.Ed. (Master of Education), M.Engr, MFA, MPH (Master of Public Health), MPVM (Master of Preventative Medicine), Ed.D. (Doctorate in Education), D. Engr. (Doctor of Engineering). There are also various certificate programs. One little known fact is that the University of California used to issue two year associate degrees! Maybe they were issued to farmers once upon a time when Davis was the University Farm? Anyone up to dive into some microfilm in the basement of Shields Library?

UC Davis (and the University of California) as a rule does not issue honorary degrees (and thus honorary diplomas). The one big exception is the issuance of the Honorary Degree of the University of California Inter Silvas Academi Restituere Iustitiam (to restore justice among the groves of the academy). These degrees were issued starting in 2009 (sometimes posthumously) to students who were unable to complete their studies because of the Japanese Internment. These diplomas are issued by the directly by the University of California (not the Regents or the Academic senate) and dont mention any specific campus. They are signed by the governor, president of the university, chair of the the board of regents, and the chair of the academic senate. The first conferral at UC Davis was during the http://www.news.ucdavis.edu/search/news_detail.lasso?id9340 December 14, 2009 commencement. You can find photos of the diplomas http://www.flickr.com/photos/davidhanddotnet/4158958841/in/photostream/ here and http://www.flickr.com/photos/davidhanddotnet/4158945661/in/photostream/ here.
