


Discovery Preschool is a Schools preschool with programs for children aged 2440 months, 3648 months, and PreKindergarten (eligible for Kindergarten the following September).  There are half day, full day, and extended day programs available.  Discovery Preschool was the first preschool to be established in the city of Davis.

Discovery preschool follows a creative curriculum.  Two theme based circle times, a music/movement circle, and a Spanish language circle time are conducted each day.

Discovery Preschool Philosophy Statement:
  Discovery Preschool is a developmental preschool with a homestyle environment.
  Our professionally trained staff serve to facilitate a childs growth by providing a warm safe environment, acceptance, and equality.
   We provide the child with the opportunity to make choices, to express ideas and feelings, and to experience social interactions in terms of his or her needs and development.
  We foster independence and responsibility by creating a childoriented environment with childoriented activities as opposed to a teacher oriented program.
  We feel that it is important for a child to develop his or her individuality as well as to learn to cooperate within a group.  Learning to be a good friend is an important part of our philosophy.



20051216 13:59:12 nbsp I went there as a kid for prek...it was good. Users/MyaBrn

20070223 18:40:40 nbsp I went here, I bit a kid and hopped the fence and wandered across F street. I got expelled from here ( Users/StevenDaubert
  20100314 19:00:50 nbsp For the record: The aforementioned incident of a child scaling the fence at Discovery and subsequently being expelled happened 20+ years ago, well before the current owner and director were in place.     Users/AynReyes
Being a wee bit dry with my cherished childhood memories here... But thanks for the politically correct clarification! Daubert

20080618 12:38:46 nbsp I interned here for two quarters for Human Development  it was great!  The teachers and kids were wonderful.  The atmosphere was so positive and happy, I truly enjoyed my experience there and would recommend contacting them if you need HDE 141 or HDE 192 units.  They were very accommodating.   Users/AynReyes

20080626 20:41:33 nbsp Not a good place to leave your child. Enough said. Users/realitycheck

20080711 10:41:55 nbsp No, that is not enough said!  I have 2 kids at Discovery now & have a lot of friends who have sent their kids there too.  The only person I know who was not happy was someone who wanted a morningonly program.  My kids love it & they get a lot of play time inside & outside in addition to a lot of fun learning.  My kids arent in it yet, but Sues preK program is supposed to be great & prepare the kids well. Users/getreal

20080903 16:48:11 nbsp I have a child at Discovery, he went there for the Toddler class and is now in 34.  The staff are the best part.  They really seem to know the kids well, and theyre always glad to communicate with parents.  They also work well with developmental milestones and treat each child as an individual.  Lots of craft and art opportunities, lots of playtime outside.  The only downside to the outdoor play is that my son occasionally comes home dirty, but thats what baths are for.   Users/CynthiaCCC

20100621 11:26:49 nbsp My experience at Discovery Preschool has been extremely positive.  My daughter has spent about a year in the Tic Tac Tot (or T3) classroom at Discovery, for toddlers.  To me, it is hard to find nurturing, highquality care for this age group in Davis for working parents.  After researching and visiting many places, I think the T3 room is an amazing place.  My daughter transitioned easily at 22 months and really enjoys it.   The staff is warm.  The physical setup for T3 (classroom, snack area, outside area) is set aside especially for the 23 year olds and is just right for their age.

I like that Discoverys approach is based on child development theory.  I am especially impressed with how much thought is put into the curriculum; the program feels very rich to me in terms of content and engagement with the children.  However, at the same time it feels very homey and lowkey, and the staff is nurturing.  My experience also is that there is lots of informal and formal communication between staff and parents. Users/SuzanneM

20110504 09:15:45 nbsp Hi all. To all you parents that are thinking of putting your child in this preschool, let me land you all a piece of advise  DO NOT!!! There are many reasons why not to do so... I wish that I had heard the truth about this preschool before enrolling my daughter. Users/Amirkol

20110605 23:05:22 nbsp In reference to the previous comment, Mr. Kols child has never attended Discovery Preschool.   Users/AynReyes

20120323 10:46:54 nbsp My daughter and I LOVE Discovery. The kids really get to play and be kids, but my daughter is learning so much! She comes home telling me about the food pyramid, about songs in Spanish... They have weekly field trips, walking to the Library or Community Park, hopping on the Double Decker bus to the Arboretum. Its just lovely for little people. Users/NicoleR

20120801 13:46:24 nbsp I created a DavisWiki account just to post a comment here after reading the vague bad reviews. Discovery Preschool is a wonderful place to send your children. My daughter attended for over a year and we were both pleased to have her there. My only regret is that we moved from Davis and I will not be able to send any other children I have there. Sue runs a great program. Discovery is a safe and nurturing environment where your children will learn and grow. I cannot say enough good things about this preschool. I highly recommend them!  Users/Liana

20120914 10:08:06 nbsp My kiddo has been going to Discovery for a year now, and we couldnt be happier!  He started when he was 2, so weve had the opportunity to experience both their little kids classroom, and now the bigger kiddos.  My son surprises us on an almost daily basis with his new found knowledge, from using Spanish words, to telling us all about what he learned that day and who he played with.  Hes developed great friendships, and adores all of his teachers.  Thank you Discovery! Users/JuliannePhillips

20121204 15:52:34 nbsp I have heard SO many unhappy stories from other moms in the area. Some are pretty concerning regarding child safety, I will be surprised if this place lasts another year.  Beware of the staff and director, truly dishonest, rude and money hungry. Do not be fooled and let your children go here, not worth it!!  ANY other school in the area is better. The staff writes a majority of the good reviews on this site. Users/bonfire

20130109 14:50:35 nbsp I created an account just to write here.  My daughter has attended Discovery for three years now.  The staff, lead by director Sue, is amazing.  Loving, kind, creative and well educated in ECE.  I have twins who are one and cant wait for them to follow in their big sisters steps at Discovery.   Users/JenniferMcNeil

20130201 16:03:24 nbsp I enrolled my son at Discovery Preschool but did not attend the school after sitting in for a couple of hours the first two days. The staff was rude, they seemed to lack appropriate training, and used harsh tones with the kids. I witnessed this first hand. To me, this is a more of a daycare, not a preschool. Sue, the owner, sued me for three months of tuition even though my son only attended for a few hours. The court mediator disclosed that she has taken other parents to court as well. Do not sign anything without a lawyer, she has a predatory contract. It is clear that the top interest of her “school” is your money, not your child’s education.  Users/StephanieTouchman

20130302 18:55:02 nbsp Suing your customer > not a good business model. Anyone can have a bad day but that one takes a serious lack of judgement. Users/BillBrackney

20130411 08:59:01 nbsp Discovery Preschool is a great place for kids.  My oldest son went here and now my youngest son attends.  My children have very different personalities; one is extroverted and the other shy.  The staff worked hard to meet their needs and encourage their development, and both boys love the school.  My oldest likes to return for Parents Night Out.  I have recommended this preschool to others, who are also very happy with the care they provide. Users/ShawnYarnes

20130617 15:04:56 nbsp When we moved to Davis last year, I checked out almost every preschool available to my 2 yr old son.  As a scientist and educator, I am very picky about balancing freeplay (very important for this age) with ageappropriate structured play (to teach skills).  I enrolled my son in Discovery and am SO glad that I did.  The staff at Discovery work with the kids personalities instead of trying to fit them into a box.  For example, my son dropped from a 2 hr to 1 hr nap.  Most schools would make him sit on his bed for the extra hour quietly.  Discovery lets him go out on the playground with the bigger kids instead and he has made such good intergenerational friends that way.  Sue and Jessica are amazing, and the other staff are knowledgeable although harder to get to know.  The school has very low turnover of teachers, something that is a problem at most schools. The curriculum encourages learning and creativity but also free play. They have several outdoor spaces and my son comes home every day covered in dirt  a really good sign that he is getting plenty of outdoor freeplay time.  I would highly recommend this program.  The down sides are that they start at age 2, so no infant program, and they require a 2 month notice if you are leaving (I would never want to leave, but its something to keep in mind when signing up, since many of us in Davis are very transient). Users/KrisDuehl

20130802 11:59:53 nbsp I went to visit Discovery and was disappointed with the fact that they feel the need to give the children a sugary treat for sitting in circle. I always thought circle time was supposed to be fun for everyone. Why the reward then? I wont choose this school because I dont want my child to have a bunch of cavities! Users/SusanBush13

20130907 18:03:28 nbsp My child was very unhappy there.  The staff didnt seem to have their hearts in their work. I thought I was lucky that they had a space when everywhere else was full.  Now I know why. Users/GaBreal

20131005 21:07:46 nbsp Discovery Preschool was and is a God Send! They helped potty train my stubborn son who luckily began attending preschool here two years ago. I first met Ayn (who was at the time assistant director)when searching and interviewing/touring for my younger son who just turned three.I decided to go with this school because of Ayns kindness and upbeat attitude. She had good vibes. Ironically, my son bit Ayns finger the first time I dropped him off at school (major separation anxiety)! But Ayn was so gracious, held in her pain and held on to my kicking and screaming three year old so I could finally leave to go to work. Now, that was just confirmation of how dedicated the staff are there! I believe the staff to be very caring and yet not fake or phony when it comes to their work. I have known plenty of daycare providers that act as if they are caring for your child but as soon as you leave they drop the act. Not so with Discovery Preschool teachers...what you see is what you get. As teachers/preschool staff, you must be a balance of stern/ reserved so children will know boundaries and still compassionate and nurturing. Most of them are parents/mothers themselves! It is not easy to care for children so please do not be quick to judge...after volunteering at my older sons kindergarten class, it can be overwhelming to be responsible for 4 kids let alone a whole class. I think the teachers there are a great team. I love this preschool because they let the children be children! Its clean...the cleaning lady is always there cleaning away, there are tons of toys and books and music! I mean, my son came home talking about Bob Dylan! Cool! Sue is a very generous person, she is smart and knows her stuff! She has been so open and flexible when it came to families with subsidies and they never make you feel second class! My son has thrived there, the location was so close to home and work. Everything is scheduled and oragnized. They have monthly handouts of what is going on, curiculum, activities for parents to get together and fieldtrips. They have an open door policy so you can drop in anytime and observe your child and the care he or she is recieving...but most likely, youll hear the kids playing and having fun as they should be. They even hold afterschool child care for parents night out. I would definitely recommend this preschool to all my friends and anyone needing childcare. Thank you to the Staff: Sue, Jessica, Martha, Yvette, Addie and Gwyn Users/giselleski
