Eddie Lee is the current Editor in Chief of The California Aggie.  Lee was a sports writer for the Aggie for about one year (2006  May 2007) before being selected by the Campus Media Board to be editor in chief of the paper for the 20072008 school year. In his first story as a senior staff writer, part of his training to be editor in chief, Eddie Lee plagiarized from a press release, an offense he admitted to and was fired for on May 9, 2007. After controversy erupted at The Aggie (see The California Aggie Controversies for more information), Marion Everidge was named interim editor in chief and subsequently reinstated Eddie Lee as a senior staff writer on May 17, 2007. This is the first time a writer has been allowed to continue working for The Aggie after committing plagiarism, although plagiarizing a press release is typically something that only mandates a warning in major newspapers such as The Sacramento Bee.

Some Aggie staff members speculated that Peter Hamilton structured Lees training so that he would fail and he could fire him. Included in this training were assignments that required him to turn in stories within 15 hours (7 p.m. to 2 p.m.) for the city and campus desks, with which he was not familiar. The way that this training was structured is unique, and some construed it as a way to entrap Lee. Signers of the petition against Hamilton and Talia Kennedy suspected that Lee was set up to be fired so Kennedy could apply for the editorinchief position.

Hamilton did not introduce this training, called senior staff writing, specifically for Lee. It has been included in The Aggies budget for years and is standard training for those ascending in rank at The Aggie. (For example, Marion Everidge trained as a senior staff writer for two weeks in May 2006 for the managing editor position.) Though Lee had not written stories for the campus or city desks, every Aggie reporter is explicitly warned, upon his or her employment, that plagiarism is strictly forbidden and leads to immediate termination at The Aggie.

It is important to note, however, that Aggie Sports Writers like Lee dont usually deal with press releases, and some of the Aggie staff felt that he was not given the necessary tools or enough briefing that is usually given to those who write for other desks (like campus, city and science) that use press releases. Also, Lee technically only had one source, the press release itself, and some members of the staff felt that it was a suspicious oversight on Talia Kennedy Kennedys part since writers are told they need three sources. Whether or not her oversight was purposeful will always remain a mystery.


20070518 19:50:19 nbsp OK  Ill paste it here then. On the speculation about a set up so Talia could take over:
In his letter to the staff, Hamilton explained that Kennedy had no intention to apply for the position before or after the initial termination of Lee. Substantiating his claim, Kennedy confirmed her registration for UC Berkeleys graduate school of journalism for fall of 2007, indicating she had no plans to stay at The Aggie for another year. Users/BrianChen

20070519 01:49:43 nbsp Nonetheless, the fact that the rumors even got brought up at the Media Board showed a profound disconnect between the Aggie staff. Users/BrentLaabs
