


El Macero Village Apartments offers one, two, and threebedroom apartments, with a washer/dryer in each threebedroom apartment. There is also a laundry facility on the premises for occupants of the one and twobed units. The twobedroom units have one bathroom attached to the bigger master bedroom and one regular bathroom across a hallway from the other smaller bedroom. No application fees. A security deposit of $500 is required prior to movein, along with a $250 deposit for each cat (up to two cats), and $450 for each dog (only one dog; a dog walk/exercise area is provided). The community room features a service bar, color TV, stereo, and full kitchen; additionally, both barbecue areas provide easy access to the community room.

This complex is located on the Unitrans A bus line and the P/Q Bus Line stops a block away. There is also the S bus line and T bus line right outside the complex. Residents appear to be a diverse mix of undergraduates, grad students, and families. Also nearby (two blocks away) is the South Davis Nugget store. In addition, the new Target is a few min drive away or just take the A bus line (get off the 2nd stop, not counting the stop where you got on) or the P/Q Bus Line (get off the next stop).

Currently the deposit is $400 for any apartment unit and the rental rates are
 1bedroom unit: $945/month
 2bedroom, 2bath unit: $1,170
 3bedroom, 2bath unit: $1,650

The above rent is for new residents; the typical policy of the management is that continuing residents get a discount. The rent above includes all city services; there is no extra charge for water or garbage. The property manager is Brenda and the maintenance crew is Miguel and Alan; this place is not run by a Property Management company.

To find out about other rental housing options in Davis, check out our Rental Housing Guide as well as our Apartments pages.


20070714 20:09:32 nbsp When I first moved in, I really liked this place. It is quiet, the maintenance is great, they allow (some) dogs, etc. Over time, I begin to find it wasnt so nice as it first appeared. The property manager Brenda could be very rude. She seemed nice at first until you wanted to get your packages the week BEFORE Christmas (a sign on the door told you that you couldnt and NOT to knock on her door). . If you got locked out the policy was that you HAD TO CALL A LOCKSMITH AND PAY FOR IT . After I left, I heard they cut down a bunch of trees without telling anyone they were going to do it. They would also water the sidewalk and the side of the buildings, so much so that it caused rotting; obviously not a very ecofriendly management. Users/john75

20071009 02:16:05 nbsp I have lived there for five years, and have found Brenda to be nothing but accomodating. Whether it be maintenance or repairs, she has been very effecient. We get a pool/jacuzzi, exercsie room, and a great quiet location for cheaper rent than most crappy places in Davis. Users/DCWine

20080330 22:16:31 nbsp We just signed a lease for 0809. They allow dogs (with breed exceptions, such as pitts, rotties, etc. per usual property insurance regulations) for a $400 deposit. We got a two bedroom for $1080 a month which is twice the size of what we have at the Trees now, for almost the same price. Brenda seemed very nice and helpful. Im looking forward to moving in. Users/CParker

20080418 00:17:13 nbsp Hi Cparker, can you tell me more about the apartment and was it had for you to get a hold of the office management??Also, is the 2br with 2bth or just 1? Users/Dreabo0

20080424 13:09:40 nbsp Hi Dreabo0, the El Macero apartments are very nice. It was pretty easy to get a hold of the manager, Brenda, I used the number I found on this very website in fact. The unit we rented is a 2br/2bth and very spacious. What really made the deal for us was the size of the private patio, its quite large (enough room for a table and chairs or a hammock or something) and fenced (private). It seemed like they had a few more available for rent next year, and there was an empty unit she showed us. The inside of the apartment looks newer than what we have now, and rally nice kitchen appliances. Theres also a pool/spa, rec room, study room, etc. on site. The grounds are very well manicured, and Brenda was very nice. Hope that helps :) Users/CParker

20080609 23:12:55 nbsp I just signed a lease here and I agree with Cparker. Brenda is nice and the grounds are very well maintained and the apartments are a good size and a great price for a 2/2 plan! Whats great is that they allow dogs, big and small which is super hard to find. Also if you are reading this and need a room to rent I am in need of a roommate!! Im moving in 8/10/08. send me an email v83arias@yahoo.com o) Users/Nessa

20081026 18:07:22 nbsp Hi, I am looking at these apartments as a potential grad student.  It sounds like a great place to live, but the distance does seem a little far.  Does anyone know if the UC Davis campus is accessible from the El Macero apartments via bike?  If not, is parking near campus a complete pain or would that be a viable alternative?  Please let me know!  Thanks! Users/mmartin

20081118 10:22:31 nbsp its a tad far for a bike, but the campus bus system would be free with very little to no inconvenience and there is a stop right outside. I like this place alot more than the trees. Has a very nice pet area, except for the ones who cant clean up after their pets, even if the pile is right by the can and scooper. Brenda is really nice and accommodating with like 5 or 6 places to eat and a shopping plaza/Nugget right across the street. Users/patrick82

20090207 16:33:24 nbsp The buses are only free for undergrads. Grad students have to pay for the buses, but I believe that grad students at least get a little annual pass discount.  Users/JW

20090207 17:09:15 nbsp My friend lived here and her neighbors cooked a lot of curry dishes. Her apartment reeked. The manager told her the only way to get the smell out was to oxygenate it or something and it would cost a fortune. It was gross and she finally had to move out.  Users/EricaMacGregor

20090302 13:46:52 nbsp my roommate and I have had an easy time meeting with Brenda with complaints like the noise above us. Shes been friendly and helpful. Must just depend on the individual. Users/patrick82

20090414 19:18:58 nbsp I lived here for the 0809 year, and resigned for the 0910 school year. It is an older apartment complex, so, of course, you will fine some issues with things. Eventually, toilets, showers, etc need to be replaced or upgraded, and they seem to be doing on an asneeded basis, which suits me just fine. The apartments are very large considering the price, and its the best deal I found when looking for a 2 bed, 2 bath. The downside with living in a dog friendly complex is always the poop that owners dont pick up  but here its pretty minimal. Brenda, the office manager, has some quirky office hours, and Ive noticed she has left early on occasion (dont we all?). But shes prompt to return phone calls, and very good at handling the few issues and disputes Ive had. Shes not afraid to reinforce the no party addendum  which is great for me, since I study a considerable amount. The maintenance crew is quick, and very friendly. All of the maintenance issues Ive had were solved relatively quickly and painlessly. The laundry room leaves something to be desired. Its operated with a card that you load money onto, and the machines have eaten my money on more than one occasion. The gym is nice, and rarely crowded. Its not terribly far from downtown, but you do sacrifice some of the conveniences of living in central Davis. I would definitely recommend living here! Users/ElizabethAbinante

20090706 15:41:37 nbsp I just spoke with Brenda about affordable housing, and she says they are discontinuing the program. ~~~ Users/ErinBlackman

20090807 16:11:22 nbsp Well be moving out at the end of the month, but only because were moving closer to town. Nothing at all because of Brenda, who has been nothing but accommodating. There was a gap originally of when wed have to move out and when we could move into our new place, and she even offered a room to us for a week if we needed. The grounds crew were very friendly, even if just passing by, and always really quick to come fix a repair. You can tell the difference between someone who owns and runs a place and someone who works for a large management company. Users/patrick82

20091002 14:16:09 nbsp This place has gone downhill in recent years as management has been unable to fill all units & rents to some very strange/creepy people (mostly clustered on one side of the complex, away from the families).  Carpets smell like pets and one of the maintenance guys (bald dude) is a peeping tom.  Agree with previous comments about Brenda  very nice and accomodating at the beginning, but once you dont resign a lease gets pretty nasty.  Id lived there many years w/o a single noise complaint, then shortly after i didnt resign my lease I fell asleep in my bedroom with a Lost marathon still playing.  The next day I saw a nasty note on my door from Brenda saying shed call the police if there was another noise complaint!!!  So much for warnings/any pretense at civility  Im sure she was trying to kiss up to the new ppl whod moved in next door.  Items of gym equipment broke 6 months ago and still havent been fixed/replaced as of my moveout. Users/davisGeek

20100114 10:12:03 nbsp I only have Silverstone to compare this place to and let me tell you its a breath of fresh air. True, its an older complex and has problems, but when there are problems I havent been given hell for it. The unit kitty corner to us got upgraded to new white appliances with a microwave/fan unit over the stove. I dont know if thats going to be standard to the new leases, but its nice for them at least. :)
Its quiet (minus the dog upstairs) and the gym is better than Silverstones & they have a study area, kitchen area open for get togethers (not parties really).
The only not so great thing we encountered was the lukewarm temp of the hot tub. Seems like it just breeds bacteria at its cool temp, and there were these nasty biting bugs in it the one time we used it. The bite I got swelled up to the diameter of a softball. But Miguel and the other maintenance guy are really prompt, helpful & friendly. And Brenda is too. In reference to her becoming bitter about not renewing a lease I cant say cause we havent been here that long, but Im 100% happier here than at Silverstone cause that managers a bitch. Users/EmC

20100126 20:56:14 nbsp Update: management was incredibly shady about refunding security deposit, vastly overinflated costs and charged me for things Brenda said wouldnt be charged for when I was moving in.  Be warned!  I think it might be the owners policy to withhold all security deposits until you threaten them with a lawyer (which I did and got every penny back).  Now I know how they can afford to give you that discount on the first months rent!!!  Make sure to take digital photos when you move in and move out and demand a walkthrough before you move out.  I HATE the way slumlords in Davis like to bleed the poor for money.

The Owners contact info:
Santa Clara Capital, Inc
Sylvia P. Boeme
9818 N. Fairway Drive
Hayward, WI 54843 Users/davisGeek

20100130 13:32:37 nbsp Does anyone know if the cable tv is basic cable or just a few channels?  Also, is it free?  Thanks! Users/sm0729

20100209 11:58:16 nbsp I have lived at El Macero for 15 years. In that fifteen years this complex has gone through a lot of changes. Everything has its down sides, i.e the age of the complex, so no problem. My appliances have all been updated. The rec room is a wonderful facility with a gym and study room and I personally love the barbecue picnic area in the summer when I can accomodate my grandsons birthday on the quaint little patio then go for a swim in the well maintained pool. My biggest complaints are ignorant neighbors and former tenants that lived like slobs and like to blame their shortcomings on management. But hey, ignorance happens. I have heard a few sob stories over the years and let me tell you, they are pathetic. Brenda is a very pleasant lady. She has been short with me once that I can think of over 15 years and thats pretty impressive since Im an asshole. Good complex, great management, great response time to maintenance and very friendly help all around. Well kept landscaping and buildings and for the most part minus a few idiots, great quiet neighbors. I just gotta say to davisgeek, get over yourself, bub. Bald peeping tom? You mean the 65 year old Brazilian guy that has a gf fifteen years his junior? yeah sure buddy. Gotta love it.  Users/giants2010

20100209 11:59:28 nbsp oh and sm0729, what cable? the one you buy from comcast? yeah its free. for only $55 per month.  Users/giants2010

20100218 12:21:29 nbsp Reply to DavisGeek: This place has gone downhill in recent years as management has been unable to fill all units & rents to some very strange/creepy people (mostly clustered on one side of the complex, away from the families). < REALLY?? you were able to go into every apartment and check if anyone lives in there? didnt think so. FYI, all apartment is filled and people are waiting to move in.

Carpets smell like pets < if that is so, why didnt you contact management when you moved in?

and one of the maintenance guys (bald dude) is a peeping tom. < really? he peeps? how come you are the only one complaining? oh, and if he does peep, hell get kicked out. OH! more importantly, where is your proof?

Agree with previous comments about Brenda — very nice and accomodating at the beginning, but once you dont resign a lease gets pretty nasty. Id lived there many years w/o a single noise complaint, then shortly after i didnt resign my lease I fell asleep in my bedroom with a Lost marathon still playing. The next day I saw a nasty note on my door from Brenda saying shed call the police if there was another noise complaint!!! So much for warnings/any pretense at civility  Im sure she was trying to kiss up to the new ppl whod moved in next door. < WOW! this must be a joke. One, there must have been multiple complaints before she will give you a letter. Two, you fell asleep with loud music on is very disturbing to those around you. That means while you sleep so peacefully, the others cannot. So how can they not complain to Brenda? Three, she is nice to you even if you do not resign a lease. She was nice enough to help someone moved out on the day i moved in.

Items of gym equipment broke 6 months ago and still havent been fixed/replaced as of my moveout. < Then you must have moved out at the right time. ONCE you moved out, all the gym equipment got fixed.

management was incredibly shady about refunding security deposit, vastly overinflated costs and charged me for things Brenda said wouldnt be charged for when I was moving in. Be warned! I think it might be the owners policy to withhold all security deposits until you threaten them with a lawyer (which I did and got every penny back). < Umm, you do know that management is not the one who refunds your deposit right? It is the OWNERS who determines how much to give back. Oh, dont even trust this guy. You can ask Brenda for pictures of his apartment when he moved out and see how filthy it looked. He should be glad that he received his full deposit back.

Now I know how they can afford to give you that discount on the first months rent!!! Make sure to take digital photos when you move in and move out and demand a walkthrough before you move out. I HATE the way slumlords in Davis like to bleed the poor for money. < Brenda gives you the option to have a pre walkthrough or not. The only way that you will not get a pre walk is if you declined it. And you can always request for a pre walk through if you want, but i bet you DavisGeek never did.

Ive been here for about a year and i am very satisfied with this complex. Okay, it is not the newest apartment around but for the price we are paying, it is very good. We are close to so many bus lines and we live about 34 min drive away from target. It is a great location and everyone here is community friendly. My housemates and I are very glad that we chose this place and we plan to stay here for another year or so. Oh, i love you their contests and stuff, it is so much fun to participate in and look at others decoration. FYI, i dont get paid for saying all these. I just dont like people twisting the truth. This place is really friendly with children and UCD students. People should really check this place out.   Users/Hollen

20100223 22:13:07 nbsp Reading the inflammatory comments of some of the posters here have compelled me to contribute my two cents.  I cant stand it when people write things out of boredom, ignorance, or spite.

Ive lived at El Macero Village Apartments in South Davis for a total of 3 years, and given any choice of apartments either in Davis or Sacramento, I would pick El Macero Village any day.  As a matter of fact, after 1 very happy/productive year at El Macero, I moved away to Sacramento to try to reduce my commute.  I ended up moving back right after my Sacramento lease expired.  Why do I like living at El Macero Village so much?  There are many reasons, but it starts with the people who keep the property running well.  The property manager Brenda, and property maintenance staff Miguel and Alan are a class actthey are kind, fair, friendly, professional, efficient and helpful, in a way that simply puts other managed properties in Davis and Sacramento to shame.  They do their very best to make the residents feel comfortable.

In terms of practical benefits, living at El Macero was a godsend to meits the perfect place for a studious graduate student to live and study.  Ive broken it down:

NOISE:  The complex is quietno loud parties, no people drunken late at night, no walking out in the morning to find vomit on the bushes, etc.

LOCATION:  I commute to Sacramento, and its right off of the Mace Exit (last Davis exit before the Causeway), and while it is near the train tracks and freeway it is set far back enough that the noise is not a problem. Super convenient to be literally 2 blocks from the freeway entrance.

SPACIOUSNESS:  While it is an older apartment, this also translates into larger floorplans; the master bedroom in the 2br/2ba is huge, check out the dimensions on the website.  I was able to fit a small sofa, a full size bed, and a large desk in there and still have room for two bookshelves.  I previously lived at the Lexington Apartments and Glacier Point Apartments, and know friends living at Tanglewood and other complexes.  The rooms there were tiny, able to fit a full size bed and a small desk.  While these other complexes were newer, the environment was uninhabitable for a serious student.  Between the loud parties, drunken/stoned neighbors (mainly at the Lexington) I found myself caring only that I got my sleep.  I didnt care how bright and beautiful the apartments were.

NEIGHBORS/ENVIRONMENT:  El Macero is a quiet complex, spacious, friendly (nice neighbors, mostly pet owners, students, and young families) with good people running the place.  I love how it feels laid back.  It is also very much affordable. Its pet friendly, its nice coming home and seeing neighbors walking their dogs and stopping to chat.  Its possible to grow a small garden in the private patios (for groundfloor units).  The patios are just big enough to accomodate a small garden table and four small chairs.  The management encourage residents to decorate their homes for the holidays, with decorating contests. In the summers its nice to lay out by the pool or on the lawn.

GYM/WORKOUT: Its great to have a gym thats not very crowded.  I love the fact that if I dont feel like running indoors, that I could just head down the streetits very safe to jog even late at night in South Davis.  Im not much for swimming, but we have a clean and wellmaintained pool and a jacuzzi.

VALUE:  I also love the fact that my roommate and I each had our own room and bath for at least $100200 less than what my friends were paying. It helps to get in on a sublease; though the rental increases have been incremental and not outrageous.

PARKING:  Parking is ample, first come first served.  They have hoses near the parking lot for those who like to wash their own cars.

LOCAL RESTAURANTS/BUSINESSES:  I love having the Nugget, Cindys, Guadalajara Grill, Subway and Thai Dynamite (yum) within walking distance.  Im not a big fan of the Chinese place in the Nugget complex.  Ive frequently walked to take a dinner break for cheap and tasty Mexican food, or make a quick run for last minute groceries.  For someone who commutes to Sacramento, its perfect because the gas station and freeway entrance is literally two blocks away.  Its nice to be able to drop by at the Nugget on the way back homevery convenient.  I have a Honda, and I can say it is REALLY nice to be able to drop off my car for an oil change or major service, walk two blocks home, and walk back to go get my car.

LAUNDRY:  There is a pretty large laundry room, its usually not crowded.  Its cardoperated, and the machines are quite new and work well.  I havent had any problems with the machines eating up money.  And if I did, Id simply talk to Brenda and Id be confident shed fix the situation.

MAINTENANCE/SECURITY:  Theyve refunded what was fair to me in terms of deposit; when I had emergency problems they were able to solve them promptly if not immediately.  For example, within 5 minutes of my calling about a broken kitchen faucet Miguel was already over to my apartment, and had replaced it within 15 minutes.  Miguel and Alan are always working on the grounds, taking care of the property so that everything is wellmaintained.  They have an excellent work ethic, have been entirely professional in addition to being warm and helpful.  It is upsetting to see that some posters here on this site have taken to falsely maligning really good people.  Miguel and Alan have gone above and beyond to help me with a dead car battery (multiple occasions) a lock out when I thought I lost my key.  In case people are thinking Im biased, I happen to know that Brenda, Miguel, and Alan volunteered to help my new neighbor move their piano so that they wouldnt have to pay for professional movers.  Several of my friends have lived here, and have felt the same way as I do about El Macero.  This kind of neighborly concern for each other is what I think sets El Macero Village apartliving here I felt like I was part of a community, and people know and watch out for me.

Id highly recommend El Macero Village as a place to call home.  If you are lucky enough, take over a sublease so that you can request to continue the lower rental rate.  This is the place for you if you want a dramafree, affordable, clean, quiet and friendly place to call home. Users/JMDavis

20100504 15:34:27 nbsp Seems like my previous comments have ticked some people off.  Please note that giants2010 and hollen have never posted anything on daviswiki except proEl Macero management comments in response to mine (and one snide insult).  Hollen is Brenda herself (Hi Brenda!) since #1 she claims to have seen pics of my apartment after moveout and #2 uses Brendas favorite buzzword of filthy (used liberally on my moveout claims form).  Just think for a minute about how these responses sound like promotional ads for the paradise that is this apartment complex.  Also didnt know it was standard procedure for management to take pictures of dirty apartments after moveout and offer to show them to others!  I guess Hollen cares so much that shes intimately familiar with former tenents lives despite having lived there a little less than a year.  Giants2010 sounds like Brendas unemployed teenage son (the one that likes to blast loud music in the gym while people are studying for finals).  He probably has lived there for 15 years, but read the rest of what he says... normal people tend not to call themselves assholes as a way to establish how great and tolerant management is!  Old people (ie grandfathers which he claims to be) also typically dont insult strangers over the internet (ie the comment about comcast).

I stand by everything else I said.  The lat/pulldown machine in the gym had a broken cord that was never repaired despite me writing notes to management about it.  Interestingly the sign I posted in the gym saying it had been broken for six months was taken down the next day.  Two exercise bikes that I used regularly broke and were taken away and never replaced.  I ask you the reader  which is more likely?  An apt complex being tightfisted with a buck and delaying repairs or me flat out making stuff up?  Also, consider the overall bulk of comments posted before I started posting at all.

As far as the bald maintenance dude: I would never lie about something that implicates someones character.  There is a locked door between the laundry room and the kitchen area of the gym room.  I noticed that sometimes it would be unlocked, which is strange since the regular gym key doesnt fit the lock.  One day I was in the gym and the bald dude came rushing out of the laundry room and headed straight for the window overlooking the pool.  He basically stood there without moving for a while and didnt notice I was there (I was in the corner using a machine and held very still since i wondered what he was up to).  Because this particular gym is covered in mirrors, i was able to see what he was looking at  it was basically the shapely rear end of a girl who was walking down the sidewalk!  I saw this same behavior repeated EXTREMELY regularly.  He never did it unless there was a hot girl walking down the sidewalk... figured he saw her in the laundry room window and rushed out to get a second, longer look from the gym window.  Another part to the story is that my special lady friend was often in my ground floor bedroom in a state of undress.. who would often happen by except the bald dude?  Considering the amount of mowing, weedwhacking, edging and god knows what else they do he always could find some reason to be around when she was in the bedroom.  Rather than report him and risk ticking management off, I simply made sure the blinds were always closed and bought a blackout curtain.  But GF or not, that is what this guy was all about.  I NEVER saw Miguel, the head maintenance dude lingering near my window or even looking.   Users/davisGeek

20100504 16:04:20 nbsp Oh, one last reply to Hollen (ie Brenda) >  I never once received a single noise complaint of any kind prior to the Lost incident.  Neutral readers please note that Hollen is convinced Im lying because there must have been multiple complaints before mgmt gives you a letter.  You attack me for not being able to prove many of the things I say  so where is your proof there were prior complaints?

The reason there were categorically no prior complaints EVER is because I am a grad student and psycho about noise.  I have complained about my neighbors multiple times for being too loud and all they got was a verbal request to keep things down.  Thus it seemed incredibly, insanely unfair that I didnt get a warning for a first offense, but a nasty threatening letter, especially when the neighbor didnt even knock and ask me to turn it off first!  I stand by what I said  pure animosity for not resigning my lease. Users/davisGeek

20100603 16:52:57 nbsp reply to davisGeek Im flattered you think Im Brenda! Thanks Users/Hollen

20110216 23:43:00 nbsp Because Davisgeek seemed to be getting flogged by a lot of comments I just wanted to add my own.  I did live at El Macero apartments and I wish that someone had stood by Davisgeek and note completely thrown his opinions out the window.  To a lot of people who read these comments to get a grasp of how living at a certain apartment is, you should at least take in some of the things he mentions.  Some things I will say are that as far as grocery goes  its convenient with a Nugget right there.  If thats too expensive youll have to have a car since buses dont run as often as apartments closer to campus.  Also one thing to take note of is the amount of children there are.  Since its a little farther from campus you do get more families living there.  While I lived there a lot of the children ran around in the parking lot and all over.  Sometimes even playing on my stairway.  They do fun things during the holidays, but its not very genuine.  Its like they have you decorate for them to make the complex look nicer then get angry if you leave it up because youre busy with class or work.  Its a pet friendly place which is a plus but theres only one pet place and it can cause a lot of conflict with other people.
I would warn about one thing which is that there is across the way a fire department and YOU WILL absolutely hear fire trucks all hours.  Also they run leaf blowers all the time and blow leaves all over your patio and balcony.
As far as management goes.  Its like management anywhere else.  Theyre not the best and if you dont spend the time to get on her good side you might have to watch out.

Its an okay place to live.  I really wouldnt recommend it if youre a student for reasons I mentioned before: the kids, the sirens, and the location isnt that great.

Everyone here has a different relationship with management and once I moved out it was a big relief.  Also a lot of the apartments are close together so people WILL complain about you.  The hours are inconvenient to meet with management as well.

The apartment itself is okay, but the rest of it might not be worth it.
Im just writing the review I wish I had read before I moved in.
Once I moved out Ive been a lot happier.  It can be really stressful living in a place where so many kids are, or where so many residents stay in their apartments all day and lodge complaints against one another.

  Users/citycat

20110315 12:50:11 nbsp Overall I had a positive experience living at El Macero Village.  I lived there from Summer 2006 through January 2011 in three different apartments: three bedroom, two bedroom and one bedroom.  For me the main draw in staying there for 4 and 1/2 years was the value for money, management, maintenance and location.

Few other apartment complexes in Davis have a remotely competitive rate per square footage.  I found Brenda a likable, responsible manager.  I appreciated that actually lived on site.  Any maintenance problems I had were quickly attended to within a week or sooner.  Locationwise I appreciated living on both the A and P/Q lines for commuting to campus: about 2025 minutes.  I would normally walk to Nugget for groceries.

For the negatives I have to say the complex is aging.  Most of the apartments have thin walls which makes even ordinary activities easy to hear through the walls.  On the upside this place tends to be quieter than most.  The mix of residents seemed to me an even mix of grads, undergrads, young professionals and families.  I didnt mind the noise of the children that lived near me, but I was usually not home during daytime hours.  Ive lived at El Macero through two fairly extensive but needed exterior renovations: one of the decks/patios, exterior wood, painting and one reroofing.  These were minor annoyances but definitely show me that some care is being taken to maintain the complex.

Some folks have also stated having issues with Brenda herself.  Ive never experienced any trouble with money, deposits or repairs.  I got the impression that she could be strict when needed, but I always found her to be fair.  She was always responsive and proactive when I had an issue with a noisy neighbor or maintenance problem. Users/MarkHixson

20110614 09:44:15 nbsp I just moved out of El Macero after living there for 4 years.  My experience has been outstanding.  They are extremely family friendly and pet friendly.  They work very hard to keep the premises looking quite nice but still keeping rent low.  The property management team is unbelievably responsive to any problems you may encounter either with the facility or other tenants (both of which were few and far between in my experience).  Brenda is extremely fair in all matters and if you are a quiet, respectful, payontime type tenant she will bend over backwards to keep you (i.e., does not jack up rent and will work with you whatever your situation).  If you are looking for a quiet, safe place to live that is an excellent value, I highly recommend El Macero Apartments! Users/ccc4

20110627 22:09:39 nbsp I initially found El Macero Village on Davis Wiki so I thought Id return the favor and do a post that might help others. (Note: This review is a copy/paste job from my Yelp account fszeto.yelp.com)
Ive lived here for the past 2 years and will move out in September when I finish my undergrad. My experience here has been great.

El Macero Villiage is an apartment complex in South Davis. Theres a no party clause that all tenants must agree to, so if youre looking for a place to party, I wouldnt recommend El Macero. The grounds are kept beautiful at all times, but the buildings do seem a little on the older side. Certain parts of the floor in our apartment are creaky, and unfortunately were on the second floor, so weve learned to take longer strides over certain places to minimize noise to the residents below us. Also note that walls/doors are a little on the thin side.

Management is lovely. Brenda is friendly, welcoming, and helpful. Shes always greeted me with a warm smile. Miguel and Alan are always maintaining EVERYTHING, from problems with the units themselves to mowing the grass, trimming the hedges, cleaning the pool, etc. Theyre always hard at work but they always take the time out to greet you with a smile and a hello. Maintenance has always been very speedy for us on the rare occasions that weve needed it.

Parking is not a problem. The parking lot is the entire perimeter around the complex. Just make sure to register your car. Theres also street parking along the outside of the complex. If you dont have a car, the A and 42A bus lines stop right outside Building 2. The Q and 42B lines are just across the street. Depending on the bus and traffic, its just a 1015 minute ride from Downtown Davis.

El Macero is pet friendly so theres lots of dogs and cats. And because theres a lot of families living here, there are also many children. A word of caution: sometimes the children running/biking/skating/playing around the complex arent watched by adults so Id especially watch out if theyre playing in the parking lot.

Theres a gym and a laundry room open for all residents to use. Theres a washer and dryer in our unit so Ive never been in the laundry room. Im in the gym a couple times a week and dont really notice any problems with it. Its not the ARC, so theres a chance youll have to wait to use the machine you want. If something breaks down, it can take a little time for it to get fixed because they need to contact someone to fix it.

El Macero is right across the street from Nugget Market, and less than a 5 minute drive from Target. Theres also a fire station across the street so youll occasionally hear the sirens but if that bothers you, you probably shouldnt live here. Sometimes you can also hear the train.

If youre a student, El Macero is a little far from campus, BUT its worth it. Its much more affordable than many other places in Davis, and its a beautiful place. I always tell my friends that if distance isnt an issue (just adjust your schedule for a slightly longer bus ride) then they should definitely consider El Macero Users/fszeto

20111212 21:52:52 nbsp I accidentally had a package delivered to my former El Macero apartment last week (I moved to Placerville for work 2 years ago). Brenda, the office manager, was very nice and even offered to meet me on her day off so I could retrieve the package. And Thank You to the honest person in apt 40 who turned it in!  Users/mpclark

20120429 19:32:42 nbsp My girlfriend and I just moved here last August and weve made the best decision by choosing El Macero. We both love it here so much! The staff are very friendly and they will help you if you need help with anything, even small personal things (They jumped started my car when my battery died!). Brenda, who works at the front desk, may be the NICEST person I have ever met! She will help you out with anything and will do her best in keeping you as a tenant happy. They have a nice sized workout room, swimming pool, a Jacuzzi, and there are BBQ pits around too! Theres a lot of parking for everyone in the apartments, and the parking lot is close by no matter which apartment you live in. Longest you will take to walk to your apartment from your car is probably 2 minutes. Unitrans and Yolobus are literally right in the front, so you dont have to worry about rushing to catch the bus and finding that youre either too early or too late. I dont have any bad things to say at all about this place, but all I know is that if youre a UCD student you will think its a far drive. But trust me, you wont regret moving into this great place! Users/Jondguzman

20120622 13:08:58 nbsp I moved into El Macero Village in September 2011. I share a 3 bed, 2 bath apartment with 4 other students. Its a great place for a somebody that doesnt want to be constantly surrounded by parties. Most of the other residents are families, so unlike other apartments, you have the choice of going to a noisy party rather than living in one.
The apartment itself is by no means a 5 star resort, but it is comfortable and accommodating for a limited budget. The kitchen is a little small, but is sufficient for 3 people to do a coordinated kitchen dance while preparing large meals. Except for the bathrooms and kitchen, all floors have beige carpeting. Its not the newest, with a few stains, but once again....this is not a 5 star resort. Washer and dryer unit that is included is a great way to save money. The only negative thing I have to say about the apartment is that except for bathrooms and kitchen...there are NO CEILING LIGHTS. Needless to say, IKEA made some money off of us when we purchased multiple floor lamps.
There have been a couple of things that needed to be fixed due to natural wear and tear. Maintenance staff consists of Miguel and Alan who are very friendly and always try to get everything fixed as soon as possible, sometimes even within 20 minutes of being informed of the problem. The longest I had to wait was 1 day and the door was fixed in 5 minutes. The property manager, Brenda, is professional, courteous, and a total sweetheart. When our upstairs neighbors were making noises at 3am like they were practicing jumping jacks or studying for a feng shui midterm, she wasted no time contacting them. When it happened again the next week, she notified them again and told us that if this was a repeated occurrence she would have no problem helping us move into a different unit.
All in all, this is a good place to live if you want someplace that is quiet and not overrun with obnoxiously loud parties. Its relatively affordable and not a dump and the grounds are kept clean. Lots of trees, with manicured lawns and decorative bushes. The only sacrifice you make is slightly dingy carpeting and a longer (20 minute) bus ride to campus. Users/BabyMammoth

20120801 14:39:07 nbsp I lived at El Macero for the past 3 years, during my Undergrad at UCD.  From the first moment I met Brenda, the apartment manager, I instantly liked her. She was friendly and understanding, and would lend a sympathetic ear when I struggled with school and relationships.  Miguel and Alan, who do a lot of the maintenance, were always friendly as well.  Miguel even gave me automotive advice, which was very nice.  I lived in a 3 bedroom apartment, and I loved the space, as the price was magnificent. Not to mention the washer and dryer in the apartment, and the many cabinets in the kitchen for me and my roommates to put all our food and appliances.  The apartment was nice and quiet, and was relatively cool.  The parking was never a problem, as there are many open spaces for tenants and guests.  I rode the A or P/Q buses everyday, and the bus stops were conveniently placed, Aline right in front of the complex, and P/Qlines just at the corner. I loved to see all the pets, and the friendly tenants. I chose this place because of the great reviews, the price, and the location.  I love the fact that it isnt too far from the I80, as it is convenient when giving directions or reducing the time travelling through town.  It is within walking distance of the Nugget shopping center, and different restaurants.  There is even a fire station nearby, which to me, always made irrational fears of fire nonexistent.  It is a very safe and quiet neighborhood, and walking alone at night wasnt scary.  There is even a park nearby, if you want to play tennis close to home.  I got nearly all of my safety deposit back after moving out, some was taken because a roommate had spilled some bleach near the washing machine, but it was fair.  I cant express my supreme satisfaction with living here, and it is well worth the distance from campus. Users/LisaD@UCD


20120823 14:28:56 nbsp Our family of 4 just moved in and this is a great place to live if you are looking for a quiet, family friendly, clean and tidy complex. Our apartment is immaculate, freshly painted, has brand new carpet, and brand new appliances. It is close to shopping and good places to eat. There is a bus stop right out front if you dont have a car. It is also easy for anyone that commutes to Sac. Brenda and Miguel are really nice and go the extra mile to make you feel comfortable. The other employees are also very nice and courteous. The other renters in the complex are considerate and always say hi, giving the complex a feeling of community.  It is close to schools and safe for kids. It has a park nearby and it is a nice for people who like to run or take their dogs out to play. The pool is nice, clean, and the perfect temperature and we use it and the spa every day. I would highly recommend this complex for family and students that are looking for a quiet, friendly, safe place to study. Users/CatherineLamm

20130215 01:20:28 nbsp When I needed to find an apartment with a nonstandard lease, El Macero was one of the few places in Davis willing to provide one. Brenda was very accommodating during the application process and afterwards as well. Apartments are pretty nice and I did not run into any issues. I would definitely recommend this complex. Users/hankim

20140131 08:00:18 nbsp The long and short of it is that they have older buildings. The apartments share walls there are cross over sounds that you would expect like voices or TV but in this instance can hear cabinets in kitchen or bath being snapped shut, garbage disposal run, oven fan going, sounds from dishwasher, and windows opening and closing, doors the same. The air vent system brings in cooking fumes from other apartments ex. you can tell how much salt pepper being used on fried steaks as if you were in the other apartment cooking it yourself! These things are structural issues, how walls were insulated when built or air vents designed  simply cant be changed. Users/FrankOmalley
