


Elizabeths Pet Sitting is an oncall licensed, insured and bonded pet sitting service thats run by Users/ElizabethBarthel Elizabeth Barthel, a preveterinarian Animal Science student who graduated with a degree in Animal Science. She currently has one employee: Mary Barthel. Services provided include dogs dog exercising, weekly dog walking, pet grooming grooming, and pet medication/medical attention, as well as plant and home care. Elizabeth offers inhome livein care and overnight services.  She also offers private boarding at her house.  Elizabeth has experience with a wide range of animals including companion and captive animals, birds, livestock, and exotics. All animals are welcome. Elizabeths Pet Sitting is a current member of Pet Sitters International as of 20 March 2013 :http://m.petsit.com/mobile/locate_details.php/id/332387

Please be aware Elizabeth has admitted to violations of the 3dog per person limit at the Toad Hollow Dog Park despite repeated requests to stop doing so. There were also complaints in 2013 about dog bites.

Link to her pet sitting video :http://www.youtube.com/watch?v65KVHO0UNYM

Elizabeths Pet Sitting has a ReferaFriend Rewards Program. If a client refers Elizabeths services to a friend, relative, neighbor, or colleague, and they book at least 3 visits with Elizabeths Pet Sitting, then the client will be rewarded with $10 off any service and their friend will receive $5 off.  Referrals must mention the name of the existing client at time of booking.






For other pet services and supplies see Pet Stores, groomers, or Dogs for dogspecific listings.

Services Provided

  Daily Pet Visits
  Home Care
  Boarding
  Doggie Daycare
  Overnight Service
  Dog Walking/Trips to the Dog Park
  Pet Taxi to the Groomer/Veterinarian
  Special Needs Administer medications: oral, injected, or subcutaneous (subQ), Express Bladder
  Poop Pickup
  Nail Trimming, Bath, Brush, FURminator (No clips)

Qualifications
  Pet First Aid/CPR Certified
  Experience in clinical care and veterinary medicine
  Care and Management of animals
  http://www.solanoferals.org/ Solano Feral Feline Spay/Neuter Clinic
  http://www.vetmed.ucdavis.edu/clubs/mercer/ Mercer Veterinary Clinic 
  Davis Small Animal Hospital Intern
  http://www.sbdawg.net/dawgs/ DAWG: Dog Adoption Welfare Group 
  http://www.bunssb.org/ BUNS: Bunnies Urgently Needing Shelter
  http://www.asapcats.org/ ASAP: Animal Shelter Assistance Program
  Experience in dog behavior and training
  2005 Spay Day Animal Guardian
  Small Animal Radiology and Ultrasound Intern
  Avian Science Research Facility barn resident
  Santa Barbara Humane Society Spay/Neuter and Vaccine Clinic
  Internships and research experience at the UC Davis Vet Med Teaching Hospital
  Rabbit, sheep, goat, turkey, and chicken projects through Future Farmers of America (FFA)
  Behavior assistant in http://www.nerdbook.com/sophia/kittyclass/ Sophia Yins puppy preschool, kitty kindergarten, and dog training class

Pictures with the Clients Pets

 For a page full of the various canine companions of Davis that Elizabeth has sat, check out the /Client Gallery Client Gallery.  Here are a few of Elizabeth in action:







 2010 Christmas Well Wishes 



  /2006 Reviews Reviews from 2006
  /2007 Reviews Reviews from 2007
  /2008 Reviews Reviews from 2008
  /2009 Reviews Reviews from 2009

 Recent Reviews 

20100108 14:06:07 nbsp Elizabeth has been a fantastic pet sitter for me over the past year.  She does such a wonderful job caring for my pets that they hardly notice Ive been away.  She is professional and organized and I will continue to have her watch my pets as long as Im in Davis :)  Thanks again, Elizabeth! Users/nmspotswood

20100314 01:50:31 nbsp Elizabeths Pet Sitting has been responsible for the care of my two cats and fish on 34 occasions, and I very highly recommend Elizabeths services!  Before I was gone the first time, Elizabeth came over to my apartment, and we discussed the details for caring for my pets.  She is extremely organized and requires various paperwork before the actual sitting takes place, and I very much appreciate how thorough the questionnaire was.  Every time Ive come home, my apartment has been clean with no trash left out and all of the spoons (used for scooping canned food) washed.  My fish looked happy and healthy, and the two cats had been obviously well taken care of and were happy to see me.  Elizabeth has always been professional and friendly.  She is also very flexible when it comes to dates, which is wonderful if youre a student like I am and often have an unpredictable schedule.  Overall, Id recommend her services to anyone, and I put my full confidence in her pet sitting abilities. Users/hwarpeha

20100315 11:27:42 nbsp Elizabeth did a wonderful job taking good care of our elderly cat (20 yrs old!)  My husband and I recently moved to Davis and we were worried about leaving our cat alone.  It was such a relief to meet Elizabeth who we found to be extremely professional, responcible, and reliable.  She texted us updates about our cat, and she took time to give her sub Q fluids every other day.  I am happy to recommend Elizabeth and her services.  It is comforting to know that your beloved pet is in good hands! Users/MeghanLML

20100410 09:41:08 nbsp I have hired many pet sitters in my adult life and have never been so thrilled with one as I am with Elizabeth.  She immediately responded to my dogs in a ways that spoke to years of experience.  Now this is not so difficult with my Golden Lab as she is a mellow easy to care for dog, but when we got our new puppy  I could really see that Elizabeth is no only a talented dog handler a gifted human being.  My puppy had serious socialization problems and I thought we werent going to be able to keep him.  I told Elizabeth about the problems and she even went to a dog training class with us and asked questions about how to better work with my puppy.  She worked with him while he was with her and even trimmed his nails with his vet. couldnt even do.  When we came back our puppy was a different dog  far more socialized and sweet and dog like  vs. the small demon we had before.  Remember, this was a dog sitting job!   and what we got out was so much more  Elizabeth really cares about pets and we wouldnt hire anyone else.   Users/mulberry

20100422 14:43:53 nbsp I recently left my bichon with Elizabeth for almost 3 weeks.  When I returned home the dog was happy, the house was just as I had left it, there were notes regarding her care.  My husband and I could not be more happy with the service that Elizabeth provided!  Elizabeth is very concerned about the pets that she cares for.  She had such a gently touch with our dog that she was jumping up to kiss her on theire first meeting.  She is knowledgeable about all breeds, she has extensive experience with animals, and she is a kind and sweet person.  After meeting her twice, I could leeave my 10 month old dog with her without any concerns at all.  I trust Elizabeth with my dog, my house, and anything else she needs.  Elizabeth you are the best!    Users/SophieBelle

20100621 14:58:19 nbsp I cannot put into words what a relief it is to have found someone who I feel completely safe leaving my dogs with when we go out of town. I have two labs, and they are like my kids, I love them so much, and would never be able to bear leaving them in a kennel. Elizabeth takes our dogs into her home, takes them on walks or to the dog park 12 times daily, provides them with food & water, dogbuddies, playtime & lotsa love. Thanks to us spoiling them, they even insist on sleeping in bed with her (Im embarrassed to say!). Because of Elizabeths experience with the UCD Vet Hospital I know that if one of them got hurt or sick shed know exactly what to do. And, she even takes time to post pictures on my Facebook page of my babies having fun. Shes the best, I would recommend her to anyone and everyone!  Users/jennyann002

20100705 19:16:27 nbsp My Labradors, Lulu and Spencer absolutely LOVE Elizabeth.  When they see her at the Dog Park, they run all the way across the field to get to her.  When I leave them off before a trip, they dont even look back.  It makes it possible for me to enjoy my time away because I know they are safe and happy.  Recently, she even took them to the vet...a daunting experience for anyone since they are big babies.  I dont know what I would do without her.  I can travel now with no guilt or concerns.Sharon Stahl Users/sharonstahl

20100711 12:58:53 nbsp Elizabeth has been walking our dogs for several years and sits with them when we take trips and she has been doing an excellent job. The dogs love her and Alex and they take great care of our animals. She has never let our beagles overfeed and if you know beagles, you know they will eat until they cant physically eat more!  Users/RickH

20100719 11:28:05 nbsp Chickens!  We have had Elizabeth tend to our three chickens  the first time for more 10 days last October.  She did a wonderful job and followed all of our requests for feeding and cleaning to the letter.  During this time there was a major storm which damaged the coop and Elizabeth is especially to be commended for taking care of keeping the chickens safe.  Since that time we have used her services for shorter vacations and we have every confidence in her dependability and professionalism. And, it is clear she likes chickens too :)  Users/MaryGillon

20100728 13:03:22 nbsp When we moved to Davis, my husband severely injured his back and was going to be alone with a near pup.  Elizabeth came to our rescue.  Our dog Buddha loves her and for some reason comes back better behaved then when he left.  Elizabeth has been there for us during the late stages of my pregnancy, was oncall for our dog for the baby delivery, and has been his dog park savior since.  She has a way with animals and has been extremely professional, flexible and reliable with us.  When Buddha spends the weekend or the night, she has sent us photos of him hanging out happily with her dogs  nice to know he isnt spending the time cooped up in a crate.  I cant more highly recommend her  but once you see her with your pet, you will feel good about them spending time together.
 Users/hladner

20100809 15:56:40 nbsp We have used Elizabeths Pet Sitting to care for our dog and cat for a couple of years now and have always received exemplary service. She has always followed our detailed instructions and has been able to improvise wonderfully when presented with unexpected situations. We look forward to utilizing her services when we go on our next trip. She is highly recommended. Users/ParshawVaziri

20100815 10:24:30 nbsp Elizabeth is professional, reliable, and easy to work with.  She goes out of her way to make you feel comfortable leaving your pets in her care.  I have had her sit our two cats several times and I definitely plan on using her again.  I would recommend her services to anyone! Users/DavidSimon

20100822 20:51:51 nbsp We are so happy with Elizabeth and how she takes care of our dog. We have her walk our dog a few times a week, but our schedules are pretty variable. Luckily she is very flexible  we just email her the days we need her to come at the beginning of the week and she takes care of it. It is so comforting to know how dependable and trustworthy she is. She leaves us a note everyday with a brief summary of her visit. We also have our dog stay with her when we go out of town. It is so nice to know that he is getting to play with other dogs and isnt cooped up in a crate while we are away. Its also true what other people have commented  our dog is soooo happy to see Elizabeth whenever she picks him up or we run into her at the dog park. It makes us feel that much better knowing that he is with someone who he loves being with, who loves being with animals and takes such good care of him. We feel so lucky to have Elizabeth take care of our precious puppy and we cant recommend Elizabeth enough to others who need a dog walker or dog sitter! Users/REL

20100826 21:15:33 nbsp One of my cats is horribly afraid of strangers. When I returned from my 10 day trip, he was out on the sofa looking very smug and well cared for! It was obvious that Elizabeth had spent significant time loving on my cats, not just the occasional dropin that my friends do. Recently Elizabeth was able to work my dog in last minute for a family emergency. My plans fell through but she was extremely understanding. Im actually trying to book her for this weekend (have to tell her that soon)! Mary Pride Clark, DVM Users/mpclark

20100907 16:27:29 nbsp Elizabeth has been fantastic with my cat!!!!  She is very knowledgeable, loving, and her care for animals shines through.  I use her for pettsitting every time I leave town.  She has always been flexible with me when my plans havent gone exactly as planned.  She responds very quickly to my requests for service and I never worry about my cat while Im out of town and Elizabeth is watching him.  I highly recommend her service to anybody who wants their animals to feel loved while they are away. ~ Dana Users/DanaMatalon

20101019 09:53:57 nbsp Elizabeth is wonderful and loving with my huge German Shepherd. I travel a lot for work, so she keeps him at her home for weeks. She truely loves animals, and I feel that Sam is in the best hands with Elizabeth. He needs special food and sometimes medications and she always follows the program. My dog and I highly recommend Elizabeth. Users/InstDesignbyJulie

20101213 17:21:46 nbsp I have 2 large dogs, a boxer and a lab.  The boxer has significant dog aggession issues while the lab cries when we are away.  Elizabeth provides a wonderful service to Chalie and Jake.  I come home to quiet and contented dogs.  I trust her with my dog & my house keys.  Her services allow peace of mind while I am away from home.  Thanks Elizabeth.  Users/KellyMacy

20101215 22:23:39 nbsp DO NOT USE THIS SERVICE!!!  Elizabeth is completely irresponsible. She was supposed to come to feed my cats while I was away for 4 days and she never showed up. I am happy that I wasnt gone long enough for there to be serious consequences. If want your cats to starve this service is for you! Users/annoyedResident

Annoyed...if you are uncomfortable using your name, clearly your comments cannot be taken seriously. Elizabeth is a hardworking, dedicated, petdevoted individual as is evident from the preponderance of the comments here on this site. If you had a problem with her work, take it up with her personally, do not slander her name here on this site.Suzanne Emerson

20101225 18:15:44 nbsp Thankfully, Elizabeth is able to watch our dog in her home, which has been a convient and wonderful service. Theodore, our Terrier mix makes himself right at home and has gotten along well with her cats and other canine clients. He gets daily walks and gets to hang out in the house, which he loves. Its the next best thing to being at our home. Prior to Theo, our golden retriever was also able to hang out at Elizabeths home, and always seemed happy to go there, as does Theo. When we are away for extended periods, knowing that Elizabeth will be there to interact with him and take him out while letting him be a part of her furry family gives us peace of mind. Thanks Elizabeth for taking such good care of our four legged kids! Users/Aliciasmithpenzel

20110125 12:33:15 nbsp Elizabeth has been my petsitter for two goldens (Max and Wilson).  They love going to her home because she not only takes excellent care of them, but she blends them right into her pack.  Visits to the dog park, simple walks (for my older guy) and rainy day visits to the Lillard Park have proven to keep them really happy and healthy.  She is always ready to receive or have me pick up my dog even if it is late at night.  She is organized and truly enjoys her work.  I highly recommend her!  If you want your dog to have a good time while you are gone and you can also have a great time because you wont be worried about your pet  then contact Elizabeth!  She even posted a photo on my Facebook page of Wilson playing at the park over the December holiday.  So even though I was out of the state, I felt relieved to see how happy he was.  Thanks Elizabeth for being such a great asset to our community!  Candy Anderson Users/CJAnderson

20110215 18:18:38 nbsp It doesnt get much better to this infrequent traveler to arrive home to a household of content animals.  I have four dogs and a few barnyard animals.  When I walked in the door, I could swear they looked at me as if to say, Oh, its just you.  Wheres Elizabeth?  HIghly recommend Elizabeths Pet Sitting service to care for your animals.   Users/CharleneLogan

20110315 11:18:19 nbsp Elizabeth has cared for my dog Jax since he was a puppy and I have been very pleased and impressed with her service. I often leave Jax with Elizabeth when I am going out of town and have complete confidence that he will be very well cared for in my absence.  Elizabeth is a true animal lover, professional, responsible and pleasant. She offers good advice about training and was the person who taught Jax to sit and stay when he was only a few months old!  I am so happy to be able to drop Jax off on my way out of town from Sacramento and feel absolutely confident that my dog is in good hands.       Users/DeniseWunibald

20110414 17:47:16 nbsp I have only good reviews for Elizabeths service.  I trust her with my two dogs while on vacation and she always goes out of her way to make accommodations with transportation out to Winters.  Her frequent visits to the dog park make her service above and beyond the services that kennels offer.  I have a very timid girl and I know Elizabeth knows how to give her what she needs.  Hannah and Reuben enjoy their vacation time in Davis and love all the dog connections she has!!  Thank you from Donna, Rick, James, Hannah and Reuben.  Users/donnamacdougall

20110601 Elizabeth has been caring for our dogs for a few years now; we have complete trust in her and offer the most positive review possible. When we drive up to her place with the dogs, they get very excitedly happy and push on the gate to try to gain entry. I can go on, but many above have said all the right things.   Larry

20110615 15:18:53 nbsp Elizabeth is simply amazing.  I have an extremely skittish and difficult dog, Domino.  Hes a rescue and doesnt trust people normally. The first day Elizabeth met Domino, he tried to test her by nipping her hand.  Elizabeth was caring but firm with him and won him over instantly.  When Elizabeth took Domino out for his first day of care, he was excited to go with her and had a fabulous, fear free day.  Ive seen how the other dogs interact with Elizabeth.  The love her and are calm as a group.  If youre looking for someone who is trustworthy, gives great care and good with any animal, Elizabeth is the way to go hands down!    Users/KenyaMitchell

20110629 19:00:14 nbsp I think Elizabeth is fantastic.  I rarely go anywhere, but the few times I have, Elizabeth has taken such good care of all my animals (dogs, cat, chickens, goats, bunnies)..  This last time, I was so frantic trying to get out of the house for my daughters wedding that I left everything a mess, yet she took it all in stride.  She took such good care of everyonethey seemed to barely notice Id been gone for three days.  Thank you! Users/CharleneLogan

20110705 22:30:35 nbsp 2006 most recent service was 14 July 2011. We have used Elizabeth since moving to Winters in Oct 2006.  2 of our cats require medical attention, Elizabeth has always been able to give them their medications without fail.  She has called us when we went on a short notice trip; Joes medications had been changed to verify the change prior to giving Joe the medications.  She is very detail orientated and is wonderful with the cats.  All five of our cats even our feral comes out for Elizabeth.  It is great being able to leave knowing our cats are being well cared for. NissaStephenson

20110714 16:15:54 nbsp We have worked with Elizabeth for over a year and she has been 100% dependable. She always visits when she says she will, and our dog loves her. Also, Elizabeth has taken good care of our dog at her house while we have been on vacation. We highly recommend her! Users/CharanRanganath

20110807 21:20:00 nbsp We have never left our dog with anyone before and were a bit anxious about how he would do either by himself all alone at home or with other dogs at Elizabeths home.  We did feel confident, though, that Elizabeth would figure it out because shes very experienced and tunedin to dogs.  We returned after our 9 day trip to find that Oreo was at Elizabeths home the whole time and he enjoyed the security and comfort of being with others.  Were so pleased to have found someone so trustworthy, knowledgeable, dependable, and caring (of both the dog and the worried owners!).  Many thanks Elizabeth!!! ChristinaChang

20110821 13:53:56 nbsp We moved to Davis about a year ago, found Elizabeth on the wiki and gave her a try.  We have now used her several times and our Susie couldnt be happier. She is a dog that does not do well in kennels and is getting older so much appreciates the great attention she receives from Elizabeth.  Thanks Elizabeth! Users/RKeith

20110922 01:33:10 nbsp Elizabeth was FANTASTIC!!! I had 4 rats that needed babysitting and contacted her with really short notice. She was very considerate that my rats would probably be freaked out about other dogs so she gave them their whole separate room. ^_^ Thank you so much for taking care of them for me!  Users/Carolt

20111007 11:57:25 nbsp I tried using Elizabeth back in May for a week long trip my husband and I were taking. This was before there was any mention of her employee Suzie, here on the wiki or anywhere on her sites. I had seen Elizabeth at Toad Hollow numerous times and she is very very good with the dogs she brings there. This is what made me want to user her and because we had talked occasionally, she said we could forgo the consultation because she was already familiar with my dog, Maia. I emailed her back and forth the weeks leading up to our trip, and again the day before to confirm that I was to drop my dog off at her house at 2:45 the next day. The day off the dropoff, I had taken off work early and my husband had moved some meetings around because we both wanted to be there just so we could check everything out. We showed up at her house and knocked on the door, but nobody answered. There were 6 dogs barking at us through the window, which scared our dog. After finally getting a hold of her over the phone, she said she was stuck in traffic in Sacramento and told us to just let her inside. We were understanding about the traffic issue, but I told her I wasnt going to just open the door and leave her at a house unattended. Especially where I didnt know how she would react with the other dogs, so my husband and I went back home.

She called back saying her partner Suzie would meet us at her house to let Maia in, but with everything not going the way we had hoped, it was offputting to hear about a partner that we had never heard of before. Honestly, I am glad that she is listed here on the wiki now so as to clear any confusion. I did speak with Suzie on the phone that day and she was very understanding of our situation, and our need to find an alternative option, and even told me she agreed that her working for Elizabeth needs to be made more public. Users/rachand1

20111021 08:29:14 nbsp My son is on a sports team at UC Davis and so we wanted to come to Davis regularly to attend games. We were at a loss as to what we would do with our two dogs on these trips during games. After much research, we found Elizabeths Pet Sitting  an ideal solution for us as she cares for dogs in her home. Our dogs had several stays there, usually f...or about five hours, and they always came back worn out and happy. Each time we returned to Elizabeths, they were excited to go in the house, see Elizabeth and play with the other dogs. Thats proof that they had a good time (you know dogs, they will try to avoid going in to places they dont want to go to, like the vet!) We even have a dog that gets serious separation anxiety and she did very well and likes it there. Elizabeth understands dogs and dog behavior and has a very calming presence for the dogs. They obey her and respond well to her. Thanks to Elizabeth, we are able to see our son play sports. We just used a drop off service, but oftentimes dogs were staying with her for several days at a time and those dogs always seemed happy as well. We will continue to use her service. Its perfect for our needs! Users/doryford

20111113 11:55:21 nbsp Elizabeth has taken care of my little kitty 3 times in the past 2 months. She comes and picks him and takes care of him overnight. My kitty always runs towards her when she walks in and seems extremely happy around her. When she drops him back off, again he looks like hes been well taken care.. Its so convenient to have such a responsible petsitter around with flexible hours. She will be taking care of my kitty again for the 5 days Im gone for thanksgiving.  Elizabeth definitely  knows how to care for pets and I highly recommend her services so take advantage guys. Dont know what I would do without her!  Users/yasmohabbat

20120114 16:23:53 nbsp We left for eight days to go halfway across the country and left our two dogs at home for the first time. Elizabeth put us at ease right away.  She sent us a text message early the first morning she was there, sent us text updates throughout our trip and even sent us a few pictures of the dogs playing and on walks.  When we came home the dogs were really calm and it was evident they were well cared for while we were gone.  She took them to the dog park almost everyday, and asked our permission before she did it.  In the meet and greet we had with her before we left she took very detailed notes on the dogs schedule and rules and really paid attention to what we told her.  We will definitely use her again!    Users/BlairSwadley

20120211 19:17:30 nbsp Elizabeth: Many dog owners have asked you repeatedly to respect the threedog rule at the dog park, especially because you are incapable of controlling 57 dogs at once. Just because you run a business doesnt mean you are exempt. Do your clients know you constantly break the rules and piss off other dog owners? Users/MeggoWaffle

20120214 11:38:41 nbsp Meggo: Thanks for your concerns but I run a business and understand dog behavior extremely well . I graduated with a degree in Animal Science , volunteered with shelters, interned at the vet school hospital , and worked with 100s of dogs. Before I accept a client as a dog park client they must have certain qualifications behavior wise and training wise. I realize having and controlling several dogs at a time is a huge task and I am very attentive and responsible. I never bring aggressive or dominant, unneutered dogs to any public park . Most people at the park know me and appreciate the fact I am providing a service in a responsible way. Since I go to the dog park several times a day I know what to avoid and how to keep the dogs I care for engaged so your comment about not controlling my dgs s simply untrue. I love my job and will continue providing dog park runs for dogs in Davis that enjoy large group settings. The dogs are well socialized, have good manners , and enjoy their outings. I am upfront with my clients on the size of the groups I take out . Thanks for your concerns, to my knowledge I have not pissed anyone off for bringing well mannered, well trained, happy, playful dogs to socialize with others . Users/ElizabethBarthel
 Elizabeth, Im quite surprised you are denying being aware of angering other dog owners when I know at least three people who have directly voiced their concerns to you people who, by the way, have at least as much animal experience as you do. I appreciate all your credentials but that doesnt mean youre perfect or more knowledgeable than anybody else. For instance, I dont have a degree in animal science but I spent a few months, just me, controlling 40 uncaged dogs all day every day and that would be no excuse for bringing a huge group to the park. Im sorry, but none of this answers why you think youre entitled to break the threedog rule. Users/MeggoWaffle
  I agree with MW.  In fact, I stopped going to Toad Hollow because of an incident with a woman with more than three dogs.  It wasnt you, but like you, she claimed that she could handle all the dogs.  Well, she couldnt.  Even if you think that you can handle the dogs youre watching, the more people that break that rule, the harder it becomes to enforce it.  (No one else is following the rule, why should I?).  More to the point, the rule is three dogs maximum not three dogs maximum, but more if you are attentive and responsible.  You should follow the rule, just like everyone else.  Personally, I think its a good rule  dogs can be unpredictable, and a person can only watch so many things at once.  Of course, they can only be in one place at once, too.   Users/CovertProfessor

Not a good environment for dogs who suffer from anxiety or are sensitive.

When I arrived for the initial consultation I showed up literally to Elizabeth and her neighbor arguing over the chaos that was in her back yard. Her neighbor was asking her to please have the dogs be more controlled so they wouldnt bark day/night and she wouldnt have to resort to yelling and screaming at the dogs.

I was most definitely put off by this, but know how people can be so I gave Elizabeth the benefit of the doubt. But unfortunately, once I was inside her house I understood exactly what her neighbor was trying to stop. There were dogs sectioned off in her whole entire house.... Two in the kitchen, one in the hall way, three in the living room... it was a house FULL of gates... NO organization.... It was stressful for me just to sit down and speak with her. She was screaming at the dogs to be quiet, she was even telling me how this dog or that dog is difficult or bad..... The entire environment was Stressful! I brought my dog in so she could meet him, and there was this huge dog in the same section as us and he was just out of control! He was attacking my dog and I was waiting for Elizabeth to do something about it, but she didnt do anything until I finally walked over and grabbed the dog to keep him from bitting my dog.

It was an awful experience and I dont know how anyone could leave their dog with her if they truly care about the atmosphere they are in. It was high anxiety, stress, screaming, out of control dogs and dogs were in little sections of the house.... She is not organized to handle the amount of dogs she has.

I opted out of this type of place for my dog because as a puppy I dont want him exposed to this type of stress so early in life. It may be fine for your dog, but I would never recommend Elizabeth for anyones dog or cat.Users/ChewyNCompany

20130317 20:34:03 nbsp Elizabeth irresponsibly brings her personal dog that has bitten multiple dogs causing injuries requiring veterinary attention, including mine to Toad Hollow dog park. She also repeatedly violates the 3 dog maximum rule. Local vets do not recommend her either. Users/Mcourv

I would like to comment on this situation at hand because I feel this is a misrepresentation of my good faith character and business ordeals. The first thing is in both circumstances I took responsibility and paid the entire bill so I dont understand how that is being irresponsible. As a dog owner whether my personal dog or clients Im caring for I am responsible for making decisions. Hunter is a well socialized 1 year old English lab who has been around dogs since he was 10 weeks old. He has been a proud member of the Davis Dog park community since hes been 4 months old . He attended puppy classes and is very well trained. He is great with my daycare and vacation clients. All dogs can make mistakes and thats what happened. Hunter will see a trainer to get to the bottom of why he did it which I am starting to think it may be health related . Hunter never injured any dog up until these two incidents.
Now as for the  veterinary statement I dont understand why someone would say that when they dont know me personally, 2 never used my services and dont even know my relationships with vets in town. I have an outstanding reputation with vets in this town. I graduated UCD in 2008 as an Animal Science major and as a student interned at local vet clinics as well as worked at the veterinary medical teaching hospital for 5 yrs. On several occasions I have had to bring clients animas to the vet for emergencies and routine medical care while the client was out of town. The well being , safety and happiness of all animals is my priority and responsibility . This past Christmas I spent half the day in the emergency rm with a clients lab that had a heart attack and lead to one of the hardest decisions a pet sitter would have to make. Most vets you ask will say I am go above and beyond in any situation. I also track referrals and can tell you that on a regular basis I get referrals from clinics in Davis. Users/ElizabethBarthel Elizabeth Barthel

 I would recommend calling the police when you see her breaking the 3dogmax rule. She has been asked multiple times by multiple people to stop (you can see my discussion with her above and on her personal page) and it seems as though she doesnt have the consideration to listen to anybody  maybe the cops can help. Also, any vet bills caused by dogs under her care should be photocopied and sent to her. If she doesnt pay up, take her to small claims court. Its past time she start running her business more responsibly. Megan

~She did in fact pay the vet bills on both occasions, as it was her legal liability. Both clinics the injured dogs were taken to stated that they did not recommend her services. I am not saying that you are a horrible person or pet sitter Elizabeth, I am stating that some actions on your part are irresponsible; for example bringing more dogs than you can safely control, and continuing to bring hunter without any steps taken to prevent another incident after the first bite occurred, causing another bite to occur. Both dogs bitten were puppies that were being socialized. Incidents like that can permanently damage dogs, which is why aggressive dogs should not be at the dog park, and if they are they should be muzzled. Users/Mcourv

20130318 14:31:31 nbsp Elizabethdo you or do you not consistently violate the 3dog rule??? This has been a repeated complaint on this page and I think potential customers would appreciate you addressing the concern. Users/PeteB
  She already admitted to me, on my personal page (now in the 2012 archive) that she breaks the rule, and in fact, there is a photo of it on the top left of this page.   Users/CovertProfessor
   Id like to hear it from directly from her because she has adamantly denied it in the past. Users/PeteB
     Look at her comment on my page, Users/CovertProfessor/2012 Archive here. cp

20130319 07:58:28 nbsp Pete to answer your questions  PLEASE refer to my statements previously on why.  I am providing a service to my clients the fact of the matter is Toad Hollow is the only place that has a three dog rule to my knowledge. A few of the accusations made my individuals have been in off leash areas where there is no sign posted. I do go to Toad Hollow on occasion but usually bring someone with me to help supervise or meet a client at the park that meets me there on a regular basis so her dog can play with friends and continue to be socialized.  Have I broken the ruleYes .I have talked to numerous people who frequent the park on a daily basis to make sure they are ok with me being there as well as been an active member of DDOG . I get complements all the time about how focused the dogs are. If someone were to ever have a problem with a particular dog or my being there I would gladly leave no questions asked. I do not go to the park during busy hours or hours where individuals are breaking other rules during the day ie rush hr times were people just get off work. i keep my dogs engaged the entire time at the park and am watching them carefully. I have been a Davis community member for 8 years and graduated from the university. I have helped with numerous fundraisers like getting the small dog gate installed at the park and donations towards the benches provided. The regulars at the park know what timeframe  I will be bringing the dogs and i dont go everyday to the same place as i like to change up routine and go hiking with the dogs, leash walks,etc. I am upfront on the size of groups I take out during the initial meeting with my clients. I am a responsible individual and care about the well being of my business, reputation and respect individuals in my community. I am a hard worker who is dedicated and devoted to her work in every aspect.The picture that was taken at Toad hollow is my personal pic. Have a great day. Users/ElizabethBarthel
 Providing a service to my clients is not a reason to break the rules. Claiming others are OK with the practice (which does not at all line up with anybody I have talked to) does not entitle you to break the rules. Claiming youre attentive does not qualify you to break the rules. Being a community member involved in charity does not mean you can ignore the rules. Im not sure how much clearer anyone can make it. Megan

20130319 09:22:24 nbsp Hello all. I am a toad hollow regular and often meet Elizabeth there to help with her daily dog outings. i bring one dog and help out with two of her charges to keep within the 3 dog limit for her. She takes her responsibilities and peoples comments very seriously. I was also present on both occasions where a puppy was nipped by her dog.  In both cases, the puppies were behaving as normal, highenergy puppies do. Adult dogs do act in a corrective behavior when around puppies.  In these cases, the pup got nipped.  Lucky for us in Davis, there happened to be a vet at the dogpark who immediately looked at the injury and assessed it to be minor.  I havent heard what the vet clinic the owner took the dog to advised as far as treatment necessary. As a dog lover, I am thankful Elizabeth provides excercise and socialization for dogs that would otherwise be fairly confined. I agree with all postings that she follow all local laws as well as be responsible for all incidents related to her charges.  Julie S Users/juliesilva
  If there was an injury that required a vets attention (i.e., teeth breaking skin), I think thats more than a nip.  And while adult dogs do correct puppies, those corrections dont usually involve teeth entering skin.   Users/CovertProfessor

20130319 11:33:57 nbsp No stitches were required in either case, Users/ElizabethBarthel

20130319 11:55:21 nbsp The vet that checked the pup at the dogpark said it did not require a vet visit, however the dog owner always makes that decision for themselves. I do want to add that several trainers and vets that Ive worked with are opposed to taking dogs to dog parks.  I, however, have had a great experience at Toad Hollow.  There have been incidents, including my dog being bitten on her nose and myself being bitten on the hand trying to break up a scuffle.  But its been overall a positive experience for my dog and for myself. The socialization for my dog is vital and its actually a good place to continue training your dog, plenty of distractions to work with!   I encourage the puppy owner to come on back & give it another try. From my experience, its best to avoid the late afternoon crowd. It can be particularly crowded and dogs are often highenergy after being cooped up during the day.   Users/juliesilva

20130319 18:15:15 nbsp I wasnt going to weigh in until I knew that my dog would not require any followup care, but I resent Julia and Elizabeth minimizing my dogs injury by calling it a nip and replying that no stitches were required. Hunter bit my dogs face soundly enough to puncture the muzzle and knock out an adult tooth. There was a lot of blood. Yes, both dogs that Hunter bit are young, but that is immaterial. In my case there were a few dogs milling about, sniffing weewees, and NO ONE was romping. But even if they had been, thats what dogs DO at a dog park. If your dog bites anyone for it then HE is the one who shouldnt be at the dog park. I suggested as much and Elizabeths response was that she would only take him a couple times a week. Uhh, isnt that like driving drunk only some of the time?? So a couple weeks later Hunter bites another dog in the exact same manner. I think its obvious that he should be banned—PERIOD.  Users/GoldenA

Sorry you felt this waymy comments were directed at the second incident not yours. I was going to follow up with you later this week to check in with Monty. Hunter has not been to park since and I have consulted a professional regarding the situation. Users/ElizabethBarthel



Note: the following refers to the second dog bite incident from Elizabeths dog, not the first dog bite incident from Elizabeths dog where a dogs tooth was lost.

20130319 20:49:00 nbsp  I’m sorry if this may be overlong, but I’d like to comment on the incident discussed above, since I happened to be the person closest to Elizabeths dog, Hunter, when he bit the pup; I’m also the veterinarian who quickly assessed the puppy immediately after the incident, as mentioned above.

I paid a great deal of attention to the puppy that morning; shes of the same breed as my girl and just a bit younger, and it was pure pleasure to see her run to greet all of the dogs in the park, just as my dog had done when she first visited Toad Hollow. Accordingly, I watched the puppy rush excitedly up to Elizabeth’s dog, Hunter, who at that moment stood only two or three feet directly in front of me. Although, despite his health issues, Hunter generally seems like a placid, happy guy, he apparently didn’t appreciate the puppys suddenly enthusiastic supplication, so he immediately rebuked it—so I whacked him. I wasn’t concerned so much that Hunter’s instantaneous response would seriously injure the pup as that he might badly frighten her, but I took one step forward and (since I couldn’t quickly reach his collar) I hit Hunter with a ChuckIt! Launcher across his shoulders hard enough to be certain that he’d long remember it; as I recall, though, the pup had already run off in the split second before I corrected Hunter.

Of course the puppy’s owner ran over, and I accompanied her back to a bench at the north side of the park. I’d already spoken to her earlier that morning as I admired her pup, but I identified myself as a veterinarian, asked if I could take a look, and quickly assessed the puppy just as I would have examined my own dog. My impression was that the puppys understandably worried owner would appreciate a more thorough, formal assessment than I could provide at the park, and that the puppy would likely go home from an office visit with no stitches but with a course of antibiotics—and I expected that Hunter’s owner would pay for that. Within a few minutes it was clear to me that the puppy would remain a happy, welladjusted bundle of energy with no longterm effects from the incident. I hope so, but my hope is based on my own puppys uneventful recoveries from strikingly similar experiences at Toad Hollow, where, not surprisingly, dogs often behave like dogs.

Edit: I should note that last summer I left my puppy with Elizabeth for a week in which she was with Hunter most hoursexcept when she slept on the bed with Elizabeths mother. I discussed Hunters situation with Elizabeth this morning; I think that she will manage this responsibly, and I understand that she has sought some qualified help. Users/RBrianWalsh

20130416 19:23:43 nbsp Whacking a dog with a Chuckit was hardly an acceptable way of dealing with that situation if you werent actually immediately concerned for the bitten dogs safety. All you accomplish there is making BOTH dogs fearful, with the added bonus of Elizabeths dog now associating the puppy with being hit. Thats likely to make his reaction WORSE the next time, not better.

edit: I also happen to think that you should remove the preveterinarian designation in the opening sentence of this page. I feel that it is a misrepresentation.  Users/inu



20130417 20:23:42 nbsp Elizabeth has been walking my big 120lb dog for a few months now and he just LOVES her! Its such a relief to know that I can go to classes and study groups all day without feeling guilty or worried that Samson is home alone and not being exercised. Elizabeth thoroughly interviewed me about Samsons habits and behavior before beginning to walk him. He was not socialized with other dogs until late in life (hes 9 years old now) and can be skittish and unpredictable. Elizabeth listened to my concerns and does not take him to Toad Hollow. She takes him on different walks on leash instead. If I was going on a vacation I would not hesitate to trust Elizabeth with Samsons care, either at her home, or as an overnight stay at mine. Oh, and she has been very patient with constant changes in my schedule over these past weeks of the new quarter, which I am sure is frustrating to her. I recommend Elizabeth very highly. Happy dog, happy owner! Users/ShannR

20130504 18:29:40 nbsp Elizabeths inhome boarding is a uniquely great service. Kennels or even pet hotels dont come close to the level of homeawayfromhome feel.  Last year I had to work outofstate over the summer  my dog stayed with Elizabeth for 3 months (with a favorable longterm rate) and had a wonderful time.  We also frequently use inhome boarding for long weekends and holidays  never sending my dog to a kennel again! Users/YihengLi

20130627 17:37:53 nbsp Elizabeth is without a doubt the best of the best when it comes to pet sitting in Davis. Not only does she watch our birds and cats, but she knows about taking care of any medical needs and is always available to be a loyal friend and caregiver to your pets. Ive used her services for over 2 years and cannot say enough good things about her and her business. To top it off, Elizabeth is a wonderful person. She is kind, approachable, and loads of fun to be around! You simply cannot find a better pet services provider than Elizabeths PetSsitting. She is the best there is and I would recommend her to anyone needing care for cats, dogs, birds, or other animals. In a word  she is AWESOME!  Jerry V.  Users/JerryVoltura

20130806 15:40:26 nbsp I have no comment about Elizabeths business, of which I know nothing. A small red car bearing her business name followed me as I drove eastbound on Lillard Drive just before 3:00PM this afternoon, though, and I do have a comment about the driver of that car.

There is a flashing speed sign close to the western end of the street and the sign indicated that I was going 25, the posted speed limit. The red car bearing her business name followed me too close for comfortI couldnt see her front bumper in my rearview mirroruntil she touched her brakes at the stop sign at Danbury Street and made a right turn before I had finished coming to a full stop myself at the same stop sign before proceeding eastward.

These are, of course, my own observations and subject to contradiction by the driver of the little red car. It goes without saying, however, that any attempt at contradiction will be informed by selfinterest. I will repeat, however, that the posted speed limit was 25, the car following me gave indications that the driver was impatient with my speed by following more closely than necessary, and I had not fully stopped when the little red car proceeded southbound on Danbury Street after barely paying its respect to the stop sign.

As someone who drives a vehicle with signs on it and who employs people who drive similar vehicles, I am sensitive to the issue here. People can easily forget a speeding blue Honda, say, but a car marked Elizabeths Pet Sitting is memorable and not particularly good advertising. Users/DavidRobinson

20131019 23:11:09 nbsp I hired Elizabeth to petsit for me based on the reviews I saw here and on Yelp, but unfortunately, she did not live up to my expectations. In fact, this was the worst petsitting experience I have ever had. When I initially met her, she seemed thorough, writing down all my instructions since my dogs have medical conditions, and she assured me that she would take great care of them. However, while I was out of town for work, one of my dogs became very ill and needed to go to the hospital right away. However, Elizabeth said that she couldnt take her to the hospital until the evening because of her other petsitting obligations. In my opinion, other dog walks can wait when there is an emergency, just as I would expect my dogs to have to wait if another of her clients was having an emergency. I ended up calling all over town to find another petsitter willing to take my dog to the hospital. When I returned from my trip, I learned that my dog had been doing poorly for days, and she was nearly dead by the time the other petsitter got her to the vet. $1800 later, my dog is still alive, but in my opinion, Elizabeth neglected her responsibility as my petsitter in an emergency circumstance. In addition, I learned after I got home that my cat was missing, and she couldnt tell me with any certainty when was the last time she saw him. According to my neighbors, my cat has been missing since Sep 22, and at the time of this posting, he is still missing. In addition to these 2 horrible situations, when I came home, my house looked like it had been hit by a tornado  it was filthy and I even found one of my large dogs pain pills on the couch. I dont want to think about what would have happened if my small dog had eaten it. Perhaps if you have only one animal to care for and it is in perfect physical and emotional health, Elizabeth could be a good petsitter for you, but personally, I wouldnt trust her if she were the last petsitter on Earth.  Users/PaulaRivadeneira

20131021 00:15:58 nbsp Im going to respond to Paulas comment because I have never been treated with such disrespect from a client upon returning home to the point of leaving in tears. I first  want to say that I did everything to the best of my ability. I am going to explain the situation from a pet sitters perspective . I was hired to care for a household of a several indoor/outdoor cats , a tortoise, and 6 dogs all of which were on pills (2x/day) and 2 were diabetic. I closely monitored  one of the diabetic dogs blood glucose numbers and made sure the dog ate and was ok at every visit. I went shopping for roasted chicken, liver wurst , and Vienna sausages. I have a background in Animal Science and have interned in several vet clinics and shelters so was aware of the responsibility of taking care of a diabetic animal. I was in constant contact with the client at all times several times a day thru text and phone conversations of the dogs situation. The dogs specialist was in Sacramento 35 minutes outside Davis . I alerted the client the moment the dog stopped eating and suggested an in home mobile vet be called or the dog be taken to the UCD Vet school but the client refused any service other than the vet in Sacramento . The next morning the dog really needed to see a vet I had offered the night before to drive the dog . It literally was an overnight decrease in health not days . The dog ended up being diagnosed with Ketosis. I had been visiting the household 3x/day plus doing a sleep over at the home. I had been awaiting a response from the client the next day about how to proceed. The vet wanted to see the dog immediately. I have dealt with several pet emergencies in my 9 years of petsitting and have always been able to respond to an emergency ASAP . This past Christmas I spent 6 hrs in the emergency rm with a dog in liver failure. I know how time consuming emergencies can be. In addition to transport , there is the waiting time and final tests and diagnosis. The client called me and asked if I could make an appointment in Sacramento around 2pm. I had to make a professional decision and be honest with the client that since she had an out of area veterinarian I would not be able to transport the dog at the specified time and she should try to find an alternative travel arrangement until I could be with the dog and give my undivided attention. Never in the history of my company have I had to do that but I did have other medical related animals I was caring for that could not be ignited even though I had cancelled my dog walks in anticipation for a worst case scenario that I could not take the dog to an out of town veterinarian at the time requested. I did have to meet the hired transport to unlock the front door.
Now to address the missing cat and condition of the house. Moki and all the other cats were INDOOR/OUTDOOR cats and had access to the outside thru a dog door. As a pet sitter I cannot guarantee the safety of a cat that has access to the outdoors. I told the client I had last seen the cat 2 days before the rain storm we had over the weekend.
Now the interesting part of the story the return of the key to the client
I completed the job and upon their return received a phone call from the client that Moki had not come home yet. I kept up to date on the status of Chollas progress and addressed by phone any concerns or complaints I received . I vacuumed the home upon leaving , washed the bedding, and even washed the rugs and dog beds since it had rained. The client complained that her kitchen floor was full of dirt . It had rained and the dogs just like the cats have access to the outside. Upon washing the rugs I hung them up on the fence to dry .
About a week went by and I was owed some money for my shopping trip and the for the special needs dog and the client wanted me to return her key . She owed me for an extra visit I did when the flight got delayed. She said she would be deducting the cost of transport fees she had to pay from what she owed me . I agreed to this arrangement.
We arranged a time that worked well for her and I proceeded to return the key . The situation turned from a couple of complaints to an ambush by Paula and her husband. They verbally insulted me , refused to pay for any extra visits and the food bought for their dog. They threatened to call the police if I didnt leave the property. About half of the meeting was Paulas husband yelling at me and trying to intimidate me. He wanted copies of the paperwork his wife signed. I told him he was making me feel very uncomfortable and we needed to be professional and talk about any concerns he or jus wife had. I handled myself in a professional manner and kept calm as I was insulted and accused of not providing the highest standard of care for their household. The pill found on the couch was never mentioned in my phone conversations , text messages, or prior to the meeting. I had been pilling the animals 2x/day for over a week and never had a problem. I continually apologized and just kept getting verbal abuse and threats that I would be sued . They said I must of done something wrong to have a diabetic dog go into a Ketotic state and accused me of Moki s disappearance saying I must be hiding the truth of when he went missing . After about 30 minutes I shook both of their hands, and left . I felt bad about the lost cat  and did everything to help even though I was upset by the way I was just treated. I have never felt so intimidated and degraded by a client in my entire professional career. I hope Moki returns and will miss caring for the animals but I learned some important lessons from this situation.
Thanks for everyones continued support and loyalty and rest assured I will ALWAYS provide the highest care and responsibility to anyones pet in any situation.
Elizabeth Barthel
  Users/ElizabethBarthel

20131221 11:20:14 nbsp Our family has been relying on Elizabeth for highquality petsitting care ever since our dog was a puppy.  Elizabeth has been an amazing dogsitter and were always relieved that we can board our dog with her when were away.  She has a fantastic rapport with dogs, takes excellent care of them, and goes the extra mile for us, providing gratis services such as toenailtrimming and scheduling grooming appointments for us.  We dont know what wed do with out her.  Elizabeth is fantastic. Users/AdamSiegel

20140303 16:12:48 nbsp Elizabeth has been helping me take care of my energetic pit bull puppy for almost a year now. I feel very comfortable leaving my dog with her and never worry about his safety when he is with her. Although he is very strong and can be difficult to handle, Elizabeth is calm and confident with him. It is also nice knowing that she has insurance should anything happen. I would definitely recommend Elizabeth to anyone with petsitting or dogwalking needs :) Users/KFReed

20140306 12:31:17 nbsp Elizabeth Barthel has been a fantastic dogsitter for me.  She has done so much for me and my dogs.  She has taken my dogs to the groomers’.  She’s taken them for short walks and long adventures.  She has stayed overnight at my house and has had the dogs at her house.  My dogs are sometimes difficult.  One is shy; the other super friendly.  Elizabeth is great with both of them.  I know that my dogs will have a good time with Elizabeth.  They are always happy when I return from trips.  Elizabeth Barthel is trustworthy, dependable, and great with animals.  I recommend her highly as a dog sitter. Users/SallieHejl

20140330 10:29:25 nbsp Elizabeth was a great sitter for our cat!

My cat is not particularly difficult, but he is prone to separation anxiety. Elizabeth did a good job caring for him. There was a bit of a hiccup in which I could not find the key that she hid in my potted plants, and she was very nice and patiently stayed on the phone with me while I looked.

The only word of caution is that cats with no exposure to dogs may find it difficult at her home. I was only there from outside, but when I knocked on her door, several dogs began to bark and it gave my cat an anxiety attack (which is why we ultimately decided to just have in home care instead).

Overall, a good experience. Users/eyun

20140404 19:25:38 nbsp Elizabeth has been caring for our dogs for 2 years when we leave town
Reliable
Trustworthy
True to her word
She provides timely pickup at our home
She provides timely drop off at our home
She is generous, honest
Simply a great resource

 Users/KJelks

20140523 12:08:51 nbsp Sadly, Elizabeth chooses to ignore pretty much ALL the park rules at Toad Hollow Dog Park.  I would not entrust my pet to someone who deems themselves to be above the rules,
She transports numbers of dogs to the park  all crammed into her car without restraints, doesnt keep their leashes with her and misses many poops as she strolls the park
Perimeter chatting away.  Park users comments to her are to no avail.  I wouldnt leave my dog with someone who promotes ill will. Users/Pamhelm

20140523 13:48:07 nbsp Very proud to be featured in the Davis Enterprise
http://www.davisenterprise.com/localnews/whyhireapetsitter/ Users/ElizabethBarthel

20140527 09:23:27 nbsp Pam I am sorry you had a bad day at the park.  My experience with Elizabeth has been positive, she really appreciates it when people come up to her to discuss their concerns in person.  I am a regular at the toad hollow dog park and have witnessed many scuffles, very few involving any of Elizabeths pack.  I am a big dog lover and so appreciate having someone in our community like Elizabeth that gives dogs the opportunity to exercise and socialize. For some dogs this is their only time to play as they are kept kenneled. I would suggest that you give her another chance and talk to her directly.
 Users/juliesilva

20140611 16:46:35 nbsp Elizabeth is awesome.  Our needy minpin needs lots of love and attention and socialization with other dogs and she has provided that and more.  I highly recommend Elizabeths Pet Sitting. Users/KMartinez
