

European Wax Center is a franchise waxing salon that does a wide variety of body and face waxing services for women and men. The women at the front desk love to try to lure you in with different packages, memberships, and promotions that EWC has to offer, but they can actually be worth it for frequent waxers. Your first wax at EWC is either free or very cheap, depending on the service you select. They also sell a line of products including exfoliating body wash, lotion, and ingrown hair serum.

  To learn about other businesses in Davis that provide professional aesthetic services, visit our Beauty Salons and Barber Shops page.



20090918 10:48:45 nbsp I was excited to see this place come in initially, but their customer service is terribly fake. I have no intention of returning. Users/RandiF

20090919 15:08:17 nbsp box waxing? Users/StevenDaubert

20091003 11:11:44 nbsp these ladies were great! yes, their customer service isnt what you would get at a full salon, but you arent paying for that. these ladies know what they are doing, and are good at it. they are welcoming and talk to you while you wait (whereas at some places you would be ignored until you are called). they use hard wax, rather than strip wax, which means that the pain is minimal, and there is very little chance of getting your skin pulled or ripped. i just got my brazillian done and it didnt hurt at all  at least compared to the strip wax that i am used to. they are offering great discounts because they just opened, and they have packages that you can buy that can save you some serious money. i am definitely going to go back every month. Users/Millie

20091003 17:33:15 nbsp
European Wax Center is like a gym  they encourage people to get memberships.  Overall, price wise, the memberships appear to be reasonable, but expect a hard sell on the memberships if you go in.   A friend and I went there and she liked it, but I didnt care for it.   While the atmosphere was great, it was probably one of the worst waxes Ive had in a long time.  They recommend you coming back every 4 weeks and I can understand why    eyebrows look terrible within 2 weeks.  Ill stick to New Fashion Salon in the U mall.  They may not be as spalike on the inside, but they do a good job and my brows look great for up to 6 weeks after getting waxed at New Fashion.
  Users/RohiniJasavala

20091006 11:36:59 nbsp There wax is definitely less painful than other waxes I have tried. My first experience getting a brazilian here was very pain free, but I was a little annoyed the esthetician  didnt go over and pull out the hairs the wax did not remove with tweezers there were definitely some major hairs that should have been removed. It was also strange that they dont leave the room to let you get undressed/dressed before and after. The second time was a better experience. The estheticians were very nice and made me feel comfortable. What is really annoying is that the people in the front are always trying to sell you their memberships. The nose waxing they do is awesome and does not hurt at all, it just feels like pressure. More men should get their noses waxed! Overall, I would recommend them! Users/Ldish949

20091018 17:04:29 nbsp The lady here did a great job waxing my eyebrows. She did exactly what I wanted and was very professional. The place itself is very clean and relatively new. Nobody bothered me about buying a membership, and even if they did its as easy as just saying No thank you so its no reason to avoid the place. The price was very reasonable. For how fancy the place was I would have expected to be charged more. My first wax was free and they gave me a $5 off my next service! If anything, you might as well try it out once and get the free wax! Users/Sarah1988

20091117 14:52:05 nbsp I liked the women at European Wax Center and the waxing was top notch. Both receptionists were very nice, real, and friendly. My esthetician, Sabrina was awesome. Her touch was as pain free as waxing can get and she was very easy going and made me feel completely comfortable. Dont let the glossy franchise fool you, the women working there are in fact very real and make it a nice experience. Users/kettle

20091124 11:51:05 nbsp Heather is the bomb. Go to her for your Brazillians or Bikini waxing!  Users/Ldish949

20091129 11:20:57 nbsp I just got a brazilian the other day and it was the best waxing job Ive had in a long time. I only paid $12 for the waxing as a first timer promo. There was very little pain (only when she flicked up some of the wax to get a hold), no irritation, and the redness went away really fast. By the way, if youve never gotten a dry wax done, one nice advantage is you dont have to worry about having sticky wax leftover on your body from sloppy waxing/cleaning. It was a little odd that the esthetician didnt leave the room while I undressed, but youre showing them all your junk anyways so I didnt think it was that big of a deal. She at least turned the other way and shes being efficient. Everything looks clean, and I actually really appreciated that the esthetician cleaned the table while I was in the room getting dressed.

I got the Super Pass membership which is $28 a month for a brazilian, and if you get waxed regularly I think its worth it. Most places Ive been to will only give you a wax under $40 if youve gone multiple times. The receptionist said something like as long as you try to go every 34 weeks, they wont screw you over or something? I dont remember. Anyways to cancel the membership all you need to do is give them written notice 30 days in advance. I dont think the super pass membership is advertised on the website, so if you go to the website and look at the deals, dont be fooled by the club 30 pass, which is really designed for people who wax every hair off their bodies. Definitely talk to them in person about what deal will be best for you if you decide to stay with them. Users/ymdean

20091213 14:13:15 nbsp I would recommend this place to my friends without hesitation. Ok, its not Bliss Spa, but they are efficient and very affordable at $28 a month for a thorough box waxing.  Went today for the first time and got my membership. For a brazilian and brow wax I was in and out in about 35 minutes and she did tweeze strayspretty remarkable.  With the inital brow wax being free and my membership it was $28 for all that. Impressive! Also a huge fan of the dry waxing  much less painful, I dont know why more places dont use this kind of wax. It also doesnt pull up your skin like the wax they use strips on, only the hairs.  Users/soledad101

20091217 22:56:00 nbsp This place does a good job for the price that you pay. My membership is under $25 a month, cant really beat that price anywhere that I know of for the quality of service you get here. Like salons of any other type, your experience will depend on the people you get. Some of the people at the counter here are fake and can come off as pretty rude, but other people are really friendly and helpful. I have had several of their estheticians and some are better, quicker, cleaner than others. Its a dice you have to roll unless you want to go somewhere with one esthetician like A Plus Image. Sure its a franchise (and looks/feels like one) but this place is much cheaper and does a better job than Smooth As Silk, and they use hard wax instead of the more painful soft wax. They also sell products that are expensive but worth the money because they work, especially the serum that Id recommend to anyone whether or not you wax here. Users/SRB

20100207 21:41:01 nbsp Traumatic! That was my experience.  I got a brazilian and full leg wax from Sabrina.

The brazilian was horrible! When she tried to take the wax off, she had a really hard time, so what with more skilled waxers is a quick rip, from her was a series of five yanks. It was much more painful and scary this way. Every time she went to remove the wax, I was so scared of how it was going to go that I was actually shaking. Then, each time, she would say in a cold, cold voice, take a minute.  In the end, I told her to just stop, and actually walked out with a chunk of wax stuck to my hair (that was fun to deal with later) because I had had enough and was scared of more pain.

After that, I did have her finish my legs  I was there anyways, and wanted to get the job done. She was sharp in her demeanor with me, and never apologetic for her terrorizing me with the brazilian.

The leg job was ok, but I was surprised because the hard wax I have used in the past is completely thorough. This stuff they call hard wax is not, so she had to run over each strip at least three times to get everything. And, of course, in the end didnt. But that, at least, is normal. However, she didnt get all of the wax off so I left with all of these dark blue blotches on my legs, and had to deal with it all when I got home.

Brazilians are for professionals, which Sabrina in my experience is not. Not in her waxing technique or her people skills. Ladies  dont do it to yourselves  steer clear!!! Users/SpringRose

20100308 14:07:42 nbsp I have absolutely no idea what the last person who commented is talking about. I just went to european wax center and had the BEST experience ever.
And I cant believe I almost let the last comment stop me from going.
Ive been getting brazilian waxes for almost 4 years now. Never before have I done hard wax. So granted I was a little nervous. The front staff was super friendly and reassuring and my esthetician Maricela (i hope i spelled her name correctly) was WONDERFUL! I will never get waxed anywhere else again.
The prices are ridiculously affordable. This was another reason I hesitated, I figured for that cheap they cant be that good. But Im glad I at least tried it.
Usually after the the hot wax with the strip, Im red and swollen and sticky! I know it depends on everyones pain tolerance and maybe Im more used to pain since Ive been getting waxed for 4 years, so getting waxed today did hurt but barely anything compared to what Im used to. And lets remember they are ripping hair out of your body so it has to hurt a little. Plus I wasnt left sticky, I wasnt swollen or hurting afterwards. It was great.
Id definitely recommend at least trying it out. They do give you 1/2 off if its your first try which also helped me take that risk of going there. I dont usually leave comments because I never think its worth it but this place is worth it, especially because I read that last comment before going there and I think she was wrong and unfair.
 Users/Aarti

20100518 12:56:15 nbsp This was my very first Brazilian wax EVER! and Sabrina made the entire experience very comfortable. She understood I was nervous and was very friendly and helpful. I 100% recommend this place. I am officially a loyal customer. Users/HoneyB

20100519 19:57:39 nbsp I decided to try this place for a free bikini line wax. The ladies were very professional and very friendly. Jessica was the receptionist and Melissa did the waxing. It was painless and the facility was very clean. The wax they use did not stick to the skin, they made sure to get any strays hairs not removed with waxing. Not pressured to buy a membership.  Users/ElizabethBarthel

20100529 09:54:44 nbsp The staff was friendly and nice; however, the job performed was lacking. I received an eye brow waxing which I had to get redone a week later because my shape was not right and there was a significant amount of growth in a week where as normally I am good for 4 weeks. They also use hard wax which is a body wax and is not recommended  for the face and I had a severe reaction. Ill stick with Benefit in Arden from now on. So much for getting a quick brow wax on a Friday when I am pressed for time.  Users/dimes

20100714 10:55:14 nbsp I just had a full leg wax and this was my first time with the hard wax method. I have been waxing since I was about 10 years old and this was way less painful then the hot wax method. I am middle eastern and have coarse thick leg hair and it worked great for me. No broken or missed hairs. I found the service professional and efficient. I was never asked or told about any membership deals. I was especially pleased at how easily they handled the fact that I am pregnant and therefore unable to lay easily on my back or stomach, Melissa was very accommodating and worked with me to find workable positions to make sure we got every spot on my legs. I am definitely going back. Users/Zeeba

20100727 11:51:11 nbsp I have been here several times, and have never had a bad experience. All of the girls are good but Maricela is great. She explains what she does before she does it so there are no surprises, then gets every hair you want off, and makes it so painless. Very friendly and would recommend.  Users/ChardeIrby

20100814 13:37:24 nbsp I used the Green Machine coupon to get a free bikini wax and it was okay. The women at the front desk seemed annoyed that I wasnt a fully paying customer. The wax was pretty good though also really quick. I realized later in the day that she had removed the very top layer of my skin on one side, which I dont often have happen with waxing. Its not terribly expensive, so I guess you get what you pay for. Users/Ratatat

20100826 12:56:47 nbsp INSIDE the WAXING ROOM:
I highly recommend Maricela for Bikini Waxing. It was my first time getting a bikini wax ever and she was especially friendly and good at calming my nerves. She explained everything about the procedure and left no surprises, which I really appreciated. She also explained to me afterwards how to properly take care of my newly bare skin. I cant believe how relatively painless my first Brazilian wax was! I would definitely come back for Maricela to do other waxing services for me. In terms of service in the waxing room, you get better than you pay for.

I have also had Rachel do a Full Bikini Wax for me. She is very pleasant to talk to and easy to be around, but I felt like she rushed me. She tried removing the wax before it had set in (to the point where I could see the wax still sticking to her wooden stick). I was a bit surprised my Brazilian Bikini Wax was LESS painful than this Full Bikini Wax (which removes less hair than the Brazilian). In addition to that, Rachel didnt do a thorough job removing all the leftover wax so I felt as if my butt was glued together for awhile.  Users/MooMoo28

20100826 12:58:14 nbsp OUTSIDE the WAXING ROOM:
If you want any kind of discount that you are PROMISED as a customer (see their website), COME ALREADY KNOWING about it. They did not tell me about the free wax for first time customers and I felt pretty cheated.

Also, dont expect any sophistication or courtesy from the receptionist. The receptionist I spoke to on the phone, Jackie, knew very little about her own companys online system, didnt even input my information correctly over the phone, and then just kept making excuses about the underdeveloped online booking system, unimplemented platinum rewards system, her computer that keeps freaking out, and the malfunctioning phones at the front desk. (These are just a few of the excuses I can remember off the top of my head.)

Even worse, my friends were in the lobby when I was on the phone and they told me that Jackie had the audacity to talk smack about me to another employee after we hung up! Heres what I found even more suspicious. I tried booking an appointment online but it didnt work, so I called back Jackie and she told me she made my appointment for me around 11 (and sure enough, I checked my account online and it said my appointment was at 11:15am). But when I went in for my appointment, it turns out Jackie had made my appointment for 10:45am. I dont know how my appointment could have changed when I had not touched my account since I made the appointment and Jackie told me specifically over the phone that she had made it for 11, but the kind of service and competence from Jackie the receptionist speaks for itself.

On top of that, the manager, Jessica, in front of my friends approved of the way Jackie handled me as the customer but told me during my appointment that her behavior was inappropriate. Its no wonder the customer service does not improve if the manager does nothing to change it.

If asking questions about promotions that are BLATANTLY advertised on European Wax Centers website is such a crime, and if the manager herself is vague about standards of customer service, I cant say much else about their customer service outside of the waxing room other than their rudeness is uncalled for.  Users/MooMoo28

20101026 11:00:53 nbsp Awful.  Car got towed from the parking spaces behind the building during my wax  my fault, I just didnt see the signs saying they were private.  Asked the receptonist to have the owner contact me, as the cost ($225) to retrieve my car was outrageous and I thought they should know that the firm theyve hired is charging outrageous fees.  She promised a call........never got one.

The wax job was soso.

The membership vibe rubs me the wrong way.  Really cheesey, in my opinion.

SPA CENTRAL is far superior.  Less cheese, more chill.  So, thats my take. Users/browneyedblues

20101211 16:26:37 nbsp I have been here on two different occasions and was fully satisfied both times!
I went to Sabrina the first time for a full bikini and lower leg wax. She was professional and did a good job. But during my second visit I went to Rachel who was easier to talk to and faster/more thorough.  The rooms are clean and the staff is professional and cordial. The free wax special is great and affordable.
I highly recommend this place and will be going back! Users/Tier

20101216 12:50:34 nbsp I just found out that Natalia is no longer working here due to poor ergonomics. I was really disappointed. I bought multiuse passes here after a wonderful experience with her, and now I definitely feel stuck. When I went in yesterday for my appointment, they had moved my 6:15 with Natalia to a 6:30 with Maricela and didnt tell me. It took Maricela much longer than Natalia and the work was, in my opinion, subpar. On the lower legs: When I left, my legs were red, swollen and stinging for over an hour. She left stray hairs all over the place, and this morning I noticed tons of stubble  it looks like many of the hairs were broken off instead of removed. Some areas on my legs are still pink and sore now, 18 hours later. Underarms: Overall not too bad, though I found lots of stray hairs this morning. Without Natalia, this place definitely is not the same!! Users/MeganCleary

20110129 14:14:41 nbsp I went in recently to get my eyebrows waxed and will never know how good the quality of work here is. The reason being very bad customer service. Probably the worst customer service experience Ive ever had. I didnt have an appointment but saw a sign saying that walkins were welcome so I decided to drop by in the early afternoon. Upon walking in, I saw the receptionist and another employee at the front counter. Neither of them greeted me when I walked in. I walked up to the front counter and stood there for about a minute before being addressed by the receptionist. Her first words to me were Hold on one sec, with her finger raised at me and not even looking in my direction. After she finished talking to her coworker about things that Im pretty sure were not related to work, she finally asked me what I needed. I told her I wanted an eyebrow wax and she told me she only had an opening at 1:45 but I was not able to make it because I had work at 2. When I told her this, she told me to come back after work since they do not close until 8. I agreed to this and mentioned that I would not be done from work until 6:30, at which point she told me that her only available appointment that evening would be 5:45. Why would she tell me that I could come back after work because theyre open til 8, yet tell me that she only had one opening at 5:45?? I told her that I would not be able to make it at that time and she commented that they were open the next day so maybe I should try then. I walked out and will never be going back. I cant say that this business does poor quality work because I was not able to experience it, but with that kind of customer service I dont think I would want to anyways. Users/HeartAlong

20110315 20:15:28 nbsp I went to Maricela today, and it was AMAZING. I have never posted anything on Daviswiki, but this was enough to make me create an account and write a comment. I read through these reviews and there was a lot of mixed emotion about this place, so I was really hesitant to try it. But my friend recommended Maricela, and I trusted her, so I went, and it was so great. I got a brazillian, and she was fast, painless, professional, and she made me feel very comfortable. This was the best waxing Ive EVER had. I recommend her a million times. I dont know about the other ladies, but Maricela was so good. Ask for her! And for $19.50 for my first time there, it was even better. I HIGHLY RECOMMEND MARICELA!! Users/TAT

20110411 18:51:23 nbsp I had a bad experience here.  The girl who waxed me was obviously new, and it was more painful than necessary, as well as awkward because she wouldnt talk to me.  I highly recommend Smooth As Silk on D street, shes great. Users/WhitneyMarie

20110606 06:54:41 nbsp The receptionists are kind of rude.. but Ive had Melissa and Maricela for Brazilian waxes and they are great! Users/Lisaaa

20111002 12:45:34 nbsp Have been coming here for 2 years. Have never had a problem with the receptionists. They used to keep promoting the membership, but they stopped after a while. They started promoting their products more instead. You can simply turn them down nicely with a no, thank you and they leave you alone. I dont understand why so many people complain about this. Ive met most of the waxers, and theyve all done a good job. Usually get a brazilian but i did my eyebrows once (which turned out great btw). Only had 1 notsogood brazilian out of the many times ive been here (shed waxed me before and after with no problem, so it was probably just a fluke or a bad day). From what Ive sen there so far, I believe most of their customers are satisfied with their services but just dont write about it here, so people just see the complaints. Their facilities are clean, you get a private room, and the waxing process is not nearly as painful as regular waxing. Dont know what kind of wax it is, but I like it. Users/vk

20111005 13:28:11 nbsp This place is the bomb dot com. I dont understand why anyone would talk negatively about Sabrina. Ive been going to her since they opened and she is by far the most professional person they have there. Youre not there to fall in love, just to get a job done, and thats reflected in the price. Deal! Users/YesItsMe

The ladies here are always super professional and offer wonderful customer service. I came in a few months ago with a free eyebrow wax coupon and the lady who assisted me did a fantastic job. I came back last week to get my eyebrows done again and was impressed. She did them exactly as I asked. The place is very clean and the wax is great less painful than other types that I have tried. I highly recommend it to both men and women.

20120320 14:02:11 nbsp I had a great experience. Front desk staff was friendly, I didnt have to wait, and my wax came out perfect. I had Rachel for Brazilian and I will be back. It was the least painful Brazilian I have had and she got everything without needing to pluck strays. She was also really nice about accommodating me since I am quite pregnant.  Users/Kristin

20120403 10:35:35 nbsp My experience here was great. When it comes to getting my hairs pulled out en masse, Im just not the stoic badass I wish I was; but Jasmin took her time, explained every step, gave me as many breathers as I needed, and still managed to do a thorough and fantastic job. She was patient and personable and responsive.

I went to my appointment a bit defensively, since the other reviewers talk about being barraged with sales pitches for subscriptions or packages. But absolutely nobody pressured me to buy a package or subscription. Nor was I pressured about products. And my firsttime customer discount was added immediately. My appointment was low stress, the results are great, and Ill go back.  Users/spulford

20120511 19:40:13 nbsp Got my first brazilian here!  ANGEL was wonderful, super friendly and communicative about what she was doing. Really knows how to take care of her clients! Users/kg18

20120613 18:30:42 nbsp Today I had a second bad experience with this business. The last time I went I was left with little burn marks on my upper lip. Today, a whole layer of skin on my eyebrow was ripped off and has left me with a large, painful burn. Some of the more established waxers seem to get a lot of raves on here, but be very careful if you get placed with one of the newer girls. Users/ASeward

20120701 17:20:37 nbsp I keep meaning to leave a comment here but always forget to. Of course, the allure of being hairfree down there is what drew me to come to this place  and also, because my friend who was a regular until she moved to Colorado told me that I absolutely must try getting a Brazilian wax. So I did. And it was awesome.

I had Sabrina and shes super easy to talk to. My first time, I was really nervous, and she catered to me and took the whole process slow and was very gentle. After that, I didnt go for a few months due to laziness, but I ended up going back and have been going every month since. ) Its even better that shes a Firefly fan! We get along swell, and shes good at her job. It gets easier and easier the more you go in, too, so if you do plan on getting a Brazilian, try to keep it up! Itll only make it more comfortable for you in the long run.

About the complaints...she traumatized you with a Brazilian? What? Im pretty sure getting waxed is a voluntary procedure...

Also, my friend saw Angel for the first time last month and absolutely loved her as well! Users/HannahFolkes

20121230 21:37:03 nbsp This place is amazing. The front desk staff is amazing and every waxer I have had has been great. I do find it super annoying that their prices are not listed online so I brought home a brochure and this is what I found: Eyebrow 16$, Lip 9$, Bikini Line 28$, Bikini Full 35$, Brazilian 42$, Lower Leg 32$, Full Leg 60$... and they have a great deal for your first time! Free Eyebrow or 50% off Bikini! I go back every month and I even got one of their wax passes! All I had to do was bring my Student ID and I got 4 services for the price of 3! Definitely worth every penny.  Users/AlexLN

20130213 15:19:55 nbsp Im European and the place or the products dont have the European touch at all, except for the name.
Price: reasonable.
What has me go hmm...: Forget having a SPA experience. This is not a SPA. It is a CENTER, and it feels like a factory and a clinic, which seems to be the definition by which Wikipedia also goes by. Dont be late or your appointment is canceled. Depending on time at which you show up, the reception is understaffed, the phone rings all the time and the receptionist (one at that time) is obviously overwhelmed. Fast speech. Out as soon as youre in, which is great cause you dont waste time if thats what youre into. Didnt find the music and surroundings relaxing, but this is a matter of personal taste. Users/DavisSite

20130611 19:17:02 nbsp Alexa and Lindsay are wonderful. So friendly and very gentle.  Users/AmandaC
