



(Not so) FAQs

  Why do you sometimes make lots of tiny edits on a single entry, seconds apart?
     When Im doing massive reformatting or rewrites about something Im confident about, Ill make them in one big chunk.  When Im editing a controversial entry or something with finely grained points, I will make them sequentially as small edits, adding a comment about each.  That allows somebody to go back through each edit individually.  It makes it harder to hide an minor edit inside a major edit... and if its controversial or has many specific facets, it should be as open and fully disclosed as possible.  Basically, Im allowing people to dispute a specific part of the edit without feeling like they have to revert all the parts of the edit.  You can see each specific edit laid out, commented upon, in the history.  Ill also add comments for the reason behind the edit, strike out text and then follow it with an edit that deletes the comment and stuck out text.  Atomic editing.
 (and because Im trying to increase my edit count Users/BrentLaabs bl)
 (hey, if I wanted that, Id do it every time rather than once every several months.  Besides, I have little problem making a half dozen edits on different entries every morning, and that satisfies my Ive done something for the wiki itch. Users/JabberWokky jw)

  Its midnight and you havent changed the wiki logo back from (or to) the holiday logo.
     Yup.  Look for them to be changed between 3am and 4am.  Note that they might show up longer on your computer until you refresh.  Although Ive forgotten at least once (Bike to Work day just kind of fit).

  How do you follow all the changes?  Even on other wikis?
     Wiki Spot has a ton of really nice tools.  Figuring out how to use them is easy, and they tend to adapt well.  I hit the wiki:wikispot:Interwiki Recent Changes at least once a day.  If I am spinning through them just checking, I can usually handle a whole days worth of changes across Wiki Spot in about 45 minutes.  Usually I zip through at the beginning and end of the day and then hit the RC randomly throughout the work day.  When Im really busy, the wiki drops out of my life... I like it and all, but family and work come first.  Usually it can get squeezed in.  I open each change in a new tab (I use http://konqueror.org/ Konqueror, coming soon to Mac and Windows), usually in blocks of about a dozen, and then read through them all.  I bookmark ones that need heavy work (phone calls, research, etc) for when I have time.

  Why do you welcome people to the wiki?
     I try to do it for peoples first edits.  That way they feel there is somebody on the other end who noticed and appreciated their contribution.  This has absolutely nothing to do with the wiki; if somebody shows up at any of the hobby or volunteer groups Im involved in, I walk up to the new people, shake their hands and welcome them to the group.  Everybody who steps into a new group of people does so with some amount of trepidation and uncertainty, and its just the polite thing to do to welcome them.  I encourage everybody active on the wiki to do the same: encouraging people to use the wiki should not end when they sign up.

  Why do you say entry sometimes and page other times?
     Its actually logical, believe it or not.  Its also subtle enough so it doesnt matter at all, but for those following along with the home game, heres the terminology I use:  The entry is the actual part of the wiki the editors edit.  You edit an entry, which is the content of the box when youre editing, and the content when you save it.  The page is the entry plus the rest of the visible items: the tabs, the wiki logo, the Copyrights and Donate links at the bottom of the page and your account information in the upper right hand corner of the page.  On the other hand, in the upper right hand corner of the entry there might be a photo of a puppy.  It really doesnt matter much in communication, but Ive found that defining precise terms is a handy way to help frame your thoughts.

  Why do you give people your phone number (or email)?
     There are two reasons: first, learning to communicate on the wiki is tricky, and sometimes people assume too much of a new editor, either by assuming that they get the wiki, or that they are able to respond.  (Every so often I get emails from people who were left messages at their user entry that they clearly did not get).  The second reason is that there are people who are just poor communicators in a written forum, especially when it comes to tone, something that tends to get worse when everybody starts getting frustrated.  Being able to hear a persons emotional affect is quite important to actual communication.  I will tell you that after years of leaving my number all over the place, I have never gotten anything but constructive calls from people who were either upbeat or were frustrated and scared, but quite grateful for my reaching out to them and honestly looking for help.  Ive placed a couple calls to some angry people, but all my inbound calls have been positive in nature.  I have a feeling that if somebody actually wants real resolution and answers, they will call, and if they are just angry jackasses playing a game, they dont want to escalate it past the internet  where they feel powerful  into the real world full of actual people.  The first thing I always explain is that I am a volunteer editor, just like they are, and I have no special control over content, just lots of experience with what tends to work and what doesnt.  If youre in a situation where you can receive calls and talk for a few minutes with somebody, you can do the same thing, too.  Were all volunteers here.

    Yes, I agree phone calls are off the wiki, and that attribute of them carries some problems.  If anybody has a way to do outreach in a better manner, Im happy to use their idea.  Im just making the best attempt I can with every tool I have.  I do try to accurately and publicly summarize any conversations I have, and Im hoping that the fact that the other party can correct me if Im wrong means that its a method for fostering communication for those who are having trouble with the wiki format, rather than a way of hiding communication.

  I always try to use a tone and word usage appropriate to the person Im writing to.  Its neither pandering nor being condescending... I try to communicate as best I can.  Its the same thing as using different terms at a formal setting (office, funeral) versus a casual setting (picnic, orgy).  People view the wiki in radically different ways and have wildly varying background and perceptions of the written word.  To some, its a casual, lighthearted who cares setting, while others see it as a cooperative project no different than a barnraising, everybody working as teammates.


