

This community bank was awarded the most recent Bill Streng Business of the Year award by the Davis Chamber of Commerce.  First Northern Bank was also voted Best Bank in Yolo County by the readers of the Davis Enterprise three years in a row.

First Northern Bank was established in Dixon in 1910 as Northern Solano Bank. It changed its name to First Northern Bank of Dixon in 1980. The of Dixon was dropped in the 1990s to reflect its widening presence in the Solano/Yolo/Sacramento/Placer region. The Bank has 11 full service branches located in Dixon, Winters, wiki:Sacramento:Downtown Downtown Sacramento, wiki:Sacramento:Roseville, wiki:Sacramento:Folsom, wiki:westsac:First Northern Bank West Sacramento, wiki:Vacaville (two locations), Fairfield, Woodland, and of course, Davis.  In addition to an array of loans, accounts and investment products, the bank also offers free checking, free gifts, and free money for unused checks from another institution!  The Bank does not charge any ATM fees.

One really nice feature of the bank is that the staff actually answer the phone, personally! There are no computerized phone systems that answer when you call, although if you prefer do your banking through a computerized phone system, there is one available.

First Northern was Bank Robberies robbed on 20050929.



20051227 21:42:51 nbsp I, and other people I know of, have applied for positions at this bank (we were qualified).  Their human resources division was lousy, and never got back to me (despite many phone calls).  I do not know how their service is. JohnNapier

20090630 13:18:58 nbsp Amazing customer service, the entire staff goes above and beyond. So refreshing to have a business actualy care about the customer and not just a number.  Users/agerould

20100512 11:59:58 nbsp The staff @ the Davis branch is great!  Always courteous and effective to the needs of the customers.  GO FNB!! Users/LRosales

20100612 15:05:35 nbsp Ive been with this bank for about 3 years and havent had reason to complain up till now. My iTunes account was hacked into, and it had my debit card information on it  Stupid, I know! But, the only purchase Ive made on iTunes was a single .mp3 in 2008, so I didnt realize the card number was still on there. An unknown person used my account to buy over $350 worth of applications for products I dont even own (iPads and iPhones). It is my belief that the person who did this was not actually the hacker, but used a password dump that a hacker uncovered, and posted online for anyone to use. This idea is backed up by the fact that this VERY SAME THING has been happening to a vast number of people in the past few months  their iTunes accounts are being accessed, hundreds of (or sometimes only one or two) purchases being made. Sometimes the offender changes the accounts password, and sometimes they dont.
With my password, this person was able to buy over $350 of apps and videos using my debit card, but wasnt one of the ones smart enough to CHANGE the password or email address so that I would no longer be able to log in. I cancelled my card as SOON as I saw the purchases appearing on my account, and went into First Northern Bank and told them what happened. I also told them how this has been happening to a lot of people, not just me  iTunes has a security issue and really has their hands full dealing with it. I filed a claim with First Northern Bank to get my money back, and a few days later received a barely coherent written response called Resolution Notification. It had multiple spelling and punctuation errors, and it SEEMED to say that they dont believe me  that if someone actually hacked into my account, they would have changed my password, therefore, Im lying, and actually was the one to make all those purchases and then try to cancel them. The quality of the letter is shocking to me, that it possibly made it past an editor and that they would actually send it out to a customer. It offends me, because I lost a lot of money that I really need right now, and they dont seem to care at all.
Not only that, they sent me part of their Electronic Banking Services Agreement and Disclosure Statement, Dispute over Goods and Services  If you have a dispute with a merchant regarding the quality, price, warranty, or otherwise of the goods and services you purchased with your card, you will have to settle your dispute with the merchant directly. In addition to this not being what happened to me at all  I did not file a claim about a dispute regarding any of the above  the copy of the agreement that they sent me clearly states that if you cancel your card within two days of finding out that it has been compromised, all of the charges will be cleared immediately. I cancelled my card within HOURS of it being compromised, and yet the charges still went through. Not only that, but if, as they say, I was lying, why in the world would I buy a bunch of applications for products I dont have, which is totally outofcharacter if you look at my purchase history, and then change my mind and go so far as to CANCEL my card halfway through?

Further, the letter included a number which I could call if you have any questions or if you would like to request documentation on which we based our decision. I called this number immediately, but all I got was the sound of a fax machine. They gave me a fax number to call.

Im writing this here in the hopes that someone will read it and just become aware of the possibility of being treated like this, and the fact that iTunes has a huge security issue right now, and your bank might not be willing to deal with it. Nor will iTunes (I have contacted them as well). So please, take care. Try to avoid this situation.  Users/gurglemeow

20110520 10:32:19 nbsp First Northern has an ongoing problem with its system for downloading account data into Quicken.  I would not recommend setting up your accounts here if you use Quicken, as many people do.  I have taken this problem all the way to the Technical Manager for the bank.  She agreed that there was a problem, but after weeks, it is still not fixed.  In summary, when you download data into Quicken, you will have a huge hassle balancing.  The system is inconsistent in which transactions it downloads (sometimes missing transactions, sometimes downloading them a second time) and the downloaded balance generally is not correct.  The latter problem the technical supervisor acknowledged.  The former problem she did not recognize.  Quicken is very simple and effective when properly set up.  Ive used it for years at other banks.  Hopefully, First Norther will get this fixed and stop frustrating customers. Users/GeneWilson

20120119 15:35:19 nbsp It is IMPOSSIBLE to talk to someone at this bank unless you go in!!!! I give up on them! I hate the big banks like BofA but at least I can speak to someone 24hrs a day if I have problems. Users/mra
