 
 

Frys Electronics is a toy store for geeks.  They sell much more than just electronics, though.  Each Frys has a different theme and for a while, a couple of years ago, they kept getting bigger and bigger and BIGGER, with cafes cafés inside and all.  The new Roseville store features a Railroads Californias Railroad History theme.  Users/MarieHuynhs relatives used to drop her off at one for hours at a time to wander around with no money to buy cool things. That might help explain her a bit.

Frys may also be the most ghetto of all electronics stores as it is the most disorganized and has the worst website.  Its supermarketchain origins might explain this somewhat, and its relentlessly nofrills approach probably explains the rest of it. They are also well known for having very poor customer service (lack of polite service and employees informed about the merchandise). This is probably because the majority of the people shopping at Frys go there already knowledgeable about the merchandise and are just looking for cheaper prices. The Sacramento location does have cool spherical bollards.

Frys will match the advertised price of any other local brickandmortar store and any internet retailer within 30 days of purchase.  With regards to internet price matching, the staff will look up the item on the website and then give you a refund.  The item must be in stock at the other store.  Bringing in the store ads might help to speed up the process.

A new Frys Weekly Ad appears in newspapers and online every Friday. The deals in the ad are good for 7 days until Thursday. There are also daily newspaper ads of one or two pages every day of the week. A link to ads can be found on the Frys Website in the upper right hand corner.

When you leave the store they will ask to see your receipt and look in your bags but if you dont like that you can just ignore them. If Frys is too mainstream and consumeroriented for your tastes, you might try HFE Electronics.




Frys is the best place to buy electronics if you already know what you want. Geeks like me love it because the prices are low and the selection is usually pretty good, but Users/RobRoy is right, the place is pretty ghetto. The Bay Area Frys stores are mostly themed (Egyptian, Aztec), but the Sacramento Frys used to be an Incredible Universe  Frys didnt do anything to the place when they bought it, and the interior is just this cavernous halfwarehoused interior space with fifty foot high ceilings. Its intimidating!  Users/KenNeville

Is there a way to get there by public transit?  Users/KenBloom BRYoloBus 42 to downtown Sacramento then either 11, 13 or 14 to the area.  I forget which exactly, but youre looking at 23 hrs each way.  Pack a lunch.  Users/TarZxf 

From Heron Technologies: 20060414 09:26:01 nbsp I went there once. The guy running the store was friendly and helpful. Incidentally I dont think we can adequately compare stores like this one to Frys, as Frys stocks refurbished items vs. Heron carrying new components Users/TusharRawat TR

    Nonsequitur.  I hate to be put in a position of defending Frys, but the reality is that maybe one tenth of one percent of Frys items are refurbished and they are plainly identified.  Supporting Davis businesses is well and good.  My family and I spend lots of dollars downtown.  OTOH, Ive just had one bad experience after another with Heron. Users/GrumpyOldGeek
     That may be, I dont know for sure. But if its true then what I would buy from Frys falls under that one tenth of one percent. However, I usually buy computer parts and accessories from http://newegg.com newegg.com.
       No argument about Newegg.  Last month I bought a case of notebook hard drives from them.  My company uses the drives in a product and Newegg had the best price and delivery.  BTW, if youre in the computer components department at Frys and you want intelligent help, ask for Kim.  Shes the older, slim Southeast AsianAmerican woman.  She is very knowledgable and honest.  Users/GrumpyOldGeek
         Thanks. Honestly though; I havent been in Frys for at least a year. Users/TusharRawat TR
   20060508 18:13:42 nbsp Frys refurbished and restocked is always clearly marked. I can understand elevated prices in a local shop vs. megamart/online. However the two times Ive been in Heron have been terrible. First time I came in looking for a power supply, they tried to sell me a cheap offbrand even after I told them I knew thats not what i wanted. Well weve never had any problems / Second time I met another customer who didnt have DVD software after reformat, I advised him to get VLC. Staff jumped in and said VLC would ruin his computer and then sold him $80 dvd software.. Users/TheodoreSuryapurnama


20060706 22:38:28 nbsp I shopped the Frys Stores in the L.A. area for years...the one in Sacramento seems rather shabby, and the ghetto of all electronic stores comment seems accurate.  To me, its a good place to buy consumables and small items, and to get a look at expensive items before purchasing them for much less online...the prices seem rather high at Frys for most items.  Theres a conspicuous lack of salespeople around the low ticket areas, and they arent terribly friendly or approachable in general. Users/DukeMcAdow

20061002 20:32:30 nbsp The organization of the store is like a Guatamalan slum. Everything is disorganized, and everyone there is simply ignoring you until you chase them down. By far, this is the ghettoest Frys in California for all I know. Users/AtyNguyen
   Hey!  I lived in a Guatemalan slum for a couple years!  Ill have you know that Guats are very hard workers and while they like their full size statues of saints, their yards and homes are very organized.  I like the crippled saint with the dogs, personally, and Ive never seen him at Frys. Users/JabberWokky

20070524 15:54:57 nbsp I made a awesome comp from 500 bucks at frys... Users/StevenDaubert

20070604 03:03:10 nbsp The new Frys in Roseville that opened in April is pretty big. The employees ride around on Segways. Users/Jedron

20070920 18:42:14 nbsp This particular Frys has one of the worst customer services Ive ever experienced.  The workers ignore and avoid you, the place is disorganized and dirty, and on top of all that the manager is extremely rude.  He needs to take some communication classes, because he has the worst people skills Ive ever seen.  I went to Frys asking for help because I locked my keys in my car and the manager said there was nothing he could do about it and told me to call triple AAA.  So I did, and tried calling my mom for the triple AAA number, but she wouldnt pick up.  At the same time I was also late for an appointment, so to save time I decided to look for tools at Frys to help me unlock my car door.  I found 2 thin long drilling bit poles, each sold at about 25$ a piece, and bought them thinking I could return them afterwards.  To my horror the manager turned me down, told me off in front of everyone saying, How do you think I feel about you coming to MY store and buying something, using it, and returning it.  The objects were in mint condition and I only used them for about 5 minutes.  Then I replied saying, I dont understand, I asked one of your workers and they said the return policy was 14 days.  He gives me a lame excuse saying the items were used and I replied saying, I dont understand this happens all the time, people buy things, try them out, and return them.  Theyre not going to be returned in new condition.  He snaps back again coldly,” What should I charge you for using it?  I thought to myself, do people get charged for trying out items in your store? I was so shocked that a manager was soo rude.  I have never in my life had customer service as bad as that moment especially not from a high positioned manager.  He then hands me the receipt and says, Im sorry we cant accept it.  How can you not honor a policy? I told myself, Im never coming to this Frys again.  So, now Im returning the items at another Frys store.  I also plan on writing a personal complaint to the corporate office on this Frys.  If youre from Davis, and want to buy cheap computer parts, DO NOT I repeat DO NOT go to the one in Sacramento.  Drive the extra 10 minutes for the one in Roseville, you will not regret it. Users/3balls

  Ok, lets look at your complaints one at at time.  The workers ignore and avoid you.  Yes, they avoid me in the auto sound department because I dont look like a 20something squid that will drop $1k on a car stereo.  OTOH, they treat me like royalty in the computer parts department because I do drop a lot of money there.  Im fine with both cases.

 The place is disorganized, dirty and the manager is rude.  Yes, no and no.  Never had any rude experiences for at least 10 years.  I spend (for my company) $5k$10k / year at the     Sac store and have always been treated well.  I always refuse to show my receipt going out the door and they never hassle me.  The place is seriously disorganized, but I can live with that.  Its no dirtier than any large store.

 Now to the crux of the matter.  You locked your keys in the car.  Wait a minute, you locked your keys in your car.  This is all we really have to know.  Anyone with the vaguest sense of personal responsibility would know that it is your problem, not Frys.  Would I help break into a strangers car?  Hell no.  Would I let him/her call AAA on my phone?  Hell yes.  But forwhatever reason, you had to call your mom, not AAA, and mommy didnt pick up.  Heres a hint.  Keep the AAA number in your wallet.  I do.

 Now about those tools you bought.  You bought them knowing fullwell that you would return them after you used them.  That is not the reason why Frys, or any other store has a return policy.  Just like the clowns that bought generators just before Y2K and tried to return them on Jan 2, you thought that you deserved to have something for a time without paying for it.  This sort of behavior ruins it for everybody.  I think it is clear that whether the tools worked or not, you would return them.  And about those tools.  I buy quite a few tools at Frys.  Now they usually arent the best tools, but they do the job.  But you know what?  When I buy a tool, I like it in its nice shiny package, all new and everything.  I dont like paying new prices for used tools, especially if theyve been used for something they werent intended for.  So I would not be interested in buying the tools you used/misused to try to open your car door.

20070920 21:37:30 nbsp Should we move this page over to the Sac Wiki, since the closest location to Davis happens to be in North Sacramento? Users/PaulAmnuaypayoat
  No.

20080917 20:03:35 nbsp I have had only one experience with frys and it is quite possibly the WORST shopping experience I have ever had. I went to the store to buy a DVD drive (which I admit I had no problems with) my girlfriend found a clearance on 80 GB iPods, and decided to get one. We walked out of the store, got in the car, drove one exit away to In n Out and bought lunch to eat in the car. In the drive through, we noticed that we had accidentally gotten a 160 GB iPod, which is an excessive size for her. We drove back to the store, (up to this point, I have no complaints).
Upon returning to the store, it took 10 minutes for a worker to get us the manager to complete the return. The manager said that they could not take it back because the iPod was scratched and there was no plastic wrap... but I had just gotten in there less than 30 min. ago, and that was the condition it was in then!
He got us the Section Manager who took one look at us, took the iPod, and disappeared for about 45 minutes w/o saying anything to us. After we had been standing for over an hour, some low level worker who had no idea what was going on came up to us and said that he could complete the return.
I got NO apology for them messing it up, and in the end have to wait at least 3 days to get our money back.
They lost 3 customers today; Me, my girlfriend, and our other friend that had to wait for us to finish the return. Users/MasonMurray



 It wasnt a credit card purchase. It was a debt card purchase. Which means they had the money in their account almost immediately. Users/masonmurray

20081209 17:44:44 nbsp Does it not always take around 35 business days to have a credit card processed for a refund....?
It shouldnt. If I gave a credit card refund, it would process just as fast as the original transaction did: instantly.  Users/DonShor

20081228 13:38:42 nbsp Heres the thing about Frys, they have great deals.  Ive bought several laptops and gadgets here for cheap.  Its worth the trip, if you know precisely what you want. But if you have questions or want to consult with someone, dont bother going to Frys.   The Natomas Frys is probably the worst location in America.  Frys, in general, offers horrible customer service.  The staff either completely ignores customers or doesnt really help when they do talk to you.  Again, they do have ridiculously awesome specials on a regular basis.   Users/CurlyGirl26
  Thats exactly my take on Frys, too.  And sometimes they have things that just cant be found anywhere else in the area, so I go even though I dont like them all that much.  Oh, and by the way  since they dont have memberships (like, e.g., Costco) you are in no way obligated to show them your receipt at the door.  Those of us who are offended by the assumption that all customers are potential crooks waltz on by.   Users/CovertProfessor
   That is kinda the best way to use Frys. Its also refreshing to see someone else have disdain for the exit policy, they only can really check you if the suspect you have been shoplifting but they do it under the auspices of  making sure you arent missing anything you have paid for...  Users/StevenDaubert
    Door checkers are also used to prevent collusion with cashiers.  e.g. having a cashier friend ring up only one item when you got two, or ringing up an expensive item as a cheaper one.  That said, the checking is, especially at Frys, usually very cursory.  I doubt they catch many crooks this way.  Users/JonathanLawton
   I generally dont mind the checkout thing that much. I understand the need for inventory control, and if a minor inconvenience on my part allows them to keep their prices so low, its well worth the few seconds it takes. Of course, exactly the same thing happens at, for instance, Best Buy, but the difference is that there it is automated using those detector things by the doors. I wouldnt say that the sentiment is any different between the store, only the may they go about fixing it. Users/JoePomidor
    Have you thought about the fact that even the police cant search you without probable cause?  When you allow a store clerk to look through your purchases, you are giving up a constitutional right.  Is chipping away at our civil rights worth slightly cheaper products?  Youre right that the sentiment behind detectors and searches is the same, but detectors dont detect what youve purchased, only if youve taken something without purchasing it.  So, the means are very different.  I have no problem with detectors, but it makes me very sad when I see people giving up a civil right so easily by opening up their bags for perusal at the door.  It makes me think they wont defend it when it really matters.   Users/CovertProfessor
    You are so right, CP! Users/CurlyGirl26
    Dont most store clerks routinely look through our purchases? Isnt that their job?  Users/NickSchmalenberger

20081228 23:35:55 nbsp Dont people shop here with the expectation that Frys will know what they bought? I shop there willingly and with knowledge of their bag checking just as if I agreed to it by having a membership. Just what rights am I giving up? I can understand being annoyed about the suspicion of shoplifting, but Im not sure that its a matter of rights. Users/NickSchmalenberger
  This right: http://www.nolo.com/article.cfm/objectId/DED24689ADA84785887A0B4A19A694DE/104/143/127/ART/ Nolo: Understanding Search and Seizure Law.  And heres more on http://archive2.tivocommunity.com/tivovb/printthread.php?t276376&page1&pp30 socalled door Nazis.
   The Nolo article says At the present time, the Fourth Amendment does not apply to searches carried out by nongovernmental employees like private security guards. This http://ask.metafilter.com/21420/Canastoresearchmybag other article has more discussion too, but like the tivo article it is not as authoritative as Nolo. If we can always walk by if we want, then we arent giving up any right by cooperating with them, but we are being polite. The metafilter article talks about if there is a line to be searched, and if there was Id be more likely to walk by but I might still wait if I felt like I had time. It honestly doesnt bother me to show my receipt and my purchases. I do it voluntarily and I feel happy that the employees are able to do their jobs, its not like Frys doesnt already know what I bought. Somebody in the metafilter page also says that there is a California law explicitly allowing people to walk by, so if this could be cited it would be very helpful because it would be relevant to Frys here even though the 4th Amendment is not. Users/NickSchmalenberger
    There is no right for a person to demand with any penalty that they search another person.  They can certainly ask; thats well within their rights.  They can even detain you if they have seen you actually steal something and walk out the store (which they can not have done at the door check).  That requires a set of four legal points that must be met (including walking out and a continuous observation since the concealment or conversion; the other two are pretty simple as well, but I cant recall them reliably enough to cite).  Unless they are actually pressing charges, they cannot stop you, and any detainment or requirement to stop and be searched is quite illegal.  I cannot lock you in my bathroom or require that I pat you down when you leave my house because I think you might have stolen a fork, nor can they do the same.  Once the transaction has been completed at the register, you are a citizen carrying your private property in a public space, and they can ask you to leave, but they cannot require you to be searched.  I am not a lawyer, but I have discussed this particular case with several in several states, including California.  There is a very scary tendency for people (including employees and customers) to think that corporate regulations carry the weight of law.  Knowing your rights (which has nothing to do with choosing to let them look in your bag or not) is important.  Instore policy does not create law.  It is that tendency toward believing that a corporate policy is something that can be applied to general citizens that irks some people.  That and the fact that every so often some employee will get physical, either blocking or grabbing people to stop them from walking out.  I know of no cases at Frys where this has happened.  Users/JabberWokky Evan JabberWokky Edwards
     Thats exactly it, JW.  Most people comply because they think they have to, which is sad.  And that was my original point  to let people know that they dont have to.  Im not advocating that people be rude to the checkers; one can simply walk by.  Others know they dont have to comply with the checking, but do so anyway.  Thats their choice, of course.  Its a choice I dont understand, because I cant see cooperating with a store who assumes that all of its customers are potential thieves, and I think that the less were in the habit of protecting our rights, the less we do so when it really matters.  But again, people can choose to do so if they wish.   Users/CovertProfessor
      Ive certainly just walked out of Frys without letting them check anything.  I think the more interesting case is actually Costco.  Since you have a membership with them, does that constitute some agreement with corporate policy?  It certainly includes inbound access control, so it probably means it applies to outward control.  At Costco, Ive actually gotten money back after they reviewed a receipt  the cashier had accidentally scanned an item twice, and the door crew caught it.  Somehow, I doubt Frys is as considerate to customers (given that their current customer service is the bare minimum).   Users/BrentLaabs
      The last time I was at Costco I couldnt find my receipt at first and after looking through various pockets the guy just said I could go anyway, after which I did find it in another pocket, but it shows what can really happen at there.  Users/NickSchmalenberger

20081229 13:15:34 nbsp I dont know the law but if Frys didnt search bags theyd be bankrupt and shut within a month.   Most people will steal if they think they can get away with it, and Northgate Frys is in a bad neighborhood with high unemployment.

Frys might be going bankrupt even with their bag searches.  Frys VP of Merchandising was arrested for embezzling $65 million a few days ago.   He needed it to pay his Vegas debts.   He must not have carried the money out in a Frys bag.   Google Umar Siddiqui for details. Users/SteveGreen
  All the Frys do it, including ones in nice neighborhoods like Sunnyvale and Palo Alto.  And somehow, most other stores manage to get by without it.  Users/CovertProfessor
   All the Frys do it because rich people steal as much as poor, if not more.  Siddiqui stole $65 million from Frys.  He drove a Ferrari and lived in Palo Alto.  Circuit City and Best Buy will look through your bags too.   Best Buy has video surveillance like an airport.   Every square inch of Best Buy is on tape.   To me thats more intrusive than a human being looking at my receipt and shopping bag. Users/SteveGreen
    You were the one who brought up the issue of the Northgate Frys being in a bad neighborhood, not me.  I dont know the statistics for theft in these different regions; I was just pointing out that whatever Frys reasoning, it has nothing to do with particular neighborhoods.  I wont say that I like the video surveillance any better, but thats a topic for another place and time.   Users/CovertProfessor
  Being in a bad neighborhood compounds the shoplifting problem.  That doesnt mean its not a huge problem for retailers in good neighborhoods too.  If Northgate Frys did bag checks and Roseville Frys didnt, just because Rosevilles a better neighborhood, then all the shoplifters would drive to Roseville.   Just like most home burglaries in Davis are committed by people who drive in to Davis from South Sac, Vallejo, Woodland, etc.   Thieves follow opportunity, wherever it is.   A $2500 laptop is the same size as a $500 laptop and just as easy to steal.   One stolen $2500 laptop erases all profit from the last 1015 legitimate $500 sales.   Retailers selling high ticket items that are easily pocketed and pawned cant stay in business without strong security measures.   Without bag checks and/or video surveillance there would be no brick and mortar electronics stores.   Users/SteveGreen

20081229 19:50:45 nbsp I see the bag checking as being like a minimum charge for credit cards. Yes, it is probably against their contract with the credit card company and I could call them on it or complain to my credit card company, but if it is a store or restaurant that I like Im not going to. Bizarro World and Shanghai Town are two places I know have minimum purchases for credit cards and if I complained about it I would be an ass. To shop there at all requires some cooperation with them and I think partial cooperation is somewhat rude, so I try to accommodate them if I sincerely want to be their customer. They are just trying to do their job the way they have determined is best so I think I can either take it, leave it, or make trouble regardless of if I have a right to act differently than they want. If you do choose to walk by and its not a big deal then thats fine too, but its nice to have some respect for people doing their jobs.  Users/NickSchmalenberger

20090210 11:18:05 nbsp I feel there is some difference between accepting that you must buy a minimum amount before they will accept your credit card, and someone going through your bags.  As I see it, its the difference between someone saying No, I wont take that, and Let me go through your stuff.   Until today, I was completely unaware that Frys had no legal right to go through my things, if you read my last comment it did not protect me as a buyer at all.  Therefore in the future, I will not be allowing them to do so.  Users/MasonMurray

20090303 00:00:52 nbsp I know Im not alone in this: I am sick of the horrendous customer service I experience every time I shop at the Northgate Frys. Just today I needed a motherboard/cpu combo that was advertised but not on any of the displays or shelves. So after about 5 different employees saying they didnt work in that dept. (even though they were standing right there) I found a guy that was helping a customer at the time. So I patiently waited but made sure he knew I was obviously in need of assistance. After teaching this customer about building your own system for a good solid 5 minutes, he started walking away to print out something for whatever he just sold to the newbie. At that point I just said, excuse me, sir. No reaction. Excuse me, Sir! He barely made eye contact with me and said, Ill be with you in a minute. Right. 5 minutes after that I was finally helped by a newly arrived employee who told me that they were out of stock for that combo. So basically I stood there for close to 15 minutes for nothing. Ive worked in retail before, and I know when a sale item is hot and goes out of stock. All that one guy had to do is give me a few seconds of his time and tell me they didnt have anymore. This isnt the first time an employee just walked away knowing I needed to ask a question. What is their problem? Seriously. It almost seems that theyre looking to get fired so they can just file for unemployment. If it wasnt for the low prices, I would never shop at this Frys. Absolutely the WORST attitudes and service of all the Frys Ive been to. Users/ReginaldW.

20100513 18:18:18 nbsp The Frys off Sacramento has always been known for their lack of customer help and disorganization.  Always has and probably always will be as long as corporate does not do something with management. And judging by the recent comments, this has not changed one bit from the time I commented 2 years ago.  Good job Frys.  Cheap electronics, crappy customer service. Users/3balls

20110502 08:05:03 nbsp Is Big Mike the manager, letting Jeff and Lester run the show? :) Users/MichaelNielsen
  No, youre thinking of Best Buy this place.
