

Glacier Point Apartments is a quiet and friendly community located in an optimal area of West Davis.  Residents enjoy a fitness center, pool and spa, barbeque spot, media loft and internet lounge with free WiFi.  With quick freeway access, walking distance to shopping, restaurants and more, and a bike path and bus lines to campus, Glacier Point is the ultimate location!  The complex offers an array of floor plans from single bedroom to spacious four bedroom apartments and every unit features a washer and dryer.

There is permanent staff in the office available to help anyone with questions regarding Glacier Point. Prices are competitive compared to other apartment communities in the area:  $1060.00 for a 1BD/1BR, $1295.00 for a 2BD/1BR, $1335 for a 2BD/2BR, $1,715 for a 3BD/2BR, and $2,095.00 for a 4BD/2BR.

The MU is about 2.5 miles from Glacier Point by car and just 1.5 miles via bike.  Glacier Point is on the Unitrans P/Q bus line, which also runs on Saturdays.  The Q Line stops directly at Glacier Point.  The P Line can be caught on the corner of Shasta Drive, the street before Denali.  Many residents opt to take the Q and transfer to the G Bus Line G Line at the Congregation Bet Haverim synagogue stop. However, if transfers are late, Residents have suggested communicating with the drivers.  For those who dont mind a short walk, the B line, on Sycamore Lane one block south of the Marketplace, is only 10 minutes away.

The Marketplace is just down the street (1 mile), where there is a Safeway and lots of other stores and restaurants.  If you go down a little bit further, youll find the Anderson Plaza with its SaveMart (1.3 miles) and Oak Tree Plaza with its Nugget and lots more shops and restaurants (2.6 miles).

For more information on rental housing in Davis, take a look at our Housing Guide as well as our Apartments page.


Older Reviews

   /Reviews Before 2009 Reviews Before 2009

Current Reviews

20090821 13:37:43 nbsp We moved in to the complex back in 8/2006. On initial movein there was a different manager, nice person, bit of a busy body (gossiped & would try to act like your best buddy). I did not care for her too much but she wasnt there for much longer. Management changed within the same year and made quite a difference. Beverly is one of the nicest and accomadating managers I have met yet. Jerry (maintenance) is very friendly, responds to ANY issues same day and I never felt nervous with him in our apartment with our cat when we are not there very important to me. We had a bad roommate situation and they were completely understanding  & did not hold it against us for our misfortune. They told us how to handle it and what they couldnt do and really showed us they cared. Nicole joined there team and she is just as awesome as the other two. This team really makes the effort to show the tenants that they are there for us. As compared to other places I have lived in where it was always at their convenience. The only reason I am moving is because we needed to relocate. If I ever need to move back and this management team is still on board, I would move back in a heartback. Good Luck Beverly, Gerry & Nicole, and Thanks! Users/Shallon

20090901 10:47:15 nbsp Had a great experience living at glacier, didnt deal with management much, but when we did they were very easy to talk to and very nice about dealing with things. The repair guy was great and responded to requests very quickly. Would have continued to live here but we needed a place closer to school. Great place to live, no complaints. Users/rocknice

20100125 09:45:56 nbsp I have been living at the Glacier Point apartments since September. So far, Ive had a great experience. Before moving in I looked at a lot of other apartment complexes and this one was by far the nicest. The property is kept neat and the insides of the apartments are also in great condition...new paint, clean bathrooms, etc.
The management are very nice either when just saying good morning or when dealing with any concerns that I have. There are always (good) coffee and donuts in the mornings and cookies in the afternoons. Whenever Ive reported something that needed to be fixed, like a light, it was taken care of within that same day. Parking has never been a problem, I can even find spaces in the lot when I come back at 3 a.m. The gym and pool areas are also very nice. They even have my favorite exercise machine from the ARC.
The only problem Ive found is that my cell phone reception wavers depending on where I am inside the apartment. Besides that, I love everything about this place and had no hesitation renewing my lease. Users/KatieP

20100125 20:12:55 nbsp Glacier is an okay place to live in, as a freshman who moved in from the dorms, its decent (no more fire hazards!) My roommates and I are currently in a three bedroom suite. As what everyone says, the walls are thin, but as far as I can tell I can only hear locally within my own suite, I sometimes hear the people upstairs but thats usually like a chair falling over and other things. Unfortunately, the way the master bedroom in the three bedroom is connected to the living room, lets just say Ive heard things that Ive never really wanted to hear.

I do have nice things to say about the management, they are friendly and pleasant. Maintenance is usually pretty quick about things and are honest about when things would be done, Jerry the main guy is friendly. And Glacier occasionally holds some events like pie day, free breakfast for finals week which is nice.

And I will definitely say that Cell phone reception for AT&T is terrible for my spot, I usually only have 12 bars and my roommate has to put his phone by the window. I know this isnt particularly Glaciers problem, its just annoying.
And currently Glaciers only service provider for internet is comcast, Id definitely recommend calling the davis rep for comcast for a deal were are paying ~$80 for high speed internet and basic cable with free HBO/Starz for 9months.
And biking to the UCD campus takes about 1020mins if you take the bike path across 113.

We did not renew our lease for this year because of roommates going to different places, but I guess I would still recommend Glacier, yay for free cookies! Users/theyangster

20100220 18:20:26 nbsp i know this is probably just wishful thinking, but does anyone know if were allowed to paint the walls while we live there? then just paint them back to white before we move out? Users/JacquelineD

20100831 16:05:44 nbsp Weve been here for 4 years, and we loved it. Were moving out because our family is growing, otherwise we would have stayed. Management is very nice, maintenance requests are addressed the same day or the next day. The pool area is nice and hardly ever crowded, so is the gym. They added the BBQ area a couple of years ago which is very nice. The place is quiet good for older undergrads/grads and young professionals. The only downside (for lazy me) was that it was a longish bike ride to campus 1520 minutes. Other than that I highly recommend it! Users/Zzz

20100831 16:07:12 nbsp I forgot to add: the morning coffee and donuts and afternoon cookies are great. For the past year or two, they also have a community dinner twice a year with free food. And, my favorite, free continental breakfast during finals week. Loved it! Users/Zzz

20110215 15:09:04 nbsp I have lived at Glacier Point Apartments for 2 years now in a 1 bedroom apartment. The complex was built in the mid2000s if I recall correctly, so it’s fairly new. The apartments are in good working order (nice windows, carpet, appliances) and come with their own washer/dryer as well as central heating and air conditioning, and a kitchen with all of the standard appliances. I cant hear my neighbors unless they slam their front door or hammer their walls. Im on the top floor so I cant comment on footsteps, etc., but Ive never had any complaints from the residents below me. There is a pool and hot tub that are wellmaintained, as well as a rec room with treadmills and other exercise machines. The entire property is taken care of very well and looks nice. Parking is available for all residents and finding a spot is never a problem.

The complex is off of Covell. There is a bus stop for the Q line right at the complex, and a bus stop for the P line a few minutes away by walking. Additionally, the D and K lines are accessible by a 5minute walk down Denali Dr to Arlington & Shasta. Highway 113 is one block away on Covell, and driving to campus or downtown takes 510 minutes. There is a plaza with a Safeway and CVS about 2 minutes east driving on Covell. There is a bike pathway off of Glacier Dr. that links to the bike loop; biking to campus takes 1020 minutes.

The management (Bev and Nicole) are very friendly, along with Jerry (maintenance). They have coffee, donuts, cookies, and candy at their office whenever I stop by. Jerry has responded to my maintenance requests within 12 days and I’ve never had a problem getting things fixed. Management hosts fall and spring socials for residents where they provide delicious hot food. During finals week of each quarter, continental breakfast is offered to residents.

There are a few potential drawbacks to living at Glacier Point. It’s far away from downtown or campus, so you have to bike, drive, or take the bus anywhere you want to go. The bus lines nearby aren’t the best – the P/Q have long routes and only stop at the MU  but many residents use them. It’s also a quiet complex that’s probably not too partyfriendly. I chose Glacier Point because it was new, quiet, and offered plenty of amenities, especially the washer and dryer. Its location and distance from campus didn’t bother me since I enjoy riding my bike everywhere. I don’t take the bus often, but it’s convenient should I ever have to. I would definitely recommend this complex to anyone!
 Users/jamesd

20110802 16:44:53 nbsp I lived there last year and enjoyed it quite a bit.  Reasonable pricing, good perks (donuts every morning, cookies in the afternoon, breakfast during finals, etc.), and decent location.  But the best thing about Glacier Point is Jerry.  Jerry is the maintenance guy for the complex and he rocks!  Super friendly, good attitude and responds very quickly to work orders.  I would definitely recommend living here, as long as youre able to put up with the P/Q lines. Users/KieranToovey

20110925 20:48:10 nbsp Glacier point is a fairly nice place to live in, except for how far from campus it is.

The worst part comes when you actually move out...so here comes my experiences at Glacier point (over 2 years).
The first apartment I was in, was a 3 bed/2 bath with a $600 security deposit. Come the end of the year (AFTER I had already signed a lease on a different apartment in the same complex), the management attempted to withhold a little less than half of my security deposit for cleaning and painting. When we received the moveout paperwork, it said that approximately $200 would automatically be deducted for CARPET cleaning...no matter what.<this is ILLEGAL. Also, my roommate and I (and our parents) cleaned that place for hours...and followed all of their instructions to the letter. So needless to say, we were surprised to have gotten only half of our money back after all of the effort to clean the place. So we had to go after the management, but wouldnt you know it...they gave our money back because they were not allowed to do that.

Of course I had signed a lease before I realized that all this crap was going to happen...so come year 2. I had prepared myself and discussed all issues with the management at the beginning of the year. This time, they had more specific cleaning outlines, as well as did not deduct for carpet cleaning costs. BUT of course something else had to happen. My roommate and I cleaned the place, once again following the instructions to the letter. Also, the complex is trying to charge me for a 1/2 paint on an apartment that DID NOT need any painting, because it was NOT damaged by me. Again they have tried to weasel me out of half of my security deposit.

Even though this complex looks nice, it is nice until you try to get your security deposit back....because you WILL have to fight in order to get your full deposit back. Renter beware because the security deposit is sure a lot of money! Users/EmilyRichards

20120726 14:24:08 nbsp Ive lived in Glacier for the past year and I love the property. I had planned to live here for an additional year, however some things happen with the people that I was supposed to live with. Beverly was very understanding with the issues that we were going through and tried to help us to her best ability. She is the nicest out of all the people in the office. Also, during the time that I lived at Glacier anytime I had any issues with anything in my apartment not working the maintenance man Jerry always came in a timely manner to fix the problem. In all Glacier is a very nice place to live and I would definitely recommend it !   Users/PatriciaCrowder

20120813 10:25:29 nbsp My wife, daughter and I lived in GP for just under 2 years. Bev and Jerry are very friendly and repair service has always been prompt. I believe this is one of the quieter complexes, since I have heard some of my friends complain about undergrad partying where they live. The management sponsors many tenant appreciation events, such as bagel breakfasts during finals week, chili night, and free coffee and donuts on weekdays. The pool and spa are also in good working order and are always a pleasure after a long day at work. Upstairs from the exercise room there is also a large screen TV for movies and cable TV where my daughter watched the olympics. Aside from the amenities the apartments are acceptable. The appliances are neither very new nor very old, and the location is neither very good nor very bad.

For families with schoolage children, the Patwin school is a 3 minute bike ride down the green belt, and it is an excellent elementary school. The bike commute to UCD campus is 1520 minutes, and there are close bus stops on Covell for those not into biking. The parking lot is all unreserved spots, with some under a shelter. I have only once seen it completely full, so there is never a problem finding a place to park. All in all, our experience has been very positive living here, and I would recommend it to others looking for an attentive management service. Our experience in other places with bad property managers fueled our pursuit of a good staff (using these reviews on Davis wiki) and the reputation for prompt and courteous care taken by Bev and Jerry is welldeserved. (e.g. Jerry helped me when I lost a house key and fixed our washing machine very promptly. Bev gave us a very good reference for our new landlord and helped us set up a sublease agreement for the last month of our lease).

While we have not completed our lease yet, I cannot address the comments from other tenants that Yolo property management will try to keep the deposit. However, our past experience is that they have been fair and that they offer a walkthrough before the lease is up give some idea if the apartments condition merits a full refund. Again, because of the management and amenities I highly recommend Glacier Point, especially for students or small families looking for a quieter apartment complex. Users/IsaacGreenhut

20130308 12:57:12 nbsp I absolutely LOVE this apartment complex. My housemates and I moved in three years ago and we never left! The management is extremely nice and helpful. They are always willing to answer any questions that we have and assist us on the spot if we ever get locked out of our apartments or need to pick a package up. Jerry, the maintenance guy, is extremely friendly and efficient! If we ever had a problem with our bathroom or apartment light etc. all I would have to do is tell Jerry about it, and he would show up on the same day and fix it. On top of that, we get free donuts and coffee every morning, free cookies every afternoon, and free breakfast during finals week. We also get free printing in the main office. With such an incredible management and so many perks, Im sad to leave Glacier Point Apartments because Ill be leaving Davis. But I would recommend anyone whos looking for a great place to stay to check this place out! Users/manpreetbath

20130311 11:44:34 nbsp We have lived in these apartments for three years and never once had a problem.  The management at Glacier Point is outstanding.  Whenever there is something wrong ( i.e a light is out or a drain is clogged) Jerry the Maintenance Man fixes it right away.  In addition to the excellent service at Glacier Point the people who work here are also very personable ( Jerry!) and willing to talk to you anytime. Though this apartment is farther away from campus than some others might be the management and the perks of living here ( i.e free coffee and donuts in the morning; cupcake and pie day; socials; and free breakfast during finals week) definitely makes up for itLaura R. Users/LauraRichstone

20140318 12:24:29 nbsp GLACIER POINT RESPONSE TO LAST REVIEW:

Hello Christine and thank you for bringing this to our managers attention on Saturday  I believe you spoke to her the day you reported this and your maintenance request is actively being met.

Glacier Point recently welcomed our new Resident Manager, Heather, who is aware of this issue and it currently organizing a bike sweep and the installation of new bike racks.  Unfortunately it seems our last Resident Manager didnt follow through with the last bike sweep for which we apologize.

Glacier Point and Yolo Property Management has a reputation for being very responsive to our Resident requests and unfortunately a need for additional bike parking was not brought to our attention until Christines call into our Resident Manager this Saturday  perhaps this was on account of the previous manager not relaying the need to our company which is unacceptable if that was the case.  If any Residents or their guests ever feel for any reason that property needs are being overlooked by a Resident Manager, we urge you to call Yolo Property Management directly.  Of course, we are confident that with our new Resident Manager, Heather, this situation and any future resident needs will be met swiftly as extraordinary customer service is our mission and what we are known for around Davis.

Thanks again Christine.  We understand your frustration and are working to improve bike parking. Users/D.Sparks
