

20101020 13:21:21 nbsp Welcome to the Wiki!  Just to let you know, a lot of folks around here are opposed to Wiki Community/Organizational Accounts organizational accounts.  Please consider the importance of using your RealName.  Or, at a minimum, consider identifying the individual who uses this account to establish a bit of identity.  From what Ive seen, your edits have been great, so abuse isnt really a problem; people like knowing with whom theyre interacting, though.

On the Fruit & Vegetable Map page, I suggest adding Pedrick Produce to the map.  They have fantastic prices for seasonal fruits. Users/TomGarberson

20101021 17:45:12 nbsp Im super excited about your map. I cant wait to be able to see ataglance where the deals for produce are. Especially because I think the idea of the poor student who cant afford fresh food is something that has to go   we create habits that are hard to break when we learn to be fast food and Ramen eaters in the relative poverty of our college years.

Ive done some pretty detailed price comparisons across Davis stores, though, and I noticed that some places have a lower base price than the advertised sale price at other places. Do you have any way of establishing a baseline for products, so that people can tell if, say, the weekly special at Safeway is actually a deal, or if itd be better to get that same product at the Coop at their regular price?  Users/JoRo
    Thanks for your feedback! We have not really decided a way to establish a baseline for produce prices, but it is something that we can look into. This is a new project and right now were just seeing how it works, if its being utilized, and then from there hopefully establishing a more thorough and extensive list in the near future. Users/HEPWellness


20101027 10:50:04 nbsp If you dont want other people to edit your work, why are you putting it on the wiki? It is unreasonable for you to ask people not to edit your work on here. Users/WilliamLewis

20101027 11:29:25 nbsp Hi Yasmine, Users/WilliamLewis reposted the contents of your document to the Fruit & Vegetable Map/Talk page.  Using external documents is unnecessary when theres an entire wiki for stuff like that!  I think youll find, though, that people arent too keen on the idea of reserving a page for a single editor (or rather, organization) to use.  Everyone loves the idea of the page itself (as you can see from the comments here).  But exclusive use of a page runs contrary to pretty much every wiki norm.  Head on over to that talk page I linked; I have a feeling people will start giving their input on it pretty quickly, and there might be some good suggestions for how to ensure that other editors contributions fit within the goals of the page. Users/TomGarberson
     Thank you for your feedback and tips! Im slowly figuring out all these wiki tips & tricks. I understand everyones concerns and I appreciate the feedback. As mentioned before, this is a new project and at this stage were hoping to gather feedback and assess if its a tool that is being/will be utilized. If it seems to be successful, well be able to hopefully create a more thorough and extensive list of markets, produce stands, and grocers in the area. Truthfully, there isnt much to edit besides nutrient information and recipes (which I hope we can archive). I just want to ensure that information is accurate and that is really why were asking for suggestions to be emailed or posted to the page. Wed love to incorporate everyones own recipes, tips & tricks for picking or cooking produce, resources, etc. I dont want the page to get overwhelmed because wed like it to be as simple and streamlined as possible.  Users/HEPWellness

20101027 11:51:41 nbsp Its an interesting request.  There are some semirelated cases.  Keep in mind that youre trying to establish a new tradition of editing.  There are no hard and fast rules here on the wiki, but there are some commonly accepted behaviors that people have figured out.  Its very people oriented.  Sort of like theres no actual law mandating people in lines, but when people are all trying to get something, we all get in line, and cutting ahead of other people is considered rude  but the crowd might let a very pregnant woman to the head of the line.  I can think of a few vaguely similar cases elsewhere on the wiki (people running for city positions or ASUCD candidates have their official candidate statements on the wiki, for instance).  Theres been a discussion page about that entry for awhile now, as people are trying to figure out what the goal is.  Read Fruit & Vegetable Map/Talk.  Keep in mind that this is part of the reason it can be a horribly bad idea to use the name of the organization for your account  these are all social interactions, with people talking out how to handle the situation, and youre wearing a big mask, and people dont know who they are talking to... or even if they are talking to the same person the next time theres a reply from this account.  From experience, anonymity coupled with an officiousness of an I AM OFFICIAL account name tends to cause some uncertainty that makes it difficult to work with you.  Or you all.  Or whoever is using this account.  Since figuring this out is all about social interaction and working with other people, you might want to reread Toms very first comment to you in that light.  Again, no hard and fast rules regarding it... but even the most polite person standing in line wearing a mask tends to cause some social anxiety among the people around them. Users/JabberWokky Evan JabberWokky Edwards

20101027 12:51:15 nbsp As a completely different take on the situation, if your actual goal is in promoting healthy eating, you have a bunch of volunteers trying to help your cause, who took the initiative to start adding recipes and expand the project... that you just told Stop! to.  Just as something to think about, you might consider working with that momentum instead of trying to sharply curtail it.  Personal thought, just trying to help. Users/JabberWokky Evan JabberWokky Edwards

20101027 13:58:58 nbsp It seems like your organization wants to take advantage of the wiki (albeit with good intentions) without respecting the thing that has made the wiki such a great resource: the accumulation of the collective wisdom of the community.  Perhaps if you didnt try to so tightly control the page, your organization might realize that the community knows a lot about this subject and could very much contribute.  Forcing the community to contribute only via suggestions that are vetted by your organization, however, is a bitoffputting.  I certainly have no interest in participating that way.  Users/CovertProfessor

20101027 14:13:30 nbsp The Wiki has had some trouble with campus organizations in the past that did not respect the main point of the Wiki and usually it ended up with the organization looking bad. The problems probably could have easily been avoided if the representatives of the organizations actually took the time to become a part of the community. Just sayin. Users/hankim

20101027 14:39:06 nbsp I want to reiterate the point that the page is an awesome idea.  I just think (like the others here) that if its going to be on the Wiki, it should be done as a Wiki page.  It really does work well! Users/TomGarberson

20101027 17:52:06 nbsp If you want to save people time and money in regards to veggies and fruit, heres what I would find most useful.  Every Wednesday, go to Safeway, Savemart, CoOp, Nugget, Westlake IGA, Pedrick, Yolo Fruit Stand, and Ikedas.  Check the prices on fresh carrots, broccoli, yellow onions, garlic, tomatoes, mushrooms, green beans, cauliflower, zucchini, iceberg lettuce, romaine lettuce, spinach, and the cheapest form of mixed baby lettuces.  Also check whatever apple is cheapest, bananas, grapes, oranges, blueberries, whatever melon is cheapest.  Check prices on frozen broccoli, corn, mixed veggies, peas, green beans.  Check prices on cheapest 8oz canned tomato sauce, 6oz canned tomato paste.  Also add in weekly specials in produce.  POST all of these prices, for as many markets as you can, up on the Fruit/Veg map page.  That way, all of us shoppers can pick what grocery store we will shop at based on market fluctuations for the veggies we cook with.  If you have a smartphone you can edit the table directly while you do research in the store.  I would imagine that you could have the notetaking for each store done in 1520 minutes. Users/JudithTruman
 And it certainly couldnt hurt to contact the places ahead of time to see if theyll provide the prices and save you the trip.  The Nugget, Westlake, and the Coop all seem like they might be willing to do that, whether for marketing or general health/outreach purposes. Users/TomGarberson

20101103 12:03:11 nbsp Deleting content off the /Talk page does not encourage conversation, which is the point of the /Talk page: discuss issues without extensive reverting of page versions.  If the fruit/veg page now says Health Center....does not endorse these recipes then it seems the recipes should not be on a page which is linked to an organization.  Please put back the contents of the letter (not all of us have computers that read .docx, which is why it was pasted plaintext) and join the discussion.  Wed like to know more about where the project started and where you all intend to go with it. Users/JudithTruman
