
To explore other dentists in the Davis area, please visit our Dentists page.


20051102 11:04:04 nbsp Ive been seeing the dentist since my teeth started coming in. No cavities so far ;) Users/RyanCastellucci

20051202 16:05:25 nbsp Ive only been to his office once, but I was very impressed with the quality of work, honesty, friendliness, and professionalism. Users/GrahamFreeman

20061012 11:56:50 nbsp Ive been to Howard for 20 years; hes very capable technically, but his mannerism is a bit frantic for my tastesseems distracted at times.  I had to take significant initiative to obtain insurance reimbursement for a crown replacementsomething that was his responsibility rather than mine.  Im also a bit disgruntled about being coaxed into paying for a Night Guard that was unnecessary.  Time for a change. Users/MikosFabersune MF
      I would like to comment on this, most dental offices will contact thier patients insurance company and file the claim as a service to the  patient.  Getting reimbursement from the insurance company is actually the patients responsibility (not the dentists), just as it is the patients responsibility to pay the fees if the insurance company denies the claim.  If you want to make sure your insurance company will cover a procedure you can always get a preapproval.  dagonjones

20070513 17:40:27 nbsp Very kind and professional  At my first appointment, Dr. Shempp met with me in a small conference room to describe his medical style, address my concerns about my teeth (hadnt put that much thought into it really before then), and described his care plan  before I even got in the chair  quite the service for just a regular old cleaning!  I also sought out Dr. Shempps office to get a second opinion about a procedure that was recommended by another Davis dentist that seemed unnecessary.  Dr. Shempp gave me the pros and cons, his recommendation, and respected my decision on the issue.  I highly recommend Dr. Shempp and his office.  They also put thought into your financial needs when considering care plans (great with handling student insurance).  It does take a long time to get an appointment, expect a 6 mos. wait (they do call if they have cancellations).   Users/SaraMeyer

20090714 20:28:14 nbsp Best dentist in Davis!  Friendly staff and love the fish in the waiting room! Users/davisgirl10

20091111 15:08:43 nbsp I would highly recommend Dr. Shempp.  I was referred to Dr. Shempp by Dr. Mandelaris (an excellent pediatric dentist) about a year ago and I have been very impressed.  When I had questions about a procedure Dr. Shempp had recommended, he called me back immediately on my cell phone.  He was knowledgeable and professional and very willing to answer all my questions.  His office staff has also always been courteous and helpful.  Most impressively, Dr. Shempp also has helped me resolve a dental problem that had been plaguing me for years and that several other dentists had been unable to address. Users/KimHeroy

20120619 16:01:12 nbsp My husband and I have been seeing Dr Shempp for the past 7 years. As an inveterate dental coward, finding a dentist who makes me comfortable is always difficult. Dr Shempp is the most calming and reassuring dentist Ive ever had. Hes a real professional. He has always explained what is going on with my teeth, options to treat (and manages to do it in a way that doesnt assume that even though I am a physician myself that I know anything about teeth but also feels like hes talking to me as a professional... and thats hard to finesse.) I just had my first visit to replace 2 decaying crowns and I have two temporaries in. I asked what to do should they come out over a weekend and was told to call and he would probably be able to meet me at his office to replace them. Really. Over the weekend. Who does that anymore? Its like my husband said about him: Dr Shempp is the first dentist hes seen that seemed like he wasnt just fixing a problem you bring to him but someone who really looks after your teeth  like a Marcus Welby for your mouth. Finally contrary to what one of the posters above suggested his staff has always taken care of my insurance claims without a problem. Ive never had a problem that MF describes. However his comment was 6 years ago so they may have gotten better since then. Users/NickGorton
