How is Robert Lugo incorrect? It didnt mention the plea deal, so I added that. Also, the page is pretty incomplete... but what is there is a rather factual recitation of the charges against Mr. Lugo. Was the plea deal later vacated and the charges dismissed? For example, looking through some of the news articles, it is claimed that Mr. Lugo has to register as a sex offender (like one would if one was convicted of four counts of felony sexual battery). However, hes not in the database (well... someone who uses the alias Richard Lugo is in there, but hes too old to be the same person). Is the newspaper coverage incomplete and are there further developments that arent documented there? Users/WilliamLewis

20100806 10:44:10 nbsp Pages on this wiki dont need to be approved by the subject of the page. Stop deleting the page; it will simply be restored, wasting all of our time. How about you answer my questions about your claims that the page is incorrect instead of making lame pronouncements of nonexistent policy? If anything is incorrect, a correction would be greatly appreciated. Users/WilliamLewis

20100806 10:51:05 nbsp Mr. Lewis,
Please review the policy regarding the posting of pages about people.  It states that pages should receive approval by the person about whom you are posting.  If you would like to continue to post this page, please contact Robert Lugo and ask for his approval.  Additionally the newspaper coverage is incomplete and the details were not reported.  This page is inflammatory.  Please stop reposting this page.
I would really appreciate it.
HWestbrook Users/HWestbrook

20100806 10:51:07 nbsp Hi Mr./Ms. Westbrook, and Welcome to the Wiki!  Theres a difference between User pages and Person pages.  User pages are a page maintained by a given user, for that user, and about that user.  This is your user page.  Person pages are pages about a public figure of some sort and, like any other normal wiki page, are owned and maintained by the community as a whole.  Compare, for example, Rob Roy and Users/RobRoy Users/RobRoy.  One of them is Robs page, while the other is a page about Rob.  He is welcome to do whatever he wants with his page, but if he tries to alter the page about him in a way that doesnt improve its value to the community, its not going to fly.

Mr. Lugo has been the subject of several news stories because of his actions and his plea.  To the extent that the details of his case are public record, they are entirely appropriate for a page about him.  If he were to make a User page and didnt want them listed there, that would be fine.  But thats not the case with the Robert Lugo page.

The Wiki is big on chronicling significant events in or around Davis or people somehow involved with Davis.  Its primarily an informational resource.  The editors here (of which you are one!) generally arent going to permit the removal of significant information, so long as its accurate.  If you believe the information is inaccurate or somehow harmful (other than to the reputation of someone who admitted the factual basis for the crimes), please feel free to explain.  His desire that the information not be listed here isnt enough of a reason to remove it, though.  If you feel the information is incomplete, you are of course welcome to fill in the gaps. Users/TomGarberson

20100806 11:06:59 nbsp This page is damaging.  After appeal in 2005 all charges were dismissed therefore this page and all its contents out of respect for Mr. Lugo should be removed.  I am sure you would not appreciate negative and incorrect information about you being posted.   Users/HWestbrook
 I absolutely would not, and thats why its important to correct the information.  I hadnt read over the stories yet, only the summary, and I agree that the page should be clarified.  Its newsworthy, though, and just as a newspaper isnt going to leave out a story because the subject of the story doesnt like it, Davis Wiki tends not to delete pages.  We do try to do everything we can to ensure that theyre accurate, though.  Im happy to try to fix up the page to accurately reflect what happened, although it might be a bit gradual.  Youre certainly welcome to do the same Users/TomGarberson

20100806 11:19:12 nbsp Just because something is or was newsworthy does not mean it should be posted.  The news is often inaccurate and damages people and their reputation.  I hope you and others will never have to experience the type of pain and long term consequences of inaccurate news reporting and posting on the internet. Users/HWestbrook
 You have yet to post about what you think is inaccurate. We dont want inaccurate things here, but your continued refusal to identify what you believe to be inaccurate makes us unable to help you! I updated the page again with the expungement in 2005 that you mentioned. Users/WilliamLewis

20100806 11:34:43 nbsp Did you create the account http://daviswiki.org/Users/GJones?actionuserinfo GJones? Users/WilliamLewis

20100806 11:38:56 nbsp Ive rewritten the page to reflect the biased news coverage and the fact that his conviction has been expunged.  Have a look, see what you think, and if there are any details you think are missing, please let me know. Users/TomGarberson

20100806 19:45:34 nbsp Excuse me?  I made clear on the page that you/your friend/whatever relationship have been treated unfairly by the media and that all charges have been cleared.  Ive already suggested a couple of times that if information on there is incorrect, you correct it.  Rather than being rude, why not actually explain whats wrong with the page as written?

For all I care, you can keep trying to delete the page.  Im not the one whos been restoring it, nor am I the one whos contradicting the legal systems current stance, that Lugos record is clean.  Ive tried to explain to you why people arent OK with it being deleted, and Ive tried to help shape it into something youll find tolerable.  Given your response, though, my time is apparently better spent elsewhere. Users/TomGarberson

20100806 21:00:43 nbsp What you consider a waste of your time is damaging to not only another person but numerous other people.  Since it appear you do not have any children, maybe when you have children you will be more understanding of how far reaching this type of information is and how many people are affected.  Publishing the bias media cover which is not factual regarding the allegation and the jury stats is very unjust.  The real story is in the trial transcripts which I am sure you and everyone else does not want to take the time to read so instead the bias and inaccurate media coverage will continue to be promoted.  During the trials, there was a gag order in place due to the unscrupulous media and all the judges in Yolo County had to recuse themselves due to their relationship with the prosecutor.  Since you went to law school you should understand that he was never convicted of any crime by a jury and he has maintained his innocence.  He has tried to move on with his life and he has been an upstanding citizen and continues to try to be a positive contributing member of society, but this type of publication continues the injustice.  There are many defendants who do not have the monetary resources and the understanding of the criminal justice system to be adequately defended and have life long consequences that are often unfair from this type of situation.  No only that but even though the criminal justice system is supposed to be fair, it has not been to him and to numerous other defendants.  And the media often times publishes what makes a good story and the quotes currently published are inflammatory.  If you think I was rude then I apologize.  And even though this page cannot be deleted it should be for the sake of personal privacy and respect for an individual and their family.     Users/HWestbrook

20100806 23:13:23 nbsp Point One: The subject of the article in question is almost definitely not your child, so I fail to see your point.

Point Two: If it happened, and there is a record of it, and it is public people are going to talk about it.  It is not your place to say that people can not.  Written communication is effectively no different than verbal communication in this regard.  It is almost as if you have come into my home and said You cant talk about this! really loudly over and over again so the people talking can no longer hear one another.

Point Three: Through the miracle of denial I am both Immortal and can not be adversely affected by peoples opinions of me.

And finally, Point Four: If you would like to include the transcripts of the trial or possibly even note some sections from it to draw peoples attention to it you are free to do so.  Adding to the article is fine.  Removing from it is not.   Users/MasonMurray

20100807 05:59:44 nbsp I have not made any changes to the page and dont even know how to do this.  People pay their dept to society and further promoting or publishing this type of information just continues the punishment to them and their family.  Regarding the subject of the article, you have no idea who I am and what my relationship to this person is therefore stating that he is not my child is actually an assumption on your part.  If you have not experienced the criminal justice system yourself then you should not comment since you have no idea how it truly works and the inherent inequity.  Try walking in someone elses shoes.  Yes I do understand the right to free speech but one day you may experience how what people say or publish can damage/hurt/punish you or your family.  Maybe you will have a different point of view regarding your point two.   Users/HWestbrook

20100807 06:47:03 nbsp A few useful tips:
1) To edit the page, just go to that page and click the Edit button up at the top.
2) You can review edits others have made by clicking on the Info button.
3) You can View each individual version of the page (oldest version is at the bottom), or you can select two edits using the circular selectors and use the Compare button near the top of the screen to see exactly what was done with that individual edit.  For example, you can see my rewrite of the page http://daviswiki.org/Robert_Lugo?actiondiff&version214&version112 here.  Removed text is in yellow, added text is to the right in green (youll probably have to scroll right to see the new text, since there are some long links).  Because I moved stuff around.

Im guessing you were confused about my edits, hence our backandforth.  Check out the green text (scroll right) in that link.  I think youll find that I was trying to represent your viewpoint. Users/TomGarberson

20100812 01:51:46 nbsp No, it is not an assumption.  It is an inference, based on age approximations as well as levels of technical sophistication based on age.  Could I be wrong? Entirely possible.  And, as you have not asserted that the subject is indeed your child, I will continue to infer that he is not.  Likewise, you inferred that I have not experienced the criminal justice system.  I very well may have.  For all you know I am posting from a public terminal in a minimum security facility right now.  I once tried walking in someone elses shoes, but they were quite small and hurt my feet terribly after only a few minutes.  Apparently, I also stretched them out because my girlfriend was quite mad.  But thank you for the suggestion Mr. and/or Ms. Hwestbrook.   Users/MasonMurray
  Lemme guess: expensive Manolos?  If they were over $400, thats felony theft.  No wonder youre hypothetically behind bars. Users/TomGarberson
