


iFIX ELECTRONICS is a serious company (you can tell because of the capital letters) that Computer Repair repairs computers and electronics.  They fix certain problems with software, hardware and firmware.  Their store has a couple of really uncomfortable black benches in it (hint hint Sit down Slowly.)

Some of the hardware and services they offer include:

  Apple computer and laptop repair (Mac Pro, iMac, Mac Mini, Macbook, Macbook Pro, Macbook Air...)
  Iphone, ipad, ipod repair
  PC laptops repair and computers repair, virus removal.
  All game consoles: xbox 360, PS3, Wii, PSP, Playstation 3 repair.

Like many local repair shops, they offer free diagnosis, limited to onsite in their case.  They also offer free computer/laptop checkup, flat rate repairs and a 3 month warranty.

Replacing/fixing (not sure which) the DVD drive in an xbox 360 is $50.



  Computer not working?  Check out the  computer repair options in Davis.

The building has been home to several businesses in the past; from oldest to most recent they include: agAccess, JGlenn Gallery, MichelNovelozo Gallery, and Axiom Photo Design. APEX Cycles started off in the buildings basement.



20110122 21:27:47 nbsp Your best bet in Davis for a computer repair. I just got my laptop back from their repair store and its running better than ever. I first contacted HP about my damaged laptop and they offered to fix it for $260! When I saw that iFix electronic just opened in Davis I took it for an diagnosis and an estimate. They asked only $65 dollars for the same repair. The customer service there is fantastic, the price for repairs are low, and the location is superb. So here I am with a laptop that has been reborn and with an extra $200 in the bank. Highly recommend this place. Users/JoshuaBedolla

20110201 12:06:09 nbsp After having a TERRIBLE experience with another computer repair company in Davis, my experience with iFix Electronics was a great delight.  My computer needed to be “overhauled” –had many problems. In less than seven hours it was fixed and working better than ever and for a very reasonable price.  I had some problems reinstalling some of my old programs so I took the computer back the next day.  They solved my problems and charged me nothing.  The staff was very pleasant and helpful!  I highly recommend taking your computer problems to this business! Users/AnnHaffer

20110205 16:33:57 nbsp Problem with this place you can barely understand these guys, so they cant explain anything very well. Very frustrating.  Also, they dont give you an itemized bill, doesnt describe what they did and for how much.  Little shady. Users/DavisLurker

20110208 18:11:43 nbsp Went here with an Xbox 360 with no video output.  He told me that he guessed that it was the video chip, and that it would cost $60 to fix.  A little skeptical, I asked what if it wasnt the video chip?  He graciously replied that if it wasnt, he would find whatever it was and fix it for $60.  It was done in two days! It works great now.   Users/AndrewFerreira

20110219 12:08:34 nbsp I love this new electronics store in Davis! They are computer engineering grads who used to work in San Jose and opened up this business in Davis. They fix Apples, PCs and all kinds of games. I didnt know if they could help me with my TV but Tan was really helpful, eager to please, and he fixed the motherboard for my Samsung TV for $60. Great work at a fair price. Whoever wrote above that they cant understand these guys is cruel and stupid. Also, what kind of itemized bill did he want? I got a professional looking Invoice with estimate when I dropped off my item. I also HIGHLY RECOMMEND this new shop. Welcome to Davis guys! Users/JohnRoyse

20110224 02:36:37 nbsp Hello, ifix, i want to say hi, and welcome you too Davis.  I think it is great to have a repair place for xbox and playstation and some of the other things you repair.  Davis is a great town, with really wonderful people.  My company does only PC repair, and there have been times my clients have
problems with xbox and playstations, and I have referred them to Sacramento, now I will be happy to refer them to a your local Davis business.  You have a great location and your shop looks very nice. I wish you the best of luck here, and I just wanted to welcome you.  Jamie, Computer Doctor.  Users/JamesMorton

20110309 12:50:02 nbsp I sent my boss here with his laptop because we thought he needed a new power jack. They took his laptop apart to replace the jack, but figured out it did NOT need replacing, and worked half the day trying to diagnose what could be causing his powerrelated error messages.  In the end, they werent able to find anything was wrong with it (and neither my boss nor I are ruling out usererror), and they gave him back his laptop.  They didnt charge him a dime, saying we didnt fix anything.  As far as Im concerned, these guys are honest and good at what they do, and provide excellent customer service.  Yes, they speak with accents, but I didnt have any problems at all understanding them over the phone, and my boss had no problems understanding them either. They explained to my boss what was going on at each stage of the diagnosis, and were very patient with his questions. Im so glad to know theyre in town, and would definitely not hesitate to give them a call if we ever needed computer help. Users/yellowsocks

20110312 23:56:53 nbsp On a whim, I took my custom built pc here as I was having heatsink problems.  Tan reapplied the thermal solution and didnt charge me for it.  When I took the thing home, it wouldnt start.  I called them back up and they sold me a very decent power supply for 50 bucks.  While I was waiting, I saw them give very honest estimates to a wide variety of customers.  The prices seemed honest, even a little on the cheap side.  A great place! Users/josephmaki

20110327 17:32:19 nbsp I went here because a friend told me to, BIG mistake. My computers screen was blank  They said the logic board was messed up and it would cost $350, but I didnt think it was the logic board (because the computer worked fine on a projector) so I wanted to go elsewhere, but before I went elsewhere I noticed they broke the back of my computer and when I asked them to fix it they said it was about to break anyways and were going to charge me $60 for fixing it, I refused, they said they didnt even charge me for the diagnostic and everything (well its FREE) and were making me feel guilty because they spent time on my computer and I didnt go to them for the repair. BUT they said they would fix it for free IF I got the repair of the logic board from them  they were just mad I refused to go to them for the ridiculous repair and they were out money. I went elsewhere and guess what? It cost me a fraction of the price and it was NOT the logic board that was messed up. These guys mark their prices up way too high and clearly dont know what theyre doing  you can tell because if someone cant find the problem with your computer, they immediately blame the mother/logic board. Shady business, I thought they were good at first, they seemed honest, and they kept telling me everywhere else would charge soo much more  but once I looked into it, other places are better and these guys are seriously shady. Students beware.  Users/Furan

20110330 21:31:45 nbsp So Furan, where did you end up going? Users/RaeWhite
 And, for that matter, what was the actual problem, and how much did it cost to fix?  That review seems shady. Users/TomGarberson

20110506 10:30:46 nbsp While their service may seem shady to some, the main thing that they have me sold on is next day service. All the other electronics stores I have been to require at least a 3 day wait period. These guys will fix any computer in a day and for a price that is far cheaper than any other shop I have ever been to. Keep up the good work. Users/HarkenBink

20110517 17:48:03 nbsp The real problem was the inverter, not the motherboard OR the screen. I went to Real Computers. I was skeptical at first because the owner works out of his home, but everything in my mind was clear when my computer was fixed for a FRACTION of the cost if i were to have gone to ifix, and Ive told a few of my friends to go to them as well. He even fixed the part IFIX broke. I had an awful experience with IFIX, to me, if it doesnt suit them or if they gain no profit from it, they arent willing to help you out. I mean who breaks a part and then doesnt fix it because the client didnt want to go to them for the repair? I just knew it wasnt either of those expensive parts after talking to a few computer friends and researching it online. I had an awful experience and I just ask everyone to look for more places before choosing one, it may save you hundreds of dollars, like in my case.  Users/Furan

20110722 14:23:51 nbsp Im not mechanically or technologically inclined at all, but the hinge on my computer broke and was causing a chain reaction of damage to my computer anytime I moved it. The guys at iFix were friendly, and it took them about 2 minutes to fix and they charged me nothing. Definitely recommend! Users/CristaThomas

20110823 19:54:34 nbsp Fixed my PSPGos screen without a hitch, and even replaced the cracked cover for no extra charge. All within 2 business days. Definitely recommend it. Users/VijayGanesan

20110919 13:03:11 nbsp I traded my dead Xbox for service on a DS. Seemed like a good deal for both of us. They got an Xbox that they surely repaired and sold. I got a DS that works. Months later, the DS is still working great. And the service was next day, no BS, no hassle. These guys are great.    Users/GordonCaulkins

20110926 13:35:32 nbsp Came in needing three power adapters.  They had all in stock, and even risked losing a sale by recommending that I go through Apple to try to get one replaced under warranty.  Definitely recommend this place. Users/JustinEllerby

20111004 07:33:31 nbsp Amazing!  Finding a reliable, trustworthy and affordable computer service is as hard as finding a good auto mechanic.  Tan and his crew do great work, stick to their estimates, have a quick turnaround time and are generally really nice folk.  I couldnt recommend them more highly!  Now, if I could only find an auto mechanic this good... Users/Marshall

20111214 12:13:25 nbsp I definitely recommend this shop ... they replaced my broken laptop screen in 30 hours at a reasonable fixed price.  They took the time to answer my questions and did an excellent job. Users/DaveSimmons

20120228 12:23:53 nbsp This is a great shop with honest people. I went there today with an iphone that wouldnt turn on. The guy there said it was probably just the screen connector, he took the screen off unplugged and plugged back in some connectors and got the screen to work again. Took maybe like 10 mins, didnt charge me a thing. Great customer service, will definitely be going back. Users/IntegDC4

20120310 11:30:06 nbsp I have mixed things to say about iFix. I came to them because my baby Acer Aspire One netbook took a dive off the bed and stopped powering on. Tan offered me $15 for it and I graciously declined, but did have them get all the data off my hard drive ($50). Upon reinstalling the hardware, they magically fixed my netbook (yay!). I was so excited about the working netbook and the honesty of the place, that I had an impulse buy of a used iPad1 that they had sitting in a glass case ($350+tax). Up to this point, I wouldve given the best review, however, the iPad developed an issue of an intermittent Accessory Does not support charging error and not charging. I had to go to the store at least five times, each time Tan tried something different (originally charger was wrong, the second charger was also wrong, reinstalling the software, deleting some (and suggesting that I delete all) of my apps). Unfortunately nothing worked and ultimately Tan said that the iPad was as is item, so essentially it was my problem and I must be installing messed up apps. I really didnt like that kind of approach especially considering that they sold me the iPad with this issue. Last time I talked to Tan, he said that if I could show him the problem three times in a row, hell take it back and refund my money. But the problem with intermittent issues, is that they do not always show up three times in a row... So I took matters into my own hands, read up on the issue and resolved it myself, but getting an OEM cable for the charger (that turned out to be a problem). Now the thing works. So if you have a computer issue, I think that iFix is a good repair place, but if you need to repair your iPad, take it somewhere else. Users/LinaPlanuty

20120327 20:25:48 nbsp Im so impressed with this place.  First, the place smells nice, like apple cider.  Then the people working there are kind and soft spoken and very skilled at what they do.  And they have candy, chocolate candy, no jolly ranchers or lifesavers!  I just had the glass replaced on my iPhone 3G, and today I picked up my netbook.  I had them replace a few keys and reformat the hard drive.  I am pleasantly surprised to find my netbook is like a new computer.  They replaced the keyboard, so its sooo clean now and when he reformatted the hard drive, he reinstalled iTunes, Picasa, firefox and AVG.  The prices are VERY reasonable, especially considering how convenient they are to just stop into (instead of driving into Sacto for a repair) and how truly skilled the workmanship is.  Im so pleased  Thank you so much! Users/ElisaAllechant

20120517 12:30:50 nbsp These guys are clueless and are NOT Apple authorized repairers. Do not take your Apple stuff here.

The screen on my Apple Macbook Pro laptop wouldnt turn on, I took it here because I was in Davis. They reattached the graphics card to the logic board ($250!!!), which fixed the problem, but it broke again soon after. It was overheating and caused the same thing to happen again. I sent it back, they fixed it again only to have it break again in a week. They gave it back this time, telling me its totally good, I try it and it immediately starts overheating. I start backing up all my data in case it fails and realize that the battery status bar says service battery. I take the battery out and the overheating problem goes away.   The computer runs great now.   I just need to get a new battery, but I wont be using i(kinda)Fix Electronics.   I think their use of Apple logos is misleading as well, and should at the very least not be used at the top of this page.

They are NOT an Apple authorized repair center.

 Users/PxlAted

20120522 14:10:02 nbsp This place was spectacularly helpful. I was working on a project for an aquarium and, after several attempts with Radioshack, iFix was able to help me. The first time was free, testing a few things and replacing a few screws for me for free. The second time was a very reasonable price for a moderately difficult fix. Their customer service was great and even though they spoke with thick accents and among themselves in front of customers in what sounded like Vietnamese, they understood perfectly and were great communicators. Id definitely come back! Users/GAvila

20120531 00:16:07 nbsp They just saved all the data from my iMacs failed harddrive; installed a new hard drive & more RAM, reinstalled my software, and transferred all my recovered data for MUCH less than the Apple Store would have. On top of that I didnt have to drive to Sacramento!!! I couldnt be happier with their service. Users/Kadegge

20120610 23:12:50 nbsp Another downtown Davis business to love. I brought my laptop in for a bizarre repairmy cats had ripped several keys off. Several friends assured me this was not a fixable problem, that they had had to trash their damaged laptops. After being tired of managing without the keys, I decided to give iFix a try. They did it in an hour for $30, cleaned my machine up, and it works perfectly, as good as new! Thanks! Users/NicoleR

20120621 11:21:43 nbsp This place is always great.  I went here because my new acer aspire laptop battery was not being detected.  They flipped a switch inside the computer allowing the battery to operate.  I also had an ssd/ram I was hoping to install and they installed it, letting me watch so i could do it myself next time.  And the price...free!  I also was able to trade them some ram for ram that would actually work in my laptop.  Great Place! Users/RobbyZimmerman

20120807 16:46:19 nbsp I was having trouble with my laptop so I took it in for an estimate. They did a hard drive test to rule out the cause at no charge. I opted not to get the proposed repair (about ready to upgrade anyway) and they were nopressure about the whole thing. Great guys. Users/JamesVitiello

20130112 20:04:37 nbsp I am the owner of Cybershield, the computer repair shop which was on 3rd st. My daughter had dropped her iPhone 4S late yesterday and I was researching options to fix it. I decided I did not want to wait a week or more shipping the phone out or doing it myself waiting for the parts to come in. I remember this computer shop opening up around the corner from my computer shop and their sign stating they fixed iPhones. I called them Friday at 5:45PM asking if they could fix the phone. They said yes and that it takes up to an hour. I asked if they would be willing to try and fix it tonight and they said yes. We raced down there and got a bit stuck in Friday traffic. We got there later than expected but the courteous staff said it was ok when I called them with an update. We gave them the iPhone, went to Panera Bread across the parking lot and ordered a small meal. As we were finishing our meal they said the phone was ready. I am glad they were willing to work a little after closing hours and accept the repair job so late in the day. I expected a good company to do that as I used to do it for the students myself. We are very happy with the repair and the polite staff.  Sergio Users/Cybershield

20130129 15:19:08 nbsp AVOID!  These guys are completely racist and unprofessional.  I dropped my Playstation off to get fixed last week.  Apparently, over the weekend, their store was burglarized when they failed to lock their door after close of business.  My Playstation was among the things stolen. They called me and not once, but twice, accused me of being the one to break into their store, threatening police action.  I eventually straightened things out, but never once received an apology for the baseless accusation (I looked like the guy from the video tape they said making a connection because both the guy on tape and I are Hispanic).  They did not apologize for accusing and threatening me, and then still charged full price for the repair.  AVOID!!!! Users/ChristianAcevedo

20130604 11:15:57 nbsp My experience with Ifix was very positive. My laptop (Acer Aspire 5742) broke just before a string of deadlines and having tried everything I thought I would have to buy a new one. I took it to these guys, who had opened early. They are easily accessible and friendly, didnt ask any patronizing questions. They called me just 3 hours later and told me there was a short in the motherboard. It would cost me $240 total (to replace the motherboard and labor, this is reasonable) and take a week. I could pay $75 for firstclass shipping but he advised me not to, as it wasnt covered by them and would probably not be any quicker. It wasnt! They called back 4 days later and it was ready to pick up; he also answered all the questions I had about laptop care clearly. Moral: dont spill liquids on your laptop but if you do, go to these guys. Users/AaronP

20130920 21:50:56 nbsp I highly recommend iFix. Our 4 yr old iMac started shutting  down with error messages that according to Apple Support indicated serious issues. iFixs initial estimate when I took it in last week was that the repair would cost several hundred dollars, which I agreed to pay. They called today and said it was ready for pickup. To my surprise, they determined that the repair was considerably less involved than anticipated. The final charge was a fraction of what we expected to pay. I am clearly a novice when it comes to computer issues, and I appreciate the integrity of a company that does the right thing for their customers.
 Users/JGQ

20131003 12:41:48 nbsp I took my dead Dell tower to iFIX and they replaced the power supply unit. When I booted it up at home, there was a strong burning smell so I took it back in. They said there was nothing wrong (I could still smell the burning). One week later the new power unit cooling fan motor started making a noise (burning smell?). iFIX replaced the defective power unit under their three month warranty. Four months later this replacement power unit cooling fan started making noise. iFIX refused to replace this faulty unit because it failed one month after their warranty period. I reminded them they had installed two faulty power units in a four month period. They still said it was out of warranty. Bad replacement parts and bad customer service, find another business to fix your computer.      Users/DavidWhite

20131204 13:23:46 nbsp Ive read many of the posts here, and I am in total agreement with those who are happy with iFIX!  Regarding those who are not, Id like to say something I consider very important:  these guys are the best in Davis, no matter what your experience.  Why do I say that?  Because I had a experiences with some of the repair people in Davis, and with one of Davis computer people in particular, and it was HORRENDOUS.  A total Con job:  watch out for fast talkers who promise to do it all quickly and who claim that everyone else is a rip off:  its the fast talker thats the real rip off.  These guys at iFIX, in stark contrast, are the real deal.  The fast talker Im talking about doesnt even know what s/hes saying. This person actually makes up lies right there on the spot.  Just to hook ya, especially if youre desperate, at the moment.  But you can be sure that if s/hes talking, its a lie.  Basically, Id say that if you have any minor problems or inconveniences with iFIX, be grateful that youre not getting INTENTIONALLY ripped off by The Con Artist.  However, Ive found iFIX SUPERB, CONVENIENT, EXPERT, FRIENDLY, REASONABLE, CONSCIENTIOUS AND RELIABLE.  None of these qualities apply to the particular competition I have in mind.  I wish Id seen iFIX first.  But I was mistakenly deluded into thinking that they wouldnt know that much about PCs, since they seem to specialize in Apple products.  WRONG!  These guys KNOW PCs!!  Theyre awesome.  Seriously! One time, they even fixed a couple of things that were wrong with my PC, on the spot, in the store, and didnt want to charge me!  The Con Artist had tried to fix it and couldnt, the Con Artist charged me an arm and a leg for failing to fix it, because he spent so much time trying.  (I ended up paying iFIX about $45 anyway, it was all the change I had.  I didnt want to use my Visa card, when they didnt even want to accept payment.  The Con Artist would have demanded triple that, and would NEVER have fixed the problem.  Seriously:  compare and contrast!!) Users/skywords
