Isaac Skinner Chiles (18291874) was born July 9, 1829 in Clark County, Kentucky to Azubah Skinner Chiles and Joel Franklin Chiles Sr., brother and sisterinlaw of Joseph B. Chiles. Young Isaac, aka Ike, left school at 14 and went to work at his fathers warehouse near Independence, Missouri on the Santa Fe Trail. The Chiles family had migrated to Missouri from Kentucky and operated successful farming operations and business ventures in Jackson County.

By 1848, the California gold rush had intensified and Colonel Joseph B. Chiles returned to bring family members and fortune seekers to California. Ike, now approximately 18, spent the winter of 1847 planning with his uncle the trek to California. By 1849 or 1850 he had arrived and set to work earning a living as a telegraph operator for the Sacramento and Napa Stage Line, and helped his uncle run a ferry across the Sacramento River in West Sacramento Washington Township. He later became superintendent on the Jerome C. Davis farm and by August 26, 1851 was known to be living on Putah Ranch, near Sacramento. By September 1854 he was purchasing cattle in Sacramento.

In 1862 Ike had saved enough money to purchase 3200 acres from Gabriel F. Brown for $2000 (see Mace Ranch). Gabriel, married to Joseph B. Chiles daughter Frances Chiles, originally purchased the tract of land from his fatherinlaw for $5000; this tract was part of the original Rancho Laguna de Santos Calle purchased by Colonel Chiles from Marcos and Manuel Vaca on November 8, 1850. Ike established himself in Davis where he farmed cattle, hogs, and grain before marrying Bridgett Dee, a native of Ireland and devout Roman Catholic, in January 1863  together they had just two children: James Franklin Chiles and William Dee Chiles. As Isaac prospered he took an active interest in the development of Davisville and purchased his first business site in 1869, eventually acquiring about twelve city lots. He was also an officer in the Sacramento Society of Pioneers.

Isaacs wife Bridget was a community stanchion as well, helping organize the Spiritual Organizations church in Davisville and deeding an acre of land to Bishop Alemany on June 7, 1880 for use as a Catholic cemetery. This and other lands adjoining the Davis Cemetery were donated to the community for a cemetery to be used by the Chiles. Isaac Skinner Chiles was among the Yolo County landowners who granted a quitclaim of 100 foot rightofways to the Train Station California Pacific Rail Road in 1868; a marker at the crossing on Road 103 once denoted Chiles Station before being stolen by unknown individual(s).

Isaac Skinner Chiles died on June 5, 1874 at the age of 45, and the Sacramento Society of Pioneers lamented, Be it resolved, that in his demise this society has lost a worthy member, society a useful citizen and his family an affectionate protector. His brother, Phineas, came out to help Isaacs wife run the Chiles ranch and married her within a matter of years; the couple raised Isaacs boys together until Bridgets death.
