These are reviews of Jack Lin, DDS, of Davis, California, when he took over the practice of James Meinert, DDS in the middle of 2007.  Dr. Meinert returned in early 2008.




20070718 11:59:02 nbsp I went to him yesterday. He is not as warm and fuzzy as Dr. Meinert was, but his confidence and efficiency made me think that he clearly knows what he is doing. Users/TomHinds

20070822 14:32:14 nbsp I recently went to Dr. Lin ,while the staff was nice enough I had difficulty understanding Dr. Lin. I didnt like all of the consent forms that were from Western Dental.  My appointment took almost 2.5 hours, for just a cleaning and exam, most of that time was waiting for the Dr. to come in for the exam. I dont recommend Dr. Lin the treamant he tried to push on me as well as some credit card to pay for it. I felt like I was at a high pressure car dealership. I went to Dr. Pisciotta and the treatment that Dr. Lin recommended was excessive and unneccesary. It was worth the extra money to get the second opinion.  Save your money dont go to Dr. Lin.
 Users/Calli

20070822 19:14:24 nbsp I went to see Dr Lin for the first time yesterday, and I was told I needed all these crowns and a couple fillings done. I dont understand how all of this came about just six months after seeing Dr. Meinert. Seeking the opinion of another dentist isnt a bad idea. Users/jess

20070831 22:12:41 nbsp This is the worst dentist ever. He has caused me much pain and suffering. After giving me two fillings I had to come back because they were hurting so badly. He redid them, only to knick my lip which needed stiches. Now my teeth hurt even worse than before and my lip is messed up.  Users/Kristin

20070911 09:18:53 nbsp I loved Meinert, but Im afraid that I cant say the same for Lin. When I complained of tooth pain, he decided that there was a problem with the chippedtooth filling I had had just 9 months previously and said he had to redo it with a more expensive filling. Well, now thats done and my tooth still hurts and he says that maybe I need something done with my root (Its really hard to understand him). Well, now Im also flat out of my dental insurance stipend thanks to that unnecessary filling. Oh yeah, and they charged me for 8 xrays when I had only had one. Users/TawnyMata

20070914 10:23:24 nbsp I went to Meintert and thought he was great.  My husband went just after the switch and had a terrible experience with Lin.  Also, hes supposed to be a delta dental provider, but he charged us for things that he didnt have a fee on file with delta dental, meaning that we had to pay out of pocket for procedures that would have been covered had he had his fee on file.  Very frustrating.  Not planning on going back. Users/AcMach

20070925 12:39:26 nbsp I had an appointment with Dr. Meinert. I was not informed that he was no longer my Dentist. It wasnt until I started asking questions about dental conditions related to my health that I discovered Dr. Meinert was not the Dentist overseeing my treatment. This was highly irregular, I would say borderline unethical, and absolutely not appreciated by this patient. Combined with Dr. Lin failing to answer or even respond to a few questions about nutritional defects and dentistry and misunderstanding other questions about the health of my teeth, I will not be returning until I have interviewed other dentists to determine what the Davis area has to offer. Call and ask to talk to the Dentist.  Users/BrianDilkes

20071009 17:20:19 nbsp I went to see Dr. Lin a few weeks ago.  I thought he was great He gave me a really nice filling and good advice about my teeth.  Also, the least painful novacaine shot Ive ever had. Granted, I havent gotten my bill yet so I dont know whether that all worked out o.k., but I would recommend him. Users/monkeybanana

20071011 12:41:41 nbsp I had my wisdom teeth removed a couple weeks ago. Ill admit, after reading all these negative experiences with Dr. Lin, I was kicking myself for not getting it done when Dr. Meinert was still there. I was really apprehensive about the procedure, but it ended up being great. It was actually pretty painless and Dr. Lin was great with explaining the procedure as well as my aftercare. It ended up taking only 45 minutes! Also, had a cleaning here recently and the hygeinists did a thorough job.
These reviews also got me worried about my pocketbook being taken advantage of, but I got my bill and it was exactly as wed discussed. Totally affordable for having all 4 wisdom teeth out.
I just thought Id leave a good review to offset some of the not so good ones. Ive had much worse experiences, like with University Dental... Users/IzzaSwiech

20071018 14:53:48 nbsp After going to Dr.Lins office I wonder how a dentist can promote good oral hygeine and yet smell like an ash tray. In addition I was sickened by the way he yelled at his employees right in front of me.  Despite all of this I had to get a crown and decided to give him a chance. I should have gone with my first impression. After four more visits my crown still didnt fit and I now need a rootcanal. Which came with a big out of pocket expense. Courtesy of Dr. Lin. Users/jessica2204
  Note that the above account was created to leave this comment and has not been active on the wiki since.  Likewise with Cali and Monkeybanana

20071210 17:10:22 nbsp NOT RECOMMENDED. The office gave me major crap. They called the day before saying that I made an appointment the next day. When I told them that I cannot make it and I need to reschedule it, they wanted to charge me $35 since they did not have a 24 hr advance notice. That is even when I want to reschedule it. I have never received a postcard reminder about it (which they always sent when its with Dr. Meinert), and all my other doctors call for reminders more than 24 hours before the appointment. Its quite clear that theyre out to get you for the $35. I received the reminder call at 4:45 PM the day before my appointment??? Users/youkai
 I dont have much sympathy for this complaint.  The call is a courtesy; you should really be responsible enough to write down your own appointments and keep them, or reschedule them if you cant keep them.  And they certainly arent going to make any money by having people miss their appointments and charging them $35.  They are losing money when you miss an appointment because an appointment with a dentist costs more than $35.  That being said, it is somewhat foolish of them not to send an earlier reminder, because they might be able to find someone else to fill the slot, a situation that would be better for everyone.  An alternative method of dealing with this dentist (if you otherwise like the dentist) would be to call them and suggest politely that you would find it helpful if they gave earlier reminders.   Users/CovertProfessor
