The firing of Davis High Girls Basketball Coach Jeff Christian has been covered ad nauseam in The Davis Enterprise during January and February 2011.  Not many details have been given about the reason for firing the sixyear coach in midseason, but there are allegations of FBombs dropped by the 2 star players, sisters Malika and Khaliya Wilkins, during a team meeting, and disciplinary actions taken for attending a party at which drugs and alcohol were present (http://davisvanguard.org/index.php?optioncom_content&viewarticle&id4075:districtissuesstatementaboutcoachfiringthatanswersfewquestions&Itemid120 article link).  None of this seems to explain why Jeff Christian was fired and why the Davis School Board has been so tightlipped about giving any explanation.

Or, possibly, the situation IS largely covered by the statement released by the School District, which included this:
Mr. Christian was released for past and present behavior patterns that do not meet DJUSD standards for dealing with students and parents; including but not limited to disparaging two high school students in the newspaper by announcing their private discipline and dismissal from the team without first notifying them or their parent(s). (see the Vanguard link above for the statement)

The failure of the Davis School Board to appeal to the concerns of citizens who want a fair hearing for Jeff Christian (or, perhaps, their steadfast guarding of confidentiality in personnel matters) is now causing a rift over the upcoming parcel tax increase to fund DJUSD operations, Measure A.  Effectively, many are expressing a vote of no confidence in the board by pledging to vote no on Measure A (Davis Enterprise, 2/20/11). Trustee Sheila Allen is quoted in that story saying, I am very sorry that because it is against (state) education code and employment law I cannot share the particulars or directly respond to the impassioned people that come to speak at public comment during school board meetings.

There are rumors spreading throughout town that there is a different reason for disciplinary action against the girls, which better explains their mothers response, the School Boards unwillingness to give an explanation for the firing that critics find satisfying, and which seems to vindicate Jeff Christians dismissal as a case of politicalcorrectness gone awry....Of course, it should be noted that this comment was posted by an anonymous editor referring to anonymous rumors, so the veracity or usefulness of this part of the Wiki entry should be considered questionable.


20110222 15:47:44 nbsp First up, I have no actual knowledge of anything that has gone on, other than what is in the paper, but have a few thoughts...

The administration of the Davis schools hears constant whining and complaining from parents about every single thing that goes on in all of their schools, so Im inclined to accept at face value the statement about past and present behaviors.  A single parent complaint would be going a lot of nowhere.  Should that statement have been made straight up at the time?  probably.

Second thought is I dont want to know any more than that.  When I first heard about this my imediate thoughts led down some paths that I will not repeat here.  Users/RocksandDirt

20110222 16:55:45 nbsp Not much of a scandal of import for the community at large. Viewing the recent changes was the first I have heard about it here on the wiki and I am still not interested now that I have found out about it.  So a coach was fired... big deal. Now if he had been released due to some type of predatory or inappropriate sexual conduct with students THAT would be something of importance for the community to be made aware of, other than that it is just a smear on the coaches online presence with no value at all other than noting he was released from his position. Not relevant for the wiki imho. Users/WesP
  This has been all over the Enterprise and the Vanguard and you can bet a lot of Davisites, especially those who have students in the HS, are talking about it.  I would edit the page and try to fill things in, but I just dont have the time to go back over everything Ive read and I dont want to make a mistake.  But the rough idea is that the coach may have done something wrong, either by letting the girls go or by talking to the media about letting the girls go (violation of privacy), he may have been fired without going through the proper process (and there were a number of people involved there), plus there is the behavior of the girls (and there are a lot of stories flying around about what transpired there).  Also, now some people are trying to say that if the coach doesnt get reinstated they wont vote for the tax increase for the schools (because how can they trust the school board with their money, they say), and that has been proposed in a serious way, in print, by a number of people.  Finally, there is a threat of a lawsuit from the coach and the expense that that would cause.  Sorry, I typed this fast and may have mucked something up since, again, I am going from memory, but basic point is that there is a lot of scandal to go around and a lot of possible downstream consequences for the school, coach, and girls.  Users/CovertProfessor
  http://daviswiki.org/Users/StevenDaubert?actiondiff&version27&version16 The rumors.  With all that the word rumors implies.

20110324 16:32:33 nbsp So..if he didnt have sex with any of the girls, why would anyone care? Was HE doing drugs? Was HE at this party? Who really cares?  Users/JoshLawson
