
Chief Jim Hyde was the Police Chief for the Davis Police Department from 2003 to June 2006. The ninth Chief, he was preceded by Martin C. Ruiz and succeeded by Landy Black.  Citing difficulties with the Davis Human Relations Commission as the reason, Jim announced his resignation and acceptance of a position as the Chief of Police, City of Antioch on 6/13/06. http://davisenterprise.com/articles/2006/06/14/news/200new1.txt Enterprise Link

Around the time of his resignation, members of the Human Relations Commission were critical of Hyde because of his role in the Halema Buzayan case.  The Humans Relations Commission also recommended the creation of a Police Review Board.

Since leaving the Davis Police Department, Hyde has made several harsh criticisms of his former colleagues. According to a http://davisvanguard.org/index.php?optioncom_content&viewarticle&id2790:formerchiefoffersinsultingdepictionofdpd&catid54:lawenforcement&Itemid87 Davis Vanguard article, he compared the Davis police force to Reno 911 characters, stating they were dysfunctional, used obsolete equipment, and often made up statistics.

In total, Hyde has been named in four federal civil rights lawsuits.

His previous law enforcement assignments included Homicide, Career Criminal Apprehension, Gang Unit, Narcotic/Gang Task Force, SWAT, and Patrol with the Sacramento Police Department. Chief Hyde has a Bachelor of Science Degree in Criminal Justice from the University of South Dakota, a Masters Degree in Clinical Psychology from the Professional School of Psychology, Sacramento. He is a graduate of the Senior Management Institute for Police sponsored by the Kennedy School of Government, Harvard University and the Police Executive Research Forum. Chief Hyde is a certified Executive Coach and he is also a doctoral student studying Organizational Psychology.

Ive talked with Hyde on a couple of occasions, notably when I was setting up a place to meet him. The man just couldnt get a good photo ever. evar.  Users/StevenDaubert


20060614 05:21:57 nbsp Word has it that Hyde is resigning Users/HenryBianco

20060614 15:17:26 nbsp The City of Antioch website shows that the application period for the Chief of Police closed in early April and initial interviews took place the next week.  This was in the midst of the HRCs meetings regarding forming a citizens police overview commission.   Users/SharlaDaly

20060614 15:40:04 nbsp Salary Ranges for Police Chiefs. In Antioch the range is $130K to $158K. In Davis the range is $103K to $125K. The Chief would like us to believe he was driven from town by the HRC. Do Davis Police Officers ever tell the truth? Users/SteveHayes
  Come on, do you really have enough evidence to make this strong an assertion about Hydes motives? Users/KenjiYamada
   20060614 20:20:11 nbsp I do not have enough evidence? We are aware of two possible motivations for why he wants to leave Davis. On the one hand there is a 30% salary increase which is worth at least $30K per year. On the other hand Mr. Hyde was annoyed by a group of people who challenged the actions of his organization. Guess which factor really caused him to leave Davis. He was going to leave regardless of Davis politics. It was unfortunate that he chose to take the low road on the way out as he cast out a couple of cheap shots. Users/SteveHayes
     I think youre significantly downplaying the hostile environment for police in Davis.  Ill be the first to agree that the departments actions and poor response to criticism arent helping that situation any, but I really dont see how you can know with so much certainty that Hydes reason for leaving was just the money in Antioch and the controversy here in town was only a false pretext. Users/KenjiYamada

20060614 16:36:09 nbsp WOW Users/JamesSchwab

20060614 21:23:33 nbsp Well, problems with the HRC would explain a desire to move, considering the controversies lately. Its probably a combination of location, HRC, and pay. Users/KarlMogel

20060615 07:03:48 nbsp Granted I have reason to be biased in this, but I think Steve is probably closer to being correct.  Hyde had a chance to move on to a bigger city, with more crime and a larger police force.  He probably was tired of the criticism, which he really did not handle all that well and he made the situation much worse with his handling of it.  But in the end, he took the highly unusual parting shot at the HRC and my wife, which served as a selfserving excuse that will if anything inflame polarization within this community.  That certainly is not going to help this situation. Users/DavidGreenwald

Sharlas comment removed. Decided I didnt want to discuss this in this venue.  Needs face to face discussion.  Users/SharlaDaly

20060615 08:32:14 nbsp Sharla: First of all, until there is an actual ombudsman, there is no system to steer people into.  Second, the HRC has not touched this issue as a body since the February 21, 2006 meeting when they presented their report on the police oversight committee.  So Im not exactly sure what the HRC has done to warrant your response. Ill also add, following what was said yesterday, Hyde did not give the HRC any choice.  They tried to meet with him, found him very defensive and unwilling to acknowledge any mistakes, this was mainly dealing with the Buzayan case, but there were actually incidents last summer predating that.  The family themselves tried to go through the system, were rebuffed, Gina Anderson turned the investigation of Ly into another investigation of Halema and Najat.  Hyde withdrew, refused to meet anymore and things deteriorated.  There was no willingness to reach common ground on the part of the Chief, and as a result we have had the drawn out battle for the last year.  The HRC was put into this situation because there was no other outlet.  Dr. Buzayan went before Council the night after the incident, but Council didnt act.  It was only then that he went to the HRC who did act.Users/DavidGreenwald
    What David said.  Dr. Buzayan made it clear on numerous occasions that all he wanted was for the charges to go away and the police department to apologize to him and his family.  He specifically stated that he did not want to make money on a lawsuit.  It took a judge to call bullshit on the charges and Jim Hyde stood firmly behind officer Ly and his conduct even after the case was tossed.  As to the HRCs role in the Buzayan incident, I think it was minor to none.  At the one meeting I attended, if anything, Dr. Buzayan seemed somewhat uncomfortable with Cecilia Greenwalds overall position.  Personally, I got involved in the Buzayan incident because a good friend in Sacramento told me about it, and indeed, most of the people at the meeting I attented were of the Muslim faith and were of Northern Africa extraction and no connection with to the HRC.

   Another thing that Id like to point out is that many people, even before the Buzayan incident, considered Davis police to be unpopular and detached from Davis community values.  If there was any other flaw of Chief Hyde it was not addressing this issue and instead focusing on stuff like boost the use of technology to enhance police work. Users/GrumpyoldGeek

20060615 16:30:55 nbsp I say good riddance. Users/PaulThober

20060615 17:19:52 nbsp Can someone please explain to this poor noob about the HRC complaints, or provide a link to a place that can? Users/CharlesGeorge

20060615 18:08:40 nbsp Okay. The Human Relations Commission is a group of people appointed by the City Council to criticize other people. Arguably, this is useful, but the Police Chief got annoyed with it so he quit when another city offered him more money.

Also, the Davis Police Department Davis Police and the Human Relations Commission both include jerks as will any group of people. The social and political power that these groups have means that the jerks often get to be in the newspaper when they fight with each other. It was his duty to fix what problems the police department certainly has, so he failed, but I think quitting is understandable given the offer of more money combined with the uncooperative criticism, cheap shots, and Law Office of Dean Johansson fight the man, cops are pigs attitude the human relations commission and Police Misconduct Stories others often took. Users/NickSchmalenberger

20060615 19:33:27 nbsp Also, Hyde was looking to leave a year ago before any of this started. Users/DavidGreenwald

20070613 16:07:30 nbsp As an Antioch resident I thank you people in Davis very much!  Jim Hyde is the BEST police chief this city has had for a long time.  The previous chief denied that we had a problem with crime, while Chief Hyde is acknowledging that there is a problem and working to clean things up.  Hes not afraid of hard work and he supports his officers when they are in the right and we appreciate his efforts.  So thanks for your fear of cracking down on crime and false accusations of racial profiling, your loss is our gain!  After all, you seem to forget that this girl committed a FELONY hit and run, so just offering to PAY OFF the victim and fix the car is not going to make a criminal act go away! Users/PLM
    HAHAHAHA! You are lucky to have Chief Hyde since he got his PhD on our money and time. The Chief only worked half the hours we paid him to work, the rest of the time he spent getting his PhD. I also dont understand your defense of him, the community did not accuse him of racial profiling, they accused him of not dealing with the officers that were accused of racial profiling. Guess he was too busy getting his PhD on our time and money. Wow, a police Chief who thinks crime is a problem, what a novelty, that education did him well.Users/JamesSchwab
    To add to James point.  Your facts are wrong as well.  The girl was charged with a misdemeanor not a felony.  The case was dismissed.  Now you call that paying off the victim.  Actually the judge ruled that the purpose of a misdemeanor hit and run is to insure that people will take responsibility for the damage done to vehicle.  The point at which the victim accepts a civil resolution, the crime is nulified in a noninjury situation.  Ill be interested to see your opinion of Hyde in a few years, a year into his tenure in Davis, most people thought that Hyde was very good.  That changed though over time.  Perhaps hell have learned from his experience here, but until you get the first real flash point issue, its hard to judge anyone. Users/DavidGreenwald
