## photo of yardsign

http://Joe4SchoolBoard.blogspot.com Joe Spector was a candidate for the School Board in the November 2007 Election.  He failed to win in the 2007 run.


 Election Materials 



20071003 22:34:37 nbsp PLEASE DO NOT ELECT THIS MAN TO OUR SCHOOL BOARD!  I have the misfortune of knowing him personally.  Its bad enough that hes allowed to practice in this district as a school psychologist.  Please vote for sane, stable people to guide our childrens education.  I could list a number of examples as to why hes considered to be mentally unfit to practice, and certainly to serve on our school board. Users/NiftyWitch

20071004 09:21:54 nbsp NiftyWitch, your comments would carry a lot more weight if you: 1) list facts and examples of Mr. Spectors mental instability rather than simply claiming that you could, and 2) do not post anonymously.
You are subjecting Mr. Spector to serious personal allegations, and it is somewhat unfair for you to hide behind anonymity as you do so.  He has the right to defend himself against specific accusations and specific accusers, neither of which are being divulged here. Users/MattJurach

20071004 09:45:00 nbsp I will be more than happy to do so, as time permits, and as comments stop being deleted.  Censorship, anyone?  And a discussion of my choice of user name is currently taking place on my user page. Users/NiftyWitch

20071004 18:36:05 nbsp I have met and spoke with Joe Spector and I endorse his candidacy. I am going to have stand by my old Sunday school teacher, Mr. Jurach, and say that Miss Witch, if you wish to make allegations do so in the open. If you really believe in something let your real name back it up. How we to trust you Miss Witch? Nifty witchcraft sounds like the devils work  not necessarily the best endorsement of any side of an issue. Joe Spector is a good guy. He has worked in the schools for a long time on a professional basis. He is the most qualified guy in my book. Users/RobRoy

20071005 21:45:13 nbsp Okay, heres a few items to start the list.  I probably wont be able to include it all tonight due to time constraints.  And again, this is behavior and circumstances Ive personally witnessed.  This is a man who supposedly works for the welfare of children, yet has raised his own family in egregiously filthy conditions.  His previous residence took a crew of 35 people almost a week to clean, just to get it minimally fit for human habitation.  At least two large garbage cans of toxic waste had to be removed.  Piles of rat and mice droppings everywhere (especially in the kitchen cabinets, with the food and dishes).  The garage and yard were filled with debris, which he made minimal attempts to clean up, yet refused the family that was renting the house to remove the trash themselves, as he insists on compulsively collecting the crap and rarely throws anything away.  In addition to the filth level, he apparently has no issue with his family living in a house thats falling to pieces.  He pretty much had to be threatened with legal action to repair the bathrooms, as water was coming through the dining room ceiling and the downstairs shower wall was being held together with duct tape.  The solution to clogged water drains is to divert the waste water to flow out into the back yard.  Containers of rancid water sitting everywhere, breeding mosquitos.  The piles of garbage provided an ideal habitat for rodents.  Fences rotting and falling over, creating a safety hazard.  His rationalization is that his familys willing to live that way, so why should anybody else have a problem with it?  While the ongoing soap opera that his tenants were going through provided much comic relief for the neighborhood, it really was a pathetic situation.  Sellers of property in the neighborhood that he moved to actually had buyers back out on them, once they found out Joe had moved into the neighborhood.  Now think about it.... are you comfortable having a man in a position of influence over our kids, who apparently has such little concern for the health and safety of his own!  And this isnt all... you wanted specifics, so they will be posted.   Users/NiftyWitch

20071005 21:50:14 nbsp RobRoy:  Yes, I follow a nonChristian spiritual path.  witchcraft sounds like the devils work??  Please.  This is the 21st Century, and its common knowledge that theres no connection with stereotypical depictions of Devil worship.  To make such a statement indicates to me.... well, lets just say Im not surprised by your support of Mr. Spector.  Thats all Im going to say on that particular matter, as I dont want to derail this into a pointless religious debate. Users/NiftyWitch

20071005 22:01:18 nbsp Okay, Ill make time for one more.  Mr. Spector is a school psychologist.  As for his performance and behavior on the job, lets just say Ive witnessed several instances of district employees expressing ridicule and disgust.  But the most serious issue I know of is this...  Medical and mental health records are, by law, required to be stored behind 3 locks.  For example, a file cabinet, within an office, within a building.  Having personally viewed the piles of debris strewn about his property, I can verify that at the time, it did contain files and paperwork with information about the students hes worked with.  A gross violation of confidentiality, as well as the law.  Is this someone you want serving on your school board, that would treat the law and rights of our students with such carelessness?  Okay, I think thats enough food for thought to give you all tonight.  Sometime over the weekend, Ill try to stop by and give you the saga of The Bushes (not the Presidential family; actual bushes). Users/NiftyWitch

These accusations, IMO, are bordering on libel. Perhaps a talk page should be started.
Users/DonShor

20071008 08:55:28 nbsp In order to qualify as libel, the statements made would have to be false.  If you dont want to take my word for it, take a trip down to his old neighborhood on Concord Place and talk to his former neighbors.  Im sure his new neighbors could also give some insight, but Ill be fair and not state his current address.  I havent had the time to come and and provide more of the information I promised, but plan to do so hopefully in the near future.   Users/NiftyWitch
   Dont worry about it.  Unless youre actively trying to mislead it is not libel, and you are perfectly fine if you believe what you say to be true (it could even be false, you just have to think it is true).  Disclaimer: Im not a lawyer, but baseless claims of libel gets kicked around enough to warrant libel an entry to counter such claims and clarify what libel is and isnt.  Dont worry about it, and feel free to write up the story of the Bushes. Users/JabberWokky

I said bordering on libel. Niftywitch has made a specific charge of professional misconduct.
Just for the record, I neither support or oppose Joe Spector for school board. But I am curious as to why the condition of his house and yard is (1) any of our business, and (2) relevant to his qualifications for school board.
In the course of my career I have been in hundreds of back yards and homes in Davis, and seen some amazing things. Ive also observed neighbor disputes, and recognize that in most cases neither neighbor is perfect. People have different standards for their home and yard care. Nothing you are describing amounts to little concern for the health and safety of his own children.
All we know is that you think hes messy and you think his neighbors didnt like that. How about discussing his positions on school board issues? Users/DonShor

20071027 11:34:19 nbsp Sorry its taken so long to get back here and respond/update.  Weve had two deaths in the family, so obviously this has taken a back seat.  DonShor, this is not just a matter of a messy house and yard.  This situation leaves messy far in the dust.  If you even bothered to read through all the info, youd realize were talking CPSinterventionlevel neglect and safety hazards.  Also, were talking about ethics violations (in breach of confidentiality).  Oh, and speaking of ethics... am I the only one that noticed the article in the SacBee about DHS students being required to stuff envelopes for Joes campaign during class time?  Anyway, I had promised to come back and explain more about the bizarre behavior thats been witnessed, supporting the claims of mental health issues.  Its really been a struggle to figure out how to present this information; its hard to convey just how disturbing this is when its observed in person. The most common example given by his neighbors is his obsession with bushes.  Yes, bushes.  The entire perimeter of the property is planted in shrubbery, which in itself isnt weird. Whats strange is the high level of protectiveness and anxiety displayed toward these bushes, and the refusal to perform (or allow to be performed, except under duress) any proper maintenance of them.  He wants them overgrown, because he likes to (in his own words) pretend hes living in a forest.  The city had to force him to cut them back from the sidewalk.  Theyd grown so huge, the upper branches were falling over into the neighbors yards, causing a risk of damage and injury.  The overgrowth collected piles and piles of the garbage that collects in the yard, and also provided an ideal haven for the rats infesting the place.  Even the bushes and trees that were dead (some for at least a couple of years), werent removed, because they might magically be resurrected.  Any attempt by anyone to mitigate the nuisance would be met with a level of hostility that is just unreal.  Hes yelled at the neighbors for cutting back the overgrowth on their own side of the property line, because... get this... they were lowering the oxygen content in the air around his house.  When the cable company had to replace the underground lines in his front yard, he freaked out, because he was afraid theyd damage the bushes.  The place is infested with rats, covered in trash and toxic materials, water is coming through the dining room ceiling, the shower walls are falling apart, the fences are falling over, but God forbid somebody should cut a branch on his bushes.  Like I said before, its really hard to give a clear picture of just how abnormal this is in just a written paragraph. But if you dont want to believe me, again... go talk to the neighbors whove had to put up with him for so many years.  The stories I can tell are just the tip of the iceberg. Users/NiftyWitch

20071027 19:08:56 nbsp ...and this is all relevant to his qualifications as a school board member, how?
You have accused him of child abuse, neglect, professional misconduct, and mental illness. Personally I believe this is a vendetta that has no place in a public forum. Users/DonShor

20071027 19:11:58 nbsp I find it telling that NiftyWitch isnt sure enough of her accusations and opinions to stand behind them with Importance of using your RealName her real name. Users/Graham.Freeman

20071027 19:22:48 nbsp The key questions about any candidate:
 priorities and goals for the Davis school district?
 how to deal with declining enrollment?
 stand on the closure of Valley Oak, and position on the charter school petition?
 positions on the various special programs and services: GATE, Spanish Immersion, Special Ed?
 record of service, involvement, volunteerism?
How does Joe Spector compare to the other candidates on these issues?
 Users/DonShor

20071029 16:14:42 nbsp Everyone here is willing to have an open discussion but NiftyWitch.  By refusing to identify herself  like she stated that she would  while making serious accusations of child abuse about a school district employee make the postings appear like political and personal sabotage.   Thus, her contributions have no value.   NftyWitch is a mere gossip, at best.  Users/SharlaDaly

20071104 18:32:38 nbsp DonShor:  How are child neglect, professional misconduct, and mental instability NOT relevant in a candidate running for public office, particularly an office responsible for the education and guidance of children??  As for his positions on the issues, I dont even care.  Hes proven to me by his behavior that hes not appropriate for the job, regardless of his position, so its not worth my time and energy to debate that topic.  Sharla, Ive addressed the issue of my username ad nauseum.  I never said Id provide my real name, so I dont even know where you came up with that one.  I said Id provide further details, and I did.  Theres enough info given for any of you to track down verification of what Ive said.  The whole OMG, shes a troll becuz she wont use RealName.  Does that mean everybody on the internet outside of this site is a troll?  As far as Im concerned, its a stupid and tiresome argument.  If Im lying, using my RealName wont make me less of a liar.  Im seeing (for the most part) two primary groups of players here.  1)  The personal friends and supporters, whose opinions I dont put much stock in. The only intention Ive seen demonstrated is to discredit the messenger by any means, no matter how weak the reasoning. Anybody who could have more than a brief acquaintance with the man and not realize theres something wrong, Im going to have doubts about.  2) Those who mean well and are openminded, but just arent yet knowledgeable about the situation.  Guess which group Im going to choose when I do find a little bit of time and energy to come in and revisit this issue? Users/NiftyWitch

20071104 21:16:19 nbsp Please dont revisit the issue. I dont know him, and am not a friend or supporter. I think your comments in a public forum are incredibly inappropriate. I dont think youre lying. I think you have a hostile personal objection to Mr. Spector, the validity of which we cant judge. Citing other community members without their permission is also inappropriate. They can speak for themselves here if they agree with you.
Please stop this ongoing personal vendetta. Users/DonShor

20071105 08:01:39 nbsp NiftyWitch is a liar.  I had the pleasure of visiting Joe Spectors home last night.  It was a lovely home. I looked into each room and found it neat, clean and beautifully decorated.  I toured the back yard. It was neat, clean, well taken care of. He has two white dogs  both of which were clean, friendly and well taken care of. Again, NiftyWitch is a liar and the maliciousness is astounding!

I suspect that NiftyWitch has some serious mental health problems that need to be addressed.

Based on my own investigation into the allegations, I would now remove NiftyWitchs comments.  However, there are members of the Wiki community who believe that everyone has the right to post comments, regardless of fact.   Users/SharlaDaly
