
John Allen Douthitt AKA Pelgye

Like Jerome C. Davis Jerome Davis, the one Davisville was named after, John was raised in Ohio.  He never wanted to live in CA, in fact hed made a vow to himself never to wind up living in CA.  Nice people there, but just didnt feel like home during the periods hed spent in Santa Cruz and LA areas.  But eventually he was drawn in by the divine forcefield of Barbara Boehler who was living and raising her family in Davis.  They married 04/19/1998 and eventually John realized hed lived in Davis longer than hed lived in Ohio.

Born goundhogs day 1951 in Baltimore, MD he has no memory of that city because his parents moved the family to Ossining,NY when he was 2 weeks old.  John does remember watching the inmates play baseball within the yard in Sing Sing prison from the vantage point of coming down the hill to the train station to fetch is father from the daily train commute to NYC.  The original name of Ossining was Sing Sing but after the famous prison was built there, the town ended up changing its name.  Apparently it became uncomfortable for the residents when people would ask where they were from.  Sing Sing.  Oh....  Like living in Davis when you say you are from Davis people tend to think, depending on ones age, you must either work for UC Davis or be students there.  With Sing Sing, though, the connotation was somewhat more pejorative.

Then in 1959, after 2nd grade, his family moved to Shaker Heights, Ohio, one of the upscale suburbs of the once elegant port cities of USs northern shore Cleveland.  Although Cleveland has never seen fit to change its name, it probably has the distinction of being the butt of more jokes than any other US city.  John graduated high school in 1969 and spent the summer wandering from National Park to National Park across the US all summer.  He picked up a Time magazine when he wandered out of Olympic National Park and read the understated caption under the photo of thenmayor of Cleveland mayor Carl Stokes standing in the foreground of a burned out bridge after the Cauyhauga River, running through the heart of Cleveland, caught fire.  The caption was: Clevelands mayor Carl Stokes says: This is not good for Cleveland.  But it did make Cleveland even more memorable.

John went off to college at Colby College in Waterville, ME, chosen on the insightful criteria that it was a long way away, in the middle of a wildlife preserve, and probably had ver deep snow in winter.  John was not famous for his academics.  And he managed to get thrown out after his first year, after which he really started enjoying life.  He tried to get back onto the education track but when he found that was not available he went to Norway and found work on a dairy and potato farm.  He arrived with the limited vocabulary of og and tante (and and aunt) but reading comic books and listening he became fairly fluent.

After fall/winter/spring on the farm, John decided to move on.  He packed what he thought hed need into a rigidframed backpack, tied it down to the rack on the back of his bicycle with a modified diamondhitch hed learned in boy scouts for loading burros, and bicycled from the arctic circle in Norway to Africa.  This was before the common use of panniers, bike shorts/shoes/gloves etc.  Johns equipment included keds, a pair of thin blue cotton gym shorts, and adhesive tape on the drop handle bars.

Meanwhile all his buddies were all doing what he though he was supposed to be doing: going to college.  Having caught a Yugoslavian freighter back to the US, he arrived in Boston to find that he had achieved some sort of hero status as the One who got away.

To be continued...
