See also: Harry Kendall Sensei, Davis Judo Team, ARC Martial Arts Program, Davis Judo Kai, Martial Arts and Self Defense

The aim of Judo is to utilize physical and mental strength most effectively. Its training is to understand the true meaning of life through the mental and physical training of attack and defense. You must develop yourself as a person and become a useful citizen to society.

 Introduction 
Judo is a tremendous and dynamic combat sport that demands both physical prowess and great mental discipline. From a standing position, it involves techniques that allow you to lift and throw your opponents onto their backs. On the ground, it includes techniques that allow you to pin your opponents down to the ground, control them, and apply various chokeholds or joint locks until submission. Judo originated in Japan as a derivative of the various martial arts developed and used by the samurai and feudal warrior class over hundreds of years. Although many of the techniques of judo originated from arts that were designed to hurt, maim, or kill opponents in actual field battle, the techniques of judo were modified so that judo students can practice and apply these techniques safely and without hurting opponents. Judo simply involves two individuals who, by gripping the judo uniform or judogi, use the forces of balance, power, and movement to attempt to subdue each other. Thus, it is simple and basic. In its simplicity, however, lies its complexity, and mastery of even the most basic of judo techniques that often take considerable time, effort, and energy, involving rigorous physical and mental training.

The word judo consists of two Japanese characters, ju, which means gentle, and do, which means the way. Judo, therefore, literally means the way of gentleness. Although the gentleness may not be immediately apparent to newcomers who see bodies flying through the air and people pinned to the ground. It is this principle of gentleness, or yawara (which is the same character as the ju in judo), on which all judo techniques are based.

Judo is much more than the mere learning and application of combat techniques, however. In its totality, it is a wonderful system of physical, intellectual, and moral education. Judo has its own culture, systems, heritage, customs, and traditions. Moreover, the principles of gentleness are carried from the practice mats and into most students lives, in their interactions with their friends, family, work colleagues, and even strangers. Judo gives its students a code of ethics, a way of living, and a way of being. Practiced today by millions of individuals, judo is undoubtedly the most popular combat sport in the world. In terms of sheer numbers of participants, judo is the second most popular sport of any sport, soccer being number one. In terms of national organizations worldwide, judo is the largest sport in the world, with the greatest number of member nations in the International Judo Federation, or IJF. It is a part of the physical education systems of many countries, and practiced in local clubs, junior high and high schools, colleges, regional and national training centers, and in many other areas in this country and across the world. Millions have discovered the spectacular enriching sport, and way of life, we know of as judo.

Judo is a rigorous and demanding physical activity. The practice of judo techniques helps people develop basic and fundamental physical fitness in a number of ways, such as the development of strength, flexibility, agility, speed, dynamic and static balance, explosive power, and endurance. The practice of active attack and defense helps develop reaction time, coordination, and overall physical selfconfidence. Judo students become physically bigger, stronger, and faster through their practice of judo. Not only does judo produce tremendous gains in overall physical and athletic ability; judo students learn the specific skills and techniques of judo. They learn a variety of techniques in order to throw their opponents to the ground with force, speed, and control. While judo students are often exposed to many of these types of throwing techniques in their judo careers, they usually master only a handful, and a handful is generally all that is needed to be successful in contemporary judo competitions. Judo students also learn the fundamental principles and the dynamics of subduing their opponents on the ground through the application of pinning and submission techniques. Their prowess both on the ground and on their feet, combined with the considerable basic physical fitness gained from daily judo practice, affords judo students with a considerable repertoire of techniques, skills, knowledge, and abilities. These, in turn, allow them to be excellent athletes, with a sound physical base of fundamental skills, and formidable and imposing opponents in competition.

But beyond the development of physical prowess and athletic ability, judo students learn much more. They learn how to control their feelings, emotions, and impulses. They learn about values of perseverance, respect, loyalty, and discipline. Judo students develop an outstanding work ethic, as well as important social manners and etiquette. They learn to overcome their fears, and to show courage under pressure. Through competition and the rigors of daily practice, they learn about justice and fairness. Through their experience, they learn about politeness, modesty, and many other wonderful values that contribute to their development as successful citizens of society. As such, judo facilitates the development of important moral knowledge and values, those that are important to help people to become active and contributing members of their communities, nations, and the world. In this way, judo students play an important role in developing societies, and creating new and better communities for the future. Judo students also learn valuable social skills, and build longlasting and meaningful relationships with others. The camaraderie, and bonding that occurs among partners who have shared the rigors of physically difficult and mentally demanding training are deep, often providing the basis for relationships that last a lifetime. Through judo, people are able to develop friendships and integrate socially almost anywhere. Regardless of the towns you visit, in your home country or elsewhere, there is bound to be a judo club, or dojo, where you will be welcomed. Judo is not only a physical activity; it is an international language that transcends national borders, cultural barriers, and language difficulties. In this way, judo links up peoples, communities, and countries; it performs an important role not only in our individual lives, but also in the future welfare of our societies in todays interdependent world.

 History of Kodokan Judo 
Dr. Jigoro Kano was born in the seaside town of Mikage, Japan, in 1860. At the age of 18, he started studying the art of jujitsu in order to strengthen his body. In 1882 he established his own school in Tokyo called the Kodokan and started teaching his own exercise, calling it Judo. Kano structured judo by taking the good points of the various schools and adding his own techniques for the purpose of physical conditioning and mental training.

When the Kodokan was started, its dojo (exercise hall) consisted of 12 mats. The Kodokan Cultural Society was established in 1922 under the slogans: Seiryoku Zenyou (maximum efficiency) and Jita Kyouei (mutual welfare and benefit). These slogans represent the fundamental principles of judo.

Initially the Japanese considered skill and technique (not force) as the main aspects for success in Judo. For this reason, early competitions did not have weight categories.

The first World Championships were held in Tokyo, Japan, and were won by the Japanese. Olympic Judo (male) competition was first held at the Tokyo Games in 1964, when the host country was allowed to include a sport of its choosing. There was no judo at the 1968 Games in Mexico City, but the 1972 Games included competition in five weight categories and the open category.

Prior to the Summer Olympic Games of 1984, a Judo athlete was permitted to compete in a weight category plus the open. This procedure was abolished effective for the 1984 Games. Currently in the Olympic Games, an athlete cannot double compete; in the World Championships, however, double competing is permitted.

 Judo Ranks 
The belt grading system is a distinctive feature of Judo. When a student demonstrates superiority over a crosssection of other students and players at the same level, he or she earns promotion to the next rank. Noncompetitors are awarded promotion based on their time in grade, and their contribution to Judo.

 Belt Colors 




See also: Harry Kendall Sensei, Davis Judo Team, ARC Martial Arts Program
