Judy Corbett is a Noteworthy Published Authors notable local author. She is also a graduate of UC Davis.

She and Michael Corbett created Village Homes back in 1975. Judy and Michael separated, but she still lives in Village Homes.  She is executive director of the nonprofit Local Government Commission.  She helped the commission produce the Ahwahnee Principles for local planning in 1991.

Books

  http://www.amazon.com/DesigningSustainableCommunitiesLearningVillage/dp/1559636866/ Designing Sustainable Communities: Learning from Village Homes
  http://www.randomhouse.co.uk/minisites/castles/ Castles in the Air
As we become more envolved in green growth, we look at past achievements within the community to reference and collect ideas on what individuals can do to live a greener life. The first person that came to mind was Michael Corbett, designer and developer of Village Homes in west Davis. I think as we reference these sources it is important to get the information correct, not only for personal reference, but also if attempting to discuss past achievements we are correct in asking about the subject matter to the person. I felt although not a critical issue but, to make the site more accurate, I need to note that Judy Corbett Micheal Corbetts exwife did not write the book Castles in the Air.
the author is a Judy Corbett in the UK. Another issue I would like to ask for input on is who had the original philosophy to then design and develop Village Homes? I get various points of view in various publications on the project. The general tone is that Judy Corbett was a lab assistant at UCD at the time, and very skeptical about Mikes ambitions to build the model of the book A Better Place to Live. I was told he recieved alot of skepticism and speculation about this project, but continued to persevere until as most great ideas came to fruition. As the project gained momentum and became famous, as in most success stories everyone then wants to take credit. This being a basic human behavior. I have heard everything from a UCD landscape professor, one of the original residents of Village Homes claims credit for the design of the natural drainage process and the edible and ornamental landscape features in this development. That a group of Davis citizens formed this concept as their pilot for a more comunity oriented neighborhood with environmental features, and then various mention from many sources that it was Judy Corbett who created the design and development with help from her husband Michael Corbett to facilitate the construction as a builder. As we watch the election process and everyone debates whether or not Hillary Clinton can represent her credentials to be commander in chief by the 8 years as first lady. Or does the clock start ticking when she on her own entered politics.......just a thought, if anyone can share the REAL story of who is responsible for the creation of Village Homes, i would be most grateful. This is an area of study for me so I would like the opportunity to get the correct information. Thanks, artherm

Michael Corbett is the designer, developer and visionary behind Village Homes. If you pick up his first book A Better Place to Live, you can read more about him. This was something he had thought about since his youth. You are correct that people skeptical tend to get on board when things go well. Public interest became international so there were many who offered to take his place to promote Village Homes as it became famous. I have known Mike for over 45 years and your best bet would be ask him. He is around Davis and is a very approachable person. Not to take away from his exwife Judy, but it is very important to get the story straight, being his wife at the time I am sure Mike would have had an influence around her as well as all the people he knew. You are correct in wanting to know the correct information, this is why I am answering your question is that we need the Mike Corbetts of the world to move into the 21st century as sources to learn from. I hope this was helpful. Sincerely, Sunny
