
K.J. Janitorial is a Janitorial Services Janitorial Service.


20120930 22:00:32 nbsp K.J. JANITORIAL HOUSEKEEPING & MAID SERVICES: WE CATER TO, SMALL BUSINESSES WITH A LIMITED BUDGET,BIG COMPANIES, AND LARGE CORPORATION CLEANING NEEDS. WE ALSO PROVIDE SERVICE TO APARTMENTS, RESIDENTIAL HOMES, LOFT APT., TOWN HOUSES, TRAILER HOMES, AND OFFICES.

WE CAN ACCOMMODATE ANY NEEDS YOU HAVE, NO JOB IS TOO SMALL, OR TOO BIG. WE OFFER HIGH QUALITY, RELIABLE, PROFESSIONAL, TRUST AND HONEST SERVICE.

WE ARE PERFECTIONISTS, AND THIS WILL BE EVIDENT IN THE CLEANING WE PROVIDE FOR YOU.

WE ALSO OFFER: CUSTOMIZED CLEANING SERVICES, WE PROVIDE ALL CLEANING SUPPLIES AND EQUIPMENT, CARPET CLEANING, MOLD CLEANING, DECKS, SIDING, PATIOS AND MORE.

      REMEMBER, WE WORK WITH YOU ACCORDING TO YOUR BUDGET, NOT OURS                 ALL WINDOWS ARE FREE


SPECIAL:
FOR ONLY $35.00 A VISIT, WE WILL DEEP CLEAN YOUR KITCHEN, BATHROOM, CLEAN ALL BASEBOARDS, AND VACUUM CARPET. ALSO SWEEP AND MOP YOUR FLOORS, AND CLEAN YOUR WINDOWS.

{PLEASE SHOW THIS FLYER IN ORDER TO RECEIVE THE $35.00 SPECIAL. IF YOU GET THE $35.00 SPECIAL OFF OF DAVIS WIKI SITE REQUEST A COPY OF THE FLYER}.

THIS FLYER IS GOOD UNTIL JAN. 1 ST., 2013
ALSO, AS LONG YOU POSSESS THIS FLYER, YOU CAN REUSE IT FOR THE $35.00 SPECIAL, UNTIL THE EXPIRATION DATE.


                                          LICENSED...BONDED...INSURED               Users/encieholman

20130202 03:20:05 nbsp KJ and David cleaned our apartment when we moved out and did an awesome job. They are totally professional, easy to work with and the place never looked cleaner. They exceeded my expectations in their thoroughness and I recommend them to anyone who needs a reliable housecleaning (for move in, move out, or regular service) at an affordable price.  Users/KathleenGuillozet
