

A local Media television station that is affiliated with the CBS network. Despite KOVRs main studios being in Sacramento, the station is actually licensed by the FCC for main operations in Stockton.  KOVR was recently aquired by http://www.cbstvdmg.com/ CBS Television Stations Group from Sinclair Broadcast Group (SBG).  The purchase was announced in December of 2004, and was finalized on May 2, 2005.  A television duopoly for CBS Television was thereby created; they also own KMAXTV CW 31.  Both stations are now housed in KOVRs building.

KOVR is one of four TV stations in Sacramento owned and operated by the network with which its affiliated.  (The others are KMAXTV, KUVS, and KTFK.)  All other stations are owned by outside companies (for instance, KCRA and KQCA are owned by HearstArgyle and KXTV by Gannett).  CBS Television felt that owning a station in one of the fastest growing markets would pull off in the end run.  This purchase by CBS Television brings in big promise to both KOVR and its sister station KMAXTV, including two television helicopters in the near future (currently, only KXTV and KCRA have television helicopters).

KOVR is Sacramentos oldest television station.  KOVR receives its call letters because it KOVRs (covers) the Sacramento area.  KOVRs duopoly with station KMAXTV is one of three duopolies in California.  The other two are Bay Area stations KBCW and KPIXTV, and Los Angeles stations KCALTV and KCBSTV.

In 1995, KOVR stationswapped with KXTV and became the areas CBS affiliate.  It stuck with KXTVs policy of not airing the soapopera Guiding Light due to its poor ratings in the Sacramento area.  KOVR also dropped its midnight viewing of The Jerry Springer Show following its merger with CBS Television in mid2005 (Springer can still be seen in the area at 3PM until 2006).

In July 2006, KOVR resurrected its weekday 4PM newscast.  It is currently the only station in the Sacramento market to operate a newscast at 4PM.

SBG is notorious for its conservative lean in the political spectrum.  SBG has often been criticized for requiring its local news stations to broadcast a nightly segment called The Point, in which Mark Hyman from Sinclairs headquarters provides commentary on a variety of issues that may be of concern to the countryan often conservative commentary.  For a more indepth coverage of Sinclair and its conservative bias, see the wiki:WikiPedia:Sinclair_Broadcast_Group WikiPedia article.



20050510 23:11:23 nbsp So, what does the FCC do besides enforcing EBS testing, radio licensing, and keeping Janet from flashing America??? Users/AlphaDog

Considering UPN is owned by CBS, and UPN owns KMAX, wouldnt KMAX  as it is currently  be considered a network O&O television station?
  Not quite.  CBS owns and operates a CBS station.  Though UPN is owned by CBS, its totally a different network.  And even so, its best to leave as is since in September, it really wont matter.  CW will change the way people think about O&O to KMAX regardless, since CBS will only hold 50 percent of the CW share (the other 50 falling into the lap of Warner Bros.)
  From a branding and organizational perspective, that makes sense.  Ive seen some articles in Variety and Broadcasting & Cable, however, that take a different view, which I follow.  If a local television stations parent company owns at least a 20% share in said stations affiliated network, said station was called a network O&O.  By that logic, KMAX is a UPN O&O.  (Begin the possibly annoying minute details part).  The classic examples are KTLA in Los Angeles, WGN in Chicago, and WPIX in New York City.  All are owned by Tribune Broadcasting and are currently WB affiliates.  Although Tribune owns only a minority stake in The WB, they were all frequently referred to as WB O&Os.  The http://en.wikipedia.org/wiki/Owned_and_operated_station Wikipedia article states that a CBSowned CW affiliate (e.g. KMAX, KBCWFKAKBHK in San Francisco, and WPSG Philadelphia) could be referred to as a CW O&O.  My Network TV will make sure this fun argument goes on, since that network will be owned by Fox, and Fox happens to own KCOP in Los Angeles, WPWR in Chicago, and WWOR in New York Cityall My Network affils.  (Always those three citieswhat gives?)  How much time do you give the CW and My Network TV to live?
  KMAX is a UPN O&O.  Source: http://www.findarticles.com/p/articles/mi_m0EIN/is_2000_May_24/ai_62286942, confirmed by CBS Corporations http://biz.yahoo.com/e/060316/cbs10k.html 10Q filing.  The Eye owns UPN, The Eye owns KMAX, therefore...
