Describe Users/kuriman here.


20130207 11:14:28 nbsp Welcome to the wiki!  No, I didnt get a ticket, so hopefully you wont, either. Users/CovertProfessor

20130207 22:51:36 nbsp Before tickets are issued a human reviews the stills and the video capture from the intersection and makes a determination  Users/StevenDaubert
  A person may review the video before issuing the citation, but even if you were just a hair over the line theyll send you the ticket and most likely the judges will make you pay it. The person reviewing it is in Arizona and  gets paid on tickets issued per hour, so if they can issue a ticket they will. I got photographed recently while driving my mothers car ( smidge over the line) and they issued my mom a citation even though shes 30 years older than me and doesnt have a beard.  Its been a huge pain to deal with. Not to go off on a rant here, but these tickets are the most expensive noncriminal traffic violations in the world($500) and are a huge source of revenue for the city and for the company in Arizona that installs the cameras and issues the tickets and splits the revenues with the city. The cameras have been shown to cause more accidents than they prevent http://www.nj.com/news/index.ssf/2012/11/redlight_cameras_lead_to_more.html so the issue of public safety is debatable, especially since cameras such as the one downtown use a yellow light that is 12 seconds shorter than most yellow lights, leaving drivers in a gotcha situation. The legality of these cameras is still under debate and a lot of the cities that initially installed them have removed them for a number of reasons including public safety and fairness. Theres a lot of good info and resources about these tickets here: http://www.highwayrobbery.net/.

 Your mom isnt bearded, wasnt her. the onus is not on her to prove who was driving. Should be able to leave it at that. The company IS shady no doubt, its just that some people think its automated. Tires have to be before the white line when its red in the stills for it to qualify.
  They (the company in AZ or the Davis PD) wont allow you to submit an affidavit of nonliability ( saying you werent the driver) unless you submit who the driver was. So my mom had a notice to appear in Yolo traffic court (she doesnt live here) and she was left with the options of either paying the fine, saying it was me in an affidavit of nonliability, or doing a Trial By Declaration. She couldnt take time off work to go to court and when you do a trial by declaration you forfeit your right to go traffic school so she didnt want to do that (and also apparently a lot of judiciaries in the state find technicalities in your TBD to reject them and force you to come to court anyway). So eventually she filed an affidavit of non liability and I got a ticket a little while later. Still trying to find a way to not pay it.
