Lamargate is a term (coined by a member of the Students for an Orwellian Society) to describe the illegal endorsement of political candidates such as Lamar HeystekFootNote(Lamar Heystek unsuccessfully ran for Davis City Council in 2004, when this endorsement took place.  He later captured a council seat in 2006.) by ASUCD.  Because of the way that ASUCD files its taxes, they are forbidden from endorsing political candidates.  They did so anyway:

  http://www.californiaaggie.com/media/storage/paper981/news/2004/02/25/FrontPage/Senate.To.Consider.Resolution.Endorsing.Souza.Saylor.Heystek.For.Davis.City.Coun1316651.shtml Consideration of endorsements.
  http://www.californiaaggie.com/media/storage/paper981/news/2004/03/01/FrontPage/Endorsements.For.Heystek.Souza.Saylor.Yamada.Pass.Unanimously1316724.shtml Passed unanimously the endorsements of Lamar Heystek, Stephen Souza and Don Saylor (Davis City Council), and an endorsement of Mariko Yamada for the Yolo County District Elections in March of 2004.
  During late fall quarter, 2004, it became clear that the issue would basically http://www.californiaaggie.com/media/storage/paper981/news/2004/12/10/FrontPage/Asucd.Unlikely.To.Face.Penalties.Regarding.Political.Endorsements1319044.shtml blow over.  Additional legislation was passed to make future endorsements legality more clear.

Because of these endorsements, ASUCD might have needed to pay back tens of thousand of dollars in taxes, possibly millions had the IRS decide to impose fines.  Igor Birman and the Davis College Republicans are credited as being the first to tell ASUCD to stop the endorsements.  Igor notified the ASUCD Executive Office in an open letter that their activities were illegal and gave them something like two or three weeks to cease and desist or else he would notify the IRS.  ASUCD in response publicly stated that they were doing nothing illegal.  Despite the testimony by a law professor interviewed by an Aggie reporter on the subject who said yes it was illegal, they did not appear at that time to actually investigate the legality.  Igor consequently informed the IRS, who eventually informed ASUCD that yes they were behaving illegally, and apparently the IRS has been working with ASUCD to investigate the situation and see that ASUCD ceases endorsements.

After the scandal came to attention, the ASUCD Senate Senate passed a constitutional amendment explicitly stating that endorsements are in conflict with tax code and are thereby prohibited.  The Winter 2005 ASUCD Election/Ballot Measures amendment was on the ballot during the Winter 2005 ASUCD Election, and passed.  This showed the IRS that the situation would be remedied.

In conclusion, as of April 11, 2005, the IRS has stated the following:

  After learning of the prohibition from participating or intervening in a political campaign, your organization stopped passing resolutions in support of or against candidates for political office.  You also intend to train newly elected officers and Senators on the prohibition from directly or indirectly participating or intervening in any political campaign.  And you intend to amend your Constitution to include language that prohibits participating or intervening in any political campaign.

  Due to your corrective actions, we do not intend to propose revocation of your taxexempt status.  However, if your organization participates or intervenes in any future political campaign you may jeopardize your taxexempt status.

By this time, the Constitutional Amendment had already passed.

According to the Dictionary of Newspeak, 2^nd^ edition, Lamargate is defined as: A series of scandals occurring during the Student Focus and L.E.A.D. administration in which members of the ASUCD Senate legislative branch issued illegal political endorsements for their perceived allies and brought an IRS audit for violation of the tax code and the public trust.  This definition appeared on a flyer for Students for an Orwellian Society, as a way of promoting the SOSSS slate.  The threat to ASUCD was very real at the time, so it became an important issue in the Fall 2004 ASUCD election.

 Historical perspective 
Lamargate is somewhat of a misnomer, as within something like a three month period ASUCD went around endorsing practically everything they could, Lamar being merely the tip of a very large and scandalous iceberg.  But since http://www.californiaaggie.com/media/storage/paper981/news/2004/11/16/Features/Coming.Clean.About.The.Scandal1318761.shtml Lamar doesnt mind, the name stays.  After all, the Watergate Hotel didnt cause the scandal that made it worldfamous.

Going even further back, in September of 1980 there was an amount of controversy regarding the ASUCD endorsement of Robert Burnside.  ASUCD had a long history of endorsing political candidates, and it seems this era is over.
