

Lanai Garden Apartments is one of the cheapest rental complexes that is not limited to residents of low and moderate income. As of 2012, a onebedroom apartment is less than $800 a month. Some people think of the place and its environs as a slumpit, whereas others find everything acceptable under the maxim, you get what you pay for.

At some point around 2009, the apartments were updated with new tile, appliances, etc. Some residents have said that the current manager and owner are friendlier than ones in the past. Some of the units even have a 5X8 storage room attached to the apartment, and they all have huge patios with sliding glass doors that connect to both the living room and bedroom. The units in the back are ideal over the ones in the front on the street.

To learn more about rental housing in Davis, check out our Housing Guide as well as our Apartments pages.


20080706 12:31:24 nbsp We lived in one of those for two years way back when Ralphs was still across the street. If you get one at the very back, your patio butts up to the backyards of the houses on Haussler and it is okay. But they are early 60s motif. The carpet was older than my girlfriend and she was 30 at the time. Wiring was substandard, no GFI near the sinks. Little old 3 burner stove with an oven the size of an RV. Old cabinets old tile. They used to be owned by a developer with an office right across the street. We called him Slum Lord Ray. They had a new manager about every 6 months. The worst part was Ray would rent to anybody. We had a bunch of tweakers across from us. Out in the carport until 4am with flash lights taped to their heads working on cars, parties with drunk underage girls. This guy was in his 30s from Yuba City... we heard the cops running his ID. Slum Lord Ray would not do anything because... this guy was on his landscaping crew for Rays cheesy developments. Some units had roach problems. We saw rats on the fence running to and from the dumpster. But any body from Davis knows this is the Rat Capital of the valley. Get a unit in back. The ones in front are sun baked and super hot. look at the carpet, maybe they replaced some. You do get a carport and storage. Get what you pay for. Say Hi to Ray for us. Users/LouisM
