


The Common Lilac (Syringa vulgaris) is a lowmaintenance purpleflowering shrub growing from 4 to 15feet high with large clusters of single or doubleheaded blooms or star florets; common varieties have heartshaped, dark green leaves. This fragrant tree is native to southeastern Europe and flowers from spring to late summer, with blooms ranging from whites to blues and purples. Lilacs grow best in a sunny location with good air flow and will tolerate shade, but flowering is poor and, especially in Davis, powdery mildew is likely to be severe. Though unattractive, powdery mildew usually does not severely damage the plant and can be avoided through proper plant siting and watering during long, hot dry periods; to create a biological counterculture solution, mix a half a cup of milk in a gallon of water and spray your plants, repeating as needed  the lactobacillus that sours milk colonizes the leaves and leaves no room for mildew spores! Major outbreaks may require pruning and disposal of infected cuttings. Scale insects are another enemy of the lilac.

The genus Syringa is named after Syrinx, an Arcadian virgin nymph who was turned into waterreeds in a desperate attempt to flee the the lusty woodland god, Pan. Finding himself clutching only reeds rather than the beautiful naiad, Pan sighed & his breath produced a sound from the reeds, which he subsequently bound together to form the first panpipes; today, the nymph Syrinx has spawned the genus classifying plants whose stems can be used to make tubes. Although lilac twigs are not hollow, they have a soft inner pulp that is easily hollowed out to make flutes or pipestems.

Lilacs do not like to get their feet wet for a prolonged period of time and do best on hillsides, slightly elevations, or welldraining soil. Lilac roots run deep, so during extended dry periods like our weather Davis summers, water infrequently yet deeply. Lilacs will tolerate almost any kind of soil, from clay to sand, but excess soil nitrogen will result in poor blooming; a standby from the old days is to spread firewood ash around the plants drip line for bigger, better blooms. Most lilacs produce suckers each spring that can be used to propagate more shrubs. Simply find shoots growing out from the main clump and dig down to expose the roots for those canes and sever between the mother plant and your new clone.

For a listing of other plants found growing in Davis, visit our Town Flora.
