Longs Drugs was bought out by the CVS Pharmacy company and was rebranded/renamed accordingly.  See the CVS page for details on the new store.



 

Longs Drugs is a good place to get medicine cheaper than at a grocery store.  Some insurance plans let you use the Longs Pharmacies to refill medications.  Both locations sell many  other items besides medical supplies with no discernible unifying theme: small clothing stores clothing items such as underwear and socks, nonperishable food, milk, frozen convenience food, seasonal items (Halloween stuff, summerrecreation stuff), small electronics, batteries, cosmetics, kitchen items, office supplies, cleaning supplies, light furniture, and more. The selection of everything is limited and tends towards lowpriced items with some privatelabel brands.

Longs also develops Photography film (1 hour and overnight), and will process passport photos with a onehour turnaround ($6.99 for the first pair; $1.99 for each additional pair).  They stop their processing at 8PM, so youve gotta drop it off before that if you want it done that evening. At the 24hour store (West Covell), 1hour photo orders are not processed overnight, but are processed first thing the next morning when the lab reopens.



They also duplicate keys.

The Oak Tree Plaza location is a little bigger. It has a larger selection of nonmedical items and also had the first Wellness Express Clinic inside (before the company went under), next to the pharmacy, where you could get routine examinations and take care of minor medical issues.

They offer a AAA discount at the pharmacy at both locations, and accept many counteroffer competitor offers from other drug stores.

During August 2008, the Walnut Creek, California based Longs Drugs was purchased by the East Coast based corporation known as CVS.  As part of the purchase, they announced that all Longs Drugs in the 48 contiguous states would be renamed and rebranded as CVS. The stores in Hawaii will retain the Longs Drugs name as Hawaiians are very attached the trusted Longs name. A name change in Hawaii would result in a devastating loss of customers.

The Longs Drugs/CVS changeover took place in the summer of 2009. CVS removed the Longs decor from the stores and installed CVS decor. CVS also reduced labor hours and cut employees from their stores. Longs managers jobs would only be guaranteed for a certain period of time. This was done in order to reduce labor costs.

CVS also changed the focus of the stores. Longs Drugs focused on selling a wide variety of food and merchandise which gave their stores the feel of a variety store. CVS however focuses more on over the counter medication and cosmetic sales. Food selection has been reduced and many products that Longs used to carry have been discontinued.

Each Longs Drug Store (taken over by CVS/Pharmacy) sells Postage stamps  only in books of 20 stamps



The last 5 times I have gone here (The Marketplace location) they were unable to develop onehour film.  Their machines always seem to be broken and they are always backed up.  I would advise going elsewhere, but sadly theres not a lot of photography photo places to choose from here. Users/PhilipNeustrom

I work at the Longs in East Davis, near the Nugget. Just a warning, we are no longer 24 hours due to personnel disputes, but all our other functions run the same schedule. Unlike the Longs mentioned above, our machines have been out once since I started working there and our processors are amazing. I highly recommend it. As a photographer, that where I develop my film, even before I got the discount Users/JohnNash
 No longer 24 hours? Well, that just removed my only reason for going there. Users/MattCzarnowski MC

David Provost suggested stealing a plant from Longs. What an idiot. Users/JohnDudek
 Speaking of plants, Longs has good deals on common garden plants, although I cant vouch for quality. I usually buy at the Red Barn Nursery because good advice comes free with the plant.Users/TomHinds

The pharmacy (Oak Tree Plaza) is the busiest in the entire region, a good time to go is before 4pm or after 7pm since the general working crowd swings through at that time. Also, being as busy as they are, patience is important in order to get good service (if youre nice theyll help as much as they can (they get stressed out too)). The same store also sells stamps Users/BryonWright

Is it just me, or does everyone that works at Longs looks suicidal? I mean, Ive been there at least 10 times last year, and every time Ive seen an increasingly miserable person. Im speaking of the North Davis one, by the way. I cant be the only one noticing this, am I? Users/AtyNguyen
 Its the lighting...Users/BenLee

I think Rite Aid has a better and more consistent beauty/personal care selection than Longs. I must say, though, it is nice to get some less mainstream items there, like Burts Bees, that Rite Aid does not carry. Longs pharmacy, though, is very good and the pharmacists there have been extremely helpful and nice to me. Users/ArielaHaro

20071028 23:06:47 nbsp I do not suggest buying bike lights there because they are really expensive. They seem like the average longs apart from that. I suggest going there after 5 to ship off stuff for the next days mail.  Users/AnnaF

20071031 09:52:30 nbsp The Longs in E. Davis is always a nightmare. The people at the pharmacy are slow and inefficient, and seem lazy and uninterested. If I owned that place, I would be appalled at the indifference and lightlymasked rudeness that their staff shows their customers. Ive decided to switch to another pharmacy. F#$% those guys. Users/AthenaGlaukopis

20071219 21:25:28 nbsp I work here. The nightshift is the best. Users/thelonepiper555

20080203 19:47:51 nbsp Every time I go to the Longs in the marketplace to pick up a prescription called in by the doctor, it takes a minimum of 45 minutes to an hour (on top of the half hour since the prescription was called in) to get it filled.  Add this to the 1520 minute wait time standing in line (twice since you have to find out that it’s not ready and wait) and the time gets very long, especially if you are waiting with a sick child.  I have NEVER been in and picked up my prescription, ready, at the counter.  This week, I decided to wait a few hours at home with my sick child to avoid the ubiquitous hour wait in the pharmacy.  So I arrive several hours after the prescription is called in, wait in line for 20 minutes, only to find out that my prescription isn’t ready because they’ve run out of the drug!  The pharmacist, after some thought, tells me we can either wait two days or she can call the other Longs to see if they have it.  Waiting is not an option, so I tell her to call. 20 minutes later, she comes back and tells me they do have it at the other Longs and she assures me several times that it will be ready when I get there.  So my sick child and I troop over to the Longs in Oak Plaza and wait there 20 minutes in line only to find out, you guessed it, that it’s NOT ready and it will be “around 10 minutes” plus another 20 minute wait in line.  Well, I’ve had it with Longs.  This is the worst service I have EVER seen with a pharmacy.  Repeatedly.  If there were more than three pharmacies in town, I’m pretty sure they couldn’t get away with consistently poor service. Users/LizSweet

20080204 17:24:55 nbsp LizSweet
i understand that you are pissed off that your kid is sick and cant get your meds. but speaking from experience, the pharmacy fills prescriptions in the order in which they arrive. if you want them to do it faster, you need to call in and let them know so they can speed you to the front of the line. otherwise, they do the ones that patients request first, then do the rest later by order. you cant just expect the doctor to fax something over and just have it filled right away. there are other people who need their medications too. Users/voiceofreason

20080227 18:51:36 nbsp Recently I picked up a 24 pack of bottled water worth $6 at the North Davis location and waited in line to pay.  When it was my turn the checker scanned the case and a price of 69 cents showed up.  I jokingly said hey, ill pay that price instead if you want.  I figured the checker would laugh at my stupid remark, find the manager and fix the error.  Instead the checker essentially had a screw it mentality and just gave me the entire case of water for 69 cents.  Lol, now I like Longs more than Rite Aid. Users/PatrickSing

20080227 19:42:27 nbsp It would appear they stopped selling compressed air cause kids would steal and huff it... Users/StevenDaubert

20080403 19:29:29 nbsp The East Davis (Oak Tree Plaza) Longs has a useless pharmacy department.  I just got back from a 3rd trip there trying to get a prescription filled.  When they need the docs permission for a refill and its delayed, they dont bother to call the customer nor the doc...they let the customer repeatedly come in to find the same excuse: the doctor didnt respond.  This in spite of the doctors assurance that they did.  Ill never use those indifferent cretins again. Users/RalphFinch

20080415 15:56:27 nbsp Dont give the pharmacy techs a hard time. Thats my job! Users/thelonepiper555

20080427 01:43:51 nbsp I recently got my photos developed here at the 1550 Covell location (next to Nugget), and was pretty satisfied. I saved my photos on a thumb drive and brought it in to upload, and it only took about half an hour to get them developed. If you live in South Davis, I would NOT recommend going to Rite Aid (near Safeway) to develop your pictures, as the photo machine is ancient and may freeze or crash. Users/at86

20080602 11:55:39 nbsp DO NOT   get your prescriptions here!!!  I had a very important prescription for my daughter and they told me it would take some time to fax over a paper to my insurance for the approval but they told me to wait.  I called in 3 TIMES to have that fax sent in so it took more than 2 weeks for them to finally give me my prescription.  They never call me to inform me they havent received it, they never called me to tell me that they finally did get it in.  I have to do all the work.  Finally when one of the ladies was VERY RUDE to me I decided to leave.  Take into consideration all the times I was waiting at the store when they told me my prescription was ready (I called in) I get there and they told me to wait an hour with a tired infant with me.

Dont develop your film here!!!  They take more time than they say they will and they overcharged me as well.  One time I asked for a white border in huge letters where they told me to write it in and I didnt get that, they told me to just pay for it nothng they can do.

SO NEVER GET PRESCRIPTION AND FILM HERE :) Users/Marcie

20080814 17:01:16 nbsp I have only good things to say about the pharmacy staff at the West Davis Longs. Im in regularly to pick up prescriptions and from time to time my doctors office will obliviously send the refills to the other Longs pharmacy. The pharmacy staff have always been gracious about transferring the prescription, even though the process seems to be kind of a pain for them. Users/LizPhillips

20081202 01:12:53 nbsp After much aggravation with the Longs website and trying to upload pictures to have them printed, I called the Marketplace location store and asked if they had a kiosk I could use a flash drive with instead, and the staff member who answered was helpful and straightforward. I hurried over, and it turns out there are THREE hp photo printing kiosks! It was 29¢ for each 4x6 print, but the process was pretty simple and quick, and definitely better than trying to do it online. So glad about this because I was trying to print a copy of my passport photo for an education abroad application and just met the deadline! Users/AmyChow

20090310 01:27:32 nbsp I used Longs at the Marketplace for passport photos. I got 14 (which was necessary for a study abroad program) and it set me back about $20, which isunfortunatelythe most reasonable price in Davis, I believe; theyre such small pictures. The pictures were processed when I came back two and a half hours later and they all processed well; I even look semiphotogenic, for once. Overall, a satisfying experience.  Users/warriorvoyager

20090506 16:38:30 nbsp DO not get prescriptions here (Oak Tree Plaza)! Their callin machine always hangs up one me right after I specify the time I want to pick it up, always! I have told them about this problem twice already, and though the first employee was helpful the second lady did not even seem to care. She told me, That is just how the system is. Wow okay...After trying to get my prescription refilled 5 times, I went in only to find out they were completely out and it would take 2 days. Finally they called the other Longs and I went over there to get it.

Honestly,the last time I talked to this lady she was so rude and uncaring that I switched my prescription to Rite Aid. She didnt even care that the phone system didnt work, and I basically had to push her into even calling the other Longs.

Avoid this pharmacy! Users/sgent

20090517 08:59:17 nbsp I am on the management team of the West Covell Store (near Panda Express & Safeway) and would like to add that our photo processing has been up, for some time Longs has been using the HP prints in seconds kiosks (prints while you wait, no tech needed), we also recieved a new Pharmacy Manager, and have an amazing Lead Pharmacy Tech, so our pharmacy staff is at its best with its staff happy with their supervision and management.

Also keep in mind our pharmacy is now open from 8a9p during the week and 8a5p on saturday and sunday. We began opening an hour earlier about a month ago to suite our customers needs. Feel free to to progress your script(s) as early and quickly as possible to avoid having to wait at the pharmacy, end up being transferred, or waiting on a drug order. The faster you can fulfill your consumer duties, the faster we can keep our customers and patients happy!

After the CVS/Pharmacy changeover completes our photo equipment will change to Kodak  and the machinery is so new that its still being made! and these kiosks (to replace the HP kiosks) will also be full service, which means different finishes, different photo sizes, even passports! we will also continue to have a wet lab (a photo tech) to assist our community with the product questions and photo needs. Users/BokALok

Welcome to the wiki boka  Users/StevenDaubert

20090603 12:12:32 nbsp My opinion is: DO NOT PATRONIZE THIS PHARMACY (lest they patronize you) (the Market Place one that is). The techs are generally friendly and helpful, however, overall, this pharmacy makes FEMA look competent and efficient. Other descriptors that come to mind are: officious, disrespectful, clumsy, bumbling and unapologetic. Details below. I imagine that some of the fumbling, ball dropping and long waits have to do with the new system and the change over to CVS. I could excuse some delays and mistakes and suchlike, its the attitude that gets my goat.

Here is my tail of woe and intrigue: doctor calls in a prescription (for an acutely ill person who needs it right away). I arrive at the pharmacy the next day and am told the prescription does not exist (Strike 1). This, of course, was on a Saturday. I manage to reach the doctor and have him recall the prescription in. I arrive at the pharmacy where I am told they do not have the right dose of pill. I am given a convoluted and generally inscrutable explanation of what they can do for me, which I understand to be give me an equivalent dose consisting of smaller dose pills and then obtain the correct dose pill on Monday. Moreover they offer to advance us these pills to get us through the weekend (i.e. no immediate charge) (Partial restitution of Strike 1). Monday I arrive again at the CVS/Longs Market Place pharmacy counter (on West CAHvuhl as their recording states). I am given the full prescription (for which I pay $65) of the wrong dose pills, which unfortunately I do not realize until after I have relinquished my place in line. So after a second long wait, I inquire why I did not get the correct dose. The pharmacist (Philippe Demayer, I believe) informs me that he converted the prescription to a different dose pill and cannot now give me the correct dose pills. He suggests that this is rational because if the patient was used to taking 24 of the lower dose pills per day and then switched midstream to a mere 6 pills per day, she could inadvertently take 24 of them, overdose and die. There is a certain logic to thisfor people who cant count or read. Neither applied to the patient in question. Philippe also said something to the effect of, we never told you we would get the higher dose pills, and besides, whats the difference, it is just more pills to take, no big deal (of course if you are non compis mentis enough to forget to take 6 rather than 24 pills, how competent are you to count out 24 pills by yourself in the first place). I find Philippe, surprisingly and inexplicably, a tad defensive when questioned and not terribly willing to explain the situation without a vexed and insolent edge on his demeanor (Strike 2). I also ask why the pills are so expensive as they are generic and our insurance should cover them with a small copay. They say that they ran it through insurance and that $65 is the copay. So I go home, disappointed on two counts. Later, just to satisfy my skepticism, I call the insurance company. They assure me that the copay is $9 and that the pharmacy ran the prescription the wrong way, so it was rejected.

Today I go back to the pharmacy to resolve the issue. The tech tries to figure out the problem. After fumbling around for a time, and asking for help from a man who seems to hang around just for such purposes (Steve), he figures out that to rerun the claim with insurance I must be refunded my initial payment, which I graciously accept. Then, after the obligatory interminable wait, the tech tells me they have just rerun the claim and that it still comes out to $65 dollars (Strike 3). I give them the insurance card and ask them to call the provider number on the back. While I am waiting, I call the insurance company again. Incredibly, the insurance person tells me they have STILL not called in or run the claim (they can see this on their computer apparently) and tells me to tell them that their contract with the insurance requires them to call the Provider help number if there is a problem with a claim. I am not sure what Philippe and his minions were doing for the 45 minutes I am sitting there, but it sure as hell wasnt calling the insurance.

Then (the denouement finally), the tech comes back unsmilingly (Philippe apparently will not talk to me any more) and tells me that I am going to have PAY the $65 and then file a grievance with the insurance company (Strike fucking 4). I am seldom rude to anyone, especially service employees, but these pharmaceutical philistines have heaped enough insult onto a gaping injury alreadyso I say very emphatically, NO, you need to figure this out by calling the number on the insurance card, as your contract requires you to do. Two minutes later, the tech brusquely and still unsmilingly hands me the insurance card back and as he quickly turns away blurts out, it is taken care of. He then beats a hasty retreat. I am not sure what this cryptic taken care of means. Perhaps they are simply forgoing the profit because theyd rather be rid of me (because that is how unpleasant I am). Or perhaps it means they called the number finally and discovered the error was theirs but were too proud to apologize (and the waving of the $9 copay was to remunerate me for my troubles and wasted time). In the absence of evidence to the contrary I will go with the latter.

I realize that mine is a data set of N1, however, in my several sojourns to this pharmacy I uncovered anecdotal evidence that my problem was not unique or even particularly unusual. Many people were grumbling and attempting to navigate out of similar SNAFUs. Our doctor tells us that this pharmacy is a problem pharmacy and they do not enjoy dealing with them (again anecdotal, but telling). My opinion is that many of the people who come to a pharmacy are sick or caring for sick people, and are likely distracted and upset. Pharmacies should recognize this and be a little bit more empathetic than the average business. They should explain their procedures and prices clearly and have a tolerance for misunderstandingand be willing to work with their customers to figure out such discrepancies. CVS/Longs, in my experience, does none of this. They seem to me like an impersonal, corporate monolith, and not a people or service oriented provider. That is all the wisdom I got out of this debacle.  FOOTNOTE: today, five days after the its taken care of event, we got a robocall from this pharmacy, letting us know that two prescriptions were in. I called and found that they had a partial and a full of the same medicationand both of the wrong dose!
 Users/MichaelPlotkin

 Providentially, I had the opportunity to pick up a medication at the Oak Tree CVS/Longs. Fascinating contrast. Many people were suffering the same sort of mix ups and delays as I experienced at the Market Place location, but in this pharmacy they had a fine grasp of basic customer service. During my 30 minute wait, I saw four potentially angry people successfully assuaged and one not so successfully. In one instance, the tech came out from behind the fortress to the waiting area to explain to a waiter in person the prognosis for getting his delayed medication. And I heard the pharmacist telling a disgruntled customer that she had every right to be angry and that they were exceptionally sorry about the problems she was experiencing. Very impressive. Only one mans dudgeon was not to be allayed by the assiduous staff. He declared to no one in particular, repeatingly and loudly, that this was a halfassed pharmacy. His wife told some of us that he had recently suffered a loss, and was out of sortsfor which the dilatory pharmacy provided an expedient scapegoat. Though the line was longer and slower moving than Id have liked and there was, naturally, a glitch over which I had to wait 20 more minutes for resolution, I left feeling fairly and respectfully treated. I sensed not so much incompetence as an ineffective system (perhaps the new CVS system is not operating at peak efficiency yet). So I may continue to go here, rather than the Rite Aid just yet. Users/MichaelPlotkin
