Describe Users/luci here.


20070921 12:55:42 nbsp Welcome to the Wiki. You might want to read Welcome to the Wiki/Business Owner to better understand some positive ways to deal with negative comments. Users/JasonAller

20071127 19:02:16 nbsp The wiki is sort of self healing and as such the http://daviswiki.org/Luci%27s_Salon?actiondiff&version232&version131 removal of other users comments tends to get reverted. Im just dropping a note so when you see the same comment back on the page youll know why. If you look at the http://daviswiki.org/Luci%27s_Salon?actioninfo edit history for the page you can see what has changed over time. Users/JasonAller

Welcome to the Wiki Howdy, Luci, and Welcome to the Wiki!   You might want to check out the importance of using your RealName, so we know who were talking to.  My names Evan, pleased to meet you!  You did some recent edits to Lucis Salon that were reversed as they removed some community review and comments. You might want to read the Welcome to the Wiki/Business Owner wiki guide for business owners to get a feel for what might be more constructive in the future. Please read it, and please stick around: many businesses have found that the wiki can provide them a great service by connecting them to the already existing community.   Also, dont forget that youre a member of the community too... so feel free to tell us about yourself, and add to the Front Page rest of the wiki as well! Users/JabberWokky Evan JabberWokky Edwards

20080111 13:51:26 nbsp Hey, I also fixed your image link.  You might want to wiki:wikispot:Help with Images consider uploading the photo so that it can be thumbnailed automatically (people can then click on the tiny image to view a full sized one).  Youd also be able to add a caption. Users/JabberWokky

20080111 14:12:53 nbsp Sure.  Pretty much everything written on the entire wiki was done by people like you or I trying to help out each other: the whole goal is to make all the entries useful.  If you havent figured out how to upload images, feel free to email them to me at Mailto(jw DOT dw AT timewarp DOT org).  Also, check out the wiki:wikispot:Help with Images entry. Users/JabberWokky

20080306 13:07:14 nbsp Howdy, Luci... you might want to read the Welcome to the Wiki/Business Owner wiki guide for business owners if you havent already.  In general, replying to or pointing out inaccuracies is preferable to just deleting or altering reviews. Users/JabberWokky Evan JabberWokky Edwards

20081216 15:44:34 nbsp Hey, Luci... you really need to reply to those negative reviews, not delete them.  That person is out there spreading that story anyway... heres your chance to have your say. Users/JabberWokky Evan JabberWokky Edwards

20081216 16:02:17 nbsp To the person who suposidly cam to see me for the 140. color 1. there is no such price with me for color and haircut, that is if you even got a hair cut. 2 I dont ever recall  someone coming into me who had there own color formula. Last but not least I fix color jobs like you had. I can garantee you never sat in my chair. If so I would like to see you step in my door and give the complaint to my face. Instead of some B.S comment becuse you probally now someone who just left my salon disgrutled.  Users/luci

20100830 15:16:58 nbsp Very poor form attempting to delete the salon page altogether AFTER continuously responding in rude, unproductive and very unprofessional statements. One wonders if this your online attitude or your general demeanor. I would hope to see a more professional and positive presence from such a longstanding business member in this community.  Users/WesP

20100830 21:32:40 nbsp Hey luci, I reverted your removal of the comment and the link to the Salons index page.  I dont care that much about the comment, but the link to Beauty Salons and Barber Shops needs to stay on your salons page.  Please remember that the Wiki is first and foremost a useful tool for readers, and that means connecting them to information on similar businesses.  By the same token, all of the other salons and barber shops in town link (or should link) to that page, meaning readers can find their way to your salon from others. Users/TomGarberson

20100831 10:28:22 nbsp Hey Luci, I went ahead and deleted the reply from your account to Carrie Bradshaw that you wanted removed, as well as the notation at the top of the page.  The comment from Users/PeterM, as a comment from another editor, isnt something Im comfortable removing.  My advice, if you want to improve the image on the page, is to go back and revise some of your responses to past comments.  You can hit the Edit button at the top of the Lucis Salon page.  Then, just scroll on down to your comment(s) and change them however you want.  If you explain things on the page the way you explained it on the phone, Im sure itll alleviate the concerns of people like PeterM.  Also, I suggest avoiding excessive punctuation :)  If you have any questions, just ask!

As for archiving, in general, its not used to remove individual comments.  It looks like comments from before 2010 have already been archived, and there arent so many comments on the page now that they really warrant archiving.  A better bet is to just rework the responses.Users/TomGarberson

20100930 10:54:20 nbsp Id have no objection personally, but I know some people really like to keep information on salons and similar services interconnected.  My advice would be to explain what youd like to do on the Talk page for the salon Lucis Salon/Talk here.  If no one objects within, say, 2 days, go ahead and make the change.  If anyone does have objections, you can talk it out there. Users/TomGarberson

20101015 23:31:41 nbsp Hey Luci, if you havent yet, its very worth reading over the following two pages:
1) Welcome to the Wiki/Business Owner  basically what to expect and how to deal with it, in a nutshell
2) Wiki Community/For Profit Restrictions  what the wiki isnt legally allowed to have on here.  Its not a matter of people wanting to cause drama or attack you or your business; its a question of Wiki Spots agreement with the IRS. Users/TomGarberson

20111026 12:29:10 nbsp hi guys, luci was wondering if now would be a more appropriate time to remove the blurb/link about lia rene, since it has been over a year. we no longer get any calls for her and we always provide customers with all forwarding/contact information for any stylist that has moved. just wondering. thank you guys! Users/EmilyFrançais
  What reason is there to remove it?   Users/CovertProfessor

20111026 13:44:16 nbsp pretty sure you can derive the reason by the information i provided, it is no longer relevant. Users/EmilyFrançais
  Actually, no I cant derive the reason, or I wouldnt have asked.  It is historical information about the salon that might still be of interest to someone.  The fact that you no longer get calls for her might just mean that people are getting the info they need from the wiki.  That leaves me to assume that the only reason you want it deleted is that you somehow fear it is hurting your business.  But the wiki is not here to help or hurt your business  it is here to provide information.  Since that has been explained to you and Luci many times, I wanted to give you the benefit of the doubt by asking, rather than simply assuming that you were trying to promote your business yet again.   Users/CovertProfessor
   Seems like kind of a harsh reaction, CP.  From my recollection, Emily has been quite good about trying to work within wiki norms and, as she did in this case, communicating when shes not sure if something will be problematic.  Emily, with something like this, I think it should stay for two reasons.  One, its history, and preserving town history (including the history of various businesses) is one of the main things the wiki does; and two, its information that would be useful to consumers if they were looking for her.  In practice that may be rare or might not happen ever again, but the informations there just in case it is needed. Users/TomGarberson
    My harsh reaction was in response to what I perceived as a snippy response to a politely and genuinely asked question.  I agree that Emily has been good about working with others in the past, but not on this occasion.  Somehow, a higher standard is expected of regular editors than of occasional editors, but were all just editors.  Those who are snippy should not be surprised if they get snippiness in response. Users/CovertProfessor

20111026 15:44:10 nbsp oh, sorry, i didnt realize i was being so covert! well, thank you so much for the help, ill pass this explanation along to luci since she has been wondering about it for quite some time. i totally understand. Users/EmilyFrançais
  Thank you!   Users/CovertProfessor
