

Matthews Mattress is a familyowned company that has been around since 1991. The Davis showroom, the second largest of six stores (4,400 sq. ft.), has over 50 beds and furniture items.  They carry Tempurpedic, Sealy, Simmons, Chateau Collection, Spring Air and Natura. These beds range from natural talalay latex mattress sets to pocketed coil on coil innerspring mattress sets.  Mention you noticed the Davis Wiki page and receive no tax on your order (valid at the Davis Showroom).

 Exchange Policy


The owners answered some of the questions posed by people regarding exchange and warranties below.  They note that its all available from their website and literature and encourage people to just ask if they have any questions.  Mattresses can be expensive items, so make sure you know what the terms of your purchase are.

  Our Comfort Exchange Policy is as followed: After delivery of your new premium mattress set, “sleep on it” for 7 nights minimum, then decide on a onetime exchange of equal or greater value within 30 days.  We’ll ask you to pay the difference, of course, if you reselect a more expensive mattress, and (Since there are costs to us) a 15% restocking fee (Not to exceed $250).  We offer store credit on returns of all bedding items (is factorysealed packages only), adjustable bed bases and special order items.  Feel free to discuss the costs and policies with our knowledgeable sales staff.  With TempurPedic mattress purchases, the Comfort Exchange Policy is extended to 90 Days from the date you receive the mattress set.  If an exchange is made on a TempurPedic mattress the restocking fee is a flat $199 to cover the costs of sending it back to their facility.  TempurPedic does not take back the Adjustable bases or pillows, so this exchange only applies to mattresses with or without a matching foundation.

  Warranties generally work as followed: All warranties are offered solely by the manufacturer of your purchased product and are usually a 10 year warranty on mattress sets.  These warranties come automatically with your mattress set purchase and are not sold as an addon purchase or warranted by Matthews Mattress.  Less than 2% of mattresses fail in the given warranty lifetime. If you believe you have a warranty defect with your purchase, please review your manufacturer’s warranty card as a guideline and call us so that we may assist you with getting it inspected.  We’ll do the work in contacting a third party group to do a non biased, in home, inspection of your mattress set.  From the time you call to the time we get a copy of the Inspector’s findings is generally about 34 weeks.  If the inspector reports in their findings that your mattress and/or matching foundation is defective under the manufacturer’s guidelines, we’ll contact you and have you come in to choose a replacement of equal or lesser value.  If you’d prefer you may choose a different manufacturer and you’ll also have the option to upgrade to a more expensive mattress set and pay the difference. We do all of this at little or no cost to you because we value your business, however if you’d rather deal with the manufacturer you are welcome to contact them directly.   They generally will offer you only the most comparable product they produce and will charge a shipping fee to have a replacement delivered and your defective mattress and/or matching foundation picked up.  That process will generally take at least 4 weeks or more from the time you call them.

Aside from mattresses (e.g. bed frames), they have a norefund exchange policy.


20050704 14:33:45 nbsp can you want to qualify that with a story/experience/something? Users/ArlenAbraham

20051001 10:40:28 nbsp They have a coupon for 40% off any sealy posturepedic mattress set in the Fall 2005 Little Green Coupon Machine Users/JasonAller

20050704 12:36:16 nbsp  Come visit the store and say, Hi. !!! Users/HansHoglund

20060321 17:21:28 nbsp This business is a firstclass operation.  I popped into Mathews Mattress this past Sunday afternoon, introduced myself to Users/HansHoglund Hans, and he guided me through their diverse showroom inventory.  I very quickly narrowed the field down to two favorites, both from the Chateau Collection – a line I hadn’t heard of before.  Choosing one over of the over took a while longer, but when Hans informed me that one was being offered at a 40% discount and included a 20year warranty, that resolved the dilemma and I made my purchase.  Hans honored the “mention Davis Wiki and receive no sales tax” offer, and he also gave me a 2for1 deal on a pair of memoryfoam pillows I liked.  My mattress was delivered at 2pm the next day.  I’m 100% pleased with the service, the product, and the outrageous discount – I ended up getting more bedforthebuck here than I ever imagined possible! Users/ErikAnderson

20060517 21:33:36 nbsp Just make sure you dont have to return a mattress.  They offer a 30day return policy but when we wanted to exchange our mattress for another, they were rude and we were not entitled to the advertised sale price on the new mattress.  The return policy is not provided anywhere in writing so make sure you are very clear about the terms of this policy. Users/LeanneCanevaro

20060811 18:43 nbsp Went there today after going to Sit/Sleep Mattress place on 2nd and B.  I didnt want a great mattress (will probably on sleep on it for a couple of years), I had just moved up to Davis that morning and didnt really know my way around.  Hans showed me their very popular backtoschool special and I quickly agreed that I would purchase it since, it was 299 for a Full, including the box and delivery.  He honored the Davis Wiki no tax tip and all in all, it was a painless process.  Mattress to come tomorrow, hopefully itll be okay!  UPDATE:  Mattress has worked great so far!  The gentlemen who came to drop it off were kind enough to adjust my frame to make it fit and to help me get everything together!  Just great! :) Users/KatYu

20060901 11:50:27 nbsp Went there a couple of months ago and I was really happy with my service with Hans.  He helped me find a Posturpedic that I was happy with.  I asked him what if i get it home and dont like it, and he told me about the 30 day comfort exchange policy and pointed to the wall behind him where it was posted.  He was very helpful. Users/MurlinLenard

20060905 10:57:04 nbsp I believe the notax offer has catches.  I went in and bought a bed from Mike, but he said that the deal expired about two weeks ago, and that it only applied to certain beds. Users/DanAlcantara

20060907 17:02:19 nbsp if your thinking of getting a Tempurpedic Matthews Mattress has the largest display. I mentioned the Davis Wiki page and got NO TAX.  since Tempurpedic never go on sale we were really happy with the no tax deal and they delivered it the same day. i think you should see there show room it a beauty!! Users/SarahSang

20060915 18:25:03 nbsp I came in to buy a mattress after recently moving to Davis. Being short of cash, Hans was able to give me a really good deal on an actually very comfortable mattress and box spring. He even honored the wiki no tax deal (although its just like getting a 7.5% discount). They even delivered it for free, at the time they promised. The delivery guys came in, dropped the mattress, and removed the wrappings in under 3 minutes (faster than my Starbucks coffee order this morning). I recommend this place, ask for Hans. Users/DanielHoang

20070914 15:07:03 nbsp Absolutely do not buy a mattress from this company. Like any good salesperson they tell you exactly what you want to hear instead of helping you find the best mattress for you. Our $2000 Simmons Beautyrest mattress started sinking after 4 months of sleep (conveniently out of their 30day comfort warranty window). When we went in to complain the same salesperson (Hans) was shocked that this happened and informed us that if the inspector found our mattress to be defective, we could have a credit at the store towards our replacement purchase. Our inspection has come back and Simmons found our mattress to be defective. Now Hans claims that we can ONLY receive a replacement mattress (meaning the same thing) or buy something more expensive. Wow, isnt that convenient, again? Hans constantly changes his story and lied to us three times when we bought the mattress: 1) he never mentioned the memory foam on top sleeps HOT (kinda important in Davis); 2) he told me that I needed the box springs (which were platforms NOT box springs) to support the mattress but when I came back in to look at frames he changed his story and said Oh no, you dont need these box springs (that I charged you for); 3) and finally he only mentioned after we purchased the BR mattress that body impressions (essentially the sinkholes) were normal on this mattress. Oh and dont bother leaving a message for the company president. He doesnt care about your comments, suggestions or most importantly grievances as touted on his web site. We called and left FOUR messages for him and he has yet to return any of our calls. Interestingly enough, Hans claimed that Kevin (the CEO) passes on all calls for the stores to deal with yet when we came in personally to complain after a week not hearing back from the CEO, he was completely unaware of our situation. Hmmmm ...another lie perhaps? Users/DebWestergaard

20070920 22:37:22 nbsp Not a good store to buy from. You can get a lot of resistance if you have a warranty claim and the salespeople can be very rude. There are better mattress stores in the area. Users/customer

20070925 19:03:38 nbsp I went there today to get a mattress and Hans was working there. I went in at about 6:30 PM and it was dead in there. Hans wasnt exactly the most friendly person, he wasnt rude either though, it seemed like he just didnt want to be there 30 minutes before he closed. The transaction went smoothly, and I couldnt get the sales tax off of the mattress because he said that the offer only applied to their higherend mattresses. I dont know what dictates a higher end mattress there, Im guessing one thats probably $500 and up. Either way, it just seemed like an ordinary store. Users/IdealParadigm

20071128 13:58:43 nbsp Oh wow! We made a big mistake and bought a mattress that was really firm. Im very happy with Hans and Tony they were so understanding and helped me reselect to a plush mattress. My wife will never let me shop for a mattress without her now. Firm isnt alway the right choice as Ive learned. Your mattress exchange policy saved my marriage. Thank you Users/ChadWorthington

20080311 19:36:34 nbsp Bought a Sealy mattress, box spring, and frame there.  Frame made loud knocking sounds when installed, even if you just pushed on it with your finger.  Installer came by, added much tape and cardboard.  Installer was very nice.  Problem solved, but came back a few weeks later.  Mattress top has been compressing as I sleep on it.  The sides are now much higher than the center.  The mattress is only 6 months old.  Im not impressed.  This is not a very high quality product.

Negotiation: Hans tried to push mattresses on me at list price.  Mattresses are typically sold at a 100% markup or more (source: Consumer Reports), and Id previously negotiated a mattress down by 50% at a store in another city, so I wasnt willing to buy at that price.  He tried to kick me out of the store when I told him what price I was willing to pay.  He tried various hard sell tactics, and did not treat me particularly well, none of which worked.  Much negotiation, and a few trips to Mattress Discounters (which will beat a price by 5%, until they wont) ensued.  Hans decided he would need to treat me better and lower his prices to get my business (which worked).  End result: I got my bed for approx $600 including installation and sales tax (list was approx $1200)  50% off.  When buying a bed, negotiate, negotiate, negotiate.  No is a good starting point for a negotiation.  Go to several retailers and compare prices.  Use your cell phone to negotiate.  Note that the same mattress is typically sold by multiple retailers with a different name and different cover to artificially segment the market and prevent competition (source: Consumer Reports).  Its usually the same thing on the inside.  Mattresses with similar (if not identical) features are comparable (even from different manufacturers), and you can use this to your advantage while bargaining.  Do not let the sales people push you around.  Do not lie on the beds in the order they specify  pick the ones that meet your needs in the order you prefer.  Be willing to walk away and shop elsewhere.  You will get a much better deal.  Get everything in writing.  And please, post your experiences here (both good and bad).  We want to reward businesses that treat their customers well and give them great products and great prices, and to force those that dont to improve. Users/IDoNotExist

20080829 13:30:33 nbsp BEWARE, they sell used mattresses!!!!! When you go into any of the  mathews mattress stores, be very careful of what you are buying. This happens at all of the mathews stores, vacaville, woodland, davis , dixon, and roseville. The salesman will tell you about the beds that are on sale, close out or damagedthey call these floor modelsthey will tell you that the mattress set fell off the del truck or slight water damage from weather or warehouse clearance ect.ALL USED wether for one night or a few months. We all know how nasty beds can be. Be sure to look at the bed very good for bodily hairs, fluids and smells, if you question any of these they will tell you its  because it is a floor model. Whats even worse is the price they will try to sell you these for!!! Most companies have go through a  spray and sanitize process with used beds not only that, they have to have a big stamp somewhere on the side that you can see.Mathew mattress doe none of this process.  If you dont believe , check it out for yourselfask for the floor models that are on sale, and be sure to look at box springs and matts still in the plastic if it looks taped up with packaging tapesurely  used. This happens at all the mathews stores.Trust this info, I know this because i used to work for them a few years ago and when i seen all of these things I was in awe. I recently talked to an excoworker that still works there and he said that they still do this. You wouldnt believe the beds that we would pick up from one house and deliver to another as new with out the costumer knowing.Its sad, so for the sake of your family BEWARE!!!! Users/OnlyTheTruth

20080830 07:45:03 nbsp I LOVE THE DAVIS WIKI. Whenever you need something it’s there. It’s important for everyone to add their two cents. I wanted to describe my shopping experience at this store. I just moved my family into the area from So Cal for work. My wife and I have 3 kids so we needed a lot of beds. I wanted good deals on good beds. Not cheap prices for crummy beds. Any one who has kids knows it’s hard to get away and get quality shopping done, but it had to be done. We hired a babysitter for the day and again the next weekend to get what we needed. We first went to Mathews Mattress, then Comfy Mattress, Costco, Sleep Train, and a few other furniture places that had beds in Vacaville and Davis.  Most places were very high pressure and not very knowledgable, or just didn’t have a good selection.  WE DID A LOT OF HOMEWORK!!! We took lots of notes. On Sunday, after “sleeping on it,” we went back to Mathews matt because they had the most variety and best prices. We ended up getting ourselves a Simmons Beautyrest World Class Plush Firm. Hans said this bed is similar to what some high end hotels use. He gave us 500 off and the davis wike no tax deal. We got a queen Serene plush for our daughter, which she LOVES. We got our young ones some closeout beds twin size which were half price.  They weren’t really dirty or anything, but Hans threw in mattress protectors anyways, couldn’t go wrong for half price! All in all we had a good shopping experience at Mathews Mattress. I would go back and do recommend it to others. Do your homework and you will probably come to the same conclusion.



  Users/j.davis

20080905 19:16:27 nbsp anyone know how much does a twin size bed set cost here? Users/Hien

20080906 07:55:56 nbsp UPDATE: The mattress delivery went good and they feel good. Everyone in the family likes their mattress. During the week my wife decided it was time for the next step... bedroom furniture. She took my daughter to IKEA, who found a nice platform bed. IKEA has nice looking furniture, but its not the best quality... perfect for students or children. IKEAs mattresses... TERRIBLE. Ever been camping?... then you have a good idea of IKEA mattresses. Anyways, the IKEA bed for my daughter required only the mattress, not the boxspring and frame. My wife went to back to Mathews and Hans took the box and frame back no questions asked. Also, she picked up some NICE bedroom furniture for our master bedroom. She got The Lodge Bed, I think its called. Really good quality and we got a good deal compared to other stores out there. We will keep the Lodge bed for a long time. The guys came to pick up the boxspring and metal frame and drop off our brand new furniture on Friday after I got home from work at about 5:30. Everything went smooth and the delivery guys were very polite and took off their shoes in our brand new house to not get the recently cleaned carpet dirty.

DELIVERY PERSON TIPS?: I asked the Mathews delivery guys if its customary to tip. They said if we were happy with our service and wanted to tip they wouldnt turn it down. I guess theres no standard for tipping the delivery guys... which their should be. I mean they delivered a huge dresser, chest, nightstands and bed upstairs and worked really hard. Worked much harder than most servers Ive had at restaurants, which you should tip 15%. I gave the guys each a $50 and they couldnt be more happy. I mean we got way more than that discount on all the stuff we bought from Hans so I had to give something back. :)
 Users/j.davis

20100926 16:29:39 nbsp Crooks. I feel ripped off after my experience here and dont think they deserve the patronage of my friends or family.

At first, Jim gave us $10 off a $40 metal bed frame because it was already opened and and just been returned. I had been very happy with Jims service and appreciated the discounted price and that he stayed a few minutes after closing to boot up his computer so that he could complete our sale. As luck would have it, on my way back home with the product I found a $130 Ikea wooden frame with padding and slats outside someones apartment for sale for $30.

I thought there would be no problem returning the metal frame and was surprised when Jim mentioned it was frustrating that I didnt call him before hand (who calls to ask if its ok to make a return?!) and made sure to remind me that he did me a service by selling it wholesale and stayed 15 minutes after closing for me. Just do what you have to do, I told him, and blindly accepted a $10 restocking fee on the product. I had heard him say something about a 10% or 15% restocking fee when I first brought in the frame, so when I went home I gave him a call to question the arbitrary 33% restocking fee. He told me he did me a favor because he previously mentioned hed charge a 50% restocking fee, and when I asked about the %15 restocking fee I thought he mentioned and then read in the policy on this page, he said they actually have a norefund policy (which wasnt mentioned at the time of the purchase) and that the %15 fee is for mattresses only. At least he offered to give back the frame for the price I was refunded if I felt he was being unfair, but I really dont need the frame; either way, it is unfair that I cannot return the frame for a reasonable refund. Users/arinazarian
 Sheesh! They were doing you a favor and youre such a whiner. Users/NickSchmalenberger

20110108 11:00:09 nbsp Stay away!!  Ordered a bed in december and was assured it would come in two weeks.  After waiting for two and a half weeks I called for an update.  Was then informed that they only place orders with the company when they have a certian number of orders and that may happen in the next two weeks!!  The bed has not even been ordered and I will have to wait another two weeks at least and possibly 3 to 4 more weeks.  They have my money and I dont have my bed!!  Going to Sleep Train today to see what they can do and going to get my money back!!  The sales person really does not care.  CRAPPY SERVICE!! Users/SamanthaSmith

20110328 21:50:20 nbsp In contrast to the negative reviews above, I had a very positive experience with Matthews Mattress a few months back when I bought a new boxspring from them. I cant remember the exact reason why, but after some preliminary research (probably a combination of Wiki and calling) I decided not to look at any other stores. I went in just before close on a weeknight and explained what I wanted (a decent boxspring that wouldnt break the bank) to the salesman, who was very friendly and attentive. He showed me the two cheapest boxsprings then told me plainly and honestly that the major difference between the two was how long theyd last, which made the decision rather easy. I got what I consider to be a decent price, $99 for the boxspring + $20 for delivery + $10.41 tax (dammit, forgot to mention the Wiki), and I was sleeping on it 2 nights later. In the end, I really appreciated the friendly, noBS service, as well as the prompt delivery. Users/DanVillarreal

20111002 16:24:17 nbsp I went in there looking to buy a memory foam mattress on Sep 5th. They bald guy who helped me out (if you would call it helping) did not seem very interested in selling me a bed. Every question I asked him was answered with either yes, no, or it just is. For example, I asked him whats the difference between two different temperpedics? His answer was Ones more expensive then the other. I was expecting an answer like this one has better quality foam, or this one is thinner etc. I ended up walking and going to Sleep Center on 2nd ave. I got a memory foam bed boxspring and a new pillow for 700 dollars and we are very happy with it. Its too bad for the guy at Matthews because I was looking to spend about 2 grand on a bed.  

20120429 17:48:11 nbsp My girlfriend and I came in last year to buy a twin bed for our guest room and the sales person did not even bother to say greet us. We looked around to see which bed we wanted, and we were also taking a look at the tempurpedic beds for ourselves. We found a twin bed and came to ask the person at the front desk for the price, along with the tempurpedic bed and his response for the tempurpedic bed was, More than you can afford. The two of us look very young, but we both just graduated from UC Davis and both have well paying jobs and I dont think this guy who doesnt even know us has the right to say that to us. We left and went to Sleep train and bought a nice twin bed and a tempurpedic bed there instead. I spent more than 2 thousand dollars, but at least that money didnt go to these rude people. Users/JaceWinter

20131223 23:02:48 nbsp I dont normally go out and buy mattresses, but it seems like they judge you on your look/adge. I came in to look for a new bed, and the person in the front desk didnt even say Hi. An elderly couple came in and the front desk stood up and walked right to them and started talking to them, and still totally ignored me. I understand that Im a college student, but I was there to purchase a bed and so they lost a customer that very day. Users/Jondguzman
