

Monticello Bistro served Sunday Brunch/French Tea, Saturday night prix fixe and a la carte dinner menus feature cuisine made with seasonal ingredients supplied by local farms farmers and the wine list is comprised of local and regional wines. Dinner menus change every month.


20080528 11:55:49 nbsp Expensive, but food is delicious and prepared with care.  Most or all of the wine comes from Yolo County. The menus (different each week) are posted on their website each month. The chefs, Tony and Rhonda, work hard to use as many local ingredients as possible, often shopping at the Davis Farmers market and Davis Food Coop. Users/dylancooke

20090308 16:23:12 nbsp I randomly walked up to this stand at the Davis Farmers Market this weekend and saw that they were selling brown rice pudding for $8 (i.e. not cheap!) but it looked delicious so I caved... I was then informed that its actually $9 bc you put a $1 jar deposit which you can get back if you bring the jar back (or just get your jar refilled for $8). I was slightly perturbed by this but the woman was one of those very smiley, friendly people and I didnt mind spending money at her booth bc it seemed that she made it herself or had some hand in it. Anyways the bottom line is this brown rice pudding is just heavenly and Im not sorry for buying it despite the price. I cant wait for them to have a spot in Davis, I know it will be great! Users/soledad101
 20090523 18:57:17 nbsp I am glad to hear you enjoyed the rice pudding. We use our own hands and local ingredients to make all of our food. Regarding the jar deposit, it was an idea that came from the Benoit Yogurt who used to sell their heavenly yogurt at the market. I think they are way too popular and busy now, but you can get it at the Davis Food Coop. Anyway, paying an extra dollar means you are more likely to return the jar and you get to see what we have come up with next. Thanks for stopping by and please bring your jar back. I really will give you a dollar or you will not pay the deposit on your next purchase! Users/RhondaGruska
