
Myanmar Childrens Foundation is a nonprofit organizations nonprofit organization.

Founded in January 2007 in Davis, a small city in the central valley of California, USA, the Myanmar Children’s Foundation (MCF) is a small yet effective organization dedicated to helping the children of Myanmar, one of Asia’s poorest and most economically isolated countries.
Run by a group of dedicated volunteers in Davis and Myanmar, the MCF keeps its administrative costs to a minimum.  This allows the maximum amount to be directed to those who truly need it  the children of Myanmar.
The MCF is working with five Buddhist monastic schools in poor rural areas of Myanmar.  These schools provide free education to children whose families cannot afford to attend governmentrun schools.  They also provide shelter, care, and education to orphaned children or children whose families are too poor to even provide for their basic needs.
At these schools, the foundation has constructed four classroom buildings (and is currently building its fifth), sponsored the educational costs of over 500 children atrisk of dropping out of school because of their family’s financial situation, and sponsored a year’s salaries for over 20 teachers.  It has also given emergency relief to children and schools affected by Cyclone Nargis in May 2008, built a water tank to provide clean drinking water in the dry season, provided health and hygiene trainings and medical checkups, provided micro loans to the families of the schools’ children, and trained volunteer local teachers to teach conversationallyfocused English to the children.  Click here to learn more about our programs.

The MCF mission statement:
We believe that education is the key to building the foundation of any country.  We seek to cultivate the future leaders and professionals of Myanmar, to break the country’s cycle of poverty and contribute to its lasting peace and development by developing educational opportunities for poor and disadvantaged children.  We work with orphanages, schools, parents and communities that share these goals and help them to build a sustainable financial foundation that relies on innovative projects and community support, rather than foreign donors.  We maximize our impact by looking to the long term.
