
The Nishi Property is located between the curve in Interstate 80 between the Richards Boulevard Richards and UC exits and the train tracks. It is further bounded by the South Davis Bike Path. The transient community takes advantage of the isolation, and there are frequently tent camps beneath the trees near the rail tracks.
A development proposal that includes highdensity housing and business components was reviewed with the city council on October 1 2013 (http://davisvanguard.org/index.php?optioncom_content&viewarticle&id7679:counciltoreceiveupdateonnishi&catid53:landuseopenspace&Itemid86)
It is covered by Measure J requiring a public vote before it can be developed.

The Nishi Family owns/farms almost all of the property south of Davis between campus, Mace Blvd, and Putah Creek. There have been several proposals to develop this property for commercial/retail purposes including one as a mall in the early 90s.  However, it is usually shot down for fear of destroying Downtown.

The Nishi Property has limited access.  One access (northcentral) is gated, the other (northwest) is via a private railroad crossing.  The gated access is across from the Olive Drive access to the Putah Creek bike trail that goes under both the railroad and the highway.  The road on the property is known as Arboretum Terrace, an extension of Arboretum Drive, itself the northern extension of Old Davis Road.  The railroad crossing access connects to Aboretum Terrace and is the only legal, atgrade crossing along the eastwest Union Pacific mainline (not the north line to Woodland run by California Northern) near central Davis (the nearest atgrade crossings being Old Davis Road to the south and Road 32 to the east  both of these are signalled with gates whereas Arboretum Terrace has only a stop sign).  Trains (should) always sound their horn at this littleused, hidden and rather deceptive private crossing.

This crossing claimed the life of Bary http://daviswiki.org/Tragic_events#headd8b881a5842bbedcc96b0bddc76cc0bc5c376def Barry Landy in 2007.  Landy had a work storage unit on the property and used it frequently.  According to one of his employees interviewed after the accident, he was always warning them how dangerous the crossing was and to look both ways.  There was a stop sign at the crossing in both directions.  It is hard to describe why this crossing is so deceptive except to drive over it.  The crossing is raised and there is a building blocking the view to the south as well as a utility post with a sheet of wood that blocks the view.  Though there is no excuse for not stopping at the stop sign, one could easily see someone who used it daily spacing out and not realizing a train was approaching. On January 30th, 2010, a pedestrian was also killed near the crossing.

There were a number of old farm / warehouse buildings on the property and a pretty nice twostory house in a shady area not far from the crossing.  After the accident, the father of one of the tenants said in a TV interview his son wasnt going to live there anymore; it was too dangerous.  Observing the house in the weeks after the accident, it appeared to be uninhabited  apparently the tenants either left voluntarily or were asked to leave.

On a recent visit in April 2008, ALL buildings on the land, even the house, were levelled and gone.  This is too bad, as the house was in a country setting on a hidden lot with nice trees yet very central to downtown, a very unique living space with a lot of character.  It is difficult to tell there were ever buildings there; even the utility power poles that served the buildings are gone.  Thankfully, the old shade trees remain, including a beautiful oak.  Apparently (this is speculation), the Nishi Family was shaken by the Landy tragedy and was willing to forgo the rent from the buildings on the property out of concern the Landy tragedy would be repeated.

In 2009 and 2010, transients established a tent city underneath the trees near the railroad track.

Any development of the property is quite a ways in the future with the 2008 housing economy and the problems with access.  Union Pacific will never allow any more atgrade crossings and the current crossing is in a lessthanideal location even if it were upgraded with gates.  Olive drive could be extended south, but not without challenges such as how to get across the bike trail and the added traffic at Olive/Richards which already is at capacity at rush hour.  Another possibility is road access under the tracks from the University side, but such crossings are very expensive.  A novel solution given the proximity to campus would be leases that precluded auto access, similar to firstyear dorm leases on campus.

20130924 09:25:43 nbsp Anybody have any information about recent construction activity (it looks a road is being built, etc.)? Users/RobertRhode

20131003 16:29:13 nbsp Ill take a guess at answering my own question by saying it might be one of the many PG&E gas main replacement projects going on right now. Users/RobertRhode
 That makes sense. That would explain the giant vaults they are putting in that I have seen around town (IE Covell) They are also doing a new bike path / refinishing the bike path on either side of the biker tunnel. Also that area is being use for some of the grant money that Davis got for urban greening. I think local plants are going to go in the culvert Daubert
