

Nonviolent Protests protesters have been http://occupywallst.org/ occupying Wall Street since September 2011.  This is a page to document the Occupy Davis movement, which is being held in solidarity with the Wall Street protesters, as other cities are doing. There are now events in roughly 2,500 cities (See http://www.occupytogether.org/). Occupy Davis spread to UC Davis.  The number of people participating in Occupy UC Davis exploded as a result of the November 18, 2011 UC Davis Police Response to Occupy UC Davis.  Sacramento also has its own http://occupysac.com group which started its occupation of Caesar Chavez Park on October 6, 2011. Continued support is welcome, encouraged and needed in order to continue.

The physical occupation of Davis began Saturday, October 15 at 10:30 AM during the Farmers Market Farmers Market when a small group of people pitched tents around the old oak tree on the deck structure of Central Park. As more people joined the movement, the group moved to the far northwest corner of the park. In response to warnings from the police, the group moved back near the original location. In the midst of the most recent political pressure, Occupy Davis is scheduled to move yet again.

Somewhat inexplicably, Occupy Davis has either been a target for local white supremacists, or are being accused of racism (an accusation increasingly common at the national level, due in part to claims of extreme inequity in the racial makeup of the larger protests such as Occupy Wall Street, which is only 1.6% black).  People are passing by and yelling white power.  Protesters are also sometimes pelted with coins and told to take showers, possibly due to one of a few negative stereotypes that exist; some critics see the movement as being made up of purely wealthy white youth attempting to freeload, whereas others view the movement as a bunch of poor, dirty hippies.

At one of its General Assemblies, Occupy Davis voted to ask the City Council to support http://occupycaliforniadotorg.files.wordpress.com/2012/01/joint_assembly_resolution.pdf Assembly Joint Resolution 22, which opposes the U.S. Supreme Courts ruling on corporate money in political campaigns.  The Council agreed on a 50 vote on February 21, 2012 to support the resolution, joining Santa Cruz and Berkeley, among other cities.  (See also Take Back Our Democracy).

 Shut Down Monsanto peaceful assembly 

We will be protesting at the Calgene LLC Calgene campus of Monsanto (which is in Davis, CA) March 16th & 17th. We are expecting 5001,000 people over the two days, many of which are planning to stay overnight Friday the 16th.

Weve been working hard on the logistics, but a little extra in monetary donations would help. We are planning on giving them places to sleep, simple food to eat, PortaPotties, clean water to drink. Lets Shut Down Monsanto! You can help us at https://www.wepay.com/donations/occupydavis


 March in March  March 5th protest at CA Capitol 

March 3rd, 4th, 5th, 6th & 7th Occupy Davis and Occupy UC Davis held a joint action and tentin in the Quad, near the MU Building. We prepared to receive the 99 Mile Marchers, who were walking from the Bay Area to Sacramento. We put up ~60 tents and people were still asking if there were more tents. The 99 marchers came into the quad about 8:30pm Sunday, shouting We! Are! the 99%! We! Are! the 99%!. Pretty cool to see. We all hugged them and then fed them. Afterward, people talked until they were ready to sleep. Most of us retired to our tents about 10pm. Three PortaPotties were provided on the edge of the Quad. A little more than 100 people were present on March 4th Sunday night.

On March 5th, the day of the protest at the CA Capitol, the 99 Mile Marchers and many people from UC Davis Occupy and Davis Occupy went to protest at the capitol as well. We were there all day. There were 1,000s of people there and about 300 people went into the Capitol building, into the rotunda, to have a General Assembly. We voted to raise taxes on the rich. Some people stayed after the dispersal order. 68 people were arresting the rotunda for trespass. I have heard recently this was the second highest arrest number in the history of protests at the CA capitol. The most ever arrested was during the Miners Strike in the 1800s.

The protest at the capitol was about cuts to public education. One of the chants was No Cuts! No Fees! Education must be Free!. Some people were protesting for a Millionaires Tax.

The TentIn takedown occurred March 6th & 7th, in preparation for a clean space on March 16th & 17th. These are the dates for the next protest action.

 Occupy Davis to Hold Weekly Daytime Occupations of Central Park 

On February 11 the Occupy Davis General Assembly approved a proposal resume daytime occupation of Central Park on Saturdays from 11 am to 5 pm, starting on February 18.  Activities will include tabling, bannermaking, a tentin and connecting with fellow human beings.    There is no consensus yet regarding overnight occupation, but it will be discussed at the February 18 General Assembly, which begins at 3 pm.

 Occupy Davis Warned to Get Out or Face Citations 

On Nov. 30, the Davis Police Department issued an official notice of citations to the protesters. Although similar warnings have been given in the past, the charges have been broadened to make compliance very difficult if not impossible to achieve. Previous warnings had been centered around waste, fire, and environmental concerns. When the occupiers made strong efforts to meet code , the city realized it must apply more pressure to evacuate the protesters.

A general assembly was held that night. Among those attending was Stephen Souza who told occupiers, the city wants you out of the park. He suggested alternatives such as daily vigils at a nearby church, an idea which most of those in attendance found unacceptable. Souza went on to claim that all five city council members, along with the city manager were against the occupiers current methods. Souza seemed to believe that he is representing the will of the townspeople. If you disagree with the city council or the police, the occupiers would love for you to contact them and let them know how you feel! Occupy Davis needs support from the larger Davis community if it is to survive much longer.

A work party is planned for December 2nd. The public is encouraged to help the occupiers move their site yet again in order to comply with the citys newest demands.  Occupy UC Davis has also https://www.facebook.com/events/191331230952306/ asked Davisites to contact one or more of the city council members to show your support of the occupation and explain what it is you think they are trying to accomplish by continuing to occupy the park.

Update: Occupy Davis announced on Dec. 7 that they would http://davis.patch.com/articles/occupydavisexitscentralpark/ cease the 24/7 Occupation of Central Park, exactly two months after http://davis.patch.com/articles/videooccupydavisholdsfirstmeetingincentralpark/ meeting to discuss the movement for the first time. Its unknown how much the police warning played into the decision to vacate. They sent out a note today discussing how the movement will proceed:

Our tents and structures are coming down this morning. This does not mean that our movement is ending or that we will stop having actions, rather that our movement will now be proceeding in a new way. At Mondays camp meeting it was decided that our goals can best be served by regrouping and refocusing on more targeted political actions. 24/7 occupation has been a valuable tactic for us so far, and an immensely successful strategy for the wider occupy movement, but now we intend to set aside continuous occupation for the time being, so that we can gather ourselves and strengthen our movement.
  As of the early evening of Dec. 7, the tents were still up... maybe they meant the morning of the 8th?
    Today (Dec. 8th) the tents are nearly all gone, revealing much dead grass...

 What is Occupy About? 


In response to critics of Occupy Wall Street, who remark about the movements lack of a clear and unified message. Prof. Cornel West replied by saying:

  It’s impossible to translate the issue of the greed of Wall Street into one demand, or two demands. We’re talking about a democratic awakening...you’re talking about raising political consciousness so it spills over all parts of the country, so people can begin to see what’s going on through a set of different lens, and then you begin to highlight what the more detailed demands would be. Because in the end we’re really talking about what Martin Luther King would call a revolution: A transfer of power from oligarchs to everyday people of all colors. And that is a step by step process.

Or, for a detailed discussion of what the protests are about, see this excellent piece, http://www.dailykos.com/story/2011/10/23/1028206/OccupyWallStreetisnotdifficultto%C2%A0understand Occupy Wall Street is not difficult to understand.  (Try to ignore the insulting bits, which are mainly directed at political pundits who still claim not to get it).

As the http://www.chinadaily.com.cn/opinion/201109/30/content_13823311.htm China Daily puts it, ...the message from the protesters is quite clear. They are against corporate greed and influence in American politics, economy and life. These protesters, who call themselves The 99 Percent, are angry about the huge amount of wealth collected by the top 1 percent of the population.  Have a look through http://wearethe99percent.tumblr.com/ to get an idea of the hardship that a lot of people are experiencing all over the United States right now.

For the first couple of weeks, there was a media blackout that ignored the protests. Then once the media started paying attention, much of what has been broadcast has portrayed them as radical hippies, as you would expect the U.S. corporate media to do when it is threatened. However, http://www.reddit.com/r/occupywallstreet/comments/l0sd0/ows_the_us_vs_international_media_xpost_from/ international media coverage  has been more thorough and, in general, more sympathetic to the protesters cause.

 Events 


  A General Assembly for Occupy UCDavis is planned for Monday 12pm on the quad
  In solidarity with Occupy Cal’s http://reclaimuc.blogspot.com/2011/11/oncominggeneralhighereducation.html  Call for a Strike and Day of Action, Occupy Davis is hosting a Day of Education & Action.  The action will start on the UC Davis Quad at 2:30 pm on Tuesday, November 15.  The following are possible topics:
   History of Nonviolent Student Movements
   Political Significance of Student and Other Nonviolent Social Movements
   Nonviolent action strategies
   Police Oppression on university campuses
   Legal Rights of nonviolent protesters
   Effect of private industry funding on public universities
    If youre wondering what the fuss is about, http://www.youtube.com/watch?featureplayer_embedded&vbuovLQ9qyWQ watch this video.
    See also: UCDavis Bicycle Barricades call for a 12 noon Nov. 15 https://bicyclebarricade.wordpress.com/2011/11/12/strikedaytuesdaynovember15/ Strike Day and Davis Faculty Associations http://ucdfa.org/2011/11/11/dfaendorsesoccupycalscallforstrike/ endorsement of the strike.

  http://finance.yahoo.com/bankingbudgeting/article/113658/banktransferdaymainstreet?modbbbudgeting Bank Transfer Day  Saturday  November 5th
   http://www.moveyourmoneyproject.org/
   What better way to punish greedy and corrupt banks that have taken tax payer money than to move your money to a notforprofit credit unions credit union or to a small local bank where you can get better service and better deals. Remember that you can move your money at any time. You can open up a new account at a new financial institution and then move your money after the new account has been established. There is nothing wrong with opening up multiple bank accounts at different institutions and trying them out. If one place gives you certain deals you can keep both accounts and keep the benefits of both.
   Even though banks claim to have repaid their TARP money, banks continue to get loans from the government at very low rates. Essentially, the banks are still taking money from the tax payers and paying virtually no interest to the tax payers in return. Banks are taking tons of virtually interest free cash from the government in the form of loans and they arent even calling it a rescue or bailout. They call it loans. Without money from the government these banks should have collapsed due to their own terrible financial decisions such as predatory lending. These corrupt banking corporations dont deserve to be rescued from bankruptcy at a time when average people are unemployed and have financial problems of their own.

  General Strike in Oakland  Wednesday  November 2nd

  There was a Public Forum on Austerity on Tuesday, Oct 25th in Central Park at 5:30pm.  It included:
   Talks by Prof. Noha Radwan, Prof. Nathan Brown, and Prof. Joshua Clover
   A knowyourrights training, followed by free dinner
   Preparation for the http://bicyclebarricade.wordpress.com/2011/09/26/oct27firstdayofactionatucdavis/ Oct 27th UC Davis Day of Action UC Davis Day of Action, Thursday, Oct 27th  MU Patio  Rally at Noon

  A number of General Assemblies have been held, including one on https://www.facebook.com/event.php?eid109862109123377 October 7 to discuss the goals of the occupation, and help get things organized, one on https://www.facebook.com/event.php?eid119792011461636&refnotif&notif_tevent_invite October 12, one on October 19, and one on October 22.  Roundtheclock occupation of Central Park began Saturday, October 15 at 10:30 AM (during the Farmers Market Farmers Market.  From the Facebook page:
  Over 100 participants at the Wednesday General Assembly of Occupy Davis voted unanimously in favor of a roundtheclock occupation of Central Park, to begin with the movements next General Assembly scheduled Saturday, October 15, at 10:30 am in central park. For the indefinite duration of this occupation protesters will erect tents temporarily during the day to symbolize a reclamation and occupation of this space, and will hold a fire watch vigil in shifts throughout the night. Planned activities include presentations of music and art, teachins, nonviolence trainings, craftins, knitins and marches.

  http://bicyclebarricade.wordpress.com/ UC Davis Bicycle Barricade

  November 18, 2011 UC Davis Police Response to Occupy UC Davis  Occupation of the UC Davis quad was broken up by dozens of police in riot gear. Ten people were arrested, according to a tweet from the Enterprise, and many more were pepper sprayed. Here are http://davis.patch.com/articles/occupyucdavis#youtube_video8488982/ several videos of the arrests. Some are from cell phones, others from HD cameras. During the General Assembly that followed, students (and others) said theyd be back monday with tents, and possibly a dome.
  A youtube video of the incident has since gone viral gaining over a million views  http://www.youtube.com/watch?vWmJmmnMkuEM

 Possible Concrete Actions in Support of the Occupy Movement 

  Move your money to a credit unions credit union.
  http://iamlaurenleonardi.wordpress.com/2011/10/26/elevesimplewaystosupporttheoccupymovementwithoutsleepinginapark/ 11 (actually 14) simple ways to support the occupy movement without sleeping in a park.
  Shop green and locally; see Green and Local Gift Ideas
  Support http://movetoamend.org/ Move to Amend, an organization dedicated to overturning the ruling that gave corporations the Supreme Court ruling status of persons.
   This is horribly fallacious.  Citizens United v. FEC did not grant corporations personhood.  Corporate personhood has existed as a legal fiction since at least the 1830s.  The underlying concept, that a corporation functionally acted as a person in creating contracts and undergoing obligations, was codified by 1819, if not before (Dartmouth College v. Woodward, 17 U.S. 518 (1819)).  In the context of political speech, corporate protection dates at least to NAACP v. Button, 371 U. S. 415 (1963).  Moreover, the First Amendment doesnt just apply to persons.  Rather, it states that Congress shall make no law . . . abridging the freedom of speech.  Not an individuals freedom of speech.  Not a persons freedom of speech.  Probably more relevant is the decision in Buckley v. Valeo, 424 U.S. 1 (1976), where the Supreme Court held that spending money on political elections constitutes speech.  That issue is probably what they really want to target.  The fact that this Move to Amend organization claims in the very first sentence of the statement on its webpage that Citizens United ruled that corporations are persons shows that they either havent read the damn case or theyre being deliberately deceptive.  Im in favor of reform in the area of campaign finance.  But I dont support, and you shouldnt support, a group that proves its ignorance of the issue its addressing in its opening statement. Users/TomGarberson
  Support the OCCUPIED constitutional amendment  http://www.theoccupiedamendment.org/
   http://thinkprogress.org/special/2011/11/18/372361/repdeutchintroducesoccupiedconstitutionalamendmenttobancorporatemoneyinpolitics/
  Write to Kamala Harris and tell her http://articles.latimes.com/2011/nov/21/opinion/laoemeyersonkamala20111121 how awesome she is.
  Related to this http://www.youtube.com/watch?vM54ZBzgcw&featureshare On December 6th, 2011, Los Angeles became the first major U.S. city to call for an amendment reserving Constitutional rights solely for living human beings.



Photos 


 Media Coverage of Occupy Davis 

  http://davis.patch.com/articles/occupywallstreetcomestodavissacramento/ Occupy Wall Street Spreads to Davis & Sacramento
  http://davis.patch.com/articles/videooccupydavisholdsfirstmeetingincentralpark#video8048330 Video: Occupy Davis Holds First Meeting in Central Park
  http://davis.patch.com/articles/occupydavistobeginroundtheclockoccupationofcentralpark Occupy Davis to Begin RoundtheClock Occupation of Central Park
  http://www.youtube.com/user/sarenasvideos YouTube videos  SarenasVideos gives short interviews with Occupy Davis protesters
  http://www.kdrt.org/node/7988 Occupy Davis, on Davisville (KDRT)
  http://www.sacbee.com/2011/11/19/4066159/10occupyprotestersarrested.html Sacramento Bee 11/19  UCD Police state that they were surrounded (elsewhere stated that a police cruiser was blocked).  Accuracy?  The Sac Bee is often quite biased.
  http://davis.patch.com/articles/theotheroccupycampgetswarnedbypolice The Other Occupy Gets Warned by Police

Counterprotests
A new group has formed to protest the Occupy Davis movement. They call themselves Occupy Occupy Davis. Their official Facebook page claims they are sick and tired of looking at a bunch of dirty hippies in central park... The group uses the Republican Party elephant as their logo. They are scheduled to protest the original protesters on Nov. 23 from 5 PM to 6 PM. Judging from the tone of their Facebook page, they are likely to yell out brainless rightwing quips such as go get a job or if you dont like it, move. This will be heartless and paradoxical, of course, because many of the original protesters would love to get a job and/or move.

  Video ousting plan to dismantle occupy  http://www.youtube.com/watch?vzha0N7QVeb4&featureplayer_embedded

 Relevant Links 
  wiki:occupytogether Occupy Together Field Manual
  wiki:WikiPedia:Corporatocracy
  wiki:WikiPedia:Occupy_Wall_Street Occupy Wall Street
  http://occupycolleges.org/
  http://www.davisvoice.com/2011/10/wordsconjuredintobeingoccupydavis/ Call to action from a local poet
  http://www.youtube.com/watch?vwK1MOMKZ8BI& Why #OccupyWallStreet? Four Reasons from DC Douglas  A powerful video that summarizes well
  http://www.youtube.com/watch?vN8o3peQq79Q& Keith Olbermann Reads The Statement Released By The Wall Street Protesters  20111005
  http://www.avaaz.org/en/the_world_vs_wall_st/?slideshow The World vs. Wall Street  Sign this Avaaz.org petition  they are at 756,907 people as of 10pm, 10/16
  http://www.thenation.com/article/163844/occupywallstreetmostimportantthingworldnow Occupy Wall Street: The Most Important Thing in the World Now  Naomi Kleins inspirational speech at Occupy Wall St.
  http://www.occupytheboardroom.org/  Find a corporate pen pal!
  http://www.rollingstone.com/politics/news/myadvicetotheoccupywallstreetprotesters20111012 My Advice to the Occupy Wall Street Protesters  5 clear goals.
  http://myrmecos.net/2011/11/20/iwaswrongaboutoccupydavis/ I was wrong about Occupy Davis  blog post by UCD alum
  http://thinkprogress.org/special/2011/11/18/372361/repdeutchintroducesoccupiedconstitutionalamendmenttobancorporatemoneyinpolitics/ A proposed constitutional amendment to get rid of corporate personhood.
  http://www.huffingtonpost.com/2011/11/21/occupydenvereverwonder_n_1106272.html  From Denver, the importance of tents to the Occupy Movement.

 Other Area Protests 

  http://blog.sfgate.com/kalw/2011/10/05/hundredstaketomarketstreetinoccupysfprotest/ Hundreds take to Market Street in Occupy SF protest
  http://www.sfgate.com/cgibin/article.cgi?f/c/a/2011/10/06/MN121LDU5B.DTL Occupy SF protest march draws 800
  http://www.sfgate.com/cgibin/article.cgi?f/c/a/2011/10/06/BAFA1LECD5.DTL S.F. police break up Occupy SF camp



20111005 14:53:32 nbsp With a little more work (e.g., nailing down a date/time would be good  Davis Patch suggests 6 or 7 pm in Central Park on Friday) this could be the Featured Page...  Users/CovertProfessor

20111005 16:36:37 nbsp This is indeed the time to sit up and get abreast of this movement.  Alternative media is essential.  Just one point now, I was trying to find a comment I read about MoveOn.org trying to coopt the movenent toward a Democratic Party corporate direction. Users/BruceHansen
  They had their chance to do something.  They blew it.   Users/CovertProfessor

20111005 18:22:44 nbsp Why Occupy Davis? What did Davis do? Users/MikeyCrews
  Perhaps nothing relevant to what the protesters are protesting about (though I may be overlooking something).  It is a national movement, in solidarity with the Occupy Wall Street protests (rather than, say, traveling to NYC).  See links above for more details.   Users/CovertProfessor

20111005 18:48:22 nbsp MikeyCrews  It is not about Occupying Davis  nothing against Davis, love this place. If you read more about the movement it will start to make sense. It is in solidarity with those occupying wall street for the above stated reasons. That is why I have suggested we camp out in the car park between all the big banks  Chase, Bank of America, Wells Fargo and Union Bank and hold them responsible for this mess we are in. Its happening in 420 cities now according to http://www.meetup.com/occupytogether/. Lets use this momentum to create positive change!!!
P.S. Thanks for the edits. I typed it up nice the first time but then the webpage expired and I lost everything and got frustrated. Persistence and a bit of community helps :) Users/ConsciousConsumer

This is a great idea. Users/Angel.York

20111005 19:22:46 nbsp Do you think wed be more powerful if we joined the Occupy Sacramento efforts? I know and love Davis, but I feel that our numbers would be more noticeable in Sacramento than in Davis.  Users/ChristyMarsden

20111005 19:25:46 nbsp Also  according to the OccupySacramento facebook page, the first event is October 6 at 11am, Ceser Chavez park. Theyre going to do another one October 15th Users/ChristyMarsden

20111005 19:35:25 nbsp I think it has the potential to be sustained for much longer if we have people who can take shifts, especially with the buzz that can be created around campus and downtown. By all means get active in both. I want every university to be buzzing with discusssion right now. Democrats and Republicans are failing us and the back and forth, corporate endorsed, pendulum that is democracy in this country needs a dose of active participation. Users/ConsciousConsumer

20111005 20:44:36 nbsp Hi ChristyMarsden, Occupy Sacramento isnt only on those two days  its actually from the 6th at 9 am until the 15th at 11:30 pm. People are physically occupying the park for the duration of that time. It would be cool to go for a couple nights there and also participate in occupying Central Park here in Davis. Well need a lot of volunteers and supplies, so please come to the First Meeting of General Assembly on October 7th at 6pm in Central Park to talk about our goals, what we need, to assign roles (i.e. press secretary), and to discuss the general plan of our occupation of the park (i.e. length of stay, etc.). Yay Democracy! :) Users/NTNMorgan

20111005 21:10:04 nbsp
hmm  arent the corporations you would be protesting the very same ones that provide the computer and connectivity and transportation you would use to rail against them? I see no real actions to fight corporatocracy other than to go protest (not even obvious things like dont buy xxx)

  Then you are clearly making your judgments before you even read the page, because they clearly are trying to encourage people to move their money from large banks to credit unions and smaller banks. They will also likely support buy nothing day which encourages people to ignore the media holiday black friday. To address your first logically flawed point, they are not protesting technology, they are protesting the growing wealth gap. Having only a few options to connect to the internet because of corporate monopolies only illustrates the need for protest like these. And many people here bike around, and there arent many bike companies in the top 1%, mostly oil, financial and chemical. ~~~

Why not do something fruitful like volunteer to help someone in need or clean up the environment. FWIW, someone will always be in the top 1 percent even if it isnt the current crowd Users/RichardL

  justifying your apathy by saying that we still consume corporate products is like denouncing campaigners against world hunger for continuing to eat.  CC

  Saying there will always be one percent is a truism, but that says nothing about the proportion of the nations wealth the one percent owns which is the issue you are conveniently ignoring. ~~~~

20111005 21:21:47 nbsp I dont want to flood the wiki with links, but this is noteworthy >http://occupycolleges.org/ Users/ConsciousConsumer

20111005 21:21:51 nbsp http://www.davisvoice.com/2011/10/wordsconjuredintobeingoccupydavis/
Beautiful poem on occupying Davis
Love can be a great motivation for occupation Users/NTNMorgan

20111005 22:04:41 nbsp Users/RichardL  You seem to be missing the point... I suggest looking more in depth at some of the links provided. They explain it in a lot more detail. Users/ConsciousConsumer

 To CC: I did look at the links, thats why I wrote I see no real actions...  they werent in the links, or in the FAQs which is obviously where they ought to be. Users/RichardL

  I dont see this movement as anticorporate in the sense that you seem to mean it, i.e., I dont think people are looking to have the corporations dismantled.  Rather, they are angry about the influence of corporations in the political process, and the resulting tax policies and other policies that favor corporations over people.  They also think that the corporations responsible for the economic crash should be brought to justice.   Users/CovertProfessor

 It was antibig business sentiments like this that kept the unemployment rate high under FDRs failed New Deal policies. Users/thellama

  So you are comparing an era with little globalization to the era of globalization and you find that productive? Corporations then and now are not even comparable. Trying to do that is a red herring to the real debate at hand, a contrived escape. ~~~~


20111006 00:03:03 nbsp I just got an email from Brave New Films (They were responsible for Outfoxed, Iraq For Sale, Rethink Afghanistan, WalMart: The High Cost of Low Prices as well as many other campaigns) Pretty cool >  http://www.youtube.com/watch?vRnGBQYOHo_k&featureyoutu.be Users/ConsciousConsumer

20111006 01:32:17 nbsp I suspect that camping out in the parking lots of downtown Davis, or even on campus, will do little but get in everyones way and annoy people that might otherwise support the cause. Furthermore, employees of local branches of big banks have no clout whatsoeverif you want those in charge to take notice, take it to corporate headquarters.

In fact theres really nothing you can do in Davis that will accomplish much in this respect. If you really want to get things done, take it to Sacramentomarch on the capitol! Yes, revolution takes work. You cant change the system by hanging out on the quad and chanting clever slogans. Users/BarnabasTruman

 You cant change the system by hanging out on the quad and chanting clever slogans.  We shall see after this pepper spray incident. The movement is growing and I believe Katehi will resign  CC

20111006 09:33:41 nbsp I totally understand the desire to focus on Sacramento or other big cities where occupy movements can have an impact—but I wouldnt underestimate the value of an Occupy Davis.  Increasing the number of cities (big and small) that have movements or hold meetings will make it harder to argue that Occupy is just a bunch of radical hippies. :)
 It will also reach people who probably wouldnt otherwise participate. Users/bethjoyce

20111006 10:40:35 nbsp Im rusty on the legality of saying something from freeway bridges. Users/BruceHansen

20111006 11:27:36 nbsp So does this movement really think that the rich are getting rich at the poors expense? Isnt the American dream of many immigrants to be able to come here and achieve anything they want, even wealth? The successful arent keeping the poor from becoming wealthy too are they? Why hate on those who have achieved success and gained wealth because of it? Users/thellama
 20111006 12:28:38 nbsp I think most people dont mind if the rich get richer while the poor get modestly richer, but whats happened in the past decade is the rich getting much richer while everyone else has been losing wealth. Presumably this is because the rich are exercising excess influence in Washington to cement only their own position in society while being subsidized by the whole of society. I havent personally read much about the movement but I think this is the general gist. Users/AndrewPotter
 I recommend scrolling through these http://www.businessinsider.com/15chartsaboutwealthandinequalityinamerica20104#thegapbetweenthetop1andeveryoneelsehasntbeenthisbadsincetheroaringtwenties1 15 MindBlowing Facts About Wealth And Inequality In America.   Users/CovertProfessor

20111006 18:22:52 nbsp Tomorrow night, Oct 7, is Kol Nidrei, the beginning of Yom Kippur, the holiest 26 hours of the Jewish year.
Most of us Davis Jews will either be in synagogue or at home focused on prayer and repentance (with fasting).
So, sorry, but we will be unable to participate in tomorrow nights protest. Users/Chamoudah

20111006 19:54:10 nbsp Tomorrow night, 6pm at the farmers market is just the general assembly where we will be discussing what this is all about, and what might be needed to sustain the movement in terms of supplies, finances, food, etc. So even if you miss it still come to the day of action which is planned for the 27th if Im not mistaken.

I would like to say that this should be a discussion for everyone (left, right, in between, any colour, any gender, any class, any age, any background etc) to get involved and participate in the political process and discuss what is happening and what we would like to happen...now. Not 10 or 20 years from now, after we have paid off their debts, and continue to pay corporate subsidies, and military contractors with our tax dollars. No more taxation without representation. This is obviously just one perspective, but at least I recognize that there are multiple perspectives and am open enough to hear everyones ideas and suggestions for a bright future. I think we now know that neoliberal economics does not work and continues to not work... In my opinion... feel free to challenge that with logic, evidence and research, because that is what I am basing it off of.

The goal of development should be agency  the creation and promotion of peoples choices and capabilities. Not a competition to see who can have the greatest GDP or who can own the most possessions. Look outside the bubble that is the United States and see what kind of effect we have on those in the global community (because believe it or not, we live in a globalised world where our actions have a domino effect) through the WTO, IMF, World Bank, countless large corporations and our influence on the UN security council.

Finally, I dont want anyone to get defensive and feel like Im coming to take their wealth so as a final thought, Ill just post this video of Tim Wise talking about Guilt and Responsibility, because it can apply to a lot of stuff in life...http://www.youtube.com/watch?vXhOh_EGe41Y Users/ConsciousConsumer

20111007 16:12:50 nbsp The Most Important Thing In The World Right Now  Naomi Kleins speech at Occupy Wall St... Intense, made me want to cry.  http://www.thenation.com/article/163844/occupywallstreetmostimportantthingworldnow Users/ConsciousConsumer

20111008 00:01:06 nbsp I joined the thing a bit late, but I ended up leaving because I couldnt keep a straight face. The person who was speaking when I got there was barely audible, and the few dozen people who attended formed a standing circle around him while totally ignoring the somewhat interested bystanders who walked by, most of whom would have had no idea what was going on due to the general lack of signs outside the circle. And for some reason (maybe to avoid violating a noise ordinance), the attendees would all just wiggle their arms in the air instead of clapping whenever they heard a good point. I understand that this was an organizational discussion more than an official protest, but still, there was such a lack of rebellious rallying energy that the whole thing seemed useless even though I agreed with the intent. Sorry; I wish I could be more positive about the meeting. Users/ScottMeehleib
  On wiggling fingers and truly democratic movements:  http://www.nytimes.com/2011/10/08/opinion/collinswallstreetweeks.html

20111008 06:41:28 nbsp Scott  Its not ready for prime time public consumption yet. What you saw was the first, organizational meeting of the group intended for members of the group itself, not a demonstration meant for public consumption. The people assembled there were not giving speeches or getting anyone riled up, or trying to get the public/passersby involved, but were discussing the boring but  essential logistics and organization of the movement, and gaining the consensus of everyone there as to how things would be conducted. In fact, because matters were being voted on, and rules of order and procedure were in place, stopping everything to educate members of the public would have slowed things down and prevented important decisions from being made. Things like logistics and park permits arent superexciting, I totally agree, but neither is the foundation of a good house. The good stuff comes later. Because this is a new kind of protest, not your typical stand and shout, it takes more time to collectively establish the new norms that people should follow and get everyone on the same page. Users/EdwardNiemand
 OK, Edward. Thanks for your explanation. Ill try to be more optimistic about this way of doing things. SM

20111009 09:26:05 nbsp Corporate greed sounds like big stuff for Davis.  Now occupying Ally properties, I can get behind that. Users/shraken

  To be fair, it actually is a big deal for Davis. Considering these international companies that many ironically love with nationalistic pride refuse to pay their taxes which directly causes the problems with our budget. It causes cuts to our schools, then these very same companies come to the universities and pretend to be white knights riding in, but force the university into one sided contracts that allow them to reap the benefits of any research derived from their financial contributions. If you want an example look at UC Daviss arrangement with Chevron. ~~~

Are there plans for a boycott?  If so please document.  Users/SueHjerpe
  A boycott of what? If youre thinking of banks, there are many fine credit unions  which are consumer financial cooperatives  that have offices in Davis. Many of us are urging our friends and coworkers to close their accounts at national banks and http://moveyourmoneyproject.org/ move your money! Users/DougWalter
    I asked because of the posting on Davis Wiki pages for local businesses of the banks that they use.  There was no explanation of why that was relevant, but the comment referred to Occupy Davis.  Users/SueHjerpe
    I would urge everyone to think about the ramifications of every purchase you make, always  your dollar is your vote. But yes, move your money to a credit union asap. http://www.laborrights.org/creatingasweatfreeworld/ethicalconsumerism   CC
    It looked as though the unidentified person posting to 3 local restaurant pages wanted people to boycott those businesses because of the banks that they used.  I dont think that is a good idea.  Perhaps with further information I would understand. Users/SueHjerpe

20111011 16:19:01 nbsp I am not a fan of the current Occupy Davis poster for tomorrows General Assembly, shown on the fb page.  While I understand the symbolism of the raised fist, I think it will turn away those who might otherwise be sympathetic.   Users/CovertProfessor

20111011 18:00:15 nbsp I agree with Users/CovertProfessor I thought the penny farthing logo was pretty clever and should be made into tshirts for fundrasing. This is a great article if you get a chance  http://www.cnn.com/2011/10/08/opinion/martinoccupywallstreet/index.html?hptpo_r1 Users/ConsciousConsumer
  Yes  heres http://www.thedailyshow.com/watch/wedoctober52011/parksanddemonstration Jon Stewart on a similar note.  cp
   Im one of those people made uncomfortable with the clenched fist.  The issue of money and politics is so important to me that I try to suppress that reaction for the time being. Users/SueHjerpe
   Glad to see that there is a globe instead of a fist for the poster for the third GA.  :)  Occupy Together  Change the World is a good message.  cp

20111011 21:21:55 nbsp is occupy Davis interesting in learning information about the water rate hikes? Users/StevenDaubert

20111012 08:19:04 nbsp If the other occupation movements are any indication, Occupy Davis will hear anything important you feel the need to share. Users/EdwardNiemand

20111013 12:11:07 nbsp The participants on Octobr 12 appeared to be hard core.  I went by the tree with the platform around it.  They had to contend with the live music in the park.  I suppose to make sure everyone could hear what was said they got into a kind of call and response where when someone said something a bunch of people repeated it.  I didnt have the fortitude to stay long.  Users/BruceHansen
 20111014 01:02:50 nbsp Thats how theyre doing it in New York because the NYPD said they cant use bullhorns. I wonder if the Davis folks are doing it to be cool or because the Davis PD actually told them the same thing. Users/AndrewPotter

20111013 20:38:54 nbsp why dont you leftist liberals investigate the liberal democrats in congress and the current president of this country and you will find they are the people that are responsible for the problems this country is having economically...Clintons attorney general janet reno threated the banks if they did not loan money to people who were not good risks...people who were sure to default on such a loan.....obama puts people in high positions in government that are from the corporate world,doing the very thing that you want to protest againts....General Electric for example....Then obama funds a big green company that goes bankrupt after taking huge sums of taxpayer money...obama is the cause of most of our problems...investigate him. Users/jerrydavis
  •Wow, why so angry? I dont see anything particularly leftist in this, I see more populist. Why are so many people so fast to denounce this movement and make it partisan?dm
  •The points mentioned are worthy of consideration.  The leftist liberals doesnt jive with the slogan We are the 99% however.  It can be noted that this movement is different than the tea party. Users/BruceHansen
  First of all calling anyone in the US government leftist is laughable (besides maybe a handful of congressmen). If you are under the delusion that Obama is a leftist you are detached from reality and need to turn off fox news. Are you really going to ignore the wars in the middle east, deregulation and tax cuts for the rich as potential problems for the economic crisis? Seriously? ~~~~

20111014 02:11:11 nbsp Agreed. Some egos out there are getting hurt. People who dont understand it seem to be trying really hard to put it in a box. Just be part of the discussion. Be open to new ideas, theres no right or wrong, just different perspectives. Some of the democrats may be trying to take this movement under their wing. That doesnt really mean diddly. Just do more research, read into more of the links above. Look outside of the US for some objective media, the media in this country is a part of the 1%. Users/ConsciousConsumer
Yo ConsiousConsumer talk to whatever group was making pre protest plans and ask them if they want more info about the water rates!
  HeyDaubert I only just saw your post. Get on the forum discussion at occupydavis.org and they would be willing to discuss it with you. Info always helps.   CC

20111014 10:04:39 nbsp I just listened to Forum on KQED 89.3.  It covered banking and consumer choices in service and providers. http://www.kqed.org/radio/programs/forum/ listen here  Users/SueHjerpe

20111014 17:33:47 nbsp Could there be another way to do this, petitions? Living in the park 24 hours a day in the beginning of fall makes me think the 1% again gets the last laugh, or do something just different to make so many wrongs a right.  Users/Theangrydiner
  I think the biggest success so far is getting the media to cover the movement and eventually its issues.  I dont think petitions are visual enough. Users/SueHjerpe

20111015 16:41:32 nbsp So Im a little unclear on the goals of the Davis and national movements, other than to generally protest the financial system.  Can someone enlighten me? Users/IDoNotExist
  There is a lot of info right on this page, on the top of the page, in the above comments, and in the links.  One place to start is the video of Keith Olbermann reading the Statement Released By The Wall Street Protesters, linked to above.   Users/CovertProfessor
  Thanks, CP.  But what I mean is, beyond protesting things that are wrong (which the statement in the video does, and what the protests are doing (from what Ive heard), what solutions are being proposed?  (i.e. Beyond saying Were really mad about these things!, it would help to hear ...and here is how we propose to change things so that the things were mad about dont happen any more!   Users/IDoNotExist
   Is it really that hard to figure out?  Fix the election laws so that politicians dont end up in corporations back pockets.  Stop the tax breaks to corporations.  Stop letting corporations get away with wreaking havoc on the environment.  Restore balance to the tax laws so that multimillionaires pay a reasonable tax rate and so that most of the nations money isnt ending up in the pockets of the 1%.  Prosecute the banks accused of wrongfully foreclosing on homeowners.  Pass a real stimulus package that builds infrastructure and invests in research and development while creating jobs.  Reinvest in education so that students dont graduate with insane amounts of debt.  Im surely leaving things out, but the bottom line is: be a government for all the people, not a government for the few and not a government for the corporations. Users/CovertProfessor
   One thing I like about this movement is that it seems like it recognizes that solving the disparity between the rich and the poor is a complex issue and isnt staking out some unreasonable demands on how to get to a solution. What theyre doing is raising awareness of the problem, hopefully creating pressure on politicians to do something productive. Users/AndrewPotter
    Covert: I think there are lots of things that could be done, some of which you stated.  But what Im asking isnt what can be done, or whether Im aware of any possible solutions.  Ive been aware of the problems and potential solutions for a very long time.  What Im asking is whether the movement has adopted any of those solutions, or other possible ones, as goals that they will actively promote.  Protesting raises awareness.  But demanding specific solutions results in change.   Users/IDoNotExist
     These are all solutions that I have heard many protesters propose, and they seem to follow directly from the things that the protesters are protesting.   Users/CovertProfessor

20111015 19:46:05 nbsp Hope you guys are more respectful of local business than the wall street protesters are being.  Not sure what occupying in Davis will do specifically but peaceful assembly is an important right so kudos on exercising it. Users/OliviaY

  First the businesses around wall street arent local in the since of small. Many are corporate chains. Second, how do you know that street protesters are not being respectful in NYC? Have you been there and spoke with people or are you getting your information from charged news stories? You realize that news in our country is more entertainment then fact right? You realize they try to create controversy because that is more interesting then plain facts? ~~~~

20111015 20:45:50 nbsp One thing I would like to see happen is for us to get rid of the tipping system in the United States and force corporations to pay real living wages and stop forcing customers to pay the difference. It has gotten worse over time  Im seeing more and more people working for tips alone and I shouldnt feel the guilt and obligation to help them out like I do. The corporation should be paying those wages. Just look at the wiki of tipping around the world to get a sense of how stupid it is here in the States...http://en.wikipedia.org/wiki/Tip_%28gratuity%29
I just wish our government (and many citizens) would stop being so arrogant and learn from the successes and failures of other countries around the world. I honestly think a parliamentary system would do better than what we have. Our current system has allowed the 2 major parties to consolidate their power, because people are afraid to vote for a 3rd party for fear of allowing the republicans to win (e.g. Ralph Nader stole votes from Al Gore in 2000). Just look at this to see how far apart our politicians are compared to the rest of the world >http://www.politicalcompass.org/ Users/ConsciousConsumer
  No thanks. oy
   Youre against corporations paying living wages? Can you make some possible suggestions on how to improve the system then? This movement is all about discussion. Ive lived in Australia on exchange and while working casual hours at a coffee shop, I received $21 an hour, X 1.3 on Saturdays and X 1.5 on Sundays. That is the norm over there, and the only place where people tip are fancy cocktail bars or something. Voting is mandatory, which you could argue is a good and a bad thing. But at least more than 56.8% of the voting age population contributes to decisions in who runs the show. Im not suggesting that we just get rid of tips overnight, but it is just another thing in this country that has come into being without people questioning hey, why do we do things this way.  CC
              Thats two separate issues.  1  tipping and wages.  Theres seven states, including California, that require servers to be paid at least minimum wage, regardless of tip.     2  Minimum vs living wages.   Merging them together makes it a much harder sell.   users/edwins ES
               I didnt say anything about minimum wage (but on that note, what percentage of the U.S. population receives minimum wage?) and $21 isnt the minimum in Australia (I think it is around $18 for a casual adult). Businesses just dont always offer the lowest wages possible like they do here. Im not trying to sell anything, just elicit some discussion and possible suggestions. Any ideas users/edwins ES?  CC
                    That was my point, that you didnt :P  You said tipping system in the United States and force corporations to pay real living wages and stop forcing customers to pay the difference   I believe my idea was that thats two separate issues.  1  tipping and wages.  Theres seven states, including California, that require servers to be paid at least minimum wage, regardless of tip.  Its the other states that allow people to be paid below minimum wage, as long as they get enough tips to make up the difference.  Before focusing on 2  minimum vs living wages, address the first issue in the other states?  Get everyone paid at least minimum wage?  Seems like good target goal if you feel strongly on the tipping issue. users/edwins ES
                    Also, theres 3.6 million workers with wages at or below the minimum making up 4.9 percent of all hourlypaid workers.  according to Characteristics of Minimum Wage Workers: 2009. U.S. Department of Labor. Accessed September 8, 2010.
                    Ok, I see what youre saying. Good point. What do you think the minimum wage should be?  CC
                        I dont know, and dont feel qualified to throw numbers into the air.  I know that the current federal minimum wage is $7.25, and that Californias minimum wage is $8.00.  In regards to your interest in tipping and wages, perhaps the current seven states with laws about tipping/minimum wage should push for expansion, either a federal law or having the other states enact similar, whatever.  Getting everyone paid the federal minimum seems to me to be the first step in addressing this issue, before trying to figure out what the minimum should be.  users/edwins ES
                            You dont need to be qualified to throw numbers in the air, its an opinion. Im gonna go ahead and say the federal minimum should be raised to $10 and even then it should be structured so that if youve been working at a place for a certain amount of time you should be guaranteed some form of job security or benefits as an incentive and reward. Theres no harm in thinking beyond the first step, in fact I think more people could benefit from being concerned with future generations and future steps.  CC

     You cant compare one single aspect of how another nation operates to ours and go Hey must be better! Australians also pay more in taxes AND have a higher cost for many goods than we pay here.  It is an entirely different system.  You can prefer that one and if you do, nothing stopping you from staying there.  It would be a boon to them since, according to a select group of Aussies I know, the young are leaving in droves because the government there is SO oppressive.  On a totally unrelated to living wage tangent, Australia also has started to regulate what cup size women can have who work in the porn industry. And mandatory voting?  I love that people who are too lazy to care dont have a say in how I live my life.  I dont imagine Snooki votes and a country where she does? Again I say: No Thanks.
           So would you like me to compare every aspect then? Still no suggestions hey...  CC
              Okay, Im a permanent resident of Australia and I have no idea what you are talking about when you say that the government is oppressive and the young are leaving in droves. This sounds like hyperbole to me. Although the country is minimalist in terms of social safety nets, the government there is much more effective than that in the U.S. in terms of social welfare benefits and I have not seen the oppression to which you allude. Regulation by government can be a very healthy aspect for society if it regulates corporations in favor of people (which it often does). I am here in the US because I want to make positive changes, despite the fact that it is much easier to live in Australia (because the higher taxes give more benefits to people who need it and the higher wages more than account for the expense of goods, which is one reason that Australia is less stratified than the U.S.). I dont know anything about porn in Australia so I cannot comment on that, but mandatory voting can actually be very positive. At least people can say they choose their government representatives, where as in the U.S. roughly half of the citizens choose their government. It is not safe to assume that people generally do not know the representative/party for whom they vote. Of course there are those who make ignorant decisions, but mandatory voting gets more people involved in politics and allows them to utilize their political voices. There are those who make ignorant decisions when voting in the U.S., too, despite the fact that voting is not mandatory. I do not want to get into a battle of Australia vs. the U.S.; they both have merits and terrible disappointments (especially since Australia is following in the neoliberal footsteps of the U.S.), but I just wanted to say, dont knock it until youve lived there. NtnM
                 Yes I especially love how Australia censors the internet to such an extent that Google and Yahoo had to say enough putting it in leagues with China and Iran for having some of the most restrictive filters around.  Awesome!  Mandatory voting will not get more Americans involved in politics, that is yet another fantasy.  It will simply be a drudgery that most people will perform to get it out of the way and will make totally ignorant decisions.  Hell, a large number of voters who DO vote do it for stupid reasons.  Among them hes cuter or he seemed more honest or worst of all: voting along party lines without knowing a damn thing about the candidate.  You cant force a mind and you cant hold a gun to someones head and force them to be free.  Its a completely absurd idea.  NO THANK YOU.oy
                  Haha, that is ridiculous. Provide your sources please. You appear to be the only one living in fantasy land. Especially if you think that the U.S. doesnt censor its population (I can guarantee they censor more than Aus does). Still no solutions either... We dont care if you are a selfconscious libertarian that thinks your suggestions will get shut down (which is what you are doing BTW). Provide some positive solutions instead of repeating what you dont want.  CC
                      http://techcrunch.com/2007/12/30/australiajoinschinaincensoringtheinternet/  and http://en.wikipedia.org/wiki/Censorship_in_Australia  I especially like the line  Censorship of video games and Internet sites hosted in Australia are considered to be the strictest in the western world. http://opennet.net/research/australiaandnewzealand   And I didnt say shut down, I said shouted down and told to die which has happened often.   Oh and the US doesnt have the strictest censorship but they do rank top 3 for mining data on citizens.  Love government! oy
                       The first link is from 2007  He is no longer PM and that stuff never went through  http://en.wikipedia.org/wiki/Internet_censorship_in_Australia. Also, I am not completely against censorship when it has to do with suicidal content, extreme violence, child abuse, sexually explicit materials etc, particularly when it is on tv early in the day. That seems to be the vast majority of what is censored in Australia. Find me something controversial. If you want to be a part of the discussion, then please be constructive. I would really love to hear your ideas for a better U.S.A. I understand general libertarian stuff, smaller federal government, more states power. Are you proposing free market capitalism be allowed to operate unregulated? I really want to understand where you are coming from and how you would like things to work. Sell it to me and I might come around.  CC
 Leaving Australia.  This data piece is from 04, but it shows the start of the trend throughout the 90s:  http://www.aph.gov.au/library/pubs/rn/200304/04rn54.htm      However, found data from immigration up through 08: http://www.immi.gov.au/media/factsheets/05emigration_1.htm   Both of you should note that arrivals/departures are both going up.  Whats more relevant imo, is WHERE these people are coming from and going to.  A lot of my family moved to Australia throughout the 70s and 80s as refugees.  Anyway, the factsheet states In 2009–10, 42 570 Australiaborn people departed permanently. This figure includes the Australiaborn children of former settlers.  Overwhelmingly, the Australiaborn are emigrating to the United Kingdom, the United States or to New Zealand. In 2009–10, 46.3 per cent of Australianborn emigrants went to one of these three countries.    Id guess the netflow to those countries is outwards, and the flow inwards is more diversified.   But I dont care enough to find the data, just thought a few numbers to chew on might help.  Or muddle.  users/edwins ES
                  Id like to hear your libertarian view on this Users/OliviaY, What is your view on how we get corporations to stop polluting?  http://www.rollingstone.com/politics/blogs/nationalaffairs/australiancarbontaxvoteaverybigdeal20111013  CC



20111015 I have to agree with BarnabasTruman on this: it does no good whatsoever to protest in this town. You need to have protests at the right locations, like corporate headquarters or state governments. You want to show how annoyed and mad you are? Show it directly to the people doing it to you. You really need to get some carpools together or bike to Sac and go to the state government to protest things. It doesnt do a darned thing to make a stink in this town because those people arent here to know.

I was in the park for most of the day today and what did I see? Folks sitting around in a circle talking for hours. Sometimes someone was playing a musical instrument. If I hadnt known what to look out for given the signs in the park (plus one random dude asking me where they were when the circle was down to a small number and less obvious), I wouldnt have thought, hey, those are protesters there. I hate to say it, but big deal? Ive seen more noisy protests at freaking Mrak Hall (which, btw, is also a waste of time to protest at for state budget cuts. Nobody who works there can do anything about the situation either). I didnt see news vans, I saw one bike cop rolling on by. Who was affected by this? Who proved a point? I guess all of yall who went felt better, but otherwise I just dont think protests here are effective. You want to AFFECT the people who can make the changes, and this protest so far isnt doing it. Sorry, but its not.
Users/JenniferRutherford

20111015 22:16:50 nbsp As Doug Walter mentions, one great step is banking with a credit union.  We have quite a few choices here in town.  Just like the Davis Food Coop, YOU OWN IT! I highly recommend the Yolo Federal Credit Union.  People who live in our community make up the board of directors. If you have one, you can also move your mortgage to a credit union.  Of course, that can be easier said than done, depending on your credit rating in the current economy.   http://www.yolofcu.org/ Users/RhondaGruska

There is, and will only ever be, one Users/DougWalter.
Users/JerseyCity

So true, so true! Editing done.

20111016 11:11:53 nbsp In response to JenniferRutherford, the whole point of a peaceful protest is to be just that  peaceful. If you want yelling and marching and news vans, theres a greater chance that things can get out of control and make the whole movement look bad. I work in a bank downtown and have been walking around worrying about what could happen if things get out of control. I completely support this movement, but I also like knowing that when I go to work Monday morning, Im not going to have to worry about a potentially dangerous situation. Also in response to CovertProfessor, yes, it was that hard to figure out. Outside of this page the ONLY place Ive been able to find what the movement wanted was on Keith Olbermann. If this movement wants to be really successful, theyre gong to have to be more straightforward with the solutions theyre offering. Were not all professors, covert or otherwise.  Users/CCarlson
  I apologize for saying that it was obvious if it wasnt.  Its true that Ive followed the protests quite a bit, so perhaps that is why these things seem obvious to me.  In that case, then, I hope my characterization of goals was helpful.  Of course, thats just my take on things.  Users/CovertProfessor
   You really dont have to be a professor to read the links provided on this page and click on links within those pages. This is a leaderless movement, all you need to do is look at some of the comments people are making on the Occupy Wall St website and understand that the problems within this country are vast and cannot be summarized in a soundbite or neat little paragraph. Maybe start watching and reading alternative media  democracynow is a good place to start. http://www.democracynow.org/  CC

20111018 10:35:56 nbsp http://www.alternet.org/vision/152773/occupy_wall_street%3A_992_arrested_at_price_tag_of_more_than_%243.4_million Users/ChristopherGomezWong

20111018 23:14:56 nbsp Yet another area Wall St has messed up. The Food Bubble: How Wall Street Starved Millions and Got Away With It http://www.democracynow.org/2010/7/16/the_food_bubble_how_wall_street Users/ConsciousConsumer

20111020 09:42:26 nbsp There was about a dozen or so people camping out in the park last night. One of the protestors told me that they are hoping to stay for a full month. Im glad that the Davis PD hasnt given them any problems yet. Users/ScottMeehleib

20111031  Since it is our federal and state government that creates, oversees, and implements tax policy (the redistribution of wealth) and regulation over businesses of all sizes, why isnt it Occupy Pennsylvania Avenue or Occupy the Capitol?  Isnt this where the change has to start? I dont think Wall Street gives a rats rear that it is being occupied or protested. Just something to consider.   Calzephyr
  I agree with you that there needs to be political change, but I see the two things as going handinhand: the Wall Street corporations have engaged in shady and illegal practices that need to be prosecuted, with new laws and policies to rein in their behaviors and their influence on our political system.  People are protesting in D.C., too, not just Wall Street; in part, people are just protesting in the places they live (in solidarity with each other), and in part the name Occupy Wall Street is to signify (and remind us!) that it was Wall Streets practices that got us into this economic mess in the first place.  (And yes, the politicians did not handle that situation well.  They gave them money because the banks were too big to fail  no strings attached).   Users/CovertProfessor

20111106 17:43:05 nbsp Ive got one question for people who are protesting: Who specifically do you want to follow what course of action?  Users/MasonMurray

20111107 09:43:29 nbsp I would say that the Occupy movements had their first solid success with Bank Transfer Day. It has been estimated that over 650,000 customers chose to leave behind big banks in favor of nonprofit credit unions in the days leading up to the Nov. 5th deadline. Bank of America backed off of its previous plan to have a $5 monthly charge for debit card use, which was one of the cited reasons for the bank protest to begin with. I would challenge the Occupy movement to continue to look for practical solutions like this. A lot of awareness has already been drummed up, and now new ideas for solutions need to emerge quickly in order to keep the ball rolling. Otherwise, the group runs the risk of looking like a neverending sleepover in favor of a redistribution of wealth that wont come about simply through awareness. Users/ScottMeehleib
  You might be interested in http://iamlaurenleonardi.wordpress.com/2011/10/26/elevesimplewaystosupporttheoccupymovementwithoutsleepinginapark/ 11 (actually 14) simple ways to support the occupy movement without sleeping in a park.  #12 and #14 in particular seem like concrete actions of the sort youre looking forward, although theyre not as good as Bank Transfer Day.  Personally, Id like to see the Occupy movements take up the banner of getting people registered to vote and then actually getting out the vote.  There is all of this energy, and one constructive place to put it is to 1) let the U.S. know that their voices will be heard on election day, and 2) actually show up to have your say!   Users/CovertProfessor
     I think it would be great if a massive amount of people got behind #12 in particular. Getting people registered to vote is also a good idea. SM
      #12 is very cathartic; I highly recommend it.  I think #14 would be better if it were shop local and independent for the holidays rather than dont shop on Black Friday.  It gives that as an alternative, but I think it should be the main suggestion.   Users/CovertProfessor
       Ah, it looks like someone has taken up the banner of shopping local on black Friday: http://www.facebook.com/buylocalday Green Friday: National Buy Local Day Nov 25.  I think this is a fabulous idea!   See Green and Local Gift Ideas. Users/CovertProfessor

20111108 10:31:29 nbsp I have dropped in and chatted with Davis Occupiers a couple of times over the past week or so. I was impressed with their dedication to keeping it together. By which several said they meant maintaining the camp site and keeping everybody fed and dry on cold, rainy nights. Also, they expressed satisfaction with their success in communicating with Davis police officers with whom they have had good relations. One said it was good to see a prowl car roll by at 3am, just to make sure were safe out here. Also, they appreciated the response from city maintenance workers who turned off sprinklers, which had come on automatically during late night hours. But, though I suggested conversational topics along the lines of politics and economic injustice, the Occupiers expressed little awareness of or interest in discussing them. As conditions worsen, perhaps the Occupy message will come into clearer focus Users/RaoulDuke

20111114 00:11:55 nbsp The Occupy movement did not do anything to stop Bank of America from adding fees.  Banks let them think theyve won but in actuality are just adding new charges in other places.  http://www.nytimes.com/2011/11/14/business/banksquietlyrampupconsumerfees.html  Just something to keep in mind.  Users/OliviaY
  As far as I was concerned, the $5/month fee was not the main reason to switch away from the big banks to the local banks or credit unions  the $5 fee was just the tip of the iceberg, a very visible indicator of all of the other ways in which the big banks act reprehensibly.  So, anyone who thinks that BoA getting rid of the $5 a month fee means that the protesters won is missing the big picture, even without the ramping up of other fees.   Users/CovertProfessor

20111114 20:37:24 nbsp Ive been occupying in New York, Oakland, and Portland Oregon. This is the BEST OCCUPY LOCATION IN DAVIS HANDS DOWN!!! Users/KCSlater

20111114 23:14:15 nbsp The action tomorrow should be interesting! I just read the counter protest thing also... hilarious. We should have a mock 1% protest and join them. haha
Check out the new story of stuff video called the story of broke its great!!! >http://www.storyofstuff.org/moviesall/storyofbroke/ Users/ConsciousConsumer


Did this really happen? UCD + students + pepper spray? Can someone who was there speak to this? When did this occur?
http://www.youtube.com/watch?vWmJmmnMkuEM&amp
Updated: Protests Additional info
 Users/JoRo
  Yes, this actually happened. Students last night set up tents in the Quad. They were gently reminded by some police officers that sleeping there was against the law and they should probably go home.  This morning they were asked again to leave and refused, so the police showed up in force to hopefully keep anyone from being injured.  As you can see in the video a row of students sat in front of the cruiser as I understand it to prevent them from leaving with students that had been arrested.  Further, (and again, this is 2nd hand knowledge) the police warned students that if they didnt move they would be pepper sprayed.  In short, if you got sprayed it was because you chose to.  The police gave you every opportunity to just leave.  users/Masonmurray MM
   RIGHT, the police were PROTECTING the students. Those dang tents sure can be dangerous. P.S. They were not blocking a police cruiser from leaving. Maybe if you were there you wouldnt misrepresent the situation.
      Thats the difference I guess. Some people think pepper spraying peaceful protestors is acceptable. Others, not so much. users/Sjoe
       W...WHAT? Who said anything about either of those things? The laws are there to protect EVERYONE ELSE from the PEOPLE BREAKING THEM. Its private property, without permission the right to assembly doesnt apply to campus any more than it does to your neighbors kitchen. So yes, I think that laws preventing unauthorized camping on public property are good. Tent cities are unsightly, and obstruct maintenance.  You want to protest thats fine. Do it on public property with a permit like everyone else.users/Masonmurray MM
        Creating something unsightly warrants being sprayed in the face like a bug?  And you say the police showed up in force to hopefully keep anyone from being injured.  I saw people sitting quietly on the ground.  So, exactly who were they protecting from injury?  The only ones causing injury were the police themselves.   Users/CovertProfessor
         MM I really question your choice of words.  When people break the law, police have the authority to arrest them if their crimes justify arrest.  In this case, the crime was basically a very mild form of trespassing.  I find the current attitude of law enforcement that the pretense of nonviolent protesters can and should be resolved by torturing the protesters until they comply.  Pepper spraying peaceful protesters for being unsightly is highly objectionable to me, and I think or at least hope most Americans would share my view. Users/rfrazier
         The Ancient Order of Walkers has asked me to remind you of the existence of legal precedent suggesting that use of pepper spray against peaceful protesters committing trespassing is excessive force, and that this should be clear to a reasonable officer. http://caselaw.findlaw.com/us9thcircuit/1332957.html  Users/BarnabasTruman
          It comes down to something very simple.  When a police officer walks up and says Go home, you are not allowed to gather here right now. If you dont, Ive got this can of mace, and you say No thanks, Id rather keep my seat, you lose all my sympathy.  But if I could direct you to how this began, all I did is answer a simple question to the best of my ability with the facts I had at hand.  If there is anything FACTUALLY UNTRUE about what I said, Id be more than happy to hear it, just know youre not going to change my opinion just as I dont expect to change yours.  users/Masonmurray MM
             At the time this occurred, the tents had already been dismantled. The students were not blocking access of any type to any police cruiser. The students were told to leave the campus, which they had every right to be on at the time as students. They sat, quietly, arms interlinked in front of the police. The can of pepper spray was brought out, with very little warning, and waved around as a warning for all of 5 seconds prior to being used. It is excessive force, extremely questionable legally, and is completely and utterly disgusting to me.  Users/WesP
              As I said at least three times, the information I had was not first hand, and it was what I had to work with.  I would have been there if I could, but I have to work to keep food on the table.  Going on midweek camping trips is not a luxury I can afford. users/Masonmurray MM
             users/Masonmurray MM, would these protestors have had your sympathy if the police had, after warning them repeatedly to disperse, walked up and shot them all in the head?  I hope your answer is yes.  Clearly the police had no intention of doing this, and didnt, but my point is that violating a police order, or even breaking the law, doesnt in itself justify any arbitrary amount of force.  The burden is on law enforcement to explain why that particular level of force was necessary in that particular situation.  users/KenjiYamada
              If anyone said You need to leave or I shoot you in the head and you chose to stay? No, you would not have my sympathy.  I dont care who pulled the trigger.  Chosing to be shot in the head is suicidally stupid.  There may be a question of whether or not the person had the right to make you move, but you dont try to make that distinction while theres a gun to your head. users/Masonmurray MM
               In such a situation, the only choice that matters (from a legal or ethical standpoint) is the choice made by the person with a finger on the trigger.  Users/BarnabasTruman
                Okay, so youre ethically right and you have the law on your side!  Youre still just as dead, and you chose that outcome.  Why should assisted suicide be worthy of sympathy?  users/Masonmurray MM


20111119 06:33:36 nbsp The standard is pretty simple an activity is either compliant with the law or it is not. If the group is compliant great. If not, then those entrusted to enforce the law are compelled to do so, no matter what the appearance (pepper spraying sitting protestors)  otherwise we are on the slippery slope of deciding what laws to enforce in our society.  Agree that this effort loses my sympathy entirely when the law is broken please do it within the framework of our laws. My perspective anyhow. thx. Users/RichardL
  to be very frank, that seems like an extremely myopic view to me.  I speed while driving very regularly.  Should I be pepper sprayed until I agree to stop?  If a citizen is jaywalking, should he be pepper sprayed until he agrees to stop?  The idea that any violation of the law justifies any and all force is repugnant to me.  The police and their supervisors have a duty to act in the public interest while enforcing the law.  I dont think anything close to a majority of Davisites would agree that pepperspraying members of a peaceful protest movement is in the public interest.  When law enforcement acts this way, I become very concerned.  The thought process that if I dont torture this student, he might still be sitting here tomorrow, harming no one but in defiance of my will, OK I guess Ill torture him is utterly repulsive.   Users/rfrazier
  The idea that the job of the police is to punish is repugnant to the foundation of our justice system. Are you suggesting that the police and the police alone should serve as judge, jury, and executioner? Let the police arrest, and let the courts decide on punishment.  Users/BarnabasTruman
  And since you bring up either compliant with the law or not, I will point out that attacking peaceful protesters with chemical weapons is NOT compliant with the law, regardless of what uniform the attacker is wearing. Does that mean that the man with the pepper spray should himself be pepper sprayed? Of course not.  Users/BarnabasTruman
   Yes, actually.  Thats exactly what that means. Hold that man down and mace him. Hell probably never do it again. users/Masonmurray MM
    But hold on  torturing people as punishment for crime isnt part of our code of laws  so I guess well have to mace everyone who maces the officer, and then mace everyone who maces them, and so on.  Sooooo...if we followed your plan, wed end up with an entire city of maced people.  MM, I think we may have found a flaw in your otherwise brilliant strategy for dealing with nonviolent protestors.  Maybe we should consider just NOT macing them and instead try ticketing and arresting people for breaking the law, and only using violence, such as mace or batons when officer safety or public safety is at risk.  Allowing cops to torture people for nonviolent noncompliance with the requests is madness and sets and extremely dangerous precedent.  Users/rfrazier
     Actually, the officer was undoubtedly already maced during his training.  I just found this out the other night, and that satisfies my call for him to experience it first hand.  And yes, the person who maced him was most likely maced themselves. ION: Im an Anarchist, not a Fascist, but if were going to have the rules they must be enforced uniformly.  Saying that it is OK for protestors to camp in the quad means its OK for everyone to camp there. Anything less is brazenly claiming these people are better than everyone else.  Further, at no point did I say that I supported the actions of the police in this situation.  All I have done is condemn the actions of the protestors.  users/Masonmurray MM
      A  protester may do what he or she believes in and have an expectation of the consequences; you choose to condemn; and the police can not do their job properly and trash UC Davis. Users/BruceHansen
      EXACTLY. Finally someone who agrees with me.  I dont know so much about the police trashing UCD, it doesnt look any worse than it did a few years ago (aside from the tents...)  users/Masonmurray MM
     Im not about to follow rules, just because they are the rules. Why should I? When clearly those rules dont apply equally to those with influence and power. As an anarchist how do you feel about the oxymoronic concepts of free speech zones and protesting permits? Because to me they are absolutely ridiculous and go against everything this country claims to be. This corrupt system is human created and can be just as easily dismantled. This is why I would choose to be noncompliant just as Gandhi was in aparthied South Africa and Colonial India. At the end of the day we all have to live on this earth so why do we bicker about whether or not the rules say someone is allowed to pepper spray someone in the face if they are in the way, just walk around them and carry on with your life.  Users/ConsciousConsumer
      Im going to try and respond in order, because Im tired and it probably wont flow without that structure.  You should follow the rules if you dont want to accept the consequences, and if you chose not to follow them you shouldnt complain loudly that there were consequences for your actions. Thats life.  As an anarchist, I oppose many, many laws, those included.  However, if I choose to protest at some point, I will probably get said permits because I would rather not see my protest broken up part way through.  I also oppose how strictly fire arms are banned from school campuses, but no one ever seems to take me seriously on thatFootNote(Personally, I still wouldnt bring a gun on campus, its just the principle of the thing. ).  why do we bicker about whether or not the rules say someone is allowed to pepper spray someone? Me? I dont care if theyre allowed to or not.  Im having trouble summarizing my standpoint, so Ill just say this: An adult takes responsibility for their actions while a child tries to place the blame on someone else, and I dont see how choosing to be maced is worthy of sympathy.  Ive never heard of anyone going down to the police academy saying oh those poor dears during mace training.  And finally, why the police shouldnt just walk around them, Im also pretty sure thats the exact opposite of their job description.  Correct me if I am wrong here, but isnt their job to... I dont know... enforce the laws equally and without discrimination?   users/Masonmurray MM
       Of course there should be consequences for actions, and of course if you break the law, you can expect to be punished for it.  Nobody is arguing this point, so Im not sure why you keep acting like theres a disagreement about this topic.  If the police had arrested or ticketed the protesters, nobody would have a problem with it  thats part of protesting and civil disobedience.  Sometimes being arrested to indicate how seriously you take a cause is the point.   The issue here is that cops thought it was OK to torture students with pepper spray when the students did something they didnt like.  This action wasnt necessary to protect themselves, it wasnt necessary to protect anyone else, and using torture to punish people is antithetical to our system of law enforcement.  You have no sympathy for them.  I get that.  I dont get why you have no empathy for the students, and I further dont get why you keep claiming to be an anarchist when you seem so anxious to grovel at the feet of anyone you perceive as an authority.  As an anarchist I suppose you can absolve yourself of any responsibility for what happens in our society.  As an American, Im afraid I dont have the luxury.  I have to care that police officers acting in my name are breaking the law, and that my fellow citizens are having their rights suppressed through torture as a result.   Users/rfrazier

20111207 19:41:55 nbsp we can oppose something without making davis unpleasant by having tents in the central park. please remove those. I am 100% positive that this movement is great and it will have results but I dont like seeing tents every freaking day when Im driving home.  Users/mahmoudrezanaemeh
  YEAH! How DARE they make you see TENTS for five whole seconds when driving along 5th Street?!? The nerve of those people...

 YEAH its awesome when you see that people who are camping there are actually homeless and they dont even care what the 99% is
 Thats quite a few assumptions all rolled into one little reply.
     $$  YEAH  Cant wait to vote next year for some more hope and change and yes we can and yes will and yes we did, and then take a walk through a city park and smell the pepper spray. Right on Obamanomics, you go baby!
       Obamanomics is just a continuation of the neoliberal agenda that has been perpetuated since Reagan. The United States would do well to get away from the twoparty vote for the lesser of 2 evils model that is in place, since both parties are currently funded by the exact same interest groups. Just look at Jack Abramoff and others and how much inluence unelected lobbyists have over our politicians nowadays.  Users/ConsciousConsumer

20111213 15:18:07 nbsp This bank sounds outrageous  charging recurring daily overdraft fees which shouldnt have been charged in he first place.  http://news.yahoo.com/illinoisteenlearnsbankfeeshardway154654489.html How are the banks in Davis? Users/BruceHansen

20111223 19:17:03 nbsp What if the decision to evict or not had been made by referendum? Voters could have determined whether to continue the long overdue public debates over inequality, injustice and capitalism that were launched and sustained above all by the Occupy encampments...  http://www.truthout.org/ Users/ChristopherHitchens
