
Most people think that the Olive Drive Railroad Fence is ugly, with its silvercolored industrial look and its irregularly undulating top edge.

FENCE BUILT

In midSeptember of 2011, UP built the fence along the south side of the tracks. It has unclimbable, tamperresistant construction with a padlocked gate at Hickory Lane. The contractor was http://www.jrfenceinc.biz/ J & R Fence, Inc..



Summary of the Fence Proposal

The Union Pacific Railroad is building a 3800 foot fence between the railroad and much of Olive Drive.  According to an article in the Davis Enterprise (September 15, 2011), Union Pacific is starting construction next week.  “They’re basically saying, ‘We’re going to do whatever we’re going to do, and tough luck,’ “ Mayor Joe Krovoza http://www.davisenterprise.com/homepage/featuredstories/unionpacificstartsfenceconstructionnextweek/ said.

According to a RR Fence Op Ed Railroad Fence OpEd by Alan Miller, the fence is to be 8feet high, will be steel reinforced in wrought iron style and is claimed to be impenetrable by conventional means.  The material cost is approximately $250,000 and will be Proposition 1B funds allocated through the Capitol Corridor Joint Powers Authority which manages the Capitol Corridor trains.  Union Pacific will supply the labor to build the fence.  As currently proposed, the fence will run along the south side of the tracks only, from where Richards Boulevard passes under the railroad, to the east end of Olive Drive at the turnaround loop adjacent to the Olive Drive exit from I80, which is also the point at which the Highway 40 bike paths bicycle path begins.

The fence, if it remains unbreached, forces residents of Olive Drive to a single exit from the neighborhood, known by some as the worst intersection in Davis, Olive Drive and Richards Boulevard.  This legal route is much longer than crossing the tracks, as one must cross Richards, go through the bike tunnel, and then cross again at 1st Street 1st & E Street E Streets, a traffic patterns very long light where, strangely, a bike ends up on the left side of E Street and so has to cross E Street to ride legally into downtown.  There is also no rational way to go from the Borders side of the intersection onto 1st Street going east into downtown on a bicycles bicycle except to stop in the middle of the crosswalk going north and back ones bike into the traffic lane half way across and wait for the light, a very odd but semifunctional path.  For those going to east Davis from Olive Drive, there is no legal exit from the bike path until Mace Boulevard, some East Davis two miles east.  Some pedestrians/bicyclists going to points in east Davis will probably cross the tracks illegally past the east end of the fence to access 2nd Street, Pole Line Road and East Davis destinations.

Upcoming Events
(On Sept. 26, 2011, there are no upcoming events scheduled.)

Train vs. person incidents in and around Davis


A March, 2010 article by Users/GregKuperberg Greg Kuperberg in the Davis Voice, http://www.davisvoice.com/2010/03/themostdangeroushalfmileindavis/ The Most Dangerous Half Mile in Davis, addressed the major reason to put a fence along these tracks.  Four people have died along this section of track since 1998, making it the most dangerous half mile of rail in Davis as measured by tragic events fatalities per year.  The basic recommendation from this article is to fence both sides of the track, and to build a safe and legal crossing point. It is also illegal to cross train tracks in California except at designated crossings (http://www.leginfo.ca.gov/cgibin/displaycode?sectionpen&group0000101000&file369a402c California Penal Code § 369(i)).

Although these fatalities took place near the fence, the fence, had it been in place at the time, may not have prevented all of them.  Patrick Allison, in 2004, committed suicide; access to the point where he died will not be blocked by the proposed fence.  Fred Nightbear Iyotte, in 2007, died near the east end of the proposed fence, suggesting his death might not have been prevented had the proposed fence been in place.  Samuel Carrasco in 2005 had been drinking and was killed lying down on the tracks at 3am; his direction of entry to the tracks is not known.  The death of Nanda Butler in 1998 may well have been prevented as he was crossing the tracks from the Olive Drive area to East Davis just east of the notlegal, but well used, L Street crossing.  He had  been drinking and therefore may have misjudged his proximity to the train.  Three additional deaths occurred near the Arboretum Drive crossing, south of the south/west end of the fence, and another death was even further south near the Putah Creek bridge.  A death at 8th street was on the branch line to Woodland and not adjacent to the proposed fence.  Additionally, several deaths at Swingle, the Road 32A atgrade crossing east of Mace Blvd., are well beyond the fence limits.

The stated need for the fence and/or an overcrossing (these can be complimentary, not necessarily mutually exclusive) can be seen graphically in http://www.youtube.com/watch?vQCmQXeUBu1A this video, which shows daily life in Davis in which Olive Drive residents and visitors cross the railroad tracks, here accessing the Amtrak Station from Hickory Lane.

Past Events

The City of Davis announced that it has formally submitted an application to the California Public Utilities Commission (CPUC) to construct an atgrade pedestrian/bike crossing at the Davis Train Station.
http://davisvanguard.org/index.php?optioncom_content&viewarticle&id4616:cityformallyfilesforatgradecrossing&catid53:landuseopenspace&Itemid86 article.

 Update  midSeptember, 2011 

UP has built their fence.

 June 30, 2011 

http://www.davisenterprise.com/localnews/manfatallyinjuredbypassengertrainindavis/ A man was killed on the tracks this morning near Olive Drive.

April 25, 2011  UP Builds Fence & City Reacts with Statement

Union Pacific crews built short sections of tall fence in front of the Davis Mobile Estates and Slaters Court gates, blocking both gates.  This is the same military style fence used in other locations such as West Sacramento.

No notice was given to the City, other than UPs longstanding assertion that it would build a fence.  Crews were on site before 8 a.m. and were done before 10 a.m..  Union Pacific conducted a propertyline survey last month that showed that the gates are within their property; the City disputes this claim.  Union Pacific has turned up the heat on the issue and is asserting what it believes to be its right to build on its property and block the gates.

On that same evening, the City of Davis issued a http://cityofdavis.org/cmo/pressreleases/repository/20110425.cfm Press Release on Union Pacific Blocking Olive Drive Access Gates strongly condemning Union Pacifics actions:  The city is extremely disappointed that UPRR has chosen to proceed with construction of the fence to block these gates.  To see a picture of the fence, see the April 26, 2011 article in The Vanguard, linked in the media section below.

February 16th, 2011  Capitol Corridor Joint Powers Board Meeting

The meeting was in Suisun City at the City Council Chambers.  The fence was be discussed, with input from several Davis residents.  Union Pacific withdrew its request for public funds for the fence.

December 5th, 2010  Protest gathering

On December 5, 2010, about 40 members of the community Railroad Fence Event gathered at the train station Davis Railroad Depot to protest the construction of the fence without complimentary implementation of legal access alternatives.

December 10th, 2010  City staff meets with railroad representatives

City of Davis staff held a meeting in Davis on Friday (12/10) with representatives of Union Pacific (UP), the Capitol Corridor Joint Powers Authority (CCJPA) and the Federal Railroad Administration (FRA).  The representatives walked the tracks adjacent to the proposed fence.  The railroad and FRA were clear that a fence was needed and would be built.

The parties involved stated their intent to work with Davis on the exact location of the fence, the design details of the fence, the timing of the fence, and on a comprehensive solution to the access issues connecting Olive Drive to other parts of town.

The railroad continued to state their opposition to an atgrade crossing.  The railroad expressed doubt that the fence would create greater safety problems.  The railroad made it clear they will not be building the fence during the 2010 December holidays.  All parties are fully aware of the City and citizen concerns and the depth of concern the issue raises in Davis.  A public workshop with all involved parties may be held early in 2011 to solicit citizen input and disseminate information on design and funding possibilities/limitations.

December 14th, 2010  City Council meeting

Three members of the public spoke about the issue.  Staff gave a brief summary of the Friday meeting with representatives from the railroad parties.  Council member Sue Greenwald, who attended the meeting, said all parties were interested in working with the City.  However, according to SG the railroad stated that an atgrade crossing was out of the question because not only do other crossings on the same line have to closed (railroad or PUC policy?), but building a new crossing has to result in less people crossing the tracks.   This is an interesting position for the railroad to take, in that more people have died at or very near legal crossings in and around Davis in the last few decades than have died adjacent to the proposed fence line. Whether or not CCJPA funnels money into the project from Proposition 1B safety funds, the railroad stated that they will build the fence.  March 1 is a deadline for CCJPA committing funds to the project; construction may begin at that time or not be related to the release of funds.

The railroad representative agreed to inquire about allowing a bike/pedestrian path along the south side of the tracks by building the fence closer to the tracks.  This does not create a crossing over the tracks, and a crossing of Richards would require a bicycle bridge over Richards, parallel to the railroad, an expensive endeavor in itself.  This may also conflict with CCJPA/UP/City longrange plans to build the platform for the #2 Track (the southern/easternmost track) on the Olive Drive side of that track.  Ironically, this would involve removing the center platform, installing a fence between the tracks, and building an overcrossing to allow pedestrians to pass over to the other platform, and could be part of the solution to creating a crossing to Olive Drive by combining it with a walkway to Hickory Lane.  As well, departing mayor Don Saylor commented at the meeting about the desire to build an intermodal station on Olive Drive that would connect to Amtrak station via a walkway over the tracks.  This would allow the Amtrak buses to avoid winding through downtown as well as incorporating parking for regional drivers using the station with access of I80.

All these ideas could be combined and use a single walkway over the tracks.  The problem here is they have been talked about for over a decade, there is no plan in place, together require funds in the low $10s of millions range, and are not going to be built any year soon.  The fence, meanwhile, will be built within weeks or  a few months at the latest.

Public Workshop on Olive Drive Railroad Fence @ January 11, 2011 City Council Meeting

The issue was discussed for three hours at the January 11, 2011 City Council meeting. Representatives from the Federal Railroad Administration and the Union Pacific Railroad were present, giving presentations and to answer questions of the public and the council.  Oddly, the UP rep mostly spoke about Operation Lifesaver issues.  The oddest statement was that there was a nearby legal crossing of the tracks.  That is a statement that could be true or false depending on whether or not you actually have to use the Richards crossing or consider it near or far.  The woman from the FRA spoke on why trains had to blow their horns in Davis and that since there was no public crossing there was no crossing to remove or alter to allow trains not to blow their horns.  The universal reaction to her presentation was what the hell does that have to do with the fence?.  Twenty residents spoke.  None spoke in favor of the fence as proposed.

Alternatives to fence only plans

Combined with or without a fence, there could be one or more railroad crossings for pedestrians.  They could be like railroad crossings for cars, but narrower. These would have to be gradeseparated (a tunnel or a bridge), which is expensive. An atgrade crossing would be much cheaper, but Union Pacific has a policy that for each atgrade crossing that is built, two have to be removed.

It might be more productive to focus on options to improve the Richards Blvd intersection. The railroad does not have much investment in community unfortunately, and the City would have more leeway over changes to the intersection than work on Southern Pacific property. Traffic calming measures through the Richards intersection would have benefits to users passing from South Davis to Downtown as well, especially those on bike or foot.

Users/jefftolentino Jeff Tolentino makes the (satirical) proposal, Id like to propose a bridge built from East Davis to Burgers and Brew. I live in East Davis, and all my neighbors between here and Burgers and Brew have put up fences! More so, the City of Davis and their horrendous planning department, designed all the streets in just such a way that I inevitably have to ride my bike in some direction that is not straight to Burgers and Brew. Whats more, not only do I have to cross the train tracks, I have to cross L Street and 5th Street. Do you know how dangerous 5th street is? It sucks. Im tired of East Davis getting this sort of treatment. Its time to take a stand!

See also

  Relevant data and background information  https://davis.csbaagendaonline.net/cgibin/WebObjects/daviseAgenda.woa/files/MTI2ODgzNTcyMjM1OC9kYXZpc2VBZ2VuZGEvMTExLzIwNzkvRmlsZXM/1052809__olive_drive_report_final.pdf The Olive Drive Transportation Study: Analysis of Pedestrian Crossings of the Railroad Tracks near the Davis Amtrak Station
  RR Fence Op Eds and Letters  An Op Ed in the Enterprise by Alan C. Miller, and an Enterprise letter by Robert Canning and Tia Will.  (Note the comments section there as well as here.)
  http://robbdavis.wordpress.com/2010/12/07/olivedrive/ A local bloggers thoughts on the Olive Drive Railroad Fence and class
  Tragic Events/Train Accidents
  Tragic Events/Suicides
  http://www.facebook.com/home.php?skgroup_181081375239031 Olive Drive Preservation Society on Facebook.
  NIMBY
  Uri Geller, for the ability to bend metal with your mind and thwart metal fences. Also, beavers on sticks for wood barriers. Perhaps Ace Hardware, which sells http://www.acehardware.com/search/index.jsp?kwCatId&kwangle%20grinder&origkwangle%20grinder&sr1 angle grinders and http://www.acehardware.com/product/index.jsp?productId2895445 cutting torches (dont do anything illegal though!)


Media
  June 1, 2011: http://www.davisvoice.com/2011/06/citycontinuestoclashwithunionpacific/ City Continues to Clash with Union Pacific,  on The Davis Voice
  April 26, 2011: http://www.davisvoice.com/2011/04/thegreatolivedrivefencefight/ The Great Olive Drive Fence Fight, on The Davis Voice
  April 26, 2011: http://davisvanguard.org/index.php?optioncom_content&viewarticle&id4292:unionpacificinasurprisemovesblocksgateaccesstotracksangeringcityandmayor&Itemid86 Union Pacific In a Surprise Move Blocks Gate Access to Tracks Angering City and Mayor, on The Peoples Vanguard of Davis
  January 3, 2011 PENDING by Sarahni Pecson in the California Aggie.
  Dec 31, 2010 PENDING by Bob Dunning in the Davis Enterprise.
  Dec 30, 2010 PENDING by Jeff Hudson in the Davis Enterprise.
  Dec 15, 2010 http://davisvanguard.org/index.php?optioncom_content&viewarticle&id3941:unionpacificwillbuildwallonewayoranother&catid53:landuseopenspace&Itemid86/ Union Pacific Will Build Wall One Way or Another, on The Peoples Vanguard of Davis
  Dec 8, 2010 PENDING by Bob Dunning in the Davis Enterprise.
  Dec 6, 2010: http://www.davisenterprise.com/story.php?id101.1 Safer RR tracks solution urged, in The Davis Enterprise
  Dec 6, 2010: http://www.davisvoice.com/2010/12/doesthisfencemakessense/ Does the Olive Drive fence make sense?, on The Davis Voice
  Dec 6, 2010: http://davisvanguard.org/index.php?optioncom_content&viewarticle&id3919:proposedrailroadwallonolivepresentsvexingproblemsforcity&catid53:landuseopenspace&Itemid86 Proposed railroad wall on Olive presents vexing problems for city, on The Peoples Vanguard of Davis
  Dec 6, 2010: http://sacramento.cbslocal.com/2010/12/06/davistraintrackfenceprotest/ Plan to build fence along train tracks in Davis sparks protest, on Channel 13 News
  Dec 5, 2010: http://www.davisvoice.com/2010/12/connectingolivedrive/ Connecting Olive Drive, by Susan Lovenburg on The Davis Voice
  Nov 4, 2010: http://search.davisenterprise.com/display.php?id72110 Fence eyed to curb dangerous railroad track crossings, in the Davis Enterprise.
  Mar 16, 2010: http://www.davisvoice.com/2010/03/themostdangeroushalfmileindavis/ The most dangerous half mile in Davis, by Users/GregKuperberg Greg Kuperberg on The Davis Voice
  June 13, 2009 http://search.davisenterprise.com/display.php?id56163/ Small places, but large responsibilities, by Kirk Trost and Chuck Foster in The Davis Enterprise
  Feb 8, 2008: https://www.ble.org/pr/news/headline.asp?id21042/ Statistics on train accidents show no rhyme or reason , in The California Aggie

Related Articles on Cities Working/Dealing with Union Pacific:

  December 22, 2010: http://www.newtimesslo.com/news/5443/trailtonowhere/ Trail to Nowhere  SLOs Railroad Safety Trail for Cyclists is Being Delayed by Union Pacific by Rober McDonald in the SLO New Times
  Mar 11, 2009: http://www.indybay.org/newsitems/2009/03/11/18576324.php/ Union Pacific Fences in Homeless Encampment/ (Fresno)

Comments


20101205 14:34:23 nbsp As a new home owner in the Old East Davis portion of town, I would like to offer a different perspective on the attitudes of the antifence activists than that offered by Greg Kuperberg. First there is no doubt that crossing the train tracks at random points is both illegal and unsafe and I do not believe that anyone would seriously argue differently. However, a critical question is, would the fence as currently proposed increase safety, or merely move the hazards to another location? As an initial proponent of the fence in the name of safety, I had my mind changed by a walk along the proposed route of the fence which on the east ends near the Olive Drive off ramp from the freeway, an area which because of the rapidly exiting cars and the inability to hear either cars exiting the freeway or oncoming trains, would present and even less safe crossing. I think most of us present at the anti fence rally would favor a comprehensive solution which might include a fence as well as conveniently located safe crossings which if located at track level would be economically feasible. Finally, I heard no suggestion that the lives of the inebriated are of less value than those of the sober. The valid point was made, however, that a fence would only stop people approaching the tracks from the south. The fence will not stop the approach to the tracks from the north whether the individual is sober or inebriated. If track level crossings are felt to be a safe option at other areas in town such as 5th St. and 8th St. crossings, might they not be an acceptable solution to crossing from Olive Drive to the remainder of downtown Davis ?   Tia Will Users/TerryWill

  Tia, I would still say that there is an attitude problem, but there is a measure of reason in your answer.  If people favor a comprehensive solution, then they should negotiate a comprehensive solution.  They shouldnt say that a fence is a waste of money and needs an alternative.  They shouldnt make this, as one person described it on another page, a campaign against abstinence.  Also, whether the fence would stop people only from one side depends partly on whether the fence will only be on one side  I have not seen a clear statement that it will only be on one side.  In any case, Nanda Butler, even though he was drunk, was crossing the tracks; he did not wander onto the track for no reason.  Users/GregKuperberg

20101205 15:02:29 nbsp Greg,  the need to negotiate seems apparent in this case, and raising the issue in public forums and creating public awareness is what has been going on in the past week.  The use of public funds to reduce UPs liability rather than seek a comprehensive safety solution for this dangerous stretch of track is an important one for discussion.  Those of us who would like to see more than simply a fence, are up against a short time frame by UP and CCJPA. Getting all the stakeholders to the table is the best first action that can happen.   Users/RobertCanning

  Even if the fence were built tomorrow, it wouldnt stop you from also doing something else.  On the contrary, it should add momentum to providing those alternatives.  Users/GregKuperberg

  One persons safety fence is anothers wall between them and downtown Davis. I just believe that the impact of the fence goes beyond safety and has other, possibly unintended consequences.  I also believe that the $250K of public money should be parlayed into a more comprehensive solution.  (And how do I get those nice indents in the comments?  :)
   just one space in front of the  as I gave it bh
   As far as the money goes, its a very weak case to make so much hay over $250,000.  Because thats crumbs compared to almost any major project in Davis, and compared to a tunnel or a bridge across the tracks.  It isnt even 1/20 of the statistical value of a human life in transportation spending.  No, clearly what bothers people the most is not the money or the trees, its the fence that will get in the way of breaking the law.  Users/GregKuperberg


20101205 15:14:30 nbsp Greg,  I appreciate your prompt response. I would also be interested in your thoughts about the other points that I raised such as the displacement of the danger to another location which I see as a major inadequacy of the fence, why alternatives found acceptable in other areas of town are not considered acceptable in this area ( rail level gated crossings) and my feeling , that, at least at the rally today, i heard absolutely no suggestion that the lives of the suicidal or inebriated are of any less value. I do not think that reiterating this non argument, especially invoking the feelings of the families, does anything to credit your statements and indeed tends to distract from the validity of the remainder of your comments.  Tia Users/TerryWill

  All right, I agree, no one has explicitly said that the lives of suicidal or inebriated people are less valuable.  But the Op Ed did say, Most have been suicides, very intoxicated people, vehicle incidents, crimes or other random events. None that I can recall were happy sober persons crossing the tracks, who, like the proverbial chicken, simply wanted to get to the other side.  So what was the point of this statement?  It reads as a dismissive statement that if someone is drunk or suicidal, then a fence wouldnt help anyway.  As for the theory of displacement of the risk to another location, its interesting, but not any more than that.  Railroad companies have a century of experience with reducing risks and they know when a fence stops people vs when people just go around it.  Why are atgrade crossings acceptable in other parts of town but not here?  Thats a better question for Union Pacific than for me.  I can see why they dont like atgrade crossings either, but for all I know they would grant a partial exception and make it oneforone if they could remove the crossing where Landy was killed.  Users/GregKuperberg
   I think the line going to the north from the wye is actually run by the wiki:WikiPedia:California Northern Railroad, not Union Pacific. Users/NickSchmalenberger

20101205 17:14:09 nbsp With regard to the response to Robert Canning, Even if the fence were built tomorrow, it wouldnt stop you from doing something else. If this were a time of economic plenty, I might be able to agree with this statement.
My concern is that since the proposa,l as I understand it, uses at least some public funds to built the fence, it may indeed have the effect of making a comprehensive solution less economically feasible. I feel that this is a major reason for considering all points of view and the possibility of a comprehensive solution before deciding upon an expensive structure that at best addresses only one portion of the problem, and at worst might make a dangerous situation worse.  I wish I shared your optimism about the 100 years of experience of the railroads meaning that they will deploy that knowledge in the best interest of the communities they pass through. However, if that were the case, I must question why they are choosing this particular time to build a fence that surely with all that experience, they might have chosen to build after the first of the cited deaths thereby preventing the remainder. Could it be that having acquired public funds may have influenced the timing of this decision?  This is probably another question best addressed to Union Pacific, however, I am not seeing a representative of Union Pacific addressing these issues to either the city, for instance at City Council meetings, in the newspaper, or in any other forum readily available to the community.  As a member of an adjacent neighborhood, I received no notification or solicitation of opinion, and since at least two members of our city council were also unaware, it would appear that the city was not made aware of this plan that would fundamentally change at least one aspect of our community. While UP may have the legal right to do as it wishes with its property, the total disregard for the opinions and well being of the impacted community does not speak well for the intent of this simplistic solution to a complex problem.
Tia Users/TerryWill
  The major point not addressed by UP, the City, or the one editor (GK) is that this situation has been a problem for over thirty years. (Heck, it may have been a problem for over sixty years). While the City has spent money on Olive Drive as a result of developments on the south side, it has done nothing to address the motive for illegal crossings: the lack of convenient and safe access to downtown from the Olive Drive neighborhood. You can walk or bike around the long way, though a cruddy intersection and crowded tunnel, or you can stop, look, and listen and make a fast, direct, illegal crossing. As for the UP, I believe they have a century of experience with ignoring local communities, and imposing changes that are good for them. I agree that a fence is a simplistic solution to a complex problem. I dont think the UP would oppose an overcrossing, but they need to fix a potential liability problems  and see if this improves safety  rather than fix a neighborhood problem. It is up to regulators and political jurisdictions in which they operate to force/induce them to participate in something holistic. Users/DougWalter

   Again, a good question, but one that has a clear answer.  The reason that no one has done anything for decades is that the victims are disenfranchised.  The discussion that there has been about a crossing has come from two wellorganized special interests in Davis:  School families and bicyclists.  Now, I have nothing against either of these groups, in fact I am part of the bicycle lobby.  But I also feel really bad for the families of the men who were killed on these tracks, and I have even more concern for the next person to die this way.  Politically, these people have no leverage, they have nothing on their side other than Union Pacific and our consciences.  Few people if any at this protest cared to mobilize until they heard that a fence was coming.  Its not that I think that railroad companies are always right  far from it.  Its that the local community can be a euphemism for local political power, and the big bad corporation can be a euphemism for good ideas that some locals dont want. Users/GregKuperberg

20101206 06:52:59 nbsp Greg, I completely agree with your comment that local community can be euphemism for local political power..... However in this instance, the people who gathered on Sunday in protest to the fence are not members of the power elite of Davis. Most of the people gathered were either from the communities along Olive Drive and a smattering of folks from Old East Davis. I share your concern for the families of those who have died along the tracks and for others who are at risk in the future. And, if I were convinced that the fence, as proposed, would save lives in the future, I would still ( yes, I initially favored it) want it built. If is precisely because I do not believe it alone represents a safer solution that I am opposed. I feel that there are actually two groups of disenfranchised in this case. The first group are the actual and potential victims and their families. The second are the members of the communities that will be isolated by the fence. I do not feel that the current proposal for a fence alone demonstrates that UP is on the side of either of these two groups, Nor is it the primary job of the railroad to take sides in local issues. I think it is important to realize that this is a company that operates for its own profit. This does not make it evil, but does mean that members of impacted communities should be aware that the actions of the company will be in what its leaders perceive to be its best interest which may or may not coincide with the best interests of the community. In this case, I think it is critically important that the voices of all in the affected communities be heard so that the best long term solution can be devised as clearly should have been done long ago. I see the awareness of the proposal of the fence as another opportunity to address the issues of safety and access in a comprehensive fashion.  Tia Users/TerryWill

20101206 08:27:03 nbsp Whoever mentioned the safety fence around the freeway has a good point.  Why is there a fence on the freeway?!?  This clearly isolates the good people of Olive Drive from South Davis.  Not being able to shop at Safeway or let their kids attend South Davis schools is clearly disenfranchising.  What about Dos?  Shouldnt Olive Drive have fair access to Dos?  Also the Richards overpass is way too dangerous.  Nevermind, that they have a bike path thats close by; its far too far away.  The people of Olive Drive should be able to just run across the freeway if they want to.  It can be done safely, and if your drunk and get hit by a car, then youre an idiot.

Also, Id like to propose a bridge built from East Davis to Burgers and Brew.  I live in East Davis, and all my neighbors between here and Burgers and Brew have put up fences!  More so, the City of Davis and their horrendous planning department, designed all the streets in just such a way that I inevitably have to ride my bike in some direction that is not straight to Burgers and Brew.  Whats more, not only do I have to cross the train tracks, I have to cross L Street and 5th Street.  Do you know how dangerous 5th street is?  It sucks.  Im tired of East Davis getting this sort of treatment.  Its time to take a stand! Users/jefftolentino
 There is a big difference between crossing I80 and crossing the Olive Drive railroad tracks. How many trains go by in an hour? Youve got two Capitol Corridor trains per hour. The Zephyr and the Starlight come twice a day. A handful of freight trains come by at various times. Any way you cut it, youre still dealing with far fewer trains than you would see motor vehicles on I80. Trains are big and noisy. They can be felt quite a distance away. There are so few traveling on this stretch at any given point in time. If you look and listen before you cross, youll know when a train is coming. The crossing is safe if you are safe about it. I80? Youre dealing with 30 cars a minute in each direction a lot of the time! There is no way that is safe.

 The four fatalities weve seen on this portion of the line over 12 years have all been caused by people recklessly or intentionally endangering their lives. Yes, its sad that they died. Was it their fault? Absolutely. Were going to spend a quarter million dollars and isolate a community because a few people were irresponsible. Thats outrageous. Users/WilliamLewis

   Thats very insightful, William.  You are right, the freeway is way more dangerous.  It would be interesting to research the number of pedestrian related freeway fatalities in town.  Theres probably dozens of cases of drunk, irresponsible people bypassing the freeway fence and dying.  (Dos Coyotes is soo good after a couple of beers.)  We could totally shoot down the railroad fence by showing that the freeway fence was a silly investment. JT

   William  I have to object again to one of the bad arguments that has been made and implied.  Youre saying that when Butler, Carrasco, Iyotte, and Allison died, it was just their own fault because they were all drunk or suicidal  so why should California spend money on a fence to stop them?  That is a terrible theory of accident prevention, a terrible theory of suicide prevention, and a callous answer to their families and to the train engineers who saw them die.  Why do we have suicide prevention in Davis?  Why do we have Alcoholics Anonymous?  These people deserve help, and fencing dangerous train tracks does help them.  Even if they did deserve it, the train engineers certainly still wouldnt.  Have you ever been behind the wheel in a fatal traffic accident?  Fortunately, I havent, but I know that its not something that you can ever forget. Users/GregKuperberg


20101214 12:06:58 nbsp At this point, it might be more productive to focus on options to improve the Richards Blvd intersection.  The railroad does not have much investment in community unfortunately, and the City would have more leeway over changes to the intersection than work on Southern Pacific property.  Traffic calming measures through the Richards intersection would have benefits to users passing from South Davis to Downtown as well, especially those on bike or foot. Users/jefftolentino

20101214 12:38:29 nbsp Starting a betting pool for how long it takes exotic fence crossing measures to manifest in the form of permanent circumventions of said impenetrable fence

Ill take 3 weeks Users/StevenDaubert

20101215 12:08:34 nbsp The fence will cut down on the number of crossings, the legal alternative is less than ideal, and a certain number of individuals will circumvent the fence in dangerous and exotic ways.  Realistically, the relative safety of asyetunbuilt solutions to this complex situation can be speculated on by those wishing to makes a particular point, but are not easily measured, and the points made by all involved parties are valid and should be considered as part of a best scenario solution within available funding sources. Users/AlanMiller
  I have to say, Alan, you are one of the easiest editors to work with, especially being that were on opposite sides of the argument here.  Its refreshing.  Its nice to have a discussion with someone who actually reads and listens.  I hope one way or another Olive drive gets the attention it needs. JT

20101216 09:08:12 nbsp  . . . but building a new crossing has to result in less people crossing the tracks.  This is an interesting position for the railroad to take, in that more people have died at or very near legal crossings in and around Davis in the last few decades than have died adjacent to the proposed fence line. Users/AlanMiller

20110103 10:16:28 nbsp Apparently no one has addressed the legal right of people to use a rightofway which they have used openly, notoriously, adversely, continuously and uninterruptedly for more than five years. The above constitutes a easement by prescription, and can be used in court to either block construction of such a fence, or to TEAR IT DOWN once it has been built.
It would be much cheaper for UP and whoever gives them any money, to address this issue of easement having been established by the long use of the atgrade crossing, in which UP (or their predecessor) has already invested considerable funds.
They may say It will be built! and it may be built, but the law can force them to either tear it all down, or put in access for the easement mentioned above. Users/RogerOLittge
  I wish that were so, but it doesnt apply to railroads which are under federal jurisdiction.  Also, it isnt five years, it is well over a century that people have been crossing the tracks here.  Users/AlanMiller

20110103 22:18:41 nbsp I used to live on Olive drive, twice, and for years I walked the tracks to get to classes on campus, almost daily, all the way from about where Public Storage is to the Arboretum, usually on a single rail. I also used to cross it often with my bike to come into town to shop. Many hundreds of times I did these things, and never once did I have any issues at all. I think the safety argument has been blown way out of proportion. It appears that most of those killed on the tracks were drunk or otherwise incapacitated. That doesnt make the tracks too dangerous to cross, it makes the drunks too dangerous be be allowed out of the house. If a drunk walks out into traffic on 5th street, does that make 5th street more dangerous, or too dangerous to bike on? In fact, I think the stats for the tracks need to be compared to those of the surface streets to restore a little perspective here. I think that if we did that wed find it would be necessary to fence off many of our streets.

I was the safety person on a UCD department and also responsible for some hazardous equipment (xrays, chemicals, cryogens, etc.) used by well over a hundred students and researchers, and in all cases all rules and policies were written with the goal of reducing risk to as low as is reasonably possible. Not absolutely, but reasonably. For instance, when working with xrays, one has to acknowledge and accept a certain amount of risk. We are told what those risks are, and we can decide to go do something else if that is not acceptable. If you use the xray equipment, you are expected to follow the procedures. Its that simple. The same goes for chemicals and other hazards. Our training included discussions of cases where people still managed to hurt themselves, but they did that by ignoring the safety procedures. In the case of the tracks being discussed here, the hazards are hardly any different in kind than crossing a street, and are much less frequent, and as big as trains are, most pass through Davis slower than most cars go on city streets. Still, the procedure is as simple as the one we were taught as kids, look both ways and cross when clear. Not, get drunk and go to sleep on the tracks. The typical counter argument at this point is the if it saves just one life argument, which we all know is just cowards nonsense. You could pull that one out any time, for any risk level, and it ultimately leads to something like, dont get out of bed, you could get killed.

I suspect there may be another angle here, possibly remote, but also a possible way to stop the fence nonsense, and that has to do with eminent domain, I think that is what it is called, where people have been traveling these routes for years, and that may mean that the owners are now not allowed to stop it. I figure the property owners along Olive Drive must have figured that out years ago when they started putting no trespassing signs on land that had wellworn foot paths going through them. Something is bugging the railroad folks, possibly safety, possibly pedestrian right of ways.

Davis seems to be experiencing an allergic reaction of some sort, one where the immune system attacks itself because it isnt being hit with the bugs that past generations experienced. That, and it seems we need to have a steady supply of dangers to deal with in order to feel like our lives are getting better, or demons to purge to feel more righteous. If it isnt a train track, its a fire place, or a leaf blower, or the shutoff on selfserve gas pumps. Whats next? House paint? Its sad.

All this situation needs is people who know how to cross the street, are fit to cross a street, are willing to do it correctly, and will take responsibilities for their own screw ups. (Mike Meier) Users/m610

 Mike, the stats and the law are very clear.  The stats say that the citys railroad tracks are much more dangerous than its streets.  The law is equally clear about the procedures:  Dont cross the tracks at all, except at designated crossings.  Dont expect any of the bit of the law to slow down the fence; the law is entirely in favor of a fence.  The only reason that people have crossed these tracks all these years, is that the railroad tolerated it, just because.   If the city tried to goad them to play nasty, it would be an easy slam dunk for them.  You have to cooperate with world outside of Davis, or else you wont get anything.  Users/GregKuperberg

   Mike, the argument in your first paragraph is saying that its ok for drunk or otherwiseincapacitated people to get injured or killed when crossing the railroad tracks.  Users/Angel.York

20110111 11:40:36 nbsp Despite a comment that railroads are immune from easement legal steps, such is not the case. They win most of the cases since such cases are often spurious. There are good case studies (Penn Central Trans Co. vs Pirate Canoe Club) which stopped the railroad from stopping established rightofway easements.
The City should assert its rights to these easements, but the key person (SG) representing Davis to the railroad and authorities is not helpful. Users/RogerOLittge
  The likelihood of Davis prevailing in a case of this nature is almost zero.  In the case of Penn Central Trans Co. vs Pirate Canoe Club, the Pirate Canoe Club won because A) their land was landlocked by the railroad and there were no alternative routes, and B) the easement was a permanent easement that was recorded in the deed of the property.  With the current situation in Davis, people cross the tracks for convenience, not necessity, and there are no recorded easements.   Users/DavidGrundler

20110112 18:25:42 nbsp There were comments made last night that the railroad does not own the land and that prescriptive easements apply to railroads.  Unfortunately, this is not the case.  The lawyer who spoke later cleared this up and he was correct.  I know these well meaning people will stick to their beliefs, but it will not help this cause.  The only two (legal) routes to solving this are piecing together a boatload of money for an an overhead ped/bicycle bridge, or piecing together a smaller boatload of money and making a very, very strong case to the PUC that an atgrade crossing is warranted here.  There are simply no other avenues to pursue. Users/AlanMiller

20110112 20:25:42 nbsp Heres an idea:  Maybe have a cyclone fence.  At each opening have a cage that would lift pedestrians and bikes over the tracks. Users/BruceHansen

20110124 12:47:03 nbsp As has been stated, railroads are protected from most attempts at prescriptive easements across their rightofway, but the situation in Davis is very special, perhaps unique, in that SP installed concrete and steel aprons (walkways between and next to the tracks, for pedestrian & bicycle traffic) to completely cross the tracks, not just for passenger access to trains.
Railroads are federally regulated, but all California laws, it can be argued, apply to their property, unless countermanded by federal law. Someone stealing a purse on railroad tracks can still be apprehended, despite there being no Federal law against purse snatching, since the property is still in California.
Another method available to the City of Davis is condemnation of the rightofway across the tracks. Sure, this is usually only done for vehicular roadways, but Davis has a very special tradition of bicycle promotion, and may convince a Federal court that it should be allowed to condemn the present well established rightsofway which have allowed many hundreds of thousands of safe crossings of the tracks over the last 132 years. Users/RogerOLittge

20110324 16:42:57 nbsp As a strong advocate of border control, I support this fence 100%! Olive drive and its trailer park/shanty towns are an eyesore and Slaters Court needs to be demolished. They should also include a few guard towers so that if anyone tries to climb the fence, they are shot. The last thing we need are convenient paths for the poor to travel on...next thing we know, downtown will be flooded with Four Loko drinking assjacks from the trailer parks The Spare Changer spanging for meth money.... Users/JoshLawson

20110425 17:47:16 nbsp As a Slatters Court resident, the new short fences are, in a word, INSULTING. A direct slap in the face of residents in the area, accomplished with a smug smirk from a company thats used to being a 500pound gorilla. Honestly, given the amount of vandalism the legitimate fances suffered, I expect the new ones to last an even shorter time... assuming that someone doesnt just open a hole in the existing fences two feet to the right of the new ones. Just sayin. Mind you, if the old fences DO turn out to be within UPs property line, then the reasonable response would be to remove the fences entirely.

Also, way to be REAL jerks, doing it while kids are off at school, so their regular route home is blocked, forcing them to go the long way around. While I wouldnt wish it on any parent, I would love to see the communitys reaction when a child that normally crosses safely at the tracks be struck by a car at the intersection. Users/Flynn

20110425 23:47:03 nbsp At 6pm I watched pedestrians for 5 minutes.  A man with a small boy walked towards the Davis Mobile Estates gate, turned, and walked up the middle of the tracks together until they reached the lot behind the furniture store and went over there.  Good, more time with children on the tracks.  I walked back to Slaters Court, where a resident was attempting to scale the old fence into Slaters.  As he was going over, he slipped and freefell horizontally six feet to the ground between fences, somewhat horizontally but head leading.  I was glad to see him get up and try again, as it looked like a potential concussion.  Nothing brings safety to mind like the words Union and Pacific.  These fence segments have made everyone safer, because now everyone will obey the law and do exactly what the railroad wants.  All it took was two fifteen foot segments of eightfoothigh, militarygrade fence with No Trespassing signs on them.  #sarcasm#  I walked around to the inside of the fence, and a man was standing there.  He said to me, I am pissed.  I feel like a caged animal. Users/AlanMiller
 Some might argue that if you hurt yourself climbing over a fence to trespass on someone elses land its on your head.  So to speak. Users/TomGarberson
 It sounds like U.P. doesnt want to allow for clarification of whose land it is on.  The City tends to think its not on U.Ps land.  When U.P disrespects others, people are going to say UP yours.  Then theres the issue of established usage.  Its a different situation than, say, trying to climb over a fence around a business. Users/BruceHansen
  Sure, theres definitely more to it.  Im just saying, even if UP is completely in the wrong, if you hurt yourself climbing over a fence to save yourself a walk (or, god forbid, bike) of a mile or so... youve gotta feel pretty stupid.  If its about getting back at the company... Flagellants went out of style a long time ago.  Some small children throw fits when they dont get what they want and do things like bang their head on the ground or a wall.  It doesnt usually work.  Unless were talking Gandhiesque hunger strikes, I dont know that the Im going to do this until I hurt myself unless you take down the fence approach is going to work.  And I suspect even Gandhi wouldve been tempted by the smell of InnOut wafting down the street, vegetarian or no. Users/TomGarberson
   I didnt get the sense of retaliation, more an old timer set in his ways. Users/BruceHansen

20110426 16:36:50 nbsp I find the recent actions of Union Pacific appalling. To build a fence/addition while currently in discussions about said fence/addition is a very profound statement to the bearish attitude of the railroad akin to Jay Gould and Charles Crocker of bygone days. Users/WesP

20110510 10:04:34 nbsp OK, as I live in S. Davis I wasnt going to comment but Mr. Garbersons comment: climbing over a fence to save yourself a walk (or, god forbid, bike) of a mile or so... youve gotta feel pretty stupid. hit a nerve.  Im disabled on a very limited income so have no vehicle and riding a bike isnt an option nor is walking a mile or so.  Obviously, I cant climb a fence either as I have days where walking across my apartment is more than I can manage much less try to get to the grocery store.  Im sure thats what was going on with the small child, as well.  Not everybody in Davis is young, healthy or has lots of $.  It seems as if you arent one of the former or an animal, you dont count in Davis. Users/KatyMartin
 I apologize if it seemed like I was belittling you or anyone else for having a disability or being short on funds.  That wasnt my intent.  I was simply pointing out that hopping a fence, if you cant do it without hurting yourself, seems like a very bad solution to this problem.  I dont know whether there is a good solution, but if there is, thats definitely not it. Users/TomGarberson

20110707 16:00:27 nbsp first of all my tone in this comment will be HARSH. I just lost a friend on the tracks on 6/30 and it is heartbreaking to hear you pissant fucks put your two cents in. He was NOT  drunk or suicidal. He was released from sutter davis 3Times in 1week with head trauma sustained by Davis Police. This should not have happened. JoshLawson sounds like he has some issues with some people that needs to be resolved. DO NOT attempt to generalize what a person is thinking before they die if you do not know them. If any of you clowns met Dan Ferguson who was killed by amtrak on 6/30 you would know that he did not want to end his life. He would have turned 55 years old on July 1st. thank you Users/JustinYoder

20110707 20:51:20 nbsp Sorry, Justin, I dont know which comments that you reference.  I brought Danny from the hospital a few days before he died and plan to attend a memorial for him tomorrow. Users/BruceHansen

20111018 01:29:12 nbsp Im surprised nobody has commented yet  UP went ahead and put up the fence, with a locked gate at the Hickory Lane section. I got to see some VERY pissedoff barhoppers last Friday night when they found out the couldnt get to downtown through Slatters Court, after having tried to go through that way. Users/Flynn

  The bar hoppers need to learn the realities of the situation.  Nanda Butler was bar hopping when he was killed by a train at the Olive Drive tracks, and Samuel Carrasco was also drunk when he was killed by a train there. Alcohol and illegal train trespass dont mix!  Users/GregKuperberg
  Just ignore Greg, he is trolling Daubert
  I always do. Users/AlanMiller

20120410 08:27:46 nbsp I truly hate this saftey measure. Severely limits ones options when walking out for breakfast... Users/WesP
