UC Davis offers some online courses.  Some believe that they will save the university money and deliver education more efficiently; the idea here is that far more students can be taught with fewer faculty.  Others argue that they have various problems: lower success rate with underprepared students, lower success rate with students lacking in selfmotivation and established study habits, loss of personal relationship between faculty and student and between students, inability to engage students in critical thinking in person or in writing because of the large numbers involved, loss of an intellectual community.

A variant on purely online courses is the hybrid course, where part of the course is taught online and part facetoface.  These are generally not controversial, with most faculty thinking that online components of a course can enhance the classroom experience.

Massive Online Open Courses (MOOCs) are another variant; these may be produced by one university yet available worldwide.  As a source of selfeducation, these are not controversial, but when degree credits are offered for them, concerns such as grading of written assignments have been raised; some MOOCs are designed to use peertopeer grading.

 SB 520 

Governor Jerry Brown has argued for an increased use of online courses throughout Californias public higher education system.  On March 14, 2013, a bill was introduced (SB 520) that would require UC System UC, CSU System CSU, and the Community Colleges to grant credit for thirdparty online courses as the equivalent of specified lower division course that are prerequisite to timely progress toward students’ degrees.  The next day, the Chair and Vice Chair of UCDs Academic Senate wrote a response, which is available http://senate.universityofcalifornia.edu/RP_BJ2AllSenate_SB520_031513.pdf here.  The letter states that Senate Bill 520 raises grave concerns and points out that faculty were not consulted in the writing of the legislation.  Three problems are identified with the proposed legislation: 1) the problems with students access to some courses is the result of UC Davis Budget Cuts reductions in public state higher education funding, 2) there is clear selfinterest of forprofit corporations in promoting the privatization of public higher education, and 3) the bill would cede the facultys authority to approve and review courses to an outside agency.

 Petition 

On 3/21/2013, the Davis Faculty Association sent an email to faculty, inviting them to add their names to a petition that originated with the Berkeley Faculty Association, and which is addressed to Sen. Darrell Steinberg (CA6), the sponsor of SB 520, asking him to withdraw or modify SB 520.  http://signon.org/sign/ucfacultyopposition?sources.icn.em.mt&r_by7376435 Petition here.  The text of the petition reads:

 Dear Senator Steinberg,

 We, the undersigned faculty of the University of California, write to express our many, deep concerns about SB 520, as recently amended. We believe that this bill will lower academic standards (particularly in key skills such as writing, math, and basic analysis), augment the educational divide along socioeconomic lines, and diminish the ability for underrepresented minorities to excel in higher education. In other words, we predict that SB 520 would worsen precisely the situation it claims to resolve.

 The research on MOOCs demonstrates that on line courses suffer from high dropout rates, poor outcomes for students struggling with basic skills, and high cheating rates (see Di Xu and Shanna Smith Jaggars, “Adaptability to Online Learning: Differences Across Types of Students and Academic Subject Areas.” Community College Research Center, Teachers College Columbia University, February 2013). This research also indicates that MOOCs produce the worst outcomes for exactly those students they would most likely serve — students from less wealthy families. None of these unfortunate realities square with your hope for highquality, wideaccess education.

 The best way for the California legislature to ensure that college students can take the courses they need to graduate on time (a goal we endorse wholeheartedly) would be to increase funding to its universities and colleges to ensure there are enough seats in classes students need. SB 520 funnels public money into the hands of private corporations – some of whom are currently under federal investigation.

 This bill fails to address the complex challenge of ensuring that credit will be given only for courses that meet the high standards of California’s many institutions of higher education. The UC campuses already have timely mechanisms in place to ensure transfer credits from a variety of sources. Your bill will undermine essential quality controls that ensure appropriate preparation for collegelevel work. Without these, students will fail to succeed in their majors or to thrive academically after they transfer into to a CSU or UC campus from the community colleges.

 In short, SB 520 is deeply flawed. We believe it will worsen the conditions you say you hope it will ameliorate. We urge you to consult with UC, CSU, and CCC faculty and other experts to enlist their help in devising a welldesigned piece of legislation that will truly help students, while protecting the quality of the education they have the right to expect – and that we, as University of California faculty, have the duty to provide them.

