
Pine Trails Ranch is a 20+ acre equestrian facility offering boarding, lessons, breeding and horse sales/rescue. Lessons include both English and Western style ridinng including hunter, jumper, dressage, western horsemanship and trail riding. They also offer summer camps and birthday events.  They are dedicated to giving riders of all ages and abilities a fun and high quality riding experience.

To learn more about equestrian resources in or near Davis, please visit our Horses page.


20080912 11:56:26 nbsp I ride at Pine Trails Ranch and find it to be very nice there.  Every one is really nice and its easy to feel at home.  they give lessons that are about 2 hours long for good prices.  They have 5 pastures that are big and are watered.  There are 2 trails on the ranch, the perimeter trail and the half perimeter trail.  Pine Trails lives up to its name, there are lots of Pine trees.  3 arenas, one is covered and the other two are HUGE and outdoor.  The barns have really clean, nice stalls and the horses will sick their headsout for a treat.  There are two ranch dogs that are very friendly and wont get into the way.  They take the lessons slowly and their horses are trained fairly well. Although they can be a bit touchy if you are late, its a place I would love to live FOREVER! Users/lilitraw

20080922 22:07:23 nbsp I used to ride here in elementary and High school. It is a decent stable for learning to ride, but not if you want to be competitive. The emphasis is NOT on showing or competing, and students move very slowly. After a certain level, you really cant learn any more from the lessons, which are little more than pony rides. If you want to show or compete, look elsewhere. Also, it is primarily a lesson stable for children, so its not an ideal boarding stable. Users/quarabaloosa

20081018 17:22:45 nbsp I have been riding there for five years and wouldnt consider going anywhere else despite the long drive I have to get there.  I took this sport up as a 45 year old, learned to ride, and bought an amazing horse from the ranch.  The instructors are terrific and the environment is very supportive and encouraging.  The other rider/clients of the ranch are a wonderful group of people.  This is a great place for kids and adults as well (and for adults that sometimes wish they were kids) Users/kellyg

20090427 12:05:32 nbsp look quarabaloosa, you seem to be really critical. is there any place you actually WANT to ride? or do you just go around and bitch and moan about how nothing is perfect enough for you.  ptranch is a really nice stable and leasers can shw. students can slo show once in a while during the schooling shows at the ranch. the trainers typically take it slow jumping so you can perfect your form.  Users/pompomcakes

20090815 21:39:15 nbsp i love this place and the dogs and cats are so careful about not getting in the way, when i did a camp i fell off and they were so nice about asking me if i wanted to keep riding or rest for a little while (the lesson had about 5 minutes left) although some stuff is a little bit jumble its a great facility if you are a beginner Users/Churro615

20090926 15:08:44 nbsp Ummm...seriously? People like this place? Maybe we are talking about two different Pine Trails because the one I viewed had trash on the grounds, a bunch of skinny horses, some scarylooking enclosures.... why would anyone want to keep their horses there? A real letdown from the website for me, which made it look like a nice place with grass in the turnouts and happy horses not horses crowded on bonedry land with poo all over and flies swarming. Yuck no thanks. Its not like I was expecting the Ritz, but some basic good horse care would be nice. Who cares if there are lots of arenas if your horse is thin and miserable? Users/imjustjoking22

20100408 19:10:29 nbsp My horse and I have been at Pine Trails for almost two years now, and I am very happy there. The only skinny horses that are there are super old/hard keepers. All of the horses get plenty of feed and care. (Many are actually on the plump side) This is one of the best lesson/training facilities Ive had my horse at. When I first moved my horse here it looked a little shabby, but a lot has been renovated over the last year. Theres a brand new (beautiful) roundpen, and all of the fencing on the pastures have been redone. There are two big outdoor arenas with nice footing, and a smaller covered arena for the rainy season. The people who work at Pine Trails KNOW horses, and you can tell they care about all of them.  As for the lessons being only good for beginners, I disagree. Ive been riding for most of my life and I find most of my lessons to be both challenging and engaging. I also love that the lessons are catered to what the students want to be learning, and are targeted to work on individual issues that the horse and rider may be having. If youre only looking to jump gigantic fences and you dont care about safety or looking like a sack of crapprobably not the place for you. But if you want to improve your equitation and communication with your horse, I would say give the lessons here a try.  ) Users/chmorr

20110430 19:25:05 nbsp I am updating my review for PTR :)

PTR is one of the few places in Yolo County that offers affordable horse boarding, training, riding lessons and summer camps.

I have boarded by horse at Pine Trails for several years now, and I have also been teaching lessons as Michelles Assistant Instructor for about a year. As a boarder, I have always felt that my horse is in good hands while I am away. PTR feeds good quality hay and the horses are always under constant supervision. There are even affordable schooling options available for those who dont have time to ride everyday, or for when you go out of town.

2011 Summer Horse Camps are MondayFriday 8:30am5pm
$275 per child, discount for siblings and repeat campers.

Instructors teach both Western and English. This barn is perfect for beginner/intermediate riders, or those trying to build up their confidence. The horses are safe, well behaved and well trained. Although PTR has a show team, the environment around the barn is really friendly and relaxed. The perfect atmosphere to ride for fun, learn more about horses, improve your riding (and your horses training) without the snobby looks or comments.

Michelle Haseltine is the owner of PTR, as well as the Head Trainer and Instructor. Dont forget to call 24 hours in advance to cancel a lesson. No shows will be charged the fullamount for missed lessons, (with the exceptions of real emergencies)

Stop by any day of the week to check out the horses, lesson program and meet the instructors! Users/chmorr

20110430 20:51:57 nbsp I road at Pine Trails all through junior high and highschool, the only reason I stopped riding there is because i had to leave for college! I also bought my first horse from Pine Trails, Ive owned her for years now and couldnt be happier with my horse or my experience at Pine Trails. Pine Trails has grown a lot over the years that I have ridden there, there is a group for those more interested in showing, there are all sorts of wonderful clinics so you can learn about all aspects of riding and horse ownership. Prices are reasonable and a lot of time and money has been put into improving the facilities. I loved my time out at Pine Trails, I grew as both a person and a rider with the help of Michelle and all of the other trainers out at the stable. All of the horses are treated beautifully and the lesson horses are trained very well. I cant say enough good things about Pine Trails, I wish I could still be out there every day with my horse and all of the great people out there! I have been riding since I was 6 but no other stable have I ever grown as much or learned as much as I have at Pine Trails. This ranch is a great place for kids and adults, and it was great for me because I became friends with both kids my age and the adults out there. you couldnt find a more friendly group of people. Pine Trails is a wonderful place and it has changed and grown over the years so you need to see it for yourself to understand what a great place it is  Users/DRandall

20110501 09:23:05 nbsp I have rode at this ranch for a long time and have enjoyed learning how 2 ride there... plus the horses r well taken care of and the lesson teachers r very helpful Users/munch

20110501 12:29:11 nbsp I started riding at at PIne Trails Ranch as an adult beginner at 46.  Two horses later, I can say Pine Trails is a safe, supportive environment for all riders, but especially those starting out or wanting to beef up their riding skills. Good advice can also be had for working with and developing your own horse.   The ranch owners and instructors are knowledgeable, friendly and relaxed.  You can learn at your own pace, and there is a wide variety of horses available for lessons and lease at various riding levels, so you can move up when you are ready. If you are interested in owning a horse, but arent sure about the commitment, leasing is a very good way to determine if you are ready to take the plunge,  In my experience, Pine Trails priority is providing a positive horse experience for everyone at every level and they frequently go out of their way for people with a real interest in learning about horses.  Users/MeganLowry

20110710 16:17:51 nbsp My daughters and I have been riding at Pine Trails for over 2 years.  We love it! There are great teachers and horses there and it is affordable. I am an older rider (over 40) and I feel comfortable and safe there. I definitely encourage anyone interested in horseback riding to try it out! They have great summer camps and birthday parties too! Users/franmaguire

20130201 10:44:41 nbsp My daughter (just turning 5 years old) just had her first horse riding lesson here.  It was a wonderful experience for her.  Colette was her trainer, and I was highly impressed with her skills.  My daughter was very comfortable with her, which seemed due to Colette knowing exactly how to talk and interact with kids.  My daughter got to help get the horse ready for the ride, walk the horse over to the riding area, and then learn some riding techniques. Pine Trails Ranch has riding shoes and helmets for kids to borrow during the lesson (my daughter loved the riding shoes and wanted to take them home).  By the end of the lesson, my daughter was able to get the horse to stop, go, and move to the left or right.  Colette new exactly when to offer assistance and when to let my daughter try things by herself.  My daughter has been wanting to go back ever since.  It was a birthday present from her grandparents, but we unexpectedly are now trying to figure out if we can make it a more regular event.  Great job, Pine Trails Ranch! Users/Oaks

20130207 21:35:44 nbsp If you are looking to develop your riding skills and want to learn more about horsemanship, I definitely recommend this place. Ive been at Pine Trails Ranch for five months now and have learned so much during this time. Ive even learned completely new things!!, and thats not bad since I have about 25 years of experience with horses from my home country Sweden. Michelle is very good at matching horse and rider. It took her about five minutes to see what kind of horses I was used to riding, and she was right of course:) I actually cannot think of one bad thing about this place. I just love Pine Trails Ranch and am so impressed by Michelles work with both horses and riders. Users/CharlotteBhatt
