

Planet Wash is a car wash that provides everything except the washing, which you do.  They even provide rainbow colored soap.  You can choose an automated drivethru wash or a selfservice wash with water, brushes, etc. For payment, they provide a bill changing machine (turn your 20 into ones), a coin machine, or you can pay with a credit card.  Its pretty darn convenient to pay with the credit card when using the selfservice so that you dont have to keep plugging the thing with change.  There are also several vending machines for car accouterments, vacuums, and scent dispensers for the car interior.

Many comments note that this location is unusually clean for a selfservice wash, with tools in excellent condition.  Note that if you are using the selfserve wash, the timer keeps going even if you turn the knob to Stop.

Planet Wash uses warm water and high pressure system so less water is needed for washing your car.  It uses soaps that are better for the environment than most car washes use.  All soaps are biodegradable. Planet Wash is a Davis family owned business.

Planet Dog Wash is also located here.  It is a self service dog wash with shampoo, oatmeal shampoo, conditioner, flea and tick, disinfectant, and deskunk

This was previously the location for Stonegate Car Wash.



20080913 13:50:08 nbsp Ive gone by this place many times and never seen a planet being washed.  I tried to wash my planet, or at least my car, there myself once, but the wash did not work, and there was no one there to turn anything on.  The machines would not even take my money.  I think that the wash may have changed owners or been renovated since then.  Meanwhile, Im sitting here with a dirty planet that I would really like to clean.  The ozone layer has holes in it.  Smog is trapped beneath inversion layers.  Theres too much CO2 in the air.  And its rivers and streams are polluted.  Oh, for a cleaner planet. Users/IDoNotExist

20081004 18:08:20 nbsp Tried this place once: ended up costing near as much as any automated place, plus it had the added benefit of making me do all the work myself. I didnt see anything indicating it was any more ecofriendly than any other wash, but then again I wasnt exactly looking too hard either. Users/JoePomidor

  The following two comments were left from the same IP address. While it does not prove that they were made by the same person, please be aware.
20081016 19:21:14 nbsp Ive gone to this place a bunch and love it. It is in no way as expensive as any automated place, and I personally think its fun. I havent had any trouble with the machines (they are all new, maybe the old machines were the ones that didnt work?) and i LOVE the dog wash. Oh and your car is beautiful when youre done  much cleaner than any gas station drive through wash. You have to try this place, youll love it. Users/anont

20081019 21:50:55 nbsp i tried planet wash for the first time today. i have to say, i was pretty skeptical about the whole wash your car yourself thing. but it was really easy, and really cheap too. try this place. five stars. Users/Samman

20081020 20:53:36 nbsp We went through the automatic washer here & paid $7.00 for the express wash. The car came out a bit wet, but still very dirty.  Users/AprilAries

20081118 18:45:03 nbsp I think we washed our Camry station wagon here for about $10 in quarters. It was fun  The cleaning foam is made of RAINBOW colors! I personally like scrubbing down a car as opposed to slowly driving through a cleaning tunnel. My only complaint is the instructions leave something to be desired, but its pretty simple so youll figure it out. Users/gurglemeow

20081204 02:43:19 nbsp Being a messy person who likes to have things clean, I clean my car out a lot. The vacuums work better then any of the other ones around town. I love the automatic car wash, it works quiet well. They keep the place clean and friendly. The self serve car wash area is great also. This place is up to date complete with all the bells and whistles for cleaning/washing your car. Also the gentlemen who work there are quiet friendly, always a smile and polite conversation!  Users/isikins

20081204 16:45:30 nbsp I did the Express automatic wash (since it was free because I got my oil changed at Davisville Express Lube) and I would say it was... better than nothing. Not good, mind you, but better than nothing. The bug guts on my windshield are still on my windshield, but the splatters are smaller. The nasty film on said windshield from driving 521 miles last week was removed, at least. I certainly wouldnt pay $7 for it. Cable Car Wash was a lot better.

I did see a cutelooking little pet wash station. Probably costs too much to use it, but the idea is nice. Users/RobertM525

20081211 23:24:36 nbsp This is a great place a hidden jewel in Davis! Its clean, it fast, and its fun! Its also very modern and very green.
Theres also a pet wash location. Its just too fun! In addition, its easy to use because they take credit cards, and its well lit.
I met the manager  Kim  a great guy all about customer service. I highly recommend this place as the best car washing place in Davis!  Users/tricket

20090103 14:49:09 nbsp I just tried this car wash for the first time, and its overwhelmingly awesome. First of all, being able to use a credit card is extraordinarily convenient for someone like me who never carries cash (ever look at a dollar bill under a microscope?) and/or never carries loose change (Wasted space). Second of all, the tools themselves are topnotch, and dang near brand new. The wand, the conditioner pistol, the foam brushall are in superfine shape. This is particularly important to me as I like babying my new Mustang, and the foam brushes at the other car washes look like they havent been replaced in who knows how long. There are lots of little things that have been bugging me about the other coinops that this one addressed, including an awesome selection of overheard classic rock while you operate the bay.

I have NOT tried the automatic drivethrough wash, but in my experience, those are usually pretty lackluster anyway. This thing is awesome, totally worth the drive! Users/Aggieanthony

20090515 12:20:23 nbsp I wrote a long review about this place, then deleted it.  The facilities are nice, new, and apparently well kept.  It may be just me, but the do it your self car wash is very hard to actually get your car CLEAN with.  After I washed my car I dried it with a terrycloth from the vending machine.  It came away very dirty. Users/MasonMurray

20090725 16:09:43 nbsp I really like Planet Wash, it has everything you would need to get the job done and leave the suds there. I have used the pet wash which is great for large dogs that have a lof of hair. Please see Planet Dog wash page for my comments and pictures.
Being a petsitter, I have car seat covers in my back seat and the high powered vacuums are perfect for sucking up dog hair and dirt and it only cost one dollar(well maybe 2 or 3 if you throughly clean your seats, floors, and covers. I usually lay the covers out to make it easier so I dont waste my time I have paid for. I have also used the shampoo steam vac for the car rugs and I must say it does a really good job. I suggest vacuuming for a dollar then using the shampoo/vac for 2.50 afterwards, that way you can spend more time getting your rugs steamed at the higher price. I have used the automated car wash after getting an oil change(it was free). It did a pretty decent job of getting the outside clean, unlike any other older car wash I have been through with the old mops that are hard on the paint. The automated car wash is quick and easy. Its one major fault is not getting the windows as clean. The one thing I like about it is how the soap is applied to the car through the pipe with holes covering more surface area and thus getting your car cleaner. I have not used the self service wash ,but will comment when I do. Users/ElizabethBarthel

20091014 14:58:06 nbsp This place is cleaner and neater and more meticulous than most restaurants Ive eaten in!!! Users/StephHolm

20091110 15:29:26 nbsp I have been here several times and love it. The self service wash does a better job than the automated wash ,but the automated job still does a pretty good job. I just use the free VIP coupons from getting oil changes and gas next door for the automated wash, but the real reason I come here is because I like the self serve wash, I can wash my car for about 6 dollars which includes pre rinse, soap, conditioning, clear coat protectant,dry, and spot rinse which really does a great job. The high powered jets make washing your car a breeze. The dryer works really well and leaves your windows nice and clean without water droplets. Everything is easy to use and new so everything functions really well. You can even hang up your mats and use the high powered setting to  wash them. Afterwards I vacuum and carpet shampoo my floor mats. I wish the VIP coupons were accepted in the self wash instead of just the automated. The automated wash is good for a quick job to get your car clean. The wash does not damage paint on your car like other washes which have the big mop to clean your car. My only complaint about the automated wash is no scrubbing power and dryer works ok. Overall, highly recommended to keep your car clean.   Users/ElizabethBarthel

20100213 13:55:01 nbsp Nice place. Clean and convenient with credit card capabilities. Having the post rinse soften water option is nice too. A little bit more expensive then Auto Washette.  If youre quick, it will cost ya about $6.  Users/103

20100516 00:39:40 nbsp A friend and I went here to get their car washed. Ive been to place like this in the Bay Area and high expectations....that were crushed. Its $2.50 for the initial charge (credit card was a definite +!) and goes up by $.25 until you say stop.
 The FIRST time through we did the steps that they recommended: prerinse, soap, tire cleaner, rainbow foam, scrub, dry, etc etc etc and the car was dirtier than when it started. It was about $6 for nothing....
We did the vacuum next and that was a good deal. It was $1 and we vacuumed the floor mats, seats (back and front), and got into some of the nooks.
We took it back to the wash section AGAIN, and for the SECOND time did just a rinse, soap scrub, and rinse off. That did a better job but still left streak marks and didnt get a lot of the dirt. That was $3.
So we paid $10 for a good vacuum and two bad washes...so not the greatest deal. But its cheap and kinda fun so give it a try if you want, just dont expect a miracle. Users/omnipotentdude

20100622 18:16:29 nbsp Overall not a bad place. The price is decent. Pros: high powered wash is actually quite high powered and got the bug guts of off as well as getting years and years of dirt out of my floor mats. The dryer squeegee thingy also was great at getting the water out of the floor mates, so it was really nice to be able to wash my mats rather than just vacuum them. Overall, my car came out decently clean. The vacuum is quite powerful and very cheap. Cons: the spotless rinse is anything but, it left streaks and droplet tracks all over my car. They dont have any sort of scrub brushes that will get stuck on dirt and bugs off. I forgot to bring my own, so I ended up having to use my hands and nails to get the bugs off which is kinda gross. Users/RachelPeters
  Not sure what you mean... there is definitely a scrub brush setting, and the brush itself was on the other side of the bay from the highpowered wash tool.  That said, I had a bit of trouble with the brush because it generated so much soap that it was hard to tell if my car was actually clean or not without rinsing it first.   Users/CovertProfessor

20100828 15:18:36 nbsp Satisfied with the facility, the option of using credit card while you are using it and stopping it when done, is good. After moving from the midwest where i typically charged the card once and the time would run out and would swipe the card again for more time, would result in more expense and unutilised time a waste of money. This one worked well for me and the cost was lesser than my past experiences at other places in the midwest.  Users/snehalt

20101009 16:48:41 nbsp I drive a convertible which cant be taken through the automated washes.  Therefore, my only options are this place and the cable car wash.  In my experience, the most cost efficient way to get your vehicle clean is to do a quick wash on your first $2.50, let the time run out. Then use your own towel or sponge to get in the cracks and crevices, then put in another $2.50 and get the details.  Im almost tempted to be super cheap and bring a bucket and a gallon of tap water to make sure I get all the little spots right.  Users/MasonMurray

20110508 16:51:32 nbsp I came here when some jerks egged my car and again when someone dumped a pizza on my car (seriously, a pizza?) and enjoyed using the high pressure hose. Five bucks for eight minutes of washing is reasonable and my only complaint is that the timer keeps going when you have the dial at the Stop position. Sure, it makes sense when there is a line and the place could be making money if some jerk is not just waiting for his car to air dry or something in the spot, but I just find no reason for ever setting it at Stop. Users/hankim

20110508 20:15:21 nbsp I can wash my dog with an oatmeal treatment, shampoo and conditioner for around $5. Shes a pretty big dog  60ish pounds. She hates water, and trying in the bathtub is a disaster  so the little table with leash attachment is PERFECT. I love Planet Wash because of its pet wash.  Users/ChristyMarsden

20120624 20:44:53 nbsp I tried this place today. The concept is good but they need to chalk out the instructions to use their equipment. It took me a while to figure out how to dispense the soap. When I swiped the credit card I had no idea how much I was being charged ($2.50 for 3 minutes). It does not give you a warning when there is one minute left if using a credit card. It gives a 1 minute warning only if you are using cash. I also tried the vacuum which costs a dollar for 4 minutes. The vacuum is really good. I had the interior of my car spik and span within 8 minutes so I spent two dollars.  Users/DivyaAiyar
