Planned Educational Leave Program (aka PELP) is for UC Davis students who wish to take a temporary leave from school for certain reasons.  This program allows students to take time off from school to work to pay for student fees.

 Beginning in the 20052006 students may only PELP for one quarter as an undergrad per the Office of the University Registrar Registrar website. The PELP fee has also increased from $40 to $55 (now $60). http://registrar.ucdavis.edu/update/#Pelp  :

Leave of Absence: Planned Educational Leave Program (PELP)

The Planned Educational Leave Program allows any registered studentundergraduate or graduateto temporarily suspend academic work at UC Davis. Undergraduates may take one such leave during their academic career at UC Davis and that leave is limited to one quarter in duration. For graduate students the maximum leave is up to one year. Undergraduates apply for PELP at the Office of the University Registrar. Graduate students apply through their departments and professional students apply through their Deans office.

Applications for PELP may be filed as late as the tenth day of instruction during the quarter for which the student is requesting a leave. However, approved applications submitted after the first day of instruction will entitle you to only a partial refund of fees paid, in accordance with the Schedule of Refunds. The Schedule of Refunds refers to calendar days beginning with the first day of instruction. The effective date for determining a refund of fees is the date the completed and approved PELP form is returned to the Office of the University Registrar. See the Fees, Expenses and Financial Aid chapter.

An application fee of $60.00 is charged to your account when you enroll in the PELP program. This fee is identical to that paid by a student who withdraws and is required to pay a readmission fee upon return. After filing your PELP form, you must file an exit form with Student Accounting.

While students may receive academic credit at other institutions and transfer this credit to UC Davis (subject to rules concerning transfer credit), participants are reminded that the intent of the program is to suspend academic work. Therefore, students are urged to carefully evaluate the desirability of taking academic work while away from the campus during PELP. Students enrolled in PELP are not eligible to enroll in Open Campus (concurrent) courses at the Davis campus, or to otherwise earn academic credit at Davis during the PELP leave.

Readmission is guaranteed assuming you resume academic work by enrolling in courses, satisfying any holds that may have been placed on your registration and paying your registration fees by the established deadlines for the quarter specified for return on your approved PELP application. Students who do not return by the specified quarter will be automatically withdrawn from the university.

You will not be eligible to receive normal university services during the planned leave. Certain limited services, however, such as placement and student employment services, counseling, and faculty advising are available. Students on PELP may purchase a health care card from the Student Health Service and may retain library privileges by purchasing a library card. International students should consult Services for International Students and Scholars to find out how the PELP will affect their status. Grants and other financial aids will be discontinued for the period of the leave, but effort will be made, where legally possible, to allow you to renegotiate loan payment schedules and to ensure the availability of financial aid upon your return.
