This is a page to leave stories of alleged and factual racial profiling, police agressiveness, misconduct, and unconstitutional rights violations on UC Davis Police Department campus and in the Davis Police Department City. The flip side of this page can be found at Police Appreciation Stories.
 http://www.aclunc.org/publications.html For a full report on racial profiling in California (ACLU)

http://www.sacbee.com/content/news/story/13489410p14330102c.html According to information provided by the Davis Police Department, According to the data presented, blacks and Latinos were arrested at significantly higher rates than whites during the first seven and a half months of 2005. From Jan. 1 to Aug. 19, Latinos accounted for 20.5 percent of all arrests in Davis, while comprising roughly 10 percent of the population. During the same period, blacks accounted for 9.2 percent of arrests, while comprising about 2.4 percent of the population.

  Are those arrested necessarily citizens of Davis?  After that question is answered, what is the average for black/latino arrests relative to their population?  Answering that question would tell us how much above or below Davis is in terms of this.


 Racial Profiling Stories 

March, 2006: The Davis police are facing an upcoming civil rights suit after initiating an investigation and arresting Halema Buzayan, a high school student, for allegedly bumping into and denting another car in the Cowell Blvd. Safeway parking lot.  Buzayan denies that she was driving at the time and her father showed photos to KGO news personnel which he claims demonstrate that it could not have been the Buzayans car that made the dent.  However, a witness to the accident took down the license plate, which matched the Buzayan family vehicle, gave a description of a teenage driver that matched Halema, and picked Halema out of a photoline up.  Regardless of fault, the police continued to pursue criminal charges against Halema after it had been settled civilly between the two parties.  The victim criticised the police investigation on KGO news: For them to prosecute something like this  this is a bumper bender in a parking lot  really makes me question where the priorities are.  http://abclocal.go.com/kgo/story?sectioni_team&id4000500 abc story.


November, 2005: An AfricanAmerican couple alleges racial profiling and discrimination by Davis police.  Ivy Anderson and David Johnson file a civil rights lawsuit, citing cameras set up around their home recording over 500 incidents of Davis PD driving by their home, shining lights, etc, but making no arrests.

November, 2004; Senior Richmond Darko, a 20yearold born in Ghana, wants an explanation why police stopped him on his way to a computer lab to search his backpack and ask what he was doing on campus.You were in the wrong place at the wrong time, Darko recalled an officer telling him. The Davis Enterprise Archives &#8220;Racism at root of police complaint&#8221; By Lauren Keene Enterprise staff writer Published: October 15, 2004

October 5th, 2004:  AfricanAmerican UC Davis graduate student Ebrima Ceesay was stopped by UC Davis police at the corner of Kleiber Hall and Hutchison drives at about 4 p.m. for obstructing traffic by not giving the right of way to a pedestrian. The officer then proceeded to ask if Ceesay ever had any driving tickets, criminal records, tattoos on his body, or lived in Oakland. Ceesay said he found the questions demeaning and dishonoring, and of no relevance to the alleged bike infraction. During the incident, a second officer pulled up behind Les patrol car and observed the conversation with one hand resting on his gun, Ceesay said.

It should be noted that it is acceptable and legal for officers to place their hands on their guns or holsters for various reasons.  Officers are trained to do this in unassessed situations as it can greatly assist in response time in a situation where either lethal force or the threat of lethal force is necessary.  Some believe the posture may be used as a method of intimidation and question how often it is done when questioning minorities versus similar situations with nonminorities.

I get asked similar questions everytime i am stopped including have you ever been arrested, do you have any warrants, where do you live. It should be noted that in every stop police verify all your information with NCIC and know the answers to all these questions already, they are simply asking to testyour honesty for whatever reason not necessarily to demean you. In the above case there was probably someone who matched the description of the person stopped that the police were actively looking for.

http://occr.ucdavis.edu/news/view.cfm?news_id61 The Davis Enterprise Archives: Racism at root of police complaint by Lauren Keene Enterprise staff writer (October 15, 2004).


Exact date unknown, Fall 2004: Frederick Clarke, a secondyear AfricanAmerican graduate student in computer science at UCD, said police officers stopped him and his roommate while in the process of getting their bicycles.One of the police officers was nasty in his approach to the whole thing, Clarke said. One made a comment about having an Uzi in my pocket. UCD grad student files complaint against campus police&#8221; by Katy Tang Posted 10/18/2004, California Aggie

i think i know this cop, i was stopped by him because i matched the description of someone who they were looking for and while he was searching me he asked if i had and weapons in my pockets such as grenades, rocket launchers etc. its a joke, at least in my case i dont think theres anything wrong with that

 Misconduct 
May 18, 2009:
Please read the UC Davis Police misconduct complaint that I sent to the UCD Police Chief. I hope that my concerns will be noted. I cannot believe that regular citizens are being treated this way.

Sir/Madame,
On May 18th 2009 around 10pm, I was stopped by a police car at A street and Hutchinson Dr vicinity in Davis California. I was driving a 1995 white mercury tracer, belonging to my daughter. I had just dropped of my daughter, who is a student at UC Davis, and was looking to make my way back to Hwy 80 for Sacramento. I got lost around the place mentioned above and called my daughter for directions. At that time I saw the blinking lights of the patrol car behind me. When I was pulled over I did use a cell phone and understood that I was in violation.
When the officer approached my vehicle from the right and knocked on the window, I opened the right side door. Due to the darkness in the car and the officer’s flashlight that was shining in my eyes, I could barely make out the officers’ profile due to his position at the right back door. He told me that I was in violation for 3 codes: 1. Cell phone use while driving. 2. Tail light failure.(checking afterwards, revealed no tail light problem) 3. License plate light failure. He said that he will write me only one ticket for the cell phone violation and dismiss the other ones. He asked for license, registration and proof of insurance. I provide my license (wallet) very quickly but had trouble finding the registration and proof of insurance (glove compartment) as the car was dark and the flashlight of the officer was constantly pointed at my face. I found the registration and the insurance paper and gave it to the officer. (Due to the darkness I must have given the officer the expired insurance paper instead of the current one.) The officer went back to his vehicle and I waited in the car. This allowed me time to go over all the facts and then I remembered that my drivers’ license has my previous address. I wanted to inform the officer of this fact as such that the correspondence of this traffic violation would not be sent to the wrong address. I opened the door and waved at the officer to get his attention. After a few seconds the responds was aggressive and loud: “Get back in the car and close the door!”. I got back in the car and waited. Finally the officer came back and stood again on my right barely visible. He told me that my insurance document was expired and said he was giving me a ticket. I told him that there was insurance on the car and that the document must be in the glove compartment. He told me that I had already ample time to find it. (this is not correct because I was only informed of this a few second before) I started looking for the current insurance documents on the seat next to me when he loudly shouted at me to stop it or he would take me to jail right there. I just sat silently in my car and waited for this to pass. The last time I was approached with such immediate verbal aggressiveness was during infantry basic training 26 years ago. He stretched to let me sign the violation report and walked off.
I fully understand and respect the authority of a police officer and I will pay the fine without reservation, however this random humiliation at the hands of this police officer has altered the image I had of a Police departments’ ability to serve and protect.
My complaint does not question the validity of the traffic violation nor does it question enforcement of the law. My complaint does question the capability of the officer to correctly read the situation in front of him and his overall poor job performance. The officer was rude, inpatient, threatening with total disregard of civil acceptable behavior. This behavior might be warranted in gang infested neighborhoods but not towards every day civilians being stopped for a traffic violation. I feel humiliated, frustrated and worried that my daughter might be approached the same way during her college time UC Davis.Users/ConcernedParent

August 26th, 2006: Whatever Rights You Think You Have You Dont.....this line was said to two UCD student leaders, Chris Herold, former chair of the ASUCD Business and Finance Commission and Eric Zamora, former Student Assistant to the Chancellor as well as myself, James Schwab ASUCD director of External Affairs. Furthermore, we have all sat on the CityStudent Liaison Commission.

Who said this line? A Davis Police officer.

This evening at 12:45am an officer responded to a noise complaint for our going away party for friend. Eric and Chris answered the door. They were not residents of the house, so the officer requested to speak with a resident. As a resident was being fetched, Eric closed the door slightly. The officer put his foot in the door and said he cannot shut the door. The officer continued and said that whatever rights you think you have you dont. Once a resident came to the door, the resident, Eric, Chris and officer talked outside. I was not a part of this coversation, but Eric and Chris told me the officers tone was very threatening. They both used audio recorders to tape the conversation.

I am extremely offended that a public servant in the City of Davis confronts its citizenry in this manner. There was absolutely no reason for the officer to take a threatening manner; Eric and Chris were both polite and cordial they have both worked consistently with leadership from the University as well as the City police departments. Second, for a police officer not to believe in a citizens rights is disturbing. I never thought I would hear such language used by an officer who has sworn to uphold the law.

I do not know the name of the officer, only that he drove one of the white, unmarked vehicles on FridaySaturday August 25th26th.

I plan on filing a formal complaint, as this behavior should not be tolerated by citizens or fellow officers.
  Doesnt it seem a bit irregular, perhaps unfair, to shunt this over to the talk page, when there are many other lengthy discussions on this page?Users/CameronMenezes


June 17th, 2005: Police accidently rough up an autistic 17 year old in Slide Hill Park after receiving a report that he attempted to lure a young girl into the car. http://www.davisenterprise.com/articles/2005/06/17/news/197new0.txt read the Davis Enterprise story.

April 16th, 2005: A police http://www.livejournal.com/community/ucdavis/2093976.html misconduct story was sighted on the UCD LiveJournal, about overactive police during Picnic Day.


June 2004:Police Pepper spray individuals at a party.  Also, police arrest couple in alleged domestic dispute. Both incidents are detailed in http://www.californiaaggie.com/media/storage/paper981/news/2004/06/02/FrontPage/Students.Police.Stories.Differ1317742.shtml this California Aggie article.

April 24th, 2004: Im not sure if this should be classified as police misconduct, or just really fucked up, so feel free to correct me if needed. Me and five other friends were coming back from a DPS formal and had a stupid idea to go see the llamas over by the Veterinary Medicince Center on campus. After driving slowly by the llamas, getting our fill for the night, we were on our way out. Then, from out of nowhere, a cop car appears and pulls us over. All of us were completely sober, and the driver had been following the traffic laws, so we all were dumbfounded as to why the cop pulled us over. The cop asked our driver why he had run the stop sign 10 feet behind us, but the odd thing is none of us could remember seeing a stop sign and didnt know what the cop was talking about. We all had to get out of the car, still in our formal clothes and show him our student IDs, and were each badgered about why were doing there, where we were earlier that night, etc. Eventually they let us go, but before they did the cop added casually, Oh, and dont worry, you didnt run a stop sign, were pulling over all the cars through this area because were looking for ELF and/or ALF demonstrators... heightened security for Earth Week, you know... and you guys just dont fit the profile. Though they let us all go without incident, I found the whole incident a little weird, and was sure glad I was in my formal clothes and didnt fit the profile.

March 5th, 2004  A friend of mine from an aerobic walking class confided in me that she was going to have to leave the country to protect herself and her kids from her allegedly abusive ex husband. I never met the exhusband and didnt even know my friend that well at the time, so I had no reason to take sides there  but as soon as she left, the police inevitably came after her for violating the custody order. Now there are laws there that they have to enforce, I understand that and dont blame them for contacting me for info (which I didnt have, she didnt tell me where she was going). But investigator Rick Gore from the Yolo Countys DA Office, who they sent to interview me, made several sexist comments, for example saying that if she were to call me, then he would want me to let him know first so that they could tap the phone, but that I shouldnt worry or get embarrassed since he wouldnt pay attention or gossip if we started to talk about boys or something. Also he told me that they had to find her because she couldnt survive on her own in a foreign country, what would she do once she got her period and got cramps and couldnt even go to the public health hospital? I felt so awkward having to talk about cramps with a male investigator, and I got the sense that he thought my friend and I were like young children or junior high girls. CristinaDeptula

September 1989,  A black lawyer is allegedly beaten by Davis police according to a group of witnesses who saw the incident. The investigation into the four officers accused of the beating is kept private by the City. Sacramento Bee on September 15, 1989, Page B1 and September 14, 1989, Page B1

December 20th, 1989  The Yolo County district attorneys office prosecuted, William Caldwell, a black man for resisting arrest in an incident outside a community theater, even though the city of Davis that the charges be dropped. The arrest in September of 1998 of Caldwell who was an amateur actor and recent graduate of the University of California, Davis, School of Law, prompted public protest and criticism of police tactics. Sacramento Bee, December 20, 1989, Page B2,
 Civil Rights Violations 
November 18, 2011 UC Davis Students PepperSprayed UC Davis Police pepper spray peaceful protesters

April, 2004: Sterling Apartment prePicnic Day party. Anonymous UC Davis football player is shot in the eye with a police pepper spray projectile. (basically a paintball gun that shoots pellets filled with a mixture of cayenne pepper and water) The student was on his balcony in Sterling Apartments, during the Sterling riots. Police are trained to avoid shooting the pepper projectile guns at peoples heads, otherwise the guns MAY become http://www.policeone.com/pdfs/bostonglobe.pdf lethal.  The student became blind in the eye he was hit in, and lost his sports scholarship. A lawsuit he filed is still pending.
  What was the student doing when he was shot?  He was obviously not leaving the area.   Why did this student remain at the party after being given lawful orders to disperse (leave the area)?  I know for a fact that officers gave orders to disperse MULTIPLE times before firing any pepper projectiles.  CameronMenezes
         The student was on the balcony of his third floor apartment looking down and whaat was happening. Users/JimSchwab
          Officers gave orders for everyone to leave the area and return to their apartments/get off the apartment grounds.  Officer did not know where, or who, was throwing the projectiles (at the police).  A thirdfloor balcony with boozy people on it would scare me, as an officer, since those people could chuck anything right onto my head (if I were on the ground).  In my opinion as a nonpolice officer, the people on that balcony were definitely an implicit, if not explicit, danger.  Or should the cops have simply had blind faith in the goodness of the people on the balcony?CameronMenezes
            I actually agree with you on this one, they should just shoot everyone on every balcony. Users/JimSchwab
             Jim!  Weve finally agreed!  But remember only if the person refuses to leave that balcony after repeated, and lawful, orders from the police. :)  July 20th... Ill write that down so that you and I can send congratulatory messages to each other on every anniversary of our first agreement. :)CameronMenezes


Can we have an examination of the increased police presence during Black Family Day (including the calling in of other local agencies: Yolo county, Woodland police)? Also, Look into the hesitation the police have of too many black people in davis, and the desire to have such events over before sundown. The early closing of businesses and police turning people away from AMPM on such nights. Users/DavisWikiGnome
  Dont know about the rest of the stuff, but how could the police have anything to do with businesses closing early?  Police officers cannot tell businesses to close, unless, of course, the business is illegal! :)  Black Family Day is a large event (with great food, I might add).  Having other agencies oncall doesnt seem that unusual... just my $.02.CameronMenezes
  Actually, police can shut down businesses when they feel that there is imminent threat of civil unrest. In 2006, the July 4 fireworks display at Raley Field was shut down by police after about 15minutes because a couple started a brawl that began to involve bystanders. How imminent threat is determined is, I suppose, at the discretion of the police officers present and is likely colored by their personal beliefs. Users/AlphaDog
    ADog, good point.CameronMenezes
   Should we then also investigate the large police presence during picnic day?  DaveZavatson
   Picnic day is entirely different, with a lot of alcohol and tons and tons of people.  If you compared the amount of police per people present black families day certainly has more. (im not talking about rained out picnic days of course, but i would still guess the analogy holds) Users/MattHh

 Addressing the Problem 

It is important that we identify, clearly document, and generate awareness about injustices in our society, but it is also important that we move toward a solution to this problem.

Solutions and things to keep in mind:

  Encourage free discussion between parties.
  Focus on bad aspects, but also identify and recognize good aspects. i.e. Police Appreciation Stories (they may be paid to do their jobs but we can also show our gratitude for their actions)
  Push for good individuals to join the force, instead of pushing them out. (collateral damage from harsh criticism directed at the entire police as opposed to individual officers who commit the actions)
  Generate and brainstorm new and innovative solutions in addition to identifying the problem.
  Occasionally, a misunderstanding may result in police misconduct, or in police conduct that is misinterpreted as misconduct. Knowing How to survive police encounters how to survive police encounters may help one to avoid these misunderstandings.
