These are older comments about Alvarado Sunset Apartments made prior to the 2010 change in management.  For current comments, Alvarado Sunset Apartments view the main entry.




20050422 14:04:50 nbsp It generally is pretty quiet in Alvarado Sunset, but the apartments tend to run a little bit dark.  Bring lots of lighting.  (I should note: when I say quiet, I mean studentwise.  It wasnt a big party place when I lived there.  Traffic noise is another thing altogether).  Users/AlexPomeranz

20050828 19:25:15 nbsp Absolutely worst apartment complex in town. The management is horrible: they do not respond to maintenance request forms, are never in the office, and give you the run around. The apartment was a mess when we moved in and they never fixed the things they said would be fixed. The windows rattle whenever someone shuts a door. The laundry facility has 3 washers2 of which steal your quarters. It is also noisy becuase its between Covell and Alvarado, both of which get a lot of traffic. While the rooms are decently sized, its not worth hassling with the management and the rest of the building which is so old its falling apart.  Users/MegLane

20051019 17:55:51 nbsp I agree with MegLane in that the apartment is horrible. Please dont move there. I am in the process of suing them and it is more trouble then you would ever want. Ever! The owners live in San Jose (Mr. and Mrs. Lee) and accuse students of doing whatever it takes to get what they want. Plus it is too expensive for what you geta dirty apartment and lousy management. Users/NicoleChunNelson

20060411 15:06:34 nbsp I think that the Alvarado Sunset complex does have its draw backs, but it is reasonably priced. The management does have their problem and do change constantly, but I see that as an effort from the owners to fix things.  Users/JohnKim

20070205 14:03:28 nbsp This place totally sucks. In addition to the things that have already been said, which are completely true, there are a number of things that are absolutely infuriating. First off, right where my roommates and I could be parking the owners of the place park their big white truck and crap volvo. What few times they do remove them for an hour or two they put cones in the spot so no one takes their spot. It takes weeks to get anything fixed for no apparent reason. The only time I see the maintainence guy is when he is eating his lunch which for some reason takes him two hours. The gardeners come at seven or eight in the morning and run their multitude of motorized equipment which is really annoying when youre trying to catch those last few zs before class. The plugs fall out of the sockets and the elctricity hasnt been inspected since 1972!!! To top the whole thing off, the internet is the worst Ive ever experienced. Its even slower than the dialup my parents have back home! My roommates and I are getting out of here as soon as our lease is up in june. Users/JeffKreis

20070717 11:42:06 nbsp Dont get instaconnect, or be prepared for tech support hell Users/davisGeek

20070811 14:58:50 nbsp My only complaint about this complex is that some of the tenants are loud at odd times of night and sound seems to really carry throughout the complex. They also seem to change managers fairly often. At one point we were sent us a notice that our rent would go down, then when a new manager came in, we were told that we should have been paying more for the last six months. Since we could not produce the notice that our rent should go down we had to pay the difference, which wasnt too bad, but that manager was really nasty about it. The new lady seems really nice though.  Users/GabeDavis

20071211 16:52:00 nbsp The apartment units are close to either Alvarado Ave or Covell Blvd. The traffic is quite noisy, especially during the daytime. The buildings are very old, you probably will get problems now and then. A small noise upstairs can be heard clearly downstairs. As mentioned by other residents, the apartments tend to run a little bit dark. This place somehow sucks.    Users/DumbCrab

20080214 00:48:00 nbsp First year living here, quiet little place. We had been shown the new renovated models and promised we would get something similar, instead we received an apartment that was old and wasnt even cleaned up after the previous tenets.  We had a huge fix it list from week 1 but it took them week 4 to even get us new screens to replace the ones with holes in it.  Blinds mismatched, some of them yellow and grimy.  Pretty bad shape overall.  Aside from that management was recently changed this year and seems pretty nice.  Wont live here again.  Heard rumors that they rip you off when deposit times comes around...well see how that goes considering the apartment wasnt even ready when we got here... Users/tuckerm

20080514 16:50:08 nbsp The ad they have been running in the Enterprise for years says they are a halfmile from UCD.  I dont know what UCD they are talking about, but they are more than a mile from any part of campus.  Covell is one mile north of 5th St./Russell, and they are north of Covell.  Isnt this false advertising, and isnt false advertising illegal? Users/aharjala

20080606 11:18:12 nbsp Looks like they finally corrected their ad.  It now says about 1.5 miles from UCD.   Users/aharjala

20080821 16:08:00 nbsp MAN, this place is DISGUSTING. Do NOT live here, no matter WHAT you do. The management (the woman) is very nice and so is the maintenance man. However, I think they probably need 23 more maintenance men because my apartment had SO MANY problems when I moved in, and when I put in an order, only some of the problems were fixed. I had to keep reminding them to fix them (broken closet door, broken window screens <I mean comn, how can people move in when these simple things dont even work).

AND WHAT IS EVEN WORSE, THERE IS A COCKROACH PROBLEM HERE. My roomie just recently found a 2 inch cockroach in the kitchen, but it isnt a recent problem, it has been occuring throughout the school year. The furniture is old. The carpet is disgustingly old. The kitchen hasnt been cleaned and doesnt look like it was ever cleaned since we moved in. And it is basically OLD AND DIRTY. I really regret signing a lease here and it was so bad that I didnt even want to come home.

That being said, DO NOT LIVE HERE. DO NOT LIVE HERE UNTIL THEY DO SOMETHING TO FIX THIS JUNK HOLE UP. BTW, the exercise room has equipment that doesnt even work.  Users/renee415

20080904 16:29:55 nbsp Renee415// Well I never found any cockroach in my unit for the entire 20072008 school year. Probably you need to keep your own kitchen a bit cleaner. One or two cockroaches might slip in when you open your front door, but since you said it happened throughout the school year, then the cockroach nest is in your kitchen. You cant blame anyone else but you and your roommates for not cleaning up your own kitchen. Users/ChickenNuggets

20080907 19:55:20 nbsp Hello. Can anyone of the current residents share the experience of living in the Alvarado Sunset complex. If you moved our recently, I would appreciate your opinion too. Thank you Users/bayer044

20080920 14:56:44 nbsp ChickenNuggets // If the cockroach problem was in our kitchen, why was the maintenance man unable to solve it even when a socalled exterminator was brought in? My roommate and I cleaned DAILY so I do not believe cleanliness was a problem. Moreover, I do not appreciate you making assumptions about my situation when you were not in it. To add to that, there were cockroaches OUTSIDE of my apartment as well as in the closet downstairs. In most CLEAN living areas, cockroaches do not just slip in when you open the door. I just moved out and I am glad that I am out of here. It was a waste of money and I couldve found a better apartment somewhere else for such expensive rent.  Users/renee415

20081215 20:57:51 nbsp I have lived at Alvarado Sunset for two years. It is, by far, not bad. Yes, it may not be new and flashy, but the rooms are big and quiet, all the appliances work, and the heating/AC works great. All and all, this is a decent apartment complex. Users/Izz

20090303 19:38:23 nbsp I moved in here September of 2008. Everything they said that was going to be fixed before I moved in was. When my boyfriend and I moved in we had new carpet, new refrigerator, new stove, and a new microwave. The panel on the air conditioner was broken but they came and fixed it right away. I have not had any problems with the management, they have always been really nice and understanding. I like the location because it is near a lot of shopping and it is an easy bike ride to campus. Plus the bus stop is right in front of the complex. I would live here next year because our place is so nice, but my boyfriend and I want to move into a smaller place. By the way the two bedroom/one bathroom is huge and has a huge storage closet under the stairs.  People tried to warn me not to move in here but I dont know what they were talking about. I really enjoyed my time here because the complex is really quiet. There is plenty of parking and I am always able to park right in front of my townhome.

 Users/jthernandez

20090306 16:25:31 nbsp Everything is a lie! This place is so bad and the management is horrible! During my walkthrough I already noticed like a yellowish mold looking color on the ceiling and the manager says what do you expect? this place is old and cheap So rude! Anyways, in October there was a big storm and we ended up we a hole in the ceiling! Water was dripping everywhere and it stunk up the entire apartment. It was horrible, especially a hole in the ceiling? It took them over 3 months just to get it fixed! Seriously, it took forever because we could see the water flowing down the living room because this yellowish color showed up down in the middle of the living room. She promised it will be done before winter quarter starts and she has the people do the ceiling the first week of winter quarter. Every door had a patched up hole, our oven is retarded it took me 4 hours to bake a cake because it wasnt hot enough it was like already nearly 400 degrees. When I first moved in, there was a big crack across my window, and there was something inside the garbage disposal because it was making really loud sounds but the manager says it was suppose to make a loud sound like that, my friend came over and checked it out and pulled out a NAIL! Also, in one of the rooms, there was a big long spider web, I was complaining because my deposit is meant to move into a clean and new apartment, apparently it was not clean at all! The manager expected me to clean the spiderweb myself! The bathroom leaks all the time. Every morning they always have these workers do the lawn but this place suck so much I dont know why the manager have to spend so much on the workers doing the lawn, they should focus more on these problems. I agree with MegLane, the manager is never there! The office hours say she will be in at 8, she doesnt show up until 10. She uses her working time for her personal time; to pick up kids, dentists appointments, etc.

 Users/KimY


20090416 15:10:35 nbsp This is the current manager of Alvarado Sunset Apartments. My name is Cora Brice. I would like to respond to the latest pictures and comments posted by KimY. Kims comments regarding how the management has responded to her were made by our temporary helper at the time. The helper is no longer with our company. I would like to apologize of any statements made by the helper during the September movein.

The broken window was replaced on the day that she moved in, and I was the one who helped Kim to pullout the nail from the garbage disposal. Also, Kims apartment currently has new roof, ceiling, oven, and doors.

We have professional lawn service contracted to our apartment. They manicure the property once a week on Fridays. Our office hours have always been posted at office. Our current office hours are Mondays (15pm), TuesdayFriday(105pm), and Saturdays (15pm). Users/corabrice

20090429 21:27:09 nbsp ok it says above no dogs, but someone im coresponding with said you CAN have dogs. Users/StephHolm

20090811 14:16:29 nbsp This complex is an interesting place.  We constantly had issues with our neighbors from the 18 year old puking drunks at our back gate to the older ones next door complaining we were too loud.  The place, like many Davis apartments is run down.  The work orders, when completed, were only rigged to serve a short term fix and were never really resolved.  The maintenance guy was not around often because of course Jon Berkeley Management is a horrible.  We can hear traffic very easily.  The blinds we had were different shades of off color white, they were dried and cracking, falling apart, and different lengths.  The front door handle always shakes loose, the bathroom fan doesnt even sucks a piece of plastic up to it.  Weve had lots of water damage and their idea was painting over it.  Weve had our cars broken into SOOO many times. The community washing machines are always breaking down and none of them seem to be set for the same time to wash. Overall its just rundown and perfect for someone who doesnt really care where they live.  There are lots of tree roaches in the bushes and there workout area is just that an area, the machines (the last time I checked) were either broken or missing vital pieces.  The manager was nice, but she seemed overworked.  I think its overpriced, but that seems to be the way Davis is.  Davis is a great town and we found something else for the upcoming year. Users/PinkLadie


20090813 23:17:15 nbsp
This place is for you if you enjoy watching and listening to drunk party right in front of your door at 3 AM in the morning.
Users/BigWilliam

20090901 18:21:01 nbsp On move in day, the carpets were DISGUSTING and covered with dust (not to mention really, really old).  The kitchen looked like someone had a party in it the night before.  Blinds were broken.  Closet doors were dirty.  The list goes on.  We had to spend about 4 hours pleading with the management before they did anything about it.  The carpets are still disgusting though.

I can tell that what everybody says about the management is 100% true.  Its so horrible, it makes Allegre apartments seem like a godsend. But theyre not.

ONE TIP IF YOURE PLANNING ON OR ARE ALREADY MOVING IN HERE:  Take a leaf outta Nicole Chuns book and take pictures of EVERYTHING before you clean a single thing.  I took over 50 pictures of various things wrong with the apartment for evidence.  If they try to make me pay for something I shouldnt be paying for, Im going to court as well.  Hopefully, if enough people do this, theyll be so out of money that they have no choice but to listen to their residents.  God knows its not happening any other way.

Lastly, the management is so horrible because no one wants to step up and take responsibilities for their faults.  They keep shoving responsibilities to each other and never get $#!+ done.

Ive talked to many of my neighbors about this, so if there are any people who feel that theyve been wronged as well, please email me at kidkoryo@gmail.com ... Users/kidkoryo

20090922 01:44:27 nbsp so now that i moved out... still do not live here!! so shady!! i cleaned so hard and even the manager told me that it was clean.. light clean she said and i only got half my deposit back... these people rip you off! nothing gets done! they told me they would give me new closet mirrored closet doors.. NOPE gave me some crappy three door sliding ones and is always in the way! never came to fix the bathroom! they were suppose to give me a new oven but instead the maintenance guy mistaken it and put it in another apartment!! not only she told me when i asked  her about it.. she knew about it and just left the oven in the other apartment!!!! only when i asked her about it, that is when she actually replaced my old one.. and on top of that.. the last week where everyone of course is packing and moving out.. she doesnt extend the hours so that people can come in and turn in the keys later the evening like 6PM!! she never picks up the phone calls and again like i said before.... she still takes her office hour times to do her own personal errands. it is true there is a lot of roaches and bugs. i still did not get new carpets like she promised! when we move out they gave us a packet of how to clean the apartment! pshh! like thats not how clean it was when i moved in! these people are scandalous and they just want to rip u off! its also true about the workout room! its not even a workout room.. everything is broken in there and it smells and its small! the fire alarm sucks, it goes off everytime you cook.  Users/babykimchii

20090922 01:58:46 nbsp i agree with everyone above me. seriously this manager needs to get her priority straight, as a manager she is suppose to get the maintenance guy to do the right things at the right time, it isnt our problem that these people dont listen to her maybe she shouldnt hire shady people and actually hire hard workers like other apartment complexes. she is nice and all but she is over all a lazy manager who acts as if she is really working but she doesnt. she just procrastinates and acts as if she is really doing her job. and our deposit is suppose to be security money to promise the residence a clean complex but on the contrary  it isnt with roaches everywhere and dirty carpets and horrible lighting.  Users/Andy123

20090928 09:58:19 nbsp Well I agree with some of the comments above and others I don’t. Oldness of the complex: It is very true. The units are old and the blinds are sometimes mismatched mine look like they were hand cut. I also moved into an apartment with older carpets. I agree do photograph everything when you move in (but do this anywhere you move).
Repairs: (The above situation looks pretty bad).  I had only one major issue and a couple of minor repairs. I had water come under my back door during a rain storm and my carpet was taken care of within 2 days. I also had a hole put in to my wall while moving furniture…if I am to be honest I would have to say that it was a sad excuse for a repair…but none the less it was done quickly. I also had a door closing issue. He fixed the working door on accident, but returned to fix the broken door the very next day. I will excuse the round toilet seat that was installed on my oval toilet and then the old one left in my kitchen. They did return with the proper seat. I think that in the real world sometimes you have to squeak a little louder. I think that the person would have been better off emailing these pictures to Jon Berkeley management and giving them a chance to remedy it, rather than waiting to be angry.
Loud parties: I have lived in Davis for 15 years in 4 different complexes.  I don’t find this one to be any louder than any other complex, especially on a Thursday night. Once again – if you have super noisy neighbors – complain!
The work out room: The treadmill is new and also the elliptical. There is also a weight set
The manager: I think that the manager is a pleasant person that does seem to be over extended at times.  I have only had positive exchanges with her and she has followed through on every repair that she has promised.
I renewed my lease this year and I plan to again next year.  They are older, and could probably use a little more TLC by the property management company, but the location and sq footage are good.  If you have any questions feel free to contact me im_cognac@yahoo.com  I will answer honestly.
 Users/cognac

20091118 14:19:54 nbsp I really regret having signed a lease here.  Its so disgusting and old and everything needs to be replaced (including furniture).  Im a clean freak and I could not live in peace.  I ended up staying the majority of my time at my best friends apartment.  There were cockroaches, spiders, etc. and everything just looked dirty.  They obviously didnt clean before we moved in because whoever was there before us left most of their stuff in the kitchen and bathroom drawers. Gross. Users/ElizabethLee

20091123 02:32:23 nbsp Oh yeah, I wanted to add that there was a cockroach problem in my apartment.  I told Cora and she said that she would said an exterminator to spray our apartment and to leave the apartment at a certain time slot and to pack all our dishes/wahtever away in the kitchen. So my roomie and I went through the hassle of doing all that, and guess what, I dont think that our place was ever sprayed. There was no trace at all that the exterminator was ever there and I even went back to the apartment an hour before I was told to come and no one was there. Nothing looked different and we continued to find cockroaches. We told Cora a second time, and she said an exterminator was coming AGAIN. Again, cockroaches were still in our kitchen. And please do not tell me its because Im unsanitary because I am a clean freak, I keep everything tucked away and neat and my roomie and I barely cooked!   Users/ElizabethLee

20100105 01:05:04 nbsp Theres a new manager and shes really unhelpful and kind of rude. Also, it really offends me that whenever she or maintenance stops by, they knock once and barge in right away not even giving me a chance to get to the door. I understand the building is old but management finds an excuse not to fix things (toilet, window, etc) and Im sure if I called out city inspection they would be in a lot of trouble. Users/jessk33

20100209 21:01:06 nbsp I agree that the new manager is very unhelpful. A couple weeks ago, I needed to call her to report problems with my apartment. I called the office five times (from morning to late afternoon) and she finally picked up on the last call. My apartment had 2 ceiling leaks in the past 3 months and they took a while to get them fixed. Good thing I am graduating this year and will be moving out of davis after june. Users/c144

20100218 01:40:25 nbsp The apartment was not cleaned when I movedin. The AC they have in my apartment is old and loud. It was broken when I movedin in september and it took them two weeks to get it fixed. Also, the laundry machines eat quarters and breaks often. Users/evaflore

20100413 15:29:33 nbsp If you like cockroaches infesting your apartment this is the place for you. I would never recommend this place to anyone. The apartment manager, Kari, has no respect for college students at all! She is rude and extremely disrespectful. I have went to the office numerous times to discuss the then cockroach problem. First she told me that it was not the apartments responsibility to get rid of the cockroaches but after multiple complaints from myself and my roommates she came to look at our place. Upon seeing the ten or fifteen dead skeletons of the cockroaches she claimed that they were not in fact cockroaches. After a google search and a few more complaints she decided to call an exterminator who supposedly sprayed. We STILL have cockroaches 2 months later! It has gotten so bad that instead of calling her we have to call the owner because she is so rude and unhelpful. We pay our rent on time and dont deserve to be treated like we dont matter because we are in college. My advice to you is if you have any other option, any at all, DO NOT LIVE HERE!!!  Users/davisstudent10

20100602 23:31:51 nbsp The comment above is over exaggerated. The apartment that got the bugs was the only one in the entire complex and it was because it was located right next to a big tree. It sucks that it happened, but management was fast to respond and called out an exterminator more than once to take care of it. Kari is an AMAZING land lord. She goes above and beyond for her residents, college students or not. She even makes food for everyone! She is just like every other human being. Treat her with respect and she will be helpful in return. If you go in with a bad attitude and complaining it isnt going to get you very far as it wouldnt with anyone. Kari is really making an effort to build a good name for the apartment complex. She is always changing things for the better. If you put in the effort to actually get to know Kari then you will also not agree with Davis Student 10. This is a great complex with a decent location and rent. Users/Bayliner
 ACTUALLY I STILL HAVE COCKROACHES!!!! Kari didnt respond to the problem quickly, I had to call the property management in order for ANYTHING to get taken care of at all. Kari is a horrible HORRIBLE manager. And I would also like to know how you know so much about my situation? Seems rather odd to me... I will be more than happy to move out of this complex. I am tired of being treated poorly by someone who shows neither myself or my roommates any respect at all.

20100603 10:36:42 nbsp I have been living in Alvarado Sunset for couple of years now and I can truly say everything changed since Kari came on board. We had a very difficult and harassing neighbor for five months. They were very rude and loud. After Kari became the manager, she helped to evict them and brought peace to our lives again. She even offered us to stay in another vacant apartment until our loud neighbor leave.

Whenever there is a problem, Kari has a solution. She always offers to help out in any way she can. She gave us this laundry basket on wheels, when she saw how difficult it is for us to take our laundry back and forth from laundry room to our apartment. She goes beyond her responsibility to be helpful in any matter even if it is not apartment related.

She is working very hard to bring positive changes to the complex. It felt more like a home since she became a manager. Whenever, I talk to her, she has great and positive attitude. She always talks about new ideas to improve the complex and I see the changes happening very quickly. She beyond doubt cares about the apartment and all the tenants. She tries very hard to create a peaceful and neighborly apartment. We are very blessed to have her here after many years of bad management, and I can’t wait to see all the more beautiful changes that she will bring in future.
 Users/Leila

20100603 10:59:05 nbsp I have lived here at Alvarado Sunset apartments for nine years and currently moved during Winter 2009 into our new home.  Unfortunately, I could not break my lease in December 2009 but the new apartment manager, Kari Lane was very helpful and assisted us to find other tenants to take over our lease until August 2010.  We were so very impressed with her kindness when she did not have to help us.  We are very grateful to her. Users/Chan

20100603 14:04:34 nbsp Kari Lane, the apartment manager in  aaawwwsome. she is very helpful and structured and willing to work with you...... I also like the way she has the office set up and also the club house. The apartment manager alone would be a great reason to live here. I was tired of having unfriendly apartment managers. And contrary to the non sense written here she is NOT rude, she is forever joyful. check it out! Users/tito123

20100604 11:35:22 nbsp Maybe I’ve been lucky, but I have lived here for 2.5 years and I have never had a leak in the roof, and I have never had ANY insect or rodent problems. I saw work done on several roofs the last year so maybe that is no longer an issue.

What I like best is Alvarado Apartments are large and fairly sound proof for the rent compared to other apartments I have lived in. Maybe some of you have just moved out of mom’s house and have never lived in an apartment? You can spend $500 more per month and find a newer apartment, but Alvarado is fine for the price. The expensive apartment wont mater if you have bad management and unruly occupants in the apartment that do whatever they want.

I lived at “The Willows” apartment in Davis for a year before I moved here. At the Willows you could hear every sound from the adjoining apartments, even snoring, parties go on all over the complex every night, and dozens of cars coming in at 2AM every weekend that sounded like they were pulling into my living room, and then the hooting and hollering until 4AM. I don’t think I slept a full night in a year.

Last year I reported 2 late night parties at Alvarado and the manager put an end to it, or had them move out. If you want an all night party apartment don’t move here, the manager will be on you. I think most of the bad comments are from partiers who got in trouble, or did not pay rent on time and when asked to move left some of these nasty comments. I’m all for having some fun, but don’t invite 50 people at 2AM, open your windows, and blast your stereo all night. Some of us are here to study, work, sleep at night in a safe, quiet, affordable place and the manager is looking out for us.
 Users/Yo

20100604 16:16:17 nbsp This complex is getting better, thanks to Kari, the apartment manager. She is truly helpful. She even goes to the extent of helping out with how to get to school, how to find the right people to work on your bikes and how to settle down in Davis if you are in international student. she always has a smile on her face and is very welcoming. People who dont like her here probably just suck themselves. I think she is also doing very good things for this apartment. When I moved in everything was barren, now there are new flowers being planted, and little spinners welcoming you from the street and happy faces all over to light up the place. Its a good place to live off campus.  Users/dani9

20100606 21:36:26 nbsp Ive been living here for 10 months and I think Alvarado Sunset is a nice place. Close to grocery stores, green belt, elementary/high school, 10 minutes biking to UCDavis; large rooms, beautiful landscape, plenty of parkings. The new manager Kari is super nice and very helpful. Users/jinjie

20100607 09:11:17 nbsp Does anyone else find the 7 consecutive comments praising the manager strange? They are all posted within the same week, not to mention the Several of the following comments all come from the same IP address and may be the same person warning... Users/xgen
 Yes, others find it strange... see the {{{Alvarado Sunset Apartments/Talk talk page}}}.

20100607 11:12:44 nbsp Maybe all the comments are because people actually like their apartment manager and like to rally behind her when someone gives a false accusation. Is it so hard to believe that people like to praise someone for their hard work?  Users/Bayliner
   Actually, yes, yes it is.  Its very hard to believe that eight different people, with some magical coincidence, all join this wiki in the exact same week and somehow independently all only do one single thing: compliment this single person on this single page.  With that much luck, Kari should be buying lotto tickets. users/edwins ES

20100607 18:05:06 nbsp @Bayliner.  How are you privy to information that usually only the apartment employees would know/care about?  The fact that you know that only one apartment located next to a big tree had bug problems is peculiar enough.  Not to mention that you also seem to know how quickly and effectively the management responded to this problem.

@dani9. Can Karis flowers, little spinners, and happy faces fix my broken leaky sink, leaky ceiling, wobbly stove tops, and bug problems?  If you are not Kari, which I highly doubt, then I suggest you evaluate the manager based on how well she is doing her job, rather than how well she is decorating the complex with trinkets bought from the dollar store.

Im sick of this apartment complex and their halfhearted fixes.  Roof leaks are NOT supposed to happen twice a month.  And if they do, I expect a fix BEFORE the rainy season is over.  Either way, the thing that puts me off the most about this place is Karis attitude.  Ugh.  She is rude, obnoxious, and belittling towards college students, EVEN while I am in the process of giving her a rent check.  She is super duper fakenice to prospective residents.  I just dont need that kind of dualpersonality bull spit in my life.  Needless to say, Im embarrassed to be living here.

At least Cora Brice had the courage to use her own name, and speak in the first person.  Show yourself, Kari, and face your accusers.  Lets see what you have to say for yourself.

 Users/kidkoryo
  Amen to that! The above review represents how MOST people actually feel who have ever lived under her management. The other 8 reviews are either all her or shes telling her international students that she hosts to make accounts and write them. I would advise everyone to avoid living anywhere Kari is managing. In addition to everything kidkoryo mentions, she is a con artist and was already fired from another complex for that reason before coming here to Alvarado Apartments. She will make you hate where you live and she will steal your money!


 For the record, the cockroach problem was only taken care of AFTER I called the owners and complained twice and sent them some nice pictures of my situation. I am also embarrassed to be living here and will be glad when I can move out! Thanks kidkoryo!!

20100609 16:09:29 nbsp I am also going to go out on a limb and say that Bayliner is more than likely Kari. The one good thing about that is that means she is reading this comments. My suggestion to her would be to treat ALL of your residents with respect. If you come take a poll of the college students who live in the complex more that 90% can give you a horror story dealing with Kari. If she is going to continue to manage these apartments she needs to take a few public relations classes and maybe read some effective communication classes because I am pretty sure John Berkeley Management is getting pretty tired of all the complaints!   Users/davisstudent10

20100611 13:06:25 nbsp I agree with the above posts. Kari is extremely disrespectful and rude every time I talk to her, I am surprised by the fact that she manages to be offensive and belittling even when I was there to turn in a rent check thats not even late. I actually liked the apartment when I first moved in, there are some problems here and there, but overall it is a pleasant and convenient place to live, and I was planning to renew my lease here until many extremely unpleasant interactions with the manager Kari. I have complained to Jon Berkley Management and they were more than willing to listen to the complaints and ask about specific details, however, Karis attitude never changed. Bayliners comment Treat her with respect and she will be helpful in return. If you go in with a bad attitude and complaining it isnt going to get you very far as it wouldnt with anyone. is just not true. I am always polite and respectful to her despite her rudeness, but once I pointed out that I should not be spoken to that way after one of her rude remarks, she became very defensive and got extremely upset. Now I just try to avoid her. My experiences with her and conversations with my neighbors makes it hard for me to believe the above praises are honest assessments of the manager. Users/xgen

20100616 19:14:00 nbsp The reason that I am privy to the information about the bug problem is because I am Davisstudent10s roommate, not Kari and not an employee of Alvarado Sunset. I had to deal with the situation too and my opinion of it is entirely different. I have had many interactions with Kari so that is why I am praising her. I will admit when I first met her I did not get along with her but I took the time to get to know her and now I think she is a great landlord.  Users/Bayliner

20100618 05:04:50 nbsp plot twist! Users/xgen


No I have no idea who that person is. Not my housemate. And if Kari was SUCH A GREAT LANDLORD whyd she get fired? Hmm maybe because some of her unprofessional and rude antics caught up with her!

20100618 05:07:07 nbsp lol.  bayliner, youre more ignorant than i thought.  if davisstudent10 is your housemate, then why did he say I am also going to go out on a limb and say that Bayliner is more than likely Kari. in his last post?

if you can get your housemate to log onto davis wiki and admit that he is indeed your housemate, you win. Users/kidkoryo

20100621 18:17:18 nbsp I have lived here for the past three years, and I have liked it very much.  It is in a good location, and my apartment is very nice.  All maintenance requests were taken care of in a timely manner, and I have never had any problems with the apartment managers during my time living here.  Also, when I recently announced my intention to move out, Kari was very kind and patient in explaining everything to me, and very helpful in finding new tenants to sublet the apartment for next year.   Users/jamesturnbaugh

20100622 09:43:36 nbsp Unfortunately, people always take the time to write about their bad experiences with a place but many will not do the same for their wonderful experiences.  I am a graduate student and have been living at Alvarado Sunset Apartments for three years now.  I was not very happy with the previous manager, Cora.  With regards to my apartment, she was good at taking care of the maintenance problems that I reported.  However, when I had an extremely noisy and disrupting neighbor last year (loud music and parties every night), she did not care to do anything and ignored all my complaints.  I was planning to move out of this apartment complex when Kari became the manager.  She helped me out tremendously with my disrupting neighbor.  Since she has become the manager, I have realized that our laundry room is always very clean.  The green area is always well taken care of.  I do believe that she cares for this apartment complex and tries very hard to have good relationships with all the tenants.  Kari has always taken care of the maintenance issues in a timely manner.  I do hope that all the tenants that see her nice work, take the time to write about their good experiences here at Alvarado Sunset Apartments.  This a quiet place for serious students who would like to study and care about the cleanliness, maintenance, and the general look of their apartments.  Kari does everything to keep it nice and wellmaintained.  If you like to party all the time and have tons of people over at your place on most days, have no respect for your neighbors and other people, do not care about the cleanliness and maintenance of your complex and are unruly, then by all means this is not the place for you.  Kari, thank you so much for all your hard work.     Users/Sima

20100710 16:06:15 nbsp I like to be as unbias as possible. I truly enjoyed Cora being our manager, she was nice to talk to, and she tried to take care of business and whatnot, but compared to Kari, yes, she might not be as prompt, or the services werent provided just as quick as Kari had made it. Usually, one would have to talk to Cora a couple times before the work actually gets done. Although Kari gets things done quick, and usually is nice about it. She is not as professional as a manager should be. She is sometimes rude with her comments, but it seems like she is trying to adjust to an environment with college kids, another word, perhaps she is trying to be cool? I am not sure. Regardless, there is much improvement with the apartments, it might just be the professionalism and attitude that she would have to work on. If there is a problem with your apartment, feel free to call in and you should receive some sort of respond.  Users/mee

20100719 00:26:08 nbsp My roommates and I had originally planned on living here, and had spent quite some time in the managers (Karis) office. We were initially drawn to the apartment complexs price (which is pretty damn cheap) for the 3 bedroom, but upon actually taking a tour of one of the apartments, we saw how old, dark and overall shabby the place looked on the inside. The floorplan of the 3 bedroom is a really odd long skinny shape, with a tiny bedroom in the middle of the hallway. The manager was super nice at first, but also very talkative (to the point of being boring) and even borderline racist! When we told her we were no longer planning on going through and signing the lease, her attitude immediately changed and she became quite rude. Overall, a pretty bad experience, but if not for our time looking at Alvarado Sunset, we wouldve never seen the much prettier (AKA better version of Alvarado Sunset) Aggie Square. Great location, and has potential (in theory), but my roommates and I are glad we didnt settle for this place. Users/mwzhang

20100804 15:38:38 nbsp DO NOT MOVE INTO THIS PLACE! I lived here for two years and have had three different managers. The first was fired because she didn’t do a background check on a tenant and they started a meth lab. YES a METH LAB! Check it out in Davis police logs. The police, fire department, and hazmat all busted into an apartment in the building that is parallel to Covell, and the perp took off running. I couple months later the hazmat team was back in their white suits cleaning it out. Maintenance here is super slow and ineffective. My roof leaked in the same spot two years in a row. I guess they were unable to fix it right the first time. Not to mention it took over a month to fix and the patch job on my ceiling looks horrible. When I went to confront the manager about the amount of time she told me that they were working on it and money is tight because there were empty units. SO WHERE DOES THE RENT MONEY I AM PAYING TO PUT A ROOF OVER MY HEAD GO! The second manager Kari was mean, rude, and made me feel like I was always inconveniencing her when I asked for something to be fixed. There is a new manager now and she just seems overwhelmed all the time. The place is run down and horribly managed. The only good thing is the complex is very quiet. There was maybe one loud party the two years I lived here. Users/ktDub
