Topics that this entry still needs to cover include: History of the need to overhaul the water system (weve known about this for years); the agreement that was made in December 2010, and Woodland and UCDs part in that agreement; environmental concerns for the Delta; controversy over the process by which the decision was made; the Prop 218 protest mechanism and the eventual easing of the requirements for protest; discussions of the pros and cons of going forward with this project now.



Background

Woodland and Davis are two of only a very few cities in California that still rely entirely on groundwater for water supplies. In the past, groundwater was good and plentiful enough to meet community needs, and also state and federal water quality regulations. By itself, groundwater isn’t good enough anymore to meet anticipated state water quality and wastewater discharge regulations. The quality of local groundwater supplies is getting worse. Our groundwater has an increasing amount of salts and other minerals that threaten the environment and public health. The Cities cannot meet anticipated future regulations for the water coming into homes, or for water returned to the environment after leaving the wastewater treatment facilities. A number of groundwater wells in Davis and Woodland have been shut down and destroyed because they no longer work and can’t be fixed, or because they compromise drinking water quality. Even with major improvements to groundwater facilities (wells and pumps, for example), Davis and Woodland would still fall short of meeting future water quality regulations for drinking water and treated wastewater. It’s the quality of the water – not the quantity – that’s driving the shift from groundwater to surface water.

The high, naturallyoccurring salt content in the groundwater combined with additional salt from consumer uses (including water softeners) results in a high concentration of salts in the water. “Used” water that leaves our homes – also known as “wastewater” – has even higher concentrations of salt than the water that comes into our homes. For wastewater, the Central Valley Regional Water Quality Control Board (Regional Board) is aggressively pursuing requirements for reductions in salt discharges to protect the environment and other downstream water users. For example, consumers may be required to switch from saltbased water softeners (maintained by homeowners) to ion exchangebased water softeners (maintained by water softener vendors) that will add significant costs (about $42 per month). Discharges of treated wastewater in the Central Valley will have to meet more stringent salinity standards in the future. Switching to surface water should eliminate the need for water softeners.

Independent professional studies commissioned by the Davis City Council repeatedly confirmed the DavisWoodland Water Supply project as the leastcost option for meeting drinking water and wastewater quality regulations, and ensuring that water is always available when needed. A panel of nationallyrecognized drinking water experts was convened in 2008 by the National Water Research Institute and their results were provided in a http://www.wdcwa.com/docs/NWRIFinalPanelReportontheDavisProject20080718.pdf written report. In the report, the independent panel concluded that the most serious consequence of postponing the project is the probability of losing the pending appropriative right to withdraw up to 46,100 acrefeet of water per year from the Sacramento River. The application to secure these rights was submitted to the SWRCB by Yolo County Flood Control and Water Conservation District in 1994 in response to a countywide water supply study. That application has been reassigned to the Project Partners. The SWRCB, however, requires due diligence on the part of the applicant to pursue and implement water rights. Therefore, if the Project Partners are not able to show timely progress, the SWRCB is likely to cancel the application. The net result of this action would be that the Project Partners would have to start the process anew, thereby losing their “place in line.” The money expended thus far in pursuing this application has exceeded $3 million. If the effort to secure these water rights is postponed to a later date, much of the work would have to be redone. The independent panel also concluded that postponement of the project to a later date would likely result in the loss of upstream water currently available for purchase to supplement the amount of water needed during the summer months. Due to pressures such as future population growth and climate change, the ability to purchase needed water at a future date will be far more difficult and expensive. Furthermore, the water may not even be available.

Proposal
The city of Davis is proposing a complete overhaul of the tap water water system. The proposed system will be a conjugative use project that will draw from both ground and surface water sources, the surface water would come from the Sacramento River and the ground water would come from one of our Davis water wells wells.  This would represent the most costly infrastructure project in the towns history. Its a very controversial issue that has Vitriol about the water rate hikes pissed off many citizens primarily because, under the original proposal, some have said that it could triple or even quadruple the current water rates; all this while we are in one of the worst economic climates of recent memory.  It is a joint project with the city of Woodland.

Proposition 218 allowed for protests to be submitted by ratepayers (i.e., residential and commercial property owners), one protest per property.  By the deadline, 4855 had filed Prop 218 protests, with 185 of those not being fully validated.  This represents almost 30% of Daviss 15,812 ratepayers; more than 50% was needed to overturn the proposed rate increase.  http://davisvanguard.org/index.php?optioncom_content&viewarticle&id4673:thisisdemocracycouncilmorethandoubleswaterratesatnearly330inthemorning&Itemid79 According to the Vanguard, at 3:20 AM on September 7, 2011, the City Council passed a series of motions that will amount to almost a doubling of the water rates after five years, a reduction from the previous proposal.  http://www.davisenterprise.com/homepage/featuredstories/councilokswaterratesadvisorycommittee/ According to The Davis Enterprise, the new numbers were achieved by pushing back local capital improvements and using more optimistic cost assumptions, since actual costs are unknown until construction bids are received. However, council member Sue Greenwald has cautioned against having blind faith in the socalled optimistic cost assumptions. In a comment made on the Vanguard, she stated, It doesnt matter what the council says the rates are. Once those bonds are issued, the rates will have to be whatever it takes to pay the interest and principle on the bonds. Therefore, in the long run, we may or may not still see a rate hike in line with the original highend estimates.  For now the plan is that the rates will increase by no more than 14% each year.  The vote was 41, with Sue Greenwald dissenting.  It is still possible that voters could try to put the rate increase to a referendum vote.

As of midNovember, 2011, it appears extremely likely that a referendum will indeed be put to the ballot. The movement to petition the water rate hike was successful in gathering the number of required signatures. Although some members of the city government appear skeptical of the referendums legality, there is now a lot of pressure on the city to allow the water rate issue to be voted on.

On December 6, 2011, the council decided to voluntarily drop the planned rate hike. Futhermore, several of the council members now seem to have come to grips with an upcoming citywide vote on the project. The measure will be placed on the November 2012 Presidential Election November 2012 General Election ballot. In the meantime, the council has formed a Water Advisory Committee. The committee will make recommendations on how to improve the water project plan overall and make it more costeffective.

On March 5th 2013 Davis citizens will have the opportunity to vote on moving the proposed water project forward. March 2013 Election/Measure I if passed would allow the City of Davis to move forward with the WoodlandDavis water project.

Sewer and sanitation rates will also be going up. (source?)

Other Resources and Commentary
Here is a link to more information on the proposed water rates and a rate calculator: http://cityofdavis.org/pw/water/watercalculator.cfm.  For questions, you can call the Water Rate Hotline at 5304053500.

And here is a radio show about the proposed hike on KDRT: http://kdrt.org/node/7206

In JuneJuly 2011, five meetings were held to give citizens an opportunity to ask questions about the proposed rate increase and what it means for Daviss future water supply.

Woodland Davis Clean Water Agency: http://www.wdcwa.com/

The Davis Enterprise recently ran an article where they interview some people who claim that you should think before you sign the petition that allows the citizens have a choice, I for one would love to engage these people in a debate. Daubert

Davis Enterprise October 11, 2011  http://www.davisenterprise.com/localnews/city/severaldavisresidentssaythinkbeforeyousign/ Think Before You Sign

http://davisvanguard.org/index.php?optioncom_content&viewarticle&id4762:counterprotestmessagethedemocraticrighttofearthepeople&catid50:elections&Itemid83 The Peoples Vanguard of Davis  Counter Protest Message: The Democratic Right to Fear the People



