Puneet Dhillon was a candidate for ASUCD ASUCD Senate Senate in the FALL 2010 ASUCD Election running on the LEAD slate


 Candidate Statement 

Hello fellow UCD students! My name is Puneet Dhillon and I am running for  ASUCD Senate on the LEAD (Leadership, Empowerment, Activism, and Determination) slate. I am from a 2nd year pursuing a political science major and I plan to attend law school. I am a fresh face entering into ASUCD and I hope to create positive change and implement needed legislation at the University of California Davis.

On of my main goals as ASUCD Senator is to create a better transitioning process into UC Davis. Entering into A University is a landmark step in many peoples lives. Which is why it is not surprising that many freshman and transfer student have a hard time adjusting to University life both academically and socially. Finding a social circle, understanding the speed of the quarter system, finding proper places to study and trying to find Wellman Hall in the rush of bike traffic is just a small number of items new students have have to face when coming to Davis. I came in as a freshman last year and understand the tough transition, which is why I will work to help make the process easier for incoming students. My goal is to create more student on student advising programs.

Another pressing issue I hope to conquer is the reduction of hate crimes hate crime and the creation of more unity and acceptance on campus. Last year, there was a great deal of vandalism and hate crimes which ensued on Davis. We are a campus which prides ourselves on our diversity and culture. I believe we need to showcase this diversity because it will more educated people on different beliefs and cultures on campus. I believe this education will lead to acceptance and eventually bridge together our community. This is why I would recommend having one uniform multicultural day. Every student would be encouraged to dress up in any type of cultural attire they identify with and their would be a multicultural fair in the quad.

With all the pressures of being a college student, students at UC Davis need time to unwind. As senator, I will work with the Entertainment Council to have more entertaining events on campus. My goal is to bring more mainstream artists, have more variety in our entertainment, and give the students what they want. I will personally work with the students and the entertainment council to bring entertainment which will fully entertain our campus! Of course, entertainment comes with a heavy price. However, this does NOT mean increasing any funds but working with the private sectors and other small businesses to help sponsor more events at UCD. This is something I have experience in and you can count on me for!

