Is a former Davis resident, current West Sacramento resident who still visits Davis for the food and the weirdness.


20100121 15:27:11 nbsp Just as a note, based on Wes edit history, it may take a couple days before he reads that... not everybody follows the wiki as much as some of us do.  :)  Although Im guessing hes checking it about once a day lately.  Users/JabberWokky Evan JabberWokky Edwards

20100126 11:33:34 nbsp Looking at http://daviswiki.org/Davis_Food_Coop/Boycott%2C_Divestment%2C_And_Sanctions?actiondiff&version233&version131 philips edit, I dont see anything objectionable. Dauberts comment was of no real substance there, so it was removed. Normally, its a nono to edit someone elses comment. However, the comment that Doug wrote stands on its own without the reference to Dauberts now removed comment and it wasnt really harmed. Users/WilliamLewis

20100126 11:36:32 nbsp I just think its a slippery slope.  There was a pointless comment, but then there was a good response.  Why edit out the pointless comment AND edit the good response to create a net zero gain, youre still left with one good comment, but its now not the comment the original poster lefts, but its still signed by that poster.  I dont see the point. Users/rfrazier
 The benefit is an increased signal to noise ratio. Pages that are simply walls of text devoid of much meaning arent very useful, and unfortunately we get a lot of those. Pruning helps with that. As for the slippery slope, had Philip done more substantial alterations to Dougs comment, his edit would have been undone. In general, we subscribe to a norm that attributed comments are either deleted or not edited at all. Of course, we also sometimes remove attribution and move a comment into the body of a page where the original quote can be edited by more people. wl
Damnit, my comments are not pointless regardless of content. I said what I meant and I attributed it to myself.   Users/StevenDaubert

20100126 11:38:17 nbsp As a wiki, all text is editable by anyone, including comments. Comments are generally not edited by other editors by convention, but its just a convention. Users/NickSchmalenberger

20100126 11:40:49 nbsp If youre comfortable changing someones statement but keeping it attributed to them, I guess you can edit however you want.  Personally I dont agree, but Im not going to engage in CovertProfessors habit of unilaterally undoing the edit because I dont agree with it. Users/rfrazier
 CovertProfessors edit was hardly unilateral. Nobody who didnt have a horse in this stupid race wanted the discussion to go back to talk of this conflict being like a game, with winners, losers, and punishments for people who have been naughty. Ill name four people right now who I know supported his edit: CovertProfessor, me, Brent, and Philip. There were likely others. wl
  Not sure if I disagree with you here because Im not sure what youre talking about.  Ive had a number of edits reverted by Covert with no explanation or with a dont edit this explanation.  Its not just one thing.  Hell, his first post to me was basically you arent entitled to an opinion because I post here more than you do.  Its a funny thing about this wiki  some of the regular editors are quick to say stop complaining about the wiki, youre an editor, just fix it if you dont like it while editors like covert rigorously police any edits they dont like and just essentially by virtue of shouting down the opposition by being more willing to keep reediting get their voice heard. users/rfrazier
    Yes.  There are many individuals here, and many dont agree, and thus do things differently.  I know I often dont agree with William or Nick, and they and I have no real problem with editing cooperatively.  Im not sure what your point is: that different people have different editing styles and viewpoints?  I would hope so!  Users/JabberWokky Evan JabberWokky Edwards

20100126 12:25:58 nbsp Im not sure that asexuality is a sexual practice analogous to bdsm and such. Im not really up on all this sex geekery, but isnt asexuality more of a sexual orientation, akin to heterosexuality, homosexuality, and bisexuality? Users/WilliamLewis
 Then again, polyamory arguably doesnt belong there. But w/e wl

20100126 12:59:47 nbsp Ah!  I JUST FIGURED OUT YOUR MISSING PIECE OF INFORMATION!!!.  The wiki is a community.  Thats a special thing, and you are welcome to be part of it.  Take pride in it, and feel free to grumble when your neighbors all decide to pave a sidewalk down your road... that might not be what you wanted, but you are part of the community.  One neighbor might decide to paint his house black and purple.  Grumble all you want about that neighbor (or maybe you are that neighbor).    If enough people gripe, maybe hell paint it back.  Maybe a good friend lives down the street and you head over there to have iced tea and watch his daughter play in the back yard as you chat about the new burger place downtown.  Thats cool too.  But the end of it all is (mostly) civil behavior, everybody figuring out how to get along with all their neighbors.  And no hope of all the neighbors ever agreeing on anything completely.  It takes awhile to figure out the traditions when you move in, and everybody has different advice.  So yeah... youre getting different advice, different views, different takes.  This is a community.  You are welcome here, but expect that some people will grumble at you if you set your BBQ grill in the sidewalk when you cook out in your front yard, and expect lots of appreciation if you help set up that basketball hoop in the culdesac or clean up some vandalism in the corner park.  Youll probably even make some friends  who will have views you dont agree with.  And above all, youll get lots and lots of contradicting advice and actions from all your neighbors.  But its a community of people all working together, so thats just part of how it works.  There are plenty of traditions and some people are more visibly active than others, but everybody can pipe up if they want.  Welcome to the wiki, an odd little neighborhood (like they all are) of Davis. Users/JabberWokky
  well the big question is  if I just revert back any changes that get made to my edits by an editor who annoys me, will I be accused of starting an edit war or somesuch, just because the other editor has a longer post history than I do?  RF
     Maybe.  Maybe not.  It certainly cant be predicted based on only what you just told me.  I will add that editing on the basis of being personally annoyed by another editor rather than on the merit of the changes seems quite petty. jw
      What Im talking about is responsive editing, ie, I post something or make a change, its reverted with no or minimal explanation, I then revert it back given that I really dont see the basis for the first revision.  RF
        Ah.  Well, how about you ask if it isnt clear?  I usually do when it happens to me, and I usually get an answer as a result. jw

20100126 13:44:52 nbsp Now if you hate second level headings without first level headings as much as I do..... ) Users/WilliamLewis
  Hey!  We agree on that!  Lets friend each other! jw

20100126 14:15:50 nbsp I wrote a really long comment but I xd my browser out.  Regarding the link, its really not about the conflict.  Crosslinking between businesses is common and is a wiki thing.  There used to be a huge wiki war between Urban Body and Primary Concepts Tattooing & Body Piercing which was started by a former employee or something, where one business owner kept adding fake reviews and all kinds of trouble.  Similarly, its very common for salons and hairstylists.  Check out the text above and below on Roxie at Davids Haircutting.   Or on an active business, youd see something like http://daviswiki.org/The_Style_Lounge?actionrecall&version167 looking for commentary.  Now, clearly Wes isnt exactly the same as a stylist in terms of service.  But the wikis also documented restaurant managers, bartenders, etc.  Theres two reasons to keep the link between the two: 1  as JW mentioned, perhaps he is someones comic book guy.  I imagine that might not mean anything to someone who buys comics at 711, but if you went in to talk to him about games and comics or whatever, it might mean something indeed.  This is evident in point 2  hes independently mentioned in both wiki pages.  At least one comment mentions him by name on the BW page, a comment thats not suspect, and someone on the Droms page asks if its the same Wes.  To people in the game leagues or whatever they are, it might make a difference.  But I think both of these are valid reasons (general wiki action, and informational context that correlates with specific comments).  The real point here is: that links not there because of this specific conflict.  Its not unique to this situation.  Its something thats done regularly.  And as a side point, on one talk page Wes said he only keeps removing it because its not on the BW page, and if it is, hell stop.  Its only fair if both sides have it, which is why some people are insistent on readding it.    This comments just meant as a contextual reply to what you said on the talk page about it.   Users/EdWins
  I see what youre saying and Im not planning any edits myself, but I really sympathize with Dan on this (obviously).   To me what it looks like is that Wes either sockpuppeted or Meatpuppet meatpuppeted a whole bunch of people into writing HEY WHERES WES WES WAS SO COOL DAN SUCKS on the BW web page right around the time Droms opened.  Wes continued to essentially cyberstalk Dan, posting other stuff like HEY HOW COME YOU ARE TRYING TO CIRCUMVENT YOUR DCI BAN DAN!?!?! on the BW web page, which really is none of his ing business.  I understand that fake comments are just something you have to deal with with a medium like this but I think the whole thing is just an open wound for Dan and I was really hoping that considering that there was proof some comments were fake, thatd be sufficient to get the suspect ones removed (which it wasnt according to consensus) at a minimum remove what appears to him to be advertising for his competator, considering that given the history, in his opinion which I share, there really should be a big question mark over a lot of those proWes comments.  RF
     Yeah, I get that completely.  The whole situation sucks a bit, and my first comment to Wes when he clarified at length what he meant on the talk page was that he should have written it that way in the first place and wed have avoided a lot of the problem.  I guess what Im trying to demonstrate is just that this has happened several times over the years, and its hard to judge what is and what isnt suspect.  Like I had said in one edit, anythonyk may very well be a friend of Wes or something, but that doesnt make his entire comment illegitimate.  We cant start cutting out whole chunks just due to a possible association.  If we knew it was from the same person/location though, we could consider them fake and cull them out.  Thats the problem: it very well might just be a customer that decided he really likes Droms better.  Wes very well might have absolutely nothing to do with it.  However, that usagigjn or whatever his name was: different IP edit from around the country, didnt mention Droms at all, and actually complained about the EBAY/Shipping purchase.  I still have not seen a single reason how thats remotely suspect due to Wes/Kyle tomfoolery.   edit: And im not saying that youre saying it is, I understand youre feelingfor Dan.  I think thats why people are so fiercely protective of the wiki: a lot of these people, specifically JasonAller and JabberWokky, spend a lot of time trying to help prevent these sorts of problems, encouraging people to become regular editors/contribute to the wiki beyond the topic of their choice, etc.  It sucks when someone gets a bit screwed over, so we try to do the best to prevent it, and once it happens, remove anything offending and move on.    users/edwins ES

20100126 14:49:59 nbsp I believe that would make them simply nudists at that point.  :) Users/JabberWokky

20100126 16:10:40 nbsp Hey, you said I really hope that nobody reading the comments section here, and I thought you should be aware that Talk pages are traditionally deleted after the edit discussion is over (some linger out there, usually because the discussion trailed off).  For instance, I just proposed a page split on Geography Graduate Group/Talk.  People seem to be in favor of it, and when its done, the Talk page will be deleted.  The same will likely occur soon for the Bizarro World/Talk page, as the discussion there only has to do with the wiki, and not with Davis itself. Users/JabberWokky
 Thatll be fine w/ me, I will probably make a more extensive comment in the main page praising Dans new location and giving additional detail regarding my earlier positive review (considering I took down my old long positive review as it has lost context due to some earlier edits) as soon as the opportunity presents itself, and based on the any publicity is good publicity theory intend to refrain from mentioning Droms or Wes in any way in said comment.  RF
   Dont make a comment  go ahead and write about the new location in the main body of the entry!  Explain whats cool, the neat features of the store and what they stock, etc.  Thats a heck of a lot more useful for people reading the entry.  Crow to the rafters and the cool and neat things that are in the store.  Do the same for Droms... and for any Bathrooms political organization you like, any spiritual organizations church you attend, any cows restaurant you like, any Parks park you enjoy, any town flora flower youre especially fond of seeing around town, a Sidewalk Crack Project crack in a sidewalk you lament, etc.  Go for it!  The current record setting inability to get along on one topic shouldnt make you timid, and if you poked around and explored the wiki, realized how fluid and dynamic and free flowing it is, you might feel kind of silly about the level of consternation the recent fluff up raised.  Oh, and make sure to take and add a photo of the bathroom to the bathrooms entry. jw
    It could be that I am carrying over some of my baggage from edit wars on reg. wikipedia here.  I tend to be very cautious about making changes to the main text other than clarifications or formatting.  Ill try to be more relaxed about it in the future.  RF
       Wikipedia is an atypical wiki.  In fact, it might not be considered a wiki at all, so theres little crossover between there and here.  Theres not much wiki:wiki:WikiNow to it, and it has rules.  You might want to read Welcome to the Wiki/Wiki Enthusiast.   jw
        Good suggestions, thanks.   RF

20100128 19:44:11 nbsp This is the last time I am going to say this Ryan. I have never used a sockpuppet for any dang thing and I am getting very tired of both you and Dan accusing me of such. Zip it. If I wanted to truly trash Dans shop I have much better ways to do it with the knowledge I have than to post bs under assumed names here on the wiki. Grow up and stop accusing people of crap you cant prove. I made the edits you asked because it was rude to leave it on the droms page with the asterisk. I have made concessions. Time to see some balance out there. I know you are Dans close friend. Thats fine. but you and I both know that A) your comments were based entirely on that relationship and not the stores since you had no problems with any of the selections I made for you while working for Bizarro World but after coming to droms to help my friends, you suddenly think I am the worst comic guy in the industry. Fine. I dont want to get into a flame war. You have your reasons for doing this stuff, I suggest you do exactly hat has been suggested by many and take the Wiki Chill pill and finally grow up a bit and stop this baseless accusation crap. You have done nothing to positively influence anyone or anything on the wiki and have been nothing but insulting to all concerned accusing me, accusing covertprofessor of editing at a whim and anyone else who doesnt agree with you or Dan. Im tired of it, The editorial staff is tired of it and Im fairly sure even you must be tiring of this at this point in time so drop it.  Users/WesOne
  Look at the edit history, Wes.  Im not the one who figured out you and Kyle are the same poster, I just agree with the editor who said it.  Same IP, same story about the G Street pub, plus hes your biggest fan, yet its a complete mystery to you who he is.  Yeah, right.  Hes either you or someone you know very well, and my money is that its you.
 I was polite to you while you worked for Dan because Im a polite person.  Jen and I both were always disappointed when we came to BW and you were working, not Dan.  You live in a fantasy world in which you are a great employee and expert on comics and Dan is a monster and any customer who likes him over you must be evil/insane/Dans best friend.  Thats nothing like the truth.  I always went to BW for Dans recommendations, not yours.  Get that through your big fuzzy head and stop crying about me being biased toward Dan.  Im biased toward giving my business to someone who is good at his job and against someone who sucks at his job.  Thats the beginning and end of it.  RF

20100128 20:10:16 nbsp At first glance, it does look like Kyle2008 and WesOne were using the same computer. Now that I look more carefully, Im not so sure.

Kyles edit history:

Wes edit history around the same time:
 Users/WilliamLewis
  I had been depending on your analysis  Ill have to read this more closely and post my opinion later, in the middle of an Agricola game right now.
   Wes has stated people have used the droms comp on occasion, he has also stated that he is not kyle.  Users/StevenDaubert
   My analysis? I never did one. P But anyway the gist of my doubt is this: WesOne edited with a different IP address before and edited with a different IP address after kyle2008 did. It wasnt until 14 days after Kyle2008 posted that Wes edited from the same IP as Kyle did at one point in time. Kyle2008 only edited from Comcast IPs, while Wes appears to be an AT&T/SBC DSL customer, at least until September 2009. Users/WilliamLewis
   Hm, that wasnt you?  Well, anyhow, while a 14 day gap is a little less suspicious than log out/log in as the other ID, the primary issue was the actual posts  Kyle posted a story and Wes claimed that Kyle had somehow stolen it from him, and that the actual events in the story happened to Wes.  Thats just weird if they arent the same person.  RF
    Thats weird if they are the same person, too! Users/TomGarberson
     Yeah, thats a point.  RF

20100131 18:27:17 nbsp mhmmm, Por qué? Users/OliviaY

20100203 19:20:39 nbsp I think so, too, re: your bb comment on the ch page.  Thats why I alluded to the history of the page, but I didnt really want to bring that up because I dont want to air their dirty laundry.  It looks to me like people were trying to delete T even before he left.  That makes me not inclined to go along with it now.  Peoples internal squabbles should not be a wiki affair, imo. Users/CovertProfessor
  thats kind of the same issue with the whole Wes/BW thing, esp when it relates to the sanctioning info.  Basically theres a lot of info on the BW page now that wouldnt be there if it werent for Wes edits  particularly the info about sanctioning.  Now yes, the info is apparently true (AFAIK, I really have no personal knowlege on the topic), but its frustrating for Dan because it was information which has a commercial effect on his business (or could) and was really clearly posted there by a business rival for a commercial purpose.  The idea that removing it shouldnt be done because the wiki doesnt bow to commercial concerns really bothers him as the reason the info is there was 100% commerical to begin with.  I guess its like a fruit of the poisons tree arguement in crim law  regardless of the truth or falsity of the information, should something be removed based on the bad behavior of the person who originally posted it?  Apparently wiki consensus is no.  RF
   Well, I dont want to discuss the BW/Droms thing again; Im pretty talked out on that topic.  Are you saying that the posts were made by T and thats why KC wants them removed?  Or is it that she didnt like T and wanted them removed for that reason?  I have no way of judging between those two scenarios.  Do you?  In any case, were talking about deleting the pic here, not the comments, and clearly T didnt create the picture, since he is in it. Users/CovertProfessor
     Oh, no no.  Its more that there was personal acrimony that lead to changes in the page.  The fundamental difference seems to be that Wes added info to the BW page and KC is removing info from the haircut page.  The Wiki rules/community strongly favor adding info not taking it away, while I have been more focused on the original purpose of the addition, which was commercial.  RF
      Pardon me butting in here, but you completely hit the nail on the head here: The Wiki rules/community strongly favor adding info not taking it away, while I have been more focused on the original purpose of the addition, which was commercial. The Wiki is here to provide a community and information about our community, and so long as the information is true and of value to some people in the community, it is welcome here.  And trying to remove it generally isnt. Users/TomGarberson

20100206 14:38:47 nbsp it had another name before it was sold and renamed posh Users/StevenDaubert

20100305 09:58:15 nbsp Looks like a pretty good edit to RC... be prepared for a shitstorm, though! Users/TomGarberson

20100305 10:03:16 nbsp I think I might have just ROFLCOPTERed! Users/TomGarberson

20100305 10:33:39 nbsp http://daviswiki.org/Real_Computers_%26_Free_Diagnostics/Talk?actiondiff&version2358&version1357 Exactly.  And yet for criticizing him, I get called antibusiness or people say that I have a personal beef with him.  Users/CovertProfessor

20100308 09:59:37 nbsp LOL yeah... he is impressively consistent, isnt he? Users/TomGarberson

20100308 10:15:08 nbsp Stick around for a few years and youll quickly see theres always an issue of the month and issue of the year on the wiki.  Brian is definitely shaping up to be the latter.  Anyway, theres always been constant rotation of random conflict, controversy or what have you, especially on election years.  Unfortunately, usually the focus subjects of it are either pretty new to the wiki or drawn to the wiki because of hearing about it.  Inevitably, almost every person takes it quite personal which is totally understandable, or assumes its all scheming by competitors, which tends to be frustrating for everybody. Users/EdWins
