
The many streets in town and the county roads outside the city limits yield a large variety of examples of Roadkill that represent the examples Town Wildlife local fauna. Mostly generated by interactions with motor vehicles, but sometimes with bicycles, they keep the local Turkey Vulture vultures busy and well fed.
