Well, Im a 3rd year student here at UCD.  I was born and raised in Salem, Ohio until the age of 13.  At 13, my mother and I moved to Thousand Oaks, CA.  I attended Westlake High School in the CVUSD.  I am attempting to get a B.A. in Psychology with a minor in Sexuality Studies.  I am a peer counselor at The House.  Also I am a GASC alternate.  I am the future trophy husband of the enchanting Jake Gyllenhaal. 

Stay tuned for more Robert info....  
