

Royal Oak is a mobile home parks mobile home park just outside City Limits Davis city limits. Space rental is said to be reasonable by Davis standards and facilities considered by at least one tenant to be clean and well maintained. Other Northern California municipalities have unincorporated sections of town like this that have not been included by annexation. In some cases there have been lawsuits brought claiming discrimination based on socieconomic status or racial makeup.

Users/Myabrn lived there 20 years ago when, she says, it was nice and family friendly. Now it is not so. She goes on to say her familys trailer, was turned into a Drugs drug lab that burned to the ground when the new owners attempted to incorporate the clothes dryer into their drug concocting process.

In July 2003, Slatters Court David Lawrence Beale was arrested when 157 pounds of human body parts were discovered behind his Royal Oak home on Erma Lane.



20060604 17:22:07 nbsp Im looking at living thereis it really this bad?  Any more detailed comments on Royal Oaks would be much appreciated... Users/BobReinhardt

20060825 08:30:37 nbsp Bob, if you really want to know go there on a Saturday afternoon and drive around. You will see a burnt out trailer that has never been replaced by the pool area (atleast it was still there as of end of July). The people are friendly but there doesnt seem to be alot of pride of ownership as a whole. The pool has been redone though. Users/MyaBrn

20061022 14:50:33 nbsp Does anybody know what the space rental is here? Even roughly?  Users/AmyGoogenspa


20071217 19:58:43 nbsp The space rent is still $750 as far as I know. The burned out husk by the pool is now gone, I dont recall exactly when it went, somewhere between 2 and 6 months ago probably? The neighbors are really friendly, and other than kids playing its pretty quiet. Ive been really happy here the past year, but recently (since they repaved the streets and numbered the parking spots a couple months ago) theyve become really bad about towing cars like mad. The worst part is they are doing so illegally.

For my neighbors: Their signs do not meet the California Vehicle Code Division 11, Chapter 10, Article 1 >> Section 22658 requirements, therefore they must give 96 hours written notice. See: http://www.dmv.ca.gov/pubs/vctop/d11/vc22658.htm

If they do not give 96 hours written notice the management/park owners must pay twice what the vehicle owner was charged to get their car back. Also, if you catch the tow truck before it reaches Research Park Drive, if you ask, the tow operator has to release your vehicle for half the normal fee (which should end up being between $90110). If your car is damaged by while being towed, the tow truck company has to pay for repairs. If enough people start taking the management to small claims court, maybe theyll start following the laws.

I dont know if its the management thats the problem or the owners or a combination of both. But theyre really driving people away with their policies. There are many places abandoned, empty spots and places for sale, even though the rent is reasonable (and they have some deal with getting a home for $1000 a month which I think includes the $750 rent) and the location is awesome (near the freeway, shopping, downtown, the Putah Creek Bike Path and from there the Arboretum and campus). So basically it can be a great place to live if you are very careful about where you park, and you warn your visitors not to park inside unless they can get a visitor labeled parking spot (and arent going to be there more than one day). But then I rank good neighbors and peace and quiet really highly after living in South Sacramento for five years. Users/JenniferKucich

20080405 15:27:58 nbsp While they keep the common areas clean and well maintained and the park is reasonably quiet and the rent is reasonable for Davis, at this point I would not recommend living here to anybody (and I do know Im screwing myself by saying that since we will want to sell eventually).  I dont blame the individual park managers (I think theyre on the fourth one in the 18 months Ive lived here, which should tell you something).  Its the company that owns it and the regional managers that will get to you.  They take forever to act on anything  if you need a place to live fast, this isnt gonna be it; we had to wait an extra two days after being approved for somebody at the main office to return from vacation and sign a piece of paper before we could move in.

And like Jennifer said, they do illegal things and they get away with it because most residents dont seem to know or have time to stand up for their rights.  Users/LisaBriggs

20081219 22:29:13 nbsp A recent article in Eureka points to a very unruly couple who have taken up management at this park and Davis Mobile Estates  read here: http://www.northcoastjournal.com/081904/news0819.html under Park managers controversial past.  I am surprised none of this was posted here. Users/CarrieBishop

20090719 13:19:59 nbsp Ive lived here about 2 years.  If you regularly ride your bicycle to the university, then this location is superb.  It is quiet and safe  apparently thats a great improvement from years ago.  Theyve really cleaned the place up in the last few years.

The newly hired manager (named Rhonda) is great; Im not sure how long shell last however since the regional manager she reports to is really meanspirited (this is the third manager since Ive been here).
I currently pay $780 in rent, which I think is a bit high.  Also, the management company seems to play fast and loose with the law.  In practice this might not affect you if you live here.
I think high rents is a major reason the park has around 50% vacancy.  Unlike an apartment, you have to pay trash, sewer, and water.

In total, it might compare favorably to an apartment, assuming you get a good deal on the purchase of the home.  Of course, you would never want to buy a brand new one. Users/livegreen

20110228 19:56:43 nbsp Does anyone know what the pet policies are for this place? Users/tcobra8

20110826 09:08:42 nbsp Just talked to management on the phone.  They said the pet policy is: up to 2 pets, dogs up to 18 tall OK but on leash at all times (no vicious breeds.)  Cats must be inside only. Users/Eve


20120206 13:23:11 nbsp I have lived at the Royal Oak since Jan of 2005.  I have watched the Managers and Regional Managers shuffle many times..   All in all  the place is a thousand times better since The Heapes left as Regional Managers..(they stalked, harassed and lied to residents); but I think the current Manager is getting too relaxed and trying to brush a lot of responsibilities onto the Police and residents.. We pay rent in this community to have the Manager enforce the rules and regulations...if the Management is afraid to confront an unruly resident or confront them about illegal acts done by their children;  how then can that unruly resident be removed from further causing complaints from other residents if no tab is kept against them?  If Ive learned one thing in this park its this:  Have the Mobile Home Ombudsmans phone number handy, if you have to talk to the Management do it with a certified letter only,  and if you want something done right  do it yourself.. To those considering living here:  Make sure you know if your rent is going up 5% or 3% a year, ask if the home you are considering purchasing is up to park standards/regulations if not ask them to bring it up prior to sale, pay cash, get a lot space where you have a little room between you and neighbors, the parking in front of your home assigned to you, check Megans Law offender registry to see who potential bad neighbors are, check to see if your neighbors maintain their yards (as the park is VERY relaxed about letting people let their yards go all to heck).  FYI:  I never had a flea, tick or cockroach problem until I had new filthy neighbors move in all around me... Trash piled in backyards, new neighbors cats and dogs let to pee in my yard who run lose... (just had a pit bull walk up to me at the Park mail boxes  I thought they didnt allow aggressive breeds???)..  Ive had enough of the Royal Oak life... One cool thing though: I have 3 awesome neighbors who have been here as long as me.  I hope theyre able to get out soon too..  The rest of my neighbors act like criminals and Ive even watched 6 homes get raided by police SWAT teams last year (all for METH  even in the family houses).  That was so frightening.  I was on the ground thinking a bullet would come through my house when I heard 15 men in black masks and guns next door shouting and slamming the door in... Also its not good when you have to worry about your neighbors stealing from you constantly... you cannot leave ANYTHING of value outside. Not even a spray nozzle for your hose... OK so now you all have heard from a long time Royal Oak resident.  Wont you be, wont you be, please wont you be my neighbor?  hehe Users/skilwhit

20120811 09:06:50 nbsp An update on the park:  Theres a new manager, Trudi.  So far, she seems really good.  Rhonda, the previous manager was good, but she seemed to be burned out on the job.  Some of the residents that caused the drama with respect to the Drug Enforcement Agency teams coming in are gone.  I have no concern about safety in the park.  It seems more neighborly than a few years ago.

The lease contracts here protect the park but potentially screw the residents in the long run, especially when it comes time to resell your home.  I would ask the sales manager about recent sales of privately owned homes (not those sold by the park) to see if the situation has improved.  You could ask the sales manager what the park would do to help ensure resale value of your home. Users/livegreen

20121005 16:03:01 nbsp New 2012 Manager is pretty cool so far. The Park has lost most of the riffraff that were requiring so many police visits (thank God).  Regardless, there is still no way any homeowner can sell their home very easily.  The previous manager, Rhonda, was pricematching what people were willing to pay for the ownerowned properties, and falsely denying residency applications to anyone seeking to buy an ownerowned home. She would always approve residency for anyone so long as it was a park owned property they purchased. Very biased. So most people here will eventually lose their homes to the park no matter how much work and money they put into fixing them.  I have put $10,000 into my home and tried to sell my place 2 times by owner and with a realtor. Rhonda lowered the price on her park models to match anything my buyers offered me. Also homeowners cannot compete with the Parks $499 handyman special rent rate because when you buy an ownerowned property, you pay where the previous owner left off paying. Thats not fair because it wasnt that way when I purchased my home in 2005. I was started $200 higher than the lady I bought from  and they said it was determined by fair market value. Now my rent is so high it is embarrassing to tell it to potential buyers.  No one wants to live in a place where one person starts at $499 and the guy next door starts at $850.  So if Royal Oak / Sierra Corporate Management would bring in new homes (and take out all of the Pre1974 aluminum wire homes), and start the new ones at $650+ with 6% yearly increase;  It may start leveling out the fairness of the rent in the community and enabling homeowners to start being able to sell their own homes. Royal Oak claims the rent inequality is fair because its only major dumpy homes that go for the $499 rent.  But those majorly dumpy homes are eyesores next to my majorly NonDumpy home. My homes condition is also judged by what is surrounding it...how does the owner of Royal Oak not know that? Buyers are not blind. But to be fair I will give Royal Oak one pro: It is close to very many amenities.  Users/skilwhit

20121006 07:31:14 nbsp I concur that the park has gotten rid of the riff raff who, while not threatening to other residence, did bring some unwelcomed drama to the park.  Also, as a community, people seem to be getting along well.

However, it is true that the business practices of the park are still grotesquely unfair (and possibly illegal) to residents whove been around a while and especially for those who need to sell their homes.  It seems that the business model is based upon driving people out by escalating individual rents to a absurdly high level and making it impossible for private owners to resell their units.  So then the park acquires the mobile homes by default for the cost of a few legal fees.  Then they are able to turn around and resell the units for cheap, undercutting private home owners, reinforcing the crooked cycle.

There are scenarios where it might work out well for you to live here.  But I would ask the sales people for information about recently resold private homes (not sold by the park) and about the rents of longtime residents. Users/livegreen

20130207 13:19:10 nbsp DO NOT DO BUSINESS WITH SIERRA CORPORATE MANAGEMENT, the company that owns this park. DONT RENT FROM THEM, DONT WORK FOR THEM, IF YOU SEE THEIR NAME RUN SCREAMING IN THE OTHER DIRECTION. They will lie to you and then screw you because you believed the lies. If you must rent anything from them, GET EVERYTHING IN WRITING, SIGNED AND DATED  and I do mean EVERYTHING. If its not signed, dated and in writing, IT IS A LIE and if you believe it YOU WILL GET SCREWED.

And there will be no Vaseline.  Users/LisaBriggs

20130422 15:54:37 nbsp I agree with Lisa that you must get EVERYTHING in writing with Sierra Corporate Management.  What any manager in the company tells you verbally is worthless.  Most residents have some personal experience of getting screwed by the company.  However, it still appears possible for people to have a generally positive experience living here.

The park location is so prime that if the park was managed well, there could be a waiting list to get in.  However, this company doesnt seem to care about being fair, and they dont seem to put any value on good will and reputation. Users/livegreen

20140308 22:13:02 nbsp I am looking to buy in this park is it as bad as it says it is? Has management changed? Is it hard to get in this park Users/Mikahdeo
