
Dr. Tran is a friendly and talented dentist who works together with Dr. Mark Wong at a small but wellequipped practice by the name of Varsity Dental.  He has decent prices, and the price for a yearly checkup/cleaning more than enough to cover the yearly allotment for Graduate Students via Delta Dental. He also has a computerized Xray machine which gives off less radiation, gives instant results, and makes for easier record keeping. They also have an on site CAD system for making crowns in office while you wait.

They no longer accept Delta PPO along with many other Dentists in Davis after Delta changed the http://www.drbicuspid.com/index.aspx?secsup&subpmt&pagdis&ItemID310683| amount it covers in 2012. They do still accept Delta insurance there is just a higher copay on many procedures.

Dr. Mark Wong no longer sees patients at Varsity, he was commuting part time but found a full time practice closer to home (Bay Area?).

Melissa Pina is a dental hygenist on staff who does many of the biannual cleanings.

To explore other dentists in the Davis area, please visit our Dentists page.



20070423 08:40:52 nbsp Dr. Tran is super nice and a good dentist.  He goes out of his way to explain what hes doing and a bit of the technical details about dentistry, which I really appreciate. Users/Sonya

20070817 18:40:17 nbsp Myself being on Metlife dental, Dr. Tran and Dr. Nik were the only two people that people least hated. Among the two, I tried out Dr. Tran.  I was pleasantly surprised that he was a very good listener and the facilities were among the best that Ive been to.  He tried to really work with the plan I had and told me the options I had.  +New or at least modern facilities and equipment like digital xrays. +Metlife +Takes UC Davis grad dental +Good listener +Works 5 days a week Not much parking Users/atwong

20071115 09:27:14 nbsp Very mild mannered man.  He introduced himself as Sang.  Friendly staff.   The office is very comfortable.  I just went in for a check up and a cleaning. It was done professionally and efficiently.  I cant complain.   Users/Stamps

20080108 18:56:52 nbsp Dr. Tran is awesome! He is friendly, helpful, and most importantly he does not try to screw you out of your money! He takes pictures of your teeth and shows you whats wrong, and then discusses the options with you. And Dr. Tran was very clear about letting me know what my insurance did and did not cover. He also was honest and told me I didnt need dental work that another dentist told me I should have done. I highly recommend! Users/Dani

20080407 09:33:06 nbsp Dr. Tran,Dr. Wong and their staff are very friendly and while I was having work done made sure that I was in the least amount of discomfort as possible.  I was in quite a bit of pain and when Dr. Tran said he didnt have time to work on me teeth right then, he rescheduled me during his lunch to make sure the work got done.  Talk about going the extra mile!  Dr. Tran was careful to go over what my insurance would cover and what I would have to pay.  What I was quoted was what I ended up paying at the end. Users/Wldrangel

20080506 09:22:08 nbsp Dr. Tran is wonderful. I have been going to him for the last three years and he has been a great dentist. Appointments are easy to get, the staff is friendly, and Dr. Tran couldnt be a more pleasant man. Plus, he is obviously interested and excited about dentistry, which gives me confidence that he is keeping up to date with all of the latest technologies. I highly recommend him. Users/MelanieJulian

20080514 02:59:12 nbsp I had a filling there with Dr. Wong on May 2nd, 2008. While the experience was very pleasant, two weeks after having the filling, I still have pretty bad pains in my entire back side of right jaw. I cant open my mouth fully and I even feel like I tore a nerve when I yawned. Is this normal? I called the office and the receptionist told me to put hot compress on it, I didnt get to speak with the doctor at all. Im kind of irked.  Users/JessicaYang

20080523 15:11:13 nbsp Id recommend this office to anyone!  I was seen by Dr. Mark Wong, who works with Dr. Tran, and thought he was a very capable and honest dentist.  Everyone that works in there is friendly and I had a very pleasant experience, which is saying a lot because I dont like going to the dentist.  I plan on going back there for sure. Users/MicheleTobias

20080811 22:36:55 nbsp WARNING! Ive had regular dental checkups for the past eight years and Davis and was forced to change dentist. I researched Dr. Sang  using Wiki among others and thought he was safe. At the conclusion of the checkup, I came away with four cavities requiring dental work close to $3K  when he didnt even refer to the xrays!!! I asked him how he was able to identify these alone and he did two things to reassure me: (1) he showed me photos upon photos of worst case pics of decay (read: scare tactics), and (2) he said, its from my years of experience that Im able to tell. Worse yet, the tooth I did have issues about came away unscathed. Sounds fishy? ABSOLUTELY!!

Ive since had two other diagnosis from two separate dentists who both thought Sangs treatment plan was unnecessary. Ill say it again: I went to two separate dentists because of the overflowing confidence Sang instilled in me. Needless to say, Ive avoided retainining his services.

In summary: be careful with Sang. If he can explain clearly, confidently, and professionally why you need work, and if he simply flasahes worstcase pics from presumably his time in dental school, consider seeking a second opinion or to seek a new dentist. Otherwise you risk unnecessary dental work.  Users/kenika1226

20080820 16:44:14 nbsp Id definitely recommend Dr. Tran.  I took my 8yearold son to him for a checkup, and they had trouble getting the xrays because my son was nervous.  Dr. Tran did a visual exam, and recommended a pediatric dentist in Davis that he thought might have better luck getting the xrays.  He said that since he wasnt able to get xrays, he didnt feel comfortable making any judgement calls on the kind of care my son would need.  He didnt charge me for the exam.  The office was clean & modern, and the staff was great.  When I make an appointment for my own dental care, Im calling Dr. Trans office first (and hopefully hell still be taking new patients!) Users/AMcAdow

20080905 09:24:58 nbsp Dr. Tran is great. Ive used him for over 2 years now. Hes thoughtful and explains things really clearly.  Users/ces139

20081102 14:13:16 nbsp His a man of Action.  Here comes... DR. TRAN!  http://www.youtube.com/watch?vFO0kRE5OTZI Users/Chibi

20081113 21:10:56 nbsp UNPROFESSIONAL!!!!! Receptionist lady in front was very rude and the dentist recommended more work than I needed! GET A SECOND OPINION! I wouldnt recommend this office unless you have no other options!! Users/mkwa

20090317 09:42:46 nbsp Absolutely UNPROFESSIONAL!!!!! AVOID THEM. DISPARATE FOR YOUR MONEY. THEY ASK FOR THE ENTIRE MONEY UPFRONT.  They recommended me to put a crown on one of my teeth and an inlay on another. They numbed me, started to work on my tooth knowing that their tooth making machine does not work. Then pretending that they did not know that their machine is broken and said we have to start plant B which is gluing a ridiculous thing on top of your tooth as temporary solution. Not having any other alternative at that time I said Ok. Then they sent me home with my tooth already destroyed and in pain a few hours later when numbing was faded away. It has been one week since then and they claime that their machine is not fixed. They have to numb me again to make the crown if their machine get fixed. But listen to this part which is so shameful of them and how bold and dare they are to ask you this. They asked me to visit them again to work on my other tooth and put a temporary thing on the other one!!!. Meaning that your mouth is 100% paralyzed until their machine get fixed. Are they insane? out of their mind or disparate for money? It is against all common sense. I do not know who gave them the dentistry certificate? An unknown university in China?
Also one week earlier I visited them to clean my teeth. They missed almost half of the teeth on my lower jaw. I went home and looked at the mirror and saw that they have not done anything on that part. I had to visit them again. So the bottom line is that they are unprofessional and do not know what they are doing. Do not fall in trap. Users/MrakGuiltinan

20090612 02:14:21 nbsp This is a followup on my last visit, posted on 2008/5/14.
I had mentioned before that the receptionist told me to hotcompress my painful jaw after I had contacted the office, without letting me speak to the doctor. I called back about a week after that to complain about my jaw pain because the hot compress clearly did not work. This time I finally got a response from an assistant and not the receptionist telling me what to do. The doctor looked at it and apologized for their unprofessional service. The bitchy receptionist also halfheartedly apologized, saying that this has never happened before in my many years of experience. Yeah, blah blah blah.
Also, now that I thought of it, the dentist filled a tooth that never felt any pain whatsoever before. Thats a little suspicious.

Yes, they are nice, but I will not be returning to their services. Ever.  Users/JessicaYang

20090923 23:09:35 nbsp Ive been seeing Dr Wong for the past 2 years and he is by far the best dentist Ive ever had. Im sorry to say that it had been a while since I had last been to the dentist so I had a lot of work to do.  But after a few appointments he was able to fix me as good as new.  The whole office is very professional and I felt comfortable the whole time I was there.  I just wish that I had found them sooner because now that I have graduated I have to move back home and find a new dentist.  I would highly recommend them to anyone looking for a new dentist. Users/UCDaggie2009

20091005 12:42:18 nbsp The dentist is nice, quiet, but nice. They seem to pressure you or use scare tactics to get certain things done. If you put it off, they will call and call saying the dentist recommends this or that as part of your treatment plan..which of course, is usually out of pocket. The office staff is pushy/borderline rude. Will not return.  Users/JuanaBNDavis

20100302 12:37:48 nbsp I have seen Dr. Tran twice, so far. He came highly recommended by a colleague, and I even changed dental plans to see him. So far, I have not been sorry. My first appointment was an emergency  cracked tooth, ultimately in need of a crown. He did a great temporary filling using some advanced material that sets up with a special light. I probably could have lived with that temp solution for a year, thats how good it felt. But even I could tell that the crown was needed. As for the crown work, I was amazed. First off, he was not stingy with the anesthetic  a very good quality in a dentist. Second, the quality of his work was very good. He did talk me into using a ceramic crown instead of gold, which concerned me a little because I grind my teeth and gold has always seemed to work better. However, the system used for creating the tooth includes a 3D model of the tooth and computer selection of the proper tooth surface for your bite. A machine in the next room creates a crown to the exact specification of the space the dentist just created in your mouth! It was very impressive. The crown fits great. After the procedure, I developed some serious gum pain and tenderness. I called the office and was able to speak directly to Dr. Tran. He made time for me the next morning and discovered that there was a little cement from the crown impinging on my gum. Fixing this was a bit of a hassle, as it involved numbing and drilling again. But it is all taken care of, there was no charge for the correction, and everything is fine. On top of all this, the staff is friendly, conscientious and intelligent. The chairside conversation is actually interesting (history of dentistry, photography, how to make shutters for your windows...) There are more crowns in my future, and I will definitely go back to Dr. Tran for this work. You can bet Ill be making sure they get all the cement off when the crown is put in! But I anticipate an overall positive experience under Dr. Trans care. Users/bebrady

20100617 15:57:24 nbsp My experience here was a very pleasant one. Mainly  because the hygienist Melissa was an absolute angel to me! She was kind, informative, patient, (oh my goodness, so patient), and communicative. This was the first time I had seen Dr. Tran so I spent over 2 hours getting my workup. Melissa was with me the whole time and kept me from going crazy with all those xrays and such. Dr. Tran seemed pleasant and was also very patient. He suggested I get thousands of dollars of work done on my teeth (not doubting that necessarily), which has never had suggested to me with my prior dentist,  so I will be getting a second opinion, but overall my experience was a good one. The office is clean, advanced, and friendly.  Users/lovinglife


20101019 22:15:07 nbsp STUDENTS AND OTHER MONETARILY CHALLENGED FOLK, TAKE HEED. I did not have a good experience here.
Before having any work done, I specifically asked the people in the office to make EXTRA sure that I was covered by insurance. They said, yes, they checked, and I was. 10 months later, after Ive had all the work done, it turns out that Im NOT covered. I now owe them far more money than I can afford.
I know that they have made a lot of effort to keep checking and see if the insurance covers me, and I appreciate that, but THEY SHOULD HAVE DONE IT BEFORE I HAD ANY WORK DONE, LIKE I ASKED. They are only putting their business at risk. Fortunately I CAN get the money, it will just be a terrible hassle and Ill have to put plans of moving on hold. But if it was someone else who simply COULDNT pay, theyd just be out of luck!
That is not my only unfortunate experience here. First, though, the assistant, I think it was Melissa, was super nice, patient, and helpful. Dr. Tran was not. I look younger than I am, and he seemed to treat me as though I were even younger (and, dare I say, as if he knew I didnt have a lot of money and wasnt going to be shelling out the big ones on a bunch of work, and therefore, he didnt have to worry). The numbing shots he gave me were rough and the most painful Ive ever gotten. When the assistant did the shots it was fine. He also talked to the assistant about TV shows the ENTIRE time he was doing work on me, including when he was giving the shots.
As for the work he did, he left a small, jagged gap on one of my teeth from where he cut out a cavity, and while my mouth was still numb, he asked Does that feel normal? I said I have no idea. My mouth is numb. He said, Well if its bad, just come back and Ill fix it. Well, it IS bad, it completely shreds floss and gets food stuck in it, but Im not going to pay to have it fixed, and he obviously KNEW it was bad so he shouldve fixed it then and there.
I will not be going back here. Users/gurglemeow

20101020 00:03:42 nbsp Similar experience as gurglemeow, I did my cleaning 7 months ago, and was asked to pay today.  The receptionist Angela and I got into an argument, and she hung up on me.  She should tell me the total cost BEFORE the cleaning, not after.  If you dont know it, say so.  Dont tell me all I need to pay $8 and then bill me $90 six months later.  That just gets me a little upset.  For those reading this, Dr.Tran is actually pretty good, Ive been with him for four years, so I hope he will read this and wont let it happen again. Users/colinc

20101202 14:04:34 nbsp I agree with ColinC. I definitely felt that Mr. Sang cared only about money. He used a procedure that wasnt covered by my SHIP insurance and didnt even tell me about it. I had to pay about 80$ for a filling and a cleaning and some xrays. The SHIP insurance should have covered more than that. He used some special polymer thing that costs more. I never asked for this and he never asked me if I was ok with it. He just assumed and picked the priciest option to stick it to a poor student. Im very upset. I feel like I walked into a scam. Users/JohnnyDoe

20110525 15:26:31 nbsp I would like to respond to the comments regarding insurance benefits and billing. I work for Dr. Tran and Dr. Wong and I am the person that checks insurance benefits. I check for every patient prior to being seen in our office. I ask for specific benefits as well as previous dental treatment history. I document the date, time and name of the person I speak with for every call. There has been a serious increase of inaccurate information provided by Delta Dental in the last year. For some of the above comments regarding getting a bill months later that is because I have disputed the denials of these claims due to inaccurate information given to me by Delta representatives prior to treatment. The response given to me by Delta Dental is that it is the patient’s responsibility to know their benefits.

My response to Delta Dental management was that providing accurate benefit information for their clients is not an unreasonable expectation, and that they should honor the benefit information they provide to the doctors office and the patients.

I am always available to discuss and provide patients with the benefit information given to me by the insurance company.  In closing if you have Delta Dental please be aware of inaccurate benefit information being provided by their representatives that is beyond our control.

Thank you
Angela Gerould
 Users/agerould


20120330
Dr. Wong is a wonderful, kind dentist who is great at what he does. He definitely makes you feel at home and comfortable and always stops to check how you are doing. I wish my insurance plan didnt change otherwise Id still go here. The receptionists are welcoming and nice as well and they are very respectful here. Dr. Wong is great at remembering what youve told him before which makes him a great conversationalist.  I HIGHLY recommend this place!
ArtiSharma


20120522 23:37:45 nbsp had a great experience at varsity dental.  Angela was great and helped discuss exactly what my insurance covered as well as referring me to practices that would be even cheaper with my insurance. when i came in they did not push any services on me, and dr, tran did a great job discussing my teeth with me, and explaining and showing me what he was talking about. great experience, and definitely would recommend them. Users/k5brown
