

Welcome to Silverstone Apartments located in the heart of Davis, California. Silverstone offers a variety of floor plans to suit your lifestyle. We have fantastic studio, one and two bedroom apartment homes as well as 3 bedroom townhomes. Silverstone is conveniently located close to the UC Davis Unitrans buslines L, P, and Q and is approximately two miles from the UC Davis campus. At Silverstone, we have all the amenities and services you will need. Some of these amenities and services include central heat and air, washer and dryer in unit, ceiling fans and modern appliances. We have all the qualities to make you feel right at home. Silverstone is more than an apartment community, it is a lifestyle. Please contact us and we will gladly answer any questions you have.


Silverstone Apartments (formerly Green Meadows) is a fairly large complex in northeast Davis situated on Pole Line Road just north of East Covell Boulevard Covell. TSilverstone is managed by the  First Pointe Managment Group.

Silverstone is near Oak Tree Plaza (most notably Nugget and CVS), Davis Athletic Club, Nugget Fields, some bike paths, and Oak Grove Park. Living there also grants you the privilege of using the lap pool & cozy spa. Washers and dryers are available in some twobedroom and all threebedroom units.

Unitrans L bus line has two stops directly in front of Silverstone on Pole Line Road and Donner Avenue. Although the bus will be headed northbound, it will soon turn around and head towards Campus campus, stopping once again on Donner. The ride takes about 15 minutes by bus or 1530 minutes by Bicycles bike. Parking is abundant here.

Water: Silverstone pays for the majority of water used by community to pay for watering/landscaping and general use, but a small amount is split up between all residents at our community.

To learn more about rental housing options in Davis, check out our Rental Housing Guide as well as our Apartments pages.


Silverstone/Reviews from 2006 and 2007 2006/2007 Reviews ~ 10 reviews/comments

Floor Plans
||<bgcolor#E0E0FF>Silo: Studio||420||<bgcolor#E0E0FF>$1,109$1,149 per month||$300|



20080228 19:04:38 nbsp Were coming up on our one year for the lease. As for everything thats been said, I agree with the weak water pressure (it is enough pressure, its just not great), mold on the window sills true. Nicolai (spelling?) the maintenance guy said to use bleach and air out the rooms. Its a pain. Weve have never had a problem with him getting stuff done quick. Hes always come by within a day to do any of our fixups. Ive never gone through the management with a work request so maybe thats where the hang up comes from. The management is nice tho.)With the NWP we get charged anywhere between $50$80 with 2 people in the 960sq ft unit. We looked for somewhere else to rent from with a washer/dryer in unit or hookups but all of them were way smaller or had poor floor layouts so I think well stay put unless we find a house to rent. If youve been living here for over a year and reup theyll have your carpets cleaned.
Um. What else...when we first moved in there were these baby cockroaches. I dont know what they really are, but they looked like roaches. There were always at least 3 in the bathroom or in the tub we found them all around the house really. It took a few good mopdowns with some pretty strong bleach water and some pest bombs and really thorough cleaning for a few months. That and winter stopped them from showing up I think. Now that its warming up weve killed 3 large roaches and some spiders, but thats been really infrequent. We are a clean couple.
The closet doors are really cheap. You have to completely break them out or their tracks if you need to remove them (using the closet space for a dresser or ent. center) and if they accidently come off track youre pretty much screwed trying to fix them up again. One neighbor said that the remodel they did in 02 was basically new carpet and fresh paint on the cupboards.
Our neighbors are quiet and friendly and the landscapers come around noon thats nice.  Users/EmC

20080310 11:49:22 nbsp We have lived here for almost a year and have good and bad things to say about this apartment complex. Overall, its quiet and the apartments are spacious. Our PG&E bills are extremely high, especially during the cold months. We have had to turn the heater way down and use a space heater to save money. The management is pretty unresponsive to repairs and other questions/problems. I have had a few calls not returned, so just stopped calling and fixed things myself. We had cockroaches when we first moved in and have had the pest guy come a few times. It seems to have relenquished the problem. Neighbors and friendly and respectful. Users/maymay

20080731 12:34:37 nbsp Had bug problems from the start. Fleas when I moved in from previous tenant and pets. Roaches got bad at times, dead ones all over the place in the apartment and outside. When walking dog around the neighborhood at night you will see roaches all over the ground in dark spots, gross. Management ok, not nice or approachable, but have candy. Pool needs more shade. Pretty pricey. Gym sucks. Like the layout of the 3 bdr 2.5 bath, came with W/D and had a huge kitchen. Users/SSS

20081107 16:25:49 nbsp My husband and I lived here from Sept. 07 to August 08 and we loved it. Maybe because we got a great, corner unit and could watch the sunset from our balcony. The place was spacious, clean (I saw a cleaning person in the laundry room almost every morning) and the neighbors were quiet. Never had a problem with maintenance orders. The laundry always worked well and parking was a breeze. I agree the closet doors are poorly constructed, the sliding door to the balcony was frequently broken and we had the occasional creepy looking bugs, but I didnt feel like it was in any way infested. The layout of the two bedroom was really nice, with the dining area separate from the living room. Also loved the location  walk to Nugget and Longs. We liked having central heat/air and so many windows with wonderful views. The office staff were pretty reliably in the office during office hours and even had some weekend hours which may have made it less vulnerable to vandalism. It is more expensive than other places in the area and its clear when you really look up close at the counters, cabinets, walls, that its an older style apartment thats been spiffed up with fresh paint and carpet.Users/Shari


20090429 21:20:47 nbsp This is no longer a nice place. 1: New management is bad. Just bad. Shes rude, curt, and not very approachable. She blows off what complaints you have while giving you a nice smile and saying something will be done. 2: New maintenance lady is bad. Just bad. Well, and lazy. 3: The pool didnt meet standards when a surprise visit from the Health/Safety guy in October. Pools still not open. The hot tub has never been nice, or hot. Its luke warm at best and theres always crap in or around it. 4: The bike in the gym broke at least a year ago and it JUST got fixed in midApril. 5: They put in a new treadmill nice. BUT it has a plugin thing that doesnt fit the outlet. You have to check out an adapter from the office during office hours in order to operate the treadmill. Or buy your own. 6: Theyre really anal about protocol. A woman in our apartment row had flowers & plants in planters, nice ceramic pots, and they told her she could only have 2. Then they dug up and tore out most of the shrubs around theyre corner lot. It looks like crap now. Just a bunch of dirt and twigs. Maybe there was a bug problem. Thats fine. But singling her out when there are plenty of others in the complex with more than 2 pots is wrong. And they are always leaving notices that something is wrong with your porch area. No bikes allowed on porches. They must be locked up in the racks outside. Well, thats nice. There are how many people here with bikes and whats that? Only 4 bike stalls? Brilliant. But they havent bothered us besides with the lame notices. :EDIT: I am deleting my #7 because its too specific and I dont want them to really have it in for me when we start our moving out stuff. But its a pretty schisty thing they done did. But Im going to try to get them to pay for at least part of it.

They dont pay NWP. We pay everything. Plus its a socialized system so I pay for other peoples waste. BS. For 2 people we pay about $58/month on NWP. PGE is the same way, you pay for the rows usage.  Were so out of here. It was $1235 for a 2br with washer/dryer 2 years ago.  Users/BaggedMilk

 Out of curiosity, I checked with PG&E  they told me each apartment is metered, and that we pay for our individual usage. Youre right about the NWP  it is a group rate, though Im not sure how its calculated.Users/DukeMcAdow
 ~Youre probably right. I remember PG&E coming by. I guess thats what they were doing. I dont think its always been this way tho. If I remember correctly they used to grouprate the PG&E too. Glad thats fixed at least.

  Just curious if youve ever lived elsewhere in Davis, because Silverstone is FAR better to deal with than a lot of other places. As for your complaints, try getting some facts straight  there are at least 10 bike racks throughout the place. I live in the same area as you, and have you even talked to the people who had their plants removed?? It was only from the front  they have a whole beautiful menagerie of plants on the back patio  And theyve lived here 16+ years and LOVE it. As for the treadmill, its working fine now. There was a week or maybe two when the plug didnt work because it wasnt the right kind, but its fixed and I use it regularly now. And yeah, the notices can be annoying, but since when does anyone (myself included) bother calling the office back when they leave a message? Yeah, apartments arent perfect. Hell, neither are homes. You may not like everyone in the office, but theyre trying to do their job and make a living just like the rest of us. It pisses me off when people go spouting off without checking their facts  especially when there are far worse places to live, and far worse office people to deal with. I should know, I went through hell when I lived off of J street in one of the apartments there. You may hate it here, thats your experience. But just because all of a sudden you dont like it doesnt mean you didnt at one point, and someone else might love living here. You obviously rented here for a reason in the first place.  Users/davislocal

~Answer to davislocal Yes, we have and are currently living elsewhere in Davis and wish I had started off here instead of at Silverstone. Yes, I talked frequently with other residence in our building. The couple were speaking of were PISSED about the change in management. We talked several times about how horrible it became after the change. Two other couples were equally displeased with the management change. The treadmill was inoperable for longer than 2 weeks, far longer. Bike racks around our unit there were 4 racks. I have no need to lie, the truth is bad enough. When my kitchen sink backed up for the second time they called a plumber but neglected to tell me that I would be the one paying him. There was nothing he could find that put me in the wrong and told management that, but they didnt care. I cleaned the heck out of the apartment when we moved out but the hired a cleaning service instead of using their own cleaning staff and had no way of knowing how long the cleaning crew spent cleaning the unit or what the actually cleaned I asked. They charged for carpet cleaning when its stated on my contract that after living in the unit for 12 months its free. They told me that I lied to them when I said we hadnt painted our walls. They told me I lied when I said the walls were white when we moved in. Yah, really classy. No, I have no good feelings toward this current management. Before the change it was good, so yes, we had a reason to rent there in the first place and left when it turned to shit.  Users/BaggedMilk

20090518 14:23:22 nbsp   Users/JanethN.

20090527 13:59:26 nbsp Absolutely the WORST apartment complex I have ever lived in! Management is terrible! They will harass you constantly despite paying rent on time every month. Any trash thats left on your front door for more then 30 minutes expect a formal write up. One too many plants out on the balcony, another write up. Cockroach problem, management are more then happy to ignore you. Oh and by the way, there IS a cockroach problem throughout this complex I found (actually, my indoor cat) found 8 in one night. Yuck! Avoid this place. Avoid! Avoid! Avoid! Users/love2dancewild

20090601 08:42:46 nbsp I lived in this place a couple of years ago, it is generally a nice place, but could use some improvement. I guess it was different management at that time who were rather nice, for the most anyway. They did have one thing in common with the new management based on other peoples more recent experiences and comments; the cockroaches. This place does have a severe cockroach infestation; that is the reason why I left. Cockroaches would come in the apartment all the time crawling in from who knows where. I had the maintenance people try to seal every obvious hole or opening on patio and front doors and frames. Management refused to have my apartment spayed for a long time saying they were spraying outdoors and that would be enough. It wasnt. They used to claim that the cockroaches came from the empty lot across the street. lmao!!! I can picture them walking across the street every night, lol. I finally got them to have my apartment sprayed after about a year of trying... it didnt help for too long. The entire complex should be tented and sprayed. You couldnt walk outside without running into a few both dead and live ones. It was awful at night knowing I could easily step on one.

Besides that problem, I really liked living there. I loved my apartment. It is a great location, lowkey, quiet yet so close to the nugget and longs. I hope the hot tub works better now, it was never all that hot just warm. Rent has gone up so much since I lived there just two years ago, that sucks! Users/belles

20090601 08:49:11 nbsp HDN sucked back then too, the entire network would go out entirely for days and they blamed it on some communications company. HDN  BAD Users/belles

20090601 18:34:15 nbsp Ive lived here for 2 years and am really looking forward to moving in July!  Here is as unbiased a review of this place as I can muster.       Pros: Quiet, plenty of parking, pretty good storage.  No bugs (i know there are units with cockroaches, and they are all over the grounds, but ive never seen one inside so go figure), Pool area is nice and uncrowded, quick trip to nugget shopping center. Mostly grad students and families.     Cons: EXPENSIVE!!!! They are losing 70 apartments to new renters (more than half the complex) this summer yet they still raised rent on all units... $3080 a month in water/garbage not included in rent, Cheap appliances and cupboards, New management are being hard asses on every ridiculous rule, Pool has been closed for 5+ months  no sign of any work done yet, apartments are dark and just feel old, closed floor plans. $500 dollar PER pet deposit, the place is constantly falling apart and you either fix it yourself or have management come into your place and fix it (leaving a nice note on all the things you need to change in order to not violate your lease, and when they will be back to make sure you changed them.)  Next door park is nice yet at the same time bad, nice because its a pretty good park, bad because from 48pm every night there are screaming/cussing/drinking basketball players there.  What else??? Ugly patios i guess...  Thats all i can think of for now. Users/JeffS

20090609 12:03:10 nbsp  The apartments are spacious, and the layouts at this complex are better than most others I have viewed in Davis.  Parking is good for the most part but it gets crowded late at night and there are handicap spaces that are not regulation size or in convenient locations.
The gym is tiny and there are really old treadmills in there, its also not ventilated very well.
The HDN internet service is very slow and doesnt always hold signal.
Also, Roaches are a problem here!
That being said, the management are pretty attentive to tenants needs and usually willing to accomodate requests.  The location is convenient, the Nugget and Longs are within walking distance and Pole Line leads you straight to Target and Costco in Woodland.  The price is steep for the location (its pretty far from campus) and they dont cover water/sewer/trash like most other complexes.  I have lived here for a year and probably wont be renewing. Users/LMarie

20090619 14:31:54 nbsp Do not take the lease with this apartment. They are totally bad. Your deposit can never be taken back. We lived there for 14 monthes. They asked us 1000$ deposit, but they only refund us 78$. You know there are no damage in our unit and we took 1 week to clean it. The unit looks very clean when we moved out. But they took off our money near to 1000$. They can not give us a resonable explanation. We are plan to sue them.  Users/cherry

POOL AND SPA FIASCO OF 2009:

These are the original comments and notes that have accumulated over the first half of 2009 related to the longterm closure of the pool and spa area. They have been moved from up above since the pool and spa have reopened as of June 26th, 2009.



  Unfortunately, the new property management has made multiple misleading and inaccurate estimates regarding the pool and spa completion dates (seemingly in a futile attempt to minimize the situation and convince tenants to resign leases). The pool and spa were both closed in late January, 2009. The doors to both the pool and spa remain chained closed even as of today, June 17th, 2009 (~5 months).

  Therefore, all bets are off. Do not live here unless you dont mind paying one of the most expensive rental rates in the city while not being able to access the amenities as advertised. Also, while there was no mention of pool access (seasonal, construction, repair, etc) at the time of lease, nor in the lease itself, it is reasonable for one to expect that when management says there is a pool, spa, and 24hr fitness center, it can be taken in good faith that these things will be available and maintained/repaired within a reasonable period of time. It is clear that the new management is more concerned with their bottomline than with customer service and satisfaction.

  The pool is NOT open seasonally, it is open year round (just not heated so have fun).

  Comments below are being added on behalf of Management (this is a correction to their deletion of the comments listed above):
    Though it is not yet the end of June 2009 so the estimation by Management is still accurate.
    Pool is open seasonally. Spa is open year round.
  Pool and spa area are open as of June 26th, 2009. Have fun people  lets hope it stays open!

20090705 18:16:06 nbsp The spa is cold!
wtf, does anything in this place work? Users/Domlertylique
  Seriously...  ilivindavis

20090712 13:38:57 nbsp Went to go see the model apartment and I was shocked by the rude managers. The blond one was on the phone while the other one barely acknowledged my presence. After I was shown the apartment, the brunette (im guessing shes the assistant manager) smoked outside while I got my drivers license. As I was walking to my car, I saw her cigarette bud on the floor. How gross and unprofessional! Overall, I wont be signing a lease here.  Users/Nikky

20090712 18:26:42 nbsp The spa and pool are still open, yet the spa doesnt have any bubbles. At least theyve turned up the heat now... Maybe someone can fix (or turn on) the pump system? Users/iliveindavis
  As of today there is a sign on the pool stating that the pool will be closed if any food or alcohol is found in the pool area.  Way to punish the masses for the sins of the few...

20090826 15:45:30 nbsp The water runs about $75 a month  not $25 as mentioned earlier. It is divided between the complex, so you cant control your monthly bill. There have been some strange people moving in here lately. It was better a year ago. Users/maymay

20090908 13:40:23 nbsp We told Management 3 times that we would like to leave a month early from our lease, and if they could find someone to take it over for us.  They finally called and told us that someone was moving in september 1st (our lease ended august 31st, so no help there).  We moved out early and were planning to just keep the apartment empty and turn in our keys on the 31st when our lease ended.  We were called and asked to turn our keys in early.  I asked if we were going to get a refund on rent for august since we were still paying for the entire month, and by turning in our keys would lose access to the unit we were paying for.  Management was shocked at our request and refused, prompting us to tell them that No, we would not turn in our keys until midnight on the 31st (good luck cleaning the apartment in 8 hours for the new tenant).  Finally they were forced to concede the rent for August.  I would definitely not recommend dealing with these people. Users/JeffS

~They asked us to turn our keys in too we have soooo many new tenants and need the extra time to clean. They still hired a cleaning crew and served us with the $100+ fee even tho I had scrubbed that thing raw, cleaner than when we moved in. If I werent 5 months pregnant  I would have taken the time to take them to small claims court...they need to be taught a lesson. They like to screw their tenants. Users/BaggedMilk

20100203 00:26:03 nbsp Expensive for what it is. Things keep breaking down here, although the maintenance people have been very responsive each time. Doors, windows, dishwasher, fake wood countertop, and stove are old and outdated, although the outside of the complex looks nice. The model unit was much more in shape than the apartment we got was. Fairly quiet except for the occasional party in unit 64, which has woken me up at 12am and 2am on 2 separate nights. Nice to have park next door and walking paths beyond that. Pool and spa are decent and not crowded. Very welcoming environment for pets. Neighbors are respectful and friendly for the most part. Users/moody1

Hey.. I live in Silverstone too.. Unit 64 is really friendly I cant imagine them keeping you up on various occasions. They are a nice young couple who actually look over a mentally challenged boy that is always wearing a big hat most days so I give them kuddos for that.

Well maybe I have the unit number wrong. Users/moody1

20100602 21:38:29 nbsp Dont trust the management here. We signed a lease with a special permission to have our small RV parked in the parking lot here. We were given permission and it was written into the lease. Now they are refusing to give us a new lease unless we get rid of the camper, and they keep harassing us about having it out there. They change managers every couple months and each time a new one comes, they dont read our lease, and put a Warning note on our RV. We are glad to be leaving, but wish we werent subject to a bait and switch tactic to get us into a lease, and then throw us out the next year. Users/moody1

20100604 10:44:45 nbsp New manager every other month. Mold, cockroaches, cracks in the concrete under floors let water seep up into carpet, A/C broke, sinks drain slow... there was always something going wrong. Had 2 bikes stolen when we first moved in, then recently one apartment robbed at gunpoint. We thought this was the best place in town when we moved in but they just paint them up really nice. Underneath they are really horrible apartments. Dont let the looks fool you. They also seem like a good price, but add in all the utilities you have to pay and they are NOT a good price. The free wifi is only free for a month, and its not very good, so youll end up paying for Comcast. Managers wont let you attach a Dish and most balconies dont face the right way for a Dish anyway. No hanging plants allowed.  Users/Toby.Adams

20100608 10:54:43 nbsp This apartment is absolutely unsafe.  In the last 8 months there has been a Peeping Tom peering into residents bedrooms and an armed robbery.  Residents were not notified of either of these incidents, which I consider to be extremely unsafe and irresponsible.  The apartment has also done nothing to improve security.  I do not feel safe living here. Users/creamsoda2014

20100723 14:11:07 nbsp Ive lived at Silverstone for 3 years and my experience has been good, so far; Im pretty comfortable here.  Havent had to deal with management much, but when I have, theyve been fine.  The only thing that has broken has been my water heater; it went out during the Christmas holiday, so the response wasnt as snappy as it mightve been at another time of year, but it was fixed.

The short walk to Nugget, CVS, my eye doctors and dentists offices, Wildhorse, the ag buffer, the location at the edge of town...all big selling points for me.  Tenants seem to be a mix of older students, workingpeople and young families.  Its generally pretty quiet with everyone into their own thing.  Traffic on Pole Line can be noisy during the day, but at night its almost deserted. The ag fields across the road allow for panoramic sunset views; the tradeoff is that they also produce a lot of dust during planting/harvesting (but the sunsets are worth it).

Crime (especially bike theft and car burglary), rodents, roaches?  I think those are problems all over Davis. I doubt Silverstone is any worse than average (and I certainly wouldnt consider it absolutely unsafe).  Ive seen roaches outdoors in the spring/summer, but have never seen any inside my apartment (or evidence of any); I live on the second floor and don’t usually have a lot of food onhand, so maybe that’s why, I don’t know. Ive never had a problem with the mold that Ive heard so much about (they even discuss it during leasesigning); I open my windows every chance I get (I like fresh air), so maybe that helps. Users/DukeMcAdow

20100819 12:59:33 nbsp I have lived here for a few years and the apartments are okay. Ours is VERY outdated with old appliances, sloppy paint jobs and old flooring installed. We should get a rent reduction with the quality of our place.

There are bugs all over the place, but you just need to call the bug guy and they will go away. Thats what you will get when you live across the street from a field.

The management should have released a statement to the renters about the home invasion. Although it was an isolated incident, people should be aware of whats happening in their community. Users/MissKay

20100917 00:30:59 nbsp Nice neighborhood and maintenance, but expensive, especially after getting less than a quarter of our deposit back. They decided to repaint the entire apartment on our dime :( Users/ChashBrown

20101121 23:14:27 nbsp Does anyone have any info on the guy with probable schizophrenia who lives in the complex? I see him yelling and gesturing wildly around the complex at different times of the day. He also sits in his car staring into my windows at night for hours while smoking cigarettes. Id call the police but hes obviously mentally ill, and Im not sure its always worth calling them about it. Users/HandGiraffe
    If you fear for your safety because of this guy, I would call the authorities no doubt. At least it would be documented in case anything did happen. Absolutely make the call.  Users/PeterBoulay
    Hi folks, I see this guy all the time too and Im seriously thinking about calling the police, is he schizophrenic because I see him driving? The management need to do something about him as its very threatening if he is staring at you as he is a big scary dude and shouts very aggressively / plays loud music, etc. I dont think its right we pay so much in rent to feel threatened where we live? Aside from this Silverstone is a nice place to live but they need to sort this issue out as especially if you are young and female Id not recommend living here as its a very threatening environment.Users/MattGoddard
  Yeah he spends a lot of time in and around his car. Im surprised he can drive as well. You hit the nail on the head  if you are young and female and live in Silverstone, be on the lookout because this guy seems dangerous. I park in his favorite spot so he wont stare into my windows. So far no damage to my car. Ive seen him off his meds a few times and he yells and threatens anyone walking by. He also walked into traffic on Pole Line and challenged passing cars to fights.Users/HandGiraffe
   Ive witnessed similar behavior and he is always around, looking in cars, peoples apartments, gesticulating strangely, shouting, etc. Have you spoken to the police or the apartment management? He might be harmless but they need to talk to his father or whoever the older dude is who lives with him to let him know people are feeling threatened. Silverstone management any comments? Let me know if you want to take it up with the management as Im totally supportive and I actually worry for the kids, etc. I see around with this going on.
   I have yet to speak to management due to scheduling conflicts, but I mean to take it up with them soon. I think that is his father. Maybe take video if you have the opportunity, so management has a clear idea of what is going on. I have about 5 minutes of him on video doing a relatively lowerkey performance in the middle of the day from about 2 weekends ago.Users/HandGiraffe
     As a bystander, it sounds like things are somewhat moving forward.  Best of luck to both you and Matt in figuring out the situation.  Im sure youre not alone in your concern. Users/JabberWokky jw
   Ill talk to the management too and let me know what they say on this forum when you talk to them and show them the video so they cant ignore it and say its an isolated incident. It isnt, its all the time and its been going on for months. Silverstone also has the rentacop now and if you dont have their phone number you should call the management and ask for it and next time hes going off outside your apartment just call the management if they are around or the rentacop if its outside office hours and get them to deal with it. Eventually they will have to do something about this situation.
  I believe they moved this week. Users/DukeMcAdow
  Really? Did you see them moving out? Users/HandGiraffe
  Yes, we gave this person notice to vacate the community due to his behavior and the safety concerns we had for each of our residents. I appologize that this process took as long as it did, however there were legalities that we are required to comply with. They vacated the community November 30, 2010. Users/ManagerSilverstone

  Thanks so much for taking care of the problem. I do, however, still see him walking around the perimeter of Silverstone. I dont think he moved too far away. Is a restraining order in order? Users/HandGiraffe
 Yes. There is a restraining order in effect until April 22, 2011. The order includes that he is not to harrass or annoy any of the residents of Silverstone Apartments. It also stipulates that he may not interfer from you engaging in your usual and customary day to day activities. Users/ManagerSilverstone

20110209 07:40:10 nbsp Question: Has anyone noticed that the management only puts ground cover around the area to the model apartment? They just put in another round of clean, black cedar ground cover  but it abruptly stops after the model home. Theres a lot of mud and exposed dirt all around the apartment complex and I wish they would take the time and money to make the whole complex look better.  Users/MissKay

20110319 11:59:53 nbsp I have talked to the police about him, and he does not live at the complex. He does live near though. He has no history of violent behavior, although he is obviously disturbed. Dont let him freak you out too much, but I would obviously keep my distance.  Users/JanethN.

20110902 21:47:31 nbsp Having lived at Silverstone for the past year, it has not been a very good experience. No matter what they try to tell you in the office, the roaches are constantly there,the big ones outside and the little (really bad, infestation) ones inside. My neighbors all have the same problem so it is not just my apartment. Another problem that has troubled the complex has been the dirty water which happened very frequently for awhile (everytime you turn on the facet or shower, there is brown water that comes out for several minutes). Finally, there is the ever present high staff turnover, which everytime I go in the office, it seems like there is somebody new in there.  All in all, not a great place to live; far from campus and the roaches are the worst of any place I have lived in Davis for the past 4 years. Users/PoyRoy


20111114 09:37:27 nbsp I lived at Silverstone for 2 years, from 2008 to 2010.  I had a mostly positive experience while there.  There is ample parking, the complex was very quiet, it is within walking distance to several stores and bus stops, and the field across the street provides for beautiful sunset views.  While we were there management changed, and for a few months they were strict about the rules (such as no bikes on balconies), but after the initial adjustment period everything went back to normal and they relaxed their stance.  Although you must pay for your own water (which really isnt unusual outside of Davis, every other city Ive lived in has required the resident to pay), the rent itself was a fair price.  We did A LOT of research into renting in Davis, we searched for months for the right place. Any apartments that are cheaper will have a sharp decline in quality.  We also loved the floor plans at this place and the washer/dryer.  Whenever we had maintenance requests they were handled in a very timely manner.  The biggest plus was that we got all of our deposit except for $50 back, even though our cat had scratched up patches of carpet and we expected to be getting hardly anything back as a result.

As for the negatives...well, there was really only one period of time where we were unhappy living there, and that was when a large family that was violating their lease was living below us.  They had way too many people, were way behind on rent, and were very loud and dirty.  They were evicted by management, but left behind a lovely roach problem that management sprayed for, which sent the roaches up to our apartment instead.  We asked management to spray our apartment but they told us that the bug guy could only come once every two weeks, so we would have to wait until then.  After a couple of days it became really unbearable as they were everywhere in our kitchen, so we begged the office to spray again, and they finally conceded and had the exterminator come the next day.  After that there were no bug problems at all.  The only other issue we had here was a stolen bike, but my roommate accidentally left it unlocked one night so it wasnt a surprise that it was gone the next day.

As for most of the complaints Ive read here...honestly, it sounds like some of these people havent spent much time renting, because there are some issues you just have to deal with no matter what apartment complex you live in.  Especially in Davis, bike theft and roaches are a problem over the entire city.  And this place is hardly overpriced (it was about $1200 for a 2 bedroom when we were there) for Davis, where the rent is completely outrageous no matter where you live (which is why we moved to Sacramento!  MUCH cheaper, even with the added commute).  Broken gym equipment, dirty pools, and annoying neighbors are things I have encountered at every apartment complex Ive ever lived in. However, at those complexes, I often had to deal with horrible parking, absent management, unsafe neighbors, terrible locations, no nearby bus stops, unanswered maintenance requests, and trouble getting my deposit back.  Those are things I never had to worry about at Silverstone, so in my mind living there was a positive experience. Users/IndigoShell

20120110 22:05:44 nbsp Followup to my July 2010 comment:  I moved a few months ago, after living at Silverstone for 4 years and it was pretty painless.  4 years was past the scheduled lifetime of the carpet and paint, so Silverstone didnt deduct any associated charges from my deposit.  I always found management and maintenance staff friendly and responsive, and I have no complaints.  I still think its a nice place to live, but it can feel a little isolated at the edge of town and Pole Line can be noisy.  The thing I miss the most at Silverstone?  Having a water heater in my apartment!  Hot water, no wait. Users/DukeMcAdow

20120614 13:51:31 nbsp FIVE STARS!!! I have been a renter for a very long time, and never have I lived in a place with GREAT property and maintenance management. Management at Silverstone really care about the needs of their residents, and up keep of the property. They are genuinely friendly, trustworthy, and super professional.

The apartments inside are cozy, with nice floor plans. I also never had to worry about noisy neighbors as the property attracts more mature adults. The pool is always clean, and refreshing on a summer day.

Many people believe that renters are always screwed from their deposit, but, this is not the case at Silverstone! If you maintain your apartment in good condition, and leave it the way it was when you moved in, you will get your deposit back. I did the first time I transferred to another unit.

Landi and Debbie are the best property managers I have ever had the privilege and honor of knowing.

 Users/CristinaTrujillo

20120803 17:12:08 nbsp Two Words: By Management. My boyfriend and I cant wait for our year lease to end by the end of this month. The two ladies that work here at the office, Landi and Debbi, appear to be nice once your signing the lease and renting an apartment, but once youre in, you have a manager that ignores you, waits too long to return your calls, talks over you and ignores your complaints. Completely unprofessional and rude. We have seen other residents walk out of the office yelling. Another thing, its way too expensive. When we first signed our lease, we asked if she knew where we could find a cheaper place. She replied by saying that everywhere in Davis one bedroom apartments are in the 1,000 range. She didnt bother giving us information on cheaper places. The manager is money hungry and she doesnt care about making your stay here comfortable. Our apartments was infested with cockroaches a month after we moved in and it took us 3 months to get rid of them. We had a guy come but it didnt work to clean it out only once. Its like the cockroaches are everywhere in the complex and will come around again even if you clean out the ones already in your apartment. We painted our wall red and she told us that she will deduct 200 from our 300 dollar deposit even after we said we would paint it back white. Anyway, I personally cannot stand a manager and staff that arent respectful and that are snobby, so that is my opinion. If you want a decent place, dont go here!! Users/DianaReed

20120920 14:44:36 nbsp I completely agree with the bitchy management. Literally worst management Ive ever experienced. Lived here for a year and had amazing management. New management at the front desk came in after the first year and Ive been here for two more years. It is the worst management and Id recommend not living here for the sole fact that they try to charge you for everything, it takes forever to get anything fixed, and Londi is the worst ever. Youd be surprised how much management makes a difference. Users/no

20121005 14:52:22 nbsp We have lived at Silverstone for about 5 years. It is quiet, dog friendly and the staff are responsive to our requests. Every time we have had a maintenance issue, Debbie always promptly responds to our requests. The apartments arent new, so there are going to be issues from time to time, its just expected. There are 2 parks right behind the property and a very nice gym.
We keep our house clean and the food sealed up, so we dont have any cock roaches in our apartment. The neighbors are friendly and we enjoy getting our dogs together to play in the grassy area at the center of the property. Silverstone is good for couples, families and grad students. Its a little far from campus, so I wouldnt recommend it to the young crowd that want to be around all the action of downtown Davis. Users/Graphics

20130102 17:51:58 nbsp Is there a rat problem here? I left my car with a friend here on New Years Eve and when I came back the next day a rat had chewed through about 8 wires and all the tubing connecting the windshield wiping fluid. Theres a ton of rat traps around the property so I guess at least theyre trying. Users/MikeyCrews

20130731 07:05:08 nbsp I was not impressed by this place. First off the timing for the lease seems to me to be kind of a catch 22, at least for us. Our leased year was shifted over from the rest of the Davis apartments by a month, so rather than SeptemberAugust this was AugustJuly. This means that come the end of the lease if we want to stay in Davis either stay signed up here or find some place to crash for a month before a new lease will begin.
When we first moved in we as well had a huge bug problem, only our pest du jour was flies. Every day we almost had to make a game out of who could kill the most flies. I think the number to beat went up to 20 with an average per person per day was 10. This continued for about 3 weeks. The other common pests are the cockroaches. If you bring one in management will say that its a common sight  because theyre looking for water. I claim so much BS on this argument because they water the grass 3 times a day and every day there are pools of standing water in the grass. Further cockroaches are highly prolific and even when you see one that would indicate a large mass of them elsewhere right nearby.
On to the kitchen shall we. Our place had a rather defunct stove and oven. Half of the dials actually would grip the knob that would actually turn on the coils, and then even if you turned them on there was no guarantee that you would get the right setting or that you would turn it off. Personally I woke up a few times to a rather warm kitchen because the oven had been left on all night. The light to indicate when the coils are on was not on so the last user thought that they had turned it off. I had personally informed maintenance about the issue, she came in turned a knob and then said it was ok. This happened a few times until we just gave up on them. In the end I started using a pair of pliers to turn it on and off. The walls however were very good and indicating issues, such as water seeping in from outside during the rains. Again, informed them and they did nothing. Our solution was to pile up towels against the wall for the rest of the year.
Bathrooms! These toilets need to be replaced! In every toilet the water container on the back was severely rusted up on the inside and on one of ours the rubber stopper was so corroded that it wouldnt always catch properly making the toilet overflow. This happened a few times as well. After pointing out the issue to maintenance they did nothing about it. It was at this point we realized that we would just have to fend for ourselves. I will say I learned more about plumbing than I had anticipated. Another fun issue was with the shower dial. The dial worked fine, the pipes it was connected to however were not fine, they in fact were not secured in at all. Whenever we turned on the shower you would have to pull on the dial and slam the piping into the wall. This is not good design by any means.
Finally the AC. Its there... But it only gets upstairs, as with the heater. During Winter we would all be downstairs with blankets on because the heater was going full blast, but upstairs. All the vents would be open downstairs with the vents upstairs closed and still nothing came downstairs.
The one thing I will give them is that they did fix our washer/dryer unit. It made an awful squeal during the dry cycle and they brought someone in to fix it. Was there really anything else that they did right... not that I can recall.
Lastly I just want to point this out to others who may be in the same boat I was. One month I was late with my payment because I had run out of checks and my bank doesnt have a branch in Davis. The closest branch was really through my parents, both of whom were on vacation at the time so I had to wait for Monday when they got back. So I informed the office that my payment would be the next day to which I was told no problem. I get it to them and then told that I would be charged a 50$ late fee. May this be a warning to all, in order to charge a late fee management must provide you with reasonable excuse or your check has to bounce. http://www.dca.ca.gov/publications/landlordbook/livingin.shtml (or look up Orozco v Casimiro 2004 California court case) Neither of these happened. In fact I saw the checks on her desk that she had yet to deposit, it wouldnt have even been an additional charge for a separate deposit. Im not an expert in law in any way so maybe my conclusions from all of this are skewed, but to me it sounds like in this case the 50$ fee was illegal. Many places do this as well, so really this is just an observation on rental agreements in general.
Overall: 3/10 Would not suggest to anyone. (I gave it a boost because it is a nice part of Davis) Users/EvanBare

20130805 10:16:01 nbsp I love Silverstone.  Londi and Debbie have been really wonderful about requests, maintenance, and the odd favor.  I really like my neighbors and havent had any problems sleeping with an overhead neighbor.  The pool recently got new BBQ area which seems to be really popular.  My dog made dogfriends quickly and a group of us regularly get together and let the dogs play.  I really recommend this place for the quieter, family, grad student set who will appreciate its peaceful atmosphere.  Not really good for the partying student, kind of on the outskirts.   Users/MaureenHoffmann
