
Simmons Real Estate is a third generation, family owned and operated property management company in Davis.  They manage several apartment complexes, townhouses, duplexes, and singlefamily homes.  They also manage several Self Storage storage facilities, most with UHaul truck rental truck rentals.


20120316 17:17:54 nbsp My husband and I tried to rent a unit from Simmons.  The Asian lady Ally is completely rude.  First they ran a credit report on me using some useless company that showed me having something false.  I then went to Experian, the top credit check company and they showed nothing.  My husband had the same problem.  We have receipts and everything including reccomendations from all our past landlors and she said its coincidental that both credit checks are wrong. at least when we prove it wrong admit to mistake.  Then she started lecturing me on how i cant have someone else live with us when we had no intention on doing it.  She then was so dumb to ask me why I work in Los Gatos and rent in Davis.  I explained that my company is huge and that is where the headquarters are.  She is literally an idiot.  They refuse to rent to people for the slightest reason.  Every step in this has been misterable!!!!!! They say one thing like only having one credit check done and then lie and say there needs to be another one done.  I cant believe how incompetent the people are to not admit their credit check company is mistaken when we have evidence!!!!!! Users/rosepetal140

20120316 17:25:45 nbsp Simmons Real Estate is a third generation, family owned and operated, property management company. They manage several apartment complexes, large and small, townhouses, duplexes and single family homes. Simmons Real Estate also manages several storage facilities, most with UHaul truck rentals. Users/lindakimsey

20120806 16:25:57 nbsp I made an account just to comment on this. Ive lived at a house manages by Simons real estate for about 3 years after I graduate college and started working. Im quite happy and think the management company is great. Prices are relatively low compared to others. One thing I dont like though is this woman named Ally who manages our house. She becones frantic and rude if we miss her call. When the deposit policy or other policies change, she doesnt tell until the last minute. She is really rude. This company provides affordable housing, but to deal with someone like Ally, its almost not worth it. Users/Workinggraduate

20140501 16:44:55 nbsp DO NOT, I REPEAT DO NOT rent from this company they are the biggest scam artists out there. One of the office ladys is completely incompetent and the other is just plain rude. Do not give them any money and rent from someone else who knows how to do their job and isnt owned by John Simmons.   Users/NSun

20140506 13:11:34 nbsp ALLY IS THE WORST. Shes the woman with a thick chinese accent who doesnt give two shits about potential customers.  ABSOLUTELY TERRIBLE service! Similar to the last post, I have an emotional service animal that was mentioned when Simmons called my current landlord. Before calling my landlord everything was set to go with the lease and deposit ready to be turned in. Then I receive a call from Dolores (another staff member) and Ally, since Ally was much too incompetent to take care of the sale herself informing me that the owner has denied my application.
I asked them the reason and they insisted they legally didnt have to tell me. Then I figured out after speaking to my current landlord that the reason they ILLEGALLY DENIED me was because I have a service animal. This business is completely unprofessional and Ally is the worst real estate agent I have ever encountered. She cant even speak English! and is utterly rude. She even told me to knock on the current tenants door during dinner time to demand a tour?!? Im pretty sure thats illegal and not to mention rude in itself. She also talks over you when you speak with her normally, and is just a shit show of a person.
Do yourself a favor and dont work/sign anything with these scumbags. They discriminate against those with service animals and have terrible management practices. Good luck with a lawsuit youre about to receive in a couple weeks!! Users/DavvvvisStudent
