
Slugs & Snails can be found most anywhere theres Town Flora vegetation in Davis. In fact, since it was originally founded as an ag school, Davis should properly have a UC Santa Cruz slug as its Gunrock mascot rather than a horse... I mean you see way more slugs in Davis than horses! Anyway, both slugs and snails belong to the mollusca phylum which includes the devilfish, octopi, squids, clams, and oysters; the huge snail/slug class is known as gastropoda. Gastropods are a softbodied type of mollusk that is basically a head with a flattened foot; most gastropods are aquatic animals, such as Northern Californias wonderful red abalone or a common limpet, and both snails and slugs are the only terrestrial mollusk.

The brown garden snail that we typically see in Davis is the European brown snail Helix (Cyptoomphalus) aspersa Müller. This plant feeder has been disseminated into many parts of the world intentionally as a food delicacy, accidentally by the movement of plants, and by hobbyists who collect snails. It was introduced to California in the 1850s as a source of escargot and has become very troublesome as a pest of crops and Town Flora ornamentals. Though you can eat snails from your yard, be aware that even though you may not use snail/slug bait, poison laid out by your neighbor may infect seemingly healthy snails in your yard  ingesting poisoned snails can kill you! Be sure to read more about farming garden snails before consuming any slimy things off the ground. To be on the safe side, you could always buy some canned escargot at Cost Plus World Market instead.

Essentially, the only difference between slugs and snails is that snails carry coiled shells on their backs while slugs dont. Both have eyes at the tips of short stalks arising below the base of much longer, more slender tentacles  these tentacles feel what the simple eyes may not see. The radular mouths of these gastropods are directed downward so that food can be taken from the surface over which they travel. And finally, all gastropods have a single, broad, muscular, flatbottom foot which propels them with the help of a special gland in the foot that secretes mucous. The common garden snail is the slowest moving animal and can travel about 0.03 mph (0.05 kph).

One adaptation enabling land snails and slugs to survive on land is their ability to produce plenty of slimy mucous. This mucous prevents the animals body moisture from being soaked up by dry terrain and protects the animals fleshy underparts from sharp objects. Snails and slugs can actually glide across a razor blade without being cut. During the dry season, snails and slugs bury themselves in the soil or another protected spot. Snails plug up their shell holes with mucous, and slugs secrete a sort of mucousy cocoon for themselves. Throughout dry spells the animals remain in a state of suspended animation, in which their body processes slow to a point almost like death. However, theres enough life for them to become active again once enough rain comes to dissolve the mucous and soak into their bodies. Mucous also serves as a defensive mechanism when a predator such as a Toad Tunnel toad snatches up a seemingly defenseless slug. The slug secretes such quantities of the stuff that after the toad chews a few times, it finds its mouth clogged with sticky, gooey slime.

Most snails and slugs are hermaphrodites, possessing both male and female genitalia. In some species, an individual may behave as male for a while, then as a female. In a few species, selffertilization occurs. Mating requires four to 12 hours and somewhere around 86 white spherical eggs about 1/8 diameter are deposited in a small dirt nest about three to six days later. The nest is hidden with a mixture of soil, mucous, and a quantity of excrement. During summer months, the eggs hatch in about two weeks and hatchlings reach maturity after about two years in southern California.

 Management 
A good snail and slug management program relies on a combination of methods: eliminating shelters, creating unfavorable conditions, destroying existing colonies. Since slugs/snails, like Earwigs earwigs, seek out shaded moist environments, you can pretty easily start eliminating these habitats by clearing boards, stones, debris, weedy areas around tree trunks, low growing leafy branches, and dense ground covers. This allows fewer snails and slugs to survive, and those remaining congregate in the last few shelters where they can more easily be located and removed. Exuberant Alcohol beer drinkers, snails and slugs will congregate around a saucer of beer like an Irishman, and those drunken souls that dont drown in the drink can easily be picked off and tossed into your neighbors yard; bury the saucers at ground level and keep the beer level deep enough to drown the mollusks. This type of trap is a good excuse to open a bottle of beer, but inverted melon rinds also make good traps. Scrape off the accumulated snails and slugs daily and destroy/relocate them. Do not use salt to destroy snails and slugs; it will increase soil salinity.

Irrigate less overall, and what irrigation you do should use longer intervals between waterings (using a bit more water per irrigation to keep plants happy, if needed).  Much of Davis is overwatered anyway, and gastropods all fear drying out.  Less frequent, deep waterings are generally better for the lawn and garden anyway.

Next, make like the US and embargo their food supplies while blocking transportation routes. Choose snailproof plants for areas where snails and slugs are dense, locate vegetables/susceptible plants as far away as possible from remaining snail habitats and switch from sprinkler irrigation to drip irrigation to reduce humidity and moist surfaces. Snails and slugs favor seedlings and plants with succulent foliage and these plants must be vigilantly protected. A copper band can be wrapped around planting boxes, headers, and the base of susceptible plants such as orange trees citrus trees  these barriers last for several years as the mucous required for snails and slugs to travel carries an electrical charge as they pass over the copper barrier. The bands need to be cleaned occasionally with a vinegar solution.

Though baits can be part of a management program for snails and slugs, by themselves they don’t provide adequate control in gardens that contain plenty of shelter, food, and moisture, and can be harmful to humans, Dogs pets, Town Wildlife wildlife and beneficial insects. One bait that is safe for use around children, pets and other wildlife, however, is the iron phosphatebased http://www.planetnatural.com/planetnatural/images/sluggolabel.pdf Sluggo. Iron phosphate is a good choice for backyard integrated pest management programs; ingestion of the bait, even in small amounts, will cause snails and slugs to cease feeding, although it may take several days for the snails to die and this type of bait may be more effective against snails than slugs. Humans and pets would have to ingest an extremely large amount of iron phosphate before reaching toxic level... in fact, coffee caffeine has a higher toxicity. Metaldehyde baits are particularly poisonous to pets, and some are formulated with carbaryl which is toxic to soilinhabiting beneficials like ground beetles and earthworms. Metaldehyde does not kill snails and slugs directly unless they eat a substantial amount; rather, it stimulates their mucousproducing cells to overproduce in an attempt to detoxify, the cells eventually fail and the snail dies. When it is sunny or hot, they die from desiccation following poisoning... if baiting is followed by cool and wet weather, they may recover if they ingest a sublethal dose. Placing baits repeatedly in the same areas maximizes control because molluscs tend to return to food source sites. Never pile bait in mounds or clumps, especially those baits that are hazardous, because piling makes a bait attractive to pets and children. Irrigate before applying a bait to promote activity and apply the bait in the late afternoon or evening.

http://www.berkeleyhort.com/gardensuggestions/gs_mj03_gastropod.html Choice of plant can greatly affect how difficult your battle with snails and slugs will be. Some plants that are seriously damaged include basil, beans, cabbage, dahlia, delphinium, hosta, lettuce, marigolds, strawberries, and many vegetable plants. On the other hand, many plants resist damage from snails and slugs including begonias, California Golden Poppy, fuchsias, geraniums, impatiens, lantana, nasturtiums, and purple robe cup flower, and many plants with stiff leaves and highly scented foliage like lavender, rosemary, and sage. Most ornamental woody plants and ornamental grasses are also not seriously affected. If you design your landscape using plants like these, you are likely to have very limited damage from snails and slugs.

To see what other pests live in Davis, visit our Town Wildlife page.

