



Solano Paw Prints is a professional service offering daily dogs dogwalks, pet sitting and house sitting during your absence, and overnight stays. We also offer an errand service. We are reliable, honest and professional.  We have excellent references, and are insured and bonded. Please check out our detailed website under www.solanopawprints.com.  Member of PSI (Pet Sitting International). Please contact us for a Meet and Greet. Wed like to meet your pets!

We service Davis, Dixon, Vacaville and Winters.



20080107 21:40:05 nbsp A good service! Iris and her friend took care of our two cats while we were away for ten days. They were very professional and the rates were reasonable.  Users/Prof.Spice

20080125 16:07:39 nbsp We had the pleasure of using Solano Paw Prints this fall for a two week vacation.  This was the first time that we had ever used a pet sitter for our cat and the first time we left out house with someone we did not know well.  Iris was great!  I would not hesitate to recommend her to anyone.  She left the house clean, followed directions well, was always very responsive to emails, and was very professional.  I plan to use Solano Paw Prints again and again. Users/mczinn

20080322 22:38:55 nbsp Iris has a wonderful service.  She took care of my cats and fish for two weeks over Christmas vacation, and I was very pleased.  My animals were very well cared for, and I appreciated her email updates while I was away.  She even leaves a daily log of each visit, which is a tribute to her attentiveness, thoroughness, and professional service.  I will definitely call on Solano Paw Prints again! Users/artfly

20080623 15:22:00 nbsp Solano Paw Prints took great care of my guinea pigs when I was out of town. Iris left a daily log of each visit; what she did, how the animals were, etc. It was very reassuring to know that my guineas were well taken care of when I was away. We will definitely be using their service again! Users/maymay

20090422 18:14:26 nbsp Iris provides exceptional service she is very professional, thorough and kind with animals.  I had never left my dear old dog with anyone else since we had adopted her from the pound and she would get very nervous and anxious when she was young and in unfamiliar environments.   So we always stayed at dog friendly places until this past holiday when due to family needs, we needed to fly far away and I didnt want to put her thru that.  She was able to stay home in her secure environment, receive medications, and Iris took notes on how she was each visit (3 times a day) and she touched base via email to reassure me which was invaluable to our peace of mind.  We came home to find our dog happy and expecting midday walks, our house cared for and we were able to visit family without requiring them to travel all the way across the country.   Worth every penny & then some!  I would highly recommend her.   Users/Angie

20121010 21:40:38 nbsp I highly recommend Solano Paw Prints, which we used for the first time this fall.  I had many concerns about leaving our two elderly cats, both of whom require daily medications, for over two weeks, especially since we had not been on such a long vacation for many years. From my first meeting with Iris I was impressed with her professional approach, the thoroughness of her questionnaire, her reassuring and calm manner, and her interactions with our animals. I was particularly impressed with her ability to handle a difficult problem that arose at the last minute. The night before we left on our trip, our third animal (a 1 ½ foot  long bluetongued skink) managed to escape from a temporary cage while I was cleaning out his terrarium; although the cage had been in a closed room, we could not find him anywhere in the room or in the house.  I had to leave Iris with this distressing situation, and suggested she keep the room door shut, and to put out food and water in the room.  She caught a glimpse of the skink on the third day still inside the original room (but was unable to catch him before he disappeared again) and emailed me, which was tremendously reassuring.  She next asked if she could bring in a friend with expertise in reptile behavior and handling to help her look. Although they were not able to find his hiding place, he continued to eat the food she  put out.  After our return, we were able to find the skink, who appeared to be in excellent condition.  Iris also left detailed notes about the cats on her daily visits.
	In summary, I give  Iris pet sitting service the highest recommendation for her  professionalism, obvious affection for the animals she cares for, and her ability to deal with an unexpected and  difficult situation with both competence and resourcefulness.
 Users/KarenReiser
