
Heather Copeland is one of the State Farm Insurance agents in town.  Her stated mission is to help people manage the risks of everyday life, recover from the unexpected and realize their dreams.  Although the name makes it sound as though its a onewoman show, other agents work in her office.


20100131 21:57:25 nbsp Heathers great to work with.  A couple of weeks ago we had an incident in the snow on Highway 4 and needed a tow out of a ditch.  State Farm took care of the tow cost, and Steve Sottana, one of Heathers agents, took great care of us.  He had a lot of advice on how to cover ourselves from potential liability in case anyone tried to file false claims (people will sometimes look up accident reports and claim that some random accident was the cause of some injury, even though they werent anywhere near it).  They took good care of us.

Both my wifes family and mine have been with State Farm for decades, so we have really fantastic rates with themmore than $400/year cheaper just for my car (2006 CRV, nothing fancy) than Geico or All State according to their quotes.  The wifes Camry is likely similar, although I didnt get quotes on it.  You also dont need AAA (other than for member discounts) with State Farm, since theyll cover tows, locksmiths, and all that jazz.  One other thing to note, you can get a $85/yr renters insurance policy that gives you something like $20k coverage, and get a $125/yr discount on your car insurance.  Free renters insurance AND a $40 discount on your car insurance?  Well, if youre going to twist my arm... oh, and the renters insurance premiums carry over partially as a discount on homeowners insurance once you buy! Users/TomGarberson

20140121 10:13:04 nbsp My review copied from Yelp, cause who has time to write two? Heather and her team are amazing to work with, I really feel like theyre on my side.

Im writing this review about a specific experience I had. I bought a house 7 months ago and went to Heathers office to cancel my renters insurance and open a homeowners insurance plan. Everything went smoothly with the homeowners insurance, but I guess something went wrong with cancelling my renters policy. I only found this out a couple weeks ago, when I finally got around to updating my billing address with them. Heather responded saying that she noticed I had both homeowners and my renters policy running. Without even a prompt from me, she cancelled my renters insurance and opened an inquiry with her head office to track down all the money Id been incorrectly spending on my renters policy these past 7 months. I gotta tell you, Ive had to track down incorrect payments and billing amounts before for all sorts of things, and I have never encountered an office willing to do the legwork for me! I couldnt believe it! Heather assured me this morning that as soon as corporate processes her correction, Ill have a check in the mail. I didnt have to provide any extra proof or even get on the phone. Needless to say I am through the roof about Heathers customer support!

If I run into any walls getting the final check through, Ill come back to update my review, but if this is the last you see of me, you can assume my review stays at 5 stars!

tl;dr: Renters insurance didnt get cancelled and no one noticed. 7 months later, Heather noticed the error and corrected it with no help needed from me! Refund of full amount is expected after processing. Amazing customer support! Users/avbarr11
