Image(swarmcloud.jpg, A huge swarm http://www.inoculatedmind.com/?p42 shows up behind Users/KarlMogel KarlMogels apartment., 300, right, thumbnail) Each year in the spring, Honeybees honeybees rear new queens. Just before they hatch, the old queen bee will leave with a host of workers to found a new colony. This is called swarming. Honeybee swarms are a common sight in Davis, either flying through town as a cloud of bees or hanging off of a tree branch in a clump. Sometimes they can hang off a tree for several days to rest while scouts search for suitable homes.

Image(swarmdetail.jpg, The same swarm moving into the walls of an apartment., 200, left, thumbnail) Contrary to their portrayal in films, swarms are not very dangerous at all. Bees only sting to defend their colony, and their immediate life, for the reason that they die shortly after stinging animals (except for other insects). The bees are usually full of honey to help build their new colony, and since they do not yet have a home they have nothing to defend. Swarms on tree branches are safe to approach and can be easily scooped up or dropped into a hive box and taken home.
If swarms are not picked up, they could establish Feral Bees feral colonies in inconvenient locations such as backyards, barns, and houses.
 Found a Swarm? 

Call someone from the Davis Bee Collective, the City of Davis, the Fire Department, or the http://www.sacramentobeekeeping.com/ Sacramento Beekeeping Supply and a happy beekeeper will come out to collect them. If you find a swarm and are interested in keeping bees, you can always buy the equipment (startup cost is pretty high, though) and collect the bees yourself. Make sure you have a good place to keep them out of the range of ants and preferably sunny in the morning and shady in the afternoon. Image(bee swarm on tree.jpg, 200, left, thumbnail)Finding a swarm can be a great opportunity to get started in beekeeping, or instead learning about bees. If you call one of the beekeepers on the lists kept at the above locations, he/she will be more than willing to tell you all they know about bees while they collect them.

For more information, consult the http://entomology.ucdavis.edu/files/147619.pdf Bee Brief (pdf) on swarms by UC Davis http://entomology.ucdavis.edu/Faculty/Eric_C_Mussen/ Extension Apiculturist, Eric Mussen.

There is a swarm that I would estimate to be 1000 strong outside of fleet feet in a tree, I told Karl so maybe he will get someone to collect them
