 Image(Avid Reader Store Front.jpg, right, thumbnail, 350)



The Avid Reader is one of the longstanding independent Bookstores bookstores in Davis. They have a decent selection and the staff is always friendly. They are pretty much the only Davis book store to host local and touring authors for public readings. Check their http://avidreader.indiebound.com/event event web page or their Davis Enterprise ad. They also have The Avid Reader Book Club.  Free gift wrapping is available year round.

As of June 2011, http://www.davisenterprise.com/localnews/ebooksavailablenowatindependentbookstores/ Google eBooks can be purchased from The Avid Reader website, allowing one to support their local bookstore while retaining the convenience of an ebooks ebook.  According to http://www.wgntv.com/blogs/leshockvalue/wgntvwatchgooglehelpingindependentbookstoressellebooks20110725,0,1397070.story this news story, Google is offering this service to independent bookstores for free, hoping that customers will become loyal to Google eBooks.

In March 2006, owner Alzada Knickerbocker was named state http://www.nfib.com/object/IO_27321.html SmallBusiness Champion of the Year by the http://www.nfib.com National Federation of Independent Business.  The Avid Reader underwent a remodel in 2009.

Avid Reader Active opened in June of 2012, filling a space just two doors down (formerly occupied by Alphabet Moon). Avid Reader Active focuses on stocking nonfiction titles, whereas Avid Reader now deals mainly in fiction.

The Avid Reader also has a wiki:sacramento:Avid Reader at the Tower sister store in Sacramento.


This place gets a big meh from me. The selection is too small and the prices are too high.  Users/Eyaddarras

20060727 12:46:25 nbsp The Avid Reader holds awards for best bookstore, best customer service, and best independent retailer. Services include overnight special ordering (with free shipping), online ordering at www.avidreaderbooks.com, and fast searches for used, difficult to obtain, and out of print books. Teachers receive a 20% discount for classroom orders. Bookclub groups are welcome and receive a 20% discount on their bookclub selections. The store hosts its own bookclub that meets monthly and is always open to new members. Its Children’s Book Loft is a popular destination for young readers. There are signups for American Girls Bookclub meetings held regularly in the Loft. The store is recognized for a staff that is fast, friendly and knowledgeable, an extensive book selection including the best in print for the readers of Davis, strong support of local authors that includes dozens of booksignings annually, contributions to local organizations, and sponsorships of community programs.  Users/TheAvidReader

20060727 12:47:22 nbsp If they dont have what I want in stock, they can get it for me fairly fast.  They also put on the Harry Potter nights over the last few book releases.  Great community participation!  Good store to support. Users/SharlaDaly

20060823 10:37:14 nbsp Today the Sacramento Bee featured an article that quoted Alzada Knickerbocker as being opposing to the minimum wage increase. Sort of surprising seeing as I would expect the Avid Reader to pay better in Davis where the cost of living is much higher. Guess it goes to show you cant always judge a book by its cover. Users/EnirytManaen

20070516 04:41:58 nbsp Interesting to read the comment above  I believe it.  I went for a job interview once and met the owner.  She appeared to be quite full of herself and kept focusing on how everyone tells her how great her bookstore was instead of doing my interview.  Anyhow I ended with a better job offer elsewhere, but...ugh...youre better off going to any other of the many bookstores in Davis since this one has a lousy selection and is way overpriced. Users/christinegallo

20070524 16:00:44 nbsp They have copies of my dads book for sale!   <3 Users/StevenDaubert

20071214 00:11:34 nbsp Im glad we still have an independent bookstore downtown, but I wish I could be more enthusiastic about this one. One of my biggest gripes is the dog upstairs. Why is a dog that is freaked out by children kept right next to the childrens section? They would sell more books if they found another daytime accommodation for this poor dog. I take my childrens book business to Bordersits bigger, cheaper, and my children can go to the kids section without being scared out of their wits. Im no doghater. (Pomegranate, the hair place on F St., has a lovely, lovely dog who belongs to the owners.) This is one instance of the sort of lack of sense about customer needs that eventually leads to loss of business & business closure, which then gets blamed (unfairly, IMHO) on Borders and Amazon. I wish someone who really loved both books & people would open a bookstore here! Users/PrimulaBaggins

20071214 22:28:19 nbsp Best selection of books in Davis. Excellent staff and their special order system is fast and efficient. Many books by local authors. Lots of great calendars around the holidays, good map selection. They have normal retail pricing, discounts on some books and a shopper card you can use to save money.
BTW, every time Ive been in the store, which is many, many times over the years, the dog has been confined behind the child gate upstairs, and is usually curled up in her corner or in her carrier. The owner is very active in downtown events and is a big supporter of local community groups.  Users/DonShor

20081008 14:31:12 nbsp I need to update that picture with one where cars arent blocking the front tables... Users/SunjeetBaadkar

20090701 15:25:26 nbsp Its a little bit surprising, since the store is physically much smaller, but the variety of books offered by Avid is probably comparable to that of Borders.  Borders shelves are (increasingly) occupied by empty space, books on display sideways, and signs telling you to look at other books.  Avids shelves are densely packed with one of just about everything.  While Im sure they dont have the diversity of Amazon, Ive been in there on a number of occasions, and always found what what I was looking for.  Highly recommended.

One concern though  I think I mentioned this on the Borders page as well at one point  it is becoming increasingly difficult to find novels in trade paperback format.  Books that should cost $7 or so cost $16 or more, and dont seem to be available in less expensive formats.  At those prices, it often feels like a better choice to try to find books at the library, to exchange books with friends, or to seek other alternatives (including Amazon, which is often somewhat cheaper).  Id rather support my local bookstores if I can, but if prices continue to increase, that may not be an option. Users/IDoNotExist
   Go to Sweet Briar Books over on G Street in East Davis; plenty of packed shelves, no gimmicks. Users/BrianJKenyon
    What gimmicks do we have, if you dont mind me asking?  Users/SunjeetBaadkar
    Answer, in two words: author selection: compared to Sweet Briar: relatively uneclectic. Their secondhand/remainder shelf contents built to different dimensions though, of course...Users/BrianJKenyon
     Well, The Avid Reader literally consists of the staff that you see at the top of the page and has stayed static for quite a while now (at least a couple years).  The inventory manager does most of the ordering, but all the employees order for the store as well.  We basically control the stores inventory as a group and decide what we want (and yes, we order some random things on whim because we feel like it should be here even if it doesnt sell) individually or as a group.  We also take customer recommendations into consideration when someone walks in and says we should order a book for the store to carry.  So if there is every anything that you think we should have, definitely come on by and wed be willing to hear what you have to say. Users/SunjeetBaadkar

20090720 01:01:50 nbsp What kind of renovations are being performed?  It looked like some pretty extensive changes were being made when I biked by. Users/IDoNotExist

20090731 10:54:07 nbsp Well, for the most part, the changes are done, but there are still a few more things happening.  Over the last two weeks, we have added wheels to all the bookshelves so we can move them around on whim, changed the carpets, repainted the walls, redid the tile in the front of the store (inside and out), refinished the wooden surfaces, redid the staircase that leads to the kids loft and have been doing minor changes to the store arrangement overall.  Suffice to say, me and the other employees are physically tired, but there are still more changes to come.  Come on by and check it out. Users/SunjeetBaadkar
   Is the community bulletin board going back up in the display window when the paint dries? Users/BrianJKenyon
     Yes, it will be back up, but were still not sure when.  Were trying to decide on the current positioning of everything in the store and probably wont be doing anything for a couple weeks.  Were toying with the idea of putting up a much larger bulletin board in the back hallway so that there isnt as much fighting over space.  Also, if we do that and put one up front, wed end up having the front reserved for downtown events and nonprofit events only.  But since wed have to punch holes in the wall to mount these things, were not doing it until were set on an idea. Users/SunjeetBaadkar

20090829 22:03:03 nbsp I love the Avid Reader.  The selection is excellent, the atmosphere inviting and relaxing, the staff are excellent, and they are involved in and supportive of the local community.  Where else can you go that the staff keep you in mind when new books come in that you might be interested in and let you know?  Definitely one of my very favorite places in Davis. Users/davisdebbie

20090904 20:45:06 nbsp The bulletin board is back up!  To accommodate the demand, weve more than doubled the size of it and moved it to the back hallway since that area gets more foot traffic than the front corner did.  Please tell the employees before posting something so that it is guaranteed to stay up (as things just randomly posted may be pulled down). Users/SunjeetBaadkar

20100414 08:50:05 nbsp I do not recommend this store to parents with small children.  I tried to take my young children upstairs to the kids section.  Unfortunately, the owner keeps a large, aggressive dog in an area upstairs right next to the kids section.  The dog lunged, snapped and growled at my kids and left them crying and cowering.  When I inquired with the people that work there they reacted with indifference.  I havent been back since.   Users/sys$hobbit

  I would like to apologize for this incident and the lack of action. We, at the Avid Reader, try to keep our customers happy in all ways possible. The owners dog (a foxhound) was in an accident years ago and has been a bit finicky when left alone upstairs. We have been trying to adjust her behavior but when customers stare at her, she gets nervous and reverts to a protective stance. Unfortunately, simply removing her from this store would not help her in anyway since she has to get used to this. She has been getting better in her behavior over the years and has never once bit anyone but sometimes we falter in our ability to control her. I invite you to come back and give us a second chance. We could introduce the dog to you and your children so that she would later recognize you if you would like. Users/SunjeetBaadkar, Store Publicist

20100629 11:48:20 nbsp That dog scared once when I was getting a book upstairs. I was terrified, but the book select at the Avid Reader is pretty good and it is a local buisness so you know money spent there will go back to the community.  Users/BryceH

20110510 09:55:45 nbsp I dont know about the traumatized dog, but I do know that I was in the store once and overheard the owner talking loudly on the phone about the necessity of sending more donations to Michelle Bachmann (yes, that Michelle the census is a communist plot and we have a communist president and the activist judges are turning our children into homosexual muslims Bachmann). Ill admit that since then Ive been torn between wanting my consumer dollars to stay in Davis and wanting my consumer dollars to stay out of the Tea Party coffers. Users/Swilltopower

20110521 22:31:26 nbsp I adore the selection of books at the Avid Reader. I thoroughly enjoying browsing in the peaceful environment in the middle of a crazy day. Users/JennyAnnMcAllister

20110528 15:59:55 nbsp Its kind of a cool little store, seems to have a decent selection. Only thing is I am a college student and cant afford to pay list price for books right now, so I like to browse the store, then buy the books on Amazon. I would love to support a local business, provided the owner doesnt contribute money to Michelle Bachmann, as another reviewer stated  perhaps when I grow up and get a job.  Users/stevohfun

20110713 10:12:45 nbsp I love the Avid Reader and always prefer it to chain bookstores. The staff is nice and I always like the selection of books they put right in the front of the store because it has a variety of genres I wouldnt normally look at. I have bought and enjoyed several of these random books. If you ask for suggestions the staff is helpful. Support local business and go to the Avid Reader! Users/LenaSchiffer

20111229 15:34:25 nbsp F avid reader, I told them a year ago to have a copy of this book the day it was released (when they didnt have a copy of the 2nd in the trilogy the day it was released) and they didnt have it they can get it by Wed... Great thanks Users/StevenDaubert

20120123 17:45:00 nbsp It seems like a nice store.  The store had the series of books I was looking for but not the actual books in the series I needed.  I will probably give it another try if I need other books in the future. Users/LoriOrf

20120703 10:40:00 nbsp Re: earlier comments about the owner supporting Michelle Bachmann, a quick internet search reveals that she is a significant donor to the Republican Party.  See http://fundrace.huffingtonpost.com/neighbors.php?typename&lnameKnickerbocker.

20130624 20:09:31 nbsp I like the selection of books at both of the Avid Reader Bookstores however, I have not found the staff there to be particularly friendly.  I have bought books on numerous occasions and I am amazed at how unfriendly the cashiers are.  They seem annoyed to be disturbed from whatever it is they are doing to ring up a sale.  Now mind you I am not intentionally interrupting them.  I always wait until the Cashier asks if I am ready.  Given the number of independent bookstores that have gone out of business over the year you would think the staff would be trained to be friendlier.  Not that I expect to be buddies with the Cashier but I would prefer to be treated with the same level of politeness that should be given a stranger. Users/DebbieONeill
