
The Lofts is a mixeduse building that includes street level retail with business offices on the second floor, and apartments on the third floor. All of the apartments are zoned as commercial and residential space. The apartments are lofts, each with one and a half bathrooms, an upstairs bedroom area, a kitchen area, and a small balcony. They have wood floors, washer/dryer, and all appliances. The rent is $1595/mo. ($1475$1640 in 2013) The Lofts building is located in downtown downtown Davis, next to John Natsoulas Art Gallery. Thai Canteen and Sugar Daddies are current retail establishments. It is one of the newer apartment complexes in Davis and was designed by http://www.berteauxarchitects.com/ Berteaux Architectural Collaborative headed by Richard Berteaux and built (and still managed) by Pyramid Construction. The building features a Mobile Phones cellular Telephones phone Cell Phone Towers site.

This used to be the site of a KFC.




 Tenants 
  Thai Canteen
  Joy Policar, Ph.D.

 Pictures 


Pictures from 2013 Listing on chl.ucdavis.edu



20110428 23:10:18 nbsp These Lofts are very nice, with one fatal flaw.  There is a bar downstairs called Sophias Kitchen which has live music on Thursday, Friday and Saturday nights (sometimes Wednesday nights).  The music is loud enough that it makes the walls shake!  These lofts are quite expensive to rent for the area, hence I assume the development is geared toward working professionals and not students.  Well be leaving as soon as possible, as it is virtually impossible to get any sleep on the nights with live music.  I would not recommend this place to anyone on a 95 schedule.   Users/ZeeZee

20110802 12:05:22 nbsp Yes, there was a noise problem with the live music. The good news is that Kevin, Sophias manager, was very cooperative  and has reduced the sound level dramatically. He changed types of bands he books and they finish their shows much earlier. Everyone living on the third floor reports that the problem is fixed. Thanks Kevin and Sophias. Living downtown isnt for everyone, but those who make it home love the vibrancy it offers. Chuck and Caren  The Lofts Management. Users/chuckroe

20111014 10:01:05 nbsp Are any units available for either rent or purchase?  I havent had a chance to research it, but I have been wanting to rent or own one of these spaces for, literally, years.

Id be interested in learning more . . .Ill try calling when I find my cell phone.  Thanks for the post! Users/AshleyHamidi


20120803 11:06:01 nbsp In concurrence with the previous review, the Lofts are beautiful but have many flaws – in my opinion, many more than one. When looking for a place to live, the Lofts were “sold” to me as a very mature and quiet place to live. I was swayed by the beautiful apartments and amenities – hardwood floors, washer and dryer, dishwasher, parking spot  oh my! Yes, all those things are wonderful, but at the Lofts, the cons outweigh the pros. Lets begin.
Sophia’s Kitchen is loud. Beyond loud. Every Thursday, Friday, and Saturday night they had bands play you would hear pounding bass, singing, and cheering up until 1am. There is also the fraternity house right next door  you can see into their windows from deck. I was told by the management, Caren, they were very nice and would alert the tenants of the Lofts when they had parties. They only did this once. And they partied almost every night of the week, and even louder during the weekends. I was forced to call the cops nearly on a weekly basis for noise complaints because it was too loud to sleep. I got tired of hearing chug chug chug! at two in the morning.
When I first moved in, the management was ripping out the deck in the courtyard. For two or three months all I heard was construction from morning until evening and the construction even kept me in/out of my apartment for hours because of them paving cement outside my door. When this situation was going to keep me inside and not able to leave my apartment to get to class, I voiced my concerns to Caren, who told me in an email I cant promise youll be able to leave apartment after 8am. Maybe get to school early and grab some coffee or breakfast.
As the weather got nicer, the courtyard became become a hangout for random teenagers and drunk college students at night, who don’t realize the third floor of the Lofts was an apartment complex  a private property sign would have been nice.
As well, the design of the apartments are extremely strange – such as ridiculously tiny bathrooms with literally no counter, and no closet space (I built my own closet). The high, unreachable wall windows (which under contract, you are not allowed to physically cover) would make it impossible for sleeping in past sunrise. With the help of my father, we built and installed curtains that hung from the ceiling at monetary expense on our end. The upstairs (bedroom) was always hot and muggy, with no air flow and I always had to leave the window open every night with two fans, otherwise I felt like I was going to suffocate up there!
Often I never even received an email response from Caren when I voiced my concerns. For example, at six am one morning, I woke up to the sound of a leaf blower. No, not on the street, right outside my bedroom window in the Lofts courtyard. Mind you, the courtyard is a square of concrete with no foliage  a broom would have sufficed for the three leaves that needed to be clean away. There was no response to my email to Caren about this  I was not mad at the time, just confused. I then later found out that noise at six am broke the City of Davis Sound Ordinance Codes. The next time the leaf blower came was at seven, the very, very earliest one can make noise in the City of Davis. The leaf blower, who was hired and under the direction of Caren (not the City of Davis!), continued to come three times a week at seven am for the remainder of my time living there.
I wanted to take the chance to warn those who are interested in living in the Lofts. PLEASE do not make the mistake I did. I was taken in by the beauty and proposed “maturity” of the complex and found nothing of the sort. I would not feel this strongly if Caren had made the effort to even try and meet me halfway with the unfortunate construction (go get breakfast), the leaf blower (no response at all), and disrespectful neighbors (would not even take me seriously). Caren seemed to have a personal favoritism over the tenants and it was apparent to me she did not hold my comfort or happiness at The Lofts in any high regard. For the price, you are definitely getting ripped off. There are MUCH larger, nicer apartment complexes in Davis with better management, staff, and amenities, with lower rents, such as the Arbors. The only positive experience was the owner of The Lofts, Chuck  he was great and very nice, but unfortunately he was not the person I dealt with on a daily basis, Caren was. The Lofts could really improve in the future under a new property manager. Users/hypertheticals

20120827 13:57:21 nbsp I do not regret my decision to move into the The Lofts a year ago at all.  Indeed, I like it so much here I have renewed my lease for another year. I have 2 young kids and we are never at a loss of fun things to do living in the heart of downtown.
Caren, the property manager, is very responsive, friendly and fair. I hope she is here as long as I am. The plaza outside my unit is filled with plants and is well taken care of. The 3rd floor courtyard was resurfaced earlier this year and I was surprised it only took two weeks to complete the job. The new surface is a real upgrade and well worth the effort. The contractor worked with all the tenants and I was only inconvenienced for one day. That’s pretty amazing considering they were resurfacing right up to my front door. Living downtown is different than the suburbs but that is why I’m here. I haven’t noticed much noise beyond what you’d expect in a vibrant urban setting. I really wanted to be in an active place with restaurants, theaters, etc. I also appreciate the video surveillance cameras. The property manager has done an excellent job discouraging unwanted visitors with no business on the property.
If you want to live downtown and don’t want yard maintenance or an apartment complex, this is a good choice.
 Users/MichaelBisch
