Nancy Abplanalp (OppLinopp), working under the name Thinking Dogs, is a local professional Dog Trainers dog trainer in Davis that provides owners with the necessary training tools for a well behaved dog. She loves what she does and is extremely good at it. She is patient, kind and understanding of owners and dogs needs. Her training is centered around positive reinforcement and clicker training. Her classes are usually on Sundays and Mondays at the various parks and schools of Davis. In addition to dog training Nancy does in home consultations and presentations. She is an active member with the Yolo County SPCA and highly involved with The Road Home K9 Rescue in which she fosters dogs and helps adopt them out. Her positive attitude and combined experience make her a valuable member of the Davis Dog Community. Her classes challenge dogs to think outside the box in real life situations. She offers four different classes depending on the age of the dog. Current class levels include a Puppy Class (two to six months old), Graduate Puppy class (six to eighteen months  Sunday only!), and a Life Skills/Adolescents class. Nancy has a yahoo group in which behavioral questions and concerns are addressed. Every class is structured and class information is posted on the yahoo group site. Some of the skills dogs learn include loose leash walking, sit, stand, downstay, targeting, and training for the Canine Good Citizen Test.

Nancy also offers classes on Nose Work with Lisa Voss and Tracey Louper, fellow dog trainers. Nose work classes are ten weeks long and three kinds are offered: beginning nose work, beginning odor, and dropin continuing. The Thinking Dogs group via Yahoo also coordinates Rally Classes taught by Lisa Voss, open to dogs who already have basic obedience skills such as heel, sit, down and stand.

Nancys Philosophy

  I teach dog training classes and I teach them with one one overriding goal. I want to save dogs’ lives. I use my education, talents, and skills to help humans look at dogs, not as the dominanceseeking, vindictive creatures from outdated ideas carried into the twentyfirst century. Instead, I work hard to give the most current scientific information we have on dogs  how they learn, think, communicate. With that knowledge, owners can deal with the reality of the dog that they live with.

  Dogs closely align themselves with us, but that does not make them human. They are see the world through the eyes of a dog, which makes them opportunistic, impulsive, and often with a set of hardwired behaviors that we find offensive  digging, barking, scratching, jumping up, and pottying on soft, absorbent surfaces immediately come to mind.

Nancys Students


20090310 12:03:42 nbsp Nancys classes are GREAT!  A friend of mine recommended her and I was very pleased, and so was my dog!  I liked that classes changed location every week, so my dog learned to be good all over Davis, not just in one special room.  The distraction of being outdoors and in a new location was great for training.  Nancy uses positive training methods that make class fun and effective.   Users/LauraBruno

20090310 13:38:37 nbsp Nancy has AWESOME classes! I really believe she sticks to her philosophy and helps you create a dog that is a well behaved member of this society. She has helped me work through a few issues that I had with my puppy as well. I just wish my work schedule wasnt so hectic so I could go more frequently! She truly helps you comprehend how to understand and think like your dog. Finding a successful training method for you both. The field trips are awesome and gives you a chance to apply what you learn in a controlled class environment to the real world! I got more out of one class with her then I had in a 6 week class with a previous trainer a few years back with my previous dog.  Users/TailsOnTrails

20090525 08:41:46 nbsp Nancy is a wonderful dog trainer who really understands dogs. She has four dogs of her own and often fosters dogs. She is active at the Animal Shelter and assists with behavior assessments. As owner of Elizabeths Pet Sitting I first started attending Nancys classes with one of my clients as a helper/ intern and every class I take away something new that I can help my pet sitting clients and their dogs with. Nancy really makes the dogs think. In her classes ,dogs will not only learn basic commands ,but life skills. She borrows concepts from other trainers and is well versed in the dog training community. Some of the things you can expect your dog to learn in her classes include: Handling and socialization for puppies, classical conditioning, loose lead walking, down, stay. stand, teaching a dog that its ok to be hugged or petted by a stranger, settle, downstay,300 peck, penalty yards, rally,Canine Good Citizen Test and much more. Nancy places dogs in real life situations in class and answers every question an owner might have. She is patient and kind, and understanding. She also works with kids in the summer through the city for a kid summer dog training class. Every class is unique and well thought out. I would highly recommend her classes to anyone with any age dog because its never to early or late to exercise a dogs mind.  Users/ElizabethBarthel

20091010 11:42:05 nbsp We took classes with Nancy for the first few months after adopting our 3month old terrier mix.  Nancy is a really great teacher, not only wonderful with the dogs but also with their people (not all dog trainers have human social skills to match!)  I have been able to continuously apply what we learned in Nancys classes as our dog grows  she is now 2 years old.  Nancy maintains a list serve for current & former clients that is incredibly informative about all kinds of dogrelated issues, from training questions to questions about recommended food, toys, etc as well as connections with her work training & placing dogs that need a home.  I would most enthusiastically recommend Nancys classes to anyone looking for training for a new dog or teaching an old dog new tricks!  Her approach to classes is also very convenient for anyone who might have trouble making every one of a class series, which is how most (if not all?) other trainers in Davis operate. Users/Dora5

20110501 23:50:45 nbsp Nancy has helped me completely change the way I think about dogs and dog training. As a new owner of a challenging dog, Ive been working with Nancy for a little under a year with fantastic results. While my dog is far from perfect, Ive come to understand and practice the method of working with my dog to have her behave the way I want by making her think her way there. Its helped me become a better dog owner as well as helped my dog be a better behaved pup. I would recommend Nancy wholeheartedly to any dog owner. Users/ChristyMarsden

20121120 10:08:45 nbsp Hi Nancy! Users/StevenDaubert
