
From Spring 2001 to Winter 2002 Tiqula Bledsoe was the ASUCD President and ran as a member of the LEAD Slate slate. Before he was president, he was an ASUCD Senate ASUCD senator.

The election that lead to him taking office was even more dramatic than usual for the time. Opponents got his slate disqualified for violating election codes in their campaign, such as spending too much money and posting large fliers. However, after playing the race card (including Bledsoe or a supporter posting fake KKK fliers on campus), the ASUCD Court reversed their decision amidst massive pressure from various ethnic minority groups on campus.

He called himself the Black Caesar of ASUCD.  This, of course, led to some controversy, including some of the hate that the LEAD slate received. Also, this reference caused problems for the California Aggie when they referenced him in their endoftheyear The California Aggie: Spoof edition spoof edition. During his presidential term Bledsoe revoked the authority of the ASUCD Court in 2001.  Later in 2005 the California Aggie featured an http://media.www.californiaaggie.com/media/storage/paper981/news/2005/01/20/Opinion/Editorial.Past.Elections.Problems.Addressed.In.Bills1319260.shtml editorial in support of Senate Bill #6 to revive the ASUCD Court Courts powers. In 2004, Bledsoe http://media.www.californiaaggie.com/media/storage/paper981/news/2004/10/05/Opinion/Uc.More.Segregated.Than.University.Of.Mississippi1318232.shtm wrote a letter to the California Aggie stating that the UC System was more segregated than the http://www.olemiss.edu/ University of Mississippi. Bledsoe was then http://media.www.californiaaggie.com/media/storage/paper981/news/2004/10/07/Opinion/Letters.To.The.Editor1318279.shtml commented on concerning the subject in a letter to the California Aggie editor.

Tiqula Bledsoe however http://www.yolocounty.org/org/bos/agendas/2002/032602/06.pdf received praise from the Yolo County supervisors and State Assemblywoman Lois Wolk in a resolution signed on March 16, 2002.  As ASUCD President, Bledsoe http://www.democraticunderground.com/cgibin/duforum/duboard.cgi?azshow_thread&om1349&forumDCForumID43&archiveyes opposed the Pledge Bill of 2001.

As an ordained minister in the Church of God and Christ, Bledsoe was also routinely called Reverend Tiqula Bledsoe, and jokingly referred to himself by numerous additional ego maniacal nicknames, such as the Mohamed Ali of ASUCD, and even half man, half amazing.

He left the office of ASUCD President with an unusually high debt in his allocated budget, causing ASUCD to have to do some juggling to survive the rest of the fiscal year. It also came to light after he left office that he had attempted to use ASUCD funds for his personal limo to the Presidents Ball (putting on a ball isnt exactly a normal ASUCD activity either, and in this case it ran a huge debt whereas it was supposed to break even), and to pay for parking tickets hed incurred in the state capitol, among other things. Mark Champagne prevented this money from actually being spent  fortunately for all students who are not Tiqula Bledsoe.

After graduating from UC Davis, Tiqula Bledsoe became the Sustainable Development and Fair Growth Fellow at wiki:wikipedia:Greenlining_Institute The Greenlining Institute. Afterwards, he became the Executive Manager of the California State Conference of the http://www.naacp.org/ NAACP. He also went on to earn an Executive wiki:MBA from California State University, Sacramento. In 2005, he became the Executive Vice President of http://www.deebabys.com/ Dee Babys Realty.

His given name is pronounced taiKYUla, if anyone was wondering.

