
Torch of India, or as the Dixon location is called, Punjabi Dhaba, has great Indian food.  The downtown Vacaville location is a bit of a hole in the wall, so you really have to be looking for it to find it, but its well worth the effort! The dishes are presented very well, and the two managers are superfriendly, and go above and beyond to make sure the diners are well taken care of.  The wiki:dixon:Torch of India Dixon location is also fantastic. Its worth a stop if youre heading to or from the Bay Area, and its just a little farther down I80 if youre at Pedrick Produce.  You wont be able to miss the signs from I80. Unlike its Vacaville counterpart, this one has a dinner buffet.  Its usually not very crowded, and the buffet is delicious.

The naan are to die for, fluffy and hot like they should be  try the garlic naan. sads Id also recommend the chicken tikka masala, the chicken kabobs, and the tandoori prawns. Items ordered off the menu are better than the buffet, although the buffet changes almost daily and is well worth the price.

The Dixon location is one of the few Restaurants within about 10 miles of Davis that has coupons available on Restaurant.com.  They all have limitations (e.g. $35 minimum purchase to use the $25 coupon, $100 minimum purchase to use the $50 coupon; dinein only, dinner only, not valid for buffet), but theyre a pretty sweet deal.  If you look around online, you can always find at least a 60% off coupon for Restaurant.com, and sometimes there are 80% off coupons.  Thus, you end up paying $24 for a $25 coupon you can use toward a $35 purchase.  Not bad, eh?


20080419 19:05:07 nbsp The Torch of India recently opened a second restaurant in Dixon near the I80/A St. exit.  The owners obviously invested a lot of money in the decor, which features impressive Indian art on the walls and ornate furniture.  They only offer a small buffet, but perhaps the menu will expand as they attract more customers.  The food was tastey and not too spicey, and included a some very good lamb curry, tantori chicken and another chicken dish in a red sauce that I dont know the name of.  There were also the usual vegetable and rice dishes, cauliflower, lentils, yogurt and other sausces, etc.all good.  They also offer warm chai tea with the buffet, which is a nice touch. Oh, and plain and garlic naan comes with the mealvery yummy.  Dinner is $10/person. Users/PeteBasofin

20080530 21:25:00 nbsp Just ate at the new Dixon location tonight.  Ive had food from the Vacaville location previously.  They now have a choice between ordering from the menu or buffet ($12.95/person).  We chose the latter since it had items we wouldve probably ordered anyway.  The food was really good.  The best part was the fresh naan.  Each basket of naan we received was hot out of the tandoor.  The service was excellent.  Anyway, its worth the 10 min or so drive to Dixon to check this place out!   Users/aggie4life

20080824 01:51:02 nbsp I love the buffet at the Dixon location. I am not sure if the two are owned by the same people though. I called the Vacaville location to get the phone # to Dixon and was told they were not affiliated.  Users/AprilAries

20081109 18:02:31 nbsp Go to the Dixon location. The food is decent, the service is sweet, they play music videos on the satellite TV, and they still have the chairs from the Mexican seafood restaurant that used to inhabit the space. Eggplant is twice as delicious when youre sitting in a leatherandrattan chair decorated with an octopus. Users/MaggieSherriffs

20090422 18:33:14 nbsp torch of india is the best indian food in this area, including all of sacramento, let me tell you. everyone in davis HAS TO go there if they love indian food. sometimes i wish the torch of india people would move to davis instead of being out in crappy dixon. torch of indias food compares favorably to some of the best places in san jose, which is where i come from, and which has many, many good indian places Users/boing3887

20090501 10:51:22 nbsp Dixon location has an updated menu now. One can also order the vegetable entrees ranging from around $10 to be served as side dishes for $6.  Users/13urningMonk

20100210 22:23:22 nbsp Torch of India is alright but probably not worth a 20minute drive from Davis. Its a tiny holein thewall. The last time I was there a few months ago I believe the lunch buffet was about $9 a person. The food was ok; it was mostly the traditional choices. Some of it was a little dry, and the desserts were kind of odd. In Vacaville this is the only Indian food option, but Id be surprised if theres not an Indian place thats comparable if not better in Davis. Users/bear

20130911 14:25:29 nbsp The Punjabi Dhaba in Dixon has been our favorite Indian restaurant for the past two years!  We have never ordered anything off the menu.  We just come in and eat the buffet.  Lunch buffet is 11:00A3:00P, $8.95, and dinner buffet is FridaySunday 5:00P9:00P, $12.95.  We will plan our whole day around eating here and we drive to Dixon from Davis at least once every other month.  We usually try to combine it with something else, but the only thing going on in Dixon is the Walmart (and once a year, the PinAGoGo).  We often stagger around the Dixon Walmart with our bellies full of Punjabi Dhabab.  So good!  Everything is good.  They have some rotating items in the buffet, so its not always the same.  We never get tired of it.  We try to eat at every Indian buffet we can find (even the Torch of Indias in Vacaville and Santa Rosa) and so far nothing has beat Punjabi Dhaba in Dixon!  Yes, the chairs still say bienvenidos from when it was a Mexican place, but everything is clean and in good shape.  There is a full bar and multiple TVs playing Indian music videos or Bollywood movies.  Its a fine dining experience with attentive wait staff, glass goblets, and cloth napkins.  GoogleMaps claims it is only 11 minutes from La Rue/Hutchison to Punjabi Dhaba.  Go there now! Users/JSilva
