
Twin Pines is a 36unit affordable apartments housing complex offering one and threebedroom apartments and twobedroom townhomes. All units include washer/dryers, and gas stoves. With a community room for resident functions, a monthly Resident Council Meeting and Neighborhood Watch Program, Twin Pines is a communityoriented, mixed community with residents from all age groups and backgrounds. Qualifying criteria for residency at Twin Pines is incomebased and applications are welcome year round.

Twin Pines was built on citydedicated land; State HOME funds, city housing funds, and redevelopment funds were all used to finance the construction of this community.

To learn more about rental housing in Davis, check out our Rental Housing Guide as well as our Apartments pages.


20120804 17:43:56 nbsp good! Users/firen2001

20121025 22:34:53 nbsp I would not recommend this place to anyone unless it was for a financial necessity. The Manager runs hot and cold depending on whether or not she needs something from you. Everyone not only knows your business, they feel obligated to be up in it as community involvement is a requirement here. There are several apartment lifers who let their children run wild. Several of my neighbors have been the victims of verbal abuse, property vandalism, keyed cars, and theft yet management does nothing about and the police hands are tied. At night you can hear your neighbors snore not to mention the lady screaming at her kids. The rent is not that much cheaper than a unit downtown and definitely not worth the headache. There is a small pool on site monopolized by several units with their kids running wild, failing to look for others before jumping in or splashing, and the real show comes when they jump from the fence into the pool. You have to be careful driving through the parking lot, it is not uncommon for small children to run in front of your moving car. There is a large tv in the community room that does not work, the chairs that are not broken have been puked on and not cleaned thuroughly, the printer is out of ink when you need it, and if you reserve the community room on the public board others feel free to replace themselves in the slot. There are units being treated for bedbugs. A couple folks are good people, the principal of the mutual housing is awesome but not implemented properly here. The maintenance is on point and finally the location is cool. Good luck to the next tenants! Users/NetworkVirus
