



20070925 16:45:10 nbsp Howdy, Tyler, and Welcome to the Wiki.  You seemed to be looking for a way to post the image, so I gave you a bit of a start.  You can edit your entry some more by clicking Edit at the top of the page.  Go ahead and ask any questions you might have, or read through the wiki:wikispot:Help with Editing pages. Users/JabberWokky

20071026 13:15:30 nbsp Hi Tyler,
I saw your comment after mine on Spa Centrals page and I just wanted you to know, I appreciate your not mud slinging and I wanted to tell you some of the facts.  The facts are that the owner of the spa in question really was horrible to me.  When I first started there the first month was great.  But then they started over scheduling me, repeatedly, cutting into my time to pump milk for my then infant daughter, and then docking my pay for starting my clients late because I had to pump.  That began a pattern of abuse by the owner that contimued until finally I was seriously hurt on the job and I was refused treatment by the owner until I had to take legal action.  I couldnt just leave my job the spa because I had established a clientelle and I am a single mom who has to support her kid.  After I was hurt, I found out she didnt have insurance because she gave me fraudulant information.  She knew she had to have insurance because she had called the company whose name she gave me to make a claim and they told me she didnt have insurance, but they had given her a quote six months prior and she had not followed thru.  My comment about her BMW is not out of jealousy, I dont care about cars, I ride a bike everywhere, its meant to point out that she chose to buy a BMW instead of get insurance.  I have since gotten my own business lisense here in Davis and the application says in bold caps, YOU MUST HAVE WORKERS COMP INSURANCE.  She knew, she just didnt care.  She was abusive and mean and I could give you a dozen examples but Im starting to go on and probably bore you.  Im not a mean person, I was trying to be honest about a place I was treated badly, me and several other employees.  I just have a big mouth.  I take my job as a healer very seriously, I consider it a privilage to work on my clients and I want people to know what theyre supporting when they spend their money.  Thanks for reading my comments and I hope I could shed light on my situation.  The owner is no victim, and I dont consider myself one, either.
Many Blessings,
Elisa Users/ElisaWeller
