


The UCD Address(Equestrian Center, 38.528183023603, 121.766977986457) had some wonderful changes and upgrades in fall 2007. The center installed new gravel throughout the property along with proper grading and drainage installation. The enormous indoor arena is finally up and running. The 3 barns (Cypress, Sycamore and Poplar) have all been renovated and include individual tack lockers. There are also 2 new paddocks and new shelters in all the paddocks.

They are set up for boarding as well as lessons. The UCD Equestrian center is directly across the street from the School Of Veterinary Medicine Large Animal Clinic, and UCD VMTH Farrier Shop.  If your horse requires frequent vet care or specialized horseshoeing this may be a factor in your choice of where to board a horse.

The fencing is mostly brand new corragated steel corral pipe fencing. Its location is between 113 and I80 as they meet. It can be scary for a new horse because trucks go by on the freeway just 30 feet from the arena, but most horse become accustomed to it quickly. There is a waiting list to board your horse in a stall or pasture and if you want a spot, plan to be on the waitlist in advance. Due to a very recent policy change only registered students, not staff, faculty or alumni (unless they are current registered students) are allowed to board a horse at the equestrian center.

There are two outdoor fenced arenas and a huge new 4.4 million dollar indoor arena with lights, opened fall 2007, a dressage arena (new footing Nov 2006, drains well), three round pens (2 with corral fencing and one braqnd new one with high wood walls, and a large grass riding field with a riding track around it.  There are cross country fences set up on the field and include hanging logs, different size ditches, a log cabin jump, multiple coups, and a up/down bank. The indoor arena and the large back arena are well lit for night time riding. There are three restrooms, one permanent one attached to the main barn, and a semi trailer with mens and womens stalls. There is also a large wash rack that has hot and cold water! The last of the old facilities (the old pipe stalls and pasture with white fencing) is still yet to be renovated. Options for the use of the new space are more turnouts, another arena, or possibly another barn.

If you are leaving for the holidays or just have too many projects due, go into the office for help. The EQC offers services like turn outs, hand walking, lungeing, and medical services (if your horse needs medication or to be wrapped daily). The staff is very friendly and well trained. Currently there is four residents that live full time on the property to take care of the horses and several other staff members.

The hours of operation are 8 am to 8 pm everyday except some holidays when the center closes for a few hours in the middle of the day. The office hours are 85 MF.

Boarding Options


These prices are for Fall 2010
   Pasture boarding  $250/month, feed and cleaning included.
   Barn Stall $415/month, feed, shavings and cleaning included.

Each barn is brand new and includes corner hay racks and automatic waterers. There are different options for barn stalls. Sycamore has all inside stalls and the barn ailse is concrete. Like all of the barn stalls, they are separeted in the middle by a wood pole to keep shavings in the front. Cypress and Poplar offer in and out stalls with middle sliding doors to keep horses inside; the barn aisles are of rubber matting. All stalls have sliding doors.

The Equestrian Center also offers riding lessons. The horses are all donated, so their abilities vary. The instructors are all UC Davis students, but theyre always very experienced. Really, its a great deal for the beginning rider. Lessons typically meet once a week for four week sessions. There are two different lessons, Introduction To Riding and Riding 101. Intro to riding is a great lesson for those who do not have much experience with horses. Lessonees are taught how to groom, tackup, and ride at a walk/jog. In Riding 101, lessonees learn further information about tack and horse care, and practice their skills at the jog/trot. Keep a ear open for private lessons being offered. Because of the budget cuts, the private lesson program was cut, but during breaks, private lessons will be offered. You can sign up for lessons online or come by in the office.

The Equestrian Center operates an affordable, extensive yearround program in English and Western riding, beginning through advanced levels. Offers successive, weeklong summer camps for kids that include riding and games. There are four intercollegiate teams, Western, Eventing, Hunter/Jumper and Dressage. These teams are coached by experienced trainers and compete against other schools like Cal Poly San Luis Obispo and Stanford. The dressage and Hunter/JUmper teams use the UCD horses for their lessons and competitions. The western team uses a mix of the schools horses and the coaches horses, and to be on the event team you must own a horse. These teams require yearly dues and vary between teams. Call, email, or come by for more information.

Group Lessons:
   UCD Student: $140 for four weeks
   General Public: $170 for four weeks

They also offer semiprivate and private lessons, please call for information.

Private LessonUCD Student: $50, Public: $60
Semi Private LessonsUCD Student: $40. Public:$50
TrailerIn Fee (per day) UCD Students: $20, Public: $25

The facility offers the unique service of a barn supervisor on site several hours per day who is usually an undergraduate student majoring in Animal Studies or Equine Health (prevet).  The Barn Supervisors turn horses out daily, blanket and otherwise perform services for the horses. There are set daily fees (roughly close to $515) for each of these services. Monthly blanketing is $60.00 and monthly turnouts are $60.00 (3 X week).
Turn out services include basic or premium service. Premium offers putting on boots and grooming/picking out hooves after the turnout. This service is $80 a month.




Random Noting

Every single one of the lesson horses are donated.

Heres a list of current & past lesson horses, which is hopefully accurate: UCD Equestrian Center Horses

The property the equestrian center is built on used to be a http://sportclubs.ucdavis.edu/horsepolo polo field

Media

http://www.davislifemagazine.com/Content.aspx?m6/1/2009&cId3020 Read a story and see photos about the UCD Equestrian Center in the June 09 issue of Davis Life Magazine.

 Pictures 





20080922 22:21:24 nbsp The EQC should not lure you in with its convenience if you are a new student coming to Davis. It might be convenient if you dont have a car, but ultimately a bad choice. For boarding: Only registered students are allowed to board. You are only allowed to board one horse. The waiting list to get into the facility is quite long, and they dont really keep it updated. THEY NO LONGER HAVE PIPE PENS, and rates have gone up. Pastures are now $190 (and ALWAYS full) and stalls are $300+. There are no other options. When I was looking in to boarding my horse here, they did not offer discounts for mucking your own stall. Also, the tack storage situation is horrible. Plan on keeping your stuff in your car, because you will have almost no space to keep anything at the barn, and being the nature of the high traffic stable, stuff WILL get stolen. IF YOU ARE THINKING OF TAKING LESSONS: Dont. The instructors are 18 year old freshman college students who barely know how to ride themselves. It is not hard at all to get hired as an instructor, and the turnover rate is so high that there is no consistent teaching style or quality. The lessons are crowded and you will barely learn anything. The horses are jaded lesson pony that you will learn very little from. Instead of taking lessons here, see about getting a cheap lease on a horse and finding a private, QUALIFIED instructor. Users/quarabaloosa

20090110 18:52:21 nbsp First of all, boarding is limited to registered students because they are the ones that pay tuition money (which in part goes to campus rec programs i.e. the EQC and helps maintains the facility).  It is also limited to 1 horse per boarder because there is such a long wait list already.  We would rather have as many people here as possible.  The waiting list is so long because it is a very convinient location for students.  The waitlist is kept as updated as possible.  Pipe pens and selfclean stall are no longer available because a lot of students do not have the time to clean their stall everyday and the stall gets disgusting!  Are you really going to out there mucking in the wind, rain, and cold when you have a 12page paper due the next day anyway?  Pastures are always full because they are priced so much lower than the stalls, duh.  The tack lockers arent that bad.  There are two racks for saddles and lots of places to hang stuff in it.  The traffic does not bother the horses.  I have never had one spook on me due to the freeway.  Things will get stolen pretty much everywhere you go so just be sensible and keep your stuff locked up in your locker, not out and about and all over the place.  The instructors do well for what they are.  Students teaching other students.  They arent high level trainers that did Rolex so dont expect them to be.  We have a lot of great little ponies.  Yes, some of them get a little jaded since they have to put up with a lot of beginner riders but they do their job well.  All of the ponies are donated.  We are not allowed to buy any so we work with what we can get.  They go through an intensive 90day trail period where they are evaluated many times.  We never accept horses that are not safe (for a horse anyway).  There are lots of upgrades still in the works like more drainage grading, new fences going up, etc.  Of course we have to wait on the university to give us money and that tends to take some time.  All in all, the ECQ is a great place to board your horse! Users/Desire

20090427 11:45:22 nbsp The EQC is a nice facility.  they have several horses in varying abilities (some are jaded and others are very high strung).  their outdoor arenas dont have the best footing (sand) but overall theyre great.  the cross cuntry course is nice and they have newer show jumps.  the traffic noise is not tht bad.  however, some of the stalls seem kind of dirty and i did not see any place to store tack and sulies. the staff is very nice and i would highly reccomend the EQC to riders.  Users/pompomcakes

20090712 02:00:11 nbsp I recently took a lesson at EQC and had a WONDERFUL time. I would highly reccomend EQC for many types of riding Users/pompomcakes

20090724 22:38:26 nbsp The Equestrian Center is a great resource for UCD!  Okay, it isnt the flashiest or fanciest barn Ive been to but the horses are well fed, well cared for, and not overworked.  The students who work for the EQC are (for the most part) wonderful and caring individuals who love horses in general and love the quirky ponies who get donated.  They work in extreme (for Nor Cal) weather conditions to teach lessons (and make bad pay, I assume, as student workers) and the barn supervisors give up their weekends, mornings and evenings to be there to ensure the safety of the riders and horses.  Three cheers for them!  Ive had some mediocre student instructors but Ive also had some outstanding instructors who helped me grow as a rider and helped me achieve goals in the saddle I never thought I could do and who show great commitment to being good instructors even with sometimes less than ideal circumstances.  The center is making some slow but good renovations redoing pens, barns and planting trees.  The horses provide good handson practice for the vet students, too, who also work really hard to keep the ponies healthy and happy.  Because they are donated horses many do have some bad habits or odd issues but thankfully this program exists because the alternative for many of these horses who are no longer useful or wanted by their owners could have been much worse.  This is a nice gig for them, their work hours are tightly monitored and they are limited to working in courses that wont exacerbate any issues they might have.  The guardian angel program where you can adopt a horse is a great way to spend extra time with the horses and give them extra love and attention.  All in all, the EQC is one of the best things about UCD and has a great group of workers who really seem to give their all to the center. Users/dandysgirl

20090812 18:55:56 nbsp Please correct the photo caption of the black horse if its not Sassafras. Im making a guess based on markings & what looks to be Sassi on her white board, however its possible that thats one of the private horses, or a horse that was on trial. Sorry if theres a mistake! Users/KokoSorensen

20101214 14:16:40 nbsp The equestrian center is a great place for student boarding. The facilities are almost all brand new. If youve had your horse boarded in Davis before, you know that in the winter the footing for corrals and arenas are horrible. The EQC is the only place where youll find pastures without deep sloppy mud mid January. All the arenas are groomed daily and are very large. This place is run very organized and professionally. Although, since the boarders are students, they tend to be girls between the ages of 18 and 25. This means that a lot of them develop really strong opinions that arent very accurate. Drama, its what happens at every barn. Compared to others, this one doesnt have that much. Most of the girls are on teams with eachother and are all friends. As far as prices go, this place is still under priced for the facilities and services offered. These boarders are so spoiled, but as you can see, nothing will ever be perfect. As far as things getting stolen...what? ive been here for a while and i dont know anyone whos had a problem.... If you are an experienced rider looking for lessons, OBVIOUSLY you wouldnt go to the beginning riding group lessons. The instructors are college level kids because they are just teaching beginners.....The coaches of the teams are all well qualified so go to them if you want lessons here. The lesson groups only allow up to four people...soo uhh no theyre not crowded. Overall, for being having a private/hobby program mixed with a governement/school operation, this place is awesome. The place opens and closes on time, the horses are fed the same time every day, youre stall will be cleaned early in the morning every day. The staff knows every horse on the premises and the owners. You may have to wear a hemlet when you jump and you cant let your dog off the leash, but those things are given on any school property, so why should it be different here? come on people use your brains. Thumbs up for the EQC.  Users/horses010101

20120516 16:32:55 nbsp I have been riding in UC Davis Equestrian Center since last year in May, starting from introduction to riding, riding 101a, riding 101b (twice), and riding 101c (third time now). I heard about the budget cut but since my riding started last year I have no way to compare my experiences between before / after the cut.

From my personal aspect, I would say UCD Equestrian center is a perfect place for anyone who want to get to start horse back riding in the area. I did a little riding six year ago (I could trot back then), and the Equestrian center definitely improve my riding to a new level (I can canter now).

Instructors:
the instructors I have been having lessons with are Teresa, Samantha and Hanna. They all are wellexperienced and patient instructors who work me through all kinds of problems or issues in riding I have. The only problem I can think of about the group lesson is that within 1 hour 30 min time period (that usually includes tacking and untacking the horses) and maximum four students (usually 34 ppl) in the same class, the attention and time you can get from instructors is somehow limited. Besides that, the quality of a group lesson is also highly related to (1) the skills of you and your classmates, (2) the mood of the horses today, and (3) the weather and the surroundings in the arena today. But I have to say that instructors are kind and nice and  enthusiastic in horseback riding that they are really open minded to teach you all riding aids for different speed of gaits. I myself as an international students, thought it was difficult for me to understand the instructions and terms in the beginning, especially when everyone is moving and the half arena is kind an open space to hear each other, the instructors are really kind and patient to me as always.

School horses:
there is a same group of horses for schooling, and each of them has their own horsepersonality you need to know to riding with. I have been riding with Duke (the calm and lazy guy), Bell (the girl who would challenge the rider at the first few minutes of the ride), Shinto (really good girl), Miss (the very sensitive girl), and CR (an old and clam guy; he is not around lately). They all are pretty calm to beginning riders, and they tend to move slower rather than faster, which makes them good and safe choices for schooling. The horse you will get for each lesson may vary depending on the availability of them at the time. In summer sometimes some of them are away for their summer camp. You can ask instructors to assign you the horse you prefer before the lesson sometimes, but I think it is good to have different horse rotated between lessons so you get to know how to accommodate yourself to different ones, which is also important in the horsemanship. The more your ride with EQC the more you understand these schooling horses. There is no the best horse to ride with in different lessons, since some of them may be good to trot but not so good in cantering. It really depends case by case. Usually the EQC will assign the ones that are available at the time and all right with the practice today. Ask your instructors to know more about them individually cause the instructors know a lot more about them.

The EQC has the guardian angel program if you want to stop by the barn and take care of the horses owned by EQC sometimes during the week. You are not allowed to ride them in this program though.


Overall, I would strongly recommend anyone who wanna understand a little bit about horseback riding to try the first level class (Introduction to riding) to get a feel about this activity, and if it seems interesting then you continue the rest of riding 101 lessons. During the winter/summer breaks or the gap between quarters, the private and semiprivate lessons are available too, which are good way to focus on improving your controlling and riding skill since you get much more time with your instructor. Users/yuhsuanchan
