
University Honda is one of the car dealerships in Davis town; Joe Clementi is the General Manager.

Their slogan is, Friends Dont Let Friends Buy Anywhere Else.

Voted Yolo Countys Best Car Dealership for 9 straight years per The Davis Enterprise Readers.

There is a nice lounge for patrons to wait, with soft chairs and table space, a free coffee machine, and a good selection of magazines. There is also a desktop computer and a highspeed wireless connection.

There is a minifridge with complimentary bottled water. You can take one when you come in, and they offer you one as you leave.

They are strictly an automotive dealership. They only sell and service Honda automobiles, and neither sell nor service other Honda products, like scooters.


20050915 22:53:33 nbsp I get my oil changed here, and theyve been pretty good about being routine. They even replaced a broken brake light without charging a service fee. That said, the car dealers didnt seem any better or worse than any other dealers Ive dealt with. After taking a test drive, they put on the hard sell and told me to go see the manager. I told him I wanted Redfield Machine my mechanic to see the car first, and he said Ohh.. we have a mechanic here. Yknow, Id trust my mechanic a lot more than any of these guys in town. To which I replied, yes, you would trust your mechanic more than these guys. The problem is I dont trust your mechanic. Needless to say, I didnt purchase my car there. Users/CraigBrozinsky

20060504 19:33:54 nbsp Unfortunately, I didnt buy my car there either.  I shopped there three time.  Once for research, then to test drive (all out of the car I wanted) and then to get a price quote.  I recommend going there for research purposes since it is local and convenient.  However, before negociating a price get some internet quotes first and bring them with you to help you get a price lower than MSRP.  They were the only Honda dealership between Sacramento and Fairfield that refused to give me a quote below MSRP on a Honda Civic without proof that other dealers did it first.  If you are looking for convenience shop there, if you want a deal, I highly recommend trying other dealers in the surrounding area. Users/JenCam

20060524 14:22:18 nbsp They charged me $80 to check my car for why my gauges were off... it turned out to be the fuse... which costs like 1.40 ANYWHERE... WTF? I will not go here EVER again. yech. (rip off) Users/JuliaNiazov

20060815 12:00:17 nbsp I enjoy going here.  As far as courtesy goes, they dont seem to differentiate between someone buying a $2 light bulb and a $40,000 car. Users/ChristopherMckenzie

20061122 15:26:27 nbsp I like this place the staff is friendly and when we have taken our Civic there for service they have always been prompt. They even call when they say they will. Users/MyaBrn

20070308 16:26:56 nbsp I have purchased two cars from University Honda, all my maintenance has been done here (except for a couple oil changes when I was out of the area), and every aspect of doing business with this company has been exceptionally enjoyable. Users/KyleWecker

20070728 04:35:29 nbsp If you are shopping for a car, do NOT give these people your phone number. They will call many times. Users/JohnWong

20070728 17:32:19 nbsp The Caucasian service rep in his 40s was very nice to my girlfriend.  He fixed the car enough so she can drive it again and changed the outside hub for free (it was scratched really bad due to the car hitting the curb).   (+) Service and explaining the charges  Users/atwong

20070831 19:00 nbsp I just had a really bad experience there today. I just bought a new honda pilot in another dealer. I want to sell my old honda civic so I called University Honda and I told them that I had an old vehicle to sell and I was not going to buy a new car there and asked them whether they were interested. The representative said he was interested and asked me to bring the car in. After I arrived, the manager first said he would only buy car the next Tuesday (Today is Friday). After I insisted that he just gave me an estimate, he walked out with me and took a look. They he asked me how much I wanted. I said maybe $300. He said the car was worth that much. Then he asked me why I was selling the car and I told him I just bought a new honda pilot somewhere else. He then basically demanded me why I didnt buy at his dealership. I explained to him that they didnt have the model I wanted (Im only interested in a 2007 model, the only one they have in stock is not the model I want). Suddenly he got pissed off and said he will not buy the car and asked me to sell to the dealer where I bought the pilot. Then I said dont get mad just because I didnt buy the car at your place. Then we had a few unpleasant exchanges which Im not going to type it here. Really, really bad experience there. Users/wikier

20070903 23:05:22 nbsp Looked at preowned vehicles here. The staff was very nice, but they definitely put the pressure on. Be ready to say no to them MANY timesit took a while to convey that I was there to LOOK, not BUY. They said they had CarFax reports on all used cars. I asked for two reports. They kept accidentally bringing two copies of one report and never did get me the second one. I test drove the car that there was a report for and found an aerosol can which had fallen under the hood. Granted, this could happen anywhere but it still made me a bit nervous. Then, it came time to drive the car I did not have the report for. The engine sounded awful just turning it onI dont know, but something tells me they didnt give me the report on purpose. This stuff could happen everywhere, and like I said, they were very nice. If I were in the market for a new car I may consider it. Keep in mind if you are looking at cars that just because one is certified does not mean it is in good condition, and always be sure to look under the hood, both above and below the engine.  Users/sweetMeliss

20070924 15:40:51 nbsp I looked at new cars there, and told them I planned to sell my old one myself. I made the mistake of giving them the keys to my car just for a tradein estimate. They would not return my car keys to me even though I asked 3 times, in a louder voice each time. I finally took out my cell phone and threatened to call the police, and finally got my keys back. Way too highpressure. However, I have used their service department a number of times and always had a good experience with it. I just wouldnt buy my cars there. Users/AngelBug

20071115 13:01:10 nbsp Dont ever give these people your phone number.  They do computerized junk phone calls.  If you contact them and are put on hold they pound you with advertisements while you  are on hold.  My wife and I bought a car there and I wanted to go get something to eat down the road and talk to my wife and they were just short of trying to physically keep us from leaving.  My impression is that they are just another untrustworthy car dealer. Users/ron@hgtitle.com

20071126 10:11:13 nbsp I dont doubt that horrible car salespeople work at University Honda, but I was fortunate to purchase a 1996 Accord from a guy who used to be a psychologist and hadnt yet developed a chain smoker, commission hungry demeanor. My comment, however, is really about the service department. I find that department to be professional and courteous, and more importantly knowledgeable and experienced. Im sure that one will pay somewhat more for service here, but the peace of mind may be worth it. Users/BryceHathaway

20080219 20:27:50 nbsp I recently purchased a car at University Honda and my sales person made it a great buying experience for me and I love my Honda.  His name is Dave Gibbons.  He has been there many years and knows the Honda cars very well.  If you ever read this Dave Gibbons, Thank You. Users/anneowens

20080318 07:34:31 nbsp I purchased a new 2008 Accord from University Honda. I am very satisfied with the purchase, and had a generally good experience purchasing the vehicle. Although of course its not exactly difficult to choose a Honda. I recommend the salesman TJ, as he was exceptionally polite and did everything possible to cater to my needs as a customer. I also feel that he and the University Honda team are highly trustworthy and knowledgeable. The purchasing process was very efficient and prompt and I did not feel pressured in any way to buy any particular vehicle or addon feature. I did receive a resident discount even though I did not negotiate the price or ask for a discount, but I did manage to talk them into giving me a couple free oil changes, complements of Joe who is exceptionally nice and highly competent. It is also nice to be able to buy from a dealership that is part of a great community such as Davis. Buying a new or used car can be quite stressful, but I think that University Honda is a very good way to go. Users/ByronDelaney

20080318 17:46:49 nbsp I have taken my older Honda Accord here for repairs, the first time to get my a/c fixed, the second time because my car didnt pass its smog test.  They may charge a bit more than some of the smaller garages in town, but as the description above notes, they offer some comforts and conveniences.  I appreciate that they have a shuttle van with a friendly driver who drops you at your doorstep after you drop off your car and picks you up when your car is done  all complimentary.  I have also been happy with their work and with the customer service people at the desk  when I went back to pick up my car, Jennifer actually remembered me when I walked in the door.   Users/AmandaSmith

20080324 20:28:31 nbsp I really didnt plan on buying my car here. I met Paul a week ago and he was very straightforward and friendly. I was just test driving cars that day and all the other sales people I met that day all seemed untrustworthy. Paul was very friendly, though. My process of dealing with univeristy Honda wasnt very smooth, though. I was going through the Internet to get pricing quotes, and every time I came in, they wanted me to bring my quote. It wasnt like We can or cant beat the price, it was just Come in and well see. I came in once on Thursday and was told that they couldnt meet my price and that the dealer who was giving me the price may go out of business, etc. etc. I could have easily let them know what price i wanted and if it could be met or not over the phone  but it seems like they dont work that way.

I was also mildly offended when it got almost confrontational when I wanted to leave the place to go buy in Stockton since the salesperson in Stockton was always up front with me and didnt play these games. I got a line Dont you care about your firemen and police? when I mentioned I would rather buy the car in Stockton. Despite this, they did lower the price to keep me as a customer. The General manager also tried a guilt tactic as if I had wasted the salespersons time. Once we had come to an agreement on price, though, the rest of the process was pleasant. They got the exact model and color I wanted and were very helpful showing me all features about the car, etc.

I guess if you know what you want, you may come to loggerheads with the people there, but they are willing to compromise, which is good. I have to reiterate again that it really was great working with Paul on this deal and Im definitely happy with the car, too. Users/RohiniJasavala

20080528 13:09:50 nbsp We were having major problems with our 02 Civic that has 90,000 miles. When my husband went to start it one day it sounded awful and wouldnt go into reverse. He somehow got it to University Honda and come to find out it needed a completely new transmission! After we got over our shock, Honda said they were going to try to contact the factory and have them pay for a nnew transmission. It ended up that the factory paid 75%...we were very diappointed that a young car had such a serious problem, but the guy who helped us was great, his name is Jose.
I agree with the phone call spamming:For a week after the repair we got 2 calls a night from Honda asking us to do a survey. We just screened calls if we happened to be home. Users/MyaBrn

20080903 11:28:47 nbsp Ive had two Hondas, both CRVs. The first my wife and I bought via carsdirect.com, because I hate heavy sales pressure and like the spirit of that web site. When that car was crunched in an accident (not our fault!), I returned to the web but also got some email quotes from other dealerships. I visited University Honda just to check out the car, and University Honda beat all the other deals. It was not a hard sale. However, you can expect them to try to sell you on peripherals such as extended service agreements, Xylon coatings, etc. Our service experiences with them have been great. Im quite happy with them. Users/BarryRice

20081128 13:01:47 nbsp I just bought my ridgeline from University Honda, it was a fantastic expereince.  Everyone was very friendly and easy to talk to.  HTey got me the exact truck i wanted and with a very fair price.  I recommend going there to anyone who wnats to buy a car. Users/sman54

20090511 17:36:58 nbsp I just bought a new Fit from UH and had a generally great experience. Dave D was my salesperson; he struck a fine balance between his investment both in making the sale and in making me happy  i.e., he wasnt too pushy, had helpful information, kept in communication with me, &c. They gave me an excellent deal even though the Fit isnt eligible for many dealer or buyer incentives, since its cheap and very popular (high mpg!). Their price, even with a few extras, was below other quotes I received from Sacarea dealers and below MSRP. They also gave me a decent interest rate, considering I have sub700 credit. Paul in Financing pushed the LoJack and the extended warranty pretty hard, but he also gave me time to consider so I cant complain too much! Users/Kay

20100824 08:02:57 nbsp brought the car in for service due to rattle noise when going over pumps. When asked about strut recall or any report on strut manufactured defect, got a smirk from the guy. 140 dollars for diagnostic test. why cant you have your mechanic test drive the car and narrow down the parts to be fixed plus lowering the diagnostic price too? When asked for how much the parts cost, the guy cant give me a price because he doesnt work for the parts shop. Boooo! Users/MBui

20110405 23:13:10 nbsp I just bought a new Civic from University Honda.  They provided me with excellent service, thanks to Loyal(salesman), Nicole(Finance), and their ManagerGreg.  They were very patient and attentive even after Ive committed to buying a car.  I felt like I got a very fair price without the pressure and deception that Ive received from other local dealers.  I recommend checking out University Honda first when buying a car to save you time and hassle.  I had a great first time new car buying experience!    Users/ArisaNaganuma

20110807 13:48:08 nbsp f worthless, dont have parts for my honda scooter. Its a Honda, you have access to the parts pipeline get my my damn air filter and brake pads you slapdicks Users/StevenDaubert

20120131 18:15:42 nbsp Last year came here for an oil change for my Honda S2000. They wanted to rape me for 80+ dollars for OEM oil change. I dont even use synthetic, just normal 10W30. The superviser told me some B.S. about how 10W30 is rare and they dont get many S2000s in to actually stock 10w30...whatever. Took me a while and finally they agreed to the price of $58 (still oil change rapage but only because I was in a hurry and wanted to get it done with). This time around I went to a shop down the street from me and got the same oil change with no B.S. about oil rarity for 38 dollars and free care wash! Was in and out within 15 minute and didnt give me University Honda haggle B.S. FU, University Honda! :D Users/C.Ling

20120201 13:46:42 nbsp Ive always had really pleasant experiences with the service dept here. For my Hybrid, their 0W20 oil changes are cheaper than nondealership shops in town, Ive checked, which surprised me. Its like $50+ and other places quoted me over $70, saying that this oil is some expensive synthetic or something, I dont really understand. Once or twice, I ventured out onto the lot while I waited, and as some people here have mentioned, the salespeople are aggressive. One literally sat me down to show me how I (on a gradstudent budget) could absolutely afford a new car there. Made the mistake of giving him my email, and got about 34 emails a week until I asked him to stop. Users/DavidBenjamin

20120325 10:35:29 nbsp This is by far the best Honda dealership in the area.  I grew up in Vacaville, and after attending school in Davis I needed a car, and my dad told me he always went to university honda.  I was not disappointed.  Their internet sales rep, Alicia, was very professional and to the point.  There were absolutely no games involved (out in less than an hour!).  I explained my situation, and she gave me several options.  I havent yet decided to go through them, just because Honda simply does not have great mpg, but other than that I loved their cars and their rates.  I was incredibly happy with their service.   Users/SabrinaMuerle

20120605 15:49:07 nbsp My son graduated from college and wanted to buy an inexpensive used car. Like most people we assumed that the best deals would be found on sites like Craigslist or AutoTrader but decided to visit some local dealers after checking online.
Dave Gibbons at University Honda surprised us by suggesting a Ford Ranger. My son hadn’t considered a pickup but decided that the Ranger made sense. It was in excellent condition, interior and exterior, with an extended cab, good sound system with CD player, A/C, a bed liner—the works. Frankly, it looked too good to be true, and we expected to pay about $7,400 based on the Kelly Bluebook.  Mr. Gibbons had the mechanics put the Ranger through a smog and safety inspection. Although everything checked out, the mechanics found a small crack in a serpentine belt and replaced it in addition to replacing other items like windshield wipers, air filter, etc.
My son and I braced ourselves for the price quote expecting it to be much higher than the approximately $6,600 quotes we’d seen on the Internet and thought Mr. Gibbons was kidding when he told us they’d decided to charge us $5,900 for the Ranger. He wasn’t.
Mr. Gibbons also told Nicole Stone, the Finance Manager, that my son was a firsttime buyer with limited funds, and she gave my son a 20% discount on the powertrain warranty he wanted and also showed him how to get a cheap auto policy and print an ID card online.
My son bought the Ranger and Mr. Gibbons had Andrew Waller and his detail team give it a thorough cleaning and check for loose screws (one was replaced) and any other minor problems.
I’m very impressed with the University Honda staff including Mr. Gibbons and his sales manager Greg Locastro who seemed to go out of his way to give my son a great deal on his first auto purchase.
 Users/nowhereman

20121103 10:12:54 nbsp I would not recommend these guys.  I went in to test drive an Insight, and had checked on their website to make sure they had one,  the website said yes.  When I got there, a nice salesman named David told me they didnt have one, but hed check.  Turns out they didnt, they said it was gone 3 days ago (this experince seems a LOT like the experience of another reviewer below, weird).  Then I asked if they could get one, and someone named George checked, and said there were some in other dealerships, but wanted to know if I was serious before getting me one to test drive.  Then continued to go back and forth, I was confused, and kept saying, yes im serious thats why im here at 9am on a work day).  I did make it clear that if i were going to buy a new car, I wanted to choose the color (the one he said he could get was silver).  He said he wasnt going to make a special call to get me a blue one, I said thats fine I dont care what I test drive but I just want you to know I want to buy a blue one, not silver (if you buy a new car, hsouldnt you get to choose the color?), he responded that he wasnt going to make a special call for this, and that if some other dealership called THEM in the next few days and wanted to trade hed do it and I should leave my info with David (who was nice) and theyd get back to me in a few days.  Then began looking at some papers in front of him.  Since hed been doing that while checking inventory for Insights, I thought he was still checking until he started talkign to another salesperson about something else, and I realized Id been dismissed.

But bevfore that theyd tried to talk me into buying a Fit which gets 27/33 mileage, not much better than my 91 Honda Wagon that gets 25/28.  I said no I want better mileage.  They were insistent, and David kept telling me the mileage on the fit was better even after I pointed to the window tag which said 27/33 (later)...

Completely confused after my immensely rude dismissal, I walked away with David, and left him my info.  Took me a few hours to get upset, as when I left I was just so confused that they were so resistant to the idea of bothering to sell me a car I wanted.  I will say in their defense that someone named Steve called me later, maybe hed overheard the whole thing?  and said hed arranged to have one delivered there for me to drive the following day.  By this time Id already made an appointment with Mel Rapton Honda, and I bought one from them today.  Which I guess technically demonstrates I was in fact serious about buying a car...  At that point I didnt want to give them my business, George acted like allowing me to test drive an Insight was a great inconvenience, and spoke as if I should be grateful.  No matter how many times I said I was serious, he still ended on Im not going to make any special calls.  Anyway, Mel Rapton was awesome.  Dont know if this is typical of University Honda, but I wont be taking my car to get serviced there, as I just dont need hassle or attitude.  Mel Rapton was super friendly and I got an Insight, though I did have to drive 60 miles RT to find good service. Users/JessS

20130918 13:57:25 nbsp I go here to service my car, a Honda Civic, whenever I have issues. They are always very helpful, courteous, and kind. Ive had to leave my car there for a few days, and they were always extremely communicative with me and always made sure I knew what was going on and what they were doing. Price wise, they always tell me up front what kind of price range Im looking at. Remember to ask if they have any special deals for service. Last time they even gave me a coupon for 30 dollars off a new car battery. I also love their shuttle service, which will take you home if you have to leave your car there for an extended period of time (I think they might pick you up, too, but Im not sure). Suffice to say that I believe the service half of their business is great. I havent had any real experience with the dealership side, though, so I cannot comment on that.  Users/Adalwolf

20131103 23:39:47 nbsp Didnt buy a car, but their parts department got me what I needed in a timely manner and at a good price. Called me when they arrived. Guy at parts counter gave me some good advice (put antiseize on my exhaust tip bolt). Dont bother buying parts through the University Honda website as I got no response. Order through the Honda eStore and have it shipped/delivered here.

ProTip: Need Acura parts but dont want to drive to Elk Grove or Fairfield? If the part is equipped on a Honda product you can buy and have it delivered here via Hondas eStore for cheaper than what Niello Acura sells it for. Crossreference the part numbers first.  Users/HarrisonM

20140721 19:44:58 nbsp I recently bought a new Honda Civic here with my dad, and they were great. The staff here was very helpful and straightforward in answering all our questions. They even answered our questions about what the cost of the car would realistically be, which other dealerships wouldnt do. I had a really great salesperson  Clete Berg. He thoroughly showed me every part of the car and how to operate each feature. He even called to check in with me the day after I bought the car! Would definitely recommend University Honda, and Clete.  Users/HannahH
