

University Court, known as Heritage House prior to 2005, offers studio, one and twobedroom apartments ranging from $1,100/month to $1,450/month. Very close to campus and affordable, across from the University Mall.  A pool lies in the middle of the South and North buildings. Extensive renovation has been done. Several large conference rooms have been constructed, most of which are accompanied by plasma screen televisions. Plenty of study area as well as room for socializing, they even have a pool table and a computer lab with free printing. There have been several noticeable upgrades but the prices are still very reasonable considering everything they offer. They offer really great tours and the office always has food or candy for prospects. Also, the renovations and all of the new furniture have really made it a more upscale place but still good for college life, and even though it is right next to the dorms it is much cheaper.

Parking does not come with rent but is an added fee, so there are always places to park. Also the apartments do not come with internet or cable television, that is also an additional fee. They have a computer room with free internet but they close at night. The computer room also has a printer so if you bring you own paper you can get free printing.

Parking is somewhat limited, but gated. The complex provides 24 hour emergency maintenance. They are currently managed by http://www.udgi.net United Development Group.  (They used to be managed by ConAM and  EAH, Inc. who also managed Primero Grove.)

See our Housing Guide for more information on housing in Davis, and our Apartments page for a thorough list of complexes within Davis.

 Floor Plans and Rental Rates for Fall 2012 




Pictures





I have a friend who lived here in a two bedroom. I thought it was kinda crappy, but its right near campus. Worth checking out if you want to live near campus.

I stayed in a 1Bed 1Bath apartment during the spring. The air conditioning unit was hard to control so it was either too cold or unbearably humid. The apartment itself is pretty old and shabby. The owner of the apartment said that she has seen Mice mice and Cockroaches cockroaches in and around the property. Positives include plenty of closet space and a separate and huge sink area in the bathroom.  Users/LenaGranik

20050405 18:59:18 nbsp My friends live in a two bedroom there, its pretty nice, but definitely on the small side. Dining room? What dining room? :P Nice place though, new carpet and a newish apartment in general. Kind of confusing layout though, theres two identical apartment complexes owned by the same properties North and South I think they do it by? And they both have the same numbers. The only way I can tell them apart is by the shape of the pool. I dunno, something to look out for.  Users/NatalieKitchiner

20050611 00:59:26 nbsp The only good things about this place is the huge closet space and that its right across the street from campus. Everything else is horrible. There are mice everywhere, when I moved in one of our sinks was clogged and when they came to fix it a dead mouse was found inside. Also HUGE rats have been seen. I mean these things must have been about a foot long not including tail. They looked like those wharf rats in all the bad horror flicks, and to have one die in the ceiling kitchen wasnt a great experience. Parking is also very limited as there is only one space per apt and street parking is nonexistent. Users/BenWebber

20050619 19:43:29 nbsp I used to live here, but I got strategically moved out by my former roommate. Oh well, it wasnt as if it was a big loss. When I lived there, I lived on the first floor of the 545 building. We had a lot of problems like the main drain pipe clogging up and everyones sink water overflowing into our apartment. We told everyone in the building to not use their sinks and what does everyone do? Use their sinks. In addition to that, the lock on the door to the apartment broke (the locking pins fell out), and we had to spend the night with an unlocked door on the first floor. When I finally moved out, it took almost two months of bitching at the (now former) manager to get my security deposit back. From what Ive heard from people who live there now, the new management is worse than the old management. Users/StephenHo

20060915 17:28:42 nbsp I find the new management company on the iffy side. They renovated nothing except the office and gym area and decided to increase the rent, not pay for water or garbage, limit only one car per apartment, and have the guts to charge $200 for a parking permit. Not to mention they decided to tell us this information in March  a month after the waitlists close in other apartment complexes. It was incredibly difficult for us to find a new apartment in such the short amount of time they allowed us to renew our lease. Users/SandyLeung

20070305 19:45:00 nbsp this website says they allow pets, but they dont. Users/VivianMartino

20070325 18:48:38 nbsp I have a friend who lives there and the place is definitely very nice, we stopped by the office to ask about renewing and they gave us baggies with free scantrons and offered us cookies...the girls in the office are really nice. My friends apartment is a 1bedroom with a HUGE closet, i like his place more than the dorms. Users/JenLee2

20070514 22:20:41 nbsp I lived here from 0607.  It was very nice compared to all my friends places i thought.  Staff is very nice and there are alot of cool things such as the billiards room, computer lab room, and the really nice pools, and study lounges.  one thing that was annoying was that i payed 120 extra to be able to park tehre and i found out everyone else was parking there and not getting towed.  looks like someone finally said something though .. the parking lot is back to how it usually is; plenty of open spots.  overall good besides when the gate would randomly stop working and you were stuck in or out! Users/dani1986

20070526 19:56:18 nbsp Great place to live. Brand new carpet. Very clean. Great maintenance. Very friendly managers. Great pool. I have enjoyed my stay here and I am a pretty picky person when it comes to living situations. This place is gated. Great location! Five minute bike ride to school and VERY close to the ARC. Big closets with mirror sliding doors! Great lounge areas. Nice computer lab. Youve got the B, C, D and K bus lines to take you to school! Thats four bus lines that are right outside the complex and take you to the MU and Silo. Users/BaySFhFmUC

20070822 20:09:51 nbsp All around HORRIBLE place to live! I had no closet doors when I moved in and was promised they would be put in within 2 weeks....2 years later I move out and still no closet doors. The faucets in my bathroom had hot and cold backwards and they wouldnt fix it. The air conditioning was so crappy it made the living room cold but left the bedrooms hot and muggy. They are constantly doing renovations and upgrades and being very noisy very early in the morning and leaving messes all over the place. Office staff is rude. You can park here...if you pay the RIDICULOUS parking permit fee (plus only 1 per apt!). The gated community sounds prestigious but is really just a pain in the ass, esp. if it decides not to work when you come home in the middle of the night. Common areas are cool, but the hours are so dumb...definitely not fit for a student schedule. Ya, its close to campus...but NOT WORTH IT! Not to mention they swindled my entire security deposit for really dumb stuff. I got charged $70 for cleaning fee even though I completely cleaned the place before I left (I left it cleaner than it was when I moved in). This place is a shit hole with a new paint job and high rent (the nicest part is the fancy office they just made). I SERIOUSLY recommend avoiding this place. They will try and lure you in with free goodie bags and barbecues and free food, but run away as fast as you can!  Users/ucdstoodent

20070921 13:00:58 nbsp I thought this place would be a good place to live because it would be a quiet place to study and since it is near the campus. Its near the campus. When I moved in, we did the the walkthrough and there were some problems: the stove knob didnt work, the AC wasnt blowing cold, paint stains and discoloration in the carpets everywhere. However, after looking more closely at the apartment, I realized there were alot more things wrong with it: There are light switches that dont connect to anything, not all the outlets work in the apartment, the window was broken so it couldnt slide shut, the whole apartment felt like a cheap apartment made over to look expensive. You have to pay to park here?? WTH is that?? I just hope the apartment doesnt take away my security deposit. They suck you in by showing you the nice amenities like a pool, workout room, billiards, study rooms, computer room but all that barely makes up for the state my apartment is in. Look around and ask the tenants before you move in, I wish I would have done that. Users/HandsomeChen

I have a great 1 bedroom apartment here. I wouldnt listen to what people say about the place having problems...its called life. No place is perfect but this is definitely a sweet deal for how close it is to campus. Management here is probably as good as it gets, theyre nice and easy to win over...plus one of the girls who works here is seriously HOT. This place has a lot to offer, I wouldnt listen to these whiney, fresh out of the dorms, sophomores who think they deserve it all. Common areas are open until 10pm...if youre complaing about that you probably need to make friends and go out more. Im a picky person but I definitely think this place is worth it. They remodeled every unit over the summer to make sure everyone has upgrades, plus who else gives out free food (catered) and prizes every month! Users/comp8t

20071207 00:40:08 nbsp The place is alright. Expensive but I guess thats how most places around cmapus are. The buildings are actually pretty nice and everything is remodeled. They give you tours and a lot of info. Plus they have feasts every month and ibe heard the social scene is pretty cool. I met one of the girls in charge of the monthly feasts, shes probably the nicest... gorgeous girl, Colombian I think. As far as the other staff, pretty unprofessional and incompetant. The receptionist was talking to a friend for a long time on the phone and I was just standing there waiting! Users/KJOOO

20080122 19:09:28 nbsp I think that this is a horrible place to live. The prices seemed reasonable but then adding electricity bills, internet bills, and water bills the place is somewhat expensive. The gates are really annoying and whenever someone comes to visit you have to go down to the gates in order to let them in. The apartment looks nice at a glance but then you see how crappy they really are. The walls are thin and do not keep in the heat during winter or keep the heat out during summer. It is close to campus though. Users/laquelle

20080126 01:05:50 nbsp This place is TERRIBLE. Nowhere in Davis wil you  have to pay utilities, internet, and everything else on top of $1294 for a pretty small 2 bedroom 1 bathrooom apartment. The apartments are not in great shape when you move in but they sure charge you when you move out. The gym is old and the machines are beat up. Save yourself the extra hundreds a month if you want to live close to campus choose another place nearby. As far as the staff, it keeps changing, seems like not only the tenants are trying to get away! Getting something fixed will take forever and a lot of BS. The office closes at a certain time, but most of the time if you go there the last hour its surprisingly closed already. The monthly events they have are okay, I can tell the students who run it are pretty genuine, but its kind of creepy when the manager and her assistant stand there and just stare at everyone they also tend to huddle in the office and eat when the student that work here are out there doing the dirty work. Stay awaay and dont let them lock you in!!! Users/markx

20080304 16:23:55 nbsp DO NOT LIVE HERE! Its among the worst places in Davis! Basically theyre old apartments that had paint slapped on them. There is a reason why they have a model apartment because they dont want to show you what the rest of them are like. The North building is the worst...do not move in there! It has a crappy pool that never gets any sunlight and the smaller 2bedrooms are horrific. The walls are way to thin youre practially sleeping with your neighbors and the windows are so cheap you can hear everything that goes on at the Umall and at the dorms. During the summer this place gets infested with mice. The gate sucks, anyone can just trail in, or reach over and touch a switch that lets you in. You pay $240 for parking but people park there without permits all the time. They warn you but believe me theyll never tow your car. Maintenance keeps changing and takes forever to respond. The manager hides away and seems to be afraid of everyone. Her assistant sits at the front, warms the chair, plays on the computer, and chats away all day shes rude and if she doesnt like you, good luck getting something you need.  Users/yuck

20080727 19:31:25 nbsp Yucks previous comment wasnt entirely wrong but its not that easy to reach over and open the gates you actually have to jump over to be able to push that button, unless you have freakishly long ass arms, you would have to sit on the top of the gate and have like a 4foot long arm idk its really not that easy to just get in. And maintenance has been a little slow but its getting beter. The whole ac thing does suck really bad. Its either freakishly cold or icky and humid. My roommie is from the bay area and he had the ac runnin 24/7 and I shut if off all the time but it quickly becomes humid...so yea thats kinda dumb that they havent resolved that issue. Users/csmith


20080921 03:38:16 nbsp To be honest, the place is a bit pricey, but the new management team is a nice bunch..so easy to talk to them. Do not park here if you do not have a permit, THEY DO RANDOM CHECKUPS!! They give you like a one day warning, then they tow your car the next day. My friend had to pay $200 fine because thats how much they charge for TOWING Service at Davis. Be warned! One request is they should STOP letting NONResident come to our monthly free food days because all they do is take all our food and leave.  Users/2point0student

20080929 22:37:37 nbsp I am living here now. The apartment is nice and the complex is quiet but... Jennie Aragon, the front desk clerk, is a ten degree BIZZATCH! Users/Pringlessong

20080929 22:41:35 nbsp Ohhhhh I forgot! If you are a graduating student and you ask her for a ten month lease and she says yeah! no problem! DONT BELIEVE HER! a couple months later she will say that they dont do that and shes never heard of a ten month lease and you are stuck paying for that expensive apartment for an additional two months WHETHER YOU ARE THERE OR NOT! Users/Pringlessong
  Why wouldnt you have agreed on the end date in the lease you both signed? Users/OscarSabino

20081029 21:44:19 nbsp My experiences with the management have been generally positive. The apartment events are quite frequent and for free food (so to speak), isnt bad at all. They definitely try more than other apartments I have had experience with. Up on the third floor, I get more exercise, but have never seen a single bug. Each room is individually air conditioned, which is very convenient. The room itself is a bit on the smaller side, but the complex is very close to campus, which is very convenient for when the bus breaks down or you need to bike to class right away. Being right next door to Cuarto, many freshman choose to move over in their sophomore year. One concern is that the only elevator (in South at least) is in the common area, which closes at 10 on weekdays and earlier (closed all day in the summer) on weekends. Keep this in mind if you have problems (or have foreseeable problems in the future) to go up the stairs.  Users/JaimeG

20081117 11:35:05 nbsp
i agree with the comment on Jennie aragon. The people who run the social events have hygiene issues. Rent here is too expensive. Air conditioning is not central but there are 8 apartments that do have it (all are in the north side). Utility rates suck. I now live at Cranbrook. Much bigger, cheaper, and prettier.  Users/treebee

20090422 14:39:24 nbsp Overall, I would not recommend this place. Not for living, not for work. I lived there for some time and now im in a condo thats saves me 300 a month and its sooooooooooo much bigger, nicer, and less noisy. BTW their alarms suck...always sounded off at high hours of the night and early morning.  Users/ucdruby

20090901 13:29:00 nbsp If you choose to live here, dont expect to get your security deposit back. My roommate and I washed all of the counters, walls, and floors, and I personally steam cleaned all of the carpets. The apartment looked exactly the same as it did when we moved in. Management now wants to use almost all of our deposit money on a new paint job and to steam clean the carpets. Im going to argue but I dont expect to get far. If I had known they were going to pull this crap on us I probably would have trashed the place on the way out, would have gotten the same amount of money back. It wasnt too bad living there apart from being overpriced, but after this deposit debacle I heartily recommend that you spend your money elsewhere. Users/dwgarcia

20100508 12:00:11 nbsp Wow, who the heck can afford this place?  They seriously should have pricing caps on properties in Davis...that is what I call Fair Housing.  I think the only people that are able to live here (in a 1 bedroom) must be rich, or not even students. Users/JSlice

20100903 15:13:37 nbsp DO NOT LIVE HERE!!! They try to take all of my deposit when I move out. Now I got nothing back!!! When we did the initial inspection, they estimate that itll only cost about $200 out of my deposit. Now then send me the letter saying this and that. DO NOT LIVE HERE, YOULL REGRET IT!! Users/thtly

20100907 01:15:05 nbsp Um, Ill start off by saying .. FALSE ADVERTISEMENT .. with the pictures. UCourt basically is old crap with new paint slapped on it. Cockroaches, rats, and jumping spiders run amuck at this place.

Management is downright HORRIBLE. I dont even attend UC Davis during the school year  but I attended summer session and stayed here for two months and it drove me NUTS. You have NO idea, how much I hate this place. This place is a NOISY dump. The garage is always seemingly open and broken, you have to pay a deposit for the gate clicker, and you practically never get your security deposit back. The management team is SO unprofessional, LAZY, and they refuse to get involved in any sort of roommate business. Um, WHAT THE HELL. New asshole people who move in want to blackmail people to get on their hands and knees to clean who arent even on the lease anymore or else they refuse the roommate release form signature? And what does management say? Oh, um its common courtesy to hire professional cleaners to clean your apartment after you find a replacement.

OH, EXCUSE ME, MANAGEMENT. We are COLLEGE KIDS, we are not MADE out of money!

UGH, I will not waste my time complaining about this place anymore because I spent all summer complaining every single goddamn day about this .. this .. piece of SHIT place with shit management!!!!!!

DO NOT LIVE HERE!!!!!! Users/sheenatsang
   If you dont like the photos, take some more representative ones and put them up.  This entry belongs to you and the rest of Davis; it isnt an advertisement for University Court Apartments. Users/JabberWokky Evan JabberWokky Edwards

20110119 12:38:30 nbsp Let me break it down for you $1300 a month for a 2bd i bath (720sq. ft which is TINY!) Plus utilities ($50 or so a month which renters typically do not pay elsewhere), parking which runs about $40 a month. Youre looking at paying almost $1400 a month not including pge and other bills. You are crazy if you choose to live here. Even if you can afford it...go live somewhere nicer. You pay the price, but trust me, there is no luxury. Oh heres an insider secret too...these used to be dormlike suites. Therefore, there are no concrete wall divisions from unit to unit, thats why so many people complain they can hear their neighbors at all times. Lastly, before you move in. Go to the third and second floors and you will notice the passage ways are literally leaning inward as id they are going to collapse soon. It is a matter of time before the city asks them to restructure or tear down.  Users/mangosalsa

20110119 17:37:47 nbsp I lived here 1 year and I couldnt wait to leave. My apt faced Russell so when ever I had my window open, it was extremely noisy. It sure doesnt help that dorms are located directly behind us so Thurssun people are constantly passing by extremely late and talking REALLY LOUD!!!! It was very annoying. The windows and walls are made of paper. I even heard every single word my upstairs neighbor said, how ridiculous is that. People here are very rude since they dont know how to talk low. So, it its a noisy complex. Management was nice. I really liked free printing, which was a great plus (the only one). Other than that this place is crap. The apt are really small and crappy. I hated the A/C unit since it ONLY made the living room cold. I didnt even use the heater because i didnt like it. So from my opinion, i say live somewhere else. This place is loud and the apts are crap. They are way over priced for what you get. So glad i dont live there anymore Users/Greengirl

20110323 04:43:36 nbsp Room available in University Court
I am a UC Davis student, I have leased an apartment in the University Court, and I am looking for a housemate. A room in the apartment is available for rent.
The lease is from September 9th 2011 through August 31st 2012. Rent: $605, Deposit: $375.
The apartment has a kitchen, bathroom, lounge and patio. The kitchen has a microwave and a refrigerator. Other facilities: swimming pool, gym, conference rooms for private study sessions, computer rooms with laser printers, security, car parking etc.
A girl or guy with any sexual orientation can contact.
If you have any question dont hesitate to email me.
faizandar0@gmail.com Users/faizan

20110621 23:44:51 nbsp Probably the most sketch apartment complex in Davis. Sure its close to campus, but beware of losing security deposit for no reason. They told me that they were removing a lot of money due to very minor carpet burns (understandable), but when I passed by the apartment 1 week after we handed it over, I saw the carpet was not changed but instead they were building tiles near the front of the door. Plus their gates sometimes dont work, stranding you either inside the apartment or outside (and cant get in). Water is shut down on random days (about once a month). That being said, the Janitor is a friendly and nice fellow, though I really think he is overworked by the management.  Users/JohnathonJosephs

20110621 23:46:02 nbsp Also worth noting that i have friends living on the third floor on the side opposite to the management and occasionally they hear mice through the AC. Cockroaches are all over the outside (never seem to get inside though) too Users/JohnathonJosephs

20110818 16:17:47 nbsp I stayed here in a 2bed/1bath for the summer of 2011 and I am about to move out in like two weeks and mannnn I cant wait to get out of here. This place looks super nice online and the club house place is pretty nice and really nice to go to when it is unbearably hot in the summer and it is always clean and pretty quiet. The main office place is really nice too and so is the gym. So basically everything except the room itself is really nice and it is a five minute bike ride to campus. The rooms are just not cozy. The place feels like it is set up in the middle of a big lot and is just not very homey feeling at all. I see pretty huge spiders in my room at least once a week and tons of cock roaches outside of the rooms. The shower drain clogs ridiculously easy and the apartments are way over priced for the size in my opinion. Having no central air is really annoying because you cant just set a thermostat to what temp you want and leave. You have to turn the window unit on and if you leave it on all day while you are at class then it is freezing when you get back and that is such a waste of electricity. So all in all I would not recommend this place and I cant wait to move out..  Users/RyanKirk

20111006 17:41:13 nbsp When you move out, cancel your PG&E account yourself. They will tell you that they will cancel it for you but they offer this so they dont have to pay the electric bill for the 12 weeks between you moving out and the next person moving in. So cancel your PG&E account the day you move out so they dont scam $10 from you. It was a really douchy move that left a bitter taste in my mouth. Users/MrPeppa

20120918 00:15:12 nbsp I just received a statement from them and what do I see? Them taking my security deposit for painting, which cost $300, when the walls are sparkly white already. In addition, everything was clean, they charge you garbage fee, water fee, and sewage fee (which is understandable) when counting against your security deposit. It is not just the painting but numerous other cleaning fees that they have done.

To add to the fire, this apartment complex outwardly lied to my housemates and I that we infected the apartment with BEDBUGS and that there were no case of it ever before there. They kept accusing us and told us that we had to pay around $2,000 to rid them all of it when WE brought it up to them.
When they said our case was the FIRST case, we find out from the terminator that the people ABOVE us had bedbugs the week before!!! So in addition to them lying to you, THEY ACCUSE YOU of everything so they can pay the least amount as a landlord.

They want to be as profitable as ever since they charge for parking and quite recently added a PREMIUM parking for extra charge. They try to make it so you can feel like they are giving you alot by having random apartment get togethers but really you are paying them a ridiculous amount of money for a dinky apartment while they will outwardly LIE, CHEAT, and SQUEEZE as much money as they can for their tennants.

Their motto is Reinventing the student life when really it really seems like it should be How can we swindle these students from all their money

AVOID AT ALL COST EVEN THOUGH IT IS CLOSE TO CAMPUS IT IS A HORRIBLE EXPERIENCE THERE FROM WHAT NUMEROUS PAST PEOPLE HAVE SAID AND FROM PERSONAL EXPERIENCE. Users/FormerDavisStudent2012

20121011 15:30:12 nbsp Oh, I love living here! All this crap about things people didnt like totally shouldnt dissuade you: its nice, its super safe, its sunny and pretty, and it feels so swanky! Pools, a great gym that it takes you less than a minute to get to, being so close to Trader Joes... I wouldnt have picked anywhere else in Davis. Also, Jessica and Hong are so sweet! And the prices are comparable to all the other weird, less great apartments way the hell away from campus. So, seriously, why wouldnt you live here?! Users/RandomCandor

20130302 23:49:29 nbsp I have lived at University Court for the past 3 years and it has been home for me :)

I absolutely LOVE my room.  I live on the first floor of the south building, Mondavi floorplan.  Its a beautiful place, you have great managers on site, two lounges (one is open 24 hours and the other one, which includes a game room, a pool table, and a computer lounge with free printing, closes at 10pm.  There are two pools, one for each building and they are amazing during the summer!  Yes, I do think that the apartment is on the smaller side.  It is teeny tiny, but I think its cozy.  My room is humongous!  Biggest one bedroom place I have seen in Davis so far and it can be easily split for THREE roommates.  My closet is completely amazing!!  It is one whole wall with fulllength mirrors!  Yes it sucks that they are raising prices (AGAIN), but if you are a student, I think its worth it.  So close to campus, the Umall,the freeway and there are two bus lines right outside (BMU, CSilo).  Water, sewage, and trash is not included, so make sure to pay attention to that and parking is NOT free!  I would have to say that the BIGGEST disappointment of living here is that they are not pet friendly.  I think the management needs to reconsider because animals are great therapy for EVERYONE and I think they can only enhance a students lifestyle.

Like I said, I LOVE my apartment and I am extremely sad that I have to leave, I am graduating in the Fall and its time to move on to bigger and better things.  I HIGHLY recommend living at University Court :)

(I WILL POST AGAIN, AFTER I MOVE OUT TO SEE HOW SECURITY DEPOSIT GOES) Users/GCuentas
