
Walnut Manor offers onebedroom units for $875895/month June 2013, and is located on Unitrans P/Q bus line.

For additional information on rental housing within Davis, check out our Housing Guide as well as our Apartments pages. Go to http://www.apartmentratings.com/rate/CADavisWalnutManor.html for more reviews by tenants.


20060428 17:49:32 nbsp have lived here since Summer of 2003 and had a good experience. small complex, and rent is very reasonable for davis. cathedral ceilings give upstairs apts a spacious feel, and complex is built so that you share only one wall with your neighborthus complex feels private. small backyard with space for gardens. apt mgrs live down the street and are very nice, in most cases very quick to respond to problems. MarisolCortez

20070104 14:36:59 nbsp Marsisol about sharing only one wall.. that is not true unless you have one of the corner units in the back all other units in the complex share two walls with neighbors.  ErinRoss

20100618 17:55:37 nbsp I lived here for several years and was initially satisfied with the complex. When ownership and management changed in 2008, maintenance response time became much slower. For example, under the new ownership/management, it took just about a month after my initial written maintenance request (and an additional inquiry with the manager) to get repairs done on a wornout garbage disposal. During that time period, I was unable to use my kitchen sink because the broken disposal prevented the sink from draining. This incident is only the most dramatic example of a pattern of what I personally considered an unacceptably slow maintenance response. Ive lived in several other Davis complexes, and Walnut Manor under the new ownership/management was far and away the slowest maintenance response time. Thats the reason I chose to move out. Renters looking for an affordable onebedroom might instead consider complexes like Renaissance Park, Portage Bay, and Pepperwood. In my opinion, its worth paying a little bit more for a management team that responds promptly to maintenance issues that impact a residents quality of life. Users/lilygirl

20101208 18:05:06 nbsp I had to sign a lease for an apartment in Davis without even seeing any units since I was moving from across the country and had to start classes as soon as I got here. I researched complexes extensively online and decided that for the price, size, location and reviews (or lack of), Walnut Manor seemed like a decent place to live.(Most complexes with lots of reviews have mostly complaints). I have now been here for a year and a half and its been pretty good living here. I have an upstairs unit with vaulted ceilings and a balcony overlooked by walnut trees. Some of the appliances are pretty old, like the oven and the heating unit, but they work fine and you learn their quirks pretty quickly. The dishwasher was also really old when I moved in, but it broke and has since been replaced with a perfectly working new one. HOWEVER, it took about 3 months to get it fixed! The food disposal in the sink has also broken/stopped working several times, but has always magically started working again while I was waiting for my maintenance request to be fulfilled (once over a month). So again, its just old. The laundry machines break a lot and usually get fixed within a reasonable amount of time. Joel, the onsite manager, is very nice and helpful I think the delay in maintenance is generally the fault of the rental company (Lapham Co). Joel has stopped by to help fix things several times, and even jumped my car one day when I was stranded in the parking lot and had no one else to call! The apartment itself is quite nice (especially if youre an aficionado of dark wood paneling and avocado green countertops), and the paint and carpet both are new. Its a great apartment all said (especially for the price) and any complaints I have are pretty minor overall.  Users/Johnmlambert
