
Often called blue bellied lizards the Western Fence Lizard can be found scurrying about in less populated areas (e.g. South Campus).  These guys are native to all of California except deserts.  They like to sit on elevated objects (like fences) and sun themselves.  They can vary their coloring from light brown to black according to their surroundings and have iridescent blue on their bellies and (on males) necks.

According to the California Academy of Sciences, Western Fence Lizards blood contains a protein that kills the Lyme diseasecausing bacterium.  Apparently the bacteria (Borrelia) is carried in the guts of ticks and can be spread by biting all kinds of animals.  But if an infected tick bites a Western Fence Lizard, the Borrelia is killed off completely, leaving the ticks future bites harmless.  Pretty cool!

Like most lizards, they eat small insects.  You have to be pretty damn quick if you want to catch one, but it is Captain Tuttle possible.  If trying to obtain a free pet, beware.  The tails DO come off.  Also, its not recommended to keep wild animals as pets, as it is stressful for them to adjust their lifestyle and likely that they wont survive the transition.  Most people advise to let them go where they were found rather than risking killing it by improper care. Capturing lizards and other wildlife without a permit is illegal, so dont do it in a way that causes problems or you will probably get caught. http://www.dfg.ca.gov/licensing/specialpermits/specialpermitsdescrip.html has more information on permits offered by the Department of Fish and Game, some of which apply to reptiles.

If you so desire to capture a Western Fence lizard, there are two methods. One involves using a fishing pole, with a loop of fishing line at the end and the other involves using your hands. With the fishing line method, you can construct the fishing line two ways, either to have a length of line extending from the tip, ending in a slipknot, or to have the end of the pole be a loop. The first method is highly recommended, as beginners tend to decapitate the poor lizards by pulling the line in the latter too hard. Now that you have a lizard catching pole, the goal is to first spot a lizard. They are most easily found sunning themselves on top of rocks in the morning, but in some places, like near Cache Creek, can be found easily throughout the day in sunny weather. You want to approach the lizard carefully, preferably slowly, and from behind. Then slowly loop the loop behind its head, and simply lift, with the slipknot, or pull the loop close. Then put the lizard in a critter cage, or other ventilated container. Using your hands to catch a lizard requires a special set of circumstances. If you see a lizard on a tree, facing you, get close enough to wrap your arm around the tree, and stare intensely at the lizard. Itll pay attention to your head. Then quickly, and gently slap your arm around the tree and grab the lizard, gently, then place it into the critter cage. This is the method used in the biology of parasitism class to capture fence lizards for measuring of malaria in their blood.

Captain Tuttle is a Western Fence Lizard one of the few who happened to cope with the transition quite well, he even has his own DWiki page!



This little fellow was hanging on my screen door today.  He is young, about half fullgrown and quite docile. He has already lost a piece of his tail, probably to a neighborhood cat.Users/GrumpyoldGeek



20050805 03:15:02 nbsp Allison, you rock my socks! And now the Western Fence Lizard rocks my socks too...and its all YOUR FAULT!! I miss you, and congrats on ur first page!! Users/AndreHarris

20050905 08:13:36 nbsp Thanks for the info on the lyme disease and lizard blood connection. While doing a creek restoration project (Strenzel Meadow, Martinez) one of the volunteers asked while doing plantings and seeing a lizard, if it was good that it was there! Sharyn  Users/SharynGalloway

20070716 11:32:09 nbsp You can hypnotize a fence swift by turning it on its back and stroking its belly...but be careful not to break the tail!
Do not try to hypnotize an alligator lizard, unless you want to be bitten. Users/K.C.STAUBACH

20100514 00:55:47 nbsp First, it is illegal to keep wild animals as pets! Second, its selfabsorbed and selfentitled  they are not here on earth to be your entertainment. And third you are recommending ways to capture an animal that might  oops, my bad  decapitate him/her. How on earth can you justify taking such a risk with a living being? What a lack of respect. Just leave the lizard in the garden, catching bugs, where he/she belongs. They are very bold and fun to watch in their own habitat, no need to capture, strangle or own one. Users/kering
  there is NO LAW on the books about capturing any animal that is not on the endangered list or not viewed as an exotic animal and there are even fewer animals that are not allowed as pets in general (like a gerbil, how silly). Be accurate in your statements in the future.  Users/WesP

20100819 09:30:26 nbsp I think lizards are super cute(:

btw. its not illegal to keep wild animals such as lizards as pets. It is only illegal to capture an animal that is on the endangered species list.  WF Lizards leave on their own after 24weeks. 63.38% die from being eaten by larger animals.  If you want to catch a lizard as a pet then do it.  Users/yoonmi
  Yoonmis comment was edited and totally unacceptable personal attacks removed.  users/jimstewart

20100819 13:47:11 nbsp See these little creatures all the time along Second St. and also downtown in the Garden corners along the business sections. Users/WesP

20110928 16:08:35 nbsp I came across this in a search for more lizard information and felt compelled to add the following.  First, I am glad that so many people appreciate these wonderful lizards.  Second,Western Fence Lizards also eat other small lizards including each other  not just insects.  And last to correct a comment above  IT IS ILLEGAL TO REMOVE WILDLIFE WITHOUT A PERMIT OR LICENSE.  Ask ANY CA Fish & Game or US Fish & Wildlife warden.  I work at a museum in CA and was a park ranger for many years.  Please do not teach people to remove these lizards or that it is acceptable because so many die.  I know many die  but the more people take out the less will be left to help us with Lyme Disease  and studies have proven how much they help.  And since I was able to access this page through a basic Google search  who knows what 8 or 10 year old saw this and is trying those techniques (more children have internet access than you think).  Unfortunately today when we post things online you have to be aware of all aspects of who would read it.  And when it comes to a lizard that so many people try to catch for fun and can harm in the process... the less they know how to do so the better.  Users/Pyratehawker

20120617 01:11:23 nbsp PyrateHawker says IT IS ILLEGAL TO REMOVE WILDLIFE WITHOUT A PERMIT OR LICENSE. The man talks like a law enforcement guy. They only tell you what THEY want you to know, in order to accomplish THEIR goals (in my experience). This raises questions in my mind. Remove from WHERE? Private land? BLM land? USFS land? Park lands? University lands? And also, whose law is it? I mean, where can I check on the wording? California Law? Federal law? Municipal law? I am not firmly settled in my mind if it can be good or is always bad, to capture lizards. Sure it impacts them. No, that isnt good. Yes, I care. But we impact animals all the time in our culture. Wild and domestic. Can we disturb some species but not others? Suppose my grandson catches a Bluebelly. Suppose he puts him in a comfortable cage and reads about their needs. Suppose he is fascinated by the lizard, maybe he uses a magnifying glass (much like the one in my desk drawer right now from the UCD bookstore back about 1972). He looks at the the scales and how flexible they are. He stares at the little hands so elegant looking. The beautiful eyes. Will he be likely to swerve to miss a lizard running across the road? Or will he pop it like so many people do to matingseason tarantulas, or cats, or toads, or ....? With such a high mortality rate in the wild maybe the lizard will live longer in the cage. Maybe GS will take the lizard to school and tell all about it. Maybe hundreds of people will ultimately be struck by the extreme wonderfulness of lizards, and write a letter both the newspaper editor and to the city council when the BluntNosed Leopard Lizard is being squeezed from his habitat by yet another sprawling subdivision? Maybe the Bluebelly lived for just such an exalted purpose? Users/GeorgeBearden
 I caught probably over a hundred WFLs as a child and released all but one, which didnt end well :( .... In California, a fishing license is required to harvest any reptile unless youre under the age of 16. Heres a link to the DFG webpage: http://www.dfg.ca.gov/regulations/FreshFishMar2012/ccrt14ch2art4sec5_60.html CA Dept of Fish and Game: Reptiles ...The limit with a license is 25, which means theyre a nonthreatened species. That said, they do a lot of good in the environment in terms of eating pest insects. In my experience, they make lousy pets unless you want to teach someone about life and death. I dont think there is any problem with your grand children catching and studying them, but I recommend letting them go ASAP. users/mikeycrews
