Hi XYZ, and welcome to the Davis Wiki. It seems that you are carrying on a correspondence with the managers of an apartment complex, and posting the emails here. This could be a little confusing to other Davis Wiki readers. Perhaps you could summarize your issue in a single comment; or, if you prefer, another Wiki editor could do that for you. Users/DonShor

Heya XYZ!  If you have questions for the management, your best bet is to give them a call or send an email.  It looked like you were posting portions of an email conversation with them on the wiki page, which was, as Don stated, extremely confusing.  If youre looking for a monthtomonth lease, you might check out Ellington Apartments or Davis Townhouse Apartments.  Or just try calling some places up to see what you find.  Most places in town just have yearlong leases, but there are at least a few exceptions.  Users/TomGarberson

People sublet their apartments.  See Rental Housing Guide for more info.
  You need to look at this, it will answer many, if not all, of you strange questions regarding University Commons :  http://cityofdavis.org/cs/mediation/fairhousing.cfm  Davis housing law

UCD does not have to do a single thing about this case, at all. UCD will not be hurt by this in any way shape or form. From the sounds of things, your son signed a 1 year lease, which is standard in Davis, sure it sucks, but thats how things work around here. Telling someone if they dont sign the lease they cant live there is not a threat, its standard business practice. University Commons can lease to who they want how they want and there is such demand for housing here that they dont have to make special lease deals if they dont want to. This is a good example of why its always a good idea to understand what you are signing and agreeing to, before you sign and agree to it. University Commons is under no obligation to find a sublease for this apartment, that all falls on your son to take care of. Hes a big boy now, he can take care of his own messes. This is a great lesson for the both of you. If you honestly feel like you have been wronged, I encourage you to use the many many resources posted earlier by Wes and talk with them about this issue. If half of what I can decipher about this issue is true though, you probably dont have a case, but you should still try if you feel you have been wronged. Users/R.W.

What is your primary language? It was asked before, but it looks like youre using Babelfish or something similar to translate to English.  Users/masonmurray MM
