
Currently the Yolo County District Attorney is Jeff Reisig.  He is in charge of representing People the people on cases from Davis and most of UC Davis, along with over twenty departments that comprise the DAs office.

Note that this office cant give you legal advice (probably because theyd be the ones prosecuting you).  See Law Firms for that.

 Previous DAs 

  Dave Henderson

Also see Juvenile Justice System for the DAs role in the handling of juvenile offenders in Yolo County and Davis Neighborhood Court for their new restorative justice program.


20060726 15:17:59 nbsp Some good news from the District Attorneys office.  Two years ago a goat rancher of middle eastern descent in Yolo County was given 170 misdemeanor citations after his goats got out and wandered off. A citation was given for each goat by Yolo County animal control.  This week, on the eve of going to trial,and after the Goatman hired Attorneys Gonzalez and Leigh, the DDA decided not to prosecute and dropped the case, saying that they had more serious criminal matters that they needed to focus on.  I say, Great call! Users/SharlaDaly

20060727 22:37:06 nbsp More good news out of the District Attorneys office regarding the Woodland 19year old that was fooling around with fireworks in his garage and was charged with multiple felonies having to do with making bombs. The boy received support from the community, who felt it was obviously a ridiculous case from the very beginning and a stern warning wouldve sufficed. The DAs Office agreed to drop all the felonies and allow him to plead to one misdemeanor charge of possessing illegal fireworks.  He does community service, gets counseling, and is on probation for a year.  If he stays out of trouble, then it all goes away in a year.  This allows him to go back to college in the Fall and eventually get out of the system.   Measured and fair handling by David Rosenberg Judge Rosenberg. The boys attorney was Steven Sabbadini.  Users/SharlaDaly

I agree the end result was measured and fair, but isnt that what the Justice System is supposed to be all about? The end result was good news, but I still think the kid was mistreated along the way. We need to at least consider what went wrong. The original police conclusions (charges) were completely out of line with the conclusions of the DA, the Judge and the Defense. The later conclusions were not based on new (different) information so why were the original charges so greatly exagerated. Perhaps the Woodland Police just had a bad day, but on the other hand Davis Police Officers do the same thing and far more frequently than Woodland Police Officers. In this particular case the original errors were overcome, but the police action subjected the kid to unnecessary risk. What if the deputy DA assigned to the case had a personality conflict with the defense attorney or what if the kid had Middle Eastern ancestry? Would the result have been the same or would that kid continue to face felonies and prison?
A well respected exdeputy DA in San Mateo County told me the more you get to know the Justice System the more you will dislike it I lived 50 years of my life respecting the Justice System and believing in it. Then I heard the comment I mentioned above and experienced the flawed system in Yolo County (mostly Davis Police dishonesty). I no longer have the respect for the Justice System I once had. If people really want justice they need to pay substantial attention to their local police department and the District Attorneys office. Steve Hayes


20090327 10:40:03 nbsp We had asked Yolo district attorney, Dave Hendersen, in June 2005, to investigate how/why superior court Presiding Judge, Donna Petre, the Yolo supervisor´s (Yamada, Chamberlain, McGowan, Thomson), Acting Probation Chief Roberto Gonzales and then county council, now Judge Steve Basha, concurrently appointed Chief Don Meyers from Calaveras county at the same time that Chief Meyers was involved in obstructing an investigation into allegations of a scheme by a group home employee, the sheriff´s and probation department to orchastrate the arrest of an Alameda county foster youth who is an Honduran national, because his type doesn´t belong in the county (one of a dozen documented allegations). DA Dave Hendersen refused to investigate these allegations and presiding Judge Donna Petre, who earlier appointed Chief Meyers, and who later in the court´s role with the county grand jury wrote us a letter stating the GJ won´t investigate as the allegations took place prior too and in another county than Yolo. Even though Yolo official´s were forwarded documents that showed the racketeering conspiracy before employing Chief Meyers.

Yolo official´s counterparts in Calaveras who stated in writing and public sessions that we´d have an independent investigation which was obstructed by the Calaveras supérvisor´s who also authorized Chief Don Meyers to handpick the county probation department to investigate Chief Meyers, Allan Sullivan and Rich Manders. Meyers started in Tuolumne where Asst. Chief PO, Tom Greene, sat idle by as Chief Meyers scripted the investigation in writing to a state licensed group home. When ACPO Tom Greene was contacted by mail and phone Greene stated he knew nothing of the actual investigation and then Greene vanished from the investigation. Chief Meyers then went to his 20+ year former employer, Sacramento probation department, where Meyers had just left that agency to Calaveras 14months prior. Sac. Asst. CPO, Susan Collins, accepted the investigation even though we countered ethics concerns, once we documented and faxed those issues ACPO Susan Collins, backedout of the investigation that same day in writing w/o explanation. Chief Meyers, with 54county´s left to investigate opted to return to Calaveras county and have subordinate DPO III, Teri Hall, falisfy the investigation.

DA Hendersen and his sucessor, DA Jeff Reisig, have refused to investigate a pltheora of allegations that interfered with our lawful right to serve state foster youth.

Now assemblyperson, Mariko Yamada, has refused several emails asking for a public explanation.

The issues included two Calif False Claims Act cases which are now infront of the five original county grand jury´s that we were told to contact by county official´s in 2005 (Calaveras, Yolo, Tuolumne, Merced and Sacramento)and last year the US attorney´s office in the Northern/Eastern districts of Calif) every county grand jury in 2005/06 violated state statues with the exception of Yolo by failing to acknowledge the complaint and state whether they will investigate or not.

Attorney general, Jerry Brown, through several attempts through the public inquiry unit, personal lobbying of Brown and his wife, Anne Gust, a special prosecutor at the AG´s office along with asst. attorney general, Peter Smith, also a former Calaveras district attorney, all refused to intervene. Later, Jerry Brown refused to intervene in two Calif FCA cases.
 Users/jakewallace
